code/modules/projectiles/guns/launcher/grenade_launcher.dm

Revert "Debug"

---

code/modules/projectiles/guns/projectile/automatic.dm

Revert "Debug SMG"

---

code/_helpers/game.dm

Revert "Disabled recursive content check."

---

code/modules/projectiles/projectile/bullets.dm

еб твою мать, ща бы путать пуллреквесты с коммитами

И пофиксил статы пары прожектайлов по реквесту шепарда

---

code/_helpers/text.dm
code/game/machinery/alarm.dm
code/modules/nano/nanoui.dm
code/modules/power/apc.dm

База фикса наноУИ.

---

code/game/objects/structures/musician.dm

Поднял число симолов на пианино

---

code/modules/projectiles/guns/projectile/revolver.dm

Изменен тип заряженных в револьвер патронов у инспектора при спауне.

Револьверофиксы.

---

interface/skin.dmf

Adds the standard hotkey mode from Bay. Shouldn't have any issues. As a ghost, page-up and page-down should allow you to move up and down a z-level in hotkey mode as well.

Hotkey Mode

---

code/modules/mob/living/bot/farmbot.dm

Забыл про фарбота в прошлый раз.

Farmbot sounds and speeches.

---

code/game/machinery/adv_med.dm
code/game/machinery/alarm.dm
code/game/machinery/computer/camera.dm
code/game/machinery/computer/cloning.dm
code/game/machinery/computer/computer.dm
code/game/machinery/computer/crew.dm
code/game/machinery/computer/guestpass.dm
code/game/machinery/computer/medical.dm
code/game/machinery/computer/security.dm
code/game/machinery/cryopod.dm
code/game/objects/structures/catwalk.dm
code/modules/multiz/turf.dm
code/modules/power/apc.dm
code/modules/virus2/curer.dm
code/modules/virus2/diseasesplicer.dm

Сменил цвет машинерии по запросу Шепарда.
Задал (почти) минимальное значения света на настенных приборах, которые успел заметить, а так же немного почистил вилкой свет в остальной машинерии.
Так нашёл ультимативный фикс со светом на опенспейсовом тайле. Возможно оно поправит ещё какие проблемы, а может ещё какие добавит.

[READY] Чистим вилкой свет

---

code/game/objects/structures.dm
code/game/objects/structures/railing.dm

- Сделал перила чуть крепче, а то от двух ударов ломом падают, как из пенопласта.
- Создаваемые перила, через метал, не должны сразу закрепляться на полу. Вроде.
- Проверка на density должна пресечь беготню по стенам и прочим непроходимым турфам.

more railing tweaks

---

code/modules/mob/living/bot/cleanbot.dm

fantastic changes and where to find them

---

code/_onclick/item_attack.dm
code/modules/mob/inventory.dm

obj/item now have pixel_x/y laying on table

---

code/modules/clothing/spacesuits/spacesuits.dm

Now you can input oxygen tank in spacesuit slot.

---

code/datums/uplink/uplink_items.dm
code/modules/clothing/spacesuits/spacesuits.dm

Deleted uplink purchase log.

---

code/datums/supplypacks.dm
code/game/objects/items/stacks/tiles/tile_types.dm
code/game/turfs/flooring/flooring.dm
code/game/turfs/space/space.dm
code/modules/materials/material_recipes.dm
code/modules/mob/living/bot/floorbot.dm
code/modules/multiz/turf.dm

Хоть он немного туп и медлителен, за то работает с нашими полами. Создает плитку в зависимости от заданной декали, а если её нет - серый пол. Так же заделывает опенспейсовые дырки, если на них есть lattice.
В емагнутом состоянии разбирает вроде всё, даже Аллаха.

Floorbot prepared for our turfs

---

code/modules/mob/living/carbon/human/examine.dm

В коммите не верный номер. Фикс рантайма 526.

Probably fix #526

---

code/game/objects/items/weapons/grenades/grenade.dm
code/game/objects/items/weapons/tools.dm
code/modules/mob/living/carbon/human/human_attackhand.dm
code/modules/mob/living/carbon/human/update_icons.dm

Как пользоваться этой хуйнёй:
С помощью окошка раздевания человека вы пихаете ему в слот маски гранату, после чего переключаетесь на харм, целитесь ему на ротик, и бьёте! *Отсчет пошел.*

Grenades ported from Polaris.

---

code/modules/mob/living/carbon/human/human.dm

Меню теперь окончательно сломано

Revert "Fix #554. Readable names in stripping menu."

---

code/game/gamemodes/cult/ritual.dm
code/modules/mob/emote.dm
code/modules/mob/living/carbon/alien/emote.dm
code/modules/mob/living/carbon/human/emote.dm
code/modules/mob/living/carbon/human/examine.dm
code/modules/mob/living/carbon/human/unarmed_attack.dm
code/modules/mob/living/carbon/human/whisper.dm
code/modules/spells/spell_code.dm

Grenades in mouth!

---

code/game/turfs/simulated/floor_types.dm
code/game/turfs/space/space.dm

Now catwalks are buildable on underplating, by clicking on underplating, while holding rods in active hand.
Also, Russian commentary was found and translated to English.

Catwalks and some fixes.

---

code/modules/mob/mob_movement.dm
interface/skin.dmf

Порт штучки связанной с передвижением мобов с бэя, оригинально сделанная на ТГ.
Не уверен, не сломало ли это всё, но после маленького теста на локалочке ничего такого подозрительного не заметил.

Port movement smooth

---

code/modules/mob/new_player/login.dm

- Now lobby music starting faster than 4 seconds.

Make lobby music start faster

---

code/game/atoms_movable.dm
code/modules/client/client defines.dm
code/modules/mob/mob_movement.dm

- Finally mobs got smooth movement like on tgstation movement gliding. Fixes #626.
- This pull fixes jerking parallax what we seen before.
- After merging, host-side configuration must be updated.

Movement tweak

---

code/game/atoms_movable.dm
code/modules/client/client defines.dm
code/modules/mob/mob_movement.dm

- Reverts Endless-Horizon/CEV-Eris#637, because i got one important issue about smoothing gameplay on other clients.

Revert "Movement tweak"

---

code/modules/multiz/controller.dm

Openspace icon record lowered turf dir

---

config/example/config.txt

Подчистил конфиг на Сильвере и решил залить сюда, дабы потом не проебать

some config changes

---

code/game/turfs/simulated/floor_types.dm

BANG when running across underplating

---

code/modules/client/preference_setup/general/01_basic.dm

These changes definitely needed for https://github.com/Endless-Horizon/CEV-Eris/issues/660 implementation.

Implement religion selection in character preferences

---

code/game/turfs/turf.dm
code/modules/mob/living/living.dm
code/modules/power/gravitygenerator.dm

* Gravity generator no more flood off announcemets
* Footsteps not playing, if you run in the wall

Gravity generator and footstep fix

---

code/game/gamemodes/changeling/changeling_powers.dm
code/game/gamemodes/changeling/modularchangling.dm

Remove "change species" changeling power

---

code/game/jobs/job/security.dm

Medspec access for Ironhammer Commander.

---

code/modules/core_implant/cruciform/cruciform.dm
code/modules/core_implant/cruciform/rituals.dm

Install ritual fix
Remove_cyber fix

Cruciform and rituals forkcleaning

---

code/modules/mob/living/say.dm

Fixed troubles with ":ы"

---

code/game/atoms.dm

Fixed excess dot in object name when examining

---

code/modules/mob/hear_say.dm

Fixed double naming for ghosts. Close #860.

---

code/game/machinery/doors/door.dm
code/game/machinery/doors/multi_tile.dm

- Now airlock opacity will change correctly while opening/closing
- Little changes of code formating in `doors/multi_tile.dm`

Airlock opacity fix

---

code/game/jobs/job/captain.dm
code/game/jobs/job/civilian.dm

Asters have more money from roundstart and payday.

---

code/game/antagonist/antagonist_create.dm
code/modules/paperwork/paper.dm

Remove Clown Job reference

---

code/game/jobs/jobs.dm

Remove unuesed proc get_job_datums()

---

code/game/verbs/ooc.dm

OOC color preference now recolor only ckey, not whole message.

---

code/game/verbs/ooc.dm

Our server rules don't forbid that.

Advertising check removal.

---

code/game/antagonist/antagonist.dm
code/modules/admin/topic.dm

Fix jobban panel formating and simplify code. Fix #963

---

code/game/machinery/alarm.dm
code/game/machinery/machinery.dm
code/modules/security levels/security levels.dm

More machinery will use it in future.

Sec levels now adjusted on all machinery, not just on fire alarms.

---

code/modules/core_implant/cruciform/inquisitor.dm
code/modules/core_implant/cruciform/rituals.dm

No more "lol kek cheburek" in holy book.

Replacing placeholders in rituals.

---

code/game/objects/structures/crates_lockers/closets/secure/medical.dm

Ради этого стоило делать отдельный бранч, да.

Medical Belt

---

code/modules/projectiles/gun.dm
code/modules/projectiles/targeting/targeting_triggers.dm

Removing help intent check for firing guns.

---

code/game/machinery/doors/blast_door.dm
code/game/machinery/doors/windowdoor.dm
code/game/machinery/portable_turret.dm
code/game/mecha/combat/durand.dm
code/game/mecha/combat/gygax.dm
code/game/mecha/working/ripley.dm
code/game/objects/structures/displaycase.dm
code/game/objects/structures/window.dm

Windows are no more stronger than most mechs.

Rebalancing HP of structures and mechs.

---

code/modules/mob/mob_grab.dm

Better grab messages.

---

code/game/objects/structures/mop_bucket.dm

Working overlay for bucket. Close #1102

---

code/game/objects/items/weapons/material/knives.dm
code/game/objects/items/weapons/material/misc.dm
code/modules/cargo/export_scanner.dm

Some fixes for damage and energy balance.

---

maps/CEV_Eris-1.dmm

Missing pipe in engine.

---

code/modules/surgery/generic.dm

hemostate no longer using welder sound

---

code/game/jobs/job/security.dm
code/game/machinery/recharger.dm
code/game/objects/items/weapons/stunbaton.dm
code/game/objects/structures/crates_lockers/closets/secure/security.dm
code/game/objects/structures/watercloset.dm
code/modules/mob/living/silicon/robot/robot_modules.dm

Stunbaton now use new cells.

---

code/game/objects/items/weapons/power_cells.dm

Tested in game. everything fine.

Nuclear cells now working.

---

code/game/machinery/computer/communications.dm

More appropriate messages for pod launch in comm console.

---

cev_eris.dme
code/modules/clothing/head/misc_special.dm
code/modules/clothing/masks/balaclava.dm
code/modules/clothing/masks/boxing.dm
code/modules/clothing/masks/breath.dm

Balaclava now have its own file and can be adjusted by verb.

---

code/game/objects/items/weapons/space_harpoon.dm

Space harpoon now use M cells instead of cooldown.

---

code/modules/mob/inventory.dm

Fixing stupid mistake that broke inventory.

---

maps/exodus/test_map.dmm

Testmap is no more outdated

---

code/modules/mob/living/bot/cleanbot.dm
code/modules/mob/living/bot/floorbot.dm
code/modules/mob/living/bot/medbot.dm
code/modules/mob/living/bot/secbot.dm
code/modules/mob/living/simple_animal/hostile/bear.dm
code/modules/mob/living/simple_animal/hostile/carp.dm
code/modules/mob/living/simple_animal/hostile/roach.dm
code/modules/mob/living/simple_animal/simple_animal.dm

They will no longer shit all over deadchat and server logs.

Bots and mobs now use proper proc for their emotes.

---

code/game/objects/items/weapons/tools/weldingtools.dm

todo rewrite repairing code:
1) Move repairing code from `cable_coil/after_attack` -> `cable_coid/attack`
2) Get in account new tool system

Fix prosthesis repairing (weldingtool)

---

code/game/gamemodes/storyteller.dm

if there is less than 10 players on the server

Storyteller will let round to start without cap and engie

---

code/modules/modular_computers/file_system/programs/ntnrc_client.dm

NT Relay chat я fix

---

code/game/turfs/turf_changing.dm

Fix: shuttle movement don't update Open Space

---

code/game/machinery/computer/computer.dm
code/game/machinery/constructable_frame.dm
code/game/machinery/navbeacon.dm
code/game/machinery/suit_storage_unit.dm
code/game/objects/items/devices/powersink.dm
code/game/objects/items/weapons/explosives.dm
code/game/objects/structures/tank_dispenser.dm
code/game/objects/structures/watercloset.dm

Updating some attackby procs.

---

code/modules/admin/IsBanned.dm

Trying to fetch ban record for bo20202 but got error: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'OR ip = '1234'  OR cid = '1234'  AND (type = 'PERMABAN' OR (type ' at line 1.

Fix ban error

---

nano/templates/sec_camera.tmpl

Better fix - upadte both code and template. Will be done later

Temporary fix for sec camera console

---

code/game/objects/items/devices/PDA/PDA.dm

Adds altclick() for taking ID out of PDA.

---

code/game/machinery/autolathe.dm
code/game/objects/items/weapons/autolathe_disks.dm
code/game/objects/items/weapons/mine.dm
code/modules/core_implant/cruciform/machinery/cloning.dm
maps/testmap/test_map.dmm

* Autolathe can print without a beaker now
* Excelsior mine do not require material caller "MATERAIL_STEEL"
* Excelsior disk no more calls "Security" in the autolathe
* Full neotheology cloner rework

Fix of various bugs catched on the 8 apr test launch

---

code/game/jobs/job/security.dm
code/game/objects/structures/crates_lockers/closets/secure/security.dm
code/modules/admin/verbs/debug.dm
code/modules/clothing/under/jobs/security.dm

Inspector uniform sensor's fix.

---

code/modules/mob/living/carbon/human/human_hud.dm

Fix miniUI issue

---

code/game/objects/explosion.dm
code/global.dm
code/modules/admin/verbs/atmosdebug.dm
code/modules/admin/verbs/debug.dm
code/modules/power/power.dm
code/modules/power/powernet.dm

I only did those tests: 
* since i'm not very familiar with the build and a bit lazy into proper engine setup process, i simply spawned some pacmans in engineering and apc + smesses had no problems with charging process, so i hope everything works now.
* used admin button Make Powernets in mid charging stage.

Fixed issue with no powernets getting into new controller.

---

code/game/objects/effects/chem/chemsmoke.dm

This was requested as a counter-measure until someone comes with a proper way to fix this issue.

Workaround for broken lighting after a lot of smoke gets created and destroyed.

---

code/game/gamemodes/gameticker.dm
strings/quotes.txt

Lobby quotes.

---

code/__defines/machinery.dm

No more 5 min afk in airlock to go into open space.

Speeds up pumping process, mainly to boost airlock cycle process.

---

code/modules/admin/verbs/buildmode.dm

It now works with it. That's all.

Fixing buildmode on open space. Close #291

---

code/_helpers/icons.dm
code/modules/admin/map_capture.dm
code/modules/paperwork/photography.dm

* Disabled lighting overlays for photos (nothing much to do here or i have no idea if it possible to make them properly to be rendered after icon operations).
* Nerfed photo size selection to 1 and 3, because 5 and 7 takes too much CPU with icon operations, especially Blend() proc which is server side operation that makes icons in real time.
* Added flash effect when taking photos (lights area around user with camera for a very short period of time).

Fixed some camera/photography issues.  

---

code/controllers/master.dm
code/controllers/master_controller.dm

* No more double or even triple msg prints.

Resolved initialization message spam.

---

code/game/turfs/turf.dm

* Should properly apply/reset animation when needed.

Fixes floating animation bug related with gravity checks under mob. 

---

code/_helpers/unsorted.dm
code/modules/lighting/lighting_system.dm

Fixes "Persistent runtime at roundstart"

---

code/game/objects/structures/railing.dm

- fixes #1581 
I did put the cooldown in this individual case, doing so, I have found out, that basically no subtypes of /obj have the cooldown installed, unless individually put in.

Fixed lack of cooldown on railings.

---

code/modules/mob/mob.dm

* resolves #1264 - this was actually true for any mob (even lying human).

Fixes issue where lying mob drawn over standing mob.

---

code/game/objects/effects/spiders.dm
code/game/objects/random/mob/roach.dm

They are now fixed enough for that.

Return of gas roaches and less omnipresent spiderlings.

---

code/modules/mob/living/carbon/human/human_attackhand.dm
code/modules/reagents/Chemistry-Reagents/Chemistry-Reagents-Dispenser.dm

* Hand punch damage was lowered a bit.
* Robustness now should help resist alcohol.
* Alcohol now less dangerous, you would need to drink much more for poisoning.

Some stat fixes.

---

code/game/objects/items.dm
code/modules/reagents/Chemistry-Reagents/Chemistry-Reagents-Dispenser.dm
code/modules/surgery/surgery.dm

Explosion effect are now more rare. You also can drop tool, stuck it in your hand, or throw it away by accident.

More critical fails for tools.

---

code/game/objects/effects/decals/misc.dm

This PR Fixes pointers being on the wrong plane and thus hidden behind most objects

Pointer Plane Fix

---

code/modules/core_implant/cruciform/machinery/cloning.dm

- Fixed cloning time
- Fixed bone printing animation

Fixed neoTheology clonpod

---

code/modules/mob/living/carbon/human/human_defense.dm

-Add damage absorb check for spawning sharapnel (now if 100% damage has been absorbed sharapnel is not spawn)
P.S. If you'll see spelling mistakes... Sorry!

Small fix for damage system

---

code/hub.dm

Allows the server to go on the hub.

Servers now goes on the hub

---

code/game/objects/random/booze.dm
code/modules/economy/price_list.dm

There is no such thing anymore. It was deleted long time ago, but someone left it here.

Removing some redundant booze.

---

code/modules/mob/living/simple_animal/simple_animal.dm

Fixed simple_animal's revive problem #1909
Removed useless code

Rejuvenate fix

---

code/modules/recycling/disposal.dm

Stuffing mobs into disposal now based on their size #1904
Forcing the user to face a disposal at the end

Disposal stuffing fix

---

code/game/antagonist/station/changeling.dm
code/modules/core_implant/cruciform/machinery/cloning.dm
code/modules/core_implant/cruciform/rituals/priest.dm

Changelings now gibs at baptism ritual #1859 
Сyberсhristians cannot be the changeling #1859 
Cloner now consumes the biomass #1842

Another theology fixes

---

code/game/objects/items.dm
code/game/objects/items/robot/robot_parts.dm
code/modules/mob/living/silicon/robot/robot.dm

Reduse copypasta, add deconstrucion code.

Update robot_suit building

---

code/game/objects/items/weapons/storage/backpack.dm
code/modules/admin/bluespacetech.dm

Cleans up code and fixes bugs introduced by #1939
Check the Files Changed tab for explanation of changes
I spotted these bugs as soon as i looked, but the PR was already closed by then. It was opened, merged and closed within the span of a single hour. Please don't do that

Backpacks fix

---

interface/interface.dm
interface/skin.dmf

Fixes a wrong macro.

---

code/game/objects/structures/window.dm
code/modules/materials/materials.dm

Window Bugfixes

---

code/modules/shield_generators/shield.dm

solution for that #2017 
Fixes #2017

Shield atmospheric fix

---

code/modules/projectiles/guns/projectile/pistol/lamia.dm

fixes https://github.com/discordia-space/CEV-Eris/issues/2020

Fixed typo.

---

code/ATMOSPHERICS/he_pipes.dm

fixes https://github.com/discordia-space/CEV-Eris/issues/2021

Fixes heat exchange pipe junction thermal conductivity

---

code/modules/overmap/ships/computers/helm.dm

fixes https://github.com/discordia-space/CEV-Eris/issues/2115

Fixes helm control being unable to view saved coordinates

---

code/controllers/evacuation/evacuation.dm

fixes https://github.com/discordia-space/CEV-Eris/issues/2110

Fixes evac alert recognition of eris hallways

---

code/modules/materials/materials.dm

fixes https://github.com/discordia-space/CEV-Eris/issues/2059

Fixes building reinforced glass full windows

---

code/game/machinery/cryopod.dm

fixes https://github.com/discordia-space/CEV-Eris/issues/2060

Fixes runtime during despawn in cryopod

---

code/modules/clothing/spacesuits/rig/rig_attackby.dm

fixes https://github.com/discordia-space/CEV-Eris/issues/2009
Only point 1. is related to rigs.
2. 3. are fixed by upcoming inventory rework.
4. modules function, except vision altering ones which still do not function
5. was not a bug to begin with, internals can be toggled by fully deploying the hardsuit and clicking the O2 icon on hud.

Fixes tool interaction based on tool quality for rig suits

---

code/modules/mob/living/silicon/robot/gripper.dm

fixes https://github.com/discordia-space/CEV-Eris/issues/2117

Adds more trash to service gripper

---

code/game/objects/items/weapons/RCD.dm

fixes https://github.com/discordia-space/CEV-Eris/issues/2026
Cost for reinforced wall deconstruction is doubled, time to completion is tripled, compared to regular walls.
Resources are now used up only after successfully completing construction/deconstruction.

RCD fixes and changes

---

code/modules/overmap/ships/computers/helm.dm

fixes https://github.com/discordia-space/CEV-Eris/issues/2111

Enables AI to see the overmap using helm control

---

code/game/machinery/alarm.dm
code/game/machinery/spaceheater.dm

Air alarm thermostat now works. Air alarm is now 3x as good at heating and cooling, which is still really bad. I've shortened the specific heating/cooling messages because they were wrong half the time and just added chat spam.
Space heater now uses large cells, starts with a 5k rating cell and uses 10% of the power. This makes it last approximately 20minutes.

Fixes thermostat and rebalances space heater

---

code/ATMOSPHERICS/components/unary/vent_scrubber.dm

There's hundreds of scrubbers, setting them manually every round is a mindless chore.

Sets scrubbers to filter all harmful gases by default

---

code/_helpers/lists.dm

It seems this got lost when ghost was repairing my maintenance PR
The old way can't account for decimal weights
fixes #2190

Random Runtime Fix

---

code/game/objects/items/weapons/power_cells.dm
code/modules/power/cell.dm

Power cell icon_update was the second most cpu intensive operation according to profiler. This puts it much lower.

Fixes power cells needlessly updating icon

---

code/modules/reagents/Chemistry-Reagents/Chemistry-Reagents-Core.dm

Temporary fix until chem rework.

Makes water always extinguish mob

---

code/controllers/subsystems/garbage.dm

No information is lost with this change.

Changes GC failure to use log_to_dd instead of crash

---

code/modules/clothing/gloves/stungloves.dm
code/modules/power/cell.dm

fixes https://github.com/discordia-space/CEV-Eris/issues/1994
Fixes some 4am coding ideas.

Fixes stungloves cell compatibility

---

code/game/sound.dm

Reverts discordia-space/CEV-Eris#2214
reverted by request, the fix may be hiding a broader issue

Revert "Fixes runtime in sound.dm"

---

code/modules/reagents/reagent_containers/food/drinks.dm
code/modules/reagents/reagent_containers/food/drinks/bottle.dm

A mechanic that would allow to drink the entire bottle/glass up, in one go. To do so, use the verb in right click.

Drinking it all up mechanic.

---

code/modules/client/preference_setup/loadout/loadout_general.dm
code/modules/client/preference_setup/loadout/loadout_mask.dm
code/modules/client/preference_setup/loadout/loadout_suit.dm
code/modules/client/preference_setup/loadout/loadout_utility.dm

A small package of things to make custom loadout items more interesting:
Adds cyberchristian prayer book, highly requested
Reduces cost of boot knife, weapons arent hard to find on eris
Reduces cost of tablets, we need to see more of these
Adds crowbar and flashlight as options. Commonly needed tools

Loadout Tweaks

---

code/datums/wires/wires.dm

Anything done with wires is logged, and can be viewed in View Variables --> wires --> wire_log.

Logging wire interactions.

---

code/game/objects/items/apc_frame.dm

fixes https://github.com/discordia-space/CEV-Eris/issues/2224

Fixes APC frame iconstate

---

code/datums/craft/recipe.dm
code/datums/craft/step.dm

fixes https://github.com/discordia-space/CEV-Eris/issues/2213
Removed default flags for recipes.

Adds multiple sanity checks for crafting

---

cev_eris.dme
code/__defines/reagents.dm
code/game/machinery/bioprinter.dm
code/game/machinery/cloning.dm
code/modules/core_implant/cruciform/machinery/cloning.dm

biomass reagent list

---

code/modules/ghosttrap/trap.dm
code/modules/mob/living/carbon/brain/posibrain.dm

Also fixes wrong `MayRespawn()` call in `assess_candidate()`

Remove respawn timers for posibrains (closes #2109)

---

code/modules/clothing/clothing.dm

Also fixes possible runtime and grammar error

Adds ability to draw bootknife via leftclick

---

code/game/objects/items/weapons/shields.dm

Previous sprite was an ugly red plastic shield. Handmade shield is made out of wood and metal, this represents that.

Change handmade shield sprite

---

code/game/machinery/machinery.dm
code/modules/power/power.dm

auto_use_power() is now about 30% faster.
No functionality changed.

Optimization for few power procs

---

code/game/atoms.dm

If container of another atoms is to be deleted they appear coordinateless.

removed logging of missing coords

---

code/controllers/configuration.dm
code/controllers/master.dm
code/controllers/subsystems/ticker.dm
code/modules/mob/living/carbon/human/human_movement.dm
code/modules/mob/living/carbon/human/species/species.dm
code/modules/mob/living/carbon/metroid/metroid.dm
code/modules/mob/living/silicon/robot/robot.dm
code/modules/mob/living/silicon/robot/robot_movement.dm
code/modules/mob/living/simple_animal/simple_animal.dm
code/modules/mob/mob_movement.dm
code/modules/vehicles/cargo_train.dm
config/example/config.txt
config/example/game_options.txt

* Removed the FPS config value. It's literally the same purpose as tick lag except worse objectively and having both makes no sense.
* All movement speed config values are gone. Good riddance.
Also removes the movement speed hacks necessary due to stupid config defaults.

Configuration spaghetti improvements.

---

code/modules/mob/living/carbon/human/inventory.dm

Fixes deleted items not being removed from your UI

Inventory Deletion Fix

---

code/game/objects/effects/chem/water.dm
code/modules/reagents/Chemistry-Reagents/Chemistry-Reagents-Core.dm

Water effect now evenly applies to all mobs on a tile.

Fixes water not damaging slimes

---

code/modules/mob/living/carbon/superior_animal/defense.dm
code/modules/mob/living/carbon/superior_animal/giant_spider/types/nurse.dm
code/modules/mob/living/carbon/superior_animal/superior_animal.dm

Fixes runtime in nurse.dm

---

code/modules/client/client procs.dm

fixes players getting kicked for no reason

AFK Kick Fix

---

code/datums/craft/recipes/floor.dm
code/game/objects/items/stacks/rods.dm

Constructing "grille" is now happens with craft_menu, self_attack no
more make lattice under your legs.
Resolves #2376 .

Rods now open craft menu on attack_self()

---

code/modules/admin/bluespacetech.dm

Code cleanup in one place which was mentioned in issues. Resolves #2221 .
Any runtimes weren't captured.

Code cleanup.

---

code/game/objects/items/weapons/storage/pouches.dm

added a pistol to the holster which was not on the list

fixed holster

---

code/game/objects/items/weapons/tanks/jetpack.dm

Fixes constant spam of found rig jetpack

Jetpack Spam Fix

---

code/game/gamemodes/roleset/secdoc_hunters.dm

Secdoc Hunter Runtime

---

code/game/objects/items/weapons/tools/_tools.dm
code/game/objects/items/weapons/tools/mods/mod_types.dm

Fixes the expanded fuel tank toolmod not being able to be filled

Auxiliary Fueltank Fix

---

code/modules/client/preference_setup/general/01_basic.dm

Pref religion save fix

---

code/game/turfs/flooring/flooring.dm

Fixes for new floors.

---

code/datums/uplink/uplink_items.dm
code/game/objects/items/devices/uplink.dm
maps/CEVEris/centcomm.dmm

Finishes up a feature that didn't make it into the initial release, the team uplink beacon for mercs. Its anchored on their ship and has a large pool to request supplies with
also removes all debug messages from uplinks

Merc Uplink Beacon and Fixes

---

code/controllers/subsystems/ticker.dm
code/modules/admin/verbs/randomverbs.dm
code/modules/client/preference_setup/loadout/loadout.dm
code/modules/mob/new_player/new_player.dm

fixes missing pda/id when using custom jumpsuit, disappearing items when cant store them, and might fix spawn in space
fixes #2510

fixes spawn bugs

---

code/modules/modular_computers/NTNet/NTNet.dm
code/modules/modular_computers/computers/modular_computer/core.dm
code/modules/modular_computers/computers/modular_computer/interaction.dm

email login fix

---

code/game/objects/items/weapons/storage/pouches.dm

Holster can now contain more types of pistols.

---

code/modules/hydroponics/seed_storage.dm

New PR to get rid of all those stupid excess commits.
Seed storages now properly load their content on initialization, instead of only loading if they're interacted with but not yet initialized, which was literally never happening.

Makes seed storages initialize properly, improves code formatting

---

code/game/machinery/telecomms/machine_interactions.dm

They were both triggering on a single action. now they won't.

Adds else ifs to telecomms machine deconstruction steps

---

code/modules/mob/living/carbon/human/examine.dm

Fix robotic limbs descriptions typo.

---

code/modules/core_implant/cruciform/machinery/cloning.dm

"clonpod" -> "clon**e**pod"
Issue #1648

Fix clonepod name

---

code/_onclick/cyborg.dm

Fixes turf-airlock click feature for borg

Borg QOL door fixes

---

code/game/machinery/adv_med.dm

Should Fix #2651. Just adds Cruciform to the Known Implant list.

Fixs Cruciform now Showing up in Body Scanner

---

code/game/antagonist/outer/mercenary/mercenary.dm

Antag debug message accidently came to master, it is time to clear it off

Debug massage fix

---

code/game/objects/items/weapons/tools/_tools.dm

fixes #2647
While this does fix the issue at hand, it would screw with how the progress bar is displayed, perhaps even to the better, since now progress bar will be displayed over the thing you are manipulating instead of over you.

Applying tools does check if target moved.

---

code/game/machinery/excelsior/autolathe.dm
code/game/objects/items/weapons/circuitboards/machinery/excelsior.dm

Fixes the excelsior autolathe not working properly when manually constructed

Excelsior Autolathe Fix

---

code/modules/reagents/recipes.dm

I have taken a very simple approach to solve #2575, is just outright ban these recipes inside the mob.
Perhaps a better solution would be to force a mob to ingest whatever has been created as a result of such recipe. That I leave for a judgement of somebody else.

No more shitting meatballs upon consuming protein and flour.

---

code/modules/core_implant/cruciform/rituals/group.dm
code/modules/core_implant/ritual_book.dm

current_category wasn't set to "Common" or something sane. The fix might be good, but that's up to you for reviewing.
Fixes: #2469 
🆑 TorinoFermic
fix: Unfolding some rituals won't crash your client.
/🆑

Bible Crash Fix

---

code/game/turfs/simulated/floor.dm
code/modules/holodeck/HolodeckObjects.dm
code/modules/mining/mine_turfs.dm

fixes #2574
Fixes floors being black after repair, and also removes some old obsolete vars

Black Floor Fix

---

code/game/objects/structures/signs.dm

Fixes #2816 
Renames Cyberchristianity to Neotheology.

Renames Cyberchristianity cross

---

code/datums/autolathe/circuits.dm
code/game/objects/items/weapons/autolathe_disks.dm
code/game/objects/items/weapons/circuitboards/computer/computer.dm
code/modules/virus2/centrifuge.dm
html/changelogs/isocent.yml

Added the board as an autolathe recipe and in the circuitpack disk as requested by Clockrigger.

Fixes isolation centrifuge decon runtime

---

code/modules/modular_computers/file_system/reports/crew_record.dm
html/changelogs/recordreligion.yml

Fixes crew religion field missing

---

code/game/machinery/excelsior/autolathe.dm
code/game/objects/items/weapons/circuitboards/machinery/excelsior.dm
html/changelogs/excelsiorautolathe.yml

Fixes : #2926 
🆑 TorinoFermic
fix: Added back missing required components for the excelsior autolathe circuit board after having built.
/🆑

Excelisor autolathe build requirements fix after first building.

---

code/modules/mob/living/carbon/human/examine.dm
code/modules/mob/living/carbon/human/human.dm
code/modules/mob/living/carbon/human/life.dm
code/modules/modular_computers/file_system/reports/crew_record.dm
html/changelogs/recordshud.yml

Links crew record criminal status with HUDs

---

code/game/machinery/washing_machine.dm
code/game/mecha/mecha.dm
code/game/objects/items/weapons/storage/belt.dm
code/game/objects/random/cloth.dm
code/modules/paperwork/paperbin.dm

Quick patch to fix issues raised by ghost about the scrap PR
This fixes all the requests on #2851 except for the mecha explosion proc. That one is too much refactoring for now, and should be part of a future overhaul

Scrap Fixes

---

code/modules/error_handler/error_handler.dm

https://secure.byond.com/forum/?post=2306577

Fix logging of stack overflow runtimes

---

code/modules/mob/mob.dm

Fixes infinite loop with paralysis

---

code/datums/uplink/announcements.dm

Fixes uplink announcements again

Announcement Uplink Fix

---

code/game/objects/random/junk.dm
code/modules/reagents/reagent_containers/pill.dm

Random pills for junk spawner with memes inside.

The floor pills.

---

code/modules/projectiles/gun.dm

fixes gun suicide

---

code/modules/projectiles/guns/Hatton.dm

Fixes robot hattons being able to have their magazines ejected

---

code/_onclick/hud/parallax.dm
code/datums/datum_hud.dm
code/modules/mob/mob.dm
code/modules/mob/observer/freelook/eye.dm

- Fixes AI lighting overlay bug
- Fixes camera console bug

Visual contents camera related bugfixes

---

code/datums/topic/world.dm

https://github.com/discordia-space/CEV-Eris/pull/3044

#3044 without conflicts

---

code/game/objects/items/weapons/tools/_tools.dm
code/modules/mining/mine_turfs.dm

Solves that^ by creating a custom callback for the radial menu to check.

fixes digging double radial

---

code/game/machinery/vending.dm

Firearm and Ammunition vending machines registered to the Frozen Star™ Corporation now conduct an extensive and scrutinous background check on all customers, in order to evade legal liability in case of selling weapons to a known criminal.

Frozen Star Background Checks

---

code/game/machinery/vending.dm

Actually fixes vending machines automatically getting the price for products from the item's price_tag. For real this time.

Fixes auto pricing

---

code/modules/mob/living/carbon/human/species/species_hud.dm

Monkeys can wear hats

---

code/modules/hivemind/core.dm
code/modules/hivemind/machines.dm
code/modules/hivemind/mobs.dm
code/modules/hivemind/objects.dm
code/modules/hivemind/wires.dm

New Hivemind texts, made by @Wesreidau.
This PR is the same as #3084, but less of a mess.

Text rework for all the hivemind dialog, mob names and descriptions

---

code/modules/mob/living/living.dm

Dragging got fixed in dev branch. NanakoAC must have missed it during the porting of bay movement code.
Fixes : #3104

Dev branch fix : Dragging is fixed

---

code/game/objects/effects/spiders.dm
code/game/objects/effects/trails.dm

Sticky Webs and Ion Trails will behave as normal.
Fixes #3003
Fixes #2826

Spiders webs and cocoons now visible and Ion Trails will fade

---

code/datums/movement/mob.dm

You could grab-drag but the animation won't be pretty.
Fixes #3130

Quick fix to Grab Drag system in DEV

---

code/datums/topic/admin.dm

Minor fix to some rights stuff

Href parsing fixes

---

code/game/objects/items/weapons/grenades/chem_grenade.dm
code/game/objects/items/weapons/grenades/grenade.dm

Removing random timer from proper grenades. Adding it to chemistry grenade only.

Rebalancing cooking of grenades.

---

code/game/objects/random/junk.dm

Removing unclickable item from scrap loot list

---

code/game/machinery/recharger.dm
code/modules/client/preference_setup/loadout/gear_tweaks.dm
code/modules/modular_computers/computers/modular_computer/core.dm
code/modules/modular_computers/computers/modular_computer/hardware.dm
code/modules/modular_computers/computers/modular_computer/interaction.dm
code/modules/modular_computers/computers/modular_computer/power.dm
code/modules/modular_computers/computers/modular_computer/ui.dm
code/modules/modular_computers/computers/modular_computer/variables.dm
code/modules/modular_computers/computers/subtypes/dev_pda.dm
code/modules/modular_computers/computers/subtypes/dev_tablet.dm
code/modules/modular_computers/computers/subtypes/preset_laptop.dm
code/modules/modular_computers/computers/subtypes/preset_pda.dm
code/modules/modular_computers/computers/subtypes/preset_tablet.dm
code/modules/modular_computers/file_system/programs/generic/configurator.dm
code/modules/modular_computers/laptop_vendor.dm

fixes https://github.com/discordia-space/CEV-Eris/issues/3126
All modular comps now use actual cells instead of shitty snowflake modular batteries.
Also adds a radial for removing parts because fuck anything that isnt a radial :)))

Modular computers use actual cells now

---

code/game/jobs/job/captain.dm
code/game/jobs/job/civilian.dm
code/game/jobs/job/civilian_chaplain.dm
code/game/jobs/job/engineering.dm
code/game/jobs/job/guild.dm
code/game/jobs/job/medical.dm
code/game/jobs/job/science.dm
code/game/jobs/job/security.dm

Updates the skills of most roles to be more realistic to their roles without compromising gameplay.
I am actively working on a design document to explain the reason behind the skills of each role, which can be found here:
https://docs.google.com/document/d/12CGD_KwJEVBqz9XIfE3yy_S2CkZkqSuERu-9CdQUICw/edit?usp=sharing
Suggestions and Comments are enabled, feel free to make comments directly there or on here.
Some roles have been given boosts to skills they should be more proficient in, some have been reduced to be less memey. Overall, this is NOT a balanced update, but rather an update that forces you to deal with the role you've chosen to play which in my opinion makes the game more interesting.
This serves as a counter PR to #3231

Skills Update 1.5

---

code/datums/movement/mob.dm
code/game/objects/items/devices/radio/intercom.dm
code/game/objects/structures/bedsheet_bin.dm

Now you no longer spawn with intercoms in your belt and bedsheets in your pocket!
Trying to move while buckled now attempts to unbuckle you. No more "OOC: Newbie: how do i get out of bed"!
Fixes #3151

Fix for dormitory spawns

---

CONTRIBUTING.md
README.md

Also, there is now a link to CONTRIBUTING.md in our README.md.

Adds to_chat to CONTRIBUTING.md

---

code/_onclick/hud/screen_objects/base_screen_objects.dm
code/modules/mob/living/carbon/carbon.dm
code/modules/mob/living/carbon/human/human.dm

Fixes damage overlay obscuring HUD icons. Allows players to check their health by clicking health icon.

HUD tweaks

---

code/game/antagonist/antagonist_factions.dm

Hopefully only makes visible the excelsior chat to ghosts/observers with antagHUD enabled.

[FIX] Probable fix to excelsior chat

---

code/game/objects/items/weapons/tools/mods/mod_types.dm

You can now attach diamond blade to shovels, and you can use whetstone on it.

Shovel can be modded.

---

code/_onclick/rig.dm

RIG module activation fix

---

code/modules/projectiles/gun.dm

To stop the abuse of full auto smgs
🆑 TorinoFermic
tweak: Recoil and aim are doubled when dual wielding on 2 guns.
/🆑

Recoil and aim increased when dual wielding

---

code/modules/clothing/spacesuits/rig/modules/modules.dm
code/modules/clothing/spacesuits/rig/rig.dm

God, forgot about dis: 
Fixes #3285, fixes #3273
Power sink would charge empty cell in RIG and activation-based modules wont ignore power requirements now.

Fixing RIGs, many things to go

---

code/modules/mob/living/carbon/carbon.dm

Fixes #3288, but adds bit more load to server.

Space inertia hotfix

---

code/game/verbs/who.dm
code/modules/mob/mob.dm
code/modules/mob/new_player/new_player.dm

Players' high-priority role shows up in lobby tab

---

code/_helpers/unsorted.dm
code/game/machinery/doors/brigdoors.dm
code/game/mecha/equipment/mecha_equipment.dm
code/game/mecha/mecha.dm
code/game/mecha/medical/odysseus.dm
code/game/objects/items/devices/PDA/PDA.dm
code/game/objects/structures/crates_lockers/closets/syndicate.dm
code/modules/mob/living/carbon/human/examine.dm
code/modules/mob/living/carbon/human/inventory.dm
code/modules/modular_computers/computers/modular_computer/core.dm
code/modules/modular_computers/computers/modular_computer/hardware.dm
code/modules/modular_computers/computers/modular_computer/interaction.dm
code/modules/modular_computers/computers/modular_computer/power.dm
code/modules/modular_computers/computers/modular_computer/ui.dm
code/modules/research/designs.dm
code/modules/research/xenoarchaeology/tools/suspension_generator.dm

Fixes #2963. Fixes the issue from #2804. Fixes a bunch of other unreported issues, see commit log for details.

Minor fixes and tweaks

---

code/modules/mob/living/silicon/robot/component.dm
code/modules/mob/living/silicon/robot/robot.dm

Closes #3301 
Adjusted power consumption for silicons, replaced << with to_chat in affected files.

Making silicon great again

---

code/datums/wires/wires.dm
code/game/machinery/pipe/construction.dm
code/game/objects/items/weapons/space_harpoon.dm
code/game/objects/random/cloth.dm
code/game/turfs/turf.dm
code/modules/mob/living/carbon/carbon.dm
code/modules/mob/mob_movement.dm
code/modules/multiz/movement.dm

- Fixes #2991 
Aural dampener on multitool works as intended now
- Fixes #3033
No more BST gloves inside scrap piles
- Fixes #3088 
Every tool with `QUALITY_BOLT_TURNING` should work with pipes just good.
- Fixes #3077
Check for distance between mob and tables was added
- Fixes #3284 
For real this time. Magboots and zero-g. Should be fine.
Some to_chat replacement.

Some fixes

---

code/modules/mob/living/carbon/carbon.dm

Another inertia fix

---

code/game/antagonist/antagonist_factions.dm

Dear god, I am not sure why the if check passed while having antagHUD disabled.
Derp, closing my branches on my github repo also closes pull requests.

Excelsior Chat Electric Boolagoo 3

---

code/ATMOSPHERICS/components/binary_devices/pipeturbine.dm
code/ATMOSPHERICS/components/unary/heat_exchanger.dm
code/ATMOSPHERICS/pipes.dm
code/game/machinery/pipe/pipe_dispenser.dm
code/game/machinery/pipe/pipelayer.dm
code/game/machinery/supplybeacon.dm
code/game/objects/items/_inventory.dm
code/game/objects/items/apc_frame.dm
code/game/objects/items/weapons/tools/_tools.dm
code/game/objects/structures/electricchair.dm
code/game/objects/structures/medical_stand.dm
code/game/objects/structures/musician.dm
code/game/objects/structures/stool_bed_chair_nest/stools.dm
code/modules/assembly/shock_kit.dm
code/modules/clothing/spacesuits/void/void.dm
code/modules/mob/living/carbon/carbon.dm
code/modules/mob/mob_movement.dm
code/modules/multiz/movement.dm
code/modules/multiz/turf.dm
code/modules/synthesized_instruments/real_instruments.dm

Fixes #3350, closes #3172 
- Some tool.use_tool replacing tool/wrench and such stuff
- Proper movement in spess, v.3.0. No more "there is space under your way".
Jetpacks borked still (stabilisation even with empty jetpack)
- Proper overslot check for voidsuits. Kinda too small to make separate PR for it.
Also, removed typo when your tried put clothing with overslot over other clothing with overslot
- Some SPAN_STUFF and to_chat thingies.

Some machinery attackby, multiZ movement

---

code/game/objects/items/crayons.dm
code/modules/paperwork/pen.dm

So, there's a recipe in the code to make paint from crayon dust, great! Problem: there's no way to get crayon dust unless you eat crayons and get a dialysis to get the dust out of your blood.
So I just made crayons grindable in chem grinders.

Crayons are now grindable

---

code/game/objects/items/weapons/cards_ids.dm
code/game/objects/items/weapons/tools/_tools.dm
code/game/objects/items/weapons/tools/mods/_upgrades.dm
code/modules/economy/ATM.dm
code/modules/economy/Accounts.dm

* Fixes bank accounts being accessible without PIN in ATMs. Closes #3441.
* Fixes tool upgrades being utterly broken.
Do not update the server until this is merged.

Important fixes

---

code/datums/wires/wires.dm
code/modules/core_implant/cruciform/cruciform.dm

Airlock signaller and ressurection fixes

---

code/game/objects/items/weapons/RCD.dm

Low walls would be build without windows.

RCD and low walls

---

code/datums/movement/mob.dm
code/game/area/areas.dm
code/game/turfs/simulated.dm
code/game/turfs/space/space.dm
code/game/turfs/turf.dm
code/modules/mob/living/carbon/carbon.dm
code/modules/mob/living/carbon/human/human_movement.dm
code/modules/mob/living/carbon/slime/slime.dm
code/modules/mob/living/silicon/robot/robot_movement.dm
code/modules/mob/living/simple_animal/hostile/bat.dm
code/modules/mob/living/simple_animal/hostile/bear.dm
code/modules/mob/living/simple_animal/hostile/carp.dm
code/modules/mob/living/simple_animal/hostile/retaliate/drone.dm
code/modules/mob/living/simple_animal/hostile/syndicate.dm
code/modules/mob/mob_movement.dm
code/modules/multiz/movement.dm
code/modules/multiz/turf.dm
code/modules/multiz/ztravel/zmethod.dm

Deleted duplications, moved almost all inertia halts to turf.dm, reworked logic a bit.
- Fixed issue about phasing empty floors from below
- Fixed issue about jetpacks inertia
- Nerfed jetpacks so they work as intended
- Almost all hostile critters would move around walls with slips, except carps ofc.
Animations are quite inconsistent so expect some floating mobs in gravitated habitat still.

Jetpacks and zero-g

---

code/game/atoms.dm
code/game/atoms_movable.dm
code/game/machinery/atmoalter/portable_atmospherics.dm
code/game/machinery/bots/mulebot.dm
code/game/machinery/floodlight.dm
code/game/machinery/recharger.dm
code/game/machinery/rechargestation.dm
code/game/machinery/spaceheater.dm
code/game/mecha/mecha.dm
code/game/objects/items/devices/lighting/toggleable/flashlight.dm
code/game/objects/items/devices/megaphone.dm
code/game/objects/items/devices/scanners.dm
code/game/objects/items/devices/suit_cooling.dm
code/game/objects/items/devices/t_scanner.dm
code/game/objects/items/weapons/space_harpoon.dm
code/game/objects/items/weapons/stunbaton.dm
code/game/objects/items/weapons/teleportation.dm
code/modules/clothing/gloves/stungloves.dm
code/modules/power/apc.dm
code/modules/projectiles/guns/energy.dm
code/modules/projectiles/guns/energy/nuclear.dm
code/modules/research/xenoarchaeology/tools/suspension_generator.dm

Fixes #3399 and a bunch of similar issues, I hope.

Rigged cell fix

---

code/modules/error_handler/error_handler.dm

Fixes a runtime error in runtime error handler

---

code/game/machinery/adv_med.dm
code/game/objects/items/weapons/implant/implant.dm
code/game/objects/items/weapons/implant/implants/excelsior.dm

Excelsior implant now shows up as either Death Alarm or Chem Implant on Adv Scanner
Gotta pry it out to be sure it's commiestuff.

Excelsior implants disguise

---

code/modules/research/rdconsole.dm

Drone in destructor

---

code/game/objects/items/weapons/handcuffs.dm

Plain nerf for cuffing as hoomins have no delay on cuffing someone. No stats affection there, as it was requested
- 4 seconds for cuffing without any grab (borgs, tele bois)
- 3 seconds for passive grab
- 1.5 seconds for aggressive grab
- 0.75 seconds for neck grab
- Instant for kill grab

Handcuffs delay nerf

---

cev_eris.dme
code/modules/admin/NewBan.dm
code/modules/admin/admin.dm
code/modules/admin/player_notes.dm
code/modules/admin/topic.dm

Ports from baystation, will update as this goes along.

[Ready for Review] Adds Player Notes

---

code/__defines/mob_stats.dm
code/datums/mob_stats.dm
code/game/antagonist/outer/mercenary/mercenary.dm
code/game/jobs/job/assistant.dm
code/game/jobs/job/captain.dm
code/game/jobs/job/civilian.dm
code/game/jobs/job/civilian_chaplain.dm
code/game/jobs/job/engineering.dm
code/game/jobs/job/guild.dm
code/game/jobs/job/medical.dm
code/game/jobs/job/security.dm
code/modules/projectiles/gun.dm

* Aim is now Vigilance. Description was eddited, and later it will be a stat will hepl protects from insanity.
* That stat was fixed across all job.
* Serbs now have this stat.

Aim stat fixes and renaiming.

---

code/modules/core_implant/cruciform/rituals/crusader.dm
code/modules/hivemind/machines.dm

* You can now resist effect of two techhive structures with Vigilance stat.
* You can now resist both drawback and actual effect of ``Searing Revelation`` litany (crusader AoE stun).

Vigilance checks on psy related stuns.

---

code/datums/topic/admin.dm
code/modules/admin/topic.dm

It is no longer old shitcode. With new topic datums, it is modern shitcode now!

Ports admin notes to topic datums

---

code/modules/organs/external/_external.dm

Tweaked a bit IB numbers, it would take twice more time to build up nasty numbers and would let you live for like one or two more minutes.

IB rebalance

---

code/game/machinery/cryopod.dm

Cryopod antirobbery system

---

code/game/objects/items/weapons/stunbaton.dm
code/modules/clothing/gloves/stungloves.dm

Looks like this last nerf was too much.

Unnerfing stungloves.

---

code/game/machinery/autolathe.dm

#3390 Should, at least. At a glance seems only thing missing was ejecting the disk prior to dismantle.

Fixes #3390

---

code/modules/client/preferences.dm

You can no longer spawn with your nutrition in red just because the random decided so.

Increases roundstart human nutrition

---

code/game/mecha/mecha.dm
code/modules/scrap/oldificator.dm

You can now install a new cell in them just fine.
Also tweaks some of the "oldificator" code.

Fixes maint mechs that spawn without a cell being unrepairable 

---

code/game/machinery/vending.dm

well this adds 4 cigars as contraband for the cigarette machine (costing 25) , and  more important adjusted the price from 300 to 12 so people are able to fuck their lungs at will (we are in cyberpunk yeah smoking is expensive in real life but... even them not that much)

[tweak] Punks Smoke

---

code/controllers/subsystems/supply.dm

export fix

---

cev_eris.dme
code/__defines/tgui.dm
code/modules/client/preference_setup/global/preferences.dm
code/modules/nano/interaction/hands.dm
code/modules/nano/nanoexternal.dm

Removes some TG UI leftovers

---

code/game/atoms.dm

Fixes MC init

---

code/modules/reagents/reagent_containers/food/drinks.dm

the mixer can now be set to transfer 
5,10,20,30,60,120 units (just like the pitcher)

mixer now have transfer amount

---

code/game/mecha/mecha.dm

Fixes a mech runtime error

---

code/modules/core_implant/cruciform/rituals/inquisitor.dm
code/modules/core_implant/cruciform/rituals/priest.dm
code/modules/core_implant/ritual.dm

Fixes Epiphany rite failing to activate cruciform

---

code/game/mecha/mecha.dm
code/game/objects/structures/crates_lockers/closets.dm
code/game/objects/structures/crates_lockers/closets/coffin.dm
code/modules/overmap/spacetravel.dm
html/changelogs/TorinoFermic_lostinspace.yml

Various fixes for mech, coffins.
A fix was ported in : https://github.com/Baystation12/Baystation12/pull/25392
Fixes #3515
🆑 TorinoFermic
bugfix: Mechs won't despawn with a occupant while going out of current map.
bugfix: Cleaned up the weird coffin code.
/🆑

[FIX] Various fixes for lost in space

---

code/game/objects/structures/crates_lockers/closets/coffin.dm

The last speedmerged PR broke coffins's reduction spawn time mechanic.

Quick fix for coffins

---

code/game/turfs/flooring/flooring.dm

Flooring fix

---

code/__defines/mobs.dm
code/game/machinery/cryopod.dm
code/modules/mob/living/silicon/ai/latejoin.dm
code/modules/mob/observer/ghost/ghost.dm
html/changelogs/Kurgis-PR-Wipe-Core-Fix.yml

Using the Wipe Core command as AI will give you the cryopod bonus, reducing their respawn timer by 20 minutes.

Wipe Core now gives cryo-sleep respawn bonus.

---

code/game/machinery/doors/airlock_electronics.dm
code/game/objects/objs.dm
code/modules/nano/interaction/hands.dm
nano/templates/airlock_electronics.tmpl

Same as my Baystation PR: ports airlock electronics to NanoUI.

NanoUI airlock electronics

---

code/controllers/subsystems/jobs.dm
code/game/objects/items/weapons/cards_ids.dm
code/modules/modular_computers/NTNet/NTNet.dm
code/modules/modular_computers/NTNet/emails/email_account.dm
code/modules/modular_computers/file_system/programs/generic/bounty_board.dm
code/modules/modular_computers/file_system/programs/generic/email_client.dm
code/modules/modular_computers/file_system/programs/research/email_administration.dm
code/modules/modular_computers/file_system/reports/crew_record.dm
code/modules/modular_computers/file_system/reports/people.dm
code/modules/modular_computers/terminal/terminal_skill_fail.dm
nano/templates/email_client.tmpl

Fixes:
- Email login in on spawn
- Potential exploit for bounty board app
Improvements:
- Email list sorted by name
- Email client has search button
- Email client puts "No subject" title for mail by default
- Crew records list sorted by name

Fixes and Improvements for Email client/Crew records

---

code/modules/materials/material_sheets.dm

No more iron sheets looking like coal.

Quick iron sheet fix.

---

code/game/gamemodes/roleset/faction/roleset_faction.dm
code/game/gamemodes/roleset/roleset.dm
code/game/gamemodes/storyevent.dm

Not sure, but I don't have the easy way to test this fix.
Fixes #2835
🆑 TorinoFermic
bugfix: Serbs shouldn't spawn more than once for now.
/🆑

[FIX] Serb double spawning fix

---

code/datums/datum_click_handlers.dm
code/modules/projectiles/gun.dm
code/modules/projectiles/guns/projectile/automatic.dm
code/modules/projectiles/guns/projectile/automatic/IH_heavy.dm
code/modules/projectiles/guns/projectile/automatic/IH_machinepistol.dm
code/modules/projectiles/guns/projectile/automatic/ak47.dm
code/modules/projectiles/guns/projectile/automatic/atreides.dm
code/modules/projectiles/guns/projectile/automatic/c20r.dm
code/modules/projectiles/guns/projectile/automatic/dallas.dm
code/modules/projectiles/guns/projectile/automatic/idaho.dm
code/modules/projectiles/guns/projectile/automatic/maxim.dm
code/modules/projectiles/guns/projectile/automatic/sol.dm
code/modules/projectiles/guns/projectile/automatic/sts35.dm
code/modules/projectiles/guns/projectile/automatic/z8.dm
code/modules/projectiles/guns/projectile/pistol/olivaw.dm

~I have a German exam tomorrow and i'm going to fail it someone please kill me~
This PR makes vigilance suck less, and allows you to hit the broadside of a barn instead of bullets just fucking off somewhere.
https://streamable.com/qmzj1
Testing is needed and appreciated, a testmerge would be perfect.
This mechanic rips off CSGO. After firing a shot, your recoil builds up. If you don't fire for a few seconds (Variable based on vigilance skill level) the recoil is removed, allowing for a clean shot. IH and Serbs can basically ignore this, though bursting will yield far more accurate shots instead of the classic spray n' pray approach.
Moving and shooting is going to fuck you up, so watch out.

Makes vigilance suck less

---

code/game/objects/items/weapons/improvised_components.dm

something something parenthesis. stunprods craftable now.

stunprod crafting fix

---

code/_onclick/other_mobs.dm
code/datums/mob_stats.dm
code/game/objects/structures.dm
code/game/objects/structures/railing.dm
code/modules/multiz/structures.dm
code/modules/recycling/disposal.dm

🆑 TorinoFermic
tweak: Vigilance will affect how fast you climb onto/into disposals, ladders, tables and railings.
/🆑

[TWEAK] Climbing into delay is now affected by your stat Vigilance

---

code/modules/multiz/ztravel/zmethod.dm

The runtime did not let him finish ztravel. A simple mob check fixed it.

mecha ztravel (fix)

---

code/modules/multiz/ztravel/zmethod.dm
code/modules/projectiles/projectile.dm

shooting on a limb, one can get into any closest limb from the one that was selected on the doll, provided that the mouse is pointed there when pressed.

pixel aiming system and a bit of chance

---

.github/PULL_REQUEST_TEMPLATE.md

Copies PR template from TG. 
Or literally all other servers, almost all have the same one.
Because we can now keep PRs organized, and also if I manage to get my last two braincells to set up changelog generation, we'd have ingame changelog.
:cl:
add: Added PR template for github.
/:cl:

Copies PR template from TG. 

---

cev_eris.dme
code/game/gamemodes/events/meteors.dm
code/modules/overmap/events/event.dm
code/modules/overmap/events/movable.dm
code/modules/overmap/ships/computers/helm.dm
code/modules/overmap/ships/ship.dm

Сomet event that will actually fly, while shitting with it tail all around
https://cdn.discordapp.com/attachments/220251965609869312/610901395792592926/unknown.png
https://recordit.co/UOLmhhKGxf

overmap comet

---

code/modules/reagents/reagents/medicine.dm
code/modules/reagents/reagents/nanites.dm
code/modules/reagents/reagents/stims.dm
code/modules/reagents/reagents/toxins.dm
code/modules/reagents/recipes.dm

Fixed text errors
Grammar
:cl:
fix: Fixed text errors
/:cl:

Fixed text errors

---

code/modules/reagents/reagents/stims.dm

👌
:cl:
add: Added more things
soundadd: added a new sound thingy
sounddel: removed an old sound thingy
imageadd: added some icons and images
imagedel: deleted some icons and images
code: changed some code
refactor: refactored some code
config: changed some config setting
admin: messed with admin stuff
server: something server ops should know
/:cl:

Stims.dm descriptions

---

code/modules/reagents/reagents/other.dm

other.dm small description fix

---

code/modules/reagents/reagents/toxins.dm

toxins.dm descritions

---

code/modules/reagents/reagents/drugs.dm

👌
:cl:
add: a single description, testament to my coding and writing skills
/:cl:

drugs.dm descriptions

---

code/__defines/craft.dm
code/datums/craft/menu.dm
code/datums/craft/recipe.dm
code/datums/craft/recipes/floor.dm
code/datums/craft/recipes/misc.dm
nano/templates/craft.tmpl

It's back.
The plus button prompts user for amount.
:cl:
add: Added batch crafting to craft menu for certain recipes
/:cl:

Batch crafting

---

code/modules/reagents/reagents/nanites.dm

👌 now with more words that before 👌 
:cl:
add: Descriptions and names for nanites.dm
/:cl:

nanites.dm descriptions and names

---

code/modules/reagents/reagents/food-Drinks.dm

Thanks wikipedia, the free encyclopedia.
:cl:
add: proper descriptions for drinks and food
del: unfunny memes
fix: a few memes
/:cl:

Food+Drinks.dm descriptions

---

.gitignore
cev_eris.dme
code/game/machinery/Sleeper.dm
code/game/objects/items/weapons/circuitboards/machinery/medical.dm
code/modules/research/designs/circuits.dm
code/modules/research/designs/weapon.dm
code/modules/research/nodes/biotech.dm
code/modules/research/nodes/bluespace.dm
code/modules/research/nodes/combat.dm
code/modules/research/nodes/engineering.dm
code/modules/research/nodes/illegal.dm
code/modules/research/nodes/power.dm
code/modules/research/nodes/robotics.dm
code/modules/research/rdconsole.dm
nano/css/shared.css
nano/templates/rdconsole.tmpl

When you hover your cursor on RND node you can see something like this:
You can faster finding node and read it description without selecting it, maybe to compare selected node and hover node.
<details><summary>Changelog</summary>
:cl:
tweak: now if you hover your mouse on research node in RND you can see it description and name and icon.
add: Descriptions for research nodes added.
/:cl:
</details>

Tooltips and using description for RND

---

code/modules/reagents/reagents/medicine.dm

new chemicals now have proper descriptions 👌 :agony:
:cl:
add: proper descriptions for new meds
/:cl:

Medicine.dm descriptions

---

code/game/objects/items/weapons/handcuffs.dm
code/game/objects/items/weapons/storage/storage.dm
code/modules/mob/living/carbon/human/update_icons.dm
code/modules/mob/living/simple_animal/simple_animal.dm

Fixes two bugs, thanks to @rpilcrow for fixing these so I could steal his code for it. Yoink.
Bugs are bad. Might as well not have them.
:cl:
fix: Cyborg-applied handcuffs should be able to be resisted out of, now.
fix: Dead simplemobs now die once instead of every tick.
/:cl:

Cyborg cuffs are removable, dead simplemobs don't die repeatedly

---

code/modules/telesci/telesci_computer.dm

Fixes old Clamp calls to the current CLAMP.
This should be fast merged.

Clamp hotfix

---

code/game/objects/items/weapons/circuitboards/machinery/excelsior.dm

board name went from excelsior excelsior teleporter -> excelsior teleporter. that's it.

one-liner grammar tweak

---

code/datums/outfits/jobs/civilian.dm
code/game/jobs/job/civilian.dm
code/game/jobs/jobs.dm
code/modules/multiz/map_data.dm

Replaces Chef and Bartender with Club Manager and Club Workers
Replaces a role.
:cl:
add: Added Club Manager and Club Worker
del: Removed Chef and Bartender
/:cl:

Replaces Chef and Bartender with Club Manager and Club Worker

---

code/datums/outfits/jobs/church.dm
code/datums/outfits/jobs/civilian.dm
code/game/jobs/job/church.dm
code/game/jobs/job/civilian.dm
code/game/jobs/jobs.dm
code/game/objects/structures/crates_lockers/closets/job_closets.dm
code/game/objects/structures/crates_lockers/closets/secure/chaplain.dm
code/game/objects/structures/crates_lockers/closets/secure/hydroponics.dm
code/modules/multiz/map_data.dm

Adds Acolyte. Moves Janitor and Gardener to Church. A lot of stuff is WIP but at least they work now. Access and descriptions still need to be done. 
:cl:
add: Added the NT update
/:cl:

The NT Update

---

code/modules/core_implant/cruciform/rituals/priest.dm
code/modules/mob/living/carbon/human/human.dm

Fixes #3799 
2 fixes
Rituals are fixed possibly
Admin heals won't remove cruciform from humans.
:cl:
fix: Admin heal will not remove the cruciform
fix: Revial and removal ritual is fixed.
/:cl:

Cruciform ritual and admin heal fixes

---

code/modules/mob/living/say.dm
code/modules/mob/living/simple_animal/parrot.dm
code/modules/mob/say.dm

Update and Simplify radio prefixes defination and hadnling
You no longer need to describe every chanel 2-3 times.
<hr>
:cl:
fix: fixed a few fixes
/:cl:

Update radio prefixes defination and handling (Testing required)

---

code/game/jobs/job/assistant.dm
code/game/jobs/job/assistant_flavors.dm

<details>
<summary>
More titles and stats for random choices for Vagabonds.
</summary>
<hr>
:cl:
add: More Vagabond job titles
/:cl:

More Vagabond flavors.

---

code/game/jobs/job/church.dm
code/modules/clothing/head/helmet.dm
code/modules/clothing/suits/armor.dm

<details>
<summary>
Gives NT jobs proper [?] info in the occupation section of loadout. Also fixes their armor to be properly resistant.
</summary>
<hr>
<hr>
</details>
:cl:
tweak: changed NT job descriptions in character setup
tweak: NT armor now has proper naming and armor values
/:cl:

Gives NT Jobs Proper Descriptions and Fixes NT Armor Values

---

code/modules/mob/living/say.dm
code/modules/mob/living/simple_animal/parrot.dm
code/modules/mob/say.dm

Reverts discordia-space/CEV-Eris#3814

Revert "Update radio prefixes defination and handling (Testing required)"

---

code/modules/mob/living/carbon/slime/powers.dm

Slimes now deal burn damage instead of clone.
:cl:
tweak: replaced slime damage with burn
/:cl:

Slime nerf

---

code/game/machinery/machinery.dm
code/modules/core_implant/cruciform/machinery/cloning.dm
code/modules/materials/material_sheets.dm

<details>
<summary>
</summary>
<hr>
<ul>
<li> Biomass container of NT cloner now can be filled by biomatter sheets from solidifier.
<li> Deleted shitcode in ping() proc
</ul>
<hr>
</details>
:cl:
tweak: biomass container of NT cloner now can be filled by biomatter sheets from solidifier
refactor: ping() proc refactored
/:cl:

 Allow to fill biomass container of cloner by biomatter ingots and machinery.ping() refactor

---

code/game/objects/items/oddities.dm

<details>
<summary>
Fixes some spelling in the code of oddities.
</summary>
<hr>
</details>
:cl:
code: fixes some spelling
/:cl:

Minor Oddity Fixes

---

code/modules/surgery/implant.dm

<summary>
Fix #3887
</summary>
<hr>
:cl:
fix: implant surgery runtime
/:cl:

Fix surgery implant runtime

---

code/_onclick/item_attack.dm
code/_onclick/other_mobs.dm
code/datums/perks/job.dm
code/game/jobs/job/guild.dm
code/modules/mob/living/carbon/human/human_movement.dm
code/modules/projectiles/gun.dm

<details>
<summary>
Changing the name for obvious reasons.
</summary>
<hr>
</details>
:cl:
code: renamed some procs
/:cl:

Changes Merchant Ability Name

---

code/modules/mob/living/say.dm
code/modules/mob/living/simple_animal/parrot.dm
code/modules/mob/say.dm

<summary>
Simplify radio chanels defination. There's no more need to describe each chanel 2-3 times.
</summary>
<hr>
:cl:
code: changed radio chanels code
/:cl:

Simplify radio chanels defination

---

code/datums/autolathe/biomatter.dm
code/modules/reagents/recipes.dm

Fixes #3844. Fixes #3835. See the issues for details.

Small quick lazy fixes

---

code/game/objects/items/weapons/circuitboards/machinery/chemestry.dm
code/modules/reagents/machinery/chem_dispenser.dm
code/modules/reagents/machinery/chem_master.dm
code/modules/research/designs/circuits.dm
code/modules/research/nodes/biotech.dm

Made chemmaster and chemical dispenser fully constructible and deconstructible.
Chemical dispenser's energy capacity now depends on power cell installed.
Fixed #3857.
:cl:
add: added chemical dispenser circuit and construction
fix: made Chemmaster deconstructible
/:cl:

Chemmaster and chemical dispenser construction

---

cev_eris.dme
code/controllers/configuration.dm
code/modules/webhook/webhook.dm
code/world.dm
config/example/config.txt

<details>
Add basic webhook support. For now, there is only a restart webhook.
</details>
:cl:
add: Add basic webhook support. For now, there is only a restart webhook.
/:cl:

Add webhook support

---

code/ATMOSPHERICS/atmospherics.dm

Fixes #3613 and the like.
:cl:
fix: fixed pipes being broken at roundstart
/:cl:

Displaced pipe fix

---

code/modules/organs/blood.dm

<details>
<summary>
Removes unnecessary code that caused this bug
</summary>
<hr>
closes #3796 
<hr>
</details>
:cl:
/:cl:

Fixes syringe blood draw

---

code/game/objects/random/scrap.dm
code/modules/scrap/scrap.dm
code/modules/scrap/scrap_beacon.dm

<details>
<summary>
Tweaked chances and sizes of srap piles
</summary>
<hr>
<hr>
</details>
:cl:
/:cl:

Scrap pile tweaks

---

code/modules/projectiles/guns/projectile/automatic/c20r.dm
code/modules/projectiles/guns/projectile/sniper.dm

<details>
<summary>
Reduces science value of two guns
</summary>
closes #3855 
<hr>
<hr>
</details>
:cl:
/:cl:

Fix for gun science value

---

code/game/jobs/job/assistant_flavors.dm
code/game/jobs/job/job.dm

<details>
<summary>
Flavor stat modification fix
</summary>
<hr>
Flavor stat modification fix + updating istype for add_stats()
<hr>
</details>
:cl:
fix: Flavor stat modification fixes
/:cl:

Flavor fixes

---

code/modules/admin/view_variables/topic.dm
code/modules/client/asset_cache.dm
code/modules/client/client procs.dm
code/modules/goonchat/assets.dm
code/modules/nano/nanoexternal.dm
code/modules/nano/nanoui.dm
nano/css/shared.css
nano/css/tgui.css

Asset cache is reworked to make NanoUI scripts and templates load faster, NanoUI code is tweaked to fix broken UIs staying broken until relog, and a new verb is added in case it doesn't help. 
I hope this ends our UI suffering once and for all.

Hopefully fixes our NanoUI woes

---

code/_onclick/click.dm

<summary>
Add requested hotkey for "point to" verb - shift +MMB
</summary>
<hr>
:cl:
add: Point-to hotkey (shift + MMB)
/:cl:

Add shift + MMB hot key for Point-to

---

code/game/mecha/equipment/tools/tools.dm
code/modules/mob/holder.dm
code/modules/projectiles/guns/projectile/automatic/IH_machinepistol.dm
code/modules/projectiles/guns/projectile/automatic/c20r.dm
code/modules/projectiles/guns/projectile/automatic/lmg.dm
code/modules/projectiles/guns/projectile/automatic/maxim.dm
code/modules/projectiles/guns/projectile/automatic/sts35.dm
code/modules/projectiles/guns/projectile/pistol/clarissa.dm
code/modules/projectiles/guns/projectile/pistol/silenced.dm
code/modules/projectiles/guns/projectile/shotgun/combatsg.dm
code/modules/projectiles/guns/projectile/shotgun/gladstone.dm
code/modules/projectiles/guns/projectile/sniper.dm
code/modules/scrap/scrap_burner.dm

<details>
<summary>
Due rework of RnD, we can have lower levels of items research value.
</summary>
<hr>
:cl:
balance: Added more things
/:cl:

Rebalancing numbers of tech var all across the codebase.

---

code/modules/projectiles/guns/energy.dm
code/modules/projectiles/guns/energy/pulse.dm
code/modules/projectiles/projectile/energy.dm

<details>
<summary>
Energy guns now have less recoil and energy crossbow now more powerful.
</summary>
<hr>
:cl:
balance: Energy guns now have less recoil and energy crossbow now more powerful.
/:cl:

Rebalancing energy guns.

---

code/game/machinery/smelter.dm

Separated refused items output from resource output in smelter.

Smelter refuse output

---

code/game/objects/items/stacks/medical.dm
code/game/objects/items/weapons/clown_items.dm
code/game/objects/items/weapons/cosmetics.dm
code/game/objects/items/weapons/gift_wrappaper.dm
code/game/objects/items/weapons/storage/backpack.dm
code/game/objects/items/weapons/storage/belt.dm
code/game/objects/items/weapons/storage/briefcase.dm
code/game/objects/items/weapons/storage/pouches.dm
code/game/objects/items/weapons/storage/wallets.dm
code/modules/paperwork/folders.dm
code/modules/paperwork/paper.dm
code/modules/paperwork/photography.dm
code/modules/reagents/reagent_containers/pill.dm

<details>
<summary>
</summary>
<hr>
:cl:
add: Biomatter material now present in more items, so junkyard can help NT more.
/:cl:

Biomatter material now present in more items.

---

code/game/objects/effects/decals/Cleanable/misc.dm
code/modules/reagents/holder.dm
code/modules/reagents/machinery/chem_dispenser.dm
code/modules/reagents/reagents/other.dm
code/modules/reagents/reagents/toxins.dm

<details>
<summary>
Biomatter fix and spills refactor
</summary>
<hr>
Biomatter got metabolism effects and can be spilled
This should also decrease roach piss.
<hr>
</details>
:cl:
refactor: Spills
fix: biomatter effects
/:cl:

Biomatter fix and spills refactor

---

code/controllers/subsystems/jobs.dm
code/datums/outfits/outfit.dm
code/game/jobs/job/assistant_flavors.dm
code/game/jobs/job/job.dm
code/game/objects/items/weapons/cards_ids.dm

<details><summary>Vagabonds now can change "name" of his "job"</summary>
<hr>Just a syndiscum card for vagabonds<hr></details>
:cl:
tweak: Vagabonds now can change "name" of his "job"
/:cl:

Vagabonds now can change "name" of his "job"

---

code/controllers/subsystems/jobs.dm
code/datums/outfits/outfit.dm
code/game/jobs/job/assistant_flavors.dm
code/game/jobs/job/job.dm
code/game/objects/items/weapons/cards_ids.dm

Reverts discordia-space/CEV-Eris#3928
Because this:

Revert "Vagabonds now can change "name" of his "job""

---

code/game/machinery/holoposter.dm
code/game/objects/random/cloth.dm
code/modules/clothing/shoes/jobs.dm
code/modules/power/antimatter/containment_jar.dm
code/modules/power/antimatter/control.dm
code/modules/power/antimatter/engine.dm
code/modules/power/antimatter/fuel.dm
code/modules/power/antimatter/shielding.dm
code/modules/power/singularity/act.dm
code/modules/power/singularity/collector.dm
code/modules/power/singularity/containment_field.dm
code/modules/power/singularity/emitter.dm
code/modules/power/singularity/generator.dm
code/modules/power/singularity/particle_accelerator/particle.dm
code/modules/power/singularity/particle_accelerator/particle_accelerator.dm
code/modules/power/singularity/particle_accelerator/particle_emitter.dm
code/modules/power/singularity/particle_accelerator/particle_power.dm
code/modules/power/singularity/singularity.dm
code/modules/projectiles/guns/launcher/crossbow.dm
code/modules/reagents/reagent_containers/food/cans.dm
code/modules/reagents/reagent_containers/food/snacks/meat.dm
code/modules/tables/rack.dm
nano/templates/ritual_book.tmpl

<details>
<summary>
More proofreading, and a bunch of extra fluff thrown into examine descriptions of engineering objects, and raw meat, as well as a few other odd objects.
</summary>
<hr>
<hr>
</details>
:cl:Gowst
spellcheck: More proofreading, and lots of extra fluff added to many engineering objects and raw meat.
/:cl:

proofreading and extra fluff on object descriptions

---

code/controllers/subsystems/garbage.dm
code/datums/underwear/underwear.dm
code/game/machinery/alarm.dm
code/game/objects/structures/under_wardrobe.dm
code/modules/bs_snare/machinery.dm
code/modules/client/preferences.dm
code/modules/mob/living/bot/farmbot.dm
code/modules/mob/living/carbon/superior_animal/roach/types/support.dm
code/modules/modular_computers/file_system/reports/crew_record.dm

<details>
<summary>
Random fixes
</summary>
<hr>
<hr>
</details>
:cl:
add: Some info to GC
fix: Underware storing in nullspace
fix: Non processing dummies for prefs
fix: proc return value
add: GC hint fixes
add: Improper placed alarms will show errors
refactor: Moved some code from New() to Init()
/:cl:

Unrelated fixes

---

nano/css/shared.css

<details>
<summary>
Tooltips appearance animation and circleful borders for them
</summary>
<hr>
Preview: <a href="https://jsfiddle.net/p1fLq9k0">jsfiddle</a>
<hr>
</details>
:cl:
tweak: Added tooltips appearance animation and circleful borders for them
/:cl:

Fancy animation of appearance for RND tooltips + border-radius

---

code/modules/mob/hear_say.dm
code/modules/mob/living/carbon/human/whisper.dm

fix for jive naming and text bubble after whispering

---

code/modules/projectiles/projectile/bullettypes.dm

Fixes .50 normal bullet armour pen that was set to rubber pen

Fixes .50 armour pen

---

code/game/objects/items/weapons/flamethrower.dm

Flamethrower now fits suit storage

Flamethrower now fits suit storage  

---

code/__DEFINES/inventory_sizes.dm
code/_onclick/telekinesis.dm
code/game/machinery/machinery.dm
code/game/objects/items.dm
code/game/objects/items/weapons/storage/bags.dm
code/game/objects/items/weapons/storage/belt.dm
code/game/objects/items/weapons/storage/fancy.dm
code/game/objects/items/weapons/storage/firstaid.dm
code/game/objects/items/weapons/storage/misc.dm
code/game/objects/items/weapons/storage/part_replacer.dm
code/game/objects/items/weapons/storage/secure.dm
code/game/objects/items/weapons/storage/storage.dm
code/game/objects/items/weapons/tools/crowbars.dm
code/game/objects/structures.dm
code/game/objects/structures/crates_lockers/closets.dm
code/game/objects/structures/girders.dm
code/game/objects/structures/window.dm
code/modules/bs_snare/machinery.dm
code/modules/mob/mob_defines.dm
code/modules/mob/mob_grab.dm
code/modules/scrap/scrap_beacon.dm

<details>
<summary>
</summary>
<hr>
Plastic bags no longer store nothing at all, and are now a very useful item. Removed the NO_CONTAINER size, and replaced it with a few larger weight classes. Changed the structure fall damage calculation proc call since NO_CONTAINER no longer exists. Removed the REDUCED_STORAGE_COST calculation, since it was used for a single item, and only introduced inconsistencies.
<hr>
</details>
:cl:
/:cl:

Fixes plastic bags, refactors inventory code, removes NO_CONTAINER size.

---

code/game/machinery/adv_med.dm
code/game/objects/structures/crates_lockers/closets/secure/hydroponics.dm
code/modules/stashes/stash_datum.dm

<details>
<summary>
As stated in title.
</summary>
<hr>
fixes #3978 
<hr>
</details>
:cl:
/:cl:

Fixes paper spawning blank, fixes church equipment spawning in botanist's locker.

---

code/game/objects/structures/burrows.dm

fixes#3954
Changelog
:cl:
tweak: active obelisks prevents burrow spawn
/:cl:

obelisks protect area from burrows

---

code/game/objects/structures/crates_lockers/closets/job_closets.dm

Custodial Closet hotfix

---

code/modules/mob/living/carbon/human/say.dm
code/modules/sanity/breakdown.dm
code/modules/sanity/breakdowns.dm

Added spans to breakdown messages.
Added *sanity* checks, including one that prevents anchored items from being picked up.

Sanity hotfixes

---

code/modules/mob/living/carbon/human/human.dm
code/modules/sanity/breakdowns.dm

Halved volume of PTSD sound effects.
Fixed obsession asking for upper body, which is impossible to acquire.

Sanity tweaks

---

code/modules/modular_computers/file_system/catalog.dm
nano/templates/catalog_entry_drink.tmpl
nano/templates/catalog_entry_reagent.tmpl

<details>
<summary>
Cleanup catalog code
</summary>
<hr>
Since it will not be used it is deleted
<hr>
</details>
:cl:
del: Removed unused things
/:cl:

Cleanup catalog code

---

code/modules/reagents/machinery/grinder.dm

<details><summary>Fix #3959</summary>
Now you can't put pistol or anything without reagents in makeshift grinder
</details>

Fix  #3959

---

code/game/objects/items/weapons/tools/_tools.dm
code/modules/client/asset_cache.dm
nano/templates/tool_stats.tmpl

Changes from #4006:
Removed UI opening on examine.
<details>
<summary>
Fixed tool quality borders.
</summary>
</details>
:cl:
add: Tool info ui
/:cl:

Tool information screen 2

---

code/game/objects/structures/stool_bed_chair_nest/chairs.dm

Now you can disassemble and assemble the chair without fear of losing steel
:cl:
balance: disassembling a chair gives 5 sheets of material
/:cl:

5 lists of material per chair

---

code/datums/uplink/highly visible and dangerous weapons.dm
code/game/objects/items/weapons/storage/uplink_kits.dm
code/modules/projectiles/ammunition.dm
code/modules/projectiles/guns/projectile/dartgun.dm

:cl:
add: Added dart gun box with dart gun and dart gun magazine for traitors uplink
(Because you don't need the dart gun if you haven't got telecrystals for dart gun magazine.)
fix: dart's gun magazine now fits in dart gun
/:cl:

Dart gun fixes

---

code/game/objects/structures/railing.dm

railings now correctly connect to neighboring

railing icon fix

---

code/modules/reagents/reagents/medicine.dm
code/modules/reagents/recipes.dm

<details>
<summary>
Adds new top tier brute healing chemical that is a counterpart to dermaline, called meralyne
</summary>
<hr>
New chemicals are good for the game, we could use some more spice to chemistry too.
<hr>
</details>
:cl:
add: Added meralyne, a chemical that is twice as good as bicardine
add: New recipe for it, which is 1 part  hyperzine,  2 parts blattedin, and 1 part tramadol to make 2 parts meralyne 
/:cl:

New chemical, Meralyne, which is a Dermaline counterpart for brute

---

code/modules/bs_snare/snare.dm
code/modules/research/designs/devices.dm
code/modules/research/designs/stock_parts.dm
code/modules/research/xenoarchaeology/tools/tools_anoscanner.dm
code/modules/research/xenoarchaeology/tools/tools_locater.dm
code/modules/telesci/bcrystal.dm
code/modules/telesci/gps.dm

<details>
<summary>
</summary>
<hr>
Fixing the impossibility of assembling a snare, beacon locator, ano scanner
<hr>
</details>
:cl:
tweak: fix of impossibility of assembling a snare, beacon locator and ano scanner
/:cl:
Resolving:
<ul>
<li>#4064
</ul>

matter of snare, beacon locator and anoscanner fix

---

code/modules/mob/mob.dm

as your father I expressly forbid it.
as your father I expressly forbid it.
as your father I expressly forbid it.
as your father I expressly forbid it.
as your father I expressly forbid it.
as your father I expressly forbid it.

Updates the WIP surgery nano UI branch

---

code/game/objects/items/weapons/circuitboards/machinery/chemestry.dm
code/modules/reagents/machinery/electrolyzer.dm

<details>
<summary>
fixes for the electrolyzer
</summary>
<hr>
blah blah fixes good not testing shit and not properly putting stuff in libraries bad.
<hr>
</details>
:cl:
fix: fixed electrolyzer not being able to be built
code: made it so the electrolyzer's circuit board is actually in the right place, which is with the chemistry boards in the chemistry.dm file in the circuitboard folders.
/:cl:

fixes the electrolyzers inability to be built and makes its circuitboard in a better place

---

cev_eris.dme
code/datums/setup_option/backgrounds/origin.dm

<details>
<summary>
New lore filled backgrounds for players to choose. They add the ability to change stats before round start, finally.
</summary>
<hr>
:cl:

New origin backgrounds.

---

code/game/objects/items/devices/mind_fryer.dm
code/game/objects/items/devices/spy_sensor.dm
code/game/objects/items/weapons/storage/bsdm.dm

Some checks in new antag devices were missing, added them.

Some verb checks

---

cev_eris.dme
code/__HELPERS/__v512.dm
code/__HELPERS/__v513.dm
code/__HELPERS/text.dm
code/modules/mob/living/carbon/human/human.dm
code/modules/mob/living/say.dm
code/modules/mob/mob.dm
code/modules/organs/blood.dm
code/modules/research/xenoarchaeology/artifact/artifact_replicator.dm

Compilation on v513 is now nice and smooth.

Fixes warnings on v513

---

.travis.yml

Exactly what it says on the tin
<details>
<summary>
Updates Travis to a newer byond version
</summary>
<hr>
<hr>
</details>
:cl:
tweak: Updates Travis to a newer byond version
/:cl:

Updates Travis to a newer byond version

---

code/modules/mob/living/carbon/resist.dm
code/modules/mob/mob_grab.dm

<details>
<summary>
buffs resisting and defending in a grab fight
</summary>
<hr>
I feel this way because grabs are too good right now.
<hr>
</details>
:cl:
balance: cooldown for resisting is 10 from 20
balance: unmoving neck resist chance is 5 from 3
:cl:

 decreases time for resisting grabs

---

code/game/machinery/camera/camera_assembly.dm

:cl:
fix: the camera can be assembled again
/:cl:

fix for camera assembly

---

code/game/antagonist/antagonist_panel.dm
code/modules/mob/new_player/new_player.dm

Closes exploits that allowed spawning uplinks and interfering with other players' preferences.

Topic checks

---

code/__DEFINES/misc.dm
code/__HELPERS/game.dm
code/controllers/subsystems/lighting.dm
code/controllers/subsystems/machines.dm
code/controllers/subsystems/processing/processing.dm
code/game/gamemodes/events/infestation.dm
code/game/objects/items/blueprints.dm
code/modules/core_implant/cruciform/machinery/obelisk.dm
code/modules/lighting/lighting_corner.dm
code/modules/lighting/lighting_overlay.dm

Hopefully this will improve performance a bit.
- Made some variables local and removed redundant checks in processing loops and lighting.
- `get_area` is now a macro.
- Merged loops and reduced `range` calls in NT obelisk `Process`.

Microoptimizations

---

code/modules/stashes/stash_types/ninja.dm

<details>
<summary>
Heavily nerfs ninja stash, Reere approved change
</summary>
<hr>
Holy shit Nanako's ghost keeps haunting us forever from all these bad stash and admin content into the game changes. 
<hr>
</details>
:cl:
balance: made ninja stash have only guaranteed smokes with chances of a pistol and grenades
/:cl:

FUCK NINJA STASH AND FUCK JANNIES

---

code/modules/mob/mob.dm

Having low sanity no longer wrecks your ability to view stats.

Stat view panel is no longer broken all the time

---

code/modules/clothing/spacesuits/spacesuits.dm

<details>
<summary>
durr long time bad
</summary>
<hr>
reere said so
<hr>
</details>
:cl:
tweak: tweaked equipment delay to 4 from 12
/:cl:

nerfs equipment delay on spacesuits (rigs and voids) by 1/3

---

code/game/objects/items/weapons/tools/mods/_upgrades.dm

<details>
<summary>
Ooga booga me fix stuff
</summary>
<hr>
Reere approved ™️ 
<hr>
</details>
:cl:
fix: fixed tool upgrading requiring MEC stats, and also the fail chance being higher than zero
/:cl:

removes fail chance and stat requirement from upgrading tools

---

code/game/jobs/job/medical.dm

<details>
<summary>
Gives Medical personnel competitive stats.
</summary>
<hr>
Scientists practically out compete the Medical staff at their own job, no more.
<hr>
</details>

Medical access & stat buffs

---

code/modules/projectiles/guns/launcher/crossbow.dm

<details>
<summary>
buffs RXD crossbow
</summary>
<hr>
Technomancers need love and care, I believe this RXD should become a somewhat viable weapon, but not too string
<hr>
</details>
:cl:
balance: throwforce from 4 to 6
balance: drawtime from 10 to 5
balance: boltcost from 10 to 5
balance: max materials from 40 to 60
balance: rcd cartridges add 20 matter, which is 4 shots
/:cl:

Rxd crossbow buff (giving technos some love)

---

code/game/machinery/doors/airlock.dm

<details>
<summary>
</summary>
<hr>
<ul>
<li>Remove Blockage and Wedge blockage fixed by deleting arguments of user in this verbs
<li>if you ALT + click on blockaged airlock, you will remove blockage, but if it isn't blocked and in ur active hand crowbar, u'll block it. 
</ul>
<hr>
</details>
:cl:
add: Feature, if you ATL + click on blockaged airlock, you will remove blockage, but if it isn't blocked and in ur active hand crowbar, u'll block it. 
fix: Remove Blockage and Wedge blockage fixed
/:cl:

Remove Blockage and Wedge blockage fix #3962

---

maps/CEVEris/_CEV_Eris.dmm

<details>
<summary>
</summary>
<hr>
Various fixes/additions/removals to the map, check changelog for exact description.
<hr>
</details>
:cl:
add: Added shield diffusers to EVERY airlock and outlet lacking them in past. Report if any still left.
add: Added some salt and pepper to the Club, both to the kitchen and on the lower level tables.
fix: Removed rogue camera in space on the third deck.
fix: Lower armory wall in brig is no longer a part of space, thus it's not getting shield on itself now.
/:cl:

Small Map Fixes

---

code/modules/goonchat/browserOutput.dm
code/modules/modular_computers/file_system/catalog.dm

Those two useless messages, especially the catalog one, are responsible for the bulk of spam in DD log.

Reduces server log spam

---

code/game/turfs/simulated/walls.dm

:cl:
add: Added spark effect on ricochet
/:cl:

Ricochet sparks

---

code/modules/sanity/sanity_mob.dm

<details>
<summary>
Going insane too easily is bad
</summary>
<hr>
Requested from Reere and approved by him
<hr>
</details>
:cl:
tweak: sanity damage modifier lowered to 0.5 from 0.7
/:cl:

lowers sanity damage modifier 

---

maps/CEVEris/_CEV_Eris.dmm

<details>
<summary>
Fixes #4210
</summary>
<hr>
Step_x was being used, this pr changes it to pixel_x which doesn't break smooth movement.
<hr>
</details>
:cl:
fix: Fixes smooth movement
/:cl:

Fixes smooth movement

---

code/modules/mob/living/carbon/carbon.dm
code/modules/reagents/reagents/medicine.dm

<details>
<summary>
Why did Haloperidol cut the maximum NSA threshold in half. WHY.  This no longer happens.
</summary>
<hr>
Bug fixes good, also this might constantly cut it in half due to affect blood, if so, I can fix that.
NIGHTCODING BAD
<hr>
</details>
:cl:
fix: fixed haloperidol making you go over the NSA threshold even faster
/:cl:

fixes haloperidol like according to the design document

---

code/modules/detectivework/tools/rag.dm

fixes damp rag aimed at mouth bypassess any mask, helmet

---

code/datums/setup_option/backgrounds/origin.dm

<details>
<summary>
Apparently Null Sector is also a faction on Overwatch, and also a thing in EVE Online, and also a game. Let's change it to something more neutral, but with same meaning.
</summary>
<hr>
<hr>
</details>
:cl:
tweak: Null Sector is now Null Space by the lore
/:cl:

Small backstory fix.

---

code/modules/sanity/breakdowns.dm

<details>
<summary>
Negative breakdowns now lasts much less. Also Stalwart restores more HP.
</summary>
<hr>
<hr>
</details>
:cl:
<!--
balance: Negative breakdowns now lasts much less.
/:cl:

Sanity balance fixes

---

code/modules/mob/living/carbon/superior_animal/giant_spider/types/nurse.dm
code/modules/reagents/reagent_containers/food/snacks/meat.dm
code/modules/reagents/reagents/medicine.dm

<details>
<summary>
sleep for 10 minutes bad
</summary>
<hr>
Holy shit this was gay, also Reere approved some kind of nerf to nurse spiders
<hr>
</details>
:cl:
tweak: nurse spiders now bite pararein instead of soporific
tweak: nurse spider meat now has pararein instead of soporific 
tweak: Dylovene now removes pararein at 0.2u a tick
/:cl:

spider toxin nerf

---

code/modules/mob/living/carbon/human/whisper.dm
code/modules/sanity/sanity_effects.dm

- Whispering now takes rank prefix into account.
- Fixed sanity whisper effect.
:cl:
fix: fixed whisper working incorrectly with rank prefixes
/:cl:

Whisper fixes

---

code/modules/cargo/exports/sheets.dm
code/modules/cargo/packs.dm
code/modules/research/experiment.dm
code/modules/research/rdconsole.dm

Wait, haven't I made a PR like that already?

Removes the last mentions of phoron

---

code/modules/research/designs/mecha_equipment.dm

Hydraulic clamp design is now unlocked by default

---

code/modules/goonchat/browserassets/js/browserOutput.js

Chat message combining now works with 20 latest messages, not only the last one. If the combined message was not the last one, it is moved forward.
Works for me on IE 8, needs confirmation on a more recent version.

Multiple message combining

---

tools/hooks/README.md
tools/hooks/dmi.merge
tools/hooks/install.bat
tools/hooks/install.sh
tools/hooks/pre-commit.hook
tools/hooks/python.sh

<details>
<summary>
Ports SpaceManiac's precommit git hooks and hook setup tools.
</summary>
<hr>
A lot of people are used to using the precommit hooks to automatically mapmerge/iconmerge so this should help let more people work on the maps.
<hr>
</details>
:cl: Garen7
add: Ports SpaceManiac's precommit git hooks and hook setup tools.
/:cl:

Ports precommit hooks from TG

---

code/game/objects/items/weapons/storage/bsdm.dm
nano/templates/bsdm.tmpl

All BSDM interactions were moved to NanoUI interface. It also shows the current owner and any contracts that will be fulfilled by sending it.

BSDM NanoUI interface

---

code/modules/biomatter_manipulation/bioreactor/platform.dm
code/modules/clothing/clothing.dm

Reverts discordia-space/CEV-Eris#4117

Revert "Changes biomatter code"

---

code/game/machinery/smelter.dm
code/game/machinery/sorter.dm
code/game/objects/items/weapons/circuitboards/machinery/smelter.dm
code/modules/mining/ore.dm
code/modules/recycling/conveyor2.dm
nano/templates/sorter.tmpl

A bunch of fixes and QoL changes for disposal system.
* Placing items on conveyors works properly now.
* Disposal sorter and smelter now work significantly faster.
* Disposal sorter can now sort corpses, and you can make it sort by object name. You can use that to make it auto-sort all the dead roaches right into bioreactor.
:cl: ACCount
tweak: Disposal sorter and smelter now work significantly faster.
add: Disposal sorter now supports sorting by name.
add: Disposal sorter now accepts corpses.
/:cl:

Garbage improvements

---

code/modules/clothing/spacesuits/rig/suits/combat.dm
code/modules/clothing/spacesuits/void/merc.dm

<details>
<summary>
</summary>
<hr>
Brought IHS RIG and SCAFsuit in line, both with armor and slowdown.
<hr>
</details>
:cl:
balance: Serbian SCAF suit now worth to use again. Roughtly brought it in line with IHS Combat RIG, it's now much more resilent to bullets and melee damage, also brought helmet and suit in line too.
balance: Slowdown of both Serbian SCAFsuit and IHS RIGsuit is now 1.3
/:cl:

SCAF voidsuit and IHS Combat RIGsuit adjustments

---

code/modules/mob/living/carbon/carbon_defense.dm

Invulnerable carbon mobs fix

---

code/modules/clothing/clothing.dm

Fixes the primary issue with clothing matter initialization, and objects that already have an existing matter list will no longer have their written over with added biomatter.
I had a conversation with Blase about it, and this is the best fix for the most immediate problems with this proc. This has all been tested in-game, and works as intended.
closes #4243
fixes #3958

Fixes primary issue with clothing matter initialization.

---

code/modules/research/destructive_analyzer.dm
code/modules/research/rdconsole.dm
nano/templates/rdconsole.tmpl

Fixes some minor issues with R&D, see commit messages. About half of them was caused by my recent PR, the other ones were present since forever.

Quick R&D fixes

---

.github/PULL_REQUEST_TEMPLATE.md

After old PR template was being basically ignored by most of the Staff, I propose a new, more light one. The changelog bot is not working here anyway.

New PR template.

---

code/game/objects/items/weapons/tools/crowbars.dm
code/game/objects/items/weapons/tools/mods/mod_types.dm
code/game/objects/items/weapons/tools/pickaxe.dm
code/game/objects/items/weapons/tools/saws.dm
code/game/objects/items/weapons/tools/scalpels.dm
code/game/objects/items/weapons/tools/screwdrivers.dm
code/game/objects/items/weapons/tools/wirecutters.dm
code/game/objects/items/weapons/tools/wrenches.dm

Tool mods now have plasteel inside them, as well as high tier tools. That makes them more valuable, because you can smelt them for guns now. 
This is basically buffs the Guild recycling, because now they will be able to have more plasteel to print guns.

Materials in tool mods.

---

code/modules/tables/interactions.dm

<details>
<summary>
Ghosts & Tables exploit fix
</summary>
<hr>
Fixes the Ghost and tables exploit.	They get only jiggle items on the same table tile.
<hr>
</details>
:cl:
fix: Ghosts are denied from having fun stealing items from a table to other table.
fix: Stunned people cannot drag and drop items on a table anymore. 
/:cl:

Ghost Drag & Drop exploit fix

---

code/controllers/subsystems/supply.dm

Another guild buff PR
Reere's personal request.

Le shuttle buff

---

code/modules/clothing/spacesuits/rig/rig.dm
code/modules/clothing/spacesuits/rig/suits/combat.dm
code/modules/clothing/spacesuits/rig/suits/light.dm
code/modules/clothing/spacesuits/rig/suits/merc.dm
code/modules/clothing/spacesuits/rig/suits/station.dm

Further Spacesuit / RIG Cleanup / Balancing
<details>
Fixed a bad return in the RIG process proc (oopsie), air tanks and modules should work again! Yay! Also changed the passive RIG power drain into a var and rebalanced the RIGs a bit with varying degrees of power drain. RIGs that aren't guaranteed to spawn are now slightly better, to be at least remotely competitive with the IHS rig. Also restored the IHS rig's bullet armor slightly and made the combat RIG better overall, but slower and with worse power drain.
</details>

Further Spacesuit / RIG Cleanup / Balancing

---

code/controllers/subsystems/processing/nano.dm
code/modules/client/asset_cache.dm
code/modules/nano/nanoui.dm

This PR should fix all UIs being sluggish as fuck while the assets are being loaded. It also fixes NanoUI windows breaking permanently if you try to open one of them while the assets are still loading. I'll wait for the confirmation of that and gut the "Fix NanoUI" button too.

Fixes for asset system and HTML UIs, including NanoUI windows

---

code/modules/clothing/head/helmet.dm
code/modules/clothing/suits/armor.dm

Agrolyte from argolyte

---

code/modules/projectiles/ammunition/bullets.dm

.25 Caseless was dropping cases, this fixes that.

Caseless ammunition now made actually caseless

---

code/game/objects/items/weapons/power_cells.dm

Seems to be bad english here.
Typo fix.
</details>

Fixes description on X-Cells

---

code/ATMOSPHERICS/pipes.dm
code/game/machinery/autolathe/autolathe.dm
code/game/objects/structures/burrows.dm
code/game/turfs/flooring/flooring.dm
code/modules/modular_computers/hardware/scanners/scanner_paper.dm
code/modules/power/gravitygenerator.dm

Fixes a runtime in autolathe and a runtime in gravity generator. Fixes some PCs being impossible to disassemble or use a disk on. Fixes #4163.

Minor fixes

---

cev_eris.dme
code/modules/mob/living/living_defines.dm
code/modules/mob/living/recoil.dm
code/modules/projectiles/_defines.dm
code/modules/projectiles/dynamic_cursor.dm
code/modules/projectiles/gun.dm
code/modules/projectiles/guns/launcher/grenade_launcher.dm
code/modules/projectiles/guns/launcher/syringe_gun.dm
code/modules/projectiles/guns/projectile.dm
code/modules/projectiles/guns/projectile/boltgun.dm
code/modules/projectiles/guns/projectile/dartgun.dm
code/modules/projectiles/guns/projectile/other/RPG.dm
code/modules/projectiles/guns/projectile/pistol/gyropistol.dm
code/modules/projectiles/guns/projectile/shotgun/sawnoff.dm

Moves recoil from being tied to the gun, to being tied to the user.
Fixes some guns not having a recoil_buildup coeff, instead they were wrongly using recoil.
<details>
</details>
<details>
</details>

Recoil tweaks

---

code/game/machinery/vending.dm

FIX: Added prices for .35 Holdout and Standard magazines

communism fix

---

code/datums/autolathe/ammo.dm
code/datums/autolathe/autolathe_datums.dm
code/game/machinery/autolathe/autolathe.dm
nano/templates/autolathe_designs.tmpl
nano/templates/autolathe_queue.tmpl

The rest of the changes are technical, so that it doesn't result in material dupe bugs.

Shotgun shells are now printed in lathes in batches of 5

---

code/modules/mob/living/recoil.dm
code/modules/projectiles/dynamic_cursor.dm

Fixes a silent fail that should not be silent.
Adds a forgotten argument.

Recoil cursor fix

---

code/datums/autolathe/circuits.dm
code/game/objects/items/weapons/autolathe_disks.dm

NT means NeoT**h**eology 
Grammar
In my defense the other packs also had the same grammar issue

corrects NeoTeology

---

code/modules/projectiles/guns/projectile/automatic/vintorez.dm

Fixes some English or attempts to make some things a bit more readable.
Changes some english.
</details>

Makes the English on the Vintorez a bit better.

---

code/game/objects/structures/signs.dm

Attempts to make the English look better.
View changed files.
</details>

Makes the English on some signs a bit better.

---

code/modules/reagents/reagents/medicine.dm

It purges spider toxins. Not sure why it shouldn't purge roach toxin.
Adds purging blattedin to dylo toxin.

dylo now purges roach toxin

---

code/modules/projectiles/guns/projectile/automatic/ak47.dm
code/modules/projectiles/guns/projectile/pistol/clarissa.dm
code/modules/projectiles/guns/projectile/revolver/revolver.dm

FS AK now no longer has illegal tech
Makarov is now illegal tech 3
All .40/.50 revolver type hand guns now deal normal harm levels
closes #3368

Corrects revolvers not having harm, FS guns having illegal tech and the /makarov/ missing illegal tech

---

code/modules/mob/living/carbon/superior_animal/roach/types/nanites.dm
code/modules/reagents/reagent_containers/food/snacks/meat.dm

4 units of dead nanites can be gotten via the Kraftwerks meat
closes  #4176

Kraftwerks meat now contains dead nanites

---

code/modules/sanity/breakdowns.dm
code/modules/sanity/sanity_lists.dm

Absolutely unsure how my previous PR got so screwed. PRing this again.
Fixes some descriptions to flow better in english and be less cringey.

Sanity Descriptors

---

code/game/turfs/flooring/flooring.dm
code/modules/mob/mob_movement.dm

Slipping in space now is only a 1% per tile
Tripping well running on underplate is now only a 5% from 20%
Slipping in space is annoying, cant be stopped and affects borgs making is a pain to do anything in 0-g even with meggie boots and walking.
20% to get a stun for not being not on the keys is really punishing, as well as kinda dumb that you can trip well in 0-g running over the plating as well

lowers odds of slipping and tripping.

---

code/modules/sanity/sanity_mob.dm

Rather than the recursion that was added in #4341

Adds a cap to however much sanity you may lose when you take damage

---

code/game/objects/items/weapons/storage/deferred.dm
code/game/objects/items/weapons/storage/storage.dm
code/modules/stashes/stash_items.dm

Was my bug, introduced in #4317. Now it's fixed.

Fixes stashes spawning empty

---

code/modules/mob/living/carbon/human/human.dm
code/modules/mob/living/carbon/human/human_defines.dm
code/modules/sanity/breakdowns.dm

Removed PTSD to see if it would help reducing lag.

Removes PTSD

---

code/game/machinery/vending.dm

FIX: added a price for a mag of lethal .35

missing prices fix /communism fix v2

---

code/modules/assembly/bomb.dm

Looks like they were broken ever since tool qualities were added.

Fixes one tank bombs being impossible to assemble

---

code/game/objects/items/oddities.dm

Oddity stats are now randomized on spawn.

Randomize oddity stats

---

.travis.yml
maps/CEVEris/_CEV_Eris.dmm
maps/submaps/dungeon_rooms/rooms/commanderoffice.dmm

<details>
</details>
<details>
</details>

Testing travis fix for map checks [DO NOT MERGE]

---

.travis.yml
maps/CEVEris/_CEV_Eris.dmm
maps/submaps/dungeon_rooms/rooms/commanderoffice.dmm

- Update travis map control
- Fix step_x/y in map files

Update travis map control (#4357)

---

code/game/objects/structures/crates_lockers/closets/secure/hydroponics.dm

Adds leather gloves to both hydroponics and Xenofuna
closes #4160

Readds leather gloves to hydro/xenofuna

---

code/game/objects/items/weapons/storage/deferred.dm

deferred crate "boxes" now appear again

---

code/datums/craft/recipes/furniture.dm
code/datums/craft/recipes/misc.dm
code/game/machinery/computer/buildandrepair.dm
code/game/machinery/constructable_frame.dm
code/game/machinery/deployable.dm
code/game/machinery/doors/simple.dm
code/game/objects/objs.dm
code/game/objects/structures/crates_lockers/closets.dm
code/game/objects/structures/crates_lockers/closets/coffin.dm
code/game/objects/structures/crates_lockers/crates.dm
code/game/objects/structures/crates_lockers/largecrate.dm
code/game/objects/structures/girders.dm
code/game/objects/structures/low_wall.dm
code/game/objects/structures/railing.dm
code/game/objects/structures/stool_bed_chair_nest/bed.dm
code/game/objects/structures/stool_bed_chair_nest/chairs.dm
code/game/objects/structures/tank_dispenser.dm
code/game/turfs/simulated/wall_types.dm
code/game/turfs/simulated/walls.dm
code/modules/library/lib_items.dm
code/modules/materials/materials.dm
code/modules/tables/tables.dm

This PR fixes some materials being lost or gained in construction/deconstruction of walls and structures. It also rewrites a lot of structure deconstruction code, enabling some structures to be recycled in smelter: lockers, computer frames and girders, for example, all smelt just fine.
I rewrote locker deconstruction code entirely - as a result, you may now use a saw or a wrench to dismantle a locker, not just welder, and lockers can be rigged with electropacks, much like the crates could have been.
This PR also improves tank dispenser code, because I just randomly did that and was way too lazy to make it a separate PR.

Conservation of mass

---

code/modules/mob/living/carbon/human/update_icons.dm

Leftover from the removal of Bay's aiming mechanic.

Removes TARGETED_LAYER

---

code/datums/autolathe/guns.dm
code/game/machinery/vending.dm
code/game/objects/items/weapons/autolathe_disks.dm
code/modules/projectiles/guns/matter/launcher/nt_sprayer.dm
code/modules/projectiles/guns/projectile/boltgun.dm
code/modules/projectiles/guns/projectile/shotgun/pug.dm
code/modules/projectiles/guns/projectile/sniper.dm
maps/CEVEris/_CEV_Eris.dmm

Now we have a Serbian Arsenal vendor on our ship, that deals in armor and bolt action rifle. It will be expanded more later. A bunch of guns changed their names in favour of new vendor, and NT cleansing carbine have a proper name now.
<details>
</details>

First Serbian vendor introduction.

---

code/modules/reagents/machinery/grinder.dm
nano/templates/grinder.tmpl

Grinder now uses NanoUI instead of a radial menu and plain HTML combo.
<details>
</details>

Grinder UI

---

code/modules/core_implant/cruciform/rituals/crusader.dm

Quickly fixes the ritual where the VIG will not properly restored when the effect ends.

Quick fix for this Crusader Call to Arms litany 

---

code/modules/sanity/breakdowns.dm

Obsession message spam is now less spammy. A message is shown once every 30-120 seconds.

Obsession cooldown

---

code/game/machinery/doors/brigdoors.dm
code/game/machinery/supply_display.dm
code/game/objects/items/devices/violin.dm
code/game/objects/items/weapons/paint.dm
code/game/objects/structures/musician.dm
code/modules/admin/DB ban/functions.dm
code/modules/flufftext/TextFilters.dm
code/modules/hivemind/machines.dm
code/modules/hivemind/mobs.dm
code/modules/mob/living/carbon/human/examine.dm
code/modules/mob/living/silicon/pai/examine.dm
code/modules/mob/living/silicon/robot/examine.dm
code/modules/mob/mob_helpers.dm
code/modules/modular_computers/file_system/programs/security/digitalwarrant.dm
code/modules/research/xenoarchaeology/finds/finds_talkingitem.dm
code/modules/scripting/Implementations/_Logic.dm
code/modules/scripting/Options.dm
code/modules/scripting/Scanner/Scanner.dm

lentext has become deprecated.

lentext to length

---

maps/CEVEris/_CEV_Eris.dmm

Changes for chemistry room, because current lay out do not give any place for people to work there freely.
<details>
</details>

New map for chemestry.

---

code/modules/projectiles/guns/projectile/boltgun.dm

Mosin man good
Buffs the bolty to deal more melee damage.
</details>

Mosin melee buff

---

code/game/objects/effects/decals/Cleanable/misc.dm
code/game/objects/effects/mines.dm
code/modules/paperwork/paper.dm
code/modules/projectiles/guns/projectile/shotgun/bull.dm
code/modules/projectiles/guns/projectile/shotgun/pump.dm

Fixes ammo casings being on wrong plane, also fixes paper having its own layer. Adjusted some misc. cleanables to use layer defines.

Fixes ammo casings being on wrong plane

---

code/game/dna/dna2.dm

Removal of redefenition in dna2.dm

Removing redefinition

---

code/modules/mob/living/carbon/superior_animal/roach/types/fuhrer.dm
code/modules/mob/living/carbon/superior_animal/roach/types/hunter.dm
code/modules/mob/living/carbon/superior_animal/roach/types/nanites.dm
code/modules/mob/living/carbon/superior_animal/roach/types/tank.dm
code/modules/mob/living/carbon/superior_animal/roach/types/toxic.dm
code/modules/mob/living/carbon/superior_animal/superior_animal.dm

Fuhrer roaches may no longer get bested by a soap bar, panzers likewise are too heavy to slip either. Hunter roaches move slightly faster than the rest now, nanite roaches may now survive in the vacuum of space, nanite locust swarms are now non-dense, and toxic roaches no longer receive skin burns from toxins (plasma) in the air.

Roach tweaks

---

code/controllers/subsystems/jobs.dm
code/datums/outfits/jobs/job.dm

The code for spawning secret documents in inventory was in a really wrong place.

Secdoc spawn fix

---

code/modules/mob/living/carbon/superior_animal/roach/types/nanites.dm

Roach has no breath type, but it's still calling minimum breath which is used in certain checks.

Roach Runtime Fix

---

code/game/objects/items/devices/radio/beacon.dm
code/game/objects/items/weapons/AI_modules.dm
code/game/objects/items/weapons/storage/wallets.dm
code/game/objects/random/packs.dm
code/game/objects/random/rig.dm
code/modules/clothing/chameleon.dm

Some small fixes regarding game balance.
<details>
* Old commented code removed.
* The cloak is now removed from random suit part pool. It was SUPPOSED to be removed along with ninja suit, but was forgotten.
* Chameleon gun got insane values of illegal tech for some bizarre reason, removed now.
* Some AI module also got nerfed to more sane value.
* There will be much less money found in junk piles now, from 500 to 1000, instead of 1000 to 5000.
* Wallets now can hold discs and syringes.
</details>

Fixes regarding game balance

---

code/__DEFINES/mobs.dm
code/modules/mob/living/living.dm

Bloodloss is incredibly dangerous, more so than it should be because the oyxloss from it cannot be stopped even with the best anti oxyloss drugs attainable. This cuts bloodloss values down a bit, but does not nerf the effects. Humans have 560 units of blood, all my values below are in units
<details>
<summary>Chopped some values down</summary>
(ALL IN UNITS)
Wound bleed multiplier moved from 0.02 to 0.01
Open_organ bleed amount cut from 1.5 to 0.5
Bloodloss from pulling people cut down from 1 to 0.5
</details>

unloosed the blood loosing

---

code/modules/clothing/spacesuits/void/merc.dm

Was using the helmet for the rigsuit.

Fixes incorrect item state

---

code/game/machinery/telecomms/telecomunications.dm
code/game/objects/items/devices/organ_module/active/multitool/miner.dm
code/game/objects/items/devices/scanners/scanners.dm
code/game/objects/items/weapons/tools/pickaxe.dm
code/modules/clothing/spacesuits/rig/modules/utility.dm
code/modules/mining/drilling/scanner.dm
code/modules/mob/living/silicon/robot/robot_modules.dm
maps/CEVEris/_CEV_Eris.dmm

* Comm relays now work on the shuttles. Fixes #1315.
* Mining drills consume less fuel now.
* Hulk now has a large fuel tank for the drills.
* Ore scanner is a scanner subtype now, which means that it uses power cells, fits in pockets, prints ore data and sucks.

Mining pain reduction

---

code/game/objects/structures/crates_lockers/crates.dm
code/modules/mob/living/simple_animal/hostile/mimic.dm

Oversight from when I moved crates out of the storage.dmi and into crate.dmi

Fixes certain objects pulling from wrong the dmi

---

code/modules/projectiles/guns/projectile/pistol/giskard.dm
code/modules/projectiles/guns/projectile/pistol/olivaw.dm

Changes designation on Olivaw to be consistent with the Molly, as it too should be considered a machine pistol by designation.
Changes description on both guns. Guns are lethal m'kay?
Changes descriptions.
</details>

Changes descriptions on the Giskard and Olivaw

---

code/modules/clothing/masks/gasmask.dm

We need to set up Travis to screech at those.

Fixes a compile warning in master

---

code/game/antagonist/station/changeling.dm
code/modules/clothing/shoes/jobs.dm
code/modules/mob/living/carbon/human/unarmed_attack.dm
code/modules/organs/blood.dm
code/modules/reagents/reagents/core.dm
code/modules/reagents/reagents/medicine.dm
code/modules/reagents/recipes.dm

Adds a new feature that allows IH to valid hunt lings better through chemistry and blood sampling.
Also jackboots have had their forced moved down from 7 to 3.
<details>
There are two new chemicals with this, negative ling marker, and positive ling marker, the first can be made with Ryetalyn and carbon, and the second can be made ONLY with the negative ling marker and ling blood. The first chemical requires over 400 degrees to form, and the second requires over 700 degrees. If the positive ling marker forms at all, it means the blood is from a ling, and you should valid them to death. 
</details>

Adds new ling blood checking feature that allows you to determine whose valid and who is not, also fixes jackboots being too forceful.

---

code/stylesheet.dm

<details>
</details>
<details>
</details>

Makes medical voice a little darker, to differentiate it from common more.

---

code/__HELPERS/logging.dm
code/modules/admin/admin.dm
code/modules/error_handler/error_handler.dm

Makes runtimes readable and informative and adds admin action logging - all relayed to discord.

Webhook improvement

---

code/game/objects/items/weapons/tools/simple_weapons.dm

Apparently, it's a line ending issue. Let's hope that makes it disappear for good.

Does some voodoo magic to a cursed file

---

code/game/machinery/telecomms/broadcaster.dm
code/game/machinery/telecomms/machine_interactions.dm
code/game/machinery/telecomms/presets.dm
code/game/machinery/telecomms/telecomunications.dm

* Fixes certain telecomm channels not working.
* Makes telecomm machines deconstruct the same way as every other machine, as opposed to the snowflake deconstruction they used before.
* Renames ship's telecomm network to "eris". It was "tcommsat" before, and telecomm sat is long gone.

Fixes telecomms

---

code/__DEFINES/components.dm
code/_onclick/click.dm
code/game/atoms.dm
code/game/objects/items.dm
code/game/objects/items/weapons/tools/_tools.dm
code/game/objects/items/weapons/tools/mods/_upgrades.dm
code/game/objects/items/weapons/tools/mods/mod_types.dm
code/modules/sanity/breakdowns.dm
code/modules/sanity/sanity_atom.dm

Changes tool upgrades over to components, so anything can become a tool upgrade
Moves tool upgrades to item level, so anything can be upgraded
Changes some SEND_SIGNAL logic, so it stops feeding the source as its first argument to everything
<details>
</details>
<details>
</details>

Changes tool upgrades to components

---

code/datums/datum_click_handlers.dm
code/game/turfs/simulated/walls.dm

Fixed a runtime on simulated walls when shot with projectile weapons way too much and fixed the exploit with full auto weapons for cham proj and closets
Closes #3191 
<details>
</details>
<details>
</details>

[FIX] Wall runtime fix and full auto exploit fix

---

code/modules/projectiles/guns/energy/charge.dm

This should handle some strange edge cases of being able to stash the energy gun while it's fully charged.

Energy gun overcharge fixes

---

code/controllers/subsystems/vote.dm
code/game/antagonist/antagonist_print.dm
code/game/jobs/access_datum.dm
code/game/machinery/constructable_frame.dm
code/game/objects/items/weapons/cigs_lighters.dm
code/modules/admin/holder2.dm
code/modules/research/rdmachines.dm

See commit messages for details.
It fixes some spammy runtimes, so I'd like to see it merged before the launch.

A batch of fixes

---

code/datums/uplink/medical.dm
code/game/objects/items/weapons/storage/firstaid.dm
code/game/objects/random/medicine.dm
code/modules/reagents/reagent_containers/pill.dm

Uplink surgery kit now comes with advanced tools and two pill bottles. One contains ProSurgeon pills, the other is loaded with Tramadol.
This should make surgery (and self-surgery) less painful for antags, in more ways than one.

Improves uplink surgery kit

---

code/game/machinery/telecomms/logbrowser.dm
code/game/machinery/telecomms/telecomunications.dm
code/game/machinery/telecomms/telemonitor.dm
code/game/machinery/telecomms/traffic_control.dm

Those things were made with just one Z level in mind, and were broken since forever.

Fixes telecomm computers being unable to find machines

---

code/modules/admin/admin.dm

reduces the ammount of logging 

---

code/modules/sanity/breakdowns.dm

Removed an extra argument that is no longer needed due to signal changes in #4473.

Runtime fix

---

code/__DEFINES/_compile_options.dm

Quickmerge this and go update the servers.

Fixes multi-z ZAS being disabled

---

code/modules/admin/admin.dm
code/modules/admin/verbs/adminpm.dm
code/modules/webhook/webhook.dm

Separates logs in different channels for discord

---

code/_onclick/click.dm
code/game/objects/items/weapons/tools/_tools.dm
code/game/objects/items/weapons/tools/mods/_upgrades.dm
code/game/objects/items/weapons/tools/mods/mod_types.dm

Fixes being unable to attach heatsinks to tools
Fixes being unable to attach an upgrade to an item in hand
Fixes being unable to remove upgrades
<details>
</details>
<details>
</details>

Tool upgrade fixes

---

cev_eris.dme
code/game/objects/random/closet.dm
code/game/objects/random/cloth.dm
code/game/objects/structures/crates_lockers/closets/utility_closets.dm
code/modules/cargo/exports/gear.dm
code/modules/clothing/spacesuits/bomb.dm
code/modules/clothing/spacesuits/spacesuits.dm
code/modules/clothing/suits/bio.dm
code/modules/clothing/suits/utility.dm
maps/CEVEris/_CEV_Eris.dmm

* Firesuit, biosuit and radsuit have all received a noticeable slowdown reduction. They have less slowdown now than space suits do.
* Bomb suit is now a space suit subtype, because bombs tend to cause depressurization. It has also received a slowdown reduction.

Makes utility suits less garbage

---

code/datums/contract.dm
code/datums/objective/steal.dm
code/datums/outfits/jobs/engineering.dm
code/game/objects/items/weapons/autolathe_disks.dm
code/game/objects/items/weapons/storage/boxes.dm
code/game/objects/structures/window.dm
code/game/sound.dm
code/modules/mob/living/carbon/carbon_defense.dm
code/modules/mob/living/carbon/human/human.dm
code/modules/mob/living/silicon/robot/robot_modules.dm
code/modules/power/cable.dm
code/modules/power/generator.dm
code/modules/power/power.dm
code/modules/power/sensors/powernet_sensor.dm
code/modules/reagents/reagent_containers.dm
code/modules/shield_generators/floor_diffuser.dm
code/modules/shield_generators/shield.dm
maps/CEVEris/_CEV_Eris.dmm

A bunch of fixes - mostly for runtime errors, but there are also some map fixes and other crap. See commit log for details.
Fixes #4184.

New year fixes

---

code/modules/mob/living/carbon/resist.dm

Resist cooldown was accidentaly removed by #4356, this PR returns it.

Fixes resist cooldown

---

code/modules/mining/mine_items.dm
maps/CEVEris/_CEV_Eris.dmm

* Fixed pipe in chem storage.
* Shotgun is removed from mining barge.
* Shotguns are now stored inside lockers.

Some map changes

---

code/modules/mob/death.dm

Your chainsaw is now far less likely to experience a bruh moment.

Fixes weapons disappearing when embedding and gibbing a mob at the same time

---

code/game/objects/items/devices/chameleonproj.dm

Remake of #4430 now with the ability to examine the cell
<details>
</details>
<details>
</details>

Adds a cell requirement to the chameleon projector

---

code/game/machinery/excelsior/ex_teleporter.dm

* Excelsior teleporter now works significantly faster by default.
* Excelsior teleporter can now be upgraded. With top tier components and an Atomcell, it works 4 times faster than it normally would.
Closes #4180

Improves excelsior teleporter

---

code/modules/mob/living/carbon/human/life.dm

Rejuvenate now resets your sanity to maximum

---

code/modules/mob/living/carbon/give.dm

Fixes being able to give people offhands.

Abstract Items Can No Longer Be Given

---

code/game/objects/structures/crates_lockers/closets.dm

Cognition can now be used to skip steps in closet hacking, and open it right away, with chance. Tested and working.

More use for Cognition.

---

cev_eris.dme
code/__HELPERS/game.dm
code/__HELPERS/names.dm
code/__HELPERS/unsorted.dm
code/_global_vars/mapping.dm
code/_global_vars/misc.dm
code/controllers/evacuation/evacuation.dm
code/controllers/subsystems/mapping.dm
code/datums/topic/world.dm
code/game/area/Space Station 13 areas.dm
code/game/gamemodes/events/prison_break.dm
code/game/machinery/bluespaceartillery.dm
code/game/machinery/computer/prisoner.dm
code/game/machinery/turret_control.dm
code/game/objects/items/weapons/implant/implants/death_alarm.dm
code/modules/mob/observer/ghost/ghost.dm

This PR is the start of a few PRs designed to enhance performance of the server. This one caches `world/Topic?status` to avoid it being called in excess, as well as making a list of all areas in world to use when needed, instead of having to scan the entire world each time, which is quite expensive

Performance tweaks 1

---

code/datums/craft/step.dm

Fixes being able to spam-click one requirement of a crafting recipe to skip other steps
This exploit would let you get past a lot of equipment gates, such as requiring adhesive.

Crafting exploit fix

---

code/modules/multiz/structures.dm

The check in the code wasn't correctly written, 2 param have been swapped. I fixed that with a single parameter, so underlying code can deal with it since it got called from structure so the var/user is good and their code already deals with it.
Fixes #3329

[FIX] Drone Ladder fix

---

code/modules/client/preference_setup/loadout/lists/headwear.dm

fixes wrong name in allowed roles

---

code/datums/craft/recipes/tools.dm
code/datums/craft/recipes/weapon.dm

- Changes the improvised saw recipe to a rod and a cutting tool from a rod, 2 shrapnel, and duck tape
- Changes the improvised welding tool to an air tank and igniter with duct tape(the same thing as what it was but without 2 pipes
Reere said the crafting recipes for improvised tools were too hard, the only two issues I saw were these.

Makes some improvised tool recipies easier

---

code/modules/ghosttrap/trap.dm
code/modules/mob/living/simple_animal/borer/borer.dm
code/modules/mob/living/simple_animal/borer/borer_powers.dm

* New borer abilities: read mind and write mind. You can now learn skills, languages and other information by stealing from your victim's brain. You can also write what you learned back, if you are feeling helpful.
* Borers can now inject more chemical types, and the injection message provides more feedback.
* Borers are a bit less slow now.
* Borer vision now ignores darkness.
* Borers regenerate health slowly while inside a host.
* You can no longer keep respawning as a borer an unlimited amount of times.

Cortical borer update

---

code/modules/mining/mine_items.dm

Fixes missing shotguns and ammunition

shotguns is back on menu

---

code/game/objects/items/weapons/cigs_lighters.dm
code/modules/sanity/sanity_mob.dm

* You now gain more rest from sources in your desires, and a bit less from other sources.
* Smoking was buffed to give more rest, with high quality cigars and smoking pipes giving you even more. 1-2 cigarettes should be enough to level your insight now.

Tweaks insight rest rates

---

code/modules/projectiles/gun.dm
code/modules/projectiles/gun_hud_actions.dm
code/modules/projectiles/guns/energy.dm
code/modules/projectiles/guns/projectile.dm
nano/templates/weapon_stats.tmpl

Weapon info tab, similar to the tool info tab. Tells you information about the gun you're using.
<details>
</details>

Gun info tab

---

code/modules/clothing/under/jobs/security.dm

Fix IH Commander suit make unifor invisible

---

code/game/objects/items/weapons/space_harpoon.dm
code/modules/research/nodes/bluespace.dm

Harpoons now have a 10-11~ second charge up before they teleport you/items and the research cost has been increased by 10 points.

Harpoon rebalance

---

code/game/objects/items/weapons/tools/mods/mod_types.dm

The old one was weird and factually wrong.

New name and description for AI toolmod.

---

code/game/objects/structures/salvageable.dm

le disks to the salvageable machinery

---

code/game/objects/items/weapons/space_harpoon.dm

Diamonds removed and bug fixed

Harpoon Fixes

---

code/game/atoms.dm
code/game/objects/objs.dm
code/game/turfs/turf.dm
code/modules/hivemind/mobs.dm
code/modules/mob/living/simple_animal/friendly/spiderbot.dm
code/modules/mob/living/simple_animal/hostile/onestar_drone.dm
code/modules/mob/living/simple_animal/worm.dm

Created atom proc update_icon() and refactored bad code formating in worm.dm <details>Ignore diff, he writes some crap in worm.dm</details>

update_icon for atoms

---

code/game/jobs/job/engineering.dm
code/modules/clothing/spacesuits/void/station.dm

Technomancers actually get payed now
Technomancers now have 5 VIG
Engineering voidsuits are about as fast as mining voidsuits now (Was slower than a deactivated RIG earlier)
Engineering voidsuits now have protection against temperature (Rejoice TE for now you can send your workers to deal with plasma leaks instead of yourself)

Techno buffs 

---

cev_eris.dme
code/game/objects/items/weapons/tools/mods/_defines.dm
code/game/objects/items/weapons/tools/mods/_upgrades.dm
code/game/objects/items/weapons/tools/mods/mod_types.dm

Upgrade defines

---

code/modules/projectiles/ammunition/magazines.dm

Because someone forgetting stuff like a cool dude

Californiamag is no more

---

maps/CEVEris/_CEV_Eris.dmm

Some high-traffic areas for the AI to be able to use, mainly within the Medbay.

Adds some additional holopads.

---

code/modules/projectiles/projectile/bullets.dm

Bullets still have a 100% chance of hitting the poor sod you have in a headlock but have a 50% chance of passing through him and hitting you (in theory, i would like to test this code to be 100% sure)

Human shield rebalance (Needs Test)

---

code/modules/biomatter_manipulation/biogenerator.dm
maps/CEVEris/_CEV_Eris.dmm

Connects the biogen to the main power grid and doubles its power output

Biogen buff

---

code/game/machinery/vending.dm

SMG mag price fix

---

code/modules/clothing/clothing.dm
code/modules/clothing/gloves/stungloves.dm
code/modules/clothing/head/armor.dm
code/modules/clothing/spacesuits/void/void.dm

Fixes strange interaction between the clothing information button and the toggle helmet function on voidsuits

Voidsuit fix

---

code/game/machinery/smelter.dm
code/game/objects/items/weapons/cigs_lighters.dm

Fixes a smelter bug that resulted in an infinite loop

---

code/modules/clothing/clothing.dm

Yet more clothing UI action fixes

---

code/modules/clothing/gloves/stungloves.dm

Fixes stungloves toggling

---

.travis.yml
code/__HELPERS/files.dm
code/__HELPERS/sanitize_values.dm
code/__HELPERS/text.dm
code/__HELPERS/unsorted.dm
code/game/machinery/navbeacon.dm
code/game/machinery/status_display.dm
code/game/objects/items/devices/PDA/PDA.dm
code/game/objects/structures/musician.dm
code/modules/goonchat/browserOutput.dm
code/modules/maps/tg/reader.dm
code/modules/mob/language/language.dm

Ported straight from other codebases that migrated to 513. 
Hopefully no security issues. 
Other discovered unicode issues shall be reported and fixed manually because holy fuck I ain't doing a mass replace.

Unicode awareness - part one (Also updates Travis to 513)

---

cev_eris.dme
code/__DEFINES/misc.dm
code/__DEFINES/subsystems-priority.dm
code/__DEFINES/subsystems.dm
code/__HELPERS/logging.dm
code/controllers/subsystems/chat.dm
code/modules/goonchat/browserOutput.dm

Ports chat subsystem from tg. It works. Sorta.
The guns don't mcfucking kill your client now. Just you.
Been tested and doesn't murder the performance.

Chat Subsystem

---

code/modules/reagents/reagents/toxins.dm

increases metabolism by 10, since being knocked down for 10 minutes minimum is quite unfun

sedatives nerf

---

code/modules/power/cell.dm

[FIX] Stops the infinite admin log while the mech is walking with a riggered cell

---

.github/PULL_REQUEST_TEMPLATE.md

To cement what was agreed upon.

Guidelines in pull request form

---

code/game/objects/items/weapons/stunbaton.dm

Fixes missing stunbaton icon

---

code/game/machinery/doors/airlock.dm

Fixes #4046. Fixes #2827 I think.

Fixes certain airlock block items being impossible to remove

---

code/datums/uplink/badassery.dm
code/modules/clothing/accessories/badges.dm

Adds badge exclusive for Ironhammer marshalls in uplink. Now you can show who is the real authority on the ship.
can be found in badassery category.

IHS Marshall badge

---

code/controllers/subsystems/chat.dm

Fixes #4604 
More fix to come : like removing redundant code.

Quickie chat fix

---

code/modules/reagents/recipes.dm

Per request, new recipe for toxins. Recipe for nicotine required toxin, but it was impossible to craft before, and was difficult to obtain, both in pure form from medical and from spoiled food in maints.
I've decided to give it 5u plasma as catalyst to make it a tiny bit harder to obtain, as poisoning is quite annoying.

Per request, new toxin recipe

---

code/modules/reagents/recipes.dm

It's my first pull request ever, decided for something easy. It's a recipe for nicotine, same as in cigarettes.

Adds a chemial recipe for nicotine.

---

code/datums/contract.dm
code/modules/mob/mob_grab.dm

This PR rewrites two chunks of code to fix two fairly common runtime errors.

Runtime fixes

---

code/game/objects/items/weapons/cigs_lighters.dm

It's a fix for the cigarette bug that pushed all ingredients in 25 seconds. Now it's one tick every 10 seconds

Cig fix, now every 10 seconds

---

code/datums/craft/recipes/weapon.dm
code/game/objects/items/weapons/melee/energy.dm

Laser Sabre

---

code/game/objects/items/oddities.dm

Some Oddities have descriptions with poor grammar, misspellings, missing words, or poor localization. This fixes that. (no offence to whoever wrote them)
<details>
Fixes minor grammar, spelling, and localization issues.
Also fixes the Obscure Report's broken icon.
</details>

Minor grammar, spelling, and localization fixes.

---

code/modules/modular_computers/file_system/programs/antagonist/uplink.dm
code/modules/modular_computers/file_system/programs/engineering/shield_control.dm

This PR is fixing the actual fuckery from the variable host not returning the correct type.

[FIX] Uplink and Shield program

---

code/modules/shield_generators/shield.dm

Changes the shiled layer to BELOW_OBJ_LAYER so players can:
-Target mobs on shields
-Pick up items on shileds

Shield layer change

---

code/modules/surgery/surgery.dm

Fixes nanopaste not working for repair of robotic organs

---

code/modules/reagents/recipes.dm
nano/templates/catalog_entry_drink.tmpl
nano/templates/catalog_entry_reagent.tmpl

I thought it was broken at some point, but no, it just was never added back when MIRC was made. Weird.
Now it's fixed though. Minus one reason to visit wiki or ask around in discord.

Makes MIRC display reaction temperatures

---

code/__DEFINES/subsystems.dm
code/controllers/subsystems/inventory.dm

Seems like inventory SS was initialized too late, resulting in runtimes.

Fixes some character setup runtimes

---

code/modules/reagents/reagents/dispenser.dm
code/modules/reagents/recipes.dm

Remember the old one with a lot of lines no more!
Does basically the same as the last pull but changed into one line
and i changed paracetamols and tramadols recipes around.

Eris alcohol fix two

---

code/modules/projectiles/guns/projectile/automatic.dm
code/modules/projectiles/guns/projectile/automatic/ak47.dm
code/modules/projectiles/guns/projectile/automatic/atreides.dm
code/modules/projectiles/guns/projectile/automatic/c20r.dm
code/modules/projectiles/guns/projectile/automatic/dallas.dm
code/modules/projectiles/guns/projectile/automatic/drozd.dm
code/modules/projectiles/guns/projectile/automatic/lmg.dm
code/modules/projectiles/guns/projectile/automatic/maxim.dm
code/modules/projectiles/guns/projectile/automatic/molly.dm
code/modules/projectiles/guns/projectile/automatic/sol.dm
code/modules/projectiles/guns/projectile/automatic/straylight.dm
code/modules/projectiles/guns/projectile/automatic/sts35.dm
code/modules/projectiles/guns/projectile/automatic/vintorez.dm
code/modules/projectiles/guns/projectile/automatic/wintermute.dm
code/modules/projectiles/guns/projectile/automatic/z8.dm
code/modules/projectiles/guns/projectile/automatic/zoric.dm
code/modules/projectiles/guns/projectile/boltgun.dm
code/modules/projectiles/guns/projectile/shotgun/bojevic.dm
code/modules/projectiles/guns/projectile/shotgun/bull.dm
code/modules/projectiles/guns/projectile/shotgun/doublebarrel.dm
code/modules/projectiles/guns/projectile/shotgun/gladstone.dm
code/modules/projectiles/guns/projectile/shotgun/pump.dm
code/modules/projectiles/guns/projectile/shotgun/regulator.dm
code/modules/projectiles/guns/projectile/shotgun/sawnoff.dm

Follow up to #4710. Now you don't need two-handed grip on shotguns and rifles (or any other ballistic weapon for rare exception) to shoot them, but penalty for one-handed increased. Establishing following standart for now:
SMGs - 5.
Bullpup Rifles/Carbines/Compact Shotguns - 10.
Automatic Rifles/Full Sized Shotguns - 15.
Bolt rifle/Automatic Shotgun/Etc - 20.
LMG - 30.
There are some special cases. This is also susceptible to changes after i test it further later.

Gun Two-Handed Stuff

---

code/game/objects/items/weapons/cigs_lighters.dm

Introduced in #4590 - shame on me!

Fixes cigarettes dropping broken items instead of cig butts

---

code/modules/clothing/spacesuits/rig/modules/utility.dm
code/modules/surgery/autodoc.dm
nano/templates/autodoc.tmpl
nano/templates/autodoc_capitalism.tmpl

Not sure if it was a feature, but the capitalist autodoc would never actually heal you
Adds some chat feedback for the user, *to help with debugging other issues in the future*
Changes the text in the autodoc module to say "Close wounds" rather than "Treat wounds" as there was some confusion between the two

Rig-mounted Autodoc fixes and tweaks

---

code/__DEFINES/mobs.dm
code/modules/mob/living/carbon/brain/brain_item.dm
code/modules/mob/living/carbon/human/death.dm
code/modules/mob/living/carbon/human/human.dm
code/modules/mob/living/carbon/human/human_organs.dm
code/modules/mob/living/carbon/human/species/species.dm
code/modules/mob/living/carbon/human/update_icons.dm
code/modules/organs/external/_external.dm
code/modules/organs/external/dismemberment.dm
code/modules/organs/external/organ_icon.dm
code/modules/organs/external/stump.dm
code/modules/organs/external/subtypes/standard.dm
code/modules/organs/internal/_internal.dm
code/modules/organs/internal/borer.dm
code/modules/organs/internal/eyes.dm
code/modules/organs/internal/machine.dm
code/modules/organs/internal/xenos/eggsac.dm
code/modules/organs/internal/xenos/hivenode.dm
code/modules/organs/organ.dm
code/modules/surgery/internal.dm

This PR splits processes that replace organs in mob and processes that replace organs in body parts, which is needed for some future stuff. It also fixes some old bugs.
It also, likely, adds a lot of nasty new bugs, so brace yourselves. Normally it would be a monday merge, but mid-week merge should do.

Refactors some organ stuff

---

cev_eris.dme
code/modules/projectiles/guns/projectile/shotgun.dm
code/modules/projectiles/guns/projectile/shotgun/bull.dm
code/modules/projectiles/guns/projectile/shotgun/pump.dm

Updates the pump code, giving players the abilty to get rid of bullets faster while still limiting chat spam. Also adds shotgun.dm

Shotgun Fix (New)

---

code/game/objects/items/weapons/tools/mods/mod_types.dm

I asked somebody to remove this a while ago, but they didn't seem to do it.

Removes the flat 4 force modifier increase from the hammer mod

---

code/modules/multiz/ztravel/jetpack.dm

Removes slip from jetpack z-level travel

---

code/game/objects/buckling.dm
code/modules/mob/living/simple_animal/friendly/mouse.dm

Reduces mouse damage to 0 and disables them buckling larger mobs

---

code/modules/goonchat/browserassets/js/browserOutput.js

Ports from https://github.com/tgstation/tgstation/pull/49867 details inside the link

[URGENT FIX] Ports the XSS exploit fix from tgstation

---

code/datums/craft/recipes/tools.dm
code/game/objects/items/weapons/tools/mods/mod_types.dm

- Dupe of plasteel when crafting tool mods is no more.
- Adjusted some recipes.

Toolmod plasteel dupe crafting fix

---

code/modules/clothing/chameleon.dm

probably an oversight
<details>
gives chameleon mask hide face/eyes.
</details>
</details>

gives chameleon mask hide face/eyes

---

code/datums/craft/recipes/furniture.dm
code/game/objects/structures/crates_lockers/crates.dm

Price for crates adjusted and material changed to steel

---

code/game/sound.dm

Shamelessly stolen from https://github.com/NebulaSS13/Nebula/pull/189. This adds softness and echoing effects to sounds that are on another z-level from you.  
Video example of it on Eris here:
https://streamable.com/un1lh

Redoes Multiz Sound

---

code/modules/mob/mob_grab.dm

The new code will include a function to calculate the slowdown for each grab at this moment.
New suggestions are welcomed.
<details>
</details>
<details>
</details>

[FIX] Grab slowdown

---

code/game/sound.dm

Should fix the `bad arg name` runtime for `use_pressure` in repeating sounds.
^ This one

Fixes Runtimes In Repeating Sound (Without Conflicts)

---

code/__HELPERS/matrices.dm
code/game/objects/random/random.dm

Fixes the define so dmm-tool could render the map for affected
FIX: #4219

Fixes the code to make map renderer work

---

code/datums/contract.dm
code/game/machinery/cryopod.dm

* Fixes cryopod runtiming out on despawn
* Makes cryopod remove antag contracts targeting the despawned mob, like it removes the regular antag objectives.

Cryopod fix

---

code/game/mecha/equipment/tools/medical_tools.dm
code/modules/reagents/reagents/nanites.dm

Fixes partial pathing in medical_tools.dm
Fixes being able to dupe nanites, by making them a solid rather than a liquid

Nanite duping fix

---

code/modules/power/supermatter/supermatter.dm

Such as when a few Hatton rounds are used on it, for instance

The supermatter now explodes when it is destabilized by an explosion

---

code/modules/sanity/breakdowns.dm

Salvages obsession being able to pick an oddity
Fixes some logic fails in obsession

Obsession changes

---

code/modules/biomatter_manipulation/bioreactor/platform.dm

Fixes being able to drag anything into the bioreactor, including parts of the bioreactor
Fixes some of the bad english

Bioreactor fixes

---

code/modules/mob/mob_helpers.dm

Fixes stammer, slurring, gibberish, starring, and ninjaspeak for unicode language

More russian language fixes

---

code/game/objects/items/weapons/space_harpoon.dm

Kills Russian translation for something more English friendly.
changed to "One of the last things developed by old Nanotrasen, this harpoon serves as a tool for short and accurate teleportation of cargo and personnel through bluespace."
<details>
</details>

Makes the english on the Harpoon better.

---

code/modules/biomatter_manipulation/bioreactor/biotank.dm

Biotank size increase to match the biogens increased power and to stop it from breaking contantly

---

code/game/antagonist/antagonist_factions.dm

Previously, Excel could talk to other excel members when unconscious or dead

Fixes Excel being able to talk over faction-comms when dead or unconscious

---

maps/CEVEris/centcomm.dmm

Forgot to do so in the PR adding them. There's six satchels which will spawn on a previously empty rack, one each for every Mercenary.

Adds military satchels to Serbian base

---

maps/CEVEris/_CEV_Eris.dmm

Some pipes in the Engine Room have been renamed for clarity, and the Wasting Room vent has been set-up properly from the get-go.
The disposal "Yeetlet" should no longer get mobs stuck when the shields are on. Certain spots near the IH Lobby where walls were showing under open space, were covered with hulling.
A EFTPOS scanner was added to the Bar Backroom.

Some map tweaks

---

code/game/gamemodes/roleset/faction/mercenary.dm

At least 5 players need to be online for serbs to spawn

---

code/game/machinery/autolathe/autolathe.dm
nano/css/shared.css
nano/templates/autolathe.tmpl
nano/templates/autolathe_designs.tmpl
nano/templates/autolathe_queue.tmpl

Tweaks autolathe license UI

---

cev_eris.dme
code/modules/client/preference_setup/global/preferences.dm
code/modules/mob/floating_say.dm
code/modules/mob/living/say.dm

Reere asked for it, so here it is. Made by Chinsky and shamelessly stolen from https://github.com/NebulaSS13/Nebula/pull/349. All I did was make it compatible with Eris code. This includes making it a preference so if you hate it you can just turn it off and never have to see it. No runtimes encountered in this version of it but keep your eyes peeled.
<details>
Normal talking.
Shouting!
Talking into radio
</details>

Adds floating chat messages

---

code/game/objects/effects/spiders.dm
code/game/objects/items/devices/PDA/PDA.dm
code/game/objects/items/weapons/cigs_lighters.dm
code/game/objects/structures/medical_stand.dm
code/modules/biomatter_manipulation/bioreactor/platform.dm
code/modules/core_implant/cruciform/cruciform.dm
code/modules/mob/living/carbon/carbon_defense.dm
code/modules/mob/living/damage_procs.dm
code/modules/mob/living/living_defense.dm
code/modules/vehicles/cargo_train.dm

Fixes the lack of logging due wrong line plus adding messages to various apply_damage for more messages
<details>
</details>

[FIX] Fixes the lack of logging for autopsy

---

code/__DEFINES/is_helpers.dm
code/game/machinery/portable_turret.dm

Thought I'd throw it under "check for anomalies", as it seemed to fit the best.

Blitzshells can now be targetted by AI-core turrets

---

code/game/antagonist/outer/mercenary/merc_faction.dm
code/game/objects/items/weapons/storage/boxes.dm

Changes 14.5mm box to .60 Anti Material Shells box. Changes L6 SAW mention in serb welcome blurb to Pulemyot Kalashnikova.

small language fixes

---

code/game/machinery/sorter.dm

Seems when I hastily fixed the sorter system, I should've read through it better, as I alienated two different methods of sorting (By name, and by contained reagent)
This PR fixes that.

Fixes the sorter selection system

---

code/game/gamemodes/storyteller.dm
code/game/gamemodes/storytellers/chronicler.dm
code/game/gamemodes/storytellers/healer.dm
code/game/gamemodes/storytellers/jester.dm

LONG AGO IN A DISTANT LAND
SOMEONE FORGOT THAT MULTIPLYING A POSITIVE NUMBER BY A POSITIVE NUMBER THAT IS LESS THAN 1 MAKES IT SMALLER.
Yeah. So, myster to it vomiting endless amount of the same antag over and over and over is solved.
Due to faulty math storyteller's events LOST weight every time they got called, making them cheaper to call and repeating the cycle.

Cures current storytellers from severe case of not knowing what math is 

---

code/modules/sanity/sanity_lists.dm

:cl:
spellcheck: Removed a weird symbol from sanity messages.
/:cl:

Removes weird symbol in sanity messages

---

.github/workflows/compile_changelogs.yml
.github/workflows/make_changelogs.yml

:cl:
fix: Beebot is no longer usurping our changelog
/:cl:

Removes beebot, adds nepotism

---

.github/workflows/compile_changelogs.yml
.github/workflows/make_changelogs.yml

:cl:
fix: Added things Crossedfall told me to add
/:cl:

Fixes changelog bot for good

---

.github/workflows/compile_changelogs.yml
.github/workflows/make_changelogs.yml
tools/changelog/generate_cl.py

:cl:
fix: fixed the changelog generation FINALLY I HOPE
/:cl:

Yeat another changelog fix

---

code/modules/reagents/reagents/medicine.dm
code/modules/reagents/reagents/toxins.dm

Some values has been changed for the poison and removed the effect multiplier being too low for the antitoxin.

Adjusted values for the spider poison to being rapid killing poison and fixed the antitoxin

---

cev_eris.dme
code/modules/hydroponics/hydrochems/medicinalplants.dm
code/modules/hydroponics/seed_controller.dm
code/modules/hydroponics/seed_datums.dm
code/modules/hydroponics/trays/tray.dm
code/modules/hydroponics/trays/tray_process.dm
code/modules/mob/living/carbon/superior_animal/roach/attack.dm
code/modules/mob/living/carbon/superior_animal/roach/riding.dm
maps/CEVEris/_CEV_Eris.dmm

Hydroponics is pretty weak and boring in my opinion, id like to add a few changes and rework it so that its a bit more fun and less of a chore. Small steps for now
Hydroponics right now feels like a big chore for how comparatively weak it is, not only to other hydro systems like goons and TG's but also compared to other departments as a whole. There are some minor tweaks that already make hydro MUCH more fun like having a sink so you dont have to beg for water or the real hydro equipment so more seasend botanists can do some more advanced stuff.
:cl:
add: A sink for NeoTheologists hydroponics
add: Both gene machines are added to NoeTheologists hydroponics
add: Atropa belladonna, a new berry which contains atropine
add: Atropine, which stops death and heals oxy damage, can be OD'd and will …

rework hydro to less frustrating

---

code/game/objects/structures/electricchair.dm

Fix issue #4632 with the electric chair not working.
The origin of the issue was a missing call to the proc/shock() function of the chair.
Increased damage to kill (total damage > 200) instead of leaving the victim in crit.
:cl: Hyperio
fix: Fixed electric chair not working
/:cl:

Fix electric chair not working

---

code/modules/reagents/reagents/toxins.dm
code/modules/sanity/sanity_mob.dm

Fixes many runtimes because wrong var and typepath being used for OnDrug intended for actual drugs, not toxins.

Fixes the sanity runtime

---

code/modules/mob/living/silicon/robot/drone/blitzshell.dm

:cl:
fix: Fixes Blitzshells being able to drop their module items
fix: Fixes Blitzshells being unable to pick up secure documents
/:cl:

Blitzshell drop item fixes

---

tools/changelog/ss13_genchangelog.py

Increases amout of supported changelog prefixes #4873 
:cl:
fix: fixed changelog choking when encountered with wrong prefix
/:cl:

Increases amout of supported changelog prefixes

---

tools/changelog/ss13_genchangelog.py

holy smokes I hate github's UI

Fixes typo in the CL generator

---

code/modules/core_implant/cruciform/machinery/cloning.dm

Fixes a few bugs with NT cloner. Might need some tweaks with balance, but it's almost untouched compared to what was before. Basicly, it adds a bit of fail-safe checks here and there and change cloner's vars a bit so it will work with different manipulators.
It fixes stuff, which is a good thing i guess.
:cl:
fix: when you upgrade manipulators inside the cloner it won't work at all
fix: manipulators don't actually speed cloning process
/:cl:

Fix of a cloner

---

code/game/objects/items/devices/organ_module/_module.dm
code/modules/mechs/mech.dm
code/modules/mob/living/carbon/human/human.dm
code/modules/reagents/metabolism.dm
code/modules/reagents/reagents/drugs.dm
code/modules/reagents/reagents/toxins.dm
code/modules/sanity/breakdown.dm
code/modules/sanity/breakdowns.dm
code/modules/sanity/sanity_mob.dm

Reverts discordia-space/CEV-Eris#4847
Due bad spawn() usage in places, reverting it for now.

Revert "Sanity"

---

code/__HELPERS/files.dm

Ported from /tg/, noticed we have the same oversight.
Exploits are bad
:cl:
server: Fixes an exploit to prevent filesystem access
/:cl:

Prevents filesystem access

---

code/game/objects/items/weapons/power_cells.dm

More storage, no more silver requirement.
Allows at least something going for them.
:cl:
balance: Excelsior cells are now somewhat marginally better now.
/:cl:

Improves Excelsior Cells

---

maps/CEVEris/_CEV_Eris.dmm

Fix Vasiliy Dokuchaev airlock buttons
Fix a bug
:cl:
fix: Vasiliy Dokuchaev airlock buttons
/:cl:

Fix Vasiliy Dokuchaev airlock buttons

---

code/game/objects/items/weapons/tanks/jetpack.dm
code/modules/mob/living/carbon/human/update_icons.dm

Needlessly cleans up the Jetpack file, and adds a contained icon check to s_store.
Hotfix.
:cl:
fix: No more tank icons appearing over everyone.
/:cl:

Fixes Tank icon states appearing over mobs.

---

code/modules/mob/living/silicon/robot/drone/drone_console.dm

Fixes drone control not detecting drones on a different z level

---

code/game/objects/items/weapons/grenades/anti_photon_grenade.dm
code/game/objects/items/weapons/grenades/chem_grenade.dm
code/game/objects/items/weapons/grenades/flashbang.dm
code/game/objects/items/weapons/grenades/smokebomb.dm
code/game/objects/items/weapons/grenades/sonic.dm

ports from tg
allows large grenades to contain slime extracts
because slimes grenades are cool
:cl:
add: large grenades can contain slime extracts
/:cl:

Slime grenades

---

code/modules/client/client procs.dm

Fixes oversight in client procs.dm

Update client procs.dm

---

code/modules/client/client procs.dm

Reason was them crashing on startup, due to an attempt to connect with a database that didn't exist.
Fixes #4935

Fixes private servers CTDing themselves

---

code/game/machinery/computer/buildandrepair.dm
code/game/machinery/deployable.dm
code/game/machinery/recharger.dm
code/game/objects/structures/girders.dm
code/game/objects/structures/stool_bed_chair_nest/bed.dm
code/modules/tables/tables.dm

* Fixes some potential recycler material dupes.
* Fixes cell charger efficiency scaling being a bit off.
Small PR, nothing changelog-worthy.

Random fixes

---

code/modules/clothing/head/armor.dm

`initial()` doesn't work on lists you chumps!
Also fixes some ugly descriptions.

Fixes "altyn" and "maska" helmet armor values being broken

---

code/modules/mob/living/carbon/superior_animal/ai.dm
code/modules/mob/living/carbon/superior_animal/giant_spider/giant_spider.dm
code/modules/mob/living/carbon/superior_animal/superior_animal.dm

This PR tweaks the behavior of roaches and spiders with windows. They were already supposed to do it but the check for destroying their surrounding was not properly done and the probability of doing it was low.
Now they will try to break full windows, directional windows as well as windoors to reach you if you're behind them. I increased the destroyProperty probability to 100% or else they do not try to actively break the window, they just bash it with a few seconds between each hit.
I also set the spider's density to 0 (like roaches) so that they are able to pass over low walls to reach you.
They are no pressure check because :
- I doubt roaches and spiders can think "Maybe I should not break that thing" when they see a juicy prey on the other side of a filmsy piece of glass, even if …

Tweak roach and spider behavior with windows

---

code/game/turfs/turf.dm

Fixes the bunch of runtimes with the missing sound for the floor in space.
The caller for this function can take these nulls and be fine.
:cl:
fix: Missing sound for catwalks in space.
/:cl:

Fixes the runtime with floor sound

---

code/datums/topic/admin.dm

Removes two more client qdels

---

code/datums/topic/admin.dm

Removes yet another client qdel

---

code/datums/contract.dm

Fixes some typos outlined in Eclipse-Station/NEV-Northern-Light#164

Fixes excel typos in code

---

code/modules/client/client procs.dm

Removes more client qdel bullshit

---

code/modules/mob/living/silicon/ai/ai.dm
code/modules/mob/living/simple_animal/hostile/retaliate/drone.dm

Some descripcion text of the AI's used "station" (job description at the start of a round, Ai annoncements's text), so I changed it to "spaceship" or "ship"
This way, the AI's text uses the correct nomination for the CV Eris. Used both "spaceship" and "ship" to avoid repetition, making a bit "cooler" to read. 
:cl:
fix: Corrected the AI greeting to clearly state spaceship instead of station. 
fix: Changed beams from brute to burn for beams weapons of a drone
fix: Corrected other references to the ship
/:cl:

Fixed some text from the AI

---

code/modules/mob/mob_helpers.dm

Fixed.
Now it can hadle **&**, **<**, **"**, **'** and **>**
:cl:
fix: Stammering now can handle '.
/:cl:

Shatter fix

---

code/game/objects/items/devices/propaganda_chip.dm

*Should* fix the runtime in propaganda_chip.dm,77: Cannot read null.real_name

Propaganda_chip runtime fix

---

code/modules/cargo/packs.dm

Adds a bee crate to guild for 700 credits, making it possible to get a queen bee.
It's possible to use beekeeping mechanics to add more things for players to do.
add: Bee crate
/:cl:

Adds bee crate to guild

---

code/modules/projectiles/guns/matter/launcher/nt_sprayer.dm

NT can now curb fungo outbreaks much easier
:cl:
add: Adds a weedkiller firemode to the NT BCR
/:cl:

Adds a weedkiller firemode to the NT BCR

---

code/modules/projectiles/guns/matter/launcher/nt_sprayer.dm

fixes the NT spray altfire

---

code/modules/clothing/suits/miscellaneous.dm

Fixes Sleek Jacket and Jaeger Jacket, code was submitted with false icon path
Icons were missing
:cl:
fix: Sleek Leather Jacket and Jaeger Jacket
/:cl:

Fixes Sleek Jacket and Jaeger Jacket

---

code/modules/dungeons/procedural/jp_dungeon_gen.dm

Lets the pathgen sleep, to give other processes a chance to do something.
The process was set to be a background process, but it was never given a chance to sleep to let others process. This is one of the main causes of server launch hanging.

JPdungeon path generator simple optimization

---

code/modules/dungeons/procedural/deepmaint.dm
code/modules/dungeons/procedural/jp_dungeon_gen.dm
code/modules/multiz/movement.dm
maps/submaps/deepmaint_rooms/normal/sm_core.dmm

A few requested fixes and a huge performance improvement.
Self-explanatory. 
:cl:
tweak: replaced SM crystal in deep maint with an SM shard, so it doesn't fuck over people as much.
fix: fixed deepmaint taking half an hour to generate
fix: fixed deepmaint rooms sometimes not generating and being utterly empty
fix: fixed deepmaint working area, now it's not overly cramped
fix: fixed deepmaint pathfinding for building corridors and alcoves sometimes leaving unusable non-interconnected areas
fix: fixed ladders and other multiz structures incorrectly moving items pulled by players
/:cl:

Deepmaint fixes and optimizations + multiz pulling fix

---

code/controllers/subsystems/ticker.dm
code/game/objects/items/devices/propaganda_chip.dm

Should fix an infinte loop in /datum/controller/subsystem/ticker/proc/excel_check()
Things working are good

Excel ticker infinte loop fix

---

code/game/machinery/excelsior/boombox.dm

Fixes Excelsior boombox description
:cl:
fix: Excelsior boombox description
/:cl:

Fixes Excelsior boombox description

---

code/game/objects/items/weapons/storage/belt.dm

title.
People complained it couldn't. So I guess I'm making this one line PR.
:cl:
balance: tactical belts fit crowbars.
/:cl:

Tactical belts can fit crowbars.

---

code/modules/projectiles/projectile/energy.dm

Balance change
:cl:
balance: removed weaken from energy dart, buffed the tox damage instead
/:cl:

Balance fix of Energy Dart weakening through armor

---

code/datums/outfits/equipment/backpacks.dm
code/modules/client/preference_setup/general/04_equipment.dm

Duffelbags will now be available in character preferences.
More choice between certain benefits but downsides to access similar to backpacks.
:cl:
tweak: You may now select duffelbags in your character preferences.
/:cl:

Adds duffelbags to preferences

---

code/modules/clothing/head/armor.dm

Please, don't use `initial()` on lists or objects. It doesn't work. It never works.
Same issue and same fix as #4944.

Fixes riot helmet face shield runtimes

---

code/modules/mob/mob_helpers.dm

the logic of the traps was broken, this fixes it.
because this fixes a bug.
:cl:
fix: trap logic
/:cl:

trap logic fix

---

code/datums/perks/fate.dm
code/modules/sanity/sanity_mob.dm

*description goes here*
:cl:
fix: Sanity no longer tanks from a single drop of blood
/:cl:

Fixes the sanity cap

---

code/datums/topic/admin.dm
code/modules/admin/DB ban/functions.dm

if player leave and you give him a manual ban it make this
no ip and cid
i fix it, and now every ban have a cid
and now if you choose no in ip ban, its realy not an ip ban
fixes for admins its good
:cl:
fix: every ban have a cid
fix: IP ban do not remembers ip if you choose no
/:cl:

ifx bans without cid and fix ip ban

---

code/modules/admin/banjob.dm

fixes! EVERY ONE LOVE IT!!!!1!
idk
:cl:
fix: Jobbans fixed.
/:cl:

jobban fix

---

code/game/gamemodes/storyteller_print.dm

fix 
fiiiiiiiiiiiiix
:cl:
fix: fixed a delayround button
/:cl:

delayround button fix

---

code/game/objects/random/voidsuit.dm

Passively allows IHS ops to figure out who is who.
:cl:
balance: removed IHS voidsuit from random spawn
/:cl:

get rid of IHS voidsuit in random spawn

---

code/datums/perks/fate.dm
code/game/objects/items/oddities.dm
code/game/objects/items/weapons/tools/mods/_upgrades.dm
code/modules/sanity/inspiration_component.dm
code/modules/sanity/sanity_mob.dm

- Removes the guff items that don't really make sense as heirlooms
- Heirloom now has an oddity effect to it
:cl:
* tweak: Noble fate background heirloom now works as an oddity
* tweak: Nonsensical items removed from Noble background heirloom list
/:cl:

Noble buff

---

code/__DEFINES/sanity.dm
code/modules/sanity/sanity_mob.dm

:cl:
fix: You should no longer get duplicate food or drink desires
/:cl:

Some groundwork for desire conversion

---

code/modules/clothing/spacesuits/void/excelsior.dm

Idedplsnerf
:cl:
balance: The excelsior voidsuits armor levels have been reduced to the equivalent of an IH voidsuit.
/:cl:

Nerfs excel armor to IH voidsuit levels

---

code/__DEFINES/sanity.dm

makes our repository pass Travis check.

Fix pr #5046

---

code/controllers/subsystems/jobs.dm

Having the "random job" option enabled should no longer allow you to acquire a job that is restricted by your character's preferences.
:cl:
fix: random job preference exploit
/:cl:

fix random job preference.

---

code/modules/reagents/reagent_containers/food/drinks.dm

Add validate before ghost gulp.
Ghosts can't drink from glasses.
:cl:
code: Add ghost validate before gulp.
/:cl:

fix(gulp_whole): validate ghost before gulp

---

cev_eris.dme
code/datums/topic/admin.dm
code/global.dm
code/modules/admin/DB_search/search.dm
code/modules/admin/verbs/antiraid.dm
code/modules/client/asset_cache.dm
code/modules/client/client procs.dm
schema.sql

Why not?
:cl:
add: The server now have whitelist  for VPN checking.
add: Admins now can search players in the server DB.
add: server now check if a player have same ip or cid with somebody else from BD and remember it FOREVER.
fix: delayed ban kick player
/:cl:

search players in DB

---

code/modules/clothing/head/armor.dm

People complained about it, also makes no real sense?
:cl:
tweak: steelpot no longer blocks facial hair
/:cl:

Steelpot no longer blocks facial hair.

---

code/modules/modular_computers/file_system/reports/bounty_entry.dm

Added force_security argument to checking account number and PIN when creating bounty without ID, so now it checks not only account number, but also PIN.
fixes #4630
Because it is bugfix
:cl: Vlad777
fix: Fixed creating bounties with wrong PIN.
/:cl:

Fix creating bounty with invalid PIN

---

code/modules/clothing/under/miscellaneous.dm

Title
missed an "e"
:cl:
fix: leisure outfit
/:cl:

fixes leisure outift code

---

code/modules/projectiles/guns/energy/laser.dm

Makes it a bit more viable by lowering charge cost.
The gun is at the end of the weapon branch and costs quite some research data, and even a full atom cell only gets 4 shots out of it which does only slightly more damage than a martin. It was a huge joke, now its usable.
:cl:
balance: lowered moebius prototype cannon charge cost.
/:cl:

makes moebius prototype laser cannon a bit more viable

---

code/game/objects/items/devices/last_shelter.dm
code/game/objects/items/devices/radio/radio.dm
code/game/objects/items/devices/techno_tribalism.dm
code/game/objects/items/weapons/maneki_neko.dm
maps/CEVEris/_CEV_Eris.dmm

Fixing bags of faction items.
:cl: DarkLevel
fix: Last Shelter will now work normally.
fix: Fixing last shelter place.
fix: Fixing random wave radio runtime errors.
fix: Fixing Enforcer infinity stat exploit.
fix: Fixing Maneki Neko to work more stable.
/:cl:

Faction items fix

---

code/modules/clothing/spacesuits/rig/rig.dm
code/modules/power/cell.dm

Fixes "rigged cell explosion" admin log spam

---

cev_eris.dme
code/game/objects/items/weapons/circuitboards/machinery/mining_drill.dm
code/modules/mining/drilling/brace.dm
code/modules/mining/drilling/drill.dm
code/modules/mining/drilling/scanner.dm
code/modules/random_map/noise/ore.dm

Try to clean drill code.
Fix request components.
Add scanning module. If better - drill will have more large work area.
:cl:
add: Add scanning module in drill. If better - drill will have more large work area.
/:cl:

Drlling update.

---

code/modules/core_implant/cruciform/rituals/base.dm

Removed fail chance for common litanies
Because fuck macro spam
:cl:
tweak: Removed fail chance for common litanies, no more stupid chat spamming to get some nutrition
/:cl:

Removed fail chance for common litanies

---

code/game/objects/random/scrap.dm
maps/CEVEris/_CEV_Eris.dmm

Genetics Lab no longer spawns with cameras, while Chemistry in contrast now does. Removed redundant piping in Cargo Maintenance, and closed certain maintenance areas being exposed to space.
Replaced some scrap spawners with their low chance subtypes, or deleted them all together.
Cryo glass should now all use plasma low wall spawners, instead of smart plasma low wall spawners (not too relevant).
No more absolute foolery regarding these "Valid Hunters", and with Genetics. Chemistry camera coverage has also been a spoken about issue for awhile. The junk pile spawns that were removed were also primarily placed by myself, without really thinking about what their gameplay impact would be.
:cl:
tweak: Performed some map changes, Genetics now has had their cameras removed to protect proprietary …

Map changes

---

code/modules/reagents/recipes.dm

recipe was using Starkellin and it should've been starkellin
patches mirc mistake caused by typo
:cl:
fix: mirc will now properly display boxer recipe
/:cl:

patches the mirc error

---

code/modules/mob/living/silicon/robot/drone/blitzshell.dm

Adds 5 minutes cooldown to blitzshell nanorepair.
Balance
:cl:
balance: Blitzshell nanorepair now have 5 minutes cooldown.
/:cl:

Nanorepair cooldown

---

code/modules/clothing/shoes/miscellaneous.dm

OVERSIGHT: German jackboots don't count as jackboots, you can't put items there.
well thats fixed now
jackboots.. should be jackboots
:cl: Fernandos33
fix: german jackboot. now have same stats as regular jackboots (can fit knives)
/:cl:

german boots same as jackboots

---

code/modules/client/preferences_spawnpoints.dm

Title.
Dear god why was this so long before?
:cl:
tweak: spawning in should no longer make you stunned for as long.
/:cl:

Lowers the amount of time spawning in paralyzes you for.

---

code/modules/reagents/recipes.dm

noexcutite now can be made again
fixes a mistake made in noexcutite recipe
fixes a bug
:cl:
fix: noexcutite now can be made again
/:cl:

noexcutite now can be made again

---

code/game/objects/items/weapons/mine.dm

as asked nerfs the mines and overlays em above everything
mines are no visible with trash. and not so fraggy
tweak: mines are now overlayed like traps
balance: frag from excels mines where lowered
/:cl:

mine changes

---

code/modules/multiz/movement.dm

Fixes #494
bugfixes go brrrr
:cl:
fix: You are able to throw things and mobs over open space now.
/:cl:

Bugfix #494

---

code/_onclick/hud/screen_objects/base_screen_objects.dm
code/datums/datum_hud.dm
code/modules/mob/living/carbon/human/species/species_hud.dm

Fixed "Invetory" typo
Typos are bad
:cl:
spellcheck: 3 instances of "toggle invetory" to "toggle inventory"
/:cl:

misspelling fixed

---

code/defines/procs/announce.dm
code/game/gamemodes/events/hivemind_invasion.dm
code/modules/hivemind/core.dm
code/modules/hivemind/machines.dm
code/modules/hivemind/mobs.dm
code/modules/hivemind/objects.dm
code/modules/hivemind/self_defense.dm
code/modules/hivemind/wires.dm
code/modules/mob/living/simple_animal/hostile/megafauna/hivetechboss.dm

General rebalance/buff of the hivemind.
Increased HP and damage of the mobs and hivemind machines.
Tyrant can now spawn (If it dies the entire hivemind dies with it)
Turret projectiles now use Energy armour instead of Bio
Assemblers can spawn Hiborgs
Hivemind can't convert soil and canisters anymore
Bombers explode with more strength, they are a bit slower and are extremely fragile though. Easy targets for hitscan weapons.
Reduces stun length of the impaler (head on a tentacle the hivemind spawns)
Increased spawn chance of Mechiver
Also fixed some typos in the hivemind code
Malfunction chance has been lowered and no longer made extremely deadly
Node teleporting will show up later now, meaning that it will only be able to teleport away if you take too long. Still a one-use ability …

Hivemind rebalance.

---

code/datums/uplink/devices and tools.dm
code/game/objects/items/weapons/space_harpoon.dm
code/modules/mob/living/silicon/robot/drone/blitzshell.dm

Adds bluespace harpoon to blitzshell
I was tasked to do that by Reere so it's good for the game I guess.
:cl:
add: Blitzshells now have bluespace harpoons
/:cl:

Blitzshell's bluespace harpoon

---

code/game/objects/items/weapons/implant/implants/carrion/breeding_spider.dm
code/game/objects/items/weapons/implant/implants/carrion/carrion_spiders.dm
code/modules/mob/living/simple_animal/spider_core.dm
code/modules/organs/internal/carrion.dm

Fixes a few big and small carrion bugs / exploits.
Stuff working properly is good.
:cl:
fix: Carrions can now properly use old spiders when transitioning to a new body.
fix: Carrion maw now gives gene points instead of sometimes taking them away.
fix: Breeding spider now works only on human bodies.
/:cl:

Urgent carrion fixes

---

code/game/objects/items/weapons/implant/implants/carrion/breeding_spider.dm
code/modules/organs/internal/carrion.dm
code/modules/organs/organ.dm

Fixes the power disappearing bug, actually fixes the breeding spider and regeneration only works on the body it was activated on.
Carrion working is good.
:cl:
fix: carrion powers should not randomly disappear
fix: breeding spider is now truly fixed
fix: regen stasis should work on the body it was activated on
/:cl:

Carrion fixes round 2

---

code/modules/clothing/spacesuits/rig/rig.dm

fix ring runtime

---

code/modules/reagents/reagent_containers/food/snacks/meat.dm

:cl:
fix: fix meat's taste tag
/:cl:

fix meat's taste tag

---

code/game/objects/items.dm

fix remove_hud_actions() runtime

---

code/game/objects/items/weapons/tools/_tools.dm
code/modules/clothing/spacesuits/rig/rig.dm

fix get_fuel() runtime

---

code/_onclick/hud/screen_objects/base_screen_objects.dm

fix s_click() runtime

---

code/modules/mob/living/carbon/breathe.dm

fix handle_chemical_smoke()  runtime

---

code/game/objects/effects/chem/chemsmoke.dm

fix splash() runtime

---

code/modules/virus2/helpers.dm

fix get_bodytype() runtime

---

code/game/machinery/hologram.dm

fix Runtime in hologram.dm,135

---

code/__HELPERS/game.dm

fix Runtime in game.dm,530

---

code/modules/organs/organ.dm

fix Runtime in organ.dm,142

---

code/datums/craft/menu.dm

fix Runtime in menu.dm,41

---

code/modules/scrap/scrap.dm

fix Runtime in scrap.dm,269

---

code/modules/projectiles/projectile/special.dm

fix Runtime in special.dm,168

---

code/modules/mining/mine_turfs.dm

fix Runtime in mine_turfs.dm,271

---

code/modules/projectiles/projectile.dm

fix Runtime in projectile.dm,601

---

code/game/sound.dm

fix Runtime in sound.dm,379

---

code/__HELPERS/manifest.dm

Title
Fixes #5097 
:cl:
fix: Lowborns manifest status fixed
/:cl:

Fixing Lowborns status in manifest

---

code/modules/client/preference_setup/augmentation/01_modifications.dm

fix Runtime in 01_modifications.dm,120

---

code/modules/client/preferences.dm

fix Runtime in preferences.dm,241

---

code/game/machinery/cryopod.dm

fix Runtime in cryopod.dm,340

---

code/game/jobs/job/job.dm

fix Runtime in job.dm,168

---

code/game/machinery/telecomms/telecomunications.dm
code/game/objects/items/weapons/candle.dm
code/modules/mob/inventory.dm
code/modules/projectiles/dynamic_cursor.dm

fix Runtime in telecomunications.dm,555 and runtime remove_cursor()

---

code/game/objects/items/weapons/material/thrown.dm

fix Runtime in thrown.dm,20

---

code/modules/reagents/reagent_containers/food/snacks.dm

fix Runtime in snacks.dm,756

---

code/modules/mob/say.dm

fix Runtime in say.dm,66

---

code/modules/mob/living/carbon/superior_animal/giant_spider/types/nurse.dm

Spider shouldn't eat carrions anymore.
Spider shouldn't eat carrions.
:cl:
fix: Spider shouldn't eat carrions anymore.
/:cl:

Spider shouldn't eat carrions anymore.

---

code/game/objects/items.dm

fix Runtime in items.dm,415

---

code/modules/organs/external/damage.dm

Runtime in damage.dm,83

---

code/modules/biomatter_manipulation/biogenerator.dm

Runtime in biogenerator.dm,522

---

code/game/machinery/multistructure.dm

fix Runtime in multistructure.dm,115

---

code/modules/mining/drilling/drill.dm

fix Runtime in drill.dm,88

---

code/game/objects/structures/bluespace_crystal_structure.dm

fix Runtime in bluespace_crystal_structure.dm,91:

---

code/datums/perks/oddity.dm

fix add_reagent() runtime
