code/game/objects/structures.dm
code/game/objects/structures/railing.dm
code/modules/materials/material_recipes.dm

Переработка перил по иссую #457. Теперь они должны работать как надо и красиво.
Что сделанно:

some railings rework

---

code/modules/mob/living/carbon/human/human.dm

Не уверен, что все как надо. По идее, должно работать.
Человекочитаемые имена для слотов в меню раздевания вместо технических.

Fix #554. Readable names in stripping menu.

---

baystation12.dme
code/client_macros.dm

Там всплыл неприятный эксплоит, позволявший абузить макрокоманды.
Оригинальный тред: http://www.byond.com/forum/?post=2219001
https://github.com/Baystation12/Baystation12/pull/16441
https://github.com/Baystation12/Baystation12/pull/16444
https://github.com/Baystation12/Baystation12/pull/16461
https://github.com/tgstation/tgstation/pull/24543
Моё уважение, ParadiseSS13

click macro exploit fixes

---

code/game/machinery/doors/airlock.dm

- Fixed all airlocks, Whose animating icons when airlocks opening with open wire panel looks little bit strange. Closes #631

Fix airlock opening animating icon if wire panel on it was been opened

---

code/game/machinery/alarm.dm

fix firealarm security light color level

---

code/modules/projectiles/guns/energy.dm

No one keeps weapons in armoury with loaded ammunition.

Energy weapon no longer spawned with preloaded cell.

---

code/game/machinery/alarm.dm

`master_area` is set in last building steps
`initialize()` try get some `master_area` vars

Fix alarm building related runtime

---

code/game/objects/items.dm

Boosts performance in heavy gun fight where a lot of blood spawns on stuff or whatever close to that situation.
Actually port of https://github.com/TauCetiStation/TauCetiClassic/commit/cb060817d5e0a84c0de15fe021a839bb9166fbfb
Long story short: "in world" loops should be avoided in features where such procs used often.
**How to reproduce:** spawn a gun (i used c20r gun in short bursts mode (5 bullets per click)), then spawn a human, then simply start shooting repeatedly towards human so that he starts getting bullet shrapnel and keep one of your eye in MC tab watching how CPU sometimes sky jumps.
A also made new profile tests if interested:
```
Proc Name                                    Self CPU    Total CPU    Real Time        Calls
-----------------------------------------    --------- …
```

Performance fix in generate_blood_overlay proc.

---

code/modules/mob/living/simple_animal/hostile/roach.dm
code/modules/reagents/Chemistry-Reagents/Chemistry-Reagents-Toxins.dm

* Roaches now only resurrects once with blattedin by default.
* Fixed expression in gas attack as it was only working when roach was dead (now it works when roach alive and has enough reagent.
* Blattedin won't regenerate anymore in dead roaches.
* Roach emote "charges at target in clouds of poison" will only be displayed when roach actually does that.

Fixed bugs in bugs (roaches).

---

code/modules/power/smes_construction.dm

* Also fixes that mapped smes unable to use its mapped charge var value.
* Removed unused smes subtypes, as for today their idea done wrong anyway, machinery parts currently populated inside InitCircuit proc, which insert parts based off circuit defines.

Fixed that smes gets wrong charge (e.g: all smes starts empty at round start).

---

code/ZAS/Fire.dm
code/game/atoms_movable.dm
code/modules/overmap/ships/engines/thermal.dm
code/modules/projectiles/guns/energy.dm
code/modules/surgery/surgery.dm

Each fix in its own commit:
* fixes #1551 - gas_mixture/proc/remove() return null, if it removed zero gas
* fixes #1545 - null.fire because it passes !istype(my_tile) check
* fixes #1550 - bad_index in this case when trying to access associative list when its null (and tool_qualities list is null for any tool by default).
* fixes #1547 - probably happens when item gets qdeled mid throwing state or for whatever reason its loc is null by that moment.
* fixes #1549 - there is a plenty of cell var checks in other places, so i think it needs here too.

5 runtimes fix pack.

---

code/_helpers/unsorted.dm
code/datums/autolathe/autolathe_datums.dm
code/game/machinery/autolathe.dm
code/game/objects/items/weapons/material/material_weapons.dm

* resolves #1565
* Autolathe now checks recycled atom contents and counts that materials too so nothing goes to waste just because player forgot to eject something from an item before recycling.
* Autolathe recipes initialization stage now checks item's contents too, e.g: crafting flashlight with power cell will cost more than flashlight without power cell.
* Minimum recipe matter price now can't be less than 1 (even in upgraded lathe), previously items with price like 0.2 were rounded to 0 (this was requested).
* I know that price rounding is intended, but i think it brings more problems than resolves, because with rounded values something can be lost or get more than it should, so maybe there still some hidden farming issues are present, but major problems should be fixed.

Should resolve any/most resource dupe/farming issues with autolathe.

---

code/game/machinery/autolathe.dm
nano/templates/autolathe.tmpl

* Fixed bug where autolathe refuses to produce an item, when player put enough resources for only one try.
* Fixed bug where autolathe UI only shows last required mat for current printing item.
* Small change in nano template - now it also shows recipe name when there is error.
* Also removed working animation play, when autolathe is in error state.

Fixed some autolathe bugs with recent autolathe merge update.

---

code/game/objects/effects/decals/misc.dm
code/modules/recycling/disposal.dm
code/modules/recycling/sortingmachinery.dm

Sets the layers for Disposal bins, and Disposal Intake/Outlet machines.
The bins are given a layer that allows them to theoretically be placed under tables. This is a thing that could be done in future
Disposal machinery are given a layer just below normal objects, so things will draw ontop of them.
The pipes and conveyor belts are unchanged, they work fine.

Disposal Machinery Layer Fix. Fixes #1616

---

code/modules/mob/new_player/new_player.dm

Causes chat in the lobby to be routed to the OOC verb, instead of silently discarded. OOC is the only channel they can read anyway
This is kind of a big deal for new players who would be confused as to why they're typing and nothing comes up.
Also generally, manually typing ooc gets annoying

Lobby Chat OOC. Fixes #1637

---

code/datums/ai_laws.dm

It's temporary solution, we need to discuss the law set for future launches

Changed default lawset to old good Asimov

---

code/modules/projectiles/guns/projectile.dm

In last pull this code wasn't copied to both places where it should've been, only to one.
This fixes, for example, piles of shotgun slugs being fully placed inside double-barreled shotgun.

Some fixes of bullet pile system

---

code/game/machinery/embedded_controller/airlock_controllers.dm
code/game/machinery/embedded_controller/airlock_docking_controller.dm
code/game/machinery/embedded_controller/airlock_docking_controller_multi.dm
code/game/machinery/embedded_controller/docking_program.dm
code/game/machinery/embedded_controller/embedded_program_base.dm
code/modules/shuttles/landmarks.dm

Fixes the mining shuttle being locked at roundstart, by working around a byond bug.
Somehow, string tables are occasionally broken. Compiletime inputs - ie, values entered into map instances in the editor - occasionally don't get assigned to the correct string in the table, and thus fail to match against strings that are identical. This is a byond bug and beyond our power to fix
The fix that i've implemented here is to use copytext on shuttle tags in new, which creates a "new" string out of them which correctly inserts into the stringtable and works as intended. This is a workaround for the aforementioned bug, and it should be a permanant solution.
We should look at doing something like this for all map-edited values like network and radio tags on buttons, cameras, etc

Mining shuttle fix

---

code/__defines/_planes+layers.dm
code/game/machinery/mass_driver.dm
code/modules/mob/living/carbon/human/human.dm
code/modules/mob/living/say.dm
code/modules/mob/typing_indicator.dm

Fix typing indicators and massdriver layers.
TODO: merge typing indicaotors in one.
Edit by nanako:
fixes #1845
fixes #1841

Layers. Fix #1845, fix 1841

---

code/game/objects/items/weapons/storage/belt.dm

Since you can store shotgun ammo here, we should just store everything here. Revolvers can use this.

You can now store all stacks of ammo in your tactical belt.

---

code/_onclick/ghost.dm
interface/interface.dm

This lets ghosted admins ctrl+shift+click on things to open their VV immediately without using the horrible dropdown. More useful for dev work than admin work, but still!
Port of some of https://github.com/ParadiseSS13/Paradise/pull/5203 
The Ctrl+click from the original PR is also nice, but that would override buildmode functionality here. If you have any suggestions, feel free.

aghost shortcut for VV

---

cev_eris.dme
code/_onclick/click.dm
code/_onclick/hud/screen_objects/robot_screen_objects.dm
code/controllers/admin.dm
code/modules/clothing/spacesuits/rig/modules/modules.dm
code/modules/mob/living/silicon/subsystems.dm

The worst bug i've seen on eris so far :P
EkuDza switched click handling over to a new reciprocity based system, where each atom would get Click called on it, and then user.ClickOn(that atom) would only get called if the atom returned zero from its Click call. If it returns a nonzero value, the click is dropped. This is good and an improvement
The problem was, he forgot to remove the call to usr.ClickOn from the baseline Atom.Click proc, so the two systems were working simultaneously and every click was triggering another click after the first one resolved
I also searched whole codebase for Click overrides and set their return values appropriately, a couple had been missed
And in the process i found a file named "subystems.dm", i corrected this obvious spelling error
fixes #1911

Double Click Fix

---

code/modules/mob/animations.dm
code/modules/mob/inventory.dm
code/modules/tables/interactions.dm

Restores safety checks
adds a user param to putdown animation
wraps putdown in spawn
This makes everything work perfectly without any need to rearrange safety checks

Putdown animation safety fix

---

code/game/objects/structures/crates_lockers/closets.dm

fixes https://github.com/discordia-space/CEV-Eris/issues/2127

Add missing adjacency check to locker altclick

---

code/game/antagonist/antagonist_create.dm
code/modules/overmap/spacetravel.dm

Fixes #2106 
Now rogue ai setups properly
Fixes #1965 
Spacetravel for ai eye now prevented, so aieye cannot going off from eris and be accidentally deleted

aieye and rampant ai fixes

---

cev_eris.dme
code/__defines/items_clothing.dm
code/game/objects/items.dm
code/game/objects/items/_inventory.dm
code/game/objects/items/devices/PDA/PDA.dm
code/game/objects/items/weapons/storage/internal.dm
code/game/objects/items/weapons/storage/storage.dm
code/modules/clothing/clothing.dm
code/modules/clothing/clothing_accessories.dm
code/modules/clothing/suits/armor.dm
code/modules/clothing/suits/storage.dm
code/modules/mob/inventory/_docs.dm
code/modules/paperwork/clipboard.dm
code/modules/paperwork/photography.dm

Changes:
- Move drag_n_drop for unequip to `/obj/item` code, ability bound to flag `DRAG_AND_DROP_UNEQUIP`
Moving:
- Moved inventory related item procs/vars to `code/game/objects/items/_inventory.dm`
Docs:
- add item procs docs to `code/modules/mob/inventory/_docs.dm`
Current docs may not reflect the real procs! Procs/docs will be update with following PRs.

Inventory basics, step 1

---

code/_onclick/hud/screen_objects/base_screen_objects.dm
code/modules/clothing/spacesuits/rig/rig.dm
code/modules/mob/living/carbon/human/human_helpers.dm
code/modules/supermatter/supermatter.dm

Adds a proc rig.getCurrentGlasses() which returns current glasses regardless rig.visor.active state.
Fixes supermatter not recognizing rig visor mesons
Adds an override into process_glasses to bypass newly added cell dependency of various glasses.
Adds a check into glasses_overlay to apply active rig visor overlay.
Combination of https://github.com/discordia-space/CEV-Eris/pull/2160 and https://github.com/discordia-space/CEV-Eris/pull/2149

Fixes multiple issues with rig visor

---

code/controllers/subsystems/inventory.dm
code/modules/clothing/spacesuits/rig/rig.dm
code/modules/mob/inventory/_docs.dm
code/modules/mob/inventory/equip.dm
code/modules/mob/inventory/slots.dm

Fixed:
- `mob_can_equip(...)`check invert value if `pre_equip` take more than one tick.
- "suit storage" slot datum `can_equip` proc always returns FALSE (also add more feedback)
- inventory subsystem return null for slot with higher id (accessory_buffer). fix #2200

Some fixes for inventory system

---

code/modules/clothing/spacesuits/rig/rig.dm

Makes hardsuits work again
Removes a completely pointless forcemove step which was screwing up the equipping process

Hardsuit Fix

---

code/modules/mob/mob.dm

Now pointing arrows have proper offsets, so you can properly point to items on tables, or air alarms!

Point arrow offset fix.

---

code/modules/multiz/structures.dm

Mobs blocking a ladder now increase climbing time by 50% instead of preventing climbing.
Shields properly take into account their setting.

Fixes ladders being blocked by shield/mobs

---

code/modules/reagents/Chemistry-Holder.dm

Splash was calling touch procs twice for turfs and objects and it was not properly respecting the amount to be splashed.
This fixes issues such as fuel not applying fire stacks properly because it was always spilled on the ground and none remained to apply to the actual target.

Fixes splashes calling touch procs incorrectly

---

code/game/machinery/doors/airlock.dm

Makes centcomm (spacefortress) airlocks opaque

---

code/datums/craft/recipes/furniture.dm
code/game/objects/structures/crates_lockers/closets.dm
code/game/objects/structures/crates_lockers/crates.dm
code/game/objects/structures/girders.dm
code/game/objects/structures/low_wall.dm
code/game/objects/structures/stool_bed_chair_nest/bed.dm
code/game/objects/structures/window.dm
code/modules/library/lib_items.dm

All items under furniture crafting tab return their crafting cost when properly dismantled, except for wooden barricade.
Shelf crafting cost lowered to 2 metal sheets to equal rack crafting cost, since they are identical objects in all but sprite.
Full windows and low walls now return their full cost when properly dismantled.

Fixes multiple furniture dismantle returns

---

code/game/turfs/simulated/wall_icon.dm
code/game/turfs/simulated/walls.dm

Fixes https://github.com/discordia-space/CEV-Eris/issues/2145
The only other cause for this runtime could be that `overlays.Cut()` is somehow responsible, but I cannot imagine how.

Fixes faulty memoization runtime in wall_icon

---

code/controllers/subsystems/mapping.dm

Fixes cases where Eris ship spawned inside asteroid fields, carp swarms or other hazards.
Moves overmap event tile creation to roundstart, it takes about half a second to generate.
What caused the bug was creation of mapping subsystem, which didn't take into account event creation excluding already occupied tiles from candidate event locations. This caused all predefined locations to get moved into position in atom initialize, only after events were created in mapping initialize, and atom initialize needs to run before mapping initialize to register locations.

Fixes overmap generating events inside occupied tiles

---

code/game/turfs/simulated/wall_icon.dm
code/game/turfs/simulated/walls.dm

Moves the start of wall processing into set material, and only starts if we have a radioactive material
radiation is all wall processing is used for. previously every wall started processing for at least one tick

Wall Process Fix

---

code/modules/clothing/spacesuits/rig/rig.dm

Fixes a runtime error i introduced where modules would try to apply an overlay to a part that doesnt yet exist

Rig Module Overlay Fix

---

code/game/gamemodes/events/spacevine.dm
code/modules/hydroponics/spreading/spreading.dm
code/modules/hydroponics/spreading/spreading_growth.dm
code/modules/hydroponics/spreading/spreading_response.dm

Makes plants a little more manageable
Reduces their health
reduces regen
Reduces cutting time
When a plant dies, nearby neighbors now take some aoe damage
Raised minimum health threshold to expand, should significantly slow down expansion
adjusted announcement time to let it get started

Plant Nerfing

---

code/game/area/Space Station 13 areas.dm
code/game/gamemodes/events/blob.dm

All `turret_protected` areas are now considered critical for events.

Makes blob not spawn in protected areas

---

code/game/objects/items/_inventory.dm

Turns out the isworn/isheld procs were flawed. 
By setting them to check for a zero equip slot, all problems are solved. The equip slot is always zero until after the first time an item is successfully equipped

Space Equipping Fix

---

code/game/gamemodes/roleset/excelsior.dm
code/game/gamemodes/roleset/simple.dm
code/game/gamemodes/storyevent.dm

Fixes the cost of our antitags - marshal and inquisitor. They now have a negative cost, as they were supposed to, meaning that normal antags will usually spawn alongside them
Tweaked weights of a few antags, notably increased traitor weight, its tried and tested, the bread and butter of antags
Reduced marshal initial weight, but tweaked their weight to properly scale with quantity of antags
Removes the crew weight requirements from most non-group antags, it was just nuking their weighting to hell and making changelings really rare

Antag Weighting

---

code/__defines/callbacks.dm
code/_macros.dm
code/game/objects/items/weapons/tools/_tools.dm
code/game/objects/structures/morgue.dm

Refactors morgue storage units a fair bit:
Morgue drawers and their contents are now fully animated, sliding in and out
Morgue units now have an upper limit on storage capacity. Shouldn't really be an issue as long as you use bodybags properly. Intended to prevent issues like sliding a thousand sheets of paper in and out, prevents possibility of spam crashing server
Minimum cooldown of 1.5 seconds added to toggling morgue drawer, again for spam protection.
Lots of little bugs and wierdness fixed
fixes #2316

The Most Serene Mausoleum

---

code/_helpers/global_lists.dm
code/modules/core_implant/core_implant.dm
code/modules/core_implant/cruciform/modules.dm
code/modules/core_implant/cruciform/rituals/group.dm
code/modules/core_implant/module.dm
code/modules/core_implant/ritual.dm
code/modules/core_implant/ritual_book.dm

Neotheology rituals are a horrible mess codewise.
How things currently work:
Just about any interaction with them generates a pile of new datums.
The cruciform stores a list of typepaths for the rituals it can cast. Every time you open a book, it creates a new copy of each of those rituals to take some values from it.
Every time you speak a ritual, it creates a copy of each of them again to test it. This is especially galling with group rituals
I have changed things.
Now, all the ritual datums are held in a single global list. Only one copy of each ritual exists, ever. The list is associative using the name as the key. Probably we should add some kind of ID instead but this works for now
The cruciform - and cruciform modules - each hold a list of ritual names, and get rituals by …

Ritual Refactor

---

code/game/objects/items/weapons/storage/bags.dm
code/game/objects/items/weapons/storage/storage.dm

Storage bags, such as plant bags and trash bags, once again utilize numbered item display.

Fixes storage numbered display

---

code/controllers/subsystems/jobs.dm
code/game/objects/structures/wire_splicing.dm
code/modules/economy/Accounts.dm

Fixes being unable to buy anything with ID cards. This was caused by attempting to assign an account number to the card before the account was setup. Reversed the order of these operations
Removes account security, so you no longer need to type in a pin when buying things from a vendor. We can revisit this in future but for now its just a pain that serves no purpose
Removes a debug message from wire splices that i forgot

Account Fix

---

code/modules/admin/bluespacetech.dm
code/modules/mining/mine_items.dm
code/modules/mob/living/silicon/robot/gripper.dm
code/modules/mob/living/silicon/robot/robot_modules.dm

This PR makes T-ray scanners more available to the people who need them:
A scanner is added to each miner equipment closet (also a single free toolmod)
Scanners are added to several robot modules, including drone
In addition this fixes a couple niggling issues:
Engineering grippers can now pickup floor tiles, so they can repair floors
Fixed a runtime error with BST backpacks
And one significant fix, i decided to implement a quick hack for the longstanding issue of robot items running out of power and breaking. For now, the charge of cells in their tools (which are unremovable and can't be recharged) is set to a really high value on initialize so it shouldn't run out.
This is a temporary fix until we (probably cups) gets around to coding a proper fix to wire them to the robot's central …

T Ray Scanner availability

---

code/game/turfs/simulated/floor.dm
code/modules/hydroponics/spreading/spreading.dm
code/modules/hydroponics/spreading/spreading_growth.dm

This PR does a couple tweaks to make it impossible for maintshrooms to cause breaches when they contain polyacid, while still allowing them to eat through parts of the ship that aren't exposed to space
In addition it includes a simple fix for a floor bug thats been bugging me
fixes #2407

Acid Plants Fix

---

code/modules/research/designs.dm

They exist, so let's give them a design.
All this does is allow the printing of the read-only ID broadcasters used in modular PDAs. It's nice if you want to assemble one from scratch, or need to replace one.

Add printable card broadcasters

---

code/modules/mob/new_player/login.dm

I was unable to reproduce the bug on a windows host, and my best guess is it's somehow nulled out, and no one can check because it's not a managed global/there's no procs that can grab the value of a world.variable (unmanaged globals)/there's definitely no proc that directly grabs the value of this.
Adding a null to client.screen (along with things like text/numbers) will to my knowledge cause the runtime of wrong type for list.
This moves the erroring line below the important functions so it doesn't interrupt them when it crashes, and also adds a block of code to catch if it's the wrong type and report that.

Temporary patch for lobby image/login.dm runtime

---

code/game/machinery/doors/airlock.dm

After playing on eris a bit, i'm getting a headache.
When we're properly populated, the sounds of nearby airlocks just NEVER STOPS, it's becoming background noise and it hurts.
This PR lowers the volume, and more importantly the range, of all sounds related to airlocks

Quieter airlocks

---

code/modules/admin/verbs/adminjump.dm
code/modules/mob/observer/ghost/ghost.dm

There were two verbs named jump to mob and they were interfering with each other
tweaked names and paths slightly to fix this

Adminjump fix

---

code/game/objects/items/weapons/storage/storage.dm
code/modules/mob/living/carbon/carbon.dm
code/modules/projectiles/ammunition.dm
code/modules/projectiles/ammunition/boxes.dm

Fixes #2558 
Fixes #2559 
Fixed storage gathering mode enabled on more types than intended
Tweaked how storage works
- On self click you now can open storage if your other hand is empty
- On tile click you will pickup item if there are gathering mode enabled and there are item to pick up if else it will empty storage if quick empty mode is avaliable

storage and ammobox tweaks

---

code/modules/projectiles/guns/launcher/crossbow.dm

Previously Powered Crossbows couldn't be crafted the expected way, with the screwdriver step being doable earlier, and finishing it early. And the fact it was done earlier meant crafting it the intended way resulted in it not being finishable.
As well, added to the descriptions to give some idea to folks unfamiliar with it what the next step is to build it when they examine it. Fine with changing those, but current ones feel like they should work.

Fixs Crossbow Crafting and Adds Description Steps

---

code/game/objects/items.dm
code/game/objects/items/weapons/material/knives.dm
code/game/objects/items/weapons/material/thrown.dm
code/game/objects/items/weapons/material/twohanded.dm
code/game/objects/items/weapons/melee/energy.dm
code/game/objects/items/weapons/tools/pickaxe.dm
code/game/objects/items/weapons/tools/saws.dm
code/game/objects/objs.dm
code/modules/mob/death.dm
code/modules/mob/living/carbon/carbon_defense.dm
code/modules/mob/living/carbon/human/human_defense.dm
code/modules/mob/living/carbon/superior_animal/defense.dm
code/modules/mob/living/living_defense.dm
code/modules/mob/mob_helpers.dm

This issue has become troublesome, time to prioritise it
This PR fixes several issues with embedding and rebalances a little. Notable changes:
There's now some text in chat when a weapon embeds into a nonhuman enemy
Embedded items are now dropped instead of deleted, when a creature is gibbed, dusted or butchered
Balance wise, reworked how embed chance is calculated, and notably factored robustness stat into it. If you're stronger, you can more easily pull the weapon out on the follow through, so higher robustness increases the embed damage threshold, and thusly allows you to more capably handle large weapons.

Embedding Fixes

---

code/modules/projectiles/ammunition.dm
code/modules/projectiles/ammunition/boxes.dm
code/modules/projectiles/ammunition/bullets.dm
code/modules/projectiles/ammunition/magazines.dm
code/modules/projectiles/guns/projectile.dm
code/modules/projectiles/guns/projectile/pistol/handmade.dm
code/modules/projectiles/guns/projectile/revolver/detective.dm

Loading magazines and ammoboxes is a little different now
You can load ammo in magazine by clicking on it with ammo in your hand
You can unload full stack from it by clicking on it with empty hand
You can unload one casing from it by alt clicking with ammo or empty hand on it
***
Stacking ammo from turf is easier now
***
Ammobox quick unload on selfclick is removed, click on turf for that
***
Magazines and ammo can be unloaded from guns by dragging gun in empty hand(just like removing battery)
***
Fixed 32 caliber not fitting in ammo box and a typo ".38"

Ammo loading/unloading fixes and tweaks

---

code/game/objects/items/weapons/tools/_tools.dm
code/game/objects/items/weapons/tools/mods/_upgrades.dm
code/modules/mob/living/silicon/robot/examine.dm
code/modules/mob/living/silicon/robot/robot.dm

Robot tools can now be modded by an external user. Robot has to be wielding a valid tool. User will attempt to install the tool upgrade by using the upgrade on the robot.
Robot can uninstall mods by itself if it has a screwdriver, or an external user can uninstall by using a crowbar with the robot's panel being open.
I also made it so that the robot's active module is visible on examine.

Robot tool upgrading

---

code/modules/projectiles/guns/energy/egun.dm
code/modules/projectiles/guns/energy/laser.dm
code/modules/projectiles/guns/energy/stun.dm

Just makes the rig modules not check for Safeties, letting them be used easily, since only the Cyborg can toggle their safety.

Removes Safety Check from Rig Guns

---

code/game/machinery/alarm.dm

Makes it so you can't keep using wirecutters on an air/fire alarms to get infinite cables.

Fix for infinite air alarm cables

---

code/datums/autolathe/ammo.dm

Now you should not miss these ammos

Fix SMG's ammo typo

---

code/game/machinery/excelsior/ex_turret.dm

Extends turret working range by 50%
Fixes infinitely duplicating energy guns when disassembling turrets

Excelsior Turret Fixes

---

code/datums/autolathe/parts.dm
code/game/antagonist/station/revolutionary/excelsior.dm
code/game/gamemodes/storyteller_meta.dm
code/game/objects/items/weapons/autolathe_disks.dm
code/game/objects/items/weapons/implant/implant.dm
code/game/objects/items/weapons/implant/implants/excelsior.dm

Fixes excelsior implants not being properly setup when spawned by storyteller, resulting in their own turrets shooting them
Fixes storyteller having a defunct "roleset" option in the roleset pool which wasted antag points
Adds many parts to the excelsior disk so they can actually create shield generators

Excelsior Fixes

---

code/game/area/areas.dm

Fixes a runtime error caused by npc mobs entering new areas.
Presumably this code was originally not designed for roaches that could travel around via burrows

Ambiance Runtime Fix

---

code/modules/research/rdconsole.dm

Now DISPOSE ALL REAGENTS pops only if there are any reagents, not for everyone in
list as it was before.

Protolathe and curcuit implanter's markdown fix

---

code/controllers/subsystems/jobs.dm
code/modules/client/preference_setup/loadout/loadout.dm
code/modules/mob/new_player/preferences_setup.dm

This fixes job-specific loadouts never being available for ANY job.
Loadout items have job titles in their allowed_roles ("Moebius Doctor"), while the check for eligibility checks the job type ("/datum/job/doctor"). This makes it so that the check is for the job title instead of the job type, fixing that loadout bug.

Loadout fix

---

code/game/machinery/doors/airlock.dm
code/game/objects/items/weapons/tools/_tools.dm

closes #2617
The title sums it all up pretty neatly.
* It may look derpy with tools that are not crowbar.
You wedge a tool in by holding it in hand, and in right-click dropdown menu of airlock clicking "Wedge item", or by putting it on the same tile as the airlock.
You take the tool out in one of three ways: dropdown menu "Take out wedged item", grab intent-click, mousedroping the airlock onto you.

Weging crowbars: RE

---

code/game/objects/items/weapons/autolathe_disks.dm
code/modules/projectiles/ammunition/bullets.dm

Two bugs with .32 hollowpoints: The bullet's caliber is .38, and the magazines don't show up on the lethal ammo disk. This fixes both.
Fixes #2776

Fixes for .32 lethal ammo

---

code/modules/projectiles/guns/projectile.dm

Basically, bullet pile code went wrong. It deleted the ejected bullet casing while trying to pile the bullet with itself. Fiiixed.
Fixes #2757

Fixes guns not dropping bullet casings

---

code/modules/clothing/clothing.dm

Makes it so that using screwdrivers to set suit sensors actually proc for all under clothing, instead of just ranked clothing (those associated with jobs).

Allows setting suit sensors for non-ranked clothing

---

code/game/machinery/camera/camera.dm

You can now hit security cameras with melee if your intent is set to harm.
Fixes #2822

Hitting cameras with melee

---

code/game/objects/structures/stool_bed_chair_nest/bed.dm
html/changelogs/beddismantle.yml

Beds and subtypes were runtiming when dismantled due to the attempted creation of a /material (datum) type, this has been resolved and they now get dismantled properly, and drop some steel. Also, to dismantle/remove the padding, the checks now use tool qualities instead of strict type-checks for basic tools.
Addresses a tiny part of #2840 , might want to remove beds from the list

Bed dismantle runtime fix and tool quality standardization

---

code/modules/mob/living/say.dm

Speechbubble code used sleep() instead of spawn(), meaning that say() code had to wait for the speech bubble to end before calling hear_talk().
Fixes #2796

Fixes input lag for hear_talk

---

code/game/objects/items/devices/taperecorder.dm
code/modules/modular_computers/file_system/programs/generic/file_browser.dm

Fixes 2 bugs:
Stopping and starting a recording a second time made the first recording get repeated in the transcript.
You could read an audio file's transcript without transcribing it by opening it in the file manager.

Fixes some bugs with audio files

---

code/game/objects/items/weapons/traps.dm

If the roach got gibbed by this bear trap, you cannot pick it for some time until the process() managed to free invisible mob ( buckled_mob ) from his trap.
🆑 TorinoFermic
fix: Bear traps can be picked again right now after a mob has gibbed on the trap.
/🆑

Unpickable beartrap bug fix

---

code/game/objects/items/weapons/autolathe_disks.dm

Accidentally put in the path for the autolathe board a second time instead of the path for the custom vendomat. Whoops.

Fix for printing vendomat boards in autolathe

---

code/game/machinery/doors/blast_door.dm

Fixes #2554 . Sometimes the doors may just disappear instead of being opened, but that's apparently intended, because the drill calls ex_act(2) on what it drills, and the default behaviour for doors is to either qdel themself immediately with a low chance, or take enough damage(300) to be force-opened.

Fixes blast door not opening when being drilled

---

code/game/gamemodes/events/money_lotto.dm
html/changelogs/lottery.yml

Fixes #2832 and removes the chance for departments to be chosen as winners.

Fixes lottery taking into account departments, and wild html tags

---

code/modules/multiz/planes.dm

This should fix a lot of similar cases.
If an object z = 0, this object is either in the nullspace, or in the other object contents and invisible. 
If object is on the screen, it should be on the above_hud plane.

Robot items plane fix

---

code/modules/multiz/map_data.dm

It was being populated with the original zlevel and not the actual z_level
With this fix, NTnet works again for PDAs

Fixes station_levels list

---

cev_eris.dme
code/controllers/configuration.dm
code/controllers/subsystems/ticker.dm
code/controllers/subsystems/voting/poll_types.dm
code/game/antagonist/antagonist_panel.dm
code/game/gamemodes/roleset/roleset.dm
code/game/gamemodes/storyevent.dm
code/game/gamemodes/storyteller.dm
code/game/gamemodes/storyteller_helpers.dm
code/game/gamemodes/storyteller_print.dm
code/game/gamemodes/storytellers/mime.dm
code/modules/admin/topic.dm

Adds an inactive storyteller, the mime, which will not trigger events or accrue points. This was designed for use in admin-events.
Also lets admins change the storyteller midround.
Both of these were requested by @GrayRachnid 
Moves both storyteller & storyteller_cache to GLOB, so they're easier to access & modify.

Adds an inactive storyteller, and lets admins change storytellers midround.

---

code/game/objects/random/junk.dm
code/game/objects/random/traps/traps.dm
code/modules/scrap/scrap.dm

A couple of quick prerelease tweaks based on internal testing, for the new scrap feature:
Increases the spawn rate of scrap piles
Adds more junk to their loot lists, and lowers the spawn rate of rare loot inside them
Also, tangentially, slightly increases the spawn rate of randomly generated traps

Scrap Balancing Tweaks

---

code/game/objects/items/devices/t_scanner.dm

get_relative_plane doesn't work if the item is in an inventory, since then their Z is zero. I'd change it to use loc if the Z is zero, but I'm not sure whether @NanakoAC would approve of that :)
fixes: #3012

Fixes the t-ray scanner not working :)

---

code/modules/mob/living/silicon/robot/robot.dm

Fixes #3036
Expanding on the issue - queuing up the borg module change prompt would allow multiple concurrent module changes, allowing the module items pools to be drawn from at will. Also messed up the HUD with ghost item sprites.  Adds checks in the alert switch statement to prevent this.

Fixes borg module duplication

---

code/controllers/subsystems/jobs.dm
code/game/jobs/job/civilian_chaplain.dm
code/game/jobs/job/job.dm
code/game/jobs/job/security.dm
code/game/machinery/vending.dm

Vending machines with auto pricing enabled now automatically price their products if a price is not specifically set.
Fixes a bug where you can't restock non-custom vendors. You need to screw open the panel to load it now.
Chaplain and Ironhammer Gunnery Sergeant can now access their department's account.

Vending machine & department account fixes

---

code/game/machinery/cryopod.dm

Makes the game start life more bearable.
🆑 TorinoFermic
change: You can exit cyropods with movement keys like sleepers.
/🆑

Cryopods can be exited by pressing movement keys after sleeping timer.

---

code/datums/topic/admin.dm
code/modules/admin/admin.dm
code/modules/admin/player_panel.dm

Can reach it from the player panel, as well as the bigger list of players (which is also incidentally called Player Panel?). No more clicking through VV to read those ugly logs.
I considered adding a search function, but disappearing logs would be annoying as hell. You can ctrl+f in there anyway.

Attack Log viewer

---

code/modules/mob/observer/ghost/ghost.dm

Ghosts will be able to unfollow mobs by moving around.
Fixes #3137
🆑 TorinoFermic
fix: Ghosts will be able to unfollow everything by moving.
/🆑

Fixes the ghost's unfollow ability

---

code/modules/mob/living/say.dm
code/modules/mob/say.dm

Code is ported from Baystation12
Also, the code handles with Russian letters, whispering.
Fixes #2714
🆑 TorinoFermic
fix: Radios has been augmented to use "." or ":" and you can whisper with ".w" or ":w". Just like all other servers.
/🆑

Change : You can use radios with . in addition to :

---

code/game/machinery/cryopod.dm

Cryopods creators forgot to set one critical part to solid form.
🆑 TorinoFermic
fix: You won't wake up at wrong side and getting stuck.
/🆑

Cyrofeed structure made solid to avoid trapping arrival players.

---

code/modules/projectiles/projectile/bullettypes.dm

10mm is a bigger and more powerful cartridge than .45, so it makes little sense that .45 does more damage in game. This PR switches the values and makes 10mm do slightly more damage (as again, it is a very powerful cartridge).

Switch damage values of 10mm and .45

---

code/game/antagonist/antagonist.dm
code/game/antagonist/station/revolutionary/excelsior.dm
code/game/gamemodes/roleset/faction/excelsior.dm
code/game/gamemodes/roleset/faction/roleset_faction.dm
code/game/gamemodes/roleset/roleset.dm

Changed so the antag Excelsior won't apply to heads of staff by the storyteller.
Excelsiors can forcefully implant heads or IH just fine.
🆑 TorinoFermic
tweak: Excelsior will not apply to head of staff or Ironhammer for the storyteller picking.
/🆑

[BALANCE] Excelsior antag won't be given to Heads or Ironhammer.

---

code/modules/mob/living/carbon/carbon.dm

Fixes #3282, lets you forget about your jetpack stabilization.

Magboots movement

---

code/game/objects/items/_inventory.dm
code/modules/clothing/clothing.dm
code/modules/clothing/shoes/magboots.dm
code/modules/clothing/spacesuits/rig/rig.dm
code/modules/clothing/spacesuits/rig/rig_pieces.dm
code/modules/mob/inventory/equip.dm
code/modules/mob/inventory/helpers.dm
code/modules/mob/mob.dm

Closes #3177
* Added `overslot` mechanics all over equipable items.
Currently only magboots (hardsuit boots - too) have such feature, but it could be turned on to everything by VV. No checks on what type of thing we got under overslot item, besides it cannot be other item with overslot abilities.
Quite TODO thing, but you would be able to put space helmet under overslot helmet, so only magboots for now.
* Replaced << thingies to to_chat macro inside rig.dm

Overslot thingie

---

code/modules/stashes/stash_datum.dm

Remains are hidden under the current floor. Not anymore of self-defeating stashes.
🆑 TorinoFermic
tweak: Remains of stash are hidden under the floor.
/🆑

[TWEAK] Remains of stash will be hidden under the floor

---

code/controllers/configuration.dm

For future config edit. Current AI still work after PR has merged until the config file has been modified to remove the line "ALLOW_AI" which is present in default config.

Make the config disabling AI in working order

---

code/modules/projectiles/ammunition.dm
code/modules/projectiles/guns/Hatton.dm
code/modules/projectiles/guns/alien.dm
code/modules/projectiles/guns/energy.dm
code/modules/projectiles/guns/launcher.dm
code/modules/projectiles/guns/launcher/crossbow.dm
code/modules/projectiles/guns/launcher/grenade_launcher.dm
code/modules/projectiles/guns/launcher/pneumatic.dm
code/modules/projectiles/guns/launcher/rocket.dm
code/modules/projectiles/guns/launcher/syringe_gun.dm
code/modules/projectiles/guns/projectile.dm
code/modules/projectiles/guns/projectile/automatic/IH_heavy.dm
code/modules/projectiles/guns/projectile/automatic/dallas.dm
code/modules/projectiles/guns/projectile/automatic/lmg.dm
code/modules/projectiles/guns/projectile/automatic/maxim.dm
code/modules/projectiles/guns/projectile/automatic/sts35.dm
code/modules/projectiles/guns/projectile/dartgun.dm
code/modules/projectiles/guns/projectile/pistol/handmade.dm
code/modules/projectiles/guns/projectile/pistol/lamia.dm
code/modules/projectiles/guns/projectile/shotgun/doublebarrel.dm
code/modules/projectiles/projectile.dm

All guns with magazine will have by default have their tactical reload enabled unless otherwise stated.
All machine guns does not have tactical reload.
🆑 TorinoFermic
rscadd: Tactical reload added for all magazine-type guns. Machine guns cannot use it.
tweak: No relevant to gameplay but changed from bunch lines to something sane in the code.
tweak: Lamia and Dallas does have the autoejection.
/🆑

[QOL] Adding tactical reload and changes to chat lines.

---

code/modules/hivemind/machines.dm

Tuning the hivemind to delay the spawning of monsters to 30 seconds in case of explosive probes.
🆑 TorinoFermic
tweak: Changed hivemind spawner to 30 seconds, increased hp to compensate for it. Increased max amount to 3.
/🆑

[BALANCE] Fine tuned the spawner to slow down the spawning

---

code/game/objects/items/weapons/grenades/explosive.dm

Adjusting the damage to make useful these HE grenades, discussions might be needed to decide the damage numbers since the damage also vary wildly from no-crit to holy-fuck-I-need-medic.
Damage can range from 50 to 201 from just one HE grenade atop a prone guy, being prone reduces the damage.
🆑 TorinoFermic
tweak: HE grenades's damage upped to compensate the changes of shrapnel. They never embed.
/🆑

[BALANCE] HE grenade damage application

---

code/game/machinery/vending.dm

Here comes the long awaited feature that everyone asked for but I always kept forgetting to actually do.
Custom vendors now generate a separate entry for items that have the same type but different names. This means you can label bottles or pills differently and they'll get their own entry on the product list.

Custom vendors now separate same-type items

---

code/game/objects/items/weapons/storage/firstaid.dm
code/modules/reagents/machinery.dm

So as it turns out, the ChemMaster was trying to use the pill bottle's "storage_slots", which the pill bottle object never redefined, so it just inherited to being just "null". And because of that, the pill bottle's storage just straight up DID NOT EXIST according to the ChemMaster. (closes #1253 )
**fix:** Pills now actually go into pill bottles.
**tweak:** Pill bottle max storage space increased to 12 from 8 as to allow a beaker of 120u to comfortably fill a pill bottle with 10u pills (can be reverted if needed)

ChemMaster Pill Bottle Fix

---

code/modules/mining/machine_stacking.dm
code/modules/mining/mine_items.dm

A redo of the last PR that doesn't have anything to do with the map. Gives miners a slight QoL change.
**tweak:** stacking machine defaults sheet stacks to 120 and now has the option in its stacking console
**tweak:** removed one of the fuel tank attachments and the random tool attachment spawn in the locker to give miners optical meson glasses, a heavy duty flashlight, a drill instead of a jackhammer, and a small cell for their mesons.

Mining Changes

---

code/game/objects/items/weapons/stunbaton.dm
code/modules/clothing/gloves/stungloves.dm
code/modules/mob/living/carbon/human/human_defense.dm

That's up for discussion due many rounds where people are getting caught by IH way too easy.
🆑 TorinoFermic
tweak: Stuns and agony adjusted.
tweak: You can make the target drop the inhand item by aiming their arms and hitting with active stunbaton.
/🆑

[TWEAK] Rebalance of agony for stun gameplay

---

code/game/objects/structures/wire_splicing.dm
code/modules/clothing/shoes/jobs.dm
code/modules/clothing/shoes/magboots.dm
code/modules/clothing/shoes/miscellaneous.dm
code/modules/power/cable.dm
code/modules/power/power.dm

- Added `proc/electrocute_mob ` ability to damage legs
- Made `proc/electrocute_mob` actually use insulation coefficients for gloves/shoes
- Added "reinforcement" for wire splicing: use cable coil with `harm` intent.
It would try to zap your hands and legs, use some insulation
- Tweaked insulation coefficients for some shoes.
Magboots, antag shoes from uplink and galoshes are fully insulated now.
- Added ability to make splicing from current wiring. Any wiring on floor.
Use cable coil with 'harm' intent.
- Added ability to spawn splicing on tools failure.

Splicings interaction

---

code/game/machinery/doors/multi_tile.dm

No more `door.dm,420: Cannot execute null.set opacity().`
Glass multi-airlocks weren't properly initialized

Fixes door.dm,420

---

code/game/turfs/simulated/cleaning.dm

Floors no longer stay lubed permanently until you exorcise it using an RCD set to deconstruct.

Removes infinite lube

---

code/modules/mob/living/carbon/carbon.dm

You gotta be kidding. 
There is cool if check in `/mob/living/carbon/throw_item(atom/target)` proc
https://github.com/discordia-space/CEV-Eris/blob/ddafebb29898d94125ac75f589e26766a696b367/code/modules/mob/living/carbon/carbon.dm#L278
Grab can't be unequipped, duh.
Sadly, it was there from 29.01.18 - https://github.com/discordia-space/CEV-Eris/commit/32114a9c4a7200e17d943fa55f152f49a9c6924c

Throwing mobs

---

code/modules/lighting/lighting_setup.dm

Runtime was caused by improper initialization - turfs without any light would get no `lightning_corner` datums

Fixes lighting_turf.dm,63

---

code/__defines/weapons.dm
code/game/machinery/doors/airlock.dm
code/game/machinery/doors/showcase.dm
code/game/machinery/portable_turret.dm
code/game/objects/items/weapons/material/twohanded.dm
code/game/objects/items/weapons/storage/toolbox.dm
code/game/objects/structures/window.dm

Windows now use the defines set out in defines weapons.
Slightly tweaks said define values.
Fixes most glass airlocks having an incorrect resistance value, making them stronger than regular airlocks.

Expands uses of the resistance value.

---

code/game/objects/items/weapons/implant/implants/excelsior.dm
code/modules/surgery/implant.dm

All implants should be calling uninstall() when removing these implants by surgery or by cruciform.
Fixes #3308
🆑 TorinoFermic
fix: Excelsior role removal works now when removing the excelsior implant via surgery.
/🆑

[FIX] Excelsior implants's role removal works now.

---

code/game/objects/structures/burrows.dm

The proper fix would involve porting persistent mob tags from tgstation, but this would do too.

Fixes burrows runtime

---

code/game/objects/items/weapons/tools/_tools.dm

Drills will no longer kill you on re-fuel.
This code is tested in-game, only works if the tool uses fuel, and has an active welding tool quality.
fixes #3551

Fixes welder tanks exploding when they shouldn't

---

nano/To BYOND Cache.bat

It was broken by a BYOND update that changed the way cache folder works. I fixed it.

Fixes NanoUI "To BYOND Cache" script

---

code/modules/cargo/packs.dm

Certain crates could be bought and then resold for considerable profit margins. While the concept of "buy low, sell high" is usually a staple of any economic system, it just doesn't work with our current static system.
Not until we somehow get a system that fluctuates the price of cargo crates to allow for actual risk of investing paying off with profit.
**tweak:** certain cargo crates can no longer be exploited with resale to make profit.

Fixes Cargo Exploits

---

code/game/objects/items/weapons/traps.dm
code/game/turfs/simulated/cleaning.dm

You can no longer pick up deployed traps, you have to disarm them first.
When you examine a deployed trap, you become aware of it and won't trigger them when you WALK into them.
Fixed a bug where lubed floors would never get delubed.

Changes to traps

---

code/game/jobs/job/security.dm
html/changelogs/Kurgis-PR-SkillAdjustmentsMedSpec.yml

Inspector stats adjusted to focus less on Biology skill. MedSpec stats adjusted to focus on Biology skill instead of Vigilance.
Gunnery Sergeant given MedSpec access, as it's essentially an extension of the Brig. Inspector given MedSpec access, as it's important for forensics.
Here's some reasoning for the stat changes, and some comparisons.
First, regarding the MedSpec's stat changes:
1. The MedSpec had the second highest VIG stat on the ship, higher than every role except the IH Commander.
2. The Inspector was inferior to the MedSpec, as they held both the same BIO stat, the MedSpec's higher VIG stat, and their lack of access to use forensic machinery.
3. MedSpec is support staff for the IronHammer Division, they shouldn't be able to operate on their own.
Second, regarding the …

Adjusts MedSpec & Inspector skills, gives medspec access to multiple Security roles.

---

code/controllers/configuration.dm
code/controllers/subsystems/ticker.dm
config/example/config.txt

This PR adds automatic server restart when there is no players on a server for some time (can be changed in config)
Will not restart if there is no value in config or it is 0

Automatically restarts server after sometime if no players

---

code/game/turfs/flooring/flooring.dm

Carpet got a problem with openspaces. It was fixed.
Before:
After:

Carpet floor fix.

---

code/modules/mob/living/carbon/superior_animal/defense.dm
html/changelogs/TorinoFermic-gibfixitems.yml

Bug fix, superior_animal doesn't have the code for embed items. I just copied a part of code from human/gib()
Fixes #3423
🆑 TorinoFermic
bugfix: Items will now eject from gibbed roaches.
/🆑

[FIX] Embed items will eject now from gibbed roaches

---

code/__defines/mob_stats.dm
code/datums/craft/recipe.dm
code/datums/craft/recipes/airlocks.dm
code/datums/craft/recipes/clothing.dm
code/datums/craft/recipes/floor.dm
code/datums/craft/recipes/furniture.dm
code/datums/craft/recipes/machinery.dm
code/datums/craft/recipes/misc.dm
code/datums/craft/recipes/tools.dm
code/datums/craft/recipes/weapon.dm
code/datums/craft/step.dm
code/datums/mob_stats.dm
code/game/machinery/doors/airlock.dm
code/game/objects/items/weapons/tools/_tools.dm
code/game/objects/items/weapons/traps.dm
code/game/objects/structures/burrows.dm

Crafting speed now depends on stats.
Making recipes availability based on stats will be mistake, instead it should be based on knowledge, like baystation's education background or learned by books etc.
Reworked stat checks, previous way was unintuitive mess.
Added new grey railing crafting recipe.

Crafting improvements, stat checks reworks

---

code/game/objects/items/stacks/nanopaste.dm

it costs 100 plastic to print this stuff because 1 use of it has 10 plastic and it prints 10 of it. big yikes.
this brings the matter in it from 10 per use to 2 per use, which should lower it to a more reasonable cost of 20 per stack. open for other numbers at this point.

nanopaste material cost reduction

---

code/datums/autolathe/tools.dm
code/game/objects/items/weapons/autolathe_disks.dm
code/game/objects/items/weapons/tools/bonesetters.dm

Simply adds a a bone setter tool to Moebius Medical Designs disk so that medical can get replacements if needed.
To make a new bone setter you just need 4 metal, same as a retractor.

Adds Bone Setters to Moebius Medical Designs

---

code/game/objects/items/weapons/storage/wallets.dm

The front_id variable on wallets wasn't clearing itself properly. By deleting a single line and unindenting a few others, it clears itself properly now.

Wallet front_id exploit fix

---

code/datums/objective/steal.dm
code/game/objects/items/toys.dm
code/modules/mob/living/carbon/human/human.dm
code/modules/reagents/reagent_containers.dm
code/modules/reagents/reagent_containers/hypospray.dm
code/modules/reagents/reagent_containers/pill.dm

Closes #358 by changing the names to be a little more lore-friendly.
Closes #1701 - unable to reproduce.
Closes #3249 - unable to reproduce.
Closes #3375 by clarifying you only need the control module.
Closes #3398 by adding an 'empty' verb to hyposprays.
Closes #3409 by fixing the job title.
Closes #3419 - unable to reproduce.
Closes #3424 - unable to reproduce.
Closes #3448 - unable to reproduce.
Closes #3581 by making pills actually work like they're supposed to.

Bugfix Bonanza

---

.gitignore
code/modules/client/preference_setup/loadout/lists/accessories.dm
code/modules/client/preference_setup/loadout/lists/clothing.dm
code/modules/client/preference_setup/loadout/lists/eyegear.dm
code/modules/client/preference_setup/loadout/lists/footwear.dm
code/modules/client/preference_setup/loadout/lists/gloves.dm
code/modules/client/preference_setup/loadout/lists/headwear.dm
code/modules/client/preference_setup/loadout/lists/misc.dm
code/modules/client/preference_setup/loadout/lists/suits.dm
code/modules/client/preference_setup/loadout/lists/uniforms.dm
code/modules/client/preference_setup/loadout/lists/utility.dm

This will facilitate the speed of finding things in loadout among colored clothes.
`.gitignore` now ignore __pycache__ of python, ignore .sav and folder tmp/, and ignore things.history of visual code. .before of mapmerge ignoring too.
:cl:AlexMorgan3817/_Elar_
tweak: Many of colored clothes now compressed in one datum, that will improve comfortability of searching in loadout.
/:cl:

Optimizing and some recast of loadout

---

code/game/objects/items/weapons/circuitboards/machinery/power.dm
code/modules/power/breaker_box.dm

:cl:
add: Allowing to construct and deconstruct breaker box
/:cl:

Allowing to construct and deconstruct breaker box

---

code/__defines/components.dm
code/game/atoms_movable.dm

Reduse plane recalculation calls.
Implement `COMSIG_MOVABLE_MOVED` signal call. Items not located on map will not try to update plane.
:cl:
add: `COMSIG_MOVABLE_MOVED` signal call
tweak: reduse `update_plane` calls
/:cl:

Update movement code a bit

---

nano/css/shared.css
nano/js/nano_base_helpers.js

Buttons are less ugly now.
:cl:
fix: Removed superfluous padding in NanoUI buttons without text
/:cl:

NanoUI: Remove padding for icons without text

---

code/game/machinery/walllockers.dm
code/game/objects/structures/crates_lockers/closets.dm
code/game/objects/structures/crates_lockers/closets/secure/personal/_personal.dm

It stops the annoyance and fixes the access for closets. 
:cl:
fix: Closets will check first the ID then Cruciform. No more annoyances.
/:cl:

[FIX] Closets will check ID then cruciform now

---

code/modules/biomatter_manipulation/bioreactor/biotank.dm
code/modules/biomatter_manipulation/toxic_biomass.dm

Quick fix to toxins spills from bioreactors when cleaning it with a mop.
Reduction of tox damage when wearing anything good.
Unsure about the goal of this in this code.
:cl:
balance: Bioreactor spills should be less deadly.
fix: Typo in a line from Bioreactor
/:cl:

[Balance] Possible fix for damage reduction when wearing anything

---

cev_eris.dme
code/__DEFINES/misc.dm
code/__HELPERS/__v512.dm
code/__HELPERS/_lists.dm
code/__HELPERS/unsorted.dm
code/game/jobs/department.dm
code/modules/organs/external/_external.dm
code/modules/surgery/generic.dm

CEV-Eris will now build and run on BYOND v513.
It still doesn't use any v513-specific features, as we don't want to break v512 compatibility yet.

Basic v513 support

---

code/modules/mob/living/carbon/human/human_damage.dm

Reverts the `adjustToxLoss` change made in #3697, because it caused toxins to become incredibly lethal, and the new medicine rework would do it differently anyway. 
Fixes #3809.

Reverts toxin damage changes

---

code/game/objects/items/weapons/traps.dm

<details>
<summary>
</summary>
<hr>
Fixed bear traps initial values and will stop harpoon gun from teleporting anchored traps now.
<hr>
</details>
:cl:
fix: Harpoon guns will not teleport anchored bear traps
fix: All bear traps will come anchored, so they don't move with pressure changes or ZAS.
code: Cleaned traps.dm code for future additions.
/:cl:

[FIX] Bear trap should prevent the Harpoon from working while armed.

---

code/game/machinery/autolathe.dm

<details>
<summary>
</summary>
<hr>
Update_icon() of autolathe now can be inherit
<hr>
</details>
:cl:
refactor: Update_icon() of autolathe now can be inherit by subtypes of it
/:cl:

Cleaning from shit code of autolathe.update_icon()

---

code/modules/reagents/reagent_dispenser.dm

Fix #3853.
:cl:
fix: tool refuelling no longer triggers an attack
/:cl:

Fixes tool refuelling

---

code/modules/mob/living/carbon/superior_animal/roach/blattedin.dm

Before, it was stronger than plasma and cyanide combined. Which clearly wasn't intended.

Makes blattedin significantly less lethal

---

code/game/objects/items/devices/radio/encryptionkey.dm
code/game/objects/items/devices/radio/headset.dm

<details>
<summary>
Gives medical personnel access to research channels and vice versa. Both work for Moebius and so the communication between two shouldn't be treated as though they're completely separate departments (especially with medical personnel having access to science and vice versa).
Keeps medical and research channels separate, partly for my own sanity, but also to help prevent discussion within the departments from getting jumbled up with the others' business, though still keeping them in the know of each other.
</summary>
</details>
:cl:
tweak: Moebius medical and research now have access to each other's channels in a single encryption key.
/:cl:

Unifies Moebius Communications

---

code/game/objects/items/weapons/cosmetics.dm

Fix #3879
:cl:
fix: runtime occures during lipstick usage
/:cl:

Fix runtime during lipstick usage

---

code/modules/reagents/reagent_containers/food/snacks.dm

Fix #3876
That code part should be replaced with timer one day.
:cl:
fix: runtime what occures if heated Donk-pocket was eated
/:cl:

Fix heated donk-pocket related runtime

---

code/game/objects/structures/crates_lockers/closets/secure/personal/_personal.dm

fix #3875 
<hr>
</details>
:cl:
fix: runtime occures when smone trying to open personal closet without ID card
/:cl:

Fix personal closet related runtime

---

code/__DEFINES/_planes+layers.dm

Plane values that high worked fine on v512, but upcoming v513 wouldn't be so tolerant. Planes beyond -10000 to 10000 are sin, and we repent.

Fixes some UB that backfired on v513

---

code/modules/reagents/recipes.dm

<details>
<summary>
Recipe now uses ammonia, a fertilizer, instead of nutriment. This allows chemistry to make it in the absence of anyone willing to do botany, and should stop it from mixing in certain foods.
</summary>
<hr>
<hr>
</details>
:cl:
/:cl:

EZ Nutrient Recipe Fix

---

code/__DEFINES/misc.dm
code/datums/mob_stats.dm
code/modules/core_implant/core_implant.dm
code/modules/core_implant/cruciform/machinery/obelisk.dm
code/modules/core_implant/cruciform/rituals/group.dm
code/modules/core_implant/group_ritual.dm

Phrases will now be repeated automatically by everyone around who knows the ritual.
Cooldown removed.
Every phrase must be read near an active obelisk to work.
Buff litanies now require at least 3 followers (for a total of 4 people) and provide global stat buff through obelisks.
Crusader litany now requires at least 6 followers (for a total of 7 people) and opens all crusader litanies when finished.
A buff is activated by completing a buff litany. Completing another will replace the buff.
When a buff is active, all active NT obelisks give the buff to NT followers in their active area. Outside of the active area the buff lasts 20 minutes. The buff power depends on the amount of NT followers on the ship.
:cl:
tweak: reworked group litanies
/:cl:

Group litany rework

---

code/datums/outfits/jobs/engineering.dm
code/game/objects/items/weapons/storage/belt.dm
code/modules/stashes/stash_types/weapons.dm

That was a dumb idea that contributed nothing but annoyance to the game.

TM toolbelts no longer spawn half empty

---

code/modules/research/designs/weapon.dm
code/modules/research/nodes/combat.dm

<details>
<summary>
Adds C-20r ammo to Advanced-Lethal Weapons Node of Combat research
</summary>
<hr>
I have made it so when someone researches Advanced Lethal weapons, they get not only the C-20r, but the ammo for it, which can also be made in the proto lathe and auto lathe. All of sciences other weapons come with ammo either built in in the form of rechargables, either by rechargers or on their own, or with the ability to install power cells which Moebius can get very good ones easily.
<hr>
</details>
:cl:
add: Added a research datum for 10 mm SMG ammo
add: Added 10 mm SMG ammo to be researched alongside the C-20r so it doesnt go without ammo
/:cl:

Rnd ammo additions

---

code/modules/recycling/disposal.dm

Allows plant/ore/plastic bags to be emptied in disposals bin like the trash bag. The only issue (or non-issue) is that you can not longer put the those bags in a bin by clicking it with the bag in hand. Nonetheless you can still dump the bag by dragclicking the sprite into the disposal bin. (But why would you want to do that, most bag types are pretty fucking rare)
I tested interactions and nothing seems to be broken, you can still load ore crates with ore bags, the trash bag icon still updates properly when emptied and you can still empty any bag by just clicking on a tile.
In short, this is a QoL for agrolytes and custodians.
:cl:
tweak: You can now empty plant, ore and plastic bags in disposals bins without having to dump the whole thing in. You can still dump those bags by …

Allows any type of /storage/bag to be emptied in a disposal bin.

---

code/game/machinery/smelter.dm
code/game/machinery/sorter.dm
code/game/objects/structures/crates_lockers/closets.dm
code/game/objects/structures/crates_lockers/crates.dm

Sorter now automatically opens containers (closets, crates, etc.) and processes their contents one by one. If the container is locked, it is refused.
Smelter and sorter input is no longer limited to items.
:cl:
add: added ability to open containers to sorter
/:cl:

Container processing in sorter

---

code/game/objects/random/guns.dm
code/modules/cargo/packs.dm

<details>
<summary>
Surplus crates are back at their previous price of 2000, but with increased guns per crate.
</summary>
<hr>
This PR decreases the price of surplus crates by 1000 to 2000 and increases the number of guns to 4 from 2 per crate.
<hr>
</details>
:cl:
balance: changed price of surplus crates to 2000
tweak: Changed Amount of guns in a surplus crate to 4 from 2
/:cl:

(Fuck wrong name) reduces Surplus crates price to 2000, changes guns in the crate to 4 from 2.

---

code/modules/projectiles/guns/projectile/automatic/sts35.dm

Reverts discordia-space/CEV-Eris#3991
It appears that we don't need this.

Revert "sts can now fit in backpack"

---

code/modules/clothing/clothing.dm

Fixes age old syntax error that prevented flamethrowers from fitting in suit storage (also thanks to my last pull they also fit belts now which is nice i guess?)

Flamethrowers actually fit suit storage now 

---

code/game/objects/structures/window.dm

<details>
<summary>
Full windows no longer override other checks first.
</summary>
<hr>
This change of behavior prevents characters from placing other characters on a low wall, despite the presence of a full window on that same turf.
<hr>
</details>
:cl:
/:cl:

Full windows no longer have priority when determining entering or leaving a turf.

---

maps/encounters/asteroid/asteroid.dm

<details>
<summary>
Asteroid no longer needs to be flown to.
</summary>
<hr>
There's no reason for the asteroid to be off of the ship's starting location, it just annoys and delays the miners until the ship can be moved to it. This wastes time that can be done doing something much more interesting, like exploring the Abandoned Fortress or the new encounter system since they still need to collect minerals.
<hr>
</details>

Asteroid starts on Ship's starting location.

---

code/game/area/areas.dm
code/modules/sanity/sanity_area.dm
code/modules/sanity/sanity_atom.dm
code/modules/sanity/sanity_mob.dm

Area sanity is now calculated once when an object with sanity bonus moves to or from an area instead of being calculated every Life tick for each mob.

Reducing sanity lag

---

code/game/area/areas.dm

Some objects providing area sanity bonus were initialized before area sanity was, resulting in a runtime. Area sanity is now initialized earlier.

Area sanity runtime fix

---

code/modules/mob/living/carbon/carbon.dm

<details>
<summary>
Currently if you throw a mob and it lands near you, you will maintain your grab. This can be abused to break things like airlocks, reinforced windows, etc. really fast. This PR makes it so you let go of the mob you were grabbing after you throw them.
</summary>
<hr>
<hr>
</details>
:cl: Garen7
fix: You will now let go of people after throwing them.
/:cl:

Fixes mob throw spamming

---

cev_eris.dme
code/__DEFINES/components.dm
code/datums/components/fabric.dm
code/modules/mob/living/carbon/human/human.dm
code/modules/mob/living/carbon/human/human_defines.dm
code/modules/mob/living/carbon/human/life.dm
code/modules/mob/mob.dm
code/modules/mob/observer/ghost/ghost.dm
code/modules/sanity/breakdowns.dm
code/modules/sanity/sanity_mob.dm

Added global sanity damage modifier for easier balancing, currently set to 70%.
Changed sanity view damage threshold from a define to a varibable, allowing to modify it per-character.
Ghosts how have fabric images too.

Sanity damage tweaks & Fabric for ghosts

---

code/modules/mob/mob.dm

<details><summary>About The Pull Request</summary><hr>
Stats values data outputs moved from status to browser opening by verb "Show Stats' Values"<hr></details>
:cl:
refactor: Stats values outputs moved from status to browser opening by verb "Show Stats' Values"
/:cl:

Relocate stats output from status to verb

---

code/modules/clothing/spacesuits/void/station.dm

<details>
changes rad protection from 90 to 100 on voidsuit helmet and regular suit
</summary>
<hr>
cant you read
<hr>
</details>
:cl:
tweak: tweaked engineering voidsuit armor values of rad to 100 from 90
/:cl:

gives engineers voidsuits rad protection in line with mining and medical void suits

---

code/modules/projectiles/guns/energy/egun.dm

<details>
<summary>
Fixes #4051 Fixes #3383 
I also made it so that the martin doesn't light up if it doesn't have the power to shoot to make it more clear when you are out of ammo or don't have a cell inside the gun.
</summary>
<hr>
**no power**
**stun**
**kill**
<hr>
</details>
:cl: Garen7
tweak: The martin will now have no lights when it does not have enough power to fire
fix: The martin will now properly show the red kill setting lights when set to kill mode
/:cl:

Fix and tweak martin overlays

---

code/game/gamemodes/changeling/changeling_powers.dm

<details>
<summary>
changeling unstun power sets agony to 0
</summary>
<hr>
45 changeling gamer points is a lot for a chemical that doesn't remove agony, and as such it is kind of useless when everyone has stun gloves and agony dealing weapons.
<hr>
</details>
:cl:
balance: changeling unstun power sets agony to 0
/:cl:

changeling unstun now removes agony as it should

---

code/__HELPERS/icons.dm
code/game/objects/effects/decals/Cleanable/misc.dm

Both originate in reagent decal code. No idea if it works correctly now, but it is now less incorrect.

Fixes the two most common runtimes

---

code/game/objects/items/weapons/tanks/jetpack.dm
code/game/objects/items/weapons/tanks/onestar_regenerator.dm
code/game/objects/items/weapons/tanks/tank_types.dm
code/game/objects/items/weapons/tanks/tanks.dm

I tried fixing that bug when all emergency air tanks spawned with a blinking red light. I ended up changing the way gas spawns in air tanks - shouldn't affect gameplay, just makes the code neater.
:cl: ACCount
fix: Emergency air tanks no longer blink red lights all the time.
/:cl:

Air tank refactor

---

code/game/objects/items/weapons/material_trash.dm

Broken devices and burnt circuits should look like this now:
Scrap metal will be left the same since they have a (small) chance of having plenty plasteel in them.

Reduces storage size on two material_trash items

---

code/datums/autolathe/parts.dm
code/game/objects/items/weapons/autolathe_disks.dm

It couldn't print them because there was no design datum for it. Already tested:

Technomancer component disk now allows the printing of voice analyzers.

---

code/game/objects/items/oddities.dm
code/modules/scrap/oldificator.dm
code/modules/scrap/scrap.dm

*  Fixes a runtime when touching a scrap pile for the first time.
*  Stops ore from being oldified.
*  Fixes some minor typos in oddity descriptions.

Scrap fixes

---

code/modules/admin/admin_ranks.dm
code/modules/admin/admin_verbs.dm

Use "Debug - Enable Profiler" to access it. May cause lag, freezes, a sense of dread and insanity.

Adds client-side performance profiler

---

code/modules/recycling/disposal.dm

Disposal rides are now more forgiving, and having high MEC or TGH can help you survive them.
:cl: ACCount
balance: Disposal rides are now more forgiving, and having high MEC or TGH can help you survive them.
/:cl:

Disposal pain train is now more forgiving

---

code/modules/mob/living/carbon/resist.dm

<details>
<summary>
Now you have to break out of the cuffs before you can resist out of the grab just like in every other ss13 server.
</summary>
<hr>
I feel like this is a bug but if I'm wrong someone correct me, either way its pretty annoying when the person you arrested keeps resisting out while you try to bring them to brig, strip them, or whatever you were doing with them. 
<hr>
</details>
:cl:
fix: You can no longer resist grabs while handcuffed
/:cl:

You can no longer resist grabs while handcuffed

---

code/datums/uplink/stealthy and inconspicuous weapons.dm
code/game/objects/items/devices/uplink_random_lists.dm

Old PDA is dead, and this thing should have died with it.
It would be preferable to replace it with something, but that is something for future generations to deal with.

Removes Detomatrix from traitor uplink

---

code/game/objects/items/weapons/tools/misc.dm
code/modules/cargo/packs.dm

Before, it only existed as rare maint loot, and even the Asters Guild couldn't buy it. That wouldn't do.
:cl: ACCount
add: You can now order Asters \"Munchkin 5000\" omnitool in cargo
/:cl:

Adds Asters omnitool to supply order list

---

code/modules/mob/living/carbon/carbon.dm

<details>
<summary>
</summary>
<hr>
Clicking a human mob with an empty hand on help intent while targeting one of their arms will now shake their hand if that arm exists; if it doesn't, you'll hold out your arm awkwardly.
Targeting their head will pat them on the head if they have one; otherwise it'll just shake them as if you targeted the body.
There's already a handshake emote in https://github.com/discordia-space/CEV-Eris/blob/master/code/modules/mob/living/carbon/human/emote.dm#L515 but it didn't seem to do anything and which mob it actually targets seems more than a little ambiguous. That file also has a \*hug emote that doesn't seem to work (it always hugs yourself).
<hr>
</details>
:cl:
add: Clicking on a human mob with an empty hand on help intent while …

Add handshakes and headpats

---

code/game/turfs/simulated/walls.dm

Damaged walls now have a chance of dropping metal fragments on bullet hit. The more damaged the wall is, the bigger the chance.

Walls dropping slugs on hit

---

code/game/machinery/computer/computer.dm
code/game/machinery/doors/airlock.dm
code/game/machinery/doors/door.dm
code/modules/modular_computers/computers/subtypes/dev_console.dm

Damaging airlocks and destroying consoles now produces smoke.
:cl:
add: Added smoke effect on damaging airlocks and consoles
/:cl:

Airlock & console smoke on damage

---

cev_eris.dme
code/game/objects/random/pouches.dm
code/game/objects/random/science.dm
code/modules/modular_computers/file_system/binary/research.dm
code/modules/modular_computers/file_system/binary/tech.dm
code/modules/research/experiment.dm
code/modules/research/rdconsole.dm
code/modules/research/research.dm
code/modules/scrap/scrap.dm
nano/templates/rdconsole.tmpl

This only supports one file type for now, but it can be easily extended in the future. I also added a category of science loot to scrap spawn tables, with some random science-related junk in it - including disks with those science files.
:cl: ACCount
add: Disks with research data can now be found in maintenance.
/:cl:

Adds files that can be uploaded to R&D console for research points

---

code/modules/mob/living/carbon/carbon_defense.dm
code/modules/mob/living/carbon/human/human_defense.dm
code/modules/mob/living/living_defense.dm
code/modules/projectiles/projectile.dm
code/modules/projectiles/projectile/bullettypes.dm

- Hitting a mob with a bullet or a weapon now plays shaking animation. If hit for ~~20~~ *TGH* or more damage, the character will stumble instead, moving himself and stuff around him, dropping tables and interacting with doors and buttons.
- Added knockback effect to certain bullet types. A mob hit by such bullet will be pushed, receiving damage if there is an obstacle. ~~Stumbling will not be triggered.~~
:cl:
add: Added shaking animation on hit and stumbling
add: Added knockback to shotgun ammo
/:cl:

Stumbling & bullet knockback

---

code/game/machinery/autolathe.dm

Fix #3952
Now, when stuffing not an integer number of sheets of material in autolathe, it entirely takes them into itself, without leaving a fractional part to you, giving you the opportunity to feed it endlessly

fix lathes inifinity math

---

code/datums/outfits/jobs/guild.dm

Guild members spawn with empty tool belts now.
When ever I spawn as guild I always immedietly turn around and leave the spawn room using none of the tools in the locker because I don't have a tool belt. 
Would cut down on gear up time by a few minutes not having to go grab a belt
<details>
<summary>
</summary>
<hr>
<hr>
</details>
:cl:
/:cl:

Guild spawns with tool belts now

---

code/modules/biomatter_manipulation/bioreactor/platform.dm
code/modules/clothing/clothing.dm

Biomatter is now something the reactor itself makes from clothing depending on size of the garment and whatnot. Sends out extra material from the garment as waste like everything else.
Biomatter is removed automatically from clothing to be added as people choose to put it and give it recipes require it from the autolathe.
:cl: Wild Jalleo
fix: You can now craft clothing in normal autolathes using the old recipes again.
/:cl:

Changes biomatter code

---

code/modules/cargo/packs.dm

<details>
<summary>
Adds FS revolver crate to cargo 
</summary>
<hr>
One problem with revolvers is that it is hard to get them in any quantity without paying huge prices at the IH vendor. It makes sense guild bought revolvers would be cheaper. This refrains from making this crate too cheap, as it is revolvers compared to handguns but does not exceed the maximum return by too much. 
<hr>
</details>
:cl:
add: FS revolver pack to cargo, contains 2 Havelocks, and 1 Consul  costs 3300
/:cl:

Adds FS Revolver Pack to cargo

---

code/game/objects/items/weapons/storage/bsdm.dm

<details>
<summary>
fixes BSDM inventory size
</summary>
<hr>
Another small fix, increases the max weight class of items that can be placed in the BSDM box and increased the BSDM box's inventory capacity.
Reasoning: some steal contract targets were too large to be placed in the BSDM for traitors to claim the reward
<hr>
</details>
:cl:
/:cl:

fixes BSDM inventory size

---

code/modules/projectiles/gun.dm
code/modules/projectiles/guns/energy/crossbow.dm
code/modules/projectiles/guns/energy/decloner.dm
code/modules/projectiles/guns/energy/egun.dm
code/modules/projectiles/guns/energy/laser.dm
code/modules/projectiles/guns/energy/stun.dm
code/modules/projectiles/guns/energy/toxgun.dm
code/modules/projectiles/guns/projectile/automatic/IH_machinepistol.dm
code/modules/projectiles/guns/projectile/automatic/atreides.dm
code/modules/projectiles/guns/projectile/automatic/drozd.dm
code/modules/projectiles/guns/projectile/automatic/idaho.dm
code/modules/projectiles/guns/projectile/pistol/IH_sidearm.dm
code/modules/projectiles/guns/projectile/pistol/clarissa.dm
code/modules/projectiles/guns/projectile/pistol/colt.dm
code/modules/projectiles/guns/projectile/pistol/deagle.dm
code/modules/projectiles/guns/projectile/pistol/giskard.dm
code/modules/projectiles/guns/projectile/pistol/gyropistol.dm
code/modules/projectiles/guns/projectile/pistol/handmade.dm
code/modules/projectiles/guns/projectile/pistol/lamia.dm
code/modules/projectiles/guns/projectile/pistol/mk58.dm
code/modules/projectiles/guns/projectile/pistol/olivaw.dm
code/modules/projectiles/guns/projectile/pistol/silenced.dm
code/modules/projectiles/guns/projectile/revolver/revolver.dm
code/modules/projectiles/guns/projectile/shotgun/sawnoff.dm

<details>
<summary>
Fixes Dual Wielding 
</summary>
<hr>
Makes it impossible to dual wield (fire simultaneously using harm intent) weapons that should logically be fired while carried with two hands, including most rifles, shotguns, and two-handed SMGs (you can tell the difference between an SMG and a machinepistol by their sprite, the molly can be dual-wielded, but not the straylight).
<hr>
</details>
:cl:
/:cl:

fixes dual wielding rifles and whatnot

---

code/datums/autolathe/ammo.dm

<details>
<summary>
fixed lathe paths
</summary>
<hr>
small fix, just changed the paths for the speedloaders in the autolathe so they actually produce speedloaders instead of popping out magazines
<hr>
</details>
:cl:
<!--fix: speedloaders now print from the lathe properly->
/:cl:

fixed lathe paths

---

code/datums/uplink/ammunition.dm
code/game/objects/items/weapons/storage/deferred.dm
code/game/objects/items/weapons/storage/uplink_kits.dm
code/modules/projectiles/ammunition/magazines.dm
code/modules/projectiles/guns/projectile/sniper.dm
code/modules/reagents/reagent_containers/food/snacks.dm
code/modules/research/rdmachines.dm

- Ammo fixes:
- Replaced regular magazines with high-cap ones that fit clarissa/makarov:
- In clarissa uplink kit.
- Ordered from uplink separately.
- In sidearms crate.
- AMR accepts ammo once again.
- Magnum HV magazine now contains magnum ammo instead of pistol one.
- Removed synaptizine from sin-pockets so they do not cause NSA breach.
- Fixed protolathe not accepting beakers.

Misc fixes

---

code/game/objects/structures/cyberplants.dm

Cyberplants give positive sanity value to the area that they are located in, much needed for the ship's public areas, and gives a mechanical depth to decor. For reference, it takes 5 cyberplants to reach the same sanity value as a single oddity, so this will mostly benefit large public areas.

Cyberplants give positive sanity value to area.

---

code/game/objects/items/weapons/storage/wallets.dm

Wallets may now store pills.
Wallets may no longer store medical stack items.

Wallets can't store trauma kits, and other medicalware.

---

code/game/objects/effects/decals/Cleanable/tracks.dm

Fixes #4050. The bug is pretty self explanatory, someone made it so decals would rotate randomly by default but forgot to set it so footprints didn't.

Fixes random direction footprints

---

code/modules/mob/living/carbon/human/human_attackhand.dm
code/modules/mob/living/living_defense.dm

Fixes damage from animals not showing up on autopsy data
To get the damage value, damage_through_armor now returns the damage done, rather than TRUE/FALSE
closes #3859

Adds autopsy to attacks by simple animals

---

code/modules/projectiles/ammunition.dm

Adds some sanity to magazine loading, where it would try to load a magazine that was full.
An aesthetic change, the do_after for loading a magazine is now done for each round, the time taken is donor reload_delay/receiver max ammo
Player feedback has been added for the following: should they have loaded the magazine, which tells you how much ammo is now in the magazine, and how much is left in the donor ammo container, and for if you failed to load anything into the receiving ammo container.
closes #4164

Ammo loading QoL

---

code/game/antagonist/_antagonist_setup.dm
code/game/antagonist/antagonist_create.dm
code/game/objects/items/weapons/implant/implants/excelsior.dm

Removed `can_become_antag` check for excelsior implant. All necessary checks are already performed in implant's `can_install`. This likely fixes #4301. Note that implants still do not work on mindless (debug-spawned) humans.

Excelsior implant fix

---

code/datums/autolathe/biomatter.dm
code/game/objects/items/weapons/autolathe_disks.dm
code/game/objects/items/weapons/clown_items.dm

The nt soap description no longer references NanoTrasen and now references NeoTheology. I also added the nt soap to the biomatter autolathe for a total of 18 biomatter.

Fixes soap description and adds it to the biomatter printer

---

code/game/machinery/computer/computer.dm
code/game/machinery/doors/door.dm
code/modules/modular_computers/computers/subtypes/dev_console.dm

It was too much, honestly, more like smoke grenade coming from the tiny circuit in door. I pretty much straight up halved amount of smoke coming from it. In my opinion, it should always give away one tile smoke, but i figured out this way PR won't be accepted. Can be changed easily tho.

Lowers amount of smoke that coming from the shoot up consoles and doors

---

code/game/objects/structures/crates_lockers/closets/secure/security.dm

The inspector locker had magazines for the Lamia in it by mistake, it now has speed loaders for the Consol (inspector's revolver) in it instead.

Inspector locker ammo fix

---

code/modules/projectiles/projectile.dm

Bullets that deal less than or equal to 10 damage will no longer make the big blood splatter effect that comes out when you get shot by a bullet. This really only means that if you get hit by a rubber bullet you will no longer shoot out blood. This is also to help people tell if someone is using rubber bullets or not in an intuitive way.

Stops low damage bullets from doing blood splats

---

code/modules/projectiles/projectile.dm

Stops the blood splatter effect from being shot happening to Silicons, Roombas, Bots, Hivebots, etc.

Silicons and Roombas no longer bleed

---

code/game/objects/items/bodybag.dm
code/game/objects/items/contraband.dm
code/game/objects/items/weapons/storage/backpack.dm
code/game/objects/items/weapons/storage/bags.dm
code/game/objects/items/weapons/storage/belt.dm
code/game/objects/items/weapons/storage/boxes.dm
code/game/objects/items/weapons/storage/deferred.dm
code/game/objects/items/weapons/storage/fancy.dm
code/game/objects/items/weapons/storage/firstaid.dm
code/game/objects/items/weapons/storage/misc.dm
code/game/objects/items/weapons/storage/secure.dm
code/game/objects/items/weapons/storage/storage.dm
code/game/objects/items/weapons/storage/toolbox.dm
code/game/objects/items/weapons/storage/uplink_kits.dm
code/game/objects/items/weapons/storage/wallets.dm
code/modules/admin/bluespacetech.dm
code/modules/clothing/chameleon.dm
code/modules/detectivework/tools/crimekit.dm
code/modules/detectivework/tools/storage.dm
code/modules/hydroponics/seed_machines.dm
code/modules/integrated/integrated_electronics/core/tools.dm
code/modules/modular_computers/computers/subtypes/preset_pda.dm
code/modules/projectiles/ammunition.dm
code/modules/reagents/reagent_containers/blood_pack.dm
code/modules/research/xenoarchaeology/chemistry.dm

Storage containers now use `populate_contents()` instead of having to override `New()` or `Initialize()` - same as lockers and crates.
The only gameplay change in this PR is that I made tools in "suspicious toolbox" spawn with better power cell and some spare power cells too. The default cells there were seriously insufficient.

Minor storage containers refactor

---

code/datums/autolathe/circuits.dm
code/game/objects/items/weapons/autolathe_disks.dm
code/game/objects/structures/crates_lockers/closets/secure/chaplain.dm
code/modules/research/nodes/robotics.dm

Rnd Is now able to make Clamps in basic Mech tech.
NT now has a disk that holds the blueprints to make more NT related circuits
Mech clamps missing SEEMS like a over sight as theirs a already done code for it to print...
NT circuits are none-replaceable nor able to be found as far as I know of. This makes getting more bio reactors, sorters, and the like harder to replace if not impossible.
This also allows NT to make more then one bio-reactor for more power generation

Adds Mech Clamps to Rnd, As well as a new NT disk that holds their circuit to Chaplin locker

---

code/__DEFINES/reagents.dm
code/_onclick/hud/fullscreen.dm
code/_onclick/hud/hud.dm
code/datums/autolathe/autolathe_datums.dm

Fixes stats flickering when stims are used. Because stim effect on stat dissipated before it could be renewed by a Life tick, stats would flicker between ticks.
Fixes glasses/mask screen overlays displaying over HUD, fucking finally. Closes #1956.

Various fixes

---

code/modules/sanity/sanity_mob.dm

Clamps sanity damage from injuries so you don't go insane after wandering around maintenance for a couple hours and then stubbing your toe.

Clamps Sanity Damage From Pain

---

code/game/objects/structures/crates_lockers/closets/maint_loot.dm
code/modules/mob/living/carbon/superior_animal/roach/ai.dm

Reere suggested that it might help with chat lag. Simply comments out "%roachname% charges at %yourname%" messages which is being spammed when multiple stacks of roaches see you all at once. Also removes chance to spawn two more stack in some of the maintenance lockers, it's now just guaranteed one stack inside to reduce spam as well.

Temporary Disables Roaches Spam

---

code/modules/mob/living/carbon/resist.dm

For those who unaware, you literally couldn't click ANYTHING for 120 ticks given that you was buckled and resisted out of buckle via "resist" verb. This is fix.

Buckling Click Cooldown Fix

---

code/controllers/subsystems/research.dm
code/datums/autolathe/autolathe_datums.dm
code/game/machinery/autolathe/autolathe.dm
code/game/machinery/autolathe/mechfab.dm
code/game/machinery/bioprinter_nt.dm
code/game/machinery/excelsior/autolathe.dm
code/modules/research/designs/cell.dm
code/modules/research/designs/circuits.dm
code/modules/research/rdconsole.dm
code/modules/research/rdmachines.dm
code/modules/research/research.dm
nano/templates/rdconsole.tmpl

* Fixes protolathe and imprinter deconstruction dropping autolathe circuit boards.
* Fixes protolathe being unable to use its chemicals.
* Fixes certain roundstart designs not unlocking properly.
* Unfucks some R&D design names.
* R&D console now displays adjusted material costs when protolathe/imprinter are upgraded.

R&D fixes and improvements

---

code/datums/autolathe/security.dm
code/game/machinery/vending.dm
code/game/objects/items/weapons/autolathe_disks.dm
code/game/objects/items/weapons/handcuffs.dm
code/modules/mob/living/carbon/resist.dm
maps/CEVEris/_CEV_Eris.dmm

<details>
Currently people wearing RIGs are very hard to take down non-lethally because:
1. They cannot be cuffed with normal handcuffs(an operative has to find cable coils and make cable cuffs with them)
2. RIGs reduce breakout time by half
3. Cable cuffs can be broken out of instantly if the RIG wearer has 30+ robustness stat(they have a 30 second breakout time and each point in robustness reduces breakouts by one second)
4. RIGs can only be removed by forcing someone onto a table(surgery or not) and forcing them to lay down and then welding it off
This is an issue because if someone wearing a rig needs to be arrested, there is a very possible chance that you just cant arrest them and have to kill them on the spot(even if you just wanted to search them to prove …

Adds zip ties

---

code/game/jobs/job/church.dm
code/modules/core_implant/cruciform/rituals/crusader.dm
code/modules/core_implant/cruciform/rituals/inquisitor.dm
code/modules/core_implant/cruciform/rituals/priest.dm

Gives Custodian additional stats after a discussion with ACCount and Reere, Crusader Call to Arms litany now grants a vigilance bonus, Priests may now short boost Vigilance while other non-combat short boosts were buffed.
Removed an extra period in Inquisitor litany description.

Implements missing Vigilance litany

---

code/modules/reagents/machinery/grinder.dm

Grinder procs were called in a different order from the one they were declared in so I passed an argument to a wrong one.

Grinder hotfix

---

code/controllers/subsystems/migration.dm

When a migration event is called, the game rerolls if it is selected within a crew area, thus making it more likely to move through to a maintenance area instead. On Jester this reroll chance is significantly reduced, and since this is performed on each candidate (being the burrow) down a list of candidates, it's almost assured to to begin an assault upon any crew area.

Jester is more aggressive with burrows

---

code/modules/projectiles/gun.dm

<details>
Someone said in #feedback on discord that the remove silencer verb was causing lag when you pick it up or unholster it or whatever since it had it own tab. It really doesn't need its own tab lag or not so I moved it to the object tab. Anyways I tested it and saw no lag now that its in its own tab(no idea if there was lag beforehand or not since I forgot to test that but like I said it doesn't need its own tab anyway)
</details>
<details>
I'm really surprised that you can set the category of procs and add them to the verbs but I guess thats just byond doing byond things.
</details>

Moves "remove silencer" to the Object tab

---

code/controllers/subsystems/research.dm
code/game/machinery/autolathe/autolathe.dm
code/game/machinery/machinery.dm
code/game/objects/items/devices/radio/headset.dm
code/game/objects/items/devices/radio/radio.dm
code/game/objects/items/weapons/storage/boxes.dm
code/game/objects/structures/tank_dispenser.dm
code/modules/clothing/spacesuits/rig/modules/utility.dm
code/modules/clothing/spacesuits/rig/rig.dm
code/modules/clothing/spacesuits/rig/rig_wiring.dm
code/modules/mob/living/carbon/human/species/species.dm
code/modules/modular_computers/file_system/program.dm
code/modules/reagents/reagent_containers.dm
code/modules/reagents/reagent_containers/blood_pack.dm
code/modules/reagents/reagent_containers/food/drinks/bottle.dm
code/modules/reagents/reagent_containers/food/snacks.dm
code/modules/reagents/reagent_containers/glass.dm
code/modules/reagents/reagent_containers/glass/bottle.dm
code/modules/reagents/reagent_containers/hypospray.dm
code/modules/reagents/reagent_containers/spray.dm
code/modules/reagents/reagents/food-Drinks.dm
code/modules/research/designs/rigmodules.dm
code/modules/research/nodes/biotech.dm
code/modules/research/rdconsole.dm
code/modules/research/research.dm
code/modules/surgery/autodoc.dm

* Screwed up RIGs are now easier to repair: cutting and mending all wires should do the trick, like it does for most things.
* Hypospray now spawns with 30u of tricordrazine. This was removed because it interfered with injectors - after a bunch of chem refactors, it no longer does.
* Backpack oxygen boxes now spawn with an injector. Those things are rarely used, but I think it's a thing that is better to have just in case. Storage space of a box increased by 1 (one tiny item size), so there is no downside to this change.
* Oxygen tank storage now dispenses the tanks that were put into it manually first, making it easier to sabotage.
Fixes #3871.
The rest of the changes are under-the-hood code improvements and fixes for bugs I haven't seen reported.

Fixes and improvements

---

code/modules/reagents/reagent_containers/food/drinks/bottle.dm

Vodka is back.
Missing icon was caused by `update_icon` called from reagent addition in `/atom/proc/Initialize` before icon states were initialized.

Booze icon fix

---

code/game/objects/items/weapons/circuitboards/machinery/power.dm
code/modules/research/designs/circuits.dm
code/modules/research/nodes/power.dm

A non-design was supposed to be unlocked by "Energy Distribution" node. No wonder the research system didn't like it.

Fixes R&D DB breaking

---

code/modules/projectiles/guns/matter/launcher/nt_sprayer.dm

NT sprayer now uses a proper projectile, not 1,5 meter long spear. It also have safety like all other guns, because later it will have a combat use.

Sprayer projectile now have a different icon.

---

code/modules/mob/living/carbon/superior_animal/roach/types/nanites.dm

Having a breath_poison_type without a required breath_required_type is incompatible, and I assume vice-versa.

Fixes breath runtime

---

code/modules/tips_and_tricks/gameplay.dm

The tip says "People in RIG/Hardsuits need to be cuffed using zipties or cable cuffs. Normal cuffs are not large enough to cover their gauntlets."

Adds tip explaining how to cuff people wearing RIGs

---

code/game/objects/items/weapons/grenades/chem_grenade.dm

Changed `New` in chem grenades to `Initialize`.
Fixed `Runtime in chem_grenade.dm,275: Cannot execute null.add reagent()` that was caused by beaker reagents being used before initialization.

Chem grenade fix

---

code/datums/contract.dm
code/datums/uplink/devices and tools.dm
code/game/antagonist/antagonist_print.dm
code/game/objects/items/devices/mental_imprinter.dm
code/game/objects/items/devices/mind_fryer.dm
code/game/objects/items/devices/spy_sensor.dm
code/game/objects/items/weapons/storage/bsdm.dm
code/game/objects/items/weapons/storage/uplink_kits.dm
code/modules/sanity/sanity_mob.dm
nano/templates/bsdm.tmpl

This PR contains: a whole lot of polish and QoL.
* Completed contracts now display in round-end report. Because the best thing about being an antag isn't killing and stealing, it's showing everyone online that you did.
* A whole lot of new feedback messages to let you know that your spying sensors are spying, your mind fryer is frying, your contracts are being completed and your TCs have arrived.
* New traitor items now have proper descriptions, materials and research levels.
* The uplink descriptions now clue you in on how to use the contract items.
* Some contracts pick their targets better now. You will no longer get a contract to assassinate some admeme guy or spy implant a Preacher.
* Contracts now do in depth search on BSDM contents. Sending a PDA that has a disk with the contract …

Traitor update

---

code/__DEFINES/_hydro_setup.dm
code/modules/hydroponics/seed_datums.dm
code/modules/hydroponics/spreading/spreading_growth.dm

<details>
Fixes hivemind wires being unable to take over seeded tiles - also adds invasiveness as an (unobtainable) trait for plant for future use.
</details>

Fixes hivemind wires being unable to take over seeded tiles

---

code/modules/mob/living/carbon/human/human.dm

How the fuck am I supposed to prepare for the techno gun update t-minus 6 months without fixing broken ass shrapnel. 
This PR adds a movement check to make sure you only take shrapnel damage when running and not walking. No more gay ass shrapnel deaths. Take as much as you want, but don't expect to survive if someones gunning for your ass.

makes shrapnel only damage you if you are not on walk intent

---

code/modules/mob/mob_grab.dm

fixes having over 50 ROB make you instantly grab someone and making the other person unable to do anything but submit.
<details>
<summary>Grab time reduction due to robustness has been given an exponential curve of 0.8</summary>
This means at 100 robustness you have a reduction of 39 from 50 which means your upgrade time is 11. At 50 robustness you have a reduction of 22 which means your upgrade time is 28. This will probably fix the rampant issue of grab-fu.
</details>

Grabs rework

---

code/world.dm

This PR implements small code that's accessible only by VS Code and is server safe code to enable the debugger on a local pc. If the var dll is not set, it won't enable debug because the environment variable isn't set.
From https://github.com/SpaceManiac/SpacemanDMM/wiki/Setting-up-Debugging to configure your VS Code
To discuss
<details>
</details>

[QoL] Adds debug feature to the codebase

---

code/datums/uplink/devices and tools.dm
code/game/objects/items/weapons/storage/uplink_kits.dm
code/modules/clothing/spacesuits/void/merc.dm

Old uplink softsuit sucked all around. This replacement sucks less.
It has an added benefit of being a rare maint loot - you can possibly obtain it as crew, so just having it isn't quite enough of a ground for IH to shoot to kill.

Replaces uplink softsuit with a merc voidsuit

---

code/modules/mob/animations.dm
code/modules/projectiles/projectile/bullets.dm

Toned down screenshake, which occurs when ANY bullet hits you. While this is not guaranteed win if you hit someone first anymore, it is still significant and very noticeable. I've done pretty extensive testing with adjusting it by hand each time, so it should be good. Made use of "taper" var by Nanako also.
And fixed small typo in animations.dm

shake_camera for bullet/on_hit adjustment

---

code/modules/mob/living/carbon/superior_animal/roach/types/nanites.dm

Rather than appearing invisible (because they have no icon for being dead), nanite roach swarms now qdel and leave a splash of motor oil behind, so the janitor has more to do.
Suggested by Roma#4395 in the discord

Nanite roaches now become motor oil on death

---

code/modules/organs/blood.dm

Adds a check for if you have a heart before checking if it's open for surgery, in blood circulation
Events that would lead to such a runtime:
- Having your heart removed
- Having your torso removed

blood runtime fix

---

code/_onclick/hud/screen_objects/base_screen_objects.dm
code/modules/mob/living/carbon/carbon.dm
code/modules/mob/living/carbon/carbon_defines.dm
code/modules/reagents/metabolism.dm
code/modules/reagents/reagents.dm
code/modules/reagents/reagents/medicine.dm

This is the half finished version of the NSA Rewrite, currently i moved almost all NSA code to metabolism.dm and it now adds NSA values paired with id (reagent ID) and metabolism_class (CHEM_INGEST, CHEM_INJECT, ect) combo. The result is NSA stacking for the same chemical over the 3 different holders. Now the reason why this is a draft is because while i have been able to make it add NSA in this way with A LOT of help from ACCount and others it still doesn't remove NSA from the list correctly (namely it still searches for a normal id to remove instead of the new combo). Any help appreciated and have a good Eris weekend!

NSA Rewrite (COMPLETE) 

---

code/modules/reagents/reagents/food-Drinks.dm

Nuka-Cola now gives you 20% less speed and has an NSA value close to that of hyperzine. It's still pretty good, just not "exploit central" good.
Combined with slowdown calculation changes from #4525, this should solve the issue of people being 2fast2furious for good.

Nuka-Cola nerf

---

code/__DEFINES/MC.dm
code/__DEFINES/subsystems.dm
code/controllers/subsystems/machines.dm
code/controllers/subsystems/processing/processing.dm

Reverts https://github.com/discordia-space/CEV-Eris/pull/2271
This has done wonders with removing most serverside lag on my local.
https://github.com/discordia-space/CEV-Eris/issues/4537 is still relevant. There absolutely should be fewer processing machines but at least we are now processing in linear time again. We still can't manage to process all machines in a single tick (and we likely never will) but it's faster and doesn't lag anymore.
This conflicts with https://github.com/discordia-space/CEV-Eris/pull/4535, but is also safer and higher priority.
I was wrong about this being the reason why SSmachines initializes slow, that has to do with atmos machines.
The old implementation was pretty stupid if you know how lists are implemented.

Fixes most 'abnormal' lag caused by processing subsystems.

---

code/__DEFINES/subsystems.dm
code/controllers/subsystems.dm
code/controllers/subsystems/machines.dm

Seems like some mistakes were made in #4538.
I dunno how broken the server would be if that wasn't fixed in time, but my guess is: very.

Hopefully fixes #4538

---

code/game/objects/structures/burrows.dm

time gets used to divide in process and something seems to call this without providing an argument. Calling this proc without setting a duration now causes an instant migration which I assume was the intended behaviour.
This is basically just a runtime fix.
This caused me to think that I broke everything with changing processing subsystems so I hate it with a passion.

Changes the default duration of burrow migration from 0 to 1.

---

code/modules/mob/living/carbon/superior_animal/roach/types/nanites.dm

Adds a limit of 5 (can be modified) nanite swarms a kraftwerk roach can create at any one time
Nanite swarms are added to a list on creation, and removed from it on destruction. Killing the kraftwerk roach gibs all associated swarms.
Fixes #4540

Adds a limit to the max amount of nanite swarms a kraftwerk roach can create

---

code/modules/reagents/reagents/drugs.dm
code/modules/reagents/recipes.dm

Metabolism speed is now 0.133 making it a viable combat drug instead of a permanent speedboost and speed is reduced to 0.4 negating slowdown on medium armours and a slight speedup with none at all.

Hyperzine rebalance

---

code/game/objects/structures/burrows.dm

Should prevent burrows from generating streams of error spam. No idea if it would help with lag.

Burrow runtime spam hotfix

---

maps/CEVEris/_CEV_Eris.dmm

Adds new bulletproof helmets for IH from recent Armor PR. They're on the rack with ballistic vests. Also removed one reduntant vest, now it's eight of both helmets and vests (6 OPs + 1 SGT + 1 LT) as it should be and as it is for other types of armors. Tested and works, mapmerged.

IH Bulletproof Helmets

---

code/modules/mob/living/carbon/human/human_movement.dm

To put into perspective 1 taser shot used to cause a 3 slowdown (as much as a deactivated hardsuit being worn) but does 0.5 now per shot which still slows target enough to catch up to them and more shots will increase this number. I think this is a lot more preferable to a 1 shot game over.

Slowdown from pain is reduced 

---

code/game/objects/structures/grille.dm

Changes grille damage so it scales off of the structure_damage_factor and removes the 90% damage reduction to brute weapons. I'm doing this PR because right now it takes a fire axe 20 hits to break a grille, after this change it will only take it 1 hit. I don't like how grilles have a snowflake health system but thats really not the issue this is trying to fix.

fix fireaxe dealing no damage to grilles

---

code/modules/mob/mob.dm

Previously, embedded objects were not being removed from mobs that weren't human, so you could forcemove an object that somebody else had removed from it.

Fixes embedded objects not being properly removed from mobs that aren't human

---

code/game/objects/items/weapons/stunbaton.dm
code/modules/clothing/gloves/stungloves.dm

Power gloves now act more as a assist in combat rather than a 2 click win due to reduced agony making stun batons a preferable weapon for melee non-lethal takedowns (also removed the insta stun on these as well as reduced agony on the cattle prod)

Melee weapon agony damage adjustment and stun baton fix

---

code/modules/clothing/clothing.dm
nano/templates/clothing_stats.tmpl

I saw this was requested by a player, so decided to code it while I was trying to figure out other projects.
<details>
You can now see the following aspects of a piece of clothing:
- Its armor values, in a range from 0 to 100
- Its slowdown, in a range from -5 to 20 (the current lowest and fastest slowdown values)
- What limbs it covers
- How long it takes to equip, in Seconds, in a range from 0 to 10 Seconds
</details>
<details>
</details>

Adds a clothing UI for the user to see held clothing's stats

---

code/modules/projectiles/guns/projectile/automatic/straylight.dm

This is follow up PR to #4587. Turns out 800RPM (0.8 delay between shots) turned out too OP for SMG. I don't want to turn down damage down or recoil up because i fear that this would render weapon pretty useless and turn it into meme peashooter (also because shrapnel that gravitates toward chest is still a thing), so i turned down speed to 600. It's still very robust with rubbers and quite deadly with lethals if you can handle it well, but any armor pretty much defeats it.

Straylight Nerf

---

code/__DEFINES/tick.dm
code/_global_vars/misc.dm
code/controllers/master.dm
code/modules/admin/verbs/ticklag.dm

ITU now defaults to 5% when MC is initializing, and to 20% once MC init is done. Those values are on the safer side of sane, unlike the "66.7%" or "60.7%" that were observed on live servers before.
This PR only matters if extools lib doesn't work, which, on live servers, it currently doesn't.

Adds a sane fallback in case extools fails to load

---

code/modules/projectiles/guns/projectile/automatic/dallas.dm
code/modules/projectiles/projectile/bullettypes.dm

Currently Dallas deals humongous amount of damage, 45 with usuall ammo and (!) 60 if you manage to aquire HV ammo which is fairly easy to be honest. I think that this is a bit too much for 99-round mag fed fully automatic (400RPM) rifle with 25 armor penetration, even if it's very rare, because once you get it - you're unstoppable. I toned it down to 35 and 41 respectively, also removing three round burst which is largely unused if gun already have full auto.
Also touched up .25 caseless ammo a bit. Weird, but it had sharp flag set to false, which effectively means this bullets shouldn't cause bleeding despite being lethal ammunition. I changed that, but instead removed ricochet possibility from them for main reason of it being used as ammo for primary IH firearm Sol, so hopefully it …

Dallas Nerf

---

code/__HELPERS/sanitize_values.dm

This resulted in two runtimes every time someone's prefs were loaded.

Fixes an annoying runtime error introduced in the v513 text PR

---

code/datums/autolathe/biomatter.dm
code/game/machinery/vending.dm
code/game/objects/items/weapons/autolathe_disks.dm
code/game/objects/random/cloth.dm
code/game/objects/random/packs.dm
code/modules/cargo/packs.dm
code/modules/clothing/accessories/holster.dm

Uniform holsters are no longer IH exclusive now. Not sure who and why removed them from various sources in first place, but now you can get them either from FS vendor, guild, NT bioprinter, maintenance loot. IH still can get them from loadout. While i can agree that uniform having a whole slot for a handgun is maybe a bad thing, but this can be done at least until we get suit attachments or any other alternative to that.
NT now also can print their own belts because they couldn't do it previously. Added NT belts to maintenance loot as well.

Uniform Holsters and NT Belts

---

code/game/objects/structures/crates_lockers/closets/secure/engineering.dm
maps/CEVEris/_CEV_Eris.dmm

Chemical and medical cartridges were replaces with equivalent NewPDA scanners. The rest are just gone.

Removes OldPDA cartridges from map

---

code/game/machinery/autolathe/autolathe.dm
code/game/machinery/autolathe/mechfab.dm
maps/CEVEris/_CEV_Eris.dmm

All map autolathes now spawn with 60 of steel, plastic and glass, and a small beaker. One of R&D's mechfabs is also spawns loaded with 120 of steel, plastic and glass.
Material stacks that are supposed to be used for loading those are removed from map.
Overall, this change reduces the amount of materials on the map a bit, but it also means that you don't have to load the lathes every round - which is a win in my eyes.

Autolathes on the map are now preloaded with materials

---

code/modules/projectiles/gun.dm
code/modules/projectiles/guns/projectile/other/RPG.dm

Changes the RPG to be fireable only when wielded, also adds the possibilty to give this feature to other guns.

The RPG wielding fix

---

cev_eris.dme
code/game/objects/explosion.dm
code/game/objects/items/weapons/grenades/explosive.dm
code/game/objects/items/weapons/grenades/frag.dm
code/game/objects/items/weapons/storage/boxes.dm
code/game/objects/items/weapons/storage/deferred.dm
code/modules/mob/living/carbon/human/human.dm
maps/testmap/test_map.dmm

This makes explosive damage much more deadly. I also stopped frag grenades from exploding, stopped HE grenades from spawning invisible fragments and made them a child of /grenade themselves.

Explosive damage changes

---

code/game/objects/random/voidsuit.dm

Techno voidsuit is now as rare as the IH voidsuit in trash since it has very similar stats

TM Voidsuit spawn rate adjustment

---

code/modules/mob/living/carbon/human/human_defense.dm
code/modules/mob/living/living_defense.dm

Hit impact direction could easily be "0" if attacker and the victim are on the same turf. This would no longer result in runtime spam.

Fixes a runtime in human attack code

---

code/controllers/subsystems/jobs.dm
code/game/jobs/job/science.dm
code/modules/modular_computers/computers/modular_computer/core.dm
code/modules/modular_computers/computers/subtypes/preset_laptop.dm
code/modules/modular_computers/computers/subtypes/preset_tablet.dm

Fixes another regression that was introduced in #4680. Also adds signaller app as a default for Scientist and MEO jobs.

Fixes loadout laptops and tablets not spawning with job software

---

code/modules/projectiles/guns/energy/plasma.dm
code/modules/projectiles/projectile/plasma.dm

Fixes the plasma projectiles to actually check for energy armour, and rebalances the 3 plasma guns we have to be viable across all firing modes.
<details>
- Changed all 3 plasma projectiles to deal 33 damage.
- Light projectile has no Armor Piercing.
- Medium projectile has 25 Armor Piercing.
- Heavy Projectile has 50 Armor Piercing.
- The design thought behind these is that the heavier the projectile, the bigger the fire delay and charge cost. Plasma weapon user is meant to adapt to the target - light projectile has the highest DPS on unarmored targets, medium is best for lightly armored (30-40% energy resist) and heavy is great against epic levels of armor.
- NT Dominion is a specialist rifle with all 3 projectile types.
- NT Cassad is an efficient rifle with …

Plasma guns fix and rebalance

---

code/modules/clothing/shoes/miscellaneous.dm
code/modules/reagents/reagent_containers/spray.dm

On Eris, Clown (or, as no one ever calls him, Actor) is crippled more than anywhere else because of how common, expected and sometimes required firearms are. Ship's favorite punching bag deserves some buffs to compensate for it!
* Clown's water flower is now a legitimate spray bottle, just with a different appearance. It's not like spray bottles are super rare anyway.
* Clown shoes slowdown has been cut, from 1.0 to 0.4. Slowdowns feel bad, and we cut a lot of them already - it makes little sense to keep an entire 1.0 of it on an item that's required for a job.
The ONLY reason clown shoes slowdown wasn't removed entirely is that being able to terrorize the crew with constant squeaking is a power that should come at a price.
Unrelated: the amount of plastic in a spray bottle was bumped to …

Small Clown buffs

---

code/modules/mob/living/carbon/human/human.dm

While working on the explosive damage code I used BPBP_GROIN instead of BP_GROIN. This sometimes caused some of the damage to not be applied. This fixes it.
Edit: Also added some spaces.

Fixed explosive damage not being applied properly

---

code/modules/clothing/spacesuits/rig/rig.dm
code/modules/mob/living/carbon/human/update_icons.dm

There was a snowflake override specifically for the rig, that would return an image.
Problem is, the function it was in was expecting to return an icon file directory, so you ended up with a dead image whose icon file was harvested, and then no icon state, so they would default to the blank icon state.

Should fix rig back slots not showing properly

---

code/game/objects/random/voidsuit.dm
code/modules/clothing/spacesuits/void/station.dm

Does a bit more of a balance pass on voidsuits.
Buffs the mining voidsuits bullet proc to be 35 rather than 20, considering there's a bunch of away mission mobs that try to shoot your face off. Same with minorly better energy due to one star drones melting miners if they don't have kelotane on them.
Gives the techno armor 40 bomb resist but less overall resist.
Medical voidsuit has more energy protection now.
</details>
nothing changed. Spooky.
</details>

Voidsuit buffs/nerfs

---

code/game/objects/items/weapons/autolathe_disks.dm

Currently it's on the public NT disk, which... never actually spawns anywhere, and it's totally absent from the internal NT one.
<details>
Just a simple move of the design so NT can make more cleansing carbines. They can sell them, use them, whatever, now that they're actually capable of producing them.
I removed it from the public disk since it's an NT-specific piece of equipment, and uses biomatter as ammo.
</details>
<details>
</details>

Moves the Cleansing Carbine design to the regular NT disk

---

code/game/jobs/job/guild.dm

I find that the guild ceases to function every time the merchant is merced or goes to sleep, now the guild technicians will also be able to keep the eris guild alive

Department account perms for guild techs

---

code/datums/movement/mob.dm

This fixes being able to grab two things, then teleporting 3 tiles in a given direction when moving
<details>
The reason this was happening: The previous code would itterate over all grabs the player had in their inventory (good so far), then for each grab object, it would collect all mobs involved in grabs, including the assailant (not good).
Then, it would move them all in the given direction, then the second grab would move them again.
</details>

Fixes being able to teleport when grabbing two things at once

---

code/game/objects/items/weapons/stunbaton.dm

Ghetto stunprod no longer spawns a cell from the aether
Ghetto stunprod don't disappear now when turned on

Stunprod fixes

---

code/datums/topic/admin.dm
code/modules/admin/verbs/debug.dm
code/modules/mob/living/carbon/brain/MMI.dm
code/modules/mob/transform_procs.dm

- Issue:
Robots and AIs, when they attempted to join, found themselves becoming a brain ghost, and not a robot or AI
- Cause:
Robots and AIs used Robotize and AIize respectively, which would qdel your organs then spawn you in as a robot.
After #4736 , if a brain is qdel'd, the person is ghosted, so the client never made it to the AI to be placed into it.
- Fix:
Remove the redundant qdeling of organs, as that is handled by humans own qdel(), which is called at the end of the transformation process anyway.
After going through them all, I also fixed MMIs being partial pathed, and the corgize and animalize having arbitrary sanity

Fixes Robots, AIs, and other transform procs from bricking themselves

---

code/modules/organs/external/_external.dm
code/modules/organs/external/subtypes/robotic.dm

Robot limbs now need 20 damage to start malfunctioning (up from 10), and the malfunction chances are lower.

Increases robot limb malfunction threshold

---

code/modules/client/preference_setup/loadout/lists/utility.dm

As of right now you can remove your legs by amputation at start but can't start in a wheelchair so I think it's nice to have it able to get it from the get go instead of crawling until you make/find one and makes sense lore-wise since poor vagabonds might not be able to afford prosthetics while still getting badly wounded on the regular.

adds wheelchair to utility loadout

---

code/modules/reagents/metabolism.dm

Well, HUD elements uses strings, not defines. Compiler cannot catch if we don't turn all strings into defines later.
Thus I have fixed the NSA UI not updating at all because wrong string was used.

Fixes the broken NSA indicator UI

---

code/modules/reagents/recipes.dm

Handyprints had itself in its recipe, I replaced it with sterilizine.
Voice mimics and nanopurgers both used synaptizine, I replaced the synaptizine in nanopurgers with vomitol.
First PR. tell me if what I did is just bs.

Fixes broken Nanite recipes

---

code/datums/autolathe/devices.dm
code/game/objects/items/devices/radio/encryptionkey.dm
code/game/objects/items/weapons/autolathe_disks.dm
code/game/objects/items/weapons/storage/boxes.dm
code/game/objects/structures/crates_lockers/closets/secure/chaplain.dm

Benefits NT in the way that they have a way to have closer contact with their followers now, as they now can actually produce encryption keys and people can ask for them in order to communicate with them later. I'd even say this should increase quantity of mass lithanies, given anyone would want to play non-church NT.
Decapitalized Neotheology in the name of the encryption key item itself, but it appears fully capitalized in the autolathe design name. Looks nicer both ways. Also added silver cost of 1 to any encryption keys because just steel feels too cheap and bland. Silver is still most common from "rare" category materials as it could be easily extracted from powercells and else.

Adding NT radio encryption key to their disk

---

code/modules/projectiles/guns/projectile/shotgun/pump.dm

Due to the popular demand, this removes two-hand requirement for pumping shotguns. Most remarkable example is Kammerer, which can fit five shells in total. You get shotgun, get shells in other hand, instert four, put away shells, twohand it, pump it, untwohand it, put remaining shell in. Sounds cumbersome? Because it is. Tested and works.

Makes so shotguns doesn't require two-handed grip to pump them

---

code/game/machinery/cryopod.dm
code/modules/mob/living/living.dm
code/modules/mob/mob.dm

Before this PR, a robot in a robotic cryo will cause a runtime because the despawn_occupant() will call the parent which lands in the proc with human-only code causing a runtime unless the line `occupant_organs = H.organs | H.internal_organs` is behind the type check
The PR fixes the spammy runtime, not sure if it also breaks the MC beforehand.
Last thing, should this fix to be changed to a refactor of cryo code so we have /obj/machinery/cryopod/organic and original /obj/machinery/cryopod/robot, the /obj/machinery/cryopod will just simply call the generic removal code ?

[FIX] Cryopod : Fixed the cause of runtime that breaks the MC ?

---

code/game/machinery/autolathe/autolathe.dm
code/game/objects/items/weapons/autolathe_disks.dm
code/modules/modular_computers/file_system/binary/design.dm
nano/templates/autolathe.tmpl
nano/templates/autolathe_designs.tmpl

Replaces disk licenses with license points. A point cost can be asssigned to every design.
<details>
A point cost is in an associative list with the design path. For now mostly guns have a specific point cost. The default is 12 license points with 3 points per gun. This allows players for different combinations of costs (3 guns 3 mags, 2 guns 6 mags, 4 guns 0 mags ...). A point cost was also added to better versions of batteries in robustcells disk. If no cost is defined it defaults to 1. 
</details>
<details>
UI look (License point cost : x changed to License point cost: x for consistency)
Warning if there aren't enough points left for the design
Other designes still work
Interaction with the hacked disk cloner, the error designs point …

New disk license point system

---

code/modules/surgery/surgery.dm

Changelings no longer need a chair to perform self-surgery, they can do it just by standing still. They also have a significant increase to success chances and don't need to diagnose a body part they are operating on.

Makes changelings real good at self-surgery

---

code/game/objects/random/guns.dm
code/game/objects/random/lathe_disks.dm
code/game/objects/random/packs.dm
code/game/objects/random/techparts.dm
code/game/objects/structures/crates_lockers/closets/maint_loot.dm
code/game/objects/structures/salvageable.dm

Makes gun disks more rare (mainly by removing them from /obj/random/techpart), rebalances other loot to make up for it, expect more finsished guns in maints and more ammo disks for guns you do find. All feedback is wellcome.
<details>
Both tests done on a set of 10 random tech lockers.
Current Situation:
FS
.40 miller
Rifle ammo x3
Gladstone SG
PDW martin
TM
Circuts x2
Components x2
Conveyors
Adv tools
Guild
Misc pack x2
Moebius
Artemis dartgun x4 (???)
NT
Lightfall LG
Regulator SG
SRB
Novakovic boltgun
Total: 22 (2.2 disks per locker)
After this update:
FS
Lethal ammo disk
Non lethal ammo x2
.35 and .40 ammo
.35 colt
TM
Components x2
Conveyors
Adv tools x2
Guild
Devices and instruments
Misc pack x2
Moebius
Computer parts
Artemis dartgun
IH
Misc pack
Total 16 …

Gun disk rebalance (Feedback wellcome)

---

code/modules/admin/bluespacetech.dm
code/modules/mob/observer/ghost/ghost.dm

It fixes the lack of UI when turning into ghost or moving out of corpse or teleporting out as BST.
But there's duplicate code in code\modules\mob\new_player\new_player.dm:110 and code\modules\mob\observer\ghost\ghost.dm:140. I wish the code gets reworked in new_player.dm to be replaced by a single function call with proper parameter.

Fixes the lack of UI for BST teleport or ghosts leaving corpses.

---

code/game/objects/items/weapons/autolathe_disks.dm

Before: you could get 8 crossbows out of a single disk.
Now: you can get 4 crossbows out of a single disk. This is consistent with all other gun disks.

Brings the license costs of NT crossbows in line with other gun disks

---

code/_onclick/cyborg.dm
code/datums/mind.dm
code/datums/uplink/devices and tools.dm
code/modules/mob/living/silicon/robot/drone/blitzshell.dm
code/modules/mob/living/silicon/robot/robot.dm

Removes the Blitzshell laser weapon, now it must be purchased seperately
Fixes the Blitzshell being able to bolt and electrify doors

Blitzshell fixes

---

code/game/objects/items/weapons/tools/hammer.dm

Changes the code for the Homewrecker item so that it has an icon when the object is on the ground. Before this, the Homewrecker had no icon (though it showed up on a player's sprite if held), even though it had icons in the code.
Also changes the spelling on the description for the Homewrecker.

Homewrecker Icon Patch + Spelling

---

code/controllers/subsystems/jobs.dm
code/game/objects/structures/morgue.dm
code/modules/biomatter_manipulation/bioreactor/platform.dm

Various fixes.
Adds an indicator of successful respawn timer reduction by putting someone into the morgue, increases it to 10 minutes.  
No more spawning as an NT without a cruciform due to having enabled random jobs. 
Adds an extra 10 minute respawn reduction for having your body dissolved in the bioreactor platform.

Adds a morgue message indicating successful respawn timer reduction, fixes spawning as NT without cruciform

---

code/modules/reagents/reagents/medicine.dm
code/modules/reagents/recipes.dm

This PR changes the vomitol recipe, so that it doesn't conflict with the inaprovaline recipe, even though it worked before (but required a specific order to make the vomitol). The new recipe is based off of looking at the chemical formula for adamsite (https://www.cdc.gov/niosh/ershdb/emergencyresponsecard_29750017.html).
This PR also makes it so vomitol decays into its base components when heated above 683.15 K, since adamsite in real-life apparently does that.

Changes Vomitol Recipe, Makes Vomitol Decayable

---

code/modules/mob/living/bot/bot.dm

Fix Issue #4631 about the repair of bots. 
I did some tests and the issue actually applied to all kinds of bots (floorbot, medibot, hydroponic bot...) and for any percentage of brute damage.
There is no way to fix burn damages on bots, I don't know if it is intended.
:cl: Hyperio
fix: Fixed not being able to repair bots
/:cl:

Fix Brute damage repair for /living/bot

---

code/__DEFINES/craft.dm
code/datums/craft/menu.dm
code/datums/craft/recipe.dm
code/datums/craft/recipes/airlocks.dm
code/datums/craft/recipes/floor.dm
code/datums/craft/recipes/furniture.dm
code/datums/craft/recipes/misc.dm

Related to 4. of issue #2828 
This PR modifies the crafting menu by grouping the variation of the same item under a single button. For instance instead of having 9 buttons in the Furniture category for the 9 available colors of comfy chair there is now a single "Comfy chairs" button that open a prompt when you click on it in order to chose the desired color.
Quality of Life improvement by making the crafting menu more convenient to use by making it easier to reach the item you desire without scrolling through a lots of variations of items you don't want.
:cl: Hyperio
tweak: Crafting menu now regroups all variations of an item under a single option
/:cl:

More compact crafting menu by grouping variations of the same item

---

code/modules/mob/living/silicon/robot/drone/blitzshell.dm
code/modules/mob/living/silicon/robot/robot.dm

Fixes robot-mounted weapons not using the robots cell.
:cl:
fix: Fixes robot equipment that would use the internal cell, not doing so.
fix: Fixes the blitzshell being on accessible camera networks.
/:cl:

Fixes the Blitzshell being on accessible camera networks

---

code/game/objects/items/devices/t_scanner.dm
code/game/objects/items/weapons/storage/storage.dm
code/modules/stashes/stash_items.dm

Add a way for storage containers to hide from t-ray scanners, it still needs some stress testing to see if it actuely effects performance
On request of reere, so you cant find stashes nearly as easily
:cl:
add: A exmaple stash sack that hides from t-ray scanners
fix: storage items can now hide from t-ray scanners
code: storage now has a is_tray_hidden, if set to true it wont be found my the scanner
/:cl:

Add t-ray hider for storage and add example stash

---

code/_onclick/cyborg.dm

Fix high priority issue #3848 about mining borgs not being able to pick up stuff like ores with their mining satchel or metal sheets with their sheet snatcher 9000.
To fix the issue I adjusted the OnClick function of cyborgs to have it closer to humans' one. Tell me if you think it could have any undesired consequences.
It is way more fun/efficient to play a mining borg than can pick up the ores it mines rather than one that cannot.
:cl: Hyperio
fix: Fixed cyborgs not being able to pick up items (ores, sheets, ...)
/:cl:

Fix cyborgs not being able to pick up stuff (ores, sheets, ...)

---

code/modules/stashes/stash_types/excelsior.dm

Makes the excel teleporter board only a chance of spawning in excel stashes, rather than a guarantee

Excel randomstash nerf

---

code/modules/mob/say.dm

Added lowertext() to this function that handles radio prefixes.
The radio prefix will work whatever if they are in capitals or not.
The drawback is it limits to 26 letters and 10 single digits.
:cl:
tweak: Radio prefix will now work with any capitalization 
/:cl:

Changed how the radio prefix is read irregardless of capitlization used 

---

code/datums/craft/step.dm
code/modules/materials/material_sheets.dm

Fix issue #4851 about the crafting system not checking which material is required to finish a multi-step recipe.
For instance to craft a modular console, you need 10 sheets of steel and 4 sheets of glass. When you click craft with, let's say, 10 sheets of steel in hand, it consumes the sheets and spawns a "crafting modular console" object on the ground. You're then supposed to click on this object with the 4 missing glass sheets in hand to finish the construction. However if you want to can use other materials like 4 sheets of plastic because material is not checked.
You cannot finish recipes with any material you want.
:cl: Hyperio
fix: Fixed crafting system not checking the required material
/:cl:

Fix crafting system not checking the required material

---

code/game/machinery/vending.dm

Add 8 holowarrants to security vendors (like the one in IH barrack). 
Holowarrants have been added with PR #4840 
Being able to use this new item is nice for IH operatives.
:cl:
add: Added holowarrants to security vendors
/:cl:

Add holowarrants to security vendors

---

code/game/objects/structures/bedsheet_bin.dm

Fix issue #4026 about a bedsheet duplication when storing it in a bedsheet bin. Basically the _toggle_fold_ of the bedsheet was triggered so one sheet was added to the bin and another appeared on top of it folded/unfolded.
Also fixed a similar problem with containers. Trying to put a folded sheet in your backpack also triggered the _toggle_fold_ and it was impossible to add it to the storage.
Duplication is bad, being able to store folded sheets in containers is nice.
:cl:
fix: Fixed bedsheet duplication and storage issues
/:cl:

Fix bedsheet duplication and storage issue

---

code/__HELPERS/files.dm

Reverts discordia-space/CEV-Eris#4905
My previous merge will break runtime logging.

Revert "Prevents filesystem access"

---

maps/CEVEris/_CEV_Eris.dmm

This PR patches an issue (#4618) with the merc shuttle being unable to dock directly with the Eris because it would intersect a room if it did. @hyperioo from the Discord pointed out the solution to this issue.
Updated 2020-05-21 06:52 P.M. EST: @hyperioo 's catch: Closes #4618 
Issue-patch.
:cl:
fix: makes the deck 5 port maint docking port longer so the merc shuttle can dock to it properly
/:cl:

Makes Merc Shuttle Dockable to Eris

---

code/datums/objective/assassinate_marshal.dm

Fix high-priority issue #3327
Add an additional test in the function that select the marshal's assassination target to ensure that the chosen antag is not a marshal.
**I was not able to test this PR** since I did not manage to spawn a marshal with dummy human mobs. It compiles though. If you know how to quickly test it.
Marshal sould not target another marshal, they're both IH and crew sided.
:cl: Hyperio
fix: Fixed marshal having another marshal as assassination target
/:cl:

Marshal cannot target another marshal

---

code/modules/economy/cash.dm

Byond took the MC out back and shot it in the head when cash bundle decided to get stuck on fraction points
:cl: drexample
fix: fixes using cash bundle as oddity crashing the server
/:cl:

Fixes infinite loop in cash bundle inspiration

---

code/controllers/subsystems/migration.dm

Fix a division by 0 runtime in the migration system
> [11:36:34] Runtime in burrows.dm,204: Division by zero
>    proc name: summon mobs (/obj/structure/burrow/proc/summon_mobs)
>   src: the cracks (/obj/structure/burrow)
>   src.loc: null
>   call stack:
>   the cracks (/obj/structure/burrow): summon mobs(0.276025)
>   the cracks (/obj/structure/burrow): migrate to(the burrow (/obj/structure/burrow), 800, 0.276025)
>   Migration (/datum/controller/subsystem/migration): do migrate()
>   Migration (/datum/controller/subsystem/migration): fire(0)
>   Migration (/datum/controller/subsystem/migration): ignite(0)
>   Master (/datum/controller/master): RunQueue()
>   Master (/datum/controller/master): Loop()
>   Master (/datum/controller/master): StartProcessing(0)
:cl: …

Fix runtime in summon_mobs

---

cev_eris.dme
code/controllers/configuration.dm
code/modules/admin/admin_ranks.dm
code/modules/admin/verbs/antiraid.dm
code/modules/client/client procs.dm
code/modules/client/client_defines.dm
config/example/config.txt

Gifts from elsewhere.
I tested these a reasonable amount, but I'd suggest you test them too, since the testing would be more authentic if you use them with your real settings and real DB and such.
When enabled, only players who have previously joined and been logged in the DB will be allowed to join. If they have not been logged in the DB, they will be kicked, and not logged in the DB (otherwise they could just rejoin and then they'd pass the test, you know?). Config option to enable it always (probably not a good idea), and R_ADMIN verb for toggling ingame.
When enabled, admins will be warned in two cases:
- A player joins who has never joined before
- A player joins with a very new byond account (0-2 days old)
Available as a config option to enable it forever, or an R_ADMIN verb ('New …

Port various antiraid/antigrief measures

---

maps/CEVEris/_CEV_Eris.dmm
maps/CEVEris/shuttles-eris.dm

This PR adds new landmarks in space for the merc shuttle. There is now a landmark near all external airlocks of the ship. Merc shuttle parks in space near those airlocks and then mercs have to do a bit of space walk to reach them.
New landmarks make the location of merc shuttle less predictible. They could also be used for others ships or events.
:cl: Hyperio
add: Added new destinations in space for merc shuttle
/:cl:

[MAP] New destinations for merc shuttle

---

code/game/objects/items/weapons/tools/hammer.dm

Makes the homewrecker fit on your back and belt slot, aswell as do 26 damage.
The homwrecker is kind of not really useable right now I'd argue, you can easily find tools that fit in belts and deal more damage than it. 
:cl:
balance: Homewrecker now fits on your back and belt. And does 26 damage wielded.
/:cl:

Homewrecker fits on back and belt. Does 26 damage when wielded.

---

code/modules/mob/living/simple_animal/friendly/spiderbot.dm

Fix runtime in spiderbot.dm when trying to assign src.loc to held_item.loc with held_item being null.
> [19:27:19] Runtime in spiderbot.dm,203: Cannot modify null.loc.
:cl: Hyperio
fix: Fixed runtime in spiderbot.dm
/:cl:

Fix runtime in spiderbot.dm

---

code/modules/core_implant/cruciform/rituals/priest.dm

Fix a runtime in priest.dm when removing a ritual boost from a participant when this participant no longer exists. It can happen if the participant is deleted between the moment the boost is received and the moment the boost ends (since the `take_boost` is an automatic callback).
> [19:28:16] Runtime in priest.dm,280: Cannot read null.stats
:cl: Hyperio
fix: Fixed runtime in priest.dm
/:cl:

Fix runtime in priest.dm

---

code/modules/mob/mob.dm

Fix a runtime issue when trying to read perks with the Show stats and perks verb.
It happens when the mob that uses this verb has no stats (ghost, mouse, borer for instance)
> [12:52:29] Runtime in mob.dm,1107: Cannot read null.perks
>    usr: The mouse (242) (zamoplay) (/mob/observer/ghost)
>   usr.loc: The open space (113,112,3) (/turf/simulated/open)
:cl: Hyperio
fix: Fixed a runtime when trying to read stats and perks
/:cl:

Fix runtime with perks in mob.dm

---

code/datums/mind.dm

Fix runtime in mind.dm when trying to check `current.mind` with `current` being `null`.
Considering that at the beginning there is a check for 
```
if(current)	//remove ourself from our old body's mind variable
if(changeling)
[...]
```
the possibility that `current` could be `null` seems to be expected.
> [19:04:26] Runtime in mind.dm,96: Cannot read null.client
>    usr: Francis Fuchs (as Pablo Mand) (coolfoolftw) (/mob/living/carbon/human)
>   usr.loc: The floor (115,114,2) (/turf/simulated/floor/tiled/dark)
:cl: Hyperio
fix: Fixed runtime in mind.dm
/:cl:

Fix runtime in mind.dm

---

code/modules/client/client procs.dm

Another day, another fucking runtime.
Clients don't support `qdel()`, and this caused runtime spam and possibly resulted in clients not being disconnected properly. I changed the 3 instances of that that I found to `del()`.

Fixes a runtime in log_client_to_db

---

code/modules/mob/living/simple_animal/hostile/retaliate/drone.dm

Combat drone's laser used to do brute damage, changed it to laser. I hope this is the right pull request
Lasers that make brute damage feel too "early Neal Stephenson-ish" kind of cyberpunk, so I think burn damage makes it more grounded.
:cl:
Combat drone's laser went from "BRUTE" to "BURN"
/:cl:

Fixed damage type of the combat drone's laser. 

---

code/game/objects/items/weapons/storage/bsdm.dm
code/modules/dungeons/teleporter.dm
code/modules/mob/living/silicon/robot/drone/blitzshell.dm
code/modules/reagents/reagent_containers/syringes.dm

Blitzshell drone can now do blood extraction contracts, with unbreakable syringe.
Exosuits can now also be teleported by Ancient teleporter.
Blitzshell drone can now do blood extraction contracts.
Exosuits can now also be teleported by Ancient teleporter.
:cl: DarkLevel
fix: Blitzshell drone can now do blood extraction contracts.
fix: Ancient teleporter will teleport exosuits as well.
/:cl: DarkLevel

Fix blitzshell blood extraction and ancient teleporter restriction.

---

code/game/verbs/who.dm

Fix runtime in who.dm when trying to read `C.mob.stat` when `C.mob` is `null`.
Added a check for the existence of `C.mob`
> [19:42:54] Runtime in who.dm,18: Cannot read null.stat
>    proc name: Who (/client/verb/who)
>   usr: Fisk06 (fisk06) (/mob/new_player)
>   src: Fisk06 (/client)
>   call stack:
>   Fisk06 (/client): Who()
:cl: Hyperio
fix: Fixed runtime in who.dm
/:cl:

Fix runtime in who.dm

---

code/game/objects/items/weapons/power_cells.dm

PDA cells no longer have Uranium material, they use a small amount of radioactive reagents instead. Increased tech level on Excelsior cells by one, and makes the large Excelsior cell equivalent to a Super cell.
Stops dumb meta-rushing of the FO's Office every round which doesn't make sense besides the fact this is a game.
:cl:
tweak: Uranium has been removed from PDA Cells, replaced by radioactive reagents.
/:cl:

Tweaks some cells

---

code/game/objects/random/rig.dm

IHS equipment is taken away according to the loot doctrine and rigged cells are just painful without any counters.
:cl:
del: Removed IHS suits from random suits;
del: Removed rigged cells from the possible damage dealt to suits;
/:cl:

Get rid of IHS equipment and rigged cells

---

code/game/objects/landmarks/join.dm
code/modules/client/preferences_spawnpoints.dm

Robot latejoin now uses a nosearch spawnpoint datum, which'll only take into account the turf the spawn landmark is on.
Issue was spawnpoints add all turfs in view, which doesn't take into account obstacles between the initial landmark and the found turf, causing robots to spawn in the maintenance section close by. (See fig 1)
:cl:
fix: Fixes latejoin robots from spawning in the maintenance near to the robot storage units.
/:cl:

Bandaid-fixes robots from spawning in maintenance

---

code/game/objects/structures/crates_lockers/crates.dm

Simply buffs trash carts to hold 3x more items and 2 more mobs
Trash carts atm are just lesser lockers as they seem to hold the same amount but cant walk past when open, making clearing things like the becone or halls of ~~bodys~~ roaches and spiders harder for no reason, and makes clearing things like maints up a lot harder to use the cart that WOULD BE USE FOR IT. >:|
:cl:
tweak: Trash Carts now hold 3x more items and 2 more bodies inside them
/:cl:

Makes trashcarts better at being usefull

---

cev_eris.dme
code/game/gamemodes/events/hidden_events/bluespace_rift.dm
code/game/objects/effects/portals.dm

- Event creates 1-5 pairs of two ways teleporters in maints
- Each pair can be used 3-10 times, when usage counter becomes 0 pair disappears
- Uses sprite and description of standard teleporter
Adds diversity to possible random events.
:cl:
add: Added bluespace rift
/:cl:

Hidden events: Bluespace Rift

---

code/modules/sanity/breakdown.dm

Fixes the admin log showing the raw duration, now it shows it as seconds. This was giving cause for alarm, making people think that a duration of 900 was 15 minutes, not 1.5 minutes.

Breakdown admin log fix

---

code/game/objects/structures/salvageable.dm

Bliss console - Now can at 5% odds drop level 4 parts, *this is a legit 20% on a 2%*
Autolathe can now at 5% drop 3 uranium and a 1% to drop 1 diamond.
Autolathe have a 5% to drop a autolathe board 
broken machine now at 5%'s can drop t3 parts
broken computer now at 5%'s can drop t3 parts
These guys are much faster/easyer to over look as any role do to sci being able to cheaply outclass its parts rather fast - 10~ mins into a round - meaning if you ever want to get parts you just trade plastic and metal for them rather then look around maints and hope to get them.
Now rather then just throwing in the parts into all the things ever, that would be bad do to making them to common - See why you never need to print off crowbars basicly
Autolathes all be it wayyy more offten deconned are mostly …

Better salvageables

---

code/modules/clothing/head/armor.dm
code/modules/clothing/spacesuits/rig/modules/modules.dm
code/modules/clothing/spacesuits/rig/modules/utility.dm
code/modules/clothing/spacesuits/rig/rig.dm

Adds flash protection, a price tag, hair, ear, eye and face blocking to the TM helmet. Also adds a interface name and interface description to the TE cape, and makes it so the TE cape doesn't appear over inventory icons by adding an option in rig.dm to toggle whether a rig module appears overlayed on the inventory of the wearer.
Adds value and practicality to the TM helmet and makes it so hair stays under the helmet, the description can help with knowing what's installed in the rig, and the cape icon doesn't fit the icon of the chest rig in the inventory far as I know. 
:cl:
add: TE cape now has interface name and description
tweak: TM helmet now blocks flashes, hair, and facial features and has a price tag
tweak: TE cape no longer appears overlayed in inventory
refactor: rig modules now …

Adds More Protection to TM Helmet, Patches TE Rig Cape Icon

---

code/modules/mob/death.dm

Previously, if you gibbed and gave a null anim, you wouldn't be deleted.
Now, if your anim is null, you won't make a useless overlay, and will be deleted regardless.
Phantom roach corpses won't block doorways and send people insane.
:cl:
fix: fixes gibbed or butchered roaches from not deleting properly.
/:cl:

Fixes roaches not being properly deleted upon gibbing

---

code/modules/mining/drilling/scanner.dm
code/modules/research/designs/mining.dm
code/modules/research/nodes/engineering.dm

Adds an advanced mining scanner, to help with locating subsurface materials more precisely
I could not test this on local, as I was not robust enough to get the ship running to move it to a mining asteroid.
After playing some rounds as a shaft miner, I found that, while surface minerals were plentiful, it was misleading and mostly carbon.
This gives something for moebius to give to miners besides atomic cells, and helps with optimizing subsurface mining.
:cl:
add: Adds the advanced subsurface ore detector
/:cl:

Advanced subsurface ore detector

---

cev_eris.dme
code/game/machinery/repairstation.dm
code/game/objects/items/weapons/circuitboards/machinery/recharge_station.dm
code/game/objects/random/circuitboards.dm
code/modules/research/designs/circuits.dm
code/modules/research/nodes/robotics.dm
maps/submaps/deepmaint_rooms/normal/mechbay.dmm

Adds an automated repair platform, to fix cyborgs up that stand on it
Another ingame request. I'm aware that the cyborg recharger can perform skin-level repairs, but as a drone you apparently have to suffer human interaction to repair yourself, worse so if its internal components that are broken.
:cl:
add: Adds the cyborg auto repair platform. Repairs cyborgs that stand on top of them.
/:cl:

Repair platform

---

.github/workflows/compile_changelogs.yml
tools/changelog/generate_cl.py

* CL action would no longer :x: commits for not having a changelog entry.
* CL action would no longer :x: commits that were directly pushed to master.
* CL rebuild now fires every 12 hours, as opposed to 15 minutes. This should cut down on CL spam in commit log.
To :x: commits and people for pushing directly to master is a job for maintainers, not bots.

Makes changelog actions suck a bit less

---

code/modules/sanity/sanity_mob.dm

I actually made the list but never checked if the item was in said list. Whoops.
:cl:
fix: Only merchants with the right perk can use money as an inspiration now.
/:cl:

Fixes money being used as an inspiration by players without the required perk

---

code/modules/projectiles/guns/projectile/automatic/sol.dm

The Sols recoil has been reduced from 13 (reere why) to a more manageable 8. This gun was literally basically worse than a pistol (paco) past point blank because of the recoil, and the kit still makes you have more recoil than a wintermute so I feel this is fine.
Makes the Sol no longer worse than your handgun.
:cl:
balance: Sol has 38ish% less recoil overrall.
/:cl:

The Sol carbine no longer has insane recoil

---

code/modules/clothing/under/jobs/medsci.dm

removes melee/bullet/energy armor from paramedic jumpsuit and nerfs bio from 30 to 10
paramedics shouldnt have the best single jumpsuit from every crewman, sec jumpsuits and tactical turtlenecks dont even have any armor values, and their bio armor is stronger than anyone else's
:cl:
balance: removes melee/bullet/energy armor from paramedic jumpsuit and nerfs bio from 30 to 10
/:cl:

paramedic no longer has melee/bullet/energy armor on his jumpsuit

---

code/game/machinery/autolathe/autolathe.dm

Add `update_strings` and `update_icon` after eject a material and validate NOT zero amount an material stack
Normal use autolathe
:cl:
fix: Fixed an error when the autholate eject zero stack, and bug with ejected icon.
/:cl:

fix(autolathe.eject): zero stack amount

---

code/modules/cargo/packs.dm

Ok so this adds more crates to the guild.
Bar resupply:  Almost everything that is in the booze-o-mat in reduced quantity , 2000 credits
Cake crate: one of each possible cake sans brain cake, 2000 credits
Research data crate: 2 research data discs, 5000 credits
Medical resupply crate: bruise packs and ointments, 1000 credits
Medical Kit crate: renamed
changed tool crate: 2 more toolmods, 2000 credits
empty disks crate: 5 empty autolathe design disks, 1000 credits
Guild is in dire need of more crates that have an actual use.
:cl:
add: Bar resupply crate:  Almost everything that is in the booze-o-mat in reduced quantity , 2000 credits
add: Cake crate: one of each possible cake sans brain cake, 2000 credits
add: Research data crate: 2 research data discs, 5000 credits
add: Medical resupply …

Adds more guild crates

---

code/_onclick/click.dm
code/_onclick/other_mobs.dm
code/datums/setup_option/backgrounds/fate.dm

1. Lowborn perk makes you are blacklisted from all jobs in moebis and IH.
2. Absolute grab perk now acts on a circular radius of 2 tiles.
:cl:
tweak: Lowborn perk makes you are blacklisted from all jobs in moebis and IH.
tweak: Absolute grab perk now acts on a circular radius of 2 tiles. 
/:cl:

fix lowborn and absolute grab perks

---

code/game/objects/items/weapons/autolathe_disks.dm

Fix "Frozen Star - .35 Paco SMG" disk. Rename disk and replace ammo in designs.
Normal use "Frozen Star - .35 Paco HG" disk
:cl:
fix: Rename disk_name (Frozen Star - .35 Paco SMG -> Frozen Star - .35 Paco HG) and replace ammo in designs (smg -> magazine_pistol).
/:cl:

fix(frozen_star | designs & disk_name)

---

code/game/objects/items/devices/radio/encryptionkey.dm
code/modules/mob/living/say.dm
code/modules/mob/say.dm

Convenience of chatting for russians.
Becouse now you should not waste your time switching from languange to languange, to get right radio key.
In my case with 3 or 4 languages it is a problem.
:cl:
add: Russiano radio keys are now available. `:ы` `:ь` `:р` `:з` `:н`
/:cl:

utf-8 two-byte russian chars hotfix

---

code/game/machinery/Sleeper.dm

add `eject_occupant_verb` to sleeper
Force eject occupation from sleeper without console
:cl:
add: Abble to eject sleeper occupation, when there's no electricity.
/:cl:

update(sleeper): add eject_occupant_verb

---

code/datums/outfits/jobs/church.dm
code/game/objects/items/weapons/storage/bags.dm
code/game/objects/items/weapons/storage/belt.dm
code/modules/clothing/shoes/jobs.dm
code/modules/clothing/spacesuits/void/neotheology.dm
code/modules/projectiles/guns/matter/launcher/nt_sprayer.dm

Now fixed PR of Custian QOL changes.
Custodian is a very menial and boring job, this aims to make the job at least more comfortable by having better space to utilize and appropiate boots that prevent the custodian from slipping. These boots are UNOBTAINABLE other than spawning as custodian as to prevent these boots to be used everywhere.
:cl:
add: Added new custodian jackboots to prevent slipping
tweak: NeoTheo Utility belt now holds soap and space cleaner
tweak: Cleansing carbine now also is carriable in the belt slot
balance: Trash bag is smaller but holds less, it now fits properly into a bag to carry it with you
/:cl:

Custodian QOL changes proper

---

code/modules/mob/mob.dm
code/modules/paperwork/paper.dm

Added UTF-8 encoding to papers and flavors, so now you can write on it in russian.
fixes #5011
Because russkie vpered.
:cl: Vlad777
fix: Fixed russian letters encoding in papers and flavors.
/:cl:

Added utf-8 encoding to paper and flavors.

---

code/game/objects/landmarks/storyevent.dm
code/modules/stashes/stash_datum.dm

Stash note with pinned `IMAGE` sometimes, what generated and pictured image are bad, crashes clients who see this note.
No more crashes (not 100% true)
:cl:
fix: fixed stash crashes due to picture in pointer note
/:cl:
`/obj/landmark/storyevent/midgame_stash_spawn.navigation` is used only for random stash spawn, so we may leave in untouched in obj's defenition until `Initialize()`. Means there won't be empty string somewhere else.

Stash image dudos

---

code/modules/projectiles/projectile/bullettypes.dm

Makes clrifle in general do more AGONY damage
also lets traitors capture people more consistently, and with no evidence. ~~the Dallas isn't real, it can't hurt you.~~
:cl:
balance: Crifle rubber ammo (ceaseless) does more agony damage.
/:cl:

clrifle rubbers (sol/caselesspistol) does more agony damage

---

code/game/objects/structures/watercloset.dm

Cisterns will no longer cancel tool check instantly anymore, showers also had their tool check tweaked.
Restores niche feature.
:cl:
tweak: Showers are easier to temperature adjust.
fix: You may now open and close cisterns again.
/:cl:

Fixes cisterns.

---

code/game/objects/landmarks/storyevent.dm
code/modules/stashes/stash_datum.dm
code/modules/stashes/stash_types/booze.dm
code/modules/stashes/stash_types/excelsior.dm
code/modules/stashes/stash_types/junk.dm
code/modules/stashes/stash_types/valueables.dm
code/modules/stashes/stash_types/weapons.dm

Improves undocumented change to stash behavior landmarks, so it doesn't override existing directions. Commented out photo stashes to preserve their writing for re-use, but still disable them.
Fixes behavior a lot of players have been complaining about.
:cl:
fix: The undocumented change which broke directions to antag stashes has been fixed. Additionally, image stashes will no longer keep spawning despite their photos being removed.
/:cl:

Restores stash behavior.

---

code/modules/stashes/stash_types/captain.dm

Command stash directions changed to only use landmark, no coordinates.
Makes the command stash more search-intensive to find.
:cl:
balance: Command stashes will only give personalized landmark directions to their loot now, and won't ever provide exact coordinates.
/:cl:

Command stash directions change

---

code/datums/craft/recipes/weapon.dm
code/game/objects/items/weapons/melee/misc.dm
code/game/objects/items/weapons/tools/simple_weapons.dm
code/modules/stashes/stash_types/captain.dm
maps/CEVEris/_CEV_Eris.dmm

Captain's Chain of Command, and the Nailstick are now tools which can be upgraded.
Just like broken bottles, you can augment your weapons with "stuff" now.
:cl:
tweak: The Chain of Command and the "Nailstick" are now both tools, and accept tool mods.
/:cl:

More simple weapon tools

---

code/game/machinery/Sleeper.dm
code/modules/reagents/reagents/medicine.dm

Adds tricord to sleepers but removes the ability to mix them inside a sleeper.
Instead of adding an OD threshold or messing with tricord at all, it'll simply be added to a sleeper while removing the ability to spam it.
:cl:
add: Tricord to sleepers.
balance: Tricord can no longer be mixed in sleepers.
/:cl:

Adds Tricord to sleepers

---

code/modules/mob/living/silicon/robot/robot_modules.dm
code/modules/projectiles/guns/energy.dm
code/modules/projectiles/guns/energy/egun.dm
code/modules/projectiles/guns/energy/lasertag.dm
code/modules/projectiles/guns/energy/nuclear.dm
code/modules/projectiles/guns/energy/shrapnel.dm
code/modules/projectiles/guns/energy/stun.dm

Also makes two gun vars use `TRUE` and `FALSE`.
:cl: ACCount
balance: Robot energy guns no longer have infinite charges - they now draw charge from robot's cell and take time to recharge
/:cl:

Fixes cyborg guns spawning with infinite charge

---

code/modules/reagents/reagents.dm
code/modules/reagents/reagents/drugs.dm
code/modules/reagents/reagents/stims.dm
code/modules/reagents/recipes.dm

recipes are now WAY easier
1st tier you can USUALLY make without roaches
2nd tier usually you need at least one monster part
3rd tier. sum of stim
also buffs are now stronger with same debuff
BUT withdraws now take sanity away
well stims are underused and sanity was not in the game when they where added
and drugs should give some more reason to use em aside from RP and Sanguinium thats just not needed
:cl: Fernandos33 
tweak: Recipes for stat stimulators changed to be made easier
balance: Withdraws now get sanity debuff (sanity debuff from withdrawing>> than sanity gain using the drug) 
balance: Every stat drug will give a small sanity boost, except for hyperzine.
/:cl:

buffin chems

---

code/modules/biomatter_manipulation/biogenerator.dm

Buffs the biogenerators maximum output power from 200k to 500k. I can't recall using or seing anyone use it, and there was a request in the orders channel
This should encourage people to actually use the biogenerator, at least as a backup power source after the SM gets vented or something
:cl:
balance: changes the biogenerators output_power from 200k to 500k
/:cl:

Biogen-buff.dm

---

code/datums/autolathe/circuits.dm
code/game/objects/items/weapons/autolathe_disks.dm

Removes the licensing costs from: Airlock electronics, Air alarm electronics, Fire alarm electronics and Power control modules on the Technomancer disk: Technomancers ESPO-830 Circuits. In addition, adds the secure electronics and makes them available for technomancer use, seems like a thing that's up their alley.
Considering how easy it is to destroy these machines and how often they are - replacing them shouldn't be half the nuisance it is. I don't know where they're pulling the need for silicon from but this will at least make them 50% less of a PITA to rebuild.
The secure airlock electronics are for the paranoid Technomancers to make use of, who want to inconvenience outsiders transgressing into their domain.
:cl:
add: The Technomancer Union's ESPO-830 now contains secure airlock …

Rebalances ESPO-830 disk

---

code/game/objects/random/guns.dm
code/game/objects/random/packs.dm
code/game/objects/random/voidsuit.dm
code/modules/scrap/scrap.dm

1)Replaced STS with FS AK because it fits much more, sts is a gun desired by basically everyone
2)Also added c20r smg and ion rifle, it isn't a real gamechanger
3)Added pouches to cloth piles because why not?
4)Lowered chance of drop for red voidsuit
5)Food trash piles now have mostly rotten food inside for obvious reasons
Currently, STS is a top tier gun, why simply putting it to junk pile for everyone to dig? Same goes for blood red voidsuit, though I didn't remove it entirely. But I noticed that pouches were even more rare than guns and there were no spoiled food in food junk, that's ridiculous.
:cl:
tweak: "Tweaked trash piles, much less chance to find STS and blood-red voidsuit in trash, but more for some other guns and pouches"
/:cl:

Random trash tweaks

---

maps/CEVEris/shuttles-eris.dm

Title.
:cl:
tweak: Adjusted the speed of Serbian shuttle travel time from 7 minutes to 3.
/:cl:

Mercenary shuttle travel time is now 3 minutes

---

code/modules/projectiles/guns/energy/lasersmg.dm

This may actually just be too low, as we want players to specifically choose this thing, but with weapon attachments the damage output can be adjusted significantly. I was motivated to quickly make this after I noticed some other balance PRs coming up, and being closed. The lowered burst fire eliminates the core identity of the weapon, and this PR maintains that.
Balances the weapon appropriately after doing dreaded math, and with actual knowledge of the values. Tested in-game as well to gauge its effectiveness somewhat.
:cl:
balance: Re-adjusted the Lasblender's damage values, remember to use weapon attachments to increase its power.
/:cl:

Lasblender damage adjustment

---

code/modules/clothing/suits/jobs.dm

give the priest and acolyte jacket same bio protect as a lab coat. so he doesn't "insta die" from touching biomass
well if the chemist can resist a bit of bio why not the priest that works with it?
:cl:
tweak: Priest and acolyte jacket should at least protect as much as a labcoat from bio damage
/:cl:

priest and acolyte jacket should at least protect as much as a labcoat

---

code/game/objects/structures/wire_splicing.dm
code/modules/power/cable.dm

It's possible to create wire splicings on existing cables, but there is some jank, and this PR addresses it. You'll actually be able to make splicings larger now. It adds in some spam protection to stop people from bypassing the skill check and prevents people from being able to create multiple splices on a single turf.
Because it fixes some intended functionality and includes a couple of safeguards to prevent ~~hilarity~~ abuse.
:cl:
tweak: it should no longer be possible to spam player-made wire splices
fix: making splices bigger is now properly functional
/:cl:

Fixes intentional wire splicing

---

maps/CEVEris/_CEV_Eris.dmm

Sectional shutters and buttons are gone. Remote buttons on bridge are removed.
:cl:
del: Sections shutters and buttons that activates them are no more as and all remote buttons on bridge.
/:cl:

Removing sectional shutters and buttons from bridge

---

code/game/objects/structures/medical_stand.dm

I found the long ass timer while placing the medical stand's gas mask on people during surgery a little annoying.
It's basically a small QoL tweak for medbay staff and the people that get surgery.
tweak: Placing gasmask and IV needles on people should be faster now.

Placing/Removing gas masks and IV needles using the medical stand should be faster now.

---

code/modules/clothing/spacesuits/bomb.dm

Basically the title.
This thing isn't even useful for bomb disposal, and I think that it protecting more is fine for the game personally. It gives it a niche as an incredibly slow and situational armor.
:cl:
balance: bomb suits now have 40 bullet/melee/energy resist.
/:cl:

Buffs bombsuits melee/bullet/energy resist to be 40

---

code/datums/perks/oddity.dm

:cl:
fix: Parkour will no longer actually increase the delay before doing parkour.
/:cl:

Parkour should no longer increase the time it takes to do parkour anymore

---

code/game/machinery/doors/airlock.dm

Title
Blitzshells can't bolt doors.
:cl:
balance: Blitzshells now can't open AI airlock control panel
/:cl:

Blitzshells now can't open airlock control panel

---

code/game/atoms_movable.dm

#5186 wasn't good enough as previous call order was so bad so it called things to check before updating atom's state
Previous PR wasn't done properly so there is another one. _its done now trust me_
:cl:
fix: Mobs that got thrown at open space are falling down as expected.
/:cl:

#494 again

---

code/modules/mechs/equipment/_equipment.dm
code/modules/mechs/equipment/medical.dm
code/modules/mechs/equipment/utility.dm

:cl:
fix: hydraulic calmps and mounted sleepers only interact with adjacent objects / mobs.
/:cl:

Fixes the range of exosuit tools.

---

code/game/objects/items/weapons/implant/implants/carrion/breeding_spider.dm
code/game/objects/items/weapons/implant/implants/carrion/infection_spider.dm
code/modules/organs/internal/carrion.dm

Few carrion balance changes and bugfixes, less spiders in general.
Making carrions a bit more fair, and some abilities more situational. Also bugs are bad.
:cl:
balance: Spider call now has a 5 minute cooldown, costs a bit more chem points, but makes more spiders.
balance: Infection spider does 33% less agony damage.
balance: Breeding spider creates a bit less spiders.
fix: Added a popup window to make sure that the player really want's to exit the body as a spider core.
fix: It should now be impossible to convert carrions to carrions.
fix: Infection spider should stop giving you pain if it failed.
/:cl:

Carrion balance changes and bugfixes

---

code/modules/lighting/lighting_atom.dm

Adds check to see if openspace is open or not, only then fall through it.
Things won't fall through catwalks on round start and when spawned.
:cl:
fix: Things won't fall through catwalks on round start.
/:cl:

Things don't fall through catwalks on spawn

---

code/game/objects/items/weapons/implant/implants/carrion/carrion_spiders.dm
code/game/objects/items/weapons/implant/implants/carrion/control_spider.dm

Control spiders don't work on carrions anymore and have a 5 minute cooldown on each controled mob. Spiders can't attach to robots and silicons anymore.
Control spider is more balanced, and spiders in general make more sense.
tweak: carrion spiders can't attach to robots anymore
balance: control spider has a 5 minute cooldown on each mob controled
balance: control spiders can't control other carrions
fix: fixes #5250 
/:cl:

Control spider fix and carrion attaching changes

---

code/controllers/evacuation/evacuation_pods.dm
code/controllers/subsystems/voting/poll_types.dm

Order on the discord: "Change the evac vote to a bluespace jump vote that initiated the 20 minute evac jump if passed".
Need a confirmation that it works on live server since on a local server the end of round does not trigger (even with a normal evac).
Lore-wise there is no reason to abandon the ship if it is not critically damaged so it's more realist to just launch a bluespace jump to another star system.
:cl: Hyperio
tweak: Change the evac vote to a bluespace jump vote
/:cl:

Change the evac vote to a bluespace jump vote

---

code/datums/uplink/devices and tools.dm
code/datums/uplink/stealth and camouflage items.dm

Fixes some uplink items only showing up for carrions
Fixes a bug.
fix: agent ID and mental imprinters should be aveliable for other antags except carrion
/:cl:

Fixes some uplink items only showing up for carrions

---

code/game/objects/items/weapons/implant/implants/carrion/toxic_spider.dm
code/modules/organs/external/stump.dm
code/modules/reagents/reagents/toxins.dm

Nerfs toxin spiders and fixes a runtime.
Toxin spiders were way too op and runtimes are bad.
:cl:
balance: toxin bomb spider uses normal lexorin instead of lexorin plus
fix: qdel loop in limbstumps
/:cl:

Toxin spider and runtime fix

---

code/modules/projectiles/guns/projectile/shotgun/doublebarrel.dm

An attempt to saw a sawn-off shotgun now gives a message "You cannot shorten \the [src] any further!"
If you have attachments, you will be asked if you want to proceed.
It was an oversight. This is a fix.
:cl:
fix: You can no longer endlessly shorten the sawn-off shotgun.
fix: If the shotgun has attachments, you will be given a chance to cancel (yes/no) to avoid destroying them.
/:cl:

Saw-off sawing fix

---

code/modules/mob/observer/ghost/ghost.dm

Admins can bypass mouse respawn time.
Closes #5096 
:cl:
admin: Admins can bypass mouse respawn time
/:cl:

Admins can bypass mouse respawn time

---

code/game/objects/items/weapons/mine.dm
code/game/objects/items/weapons/traps.dm
code/game/objects/structures/wire_splicing.dm
code/modules/assembly/mousetrap.dm
code/modules/mob/living/carbon/human/inventory.dm
code/modules/mob/mob_helpers.dm

Player stats were giving too much ability to evade traps even with low stats in VIG.
The noise coefficient was not working as designed.
Both modifiers are now not only affected by the weight of what you are wearing but also by what you carry with you.
:cl:
tweak: traps are now a little more effective.
tweak: The noise coefficient is now affected by the objects you carry with you.
/:cl:

tweak noise_coeff and traps logic

---

code/datums/perks/fate.dm

The name of the noble family is now found in the description of the weapon and not in the name of the weapon.
:cl:
fix: Toolmods no longer erase the noble family name.
/:cl:

Toolmods no longer erase the noble family name.

---

code/game/objects/items/weapons/autolathe_disks.dm

Currently counselor autolathe disk has small power cell while counselor is powered by medium power cell. This PR fixes that, replacing small high-capacity power cell with medium high-capacity power cell.
grug print ammo without walking away good
:cl:
fix: Counselor autolathe disk now contains medium battery design instead of small one.
/:cl:

Fix Counselor disk

---

code/game/objects/items/weapons/implant/implants/carrion/carrion_spiders.dm

Spiders were not getting the 4 sec cooldown on attaching after surgery, should be fixed.
It's a pain to kill spiders with a small time window.
fix: spiders should take the same time to attach after surgery, as after movement.
/:cl:

Spider time to attach fixed for surgery

---

code/__DEFINES/damage_organs.dm
code/__DEFINES/items.dm
code/game/objects/items/weapons/tools/mods/_upgrades.dm
code/modules/mob/living/carbon/human/human_damage.dm

* Add the `PSY` damage type with a `GUN_UPGRADE_DAMAGE_PSY` keyword to add PSY damage to guns.
* This type of damage is handled like the others so it is reduced by armor when you are hit by a bullet
* Damage is applied to sanity through `sanity.onPsyDamage(damage)` with for instance mindfryer doing 2 damage and mindboil spider doing 1 damage. So for projectiles psy damage will have to stay quite low or else the target will go into breakdown really quickly if they are hit several times.
There is now a way for guns to shoot projectiles that directly impact the sanity level.
:cl: Hyperio
add: Added psy damage type to guns and projectiles
/:cl:

Add the PSY damage type and the possibility for guns to do PSY damage

---

code/game/gamemodes/changeling/modularchangling.dm
code/game/objects/items/weapons/implant/implants/carrion/infection_spider.dm

Increses the infection time of the infection spider from 3.5 to 5 minutes, cost from 5 to 7, damage from 20 to 15 and while keeping overall damage procs in the 5 minute similar to the 3.5 minute one, chance for limbs to pop off has been cut in half.
Infection spiders were too strong and could be an effective combat tool instead of a conversion tool.
balance: Infection spiders cost more and take more time to convert someone while dealing less damage.
/:cl:

Infection spider nerf

---

code/modules/mob/living/carbon/human/emote.dm

Allows the Excelsior to dab, which gives an unique red message if they really are Excelsior, since only they know all the intricacies of dabbing to truly make a dab a dab.
:cl:
add: Excelsior can now dab using the *dab emote. Normal folks can do it too but they don't truly know how to do it like the Excelsior do.
/:cl:

Excelsior can dab

---

code/modules/mob/living/carbon/human/emote.dm

Reverts discordia-space/CEV-Eris#5272
Because dear God, this is going to escalate into cancer fest with communists dabing on capitalists corpses, and this should be avoided.

Revert "Excelsior can dab"

---

code/game/objects/structures/door_assembly.dm

Fixes mining airlock assembly sprite.
Typo fix.
:cl:
fix: Fixed the mining airlock assembly sprite, it's no longer invisible.
/:cl:

Mining airlock assembly sprite fix (door_assembly.dm, 201)

---

code/game/gamemodes/events/weather/rad_storm.dm

Right now the way weathers work, they are created everywhere besides "protected areas".
For radstorm, there is an extra check on actual radiate() function if it's a station Z level or not.
As the result, the radstorm appears in deep maintenance/on mining level, but it does not do damage.
Also mining shuttle is the only shuttle that is not currently shielded from it.
My fix adds "mining shuttle", "asteroid" and "deep maintenance" to the list of protected areas.
What it does in reality: it simply removes the green overlay where it was not already damaging players/had no effect.
Right now the listed areas show overlay but do not damage, negating the purpose of the overlay.
This fixes it.
:cl:
fix: radstorm no longer displays its overlay in deep maintenance/asteroid belt (it did not damage …

Radstorm fix: Expansion of protected areas

---

code/game/machinery/spaceheater.dm

Space heaters start with large cells which cannot be inserted back, because the check is for medium cell. Corrected that.
Without the fix:
- You cannot reuse the cell the heater starts with.
- Since the heaters are designed to run for prolonged time (to maintain/change atmosphere temperature), it makes sense for them to be designed with long term cells.
:cl:
fix: Space heaters now properly accept large cells instead of medium ones.
/:cl:

Space heater - Cell size fix

---

code/modules/mob/living/carbon/human/human.dm
code/modules/reagents/reagent_containers/food/snacks.dm
nano/templates/sanity.tmpl

the sanity ui was not working well, this fixes it.
:cl:
fix: sanity ui.
tweak: add the label "cheese food" to various types of pizza.
/:cl:

fix sanity ui

---

code/modules/mob/living/carbon/resist.dm

##About The Pull Request
Changes breakout time (when resisting in handcuffs) to be displayed in seconds instead of rounded minutes.
Works well with cuffs with breakout times less than 1 minute or not equal to the power of a minute.
Without this fix you would either see incorrect time (1 minute for 70 seconds) or even 0 minutes (for 59 seconds and below) breakout times.
:cl:
fix: handcuffs breakout time is now displayed in seconds (to see correct time/work right with breakout time < 1 minute).
/:cl:

Breakout time in seconds

---

code/modules/projectiles/guns/energy/plasma.dm

This PR edits plasma weapon descriptions to state some info about their different modes.
People have zero fucking idea what different plasma weapon modes do unless they codedive.
:cl:
tweak: Plasma weapons are more obvious about their firing modes now, check their descriptions to see the details.
/:cl:

Make plasma weapon descriptions obvious

---

code/modules/projectiles/guns/mods/mods.dm

Prefixes do not work for gun mods. I saw that it worked for tool mods but forgot to check for gun mods.
Cleaning the code of useless stuff.
:cl: Hyperio
code: Remove prefixes for new RnD gun mods
/:cl:

Remove prefixes for new RnD gun mods

---

code/modules/projectiles/projectile/bullettypes.dm

title
:cl:
fix: beanbags finally. Check bullet armor.
/:cl:

beanbags now actually properly check bullet armor, removes a dumb comment

---

code/game/objects/items/weapons/storage/storage.dm

I was surprised this feature wasn't here. 
The only way to do this at the moment that I could find was to drag the container to your body.
This functionality works really well in other codebases.
:cl: Hopek
add: You can now Alt-click on storage containers to look inside them
/:cl:

You can now Alt-click on storage containers to look inside them

---

code/game/objects/structures/extinguisher.dm

**EDIT:**
Extinguisher Cabinants have a new verb. They can now be opened via the right-click menu.
Added 
:cl: Hopek
add: Extinguisher Cabinants can be alt clicked to open/close
add: Extinguisher Cabinants have a new verb. They can now be opened via the right-click menu.
/:cl:

Extinguisher Cabinants can be alt clicked to open/close

---

code/datums/outfits/jobs/engineering.dm

Changes hard hat in pre-spawn loadout for technomancer to proper one.
So you don't waste those 2 seconds changing your awful preset helmet that does not fits your palette onto cool technomancer one. Exultant keeps his white helmet.
:cl:
fix: Technomancers spawn with proper helmet now.
/:cl:

Give technomancer loadout a proper helmet

---

code/datums/topic/admin.dm
code/modules/admin/admin.dm
code/modules/mob/living/carbon/human/human.dm
code/modules/mob/living/carbon/human/human_defines.dm
code/modules/sanity/breakdowns.dm

Glassification breakdown now no longer hijacks both peoples views, unless the receiver is below a sanity threshold.
Glassification now only hijacks your view for precisely a second, rather than a second + mob tick offset
Adds some new debug tools for testing out sanity breakdowns through the player panel.
Having your eyesight hijacked during a firefight for 3~5 seconds because a vagabond stubbed his toe on a roach is not very fun.
:cl:
tweak: Glassification no longer hijacks the receiver's view, unless they are below a certain sanity threshold.
tweak: Glassification now only hijacks your view for a true second.
admin: Added a sanity debug function, to invoke a breakdown upon somebody.
/:cl:

Glassification tweaks

---

code/modules/projectiles/guns/projectile/automatic/sol.dm
code/modules/projectiles/guns/projectile/automatic/sts35.dm

Basically the title. The STS and sol literally do not need a damage bonus. If you want something that does a decent amount of damage as IH get a wintermute.
If you want more damage as a traitor buy HV ammo for your STS.
Makes the sts not a literal death laser beam that fires enough damage to instantly kill everything in the game in 2 bursts and makes the sol not literally better than the wintermute in almost every way
:cl:
balance: sol and sts no longer have damage multipliers and now do 1x damage, or basically base damage for their calibers. STS can now only bursts in bursts of 3.
/:cl:

STS and Sol no longer have a damage bonus. STS now only bursts in rounds of 3

---

code/modules/reagents/reagent_containers/glass/bottle.dm
maps/CEVEris/_CEV_Eris.dmm

well as suggested from the #feedback channel in discord.
replaces snack vendors all around the ship. that and
medbay got 2 extra sinks
RnD now have 1
bones. and punpun are back at their houses
added a handmade pistol and some bullets to xenobio. maybe this i'll give em a better chance against slimes roundstart
added screwdrivers to fix synth organs in surgery
https://gyazo.com/collections/01819e163794e3fc0d80cce71f9188ea
to make bar and garden more meaningfull. since the sanity on itself didn't brought it to eris needs
also
adds sinks to medbay and robotics surger. for surgeons. to clean their paws
adds pets. cause cmon you gotta love em (and incentive to pick MBO and Bar manager)
🆑 Fernandos33
add: 2 sinks to moebius
add: handmade pistol and ammo to xenobio
add: 2 screwdrivers to surgery …

Snacks remade (also punpun and bones return) and tweaks to moebius

---

code/modules/reagents/reagent_dispenser.dm

Why:
NT has 3 more barrels downstairs but because of the massive size of the barrels they never run out of wine in the first barrel inside of the altar room.
At the moment there is almost no point in having extra barrels downstairs if it holds 1000 units unless the barrels downstairs are meant to be stolen and not used by NT.
:cl: Hopek
tweak: The NeoTheology Cahors barrel holds less volume to give NT a chance to use the extra barrels downstairs.
/:cl:

The NeoTheology Cahors barrel holds less volume to give NT a chance to use the extra barrels downstairs.

---

code/game/machinery/autolathe/autolathe.dm

You can now Alt-Click autolathes to eject the disks.
:cl: Hopek
add: Autolathe disk eject QoL. You can now Alt-Click on any autolathe to eject the design disk.
/:cl:

Autolathe disk eject QoL

---

code/modules/hydroponics/trays/tray.dm
code/modules/reagents/reagents/toxins.dm

-you can know sample FROM TRAYS with wirecutters and knife (just be sure to use the "WIREcutting skill that it got" not the CUTTING
PLANT B GONE now kills everything on the tray
-plant
-pests
-and weeds
**ALSO:** 
you can now sample 3 times before killing the plant (no more RNG) and 4th will kill it and sample one last seed
fixes 2 bugs with botany
deletes the RNG around sampling from trays. AND allows for botanists to experiment more around splices
tweak: you can now sample 3 times before killing the plant (no more RNG) and 4th will kill it and sample one last seed
fix: wire cutters can be used to sample from tray now
fix: plant b gone now kills everything in Hydroponic trays
/:cl:

botany fix and more

---

code/modules/dungeons/teleporter.dm

Dungeon exit teleporter now teleports all clostets in range as well
Makes looting the one star dungeon less of a pain
tweak: Dungeon exit teleporter now teleports all clostets in range as well
/:cl:

Dungeon exit teleporter now teleports closets.

---

code/modules/clothing/spacesuits/void/void.dm

Now when you put a voidsuit in the washing machine, it'll clean the helmet, boots, and tank attached too.
You can't detach a voidsuit helmet (without decapitating somebody), so cleaning your voidsuit only to find that it irradiates you when you deploy the helmet with no way to clean it kinda sucks.
:cl:
add: Cleaning a voidsuit with a washing machine now cleans the attached components
/:cl:

Cleaning a voidsuit now cleans the attached boots, helmet, and tank

---

code/game/objects/items/weapons/storage/bags.dm

Add `matter` to bluespace trashbag to avoid having a free construction with autolathe.
You could construct an infinite amount of bluespace trashbag without that.
:cl: Hyperio
tweak: Bluespace trashbag construction is not free anymore
/:cl:

Fix trashbag matter since without that you can construct it for free

---

code/controllers/subsystems/jobs.dm
code/datums/datacore.dm
code/modules/modular_computers/file_system/reports/crew_record.dm

Looks like the records are partially created earlier than my previous code.
Fixes all of these:

Fixes 3 runtimes in records

---

code/modules/holodeck/HolodeckControl.dm

This gives all holodeck objects a plane of 95, which is the plane for items on the 4th z-level. If the location of the holodeck is changed in a future map update or if the holodeck is on a different z-level this value will need to be changed. I have no idea how to make this dynamic, some other coder will have to do that.
Get the holodeck working again.
:cl:
fix: fixed the holodeck items having the wrong plane
/:cl:

Fixes the holodeck

---

code/modules/multiz/turf.dm

You can descend onto tables.
You can climb up, and now you can climb down without breaking bones.
:cl:
add: Now you can climb down onto tables from z-level above by dragging yourself onto openspace.
/:cl:

Climbing down onto the tables from another z-level.

---

code/game/objects/items/weapons/grenades/chem_grenade.dm

> Large Chem Grenades:
> They don't work, fix them. Nobody know why.
Explanation:
```
beakers = list()
..()
```
at the end of `chem_grenade/large/prime()`, meaning the beakers were deleted just before processing `chem_grenade/prime()`
You can now use large chem grenades.
:cl: Hyperio
fix: Fix large grenades not exploding
/:cl:

[Order] Fix large grenades not exploding

---

code/modules/core_implant/cruciform/cruciform.dm

Added copying mob stats in cruciform on activation, so now cruciform can copy stats after cloning.
Because it makes cloning work as intended
:cl: Vlad777
fix: Fixed copying stats after cloning
/:cl:

Fixed copying cloning stats

---

code/modules/admin/topic.dm

Just noticed while porting https://github.com/discordia-space/CEV-Eris/pull/2977/files that I accidentally made this reference world_topic instead of admin_topic. Effectively it doesn't matter, but it's still the wrong type so you know

Fixes a mistake I did when datumizing admin topic

---

code/modules/detectivework/tools/rag.dm

1) Typo fixes
"The [name] try to smothers [target] with the damp rag, but blocked!"
changed into
"The [name] tries to smother [target] with the damp rag, but fails!"
"You try to smother [target] with the damp rag!"
changed to
"You try to smother [target] with the damp rag, but the mouth is covered!"
2) When someone just STARTS smothering another person, a message about the action appears in the chat (like with forcefeeding).
Before the fix,
1) it was unclear if you are smothering someone or their mouth is blocked.
2) Also, incorrect grammar.
3) Also, there was only a progress bar above the smotherer's head without a message about what's actually going on.
:cl:
fix: fixed grammar/notification for rag smothering actions.
/:cl:

Fixed typos for Damp Rag smothering actions

---

code/modules/mechs/mech_construction.dm

Adds more player feedback for installing things on mechs.
Me and another scientist were trying to figure out why some equipment wouldn't attach to a mech, as you can't exactly see what hardpoint restrictions there are on equipment, or software restrictions there are on a mech.
It would do the do_after, then drop to the floor, which felt pretty pointless.
:cl:
tweak: Attempting and failing to attach mech equipment to a mech now tells you why it failed to do so.
/:cl:

Mech equipment failure feedback

---

code/modules/reagents/machinery/chem_master.dm

due to a confusion/overlook i created a bug
"I tried making 10 u pills with 120 medicine, it said the maximum was 60u of volume per pill"
it is now fixed with one var change
fix for chemmaster bug ((not being able to make pills with a beaker that have more than 60u))
fix for chemmaster bug
fix: you can again make pills with a beaker filled with more than 60u (pills themselves cannot have more than 60 tho)
/:cl:

fix chemmaster bug (not being able to make pills with a beaker that have more than 60u)

---

code/game/objects/items/weapons/implant/implants/carrion/breeding_spider.dm

Adds a check so that you can't use multiple breeding spiders on a single corpse.
No more crashing the server from breeding spider spam.
:cl: TheShown
fix: Multiple breeding spiders can't be activated on the same body anymore.
/:cl:

Breeding spider bugfix

---

code/game/machinery/teleporter.dm
code/game/objects/items/weapons/circuitboards/machinery/research.dm
code/modules/research/designs/circuits.dm
code/modules/research/nodes/bluespace.dm
code/modules/telesci/bcrystal.dm

Spent a day revamping old gutted teleporter code to make it fully (dis)assemblable. 
Now you can assemble teleporter anywhere. Or disassemble one from MEO's office to go play telescientist early ingame. Up to you really. Demo [https://youtu.be/9itPC5xVsPI](https://youtu.be/9itPC5xVsPI)
p.s. sorry for the inconvenience of recreating a pull request, after fork. This is my first time working with this system.
:cl:
code: changed and refactored /code/game/machinery/teleporter.dm 
code: added circuitboards to /code/game/objects/items/weapons/circuitboards/machinery/research.dm component pricing is equal to NSV13
code: added design definitions to /code/modules/research/designs/circuits.dm 
tweak: /code/modules/research/nodes/bluespace.dm added both station and hub to research tree
tweak: lowered …

Teleporter changes

---

code/modules/clothing/spacesuits/captain.dm

Captain armor slowdown changed from 1 to 0.3. That's it.
Context: stats are now identical to traitor/junk bloodred voidsuit, still worse than Excelsior armor (which is faster and more armored) and Serbian SCAF (which is far more armored). Now has same speed as IH/Techno voidsuit and NT armor, but with better protection (because Captain).
Captain armor is currently a joke deathtrap that nobody uses unless they happen to be inside of Captain's bedroom when the bridge is hit by a meteor and there is literally no other option, because for some reason it was more or less left behind when all voidsuits were buffed from being based around default 1 slowdown to the current default of 0.3. Captain armor at 0.3 slowdown may be a bit too fast (hard to judge without live gameplay), but 1 is comically …

Lowers slowdown on Captain Armor to default voidsuit value

---

code/modules/mob/living/carbon/human/human_defense.dm

Can't test this at the moment but this fix, in theory, will work.
Issue:
----
In human_defense.dm
After C is defined (as obj/item/clothing) it is calling a proc that doesn't exist inside of its scope twice ( getRating() ) .
getRating() exists in /datum/armor not obj/item/clothing
My fix:
-----
Mimics the function of getRating() in this place by just doing vars[] instead since getRating is basically just vars[]
:cl: Hopek
fix: In theory fixed the huge organ issue destroying the server
/:cl:

In theory fixes the huge organ issue destroying the server

---

code/modules/organs/external/damage.dm

Not sure why this isn't here since it checks for "owner" later in the file as well.
Runtime:

Fixes runtime in organ damage code

---

code/game/objects/items/weapons/mine.dm

fixes mine bugs
and hitting a armed mine will explode it. to please don't try to pick up armed pressure sensitive mines
fixes mine bugs
picking up armed pressure sensitive mines are now bad, as it should be
:cl: Fernandos33
add: Hitting a armed mine will make it explode
fix: fixes mine bugs
/:cl:

fixed now you can't pick it up. and

---

code/modules/reagents/machinery/chem_dispenser.dm

Saw that there was a admin chem dispenser, yet it lacked a couple medicines that a cheat dispenser really should have. Had a couple extra minutes on my hands, so I figured I'd update it. Also gave it a more descriptive atompath, name, and description.
Obviously incredibly unbalanced, but also unobtainable unless an admin spawns it. Mostly used for testing or for the admins to make Moebious Medical obsolete at the press of a button.
Consistency for the admin dispenser, mostly. It's nice for testing out chems on localhost, this makes it a bit easier to do that.
Let me know if I missed any medicines - I intentionally chose to leave out QuickClot, since internal bleeding doesn't exist. At least, according to the wiki. If QuickClot is actually useful, lemme know and I'll throw that in too. …

Admin Chem Dispenser update and touchup

---

code/game/machinery/cryopod.dm

Bug: 
When clothes get changed inside of the Cryopod (a custom clothing loadout for example), the items get dumped on the ground. Since the cryopod is closed during this, this means that the contents are now inside the cryopod. The re-equipping code doesn't check for the contents of objects so it didn't put those back on the occupant.
This also happens to be a feature as well!
It is more efficient to do this check here vs where the initial re-equipping loadout uniform happens since doing it here means that other instances of items being left in the pod will be addressed instead of just on clothing changes.
:cl: Hopek
add: The cryopod will now attempt to give your items back on eject if you leave items inside of the pod.
fix: fixed a re-equipping bug where it left your items (Such as the …

Items left inside the cryopod will come back to occupant on eject.

---

code/datums/autolathe/circuits.dm
code/datums/autolathe/computer_parts.dm
code/datums/autolathe/security.dm
code/game/objects/items/devices/whistle.dm
code/game/objects/items/weapons/autolathe_disks.dm

Adds a Hailer design for the Ironhammer misc pack and the Aester's device disks
Adds an Industrial Grinder board design to the Technomancer's circuit disk
Adds medical and reagent scanners modules for PDAs to the Moebius computer parts disk.
Tweaks the license cost of two boards in the circuit disk (3 license uses for a Disk Cloner board and 2 license uses for an Industrial Grinder board)
(Yes, I am aware that the Hailer in that picture says "silencer", forgot to change the label when I compiled before testing it. It's properly labeled in this PR)
All tested.
1- Currently, it rather fucking impossible to craft loudmouth grenades since there's no viable way of getting hailers
2- Industrial grinders can benefit ghetto chem labs made by vagabonds and NT Agrolytes that want to get chems out …

Adds few designs to Circuits, IH, Computer parts and Devices disks

---

code/game/objects/items/weapons/implant/implants/carrion/control_spider.dm
code/modules/organs/internal/carrion.dm

Changes the carrion healing proc from aheal to rejuvinate with extra changes for missing limbs, to hopefuly fix some bugs and randomizes control spider duration.
Bugs are bad, and some strange stuff can be done with perfectly timed control spiders.
:cl: TheShown
balance: control spider duration is no longer exactly 1 minute, but randomized from 45 to 70 seconds.
code: revive() proc from carrion regen stasis changed to rejuvinate().
/:cl:

Carrion regen change and control spider timer randomisation.

---

code/__DEFINES/components.dm
code/__DEFINES/qdel.dm
code/__DEFINES/subsystems.dm
code/__HELPERS/logging.dm
code/controllers/subsystems/garbage.dm

In hopes of fixing major problems of the game crashing at high players count and long hours rounds, I quickly ported the TG's GC from https://github.com/tgstation/tgstation/
It should stop MC from panicking and die on the spot.
:cl:
code: Added new fresh GC code
refactor: Ported GC from tgstation
/:cl:

[Porting] Initial TG Garbage porting

---

code/ATMOSPHERICS/components/binary_devices/passive_gate.dm
code/ATMOSPHERICS/components/binary_devices/pump.dm
code/ATMOSPHERICS/components/omni_devices/filter.dm
code/ATMOSPHERICS/components/omni_devices/mixer.dm
code/ATMOSPHERICS/components/omni_devices/omni_base.dm
code/ATMOSPHERICS/pipes.dm
code/game/machinery/alarm.dm
code/modules/admin/admin_investigate.dm
code/modules/reagents/machinery/chem_dispenser.dm
code/modules/reagents/reagent_containers.dm
code/modules/reagents/reagent_containers/glass.dm

Adds 2 new tabs to the investigation admin verb, based on /tg/ investigations.
Admins should be able to track grief easier, while not clogging up the logs.
:cl:
admin: expands investigations to include atmos and chemistry information.
/:cl:

Atmos and chemisty investrigation

---

code/modules/mining/machine_processing.dm
code/modules/mining/ore_datum.dm

plasteel no longer makes an extra piece of plasma ore into slag
the ore processor picks ore up off the ground faster
i do not enjoy having my perfectly good plasma turned into slag
also slow pickups are cringe and controllable ore processing speed would be nice but that's out of scope of this fix
:cl:
fix: Plasteel now alloys properly without extra conversion of plasma ore into slag.
tweak: The ore processor on the Hulk no longer has a limiter on how much ore it can pick up per tick.
/:cl:

processor pickup buff, plasma slag fix

---

code/__HELPERS/logging.dm
code/controllers/master.dm
code/controllers/subsystems.dm
code/controllers/subsystems/garbage.dm
code/modules/admin/verbs/debug.dm

Adds the debug verb "Display del() Log" and fixes the output of logging for readability. Ports the code from https://github.com/tgstation/tgstation/pull/30118
Additional porting might be done by following up with https://github.com/PolarisSS13/Polaris/pull/4463 and also important : https://github.com/tgstation/tgstation/pull/31494 and https://github.com/tgstation/tgstation/pull/32022
To help admins and coders debug the GC for any problems making qdel very slow on objs.
:cl:
admin: Added debug verb "Display del() Log"
server: Minor change in qdel file logging
/:cl:

[Porting] Updating GC with one new debug verb from tg and minor change to file logging

---

maps/submaps/dungeon_rooms/rooms/armory_secure.dmm

This thing has been causing log spam for the past year. 
Stops admin logs from being spammed.
:cl:
admin: fixed admin issue regarding log spam
/:cl:

Removes a mob spawner from one of the One Star dungeon rooms

---

code/datums/topic/admin.dm
code/modules/admin/player_notes.dm

Root kinda broke when he changed from "<<" to to_chat without thinking there's file handlers that only works with <<
I might fix the to_chat so it can also work with files as well.
Admins gets to put notes on players or kick them out of game.
:cl:
fix: Admin kick and notes.
/:cl:

[FIX] The admin kick and notes

---

code/modules/mechs/mech.dm
code/modules/xgm/xgm_gas_mixture.dm

Works now if you're running through extools or VS code.
Only an issue because these runtimes pause the whole application on boot.
Also should in theory help memory usage if sharer doesn't exist in gas mixture which for some reason I encountered.
:cl: Hopek
code: You can now compile and run the codebase through VS code or extools without errors on start.
/:cl:

You can now compile and run the codebase through VS code or extools without errors on start.

---

cev_eris.dme
code/game/machinery/embedded_controller/docking_program.dm
code/game/machinery/embedded_controller/simple_docking_controller.dm
code/game/machinery/embedded_controller/~docking_program_undef.dm

Adds a frustration limit to undocking, where a ship will auto-undock after 5 failed attempts for the server-side dock to respond correctly.
It makes sense that, if you fuck up a ships docking door, it won't be able to undock, but a ship should be able to undock if there is an issue with the port it is docked to (Emergency undocking)
:cl:
tweak: After 5 failed attempts to undock, a ship will auto undock regardless of the condition of the port it is docked to.
/:cl:

Pod undocking fix

---

code/game/machinery/cryopod.dm
code/modules/client/preferences_spawnpoints.dm

Who knew some typo merged 2 years ago would come back to haunt me!
(That or an attempt at a lazy workaround since usr isn't defined when eject() is called indirectly)
**Cause:**
When you go afk in a cryopod when spawning in; go_out() is called.
When go_out()  is called instead of eject()  it bypasses all the logic in eject() meaning that the cryopod eats the items and doesn't give them back.
This is bad because we need the cryopod to give the items back to people spawning in.
:cl: Hopek
fix: fixed cryopods ignoring logic and not giving items back when the occupant went afk on spawn for longer than a minute.
/:cl:

Fixes the cryopod not following logic when occupant is afk

---

code/modules/mechs/mech.dm

Testing by loading it up multiple times on a loop there are instances where src exists here without loc on boot.
No idea what causes this but for me it seems to happen about once every 6 boots and sometimes multiple times in a row.
Works fine after this change.
Fingers crossed this is the last modification.

Booting with extools and VsCode part 2

---

code/game/objects/items/weapons/circuitboards/circuitboard.dm

**Before:**
------
**After:**
-----
:cl: Hopek
add: Circuit boards now display required components when examined.
/:cl:

Circuit boards now display required components when examined.

---

code/modules/client/preference_setup/loadout/lists/utility.dm

**Why:**
At the moment in order to get started with improvised tools you need adhesive.
You cannot get adhesive unless you go to the public autolathe or get really lucky meaning that you cannot start making improvised tools without leaving maintenance if you spawn as a vagabond.
The point of improvised tools is to be able to make them without relying on the autolathe to start out.
Yes; I know you can make the spider web tape but the recipe for it is not accessible to someone without tools or weapons (probably needs a separate PR to change that)
:cl: Hopek
add: You can now spawn with duct tape for 3 loadout points because at the moment you cannot get adhesive unless you go to the public autolathe or get really lucky defeating the point of current improvised tools.
/:cl:

You can now spawn with duct tape

---

code/modules/mob/mob_helpers.dm

This happens when something without stats sets off a trap
Returns no skill as intended.

Fixes runtime in mob_helpers.dm

---

code/modules/mob/living/silicon/robot/robot_modules.dm

Increases speed for custodial (cleaning) module from 0.85 to 1.0 because its so slow, no one would ever pick it to clean up the ship.
Current custodial module is too slow to be useful on the giant mess of a ship.
:cl:
balance: increased custodial cyborg module speed to 1.0
code: changes in robot_module.dm
/:cl:

[BALANCE] Increases the custodial module speed from 0.85 to 1.0

---

code/modules/economy/cash.dm

Catch-all fix for the money when it gets deleted but the user could retain the split dialog. This stops from being duped after being put in ATM.
:cl:
fix: Makes sure duping money method is extra dead.
/:cl:

Money fix final fix

---

code/modules/economy/price_list.dm
code/modules/mob/mob_helpers.dm
code/modules/reagents/holder.dm
code/modules/reagents/reagents.dm

Also fix the logic of the proc "skill_to_evade_traps" that someone has broken trying to fix.
:cl:
fix: skill_to_evade_traps logic
fix: reagent containers no longer have the same value as the entire multiverse.
/:cl:

Makes the cargo code less shitty

---

code/game/machinery/doors/windowdoor.dm

Previously, it would attempt to send the user as the item argument for an attackby, when something that wasn't human attack_handed a windoor (Such as AIs and robots). This is poor coding standard.
Now, it uses a new function, attempt_open(), on attack_hand, and attackby.
AIs and other silicons can now interact with windoors.
:cl:
fix: Fixes silicons not being able to interact with windoors.
/:cl:

Reorders windoor code to prevent a runtime and poor code.

---

code/modules/overmap/ships/computers/helm.dm

This is, like, the tenth time someone is confused why overmap console is failing silently.
I added a message that displays when you try to access helm console, but overmap is disabled in config, and you have an admin rank.

Adds a message that explains why overmap doesn't work on local

---

code/game/objects/items/weapons/mine.dm
code/game/objects/items/weapons/traps.dm

This PR fixes bear traps and mines being able to be placed onto ladder turfs
Gamey combat exploits are dumb and this is an order from gray
:cl:
fix: fixed bear traps and mines being able to be placed onto ladder turfs
/:cl:

fixes beartraps and mines being able to be placed on ladder tiles

---

code/game/gamemodes/events/weather/rad_storm.dm

this PR fixes radstorms affecting areas of limited to no coverage against rad storms, which prolonged exposure will almost certainly lead to death.
fixes good, this was ordered by Gray
:cl:
fix: fixed radstorms affecting encounter maps, like the mine, asteroid belt, space fortress
/:cl:

fixes rad storms affecting encounter maps

---

code/modules/mob/language/german.dm

With Changeling gone, the "g" language prefix is no longer in regular use. The current prefix, ,d, is already in use by both drones and blitzshells and is preventing carbon mobs from being able to use that prefix.
Not having to use the language menu constantly to use a language is always a plus.
:cl:
tweak: The prefix to speak in German is now ,g
/:cl:

German now uses the "g" prefix

---

code/datums/craft/recipes/misc.dm
code/game/machinery/kitchen/smartfridge.dm
maps/CEVEris/_CEV_Eris.dmm

this maps drying rack to NT garden, drying rack needs to undergo further testing but if people tell me the code is working. the mapping is done
well.. lets you dry stuff to smoke
boosts the speed to dry stuff (from  0.005 to 0.1) we don't need to wait half a hour to dry things
new recipe to create the smoking pipe
add: drying rack added to NT garden
add: recipe to create smoking pipe. (5 wood, and something that can cut)
tweak: drying rack now dry stuff faster (from almost an hour before. to a couple of seconds npw)
/:cl:

maps drying rack to NT garden, and public garden

---

code/modules/mob/living/carbon/human/human.dm

:cl:
tweak: revive proc no longer destroys organs, it only heals them.
fix: revive proc no longer causes the target to lose their cruciform.
/:cl:

[BOUNTY] revive proc no longer causes the target to lose their cruciform.

---

code/game/objects/items/weapons/autolathe_disks.dm
code/game/objects/items/weapons/storage/belt.dm
code/modules/reagents/reagent_containers/food/snacks.dm
code/modules/reagents/reagent_containers/syringes.dm

large syringe now uses 1 silver. and is in Moebius Medical Designs" (20 liscense points)
typo in the "taste like"
EMT now can hold everything that regular medical belt does, except for the blood bag plus:
crowbar
mini extinguisher
and flashlight,
that medical belt can now hold bloodbags
and both are able to hold glasses and gloves to make surgery swaps easier, if you wanna go for that
large syringe now uses 1 silver. and in Moebius Medical Designs" (20 liscense points)
typo in the "taste like"
gives medical belts and EMT belts some more unique stuff
fixes
picking up one belt or the other should be more of a choice now
balance: large syringe now uses 1 silver. and is in Moebius Medical Designs" (20 liscense points)
fix: typo in the "THIS taste like"
add: EMT now holds, …

large syringe price change. and typo in tastes, amd Emt plus medical belt changes

---

code/modules/tables/presets.dm

:cl: Hopek
/:cl: Fixed tables in onestar ruins being labled "onestar" instead of "onestar table"

Fixed tables in onestar ruins being labled "onestar" not "onestar table"

---

code/game/gamemodes/events/infestation.dm

I've been told a few times that the bay animals are wasted on an infestation event, as they provide nothing to the round. Most of the ones removed don't even fit the setting.
Less points wasted on NPCs that can't be butchered or interacted with in a meaningful way.
:cl:
del: Lizards, Yithians, Tindalos, Diyaabs, Samaks, and Shantaks have been removed from the infestation event.
/:cl:

Removes poorly-implemented bay animals from the infestation event.

---

code/modules/mob/inventory/equip.dm
code/modules/mob/living/carbon/human/inventory.dm
interface/interface.dm
interface/skin.dmf

This PR adds QoL hotkeys to add things to storage easily
Massive Quality of Life feature that was not in here that should have been
:cl:
add: You can now put items easily into your backpack with E and into your belt with Shift E
/:cl:

[BOUNTY] QoL: Press E to put in backpack . Press shift + e to put things in your belt

---

code/modules/ghosttrap/trap.dm
code/modules/mob/living/carbon/brain/posibrain.dm

Posibrains will now inform
- Deadchat about whether they can use a posibrain (which includes if they can respawn and if they are jobbanned)
- Ghosts that use it whether they are eligible to play it (which includes if the posibrain is currently active and searching for ghosts, if the player can respawn and if the player is jobbanned)
:cl:
tweak: Players will now receive more feedback regarding their eligibility to use posibrains. Remember that you have to be able to respawn as a crewmember before you can become a robot!
/:cl:

[BOUNTY] Posibrains now give more feedback regarding player eligibility to aspiring ghosts

---

code/modules/projectiles/gun_firemode.dm
code/modules/projectiles/guns/energy/plasma.dm

Switching firemode on energy weapons now checks for equipped gunmods and applies their effects properly.
Remove cassad with battery shunt meme (switching firemode with battery shunt gave you a cassad with classic number of shots but with vastly increased firerate)
:cl: Hyperio
fix: Fixed firemode change that was erasing charge_cost and fire_delay of gunmods
/:cl:

Fix firemode change that was erasing effects of gunmods

---

code/modules/reagents/machinery/chem_dispenser.dm

:cl:
fix: fix drag beakers to chem master
/:cl:

[BOUNTY] Bug: fix drag beakers to chem master

---

code/modules/mob/living/living_defense.dm

:cl:
fix: armor spam messages
/:cl:

[BOUNTY] Bug: Armor message spam

---

code/datums/autolathe/guns.dm

Simply moves the Mandella up on the list and corrects its name being .35 to .25 as thats its caliber 
Simple miss-caliber correct, help against confusion
:cl:
fix: Fixed the .25 Mandella being called .35 in its linense
/:cl:

Corrects Mandella's design calling it a .35 when its a .25

---

code/modules/power/supermatter/supermatter.dm

Lazy fix vs finding exactly why the 0 is created and painstakingly making sure it will never become zero but it'll work.
:cl: Hopek
fix: The SM no longer divides by zero creating thousands of runtime errors
/:cl:

Fixes lots of divided by zero SM runtimes

---

code/game/objects/structures/medical_stand.dm

:cl: Hopek
fix: The medical stand no longer runtimes a few thousand times per round.
/:cl:

Fixes repeating medical_stand.dm runtime

---

code/game/objects/items/weapons/storage/belt.dm

Removes "can_hold" on the EMT belt, put it to a few extra items. Removed fun away from the medical belt, like being able to hold all clothing subtypes for gloves and glasses. Removed additional redundant entries on the list.
Removing fun is a tested and true design strategy, full /tg/-approval for these changes.
:cl:
balance: Medical belts may only hold latex and medical HUDs.
/:cl:

EMT Belt Redux

---

code/datums/craft/step.dm

Silly of me to assume that single-item crafting steps wouldn't use req_amount
Reverts a change I made to req_amount in crafting steps, it no longer fails if the object in question is not a stack.
You can craft shivs again.

Crafting hotfix

---

code/modules/organs/external/_external.dm

Fixes bones being made of paper
Previously, due to the inline and the compiler being dumb, rather than doing math, it would return 1 instead, so your bones would effectively have 1HP
People can't explode into a million pieces from slipping on a banana peel

Bone hotfix

---

code/__DEFINES/spawner.dm
code/game/objects/items/weapons/tools/_tools.dm
code/game/objects/items/weapons/tools/crowbars.dm
code/game/objects/items/weapons/tools/hammer.dm
code/game/objects/items/weapons/tools/mods/mod_types.dm
code/game/objects/items/weapons/tools/saws.dm
code/game/objects/items/weapons/tools/scalpels.dm
code/game/objects/items/weapons/tools/screwdrivers.dm
code/game/objects/items/weapons/tools/shovel.dm
code/game/objects/items/weapons/tools/tape.dm
code/game/objects/items/weapons/tools/weldingtools.dm
code/game/objects/items/weapons/tools/wirecutters.dm
code/game/objects/items/weapons/tools/wrenches.dm
code/game/objects/random/tools.dm
code/modules/research/experiment.dm

Tool spawner will no longer spawn only from a list of duct tape. Circular saws will no longer dominate places where surgical tools randomly spawn.
Tool spawners will no longer spawn items with the "junk" tag. Added junk tag to all improvised tools.
Adjusted various rarity values on tools, and removed reinforced plating's lower rarity value.
Better, more varied, item spawns.
:cl:
tweak: Tool spawners will no longer spawn items with the "junk" tag. Added junk tag to all improvised tools.
balance: Adjusted various rarity values on tools, and removed reinforced plating's lower rarity value.
fix: Tool spawner will no longer spawn only from a list of duct tape. Circular saws will no longer dominate places where surgical tools randomly spawn.
/:cl:

Tool spawn tweaks

---

code/modules/organs/internal/bones.dm

With the addition of bones, prosthesis gained a biomatter requirement.
The exofab can not accept biomatter, so this issue caused prosthesis to be impossible to print.

Fixes prosthesis printing requiring biomatter

---

code/game/machinery/bluespacerelay.dm

Because of BYOND updating icon_state even if the value doesn't change means that the sprite icon refreshes.
So running this on process() means that the icon updates over and over when nothing happens.
As far as I know, doing these extra checks should be much more efficient than updating the icon on every process tick.

Doesn't update the bluespace relay icon when not needed.

---

code/modules/stashes/stash_types/excelsior.dm

Removes the excelsior teleporter board from random excel stashes.
Excelsior teleporter invalidates 90% of the ship. This way the only way to get an excel teleporter is through raiding an actual excel base.
:cl:
balance: The excelsior teleporter board no longer shows up in randomly generated excel stashes.
/:cl:

Removes the excel teleporter from random excel stashes

---

code/game/objects/items/weapons/tools/_tools.dm
code/modules/organs/internal/eyes.dm

No longer will welding tools manipulate your genetics
Using a tool that requires eye protection (Welding tools primarily) used to flick disabilities on and off to emulate flash-blindness. Now it no longer does this, so the eye can handle its own damages
The disability flickings only cure was to genemod yourself. Not something easily done, or intuitive to fix welder-eye.
Now, it can be treated through imidazoline, eye repair surgery, or eye switching surgery.
:cl:
tweak: Welder eye damage now can be treated through surgery or imidazoline.
/:cl:

Welding eye fix

---

code/modules/projectiles/projectile/beams.dm

Stun guns now take account burn(energy) armor and as compensation they get a whopping 1 burn damage.
left(naked)(slight delay on refreshing hallos) / right(techno voidsuit)(30% energy) - NT SP "Counselor" used for tests
Making armor choice apply to stun guns is cool, also no more dual wielding 60 hitscan damage a hit with small guns.
:cl: TheShown
balance: stun beams don't bypass armor anymore
/:cl:

Stun guns now don't ignore armor.

---

maps/submaps/dungeon_rooms/rooms/1.dmm
maps/submaps/dungeon_rooms/rooms/Escape_Pod_West-East.dmm
maps/submaps/dungeon_rooms/rooms/Hallway_4way.dmm
maps/submaps/dungeon_rooms/rooms/Hallway_North-South.dmm
maps/submaps/dungeon_rooms/rooms/anomaly.dmm
maps/submaps/dungeon_rooms/rooms/armory.dmm
maps/submaps/dungeon_rooms/rooms/armory_secure.dmm
maps/submaps/dungeon_rooms/rooms/autolathe_South-East.dmm
maps/submaps/dungeon_rooms/rooms/cargo_horizontal.dmm
maps/submaps/dungeon_rooms/rooms/cargo_vertical.dmm
maps/submaps/dungeon_rooms/rooms/checkpoint_horizontal.dmm
maps/submaps/dungeon_rooms/rooms/checkpoint_vertical.dmm
maps/submaps/dungeon_rooms/rooms/crematorium.dmm
maps/submaps/dungeon_rooms/rooms/garden.dmm
maps/submaps/dungeon_rooms/rooms/hallway_West-East.dmm
maps/submaps/dungeon_rooms/rooms/hallway_executive.dmm
maps/submaps/dungeon_rooms/rooms/hallway_storage.dmm
maps/submaps/dungeon_rooms/rooms/hallwayatmos_west-east.dmm
maps/submaps/dungeon_rooms/rooms/mechbay.dmm
maps/submaps/dungeon_rooms/rooms/office.dmm
maps/submaps/dungeon_rooms/rooms/penitentiary.dmm
maps/submaps/dungeon_rooms/rooms/refinery.dmm
maps/submaps/dungeon_rooms/rooms/secure_storage_horizontal.dmm
maps/submaps/dungeon_rooms/rooms/shootingrange.dmm
maps/submaps/dungeon_rooms/rooms/showers.dmm
maps/submaps/dungeon_rooms/rooms/surgery.dmm

This PR re-adds roombas as they were meant to be implemented but by a mapping typo were left off the dungeon rooms; the most rudimentary form of roomba is harmless as it nuzzles enthusiastically, but its unslowing approach adds more health to the robotic swarm of much meaner roombas. I clean my hands of any balance related injuries as explosive landmine roombas hide amongst their ranks, able to explode; as i simply repaired the code to where they would spawn anyway, and other people would have a much intuition of whether its fair.
My most functional advice is to bring anti-robotic tailored equipment and try not to get caught in a corner. The dungeon doesn't have any doors to hide behind and some tight corners. Stay alert.
- I have not been able to try this successfully when i have …

Fixes some DMM code, instigates Roomba re-emergence in dungeon rooms.

---

code/modules/power/lighting.dm

You can now replace broken lights by clicking them with a new light. There is also some new spans on some messages, and some consistency changes to light fixture examine.
It reduces the amount of annoying inventory tetris you need to do to replace lights manually.
:cl: ACCount
tweak: You can now replace broken lights by clicking them with a new light
/:cl:

You can now replace broken lights by clicking them with a new light

---

code/game/objects/items/weapons/grenades/flashbang.dm

Flashbangs have the `weaken` on the bang proc connected to ear protection removed and the `stun` reduced by 50%. `weaken` and `stun` on the check related to eye protection remain the same. 
Ear protection is almost non-existant in the game, and even *with* ear protection people could stll get knocked down.
:cl: TheShown
balance: Flashbangs no longer knockdown people with eye protection, and the stun on people with eye protection has been further reduced.
/:cl:

Flashbang sound stun nerf

---

code/game/objects/items/weapons/grenades/grenade.dm
code/modules/mob/living/carbon/carbon.dm
code/modules/mob/living/carbon/carbon_defines.dm
code/modules/mob/living/carbon/human/human_defines.dm
code/modules/mob/living/carbon/human/life.dm
code/modules/multiz/structures.dm

This PR adds the ability to see down and up ladders and also see down and up stairs by Alt Clicking the multiz structure 
This PR also adds the ability to thrown items up and down ladders by clicking on the ladder with the item
This PR has been heavily tested for ways to break the code and mess with planes
This completely destroys the z-level transverse camping that was possible before, in which you could wait for someone, and instantly open fire and kill them before they could know what was going on. Also the new functionality for  items
:cl:
add: You can now see down and up ladders, and up and down stairs by alt clicking the zlevel change structure, whether it be a ladder or a stair
add: You can now throw items up and down ladders by clicking on the ladder with the item inhand (grenades …

Ladder peeking and grenade throwing

---

code/modules/admin/verbs/randomverbs.dm

VV drop everything now only dropes equiped items (and not organs).
Bug bad and admins can instantly ERP now without needing to take off clothes without the fear of losing their organs.
:cl: TheShown
admin: Drop everything in VV does not drop EVERYTHING including organs anymore.
/:cl:

VV drop everything fix

---

code/modules/trade/datums/trade_stations_presets/zarya.dm

You can now gamble a small amount of cash at the Zarya to get a random design disk for autolathes. This uses the same spawner for non-advanced design disks, so you're not going to get anything amazing - and it's possible you'll pull a dud, such as an Asters Tool Pack or Moebius Medical disk.
In order for Cargo to get any good disks to print stuff from, they need to buy from vagabonds or get lucky when a techie is poking through maint. You still need to poke around in maintenance for the advanced disks, but you can at least get some decent ones by buying from the trade beacons.
It also encourages trade beacon use instead of using the shuttle, which is good.
Pictured above is me asking a maintainer if this was okay.
:cl:
add: You can now buy autolathe design disks from the 'Zarya' in the …

Random Design Disks from Trade Beacons

---

code/modules/mob/living/silicon/robot/robot_modules.dm

Not sure how this went unnoticed
Fix
:cl:
fix: Construction borgs can use regular glass 
/:cl:

Construction borgs can use regular glass

---

code/game/objects/items/weapons/circuitboards/machinery/chemestry.dm

Forgot to rename the boards - Woops
Small bug that slipped through the cracks. 
Thought I made them all subtypes of one a other but that seems not to the the case leading to this small but annoying error
My bad, sorry.
:cl:
fix: Chem dispenders now have different boards again
/:cl:

Quick circuit board fix

---

code/modules/modular_computers/file_system/catalog.dm

Previously, you could only search for the drink name, and how strong it was. This didn't prove very useful in narrowing down what a customer would want, as the new sanity system wants things of a certain taste, not of a certain name.
As people come by to ask for bitter, or sweet, or spicy drinks, you can now search by that given descript.
:cl:
add: You can now search by taste type in the neon cocktails catalogue
/:cl:

You can now search the neon cocktails drinklist by taste tag

---

code/game/objects/items/weapons/autolathe_disks.dm

Somebody forgot to give robustcell disks a rarity, so they never spawned.
It's good to have things that you want to spawn actually spawn.
:cl:
fix: The 'Asters Robustcells' disk should now correctly spawn wherever common design disks would be found.
/:cl:

Makes Robustcell disks actually spawn again

---

code/game/objects/items/weapons/autolathe_disks.dm

would have included this in previous bugfix pr if i wasn't blind
already got approval from Lucario here - 
things spawning is very good and based
:cl:
fix: The autolathe disk "Technomancers IJIRO-451 Advanced Tools" should now correctly spawn wherever common disks may be found, albeit rarely.
/:cl:

advanced tool disks actually spawn now

---

code/game/objects/items/weapons/tools/wrenches.dm

There was little reason to pick up a big wrench over a normal wrench, as there's no real failure with bolt turning.
Now you can clonk somebody with a big wrench.
:cl:
tweak: The big wrench now does more damage than a normal wrench
/:cl:

Big wrenches now do big damage

---

cev_eris.dme
code/game/objects/items/weapons/circuitboards/machinery/chemistry.dm
code/modules/reagents/machinery/chem_dispenser.dm
code/modules/research/designs/circuits.dm
code/modules/research/nodes/biotech.dm

Fixes the inability to construct soda, beer, and industrial chem dispensers
Makes the circuitboards a child of the chem dispenser board, as they all copypasted the same thing anyway.
Fixes a typo in the chemistry board filename
Being able to build an automatic beer dispenser is a sovereign right of all spessmen
:cl:
fix: Soda, beer, and industrial chem dispensers can now be built again.
/:cl:

Soda, beer, and industrial chem dispenser fixes

---

code/game/objects/structures/window.dm
maps/CEVEris/_CEV_Eris.dmm

Reinforces the medical lobby doors, so it's not the preferred method of brute-entry. (You now have to get above 20 damage with a melee weapon to deal damage to them. Previously it was 8 damage.)
Adds some buttons to the medical front desk, so desk-operators can allow people access to the front areas with ease.
Changes some wiring around, so the reception APC cable doesn't lead from the lobby area needlessly.
Fixes a bug with plasma windows becoming invisible (Unatomic, but I was planning on adding plasma windows to the front desk until we realized that was just going to be negative gameplay.)
The medbay doors were so weak, they could be broken before a doctor comes from a screen away to actually open it.
:cl:
balance: The medbay doors have now been reinforced, after complaints from …

Medical lobby tweaks

---

code/modules/projectiles/ammunition/bullets.dm
code/modules/projectiles/guns/launcher/projectile_grenade_launcher.dm

The China Lake can now be found (extremely rarely) wherever a projectile gun can be found. It's ammunition (rubber grenade shells, explosive grenade shells, or frag grenade shells) can now be found (rarely) wherever ammunition can be found.
Gray and Reere told me to do this
:cl:
tweak: The China Lake and it's specialized ammunition should now correctly spawn in places across the ship.
/:cl:

China Lake and it's ammo can now be found

---

code/modules/mob/living/simple_animal/hostile/hostile.dm
code/modules/mob/living/simple_animal/hostile/megafauna/hivetechboss.dm
code/modules/mob/living/simple_animal/hostile/megafauna/megafauna.dm

Fixes the tyrant destroying half the ship on death
Removes redundant checks
Removes redundant walk(src,0) calls
Fixes the tyrant from stopping time every time it shit talks you, and then embedding you with 80 ~~knives~~ globs of goo
AAAAAAAAAAAAA asked me for a little help on fixing the tyrant, so I fixed some surface-level bugs.
- The tyrant, on death, is supposed to kill all hivemind-controlled machines on the ship. Issue was it called qdel() rather than node.destruct, so it would also destroy the underlying machines.
- The tyrant, in combat, mocks people every 3~5 seconds. Issue is it sleeps for this amount of time, which would also sleep the entire Mob subsystem. Same goes for it firing projectiles
- It would call the usual hostile attack chain within its own Life(), after previously …

Hivemind tyrant fixes

---

code/game/objects/items/weapons/autolathe_disks.dm

( everything is way too common )
These disks are supposed to be uncommon or rare, not omnipresent
:cl:
tweak: Armor design disks no longer dominate disk spawns.
/:cl:

Makes armor disks way rarer

---

code/game/gamemodes/roleset/simple.dm
code/game/gamemodes/storyevent.dm

When making the blitzshell to specification, I accidentally overlooked some things when making the storyteller roleset, as I was unfamiliar with it.
- Blitzshells now only spawn if there are 10 or more people, along with a requirement for some leve of security, so there are potentially enough people to deal with them, considering how lethal they can be.
- Blitzshell storyteller event is now less likely to fire, as it does not contribute as much to the round as traitors/excel/carrion.
Blitzshells do not contribute as much to the round as in-station antagonists, so should have less of a chance to spawn than traitors/excel/carrion, and require a certain amount of people to wrangle, security namely.
:cl:
balance: Blitzshells are now less likely to spawn
/:cl:

Makes blitzshells rarer

---

code/modules/power/cell.dm

Having a high enough mechanical skill can tell you if a cell is rigged or not
Might as well have a practical use for mechanical skills when scavving
:cl:
tweak: Having a high enough mechanical skill can tell you if a cell is rigged to explode on use.
/:cl:

Cell rig examine

---

code/game/objects/items/weapons/grenades/flashbang.dm

Flashbangs no longer floor you, instead they render you blind, deaf, and confused
Flashbangs no longer weaken and stun you when detonated. Instead, they blind you if you lack proper eye protection, apply the usual deafening effect they had previously, and now debuff your stats for a short time while you recover.
Being able to 1-second slap stun somebody for 10 seconds is a little anticlimatic. This change would prompt people to time their grenades properly, and actually breach and clear with them.
:cl:
balance: Flashbangs no longer floor you, instead they disorient you.
/:cl:

Flashbang balance change

---

code/modules/multiz/turf.dm

When the best method of disabling a serbian mercenary is to drop crayons on their head, you have to question the balance.
This pull request adds a helmet armor check when dropping an item on somebody from a height, so you can't stunlock somebody by throwing individual playing cards on people, but you can if you drop a locker on them for instance.
After seeing people get stunned by a deck of cards, or food paste packets, while decked to the nines in combat armor, I felt it was time to take a look at what code was doing this.
It's still a viable tactic to disable somebody, just now a little more sane.
:cl:
balance: Helmets are now taken into account when stunning people by throwing things on top of them.
/:cl:

Nerfs stunning people by dropping things on them

---

code/modules/hydroponics/grown.dm

Fixes being unable to pick up stinging fruits when you have gloves or it is out of reagents
An agrolyte informed me that they couldn't pick up some stinging ambrosia while wearing gloves.
The cause was in the plants prepickup, if the plant had thorns, it would check for your gloves, or if it had no reagents. If so, it would return false.
Returning false on prepickup means you can't pick up the object. Incorrect logic.
Now ambitious agrolytes can actuate their agroculture
:cl:
fix: Stinging fruits can now be picked up if you are wearing gloves.
/:cl:

Stinging fruit fix

---

code/modules/mob/holder.dm

Animal holders would call release_mob on destruction if they still held a mob (perhaps somebody threw a mouse in the destructive analyzer, or an MBO with 40 rats in their backpack met an unfortunate end with some supermatter). 
Release_mob would then call qdel, which would call destruction again.
Let's not bully the garbage collector.
Less runtimes from poor logic

Fixes holders calling qdel in their destroy

---

code/modules/mob/living/carbon/human/species/species.dm
code/modules/mob/living/carbon/human/species/station/monkey.dm
code/modules/sanity/sanity_mob.dm

Removes on life sanity effects on NPC monkeys things like environment sanity gain and insight (player controled monkeys keep the full sanity effects) and makes on life sanity effects run once every 2 life ticks at double the effect.
Effects: (Tested with 15 roundstart monkeys and 1 player. Test was done before cutting the onLife() checks to once every 2 life ticks)
(without change)^
(with change)^
Optimization. Things like sanity damage from real damage or drugs are untouched, so in game effects should be minimal.
:cl:
tweak: NPC monkeys don't receive environment sanity damage and insight.
code: onLife() sanity procs effects trigger once every 2 life ticks.
/:cl:

Sanity optimizations

---

code/modules/research/experiment.dm

Nerfs the amount of research you gain from an autopsy, from 1000-2000 per unique weapon, to 50-100 per unique weapon.
Previously all you had to do was raid the morgue, steal the autopsy scanner, grab a monkey, and hit it with a toolbox and other assorted surgical equipment in order to max research.
Now, a cadaver will yield an average amount of research equivalent to an unresearched item, so it is better to inspect a vagabond who died an untimely but unique death, than beath a monkey to death with every item in the R&D lab. It's less the primary method of research acquisition, and now just another unique branch of research acquisition.
:cl:
balance: The amount of research points you receive from researching an autopsy report has been nerfed
/:cl:

Nerfs the amount of research points you gain from autopsies

---

code/game/objects/items/weapons/mine.dm

Previously, if you tried to take a planted mine in your hands, it exploded and another mine was added under the mob
Bug fix 🐱 
:cl:
fix: fixed double mine bug
/:cl:

double spawn mine fix

---

code/game/objects/items/weapons/implant/implants/carrion/control_spider.dm

Does what it says on the tin. Reduces the control spider duration from a maximum 75 seconds to a maximum of 20 seconds.
At the moment, control spiders are a complete death sentence. The carrion can literally just get you to commit suicide and end your round - and it only kills the carrion's shell, not the core.
This doesn't really fix that problem, but what it does do is make it far harder for the carrion to remotely slaughter people via control spider. 
Control spiders should be used for spreading bits of misinformation and starting conflicts between crew - not just used as a remote killswitch. 20 seconds is enough time for a carrion to dump a few shots into a crewmember's ally or to screech that a crewmember is killing them when they aren't. 70 seconds is more than enough time that a …

Knocks down control spider duration to 15-20 seconds

---

code/__DEFINES/weapons.dm
code/datums/datum_click_handlers.dm
code/modules/mob/living/living_defines.dm
code/modules/mob/living/recoil.dm
code/modules/projectiles/gun.dm

This PR changes recoil to be like in FPS games, so you can't keep clicking your target with single fire mode and don't get recoil. Also vig now increases penetration, ask Reere why. Damage when autofiring is lowered, you can ask Reere about that too.
Click handlers changed, so it will (possibly not) reduce lag when autofiring.
Recoil increases when firing with single fire modes. Also Reere requested this changes.
:cl:
code: Recoil will now act differently, reducing to zero after second without firing guns.
tweak: Vig now affects penetration, not recoil gains.
tweak: Autofire damage is slightly lower.
refactor: Full Auto click handler refactoring
/:cl:

Recoil and click handlers update

---

code/modules/mob/living/carbon/superior_animal/roach/types/bluespace.dm

Gives the bluespace roach a more fitting name to be in line with our other roaches.
It is now called 'Unbekannt Roach', which means 'Unknown Roach' in English. 
It was really weird how we had cool names for all other roaches, but bluespace roaches are just 'bluespace roaches'. This makes them look cooler and lets me flex a funny german word.
Also Reere said it was ok; 
:cl:
tweak: Bluespace Roaches now have a more immersive name and description.
/:cl:

Gives the Bluespace Roach a more immersive name and description

---

code/modules/projectiles/guns/energy/nt_svalinn.dm
code/modules/projectiles/guns/energy/plasma.dm

This PR fixes Svalinn and Brigador slot_flags and cleans a bit of Brigador code.
I'm unsure about why Svalinn can't be put into holster slot. Brigador is a child of "Dominion" which is a rifle that can't be put into holster, that's why it lacked those flags.
Put pistols into pistol holsters.
:cl:
fix: Brigador and Svalinn can be put into holster and belt slots.
/:cl:

Fix Brigador and Svalinn slots

---

code/game/machinery/portable_turret.dm

Fixes being able to dupe the installed weapon when deconstructing a turret - Previously it would runtime when creating a new gun to give to the player upon deconstruction, which would halt the deconstruction process short of destroying the turret, so you could deconstruct it again and again.
Fixes some weapons being terrible to install into a turret - Some weapons are heavily dependent on their firemodes to give them their unique attributes (projectile type, for instance). An example is the Cassad, whose projectile at initial is a no-damage laser, whereas its firemode gives it the light plasma projectile.
Being able to dupe a gun sucks, being unable to put a gun into a turret and have it work also sucks.
I may approach this in a different way, have the turrets physically fire the gun so …

Portaturret fixes

---

code/modules/projectiles/guns/projectile/pistol/colt.dm
code/modules/projectiles/guns/projectile/pistol/mk58.dm
code/modules/projectiles/guns/projectile/pistol/paco.dm

Adds high cap magazine support for colt, mk58 and paco.
Highcap magazines are used in very few guns, and with this they could be used for every .35 pistol except the giskard.
:cl:
add: Colt, mk58 and paco can use high cap magazines.
/:cl:

High cap magazines for .35 guns

---

code/game/machinery/alarm.dm
code/modules/power/apc.dm

You can lock/unlock Air alarm and APC using alt-click.
You don't need take off your PDA or ID card, just simple cool access
:cl:
add: You can lock/unlock APC and air alarm with alt-click
/:cl:

Alt click for APC and Air Alarm

---

code/controllers/subsystems/staverbs.dm
code/modules/research/rdconsole.dm

Adds new statverb to staverbs.dm, allowing hacking of R&D console permissions
Plays keyboard sound effect during interaction
Pass/fail, no dice roll, min 25 COG required
Also fixes some bad English in the rest of the file.
Allows junk addicts to start their own research projects in maintenance.
:cl:
add: added new statverb interaction for hacking R&D console permissions
fix: cleaned up grammar in the remove floortile statverb
/:cl:

Update staverbs.dm - adds new interaction for hacking R&D console permissions

---

code/modules/mob/living/carbon/superior_animal/giant_spider/giant_spider.dm
code/modules/mob/living/carbon/superior_animal/giant_spider/types/hunter.dm
code/modules/mob/living/carbon/superior_animal/giant_spider/types/nurse.dm

Gives our favorite spiders three new names, similar to how roaches have german names.
The guard spider is now the Senshi Spider, or the Warrior Spider.
The nurse spider is now the Kouchiku Spider, or the Building Spider.
The hunter spider is now the Sokuryou Spider, or the Scout Spider.
Gives the spiders more character, does something Reere had been planning to do anyways, and makes it a standard for all our insects to have non-english prefixes. Very nice.
:cl:
tweak: Giant spiders now have class-specific names and descriptions.
/:cl:

Gives spiders japanese names and descriptions

---

code/datums/mob_stats.dm
code/datums/perks/fate.dm
code/datums/perks/job.dm
code/datums/perks/oddity.dm
code/modules/client/preferences.dm
code/modules/core_implant/core_implant.dm
code/modules/core_implant/cruciform/machinery/cloning.dm
code/modules/core_implant/cruciform/modules.dm
code/modules/core_implant/module.dm
code/modules/mob/living/carbon/human/human.dm
code/modules/organs/external/_external.dm

Currently, the cruciform points towards the users stats holder. This can be deleted if the body itself is destroyed.
If the stats holder is deleted after a clone has been made, the clone starts to runtime out (Able to move at super speed, unable to die, unable to perform certain actions that depend on a perk)
NT shouldn't have access to making ubergolems
:cl:
fix: Fixes NT cloning turning people into statless power husks.
/:cl:

Fixes the NT cruciform's odd interaction with stat holders

---

code/game/machinery/telecomms/telecomunications.dm

This adds an examination override to telecomms machinery, that shows flavourtext depending on how much damage they have.
Trying to diagnose what is wrong with Tcomms can be a pain, considering how little feedback there is 
:cl:
add: You can now examine telecomms equipment to see how much damage it has taken.
/:cl:

You can now examine telecomms machinery to see how damaged it is.

---

code/modules/reagents/reagent_containers/food/snacks.dm

Get it? Flavor text?
Each of the masterpiece donuts - from the 20tc badassery bundle - now contains a small amount of reagents so as to give most of them their own unique flavor, based on the color of their frosting. The flavor text of each donut was altered to indicate their flavor, and the stat buff text at the end of each donut's flavor text was modified to be more unique and fluid than the previous copy paste description.
By default, masterpiece donuts will have 2 sprinkles - as the only donuts without their own unique reagents, this means that the cream donut and purple donut have 2 sprinkles. The other donuts have 1 sprinkle and 1 other flavor reagent; 1 lemon juice for yellow, 1 mint for green, 1 coco for brown, and 1 berryjuice for blue. 
As such, although their names are the …

Alters masterpiece donuts' flavor texts and adds flavors to them accordingly

---

code/modules/organs/internal/bones.dm

Okay, Halloween is over. Time to fix these big bones. 
These big bones look pretty good though so I can only think of one way to preserve this full detail.
Using this simple BYOND trick bones are now reasonably sized when on the ground but display full 32x32 detail when interacted with.
:cl: Hopek
add: Bones now are reasonably sized when on the ground but still display full detail when interacted with.
/:cl:

Bones now are reasonably sized when on the ground but still display full detail when interacted with.

---

code/game/objects/items/weapons/storage/deferred.dm
code/modules/cargo/exports/gear.dm
code/modules/clothing/head/armor.dm
code/modules/random_map/drop/drop_types.dm

Fixes some bugs with a small refactor to the altyn, maska, and old riot helmets. Basically altyns copy pasted riot helmet code for some reason instead of just inheriting it so I merged the two types. I also wrapped the variable tracking if the face shield was up or down in a setter function so that way if someone expands the code they won't reintroduce the bugs this fixes.
The 1st bug was occurring because the armor list wasn't turning into an armor datum, and the second bug was occurring because someone copy pasted the code and didn't modify the other values after making it start with the face shield up, both are fixed by the setter proc.
Adhering to DRY standards and encapsulation to improve maintainability
:cl:
fix: Fixed the stats UI not working for altyn, maska, and old riot helmets …

Fixes altyn bugs with minor refactor

---

code/game/objects/items/weapons/implant/implants/carrion/explosive_spider.dm

i ded pls nerf
Carrion spiders now have a delay in explosion, two second, more importantly they now pop out when activated, glowing a bright orange hue along with a warning message in the chat.
i ded pls nerf
Make it so carrion explosive spiders are able to be countered, instead of being haha i click you dead
:cl:
tweak: Carrion explosive spider now has a delay and pops out of the victim's body when it's activated
/:cl:

Tweak to Carrion Explosive Spider

---

code/game/objects/items/weapons/implant/implants/carrion/control_spider.dm
code/modules/mob/death.dm

Changed the control spider duration from 15-20 to 50-60 seconds and made the spider core die with the host body if the victim dies during control spider mind control.
This is a better way to balance it so carrions would still need to think hard to avoid death while having a lot of time during mind control for various plans instead of whiping out a gun and shooting the victim in the head.
:cl:
balance: Control spider duration incersed to 50-60 seconds, but if the controled victim dies under mind control the spider core dies with it.
/:cl:

Control spider rebalance

---

code/game/machinery/doors/airlock_electronics.dm

Seems that, during a refactor, somebody just CTRL+H'd *_electronics to electronics/*, without checking if they'd changed anything that wasn't a typepath.
Vagabonds keep breaking my damn doors, and technos couldn't fix them.
:cl:
fix: Airlock electronic boards now have their UI again.
/:cl:

Fixes airlock electronics having no UI

---

maps/CEVEris/_CEV_Eris.dmm

NT lost biofabrics in the disk change, this gives it to 'em on the desk next to the bioprinter.
I'd intended to add the logistics disk to the guild with my recycling PR but my mapmerge was fucking up - so I did that now while I was taking care of the NT disk too.
NT needs to have their designs, since they're spawn-only and they've no other way of getting them.
Guild can get any disk from the vendor for free anyway, so let's give them logistics roundstart to encourage playing with conveyors and sorters.
:cl:
add: The NT bioreactor room and Guild lathe now have a new disk spawn each - biofabrics for NT, and logistics for guild.
/:cl:

Adds 2 roundstart disk spawns, NT biofabric and logistics for guild

---

code/modules/mechs/equipment/combat.dm
code/modules/projectiles/guns/energy.dm
code/modules/projectiles/guns/matter.dm
code/modules/research/designs/mechs2/exosuits_equipment.dm

Prevents some parent objects from spawning in the loot tables.
Renames balistic_gun -> ballistic
There were some strange things found in loot over the weekend, a matter gun that shouldn't spawn, the default energy gun that does nothing, and a piece of mech equipment that had no sprite.
No more cursed useless objects
Backfacing, no changelog required.
:cl:
/:cl:

Loot stuff

---

code/modules/clothing/spacesuits/void/merc.dm

People were saying that the blood-red voidsuit was much too common, this was due to two reasons
1. It had a rarity level 50 chance to roll
2. There were three of them, giving them a much larger chance of spawning
I have made it so the two subtypes can not spawn, and made its rarity level 90
Rare armor is now actually rare
:cl:
balance: The bloodred voidsuit is now much rarer from maint loot.
/:cl:

Makes the blood-red voidsuit much rarer

---

code/modules/organs/internal/bones.dm

Makes bones have 100 hp instead of 60.
A few players were complaining that bones are too easy to brake, this makes them a bit more resileant on average.
:cl:
balance: Bones are harder to break.
/:cl:

Makes bones stronger

---

code/modules/surgery/internal.dm

Fixes shrapnel, and other things, not being removed properly
Previously, when you removed shrapnel via surgery, it removed it from the embeds/implants list, but never physically moved it, so the character would just have a bunch of shrapnel in them.
Having dud objects is bad
Lets you actually do some autopsy investigation to see who was shot by what.
Lets you recycle some materials from corpses.
:cl:
fix: Shrapnel is now properly removed from the body during extraction surgery.
/:cl:

Shrapnel removal fix

---

code/game/machinery/adv_med.dm
code/modules/reagents/metabolism.dm

The body scanner now shows the NSA of the patient. It shows it as a ratio against NSA_threshold. If it goes above the NSA threshold, it shows as red.
Also fixes NSA returning null sometimes, due to an uninitialized variable. This fixes the HUD element being invisible sometimes.
No longer will people ahelp to ask why the chemist dropped dead, after he was riding high on bicaridine, tramadol, and hyperzine for 30 minutes
:cl:
add: Body scanners now show the NSA of the patient.
/:cl:

Body scanner now shows NSA

---

code/game/objects/structures/crates_lockers/closets/maint_loot.dm
code/modules/mining/mine_items.dm

Removes the debug mining cart from maint loots
Fixes the spareparts closet
Locker's "bad icon" was just a bad icon_state that needed correcting (and wasn't spawning the right stuff anyway)
mining cart was just bad.
:cl:
/:cl:

Misc maintloot fixes

---

code/game/gamemodes/changeling/modularchangling.dm

Carrion organs now force enter the body part when bought, even if there is not enough space inside.
Carrions won't get scammed for their organs if there isnt enough space.
:cl:
fix: carrion organs you buy will not disappear if there isn't enough space.
/:cl:

Carrion organ buy fix

---

code/datums/objective/individual_objective/church.dm
code/datums/objective/individual_objective/technomancers.dm

:cl:
fix: "Heretical Technology" and "Advanced Tribalism" objectives cannot be assigned to any player if their respective key item was destroyed.
/:cl:

fix some personal objectives.

---

code/modules/clothing/spacesuits/void/merc.dm
code/modules/clothing/spacesuits/void/station.dm

People have been asking for this for a while(I think theres like 3 requests or so in the #feedback channel in discord) so I'm gunna go ahead and put it through the proper channels so that someone who has the authority can either approve, refuse, or request modifications to the proposed changes. I modified the rarity of the blood red voidsuit so that it wont become more common since the spawn pool is shrinking, see the spawn pool charts below.
1. The armored voidsuits in maint have been power creeping on the armor already in maint
2. The above reason has led to a reduced design space where people feel like a new armor needs to have 50-70 armor stats to be viable
3. Improved clarity, people often mistake vagabonds for technomancers, IH, or miners since vagabonds are so prone to wearing …

Removes faction voidsuits from maint

---

code/game/objects/items/devices/chameleonproj.dm

Chameleon projectors can no longer copy things that are less than 32 pixels
After watching a cigarette butt (about 10 pixels in total) reload a valkyrie laser sniper, as all of NT ran past it, I felt it was time to deal with it.
:cl:
balance: The chameleon projector now requires an item have a minimum pixel count to their icon.
/:cl:

Chameleon Projector nerf

---

code/modules/clothing/spacesuits/rig/modules/ninja.dm
code/modules/clothing/spacesuits/rig/suits/light.dm

I've removed you three times so far. How many more will it take?
Removes the teleporter rig module from the loot tables, again.
It, combined with night vision/mesons/cameras, means you can just teleport anywhere instantly.
:cl:
balance: The rig teleport module has been removed from the loot tables, hopefully.
/:cl:

Teleporter Rig module removal

---

code/modules/organs/internal/internal_organ_processes.dm

Fixes a runtime in internal_organ_processes.dm, it was caused due to def_zone in armor having inconsitant bahaviour, either being a organ tag or an organ.
Runtimes bad.
:cl:
fix: fixed a runtime in erismed
/:cl:

Erismed runtime fix

---

code/modules/organs/external/_external.dm
code/modules/organs/external/damage.dm
code/modules/organs/external/subtypes/robotic.dm

Robot limbs can now break their internal bones
Robot limbs now break off or explode when they take too much damage
There are a few complaints about robot limbs being a bulwark, absorbing attacks when they have reached maximum damage threshold, with little negative effects to the user.
:cl:
balance: Robot limbs now have breakable bones
balance: Robot limbs now break off or explode when they take too much brute damage
/:cl:

Robot limb rebalancing

---

code/modules/telesci/telesci_computer.dm

Restricting telepad from accessing centcomm and dungeon z-level *for now*
Nerd guys from R&D can't take stuff from serb base.
:cl:
balance: Telepad can't access centcomm and the one star dungeon levels
/:cl:

Restricting telepad from accessing specific z-levels

---

maps/CEVEris/_CEV_Eris.dmm

There were a lot of problems related to Eris's toxins room and this fixes them
Toxins is the best part of science
:cl:
add: Added a pipe dispenser to toxins
add: Added a gas filter to toxins
add: Added a connector port directly to space
add: Replaced a bedroom with a tachyon array room on the science shuttle
tweak: The mixing chamber monitors can now control the air injectors and vents in the chambers
del: Removed pumps from toxins that are no longer needed
tweak: Moved the von krabin infront of toxins so you can reach the rnd apc
tweak: Replaced the plasma glass on the mixing chamber with reinforced plasma glass so it doesn't break so easily
fix: Fixed the toxins igniter buttons firing both igniters despite which button you pressed
/:cl:

Various toxins map fixes

---

code/game/objects/items/weapons/implant/implants/carrion/explosive_spider.dm
code/game/objects/items/weapons/implant/implants/carrion/flashbang_spider.dm
code/game/objects/items/weapons/implant/implants/carrion/toxic_spider.dm

all around standardization of carrion grenade-y spiders
warning message is now bold red and emits romnche sound
please i just want to see them again
:cl:
tweak: Grenade-like spiders (Toxic, Explosive, Flashbang) now emit more obvious tell-tale signs before activating
/:cl:

Updates various messages for grenade-spiders giving more attention to themselves for others

---

code/modules/mob/living/carbon/brain/MMI.dm

The user is now informed if the brain is no longer playing, and the brain is now informed that somebody is putting their brain in an MMI
Having to performe a seance to get somebody to get back into their brain, only to find they ragequitted because somebody slugged them in the chest sucked.
:cl:
tweak: Attempting to put a brain in an MMI now informs the brain they're being MMI'd, and informs the user if the brain is no longer playing.
/:cl:

MMI better user feedback

---

code/modules/clothing/head/armor.dm
code/modules/clothing/suits/armor.dm

It felt weird to me that the values on these armors were different on the helmets and vests. Deny this if there was a reason for the armors being like this, but otherwise I have this done.
Handmade: Slight buff to the vest (20 --> 25 bullet protection)
Bulletproof (non IH) armor: Helmet buffed (50 --> 55 bullet protection)
Heavy armor: vest nerfed slightly (55 --> 50 to melee, bullet, and energy protection)
IH ballistic proof armor: Helmet nerfed (40 --> 30 melee protection, 35 --> 25 energy protection)
Lemme know if there's anything I should change.

Tweaks the values on handmade, bulletproof, heavy, and IH ballistic proof armor.

---

code/game/jobs/job/guild.dm

:cl:
fix: now there can only be two artists per round
/:cl:

now there can only be two artists per round

---

code/datums/autolathe/biomatter.dm
code/game/objects/items/weapons/autolathe_disks.dm
code/game/objects/items/weapons/storage/pouches.dm

Adds following items to NT's clothes disk (cost in biomatter in brackets):
Small generic pouch (15); medium generic pouch (30); large generic pouch (45); ammo pouch (45); medical supplies pouch (15); engineering tools pouch (15); engineering storage pouch (15); tubular&vial pouches (20).  
More useful items and services for NT to produce and provide = more interaction with rest of the population = good.
As of now the only source of these items in game is junk and ordering crate from Guild, until now there was no way to craft these items otherwise. It's a nice niche for NT to fill, since they lready produce holsters and such.
:cl:
add: Pouches to NT's clothes disk.
add: Biomatter cost for pouches. 
/:cl:

Adds generic pouches to NT bioprinter clothing disk

---

code/game/gamemodes/changeling/modularchangling.dm
code/modules/organs/internal/carrion.dm

Nest planting now costs a genome point each
Changes the carrion maw to cost 0 genome points
Having no maw would screw a carrion over.
Being able to spam infinite spiders sucked.
Being able to spam
:cl:
balance: Carrion Maws now cost 0 genome points.
balance: Carrion spider nests cost 1 genome point each to place.
/:cl:

Requested carrion tweaks

---

code/game/objects/items/weapons/implant/implants/excelsior.dm

Was requested
So people don't think you're just shit at surgery when the patient's head explodes.
:cl:
tweak: Removing an Excel's implant now gives a bit more feedback to viewers as to why that person's head explodes.
/:cl:

Removing an excelsior rev's implant now gives more feedback

---

maps/CEVEris/_CEV_Eris.dmm

This connects the MBO's office to chemistry.
Requested by Dev Delegate.
MBO can just walk from their office to chemistry, rather than going through a half dozen doors.
Does also mean the access to the rear maint of medbay is a little more inaccessible.
:cl:
tweak: The MBO's office is now connected to chemistry.
/:cl:

Connects the MBO's office to chemistry

---

code/datums/mob_stats.dm
code/game/objects/items/oddities.dm
code/modules/sanity/sanity_mob.dm

1. Now odditys lose their perk on first use.
2. Odditys now have a 60% chance to have an associated perk.
:cl:
tweak: Now odditys lose their perk on first use.
tweak: Odditys now have a 60% chance to have an associated perk.
/:cl:

Odditys rebalance

---

code/modules/organs/body_modifications.dm

Turns out vagabond status is stored in job_low
Vagabonds should be the most post-human, as they exist within the muck and grime
Previous PR had the changelog
:cl:
/:cl:

Vagabond prosthesis fix

---

code/modules/organs/internal/carrion.dm
code/modules/reagents/reagents/toxins.dm

Carrions were causing a bunch of runtimes
No more runtimes
:cl:
/:cl:

Fixes timeofdeath being nonstandard in carrion and zombiepowder

---

maps/CEVEris/_CEV_Eris.dmm

Trying to do surgery while missing retractors sucks.
:cl:
add: The misc tools in robotics surgery bay have been replaced with a surgical medkit.
/:cl:

Adds surgery medkit to robotics

---

maps/CEVEris/_CEV_Eris.dmm

When chemistry was extended to reach the MBO's office, I forgot to put in shutters on the windows
No more staring at the dumb vagabonds as they ape on about wanting space drugs
:cl:
fix: The chemistry shutters now extend to the windows added in the extension.
/:cl:

Extends the chemistry shutters

---

code/game/objects/items/weapons/space_harpoon.dm

One of two PRs relating to the harpoon. either, neither or both could be merged.
The bluespace harpoon can be used to access areas you can't see, through clicking on the black space therein.
Why It's Good For The Game
Being used to rush the spare roundstart, and generally make the round inhospitable for anyone but moebius
Changelog
🆑
del: The bluespace harpoon gun can no longer receive and send items to places you can't directly see.
/🆑

Harpoon out-of-sight fix

---

maps/submaps/deepmaint_rooms/core/vault.dmm

Turns out, whoever made this dungeon map didn't bother to read the nuclear bomb code, and just map-editted it to be LOLNO.
If you just change it so that it isn't the eris_ship_bomb version, it doesn't overwrite the ship's bomb code.
A captain should be able to nuke the ship if needs be.
:cl:
fix: Fixes deepmaint disabling the ship's nuke
/:cl:

Fixes the deepmaint making the ship nuke unusable

---

code/modules/mob/living/simple_animal/borer/borer_powers.dm

**About The Pull Request**
Borer players cant actually paralyse victims
**Why It's Good For The Game**
Players that have played borer have been reporting that they cant infect someone due to the victim being able to crawl away while downed which cancels the infection attemp immediately.
**Changelog**
🆑 
fix: Switches out the Weaken mob state in the borer's paralyse ability with the Paralyse mob state
/🆑

Borer paralysis fix

---

code/modules/projectiles/guns/energy/crossbow.dm
code/modules/projectiles/guns/energy/laser.dm
code/modules/projectiles/guns/energy/plasma.dm
code/modules/projectiles/guns/energy/shrapnel.dm
code/modules/projectiles/guns/projectile/automatic/ak47.dm
code/modules/projectiles/guns/projectile/automatic/atreides.dm
code/modules/projectiles/guns/projectile/automatic/c20r.dm
code/modules/projectiles/guns/projectile/automatic/dallas.dm
code/modules/projectiles/guns/projectile/automatic/sol.dm
code/modules/projectiles/guns/projectile/automatic/straylight.dm
code/modules/projectiles/guns/projectile/automatic/vintorez.dm
code/modules/projectiles/guns/projectile/automatic/wintermute.dm
code/modules/projectiles/guns/projectile/automatic/z8.dm
code/modules/projectiles/guns/projectile/automatic/zoric.dm
code/modules/projectiles/guns/projectile/boltgun.dm
code/modules/projectiles/guns/projectile/pistol/avasarala.dm
code/modules/projectiles/guns/projectile/pistol/clarissa.dm
code/modules/projectiles/guns/projectile/pistol/lamia.dm
code/modules/projectiles/guns/projectile/pistol/olivaw.dm
code/modules/projectiles/guns/projectile/pistol/paco.dm
code/modules/projectiles/guns/projectile/revolver/consul.dm
code/modules/projectiles/guns/projectile/revolver/deckard.dm
code/modules/projectiles/guns/projectile/revolver/sky_driver.dm
code/modules/projectiles/guns/projectile/shotgun/bojevic.dm
code/modules/projectiles/guns/projectile/shotgun/gladstone.dm
code/modules/projectiles/guns/projectile/shotgun/regulator.dm
code/modules/projectiles/guns/projectile/sniper.dm
code/modules/projectiles/projectile/beams.dm

Reverting damage of all guns to pre #5446 state, except Gladstone.
<details>
<summary>Reason for Gladstone nerf</summary>
</details>
***balance***
:cl:
balance: Guns damage reverted.
balance: Gladstone now have reduced damage.
/:cl:

Damage reduction

---

code/game/objects/random/ammo.dm
code/game/objects/random/spawner.dm
code/modules/cargo/packs.dm
code/modules/projectiles/ammunition/boxes.dm

Nerfs the guild's ability to gain top tier guns and top tier ammo and all the money they could ever need, from two crates.
Previously, surplus weapons and ammo crates would draw from all possible ammo types, and all possible weapon types
This would mean that ammo crates would be worth MUCH more than their cost, so could be sent straight back for 1000% profit in some cases.
The weapon crates would also spawn the best possible weapons incredibly often.
This would mean that, guild would not want to deal with the ship, as it had nothing to offer them that they couldn't already have.
:cl:
balance: The value of the contents of surplus weapon and ammo crates from guild, is now more or less equivalent to the cost of the crate.
/:cl:

Surplus crate nerf

---

code/datums/autolathe/biomatter.dm
code/game/objects/items/weapons/autolathe_disks.dm
code/game/objects/items/weapons/storage/pouches.dm
code/modules/clothing/suits/neotheology.dm
code/modules/projectiles/guns/mods/mods.dm

Added production cost for Excruciator (3 biomatter, 1 plasteel, 1 gold, 1 glass), added design disk for it that should spawn only from EotP as one of armanents disk.
Added lights back to NT helmets, they lost it when they transitioned from spacesuit to armor.
Rectifies my mistake of setting ammo pouch's cost to same as large pouch, now it's a bit less expensive to produce than medium one.
Nice having any way to actually produce these lenses I guess. More rewards from EotP ain't bad either I think.
:cl:
add: Excruciator disk
add: Excruciator's cost
balance: rebalanced ammo pouches
tweak: fixes light on NT helmets.
/:cl:

Adds Excruciator lense disk to Eye of Protector + misc NT tweaks ( with Dante from Devil May Cry series)

---

code/modules/clothing/spacesuits/rig/suits/light.dm

This removes ALL light rigs from the loot table.
The light suit sucks to play against as its invisibility has no counter, and has been removed several times
:cl:
del: The Lightsuit rig has been removed from loot tables
/:cl:

Remove ninja

---

code/modules/organs/external/subtypes/robotic_types.dm
code/modules/research/designs/prosthesis_implants.dm

Was told to, now there's some actual incentive to augmenting yourself via the moebius medical scheme
Roundstart FBPs having armor was apparently pretty BS.
:cl:
balance: The moebius roundstart prosthetics are no longer armored.
/:cl:

Fixes the roundstart moebius FBP having armour

---

code/modules/economy/price_list.dm

ammo casings no longer export for 20 credits per casing. They now export for 0 credits per casing. that's 100% less profit per casing!
money printer go brrrrrrrrr 
:cl:
balance: ammo casings no longer have any export value.
/:cl:

Casings are now worthless

---

code/modules/sanity/breakdowns.dm

Increases the hysteric breakdown delay from 30 seconds to 60 seconds.
Hysteric is one of the most annoying and detremental breakdowns in the game, so players should have more time to react to it.
:cl:
balance: Hysteric breakdown takes 60 instead of 30 seconds to trigger.
/:cl:

Hysteric breakdown delay increase

---

code/controllers/subsystems/supply.dm
code/game/atoms_movable.dm
code/game/objects/items.dm
code/game/objects/items/devices/scanners/price.dm
code/modules/cargo/exports.dm
code/modules/cargo/packs.dm

Adds the surplus tag, which marks anything bought via the guild's supply shuttle.
This is currently used to drop exported surplus items value by 60%
Being able to buy then resell the same item to the same company for infinite recursion profit makes no damn sense.
:cl:
balance: Items purchased via the supply shuttle are now only resellable to the supply shuttle for 40% base value, unless processed
/:cl:

Guild nerf eternal

---

code/datums/contract.dm
code/game/objects/items/weapons/grenades/flashbang.dm

flashbang/nt and the excelsior grenade launcher contract now have proper grammar.
Basic typo fixes.
:cl: Xoxeyos
spellcheck: 'granade' is now 'grenade'.
/:cl:

Grammar Fixes, 'granade' to 'grenade'.

---

code/game/machinery/autolathe/artist_bench.dm

Removes those calibers and associated vars.
.60 revolver which you can hide in a holster and which can de-cap a person in full bullet-proof armor is too funny. .70 is gyro and ammo/pistol was appearing due to bugs. It shouldn't exist at all.
:cl:
del: Removed .70 and .60, grenades and rockets from artist revolvers.
/:cl:

Remove .60 and .70 froma artist revolver

---

code/modules/organs/external/_external.dm

Previously, you could go up to 4 times speed if you filled your legs with hydraulics, and even moreso if you used nerves instead
No more super-speed moebius FBPs ruining the round for everyone.
:cl:
balance: There is now a hard limit on how much of a speed boost you can get from implanting muscles into your legs.
/:cl:

Clamp muscle speed

---

code/modules/clothing/spacesuits/rig/rig.dm
code/modules/clothing/spacesuits/void/void.dm
code/modules/scrap/oldificator.dm

Cleaning a voidsuit now makes its helmet, boots, and tank young too
Being able to clean your voidsuit is nice
:cl:
tweak: Cleaning a voidsuit now also youngifys the helmet, tank, and boots
fix: Cleaning your voidsuit in the washing machine no longer deletes magboots attached post spawn
fix: Rigs no longer eat your shoes and gloves when unequipping the rigsuit.
/:cl:

Voidsuit cleaning fix

---

code/game/objects/items/stacks/nanopaste.dm
code/game/objects/items/weapons/tools/_tools.dm
code/modules/mob/living/carbon/human/human_damage.dm
code/modules/organs/external/damage.dm
code/modules/organs/internal/bones.dm
code/modules/organs/surgery_helpers.dm
code/modules/power/cable.dm
code/modules/surgery/robotic.dm
code/modules/surgery/robotic_damage.dm
code/modules/surgery/surgery_ui.dm

You can now fix robot bones
Surgery UI data acquisition made more modular
I made it so you can break robot bones, but didn't realize that bone fixing was locked to organic bones for some reason.
:cl:
fix: You can now fix robot bones, using a welding tool, or some nanopaste.
/:cl:

Robot Bones fix

---

code/modules/projectiles/gun.dm

previously, the AP of any gun would be doubled if you had 5 vig tripled if you had 10 vig and so on, effectively resulting in most guns getting obscene amounts of AP. With this change, you now get 2% extra AP per unit of VIG.
I'm about to click you with 100 AP
:cl:
balance: VIG now has a much lower influence on AP than before
/:cl:

fixes the influence of vigilance on armor penetration

---

code/modules/organs/external/_external.dm

My math was off.
Navigation of the ship is an important part of the game.
:cl:
fix: Players now walk at the pre muscle speed nerf speed again
/:cl:

Removes the accidental .25 slowdown players started with

---

code/datums/craft/menu.dm
code/datums/craft/recipe.dm
code/datums/craft/recipes/airlocks.dm
code/datums/craft/recipes/floor.dm
code/datums/craft/recipes/furniture.dm
code/datums/craft/recipes/misc.dm

I deleted some code in the makeshift prosthetics PR, not realizing that the jank was not just skin-deep
Technos can possibly replace my broken medbay doors with medbay doors now, rather than the default airlock
:cl:
fix: The crafting subtypes of doors, tiles, and chairs are now available again.
/:cl:

Completes a partial revert of the craftmenu subtype code

---

code/game/machinery/vending.dm
code/modules/projectiles/projectile/special.dm

See title
The fire inventory hack option was reported to be too beneficial, so in true eris fashion, we fitted gunpowder to the change return slot.
:cl:
balance: Vending machines now fire coins at projectile speeds when hacked, rather than their inventory
/:cl:

Vending machines now fire coins, rather than their inventory

---

code/game/machinery/cryopod.dm
code/game/objects/items/bodybag.dm
code/modules/mob/living/carbon/human/human.dm
code/modules/mob/living/carbon/human/life.dm
code/modules/reagents/reagents/other.dm

Fixing organs checks, instead of using proc has_organ to random_organ_by_process, because has_organ are for external organs.
Also adding health check (without oxyloss), so people who are revived do not die instantly several times, making doctors go insane and dead people annoyed by that.
Reducing minimal oxyloss from 40 to 20.
Now stasis bags and cryopods can "stop" the death timer of necrosis. Now if you luckily place corpse in stasis bag before 5 minutes, you can revive this body later.
:cl: DarkLevel
balance: reducing minimal oxyloss of resuscitator
fix: fixing resuscitator organs check.
code: Stasis now re-update death time
/:cl:

Resuscitator fixes and improvement

---

code/__HELPERS/bluespace_entropy.dm
code/datums/objective/individual_objective/technomancers.dm
code/game/gamemodes/events/hidden_events/bluespace_crystal_infestation.dm
code/game/objects/effects/effect_system.dm
code/game/objects/effects/portals.dm
code/game/objects/items/oddities.dm
code/game/objects/items/weapons/teleportation.dm
code/modules/mob/living/carbon/superior_animal/roach/types/bluespace.dm
code/modules/mob/living/simple_animal/hostile/stranger.dm
code/modules/trade/machinery/trade_beacon.dm

This pr is focused on making entropy-related events a little more frequent. As well as increasing the feedback when a cockroach disappears before your eyes. It also provides admins with information on where the Stranger spawned.
:cl:
tweak: Completing the Technomancer's "Disturbance" objective reduces global entropy.
tweak: the narrator's events related to bluespace increase global entropy.
tweak: bluespace cockroach teleports create sparks.
tweak: the Stranger is a bit more powerful as a minor event.
tweak: portals produce a little more entropy.
tweak: destroying the gitf bluespace produces much more entropy.
tweak: creating the bluespace gift produces reduces entropy a bit more.
add: admins are informed about where the Stranger spawned. 
tweak: bluespace roaches now have bluespace …

bluespace entropy improvements

---

code/modules/projectiles/guns/energy/shrapnel.dm
code/modules/projectiles/projectile/projectilegrenades.dm

The Hand-held version of the Shellshock loses it's ability to fire beanbags, and gains a mode that can fire a weaker version of the projectile frag grenades the china lake uses. It usually deals between 35 and 50 damage on a direct hit to an unarmored human, but rarely it can deal as much or as few damage as 20 or 60 due to chance-based same-turf hits.
The hand-held version also gains the ability to shoot once more if its cell is out of charge, which consumes the cell. The charge cost for the grenade launcher is so high that it will always consume the cell. Additionally, the hand-held shellshock must now be wielded, to increase the time to reload
This configuration encourages using one of the shotgun firemodes until the cell is empty, and then using up the cell with a grenade or another …

Shellshock rework

---

code/__DEFINES/mobs.dm
code/_onclick/item_attack.dm
code/game/objects/items/stacks/medical.dm
code/game/objects/items/stacks/nanopaste.dm
code/game/objects/items/weapons/autopsy.dm
code/modules/mob/living/carbon/human/human_attackhand.dm
code/modules/mob/mob_grab_specials.dm
code/modules/organs/external/_external.dm
code/modules/organs/surgery_helpers.dm
code/modules/surgery/organic.dm
code/modules/surgery/surgery.dm

Adds self shrapnel removal surgery (Needs a sharp item), and being able to close your own wounds using a cauterizable item (Welding torch, for instance)
Removes some text from get_wound_desc that was never used, as it was never returned properly.
Adds surgery checks to see if you're standing and trying to operate on yourself, or sitting and trying to operate on yourself, to prevent conflicts with regular surgery and emergency surgery.
Adds being able to see shrapnel in somebodies limb by using the grab-examine inspect organ
Requested feature, as shrapnel is a death sentence for solo antagonists.
:cl:
add: Adds emergency self surgery. 
add: Stand still, and use a sharp item on the limb with shrapnel in it to remove shrapnel from yourself.
add: Stand still, and use a hot item to cauterize …

Adds emergency self-surgery

---

code/game/objects/items/devices/hacktool.dm

the hacktool's hacking speed is now affected by the COG stat of it's user. default time is 30 seconds, every point of COG removes 0.5 seconds up to a maximum of 20 seconds. negative cog will affect it in the same way, but there is no maximum amount of extra time you can get from having terrible COG
Cognition OP, pls nerf
:cl:
tweak: The hacking tool now uses COG to determine the hacking speed
/:cl:

The hacking tool's speed now scales off cog

---

code/datums/perks/oddity.dm
code/modules/reagents/reagent_containers/pill.dm

having the fast fingers perk allows you to slip pills into drinks unnoticed.
nanoforge
:cl:
tweak: you can now put pills into drinks unnoticed if you have the fast fingers perk.
/:cl:

You can now put pills into drinks unnoticed if you have fast fingers

---

code/datums/uplink/announcements.dm
code/datums/uplink/medical.dm
code/datums/uplink/stealth and camouflage items.dm

Adds the surgery kit, shipwide announcement and the chameleon kit to the carrrion uplink. 
Carrions get to use a few more fun and stealthy items if they don't want any more gene points, the surgery kit should also make organ extraction less painful.
:cl:
add: Added the surgery kit, the chameleon kit and the shipwide announcement to the carrion uplink.
/:cl:

Few more itmes in carrion uplink

---

code/modules/mob/living/silicon/robot/robot_modules.dm

Gives Service module a synthesizer for all those associated morale reasons.
Portable cyber-music playing.
:cl:
tweak: Cyborgs with the Service module now have access to a mini-synthesizer instrument.
/:cl:

Service borg gets instrument

---

code/__DEFINES/weapons.dm
code/datums/autolathe/guns.dm
code/game/objects/items/weapons/design_disks/autolathe_disks.dm
code/modules/projectiles/guns/energy/laser.dm

Adds Cog design disk with enough license points to print 4 off one. Adds 2 burst firing mode to Cog, instead of charge mode. Changes material cost from 12 steel to 10 steel, 15 plastic and 5 glass. Adjusted rarity values of both gun itself and design disk to mirror these of Novakovic.
To add to that: Cog has always been embarrassing gun to shoot by any means, and it has largely remained such: it still fires beams of 30 burn damage wih 0AP, it still is woefully uneconomical to shoot with charge cost of 100 per shot. But I hope it will now have at least any reason at all to be considered and become different from upcoming makeshift laser gun, which would otherwise be very same thing.
:cl:
add: 2 burst  firemode
del: Charge mode on cog
add: cog's design disk 
tweak: cog's matter list
add: …

Big Cog Renaissance ( I am very proud of that name)

---

code/datums/autolathe/clothing.dm
code/game/objects/items/weapons/design_disks/ironhammer.dm
code/modules/clothing/suits/armor.dm

Adds leg and arms coverage to ablative vest.
It was super confusing to find out that ablative vest does not, in fact, cover arms and legs, despite its sprite following same scheme as all fullbody vests do. Also it made armor kind of an absolute joke.
:cl:
tweak: added legs and arms coverage to ablative_vest
tweak: made ablative_vest into ablative_vest_full
/:cl:

Makes ablative vest into full body ablative vest

---

code/modules/sanity/sanity_mob.dm

Oddities no longer lose their perk when being used to level up
Oddities losing their perks upon use serves no purpose other than hindering free trade of oddities, and thus player interaction. Since you can't get a perk twice, Vagabond Mcpowergame just continues to use an oddity with a good perk once and then switches to whatever oddity gives the most stats, and it does not matter to him whether or not the oddity is purged because he isn't looking to sell it or pass it on anyways. If you are actually trying to interact with players through selling, renting or gifting oddities, having their perks removed upon use is just another hindrance. 
:cl:
tweak: Oddities no longer lose their perk when being used to level up
/:cl:

Oddities no longer lose their perks when being used to level up

---

code/modules/sanity/sanity_mob.dm

Reverts discordia-space/CEV-Eris#5891
After a bit of discussions with Nestor we've decided that it was a abad idea to merge akchually
:cl:
tweak: the changelog that says that oddities do not lose their perk is a lie.
/:cl:

Revert "Oddities no longer lose their perks when being used to level up"

---

code/modules/projectiles/ammunition/boxes.dm

This PR removes the `SPAWN_TAG_AMMO_COMMON` from old .60 box. It should make it refer to default `SPAWN_TAG_AMMO` which isn't frequent as shit in maints. 
:cl:
tweak: Junk .60 ammoboxes should be less frequent now.
/:cl:

Unfuck the junk .60

---

code/game/objects/items/devices/organ_module/active/armblades.dm

the armblade item that looks like it's the upgrade, but actually is the real armblade can no longer spawn in maint
less confusion
:cl:
tweak: armblades no longer spawn in maint
/:cl:

armblades no longer spawn in maint

---

code/game/jobs/job/church.dm

Tune stats of NT jobs according to what's written in the NT rework documentation
It was asked for on discord in miner channel so here it is.
```
Custodian
Remove BIO, because he doesn’t need it, and move it all into TGH, it’s useful in fights.
Agrolyte
Take 5 TGH and move those points to BIO, this will help with them being medic.
Acolyte
Again, he has no use for bio as he is no farmer, nor healer. Make ROB 15, helps with killing roaches. Maybe 5 points could be taken from VIG and again put into the ROB again because NT is melee oriented.
Preacher
Give 15-20 to ROB as all church members complete a melee training course.
(At the cost of BIO?)
P.S.-I’m moving bio points into other skills because they are more useful there. Again, those roles don’t grow or heal and the possibility of printing …
```

Tune stats of NT jobs to be consistent with NT documentation

---

code/__DEFINES/perks.dm
code/datums/perks/job.dm
code/game/jobs/job/civilian.dm

Club personnel now starts with a trait thta has the same characteristics as the "charming personality" trait.
:cl:
tweak: club personnel now starts with a sanity-recovering aura trait
/:cl:

sanity boost aura for club personnel

---

code/modules/projectiles/ammunition/ammo_kits.dm

This PR makes sure you won't waste junk ammo kit if you close the window without choosing any ammo. Also makes its name lowercase and adds some feedback.
Laws of thermodynamics should usually be respected.
:cl: Firefox13, Shazbot
fix: Junk ammo craft kit won't delete itself if you leave the ammo selection menu. Also added some feedback to it.
/:cl:

Minor junk kit fixes

---

code/modules/hydroponics/spreading/spreading.dm

you can now draw reagents from maintshrooms directly by using a syringe
dying in maint? just inject yourself with some shroom-grown inaprovaline (radium)
:cl:
tweak: maintshrooms are now syringe-drawable
/:cl:

Makes maintshrooms drawable

---

code/game/objects/items/devices/chameleonproj.dm

Title.
Blacklists the chameleon projector from spawning.
A, quite frankly strong, traitor item being able to spawn in maint doesn't seem like a good idea
:cl:
tweak: Chameleon Projector is now blacklisted from maint.
/:cl:

Blacklists chameleon projector

---

code/modules/clothing/spacesuits/void/station.dm

Brings back the classic technomancer voidsuit while adding the other one to maint loot.
Players dont like the current voidsuit in EVA storage and this reverts it back to the classic one while not dumping the other.
:cl:
add: Added the other Engi voidsuit to maint loot
tweak: Reverted the Engi voidsuit in EVA storage back to the classic one
/:cl:

Technomancer Voidsuit Update

---

code/game/objects/items/weapons/tools/knives.dm
code/game/objects/items/weapons/tools/pickaxe.dm
code/game/objects/items/weapons/tools/saws.dm
code/game/objects/items/weapons/tools/simple_weapons.dm
code/game/objects/items/weapons/tools/wrenches.dm

This PR mostly tries to make knives a bit more distinct and interesting and rebalances some melee weapons along the way.
- The tactical knife now has a lower chance to embed than other knives because tacticool
- The damage and the armor penetration of the dagger have been increased to from 10 to 13 and from 20 to 50, respectively, to make the dagger an actual dedicated anti-armor knife instead of being a crowbar minus
- The switchblade and butterfly knife are now tiny items when folded in.
- The ceremonial knife gets all of the above benefits with the exception of folding in, of course. The cap should get a robust knife.
- The katana has been nerfed to deal 30 damage instead of 33 in order to make it less superior to the claymore and other non-powered melee weapons
- The muramasa has been …

Small melee balance changes

---

code/game/objects/items/weapons/nt_melee.dm

fixes a bug where every time you extend the NT scourge, it would get extra damage and stop fitting in your belt slot, but refuse to reset these values upon unextending, resulting in a sword with infinite armor penetration after a while. and no way of fitting it in slots.
:cl:
fix: fixed some NT scourge related bugs
/:cl:

NT scourge bug fix

---

code/modules/hivemind/mobs.dm

Reduces bomber hp by 80%
Reduces bomber speed to 2
As it turned out bomber could actually survive two "hits" from thrown item, by reducing it's hp to 1 it can now instantly die to a single thrown item. (Like glass shards, for ex. cigarettes are too weak).
Speed is reduced mostly because I didn't notice any difference between 2 and 2.5, and having it slightly slower won't make it hyper stronger, or hyper weaker. So i believe it's ultimately a better change, if virtually doing nothing.
I'm still betting people will die to bombers and complain, as always.
:cl:
tweak: tweaked Bomber speed and health
/:cl:

Updates bomber

---

code/game/machinery/vending.dm

see title
Smoke bombs are cool but under-used.
:cl:
tweak: added smoke bombs to the sec and gun vendors
/:cl:

adds smoke grenades to the Sectech and gun vendor

---

code/modules/projectiles/guns/energy/laser.dm

The las cannon no longer has a charge mode, and it's power cost per shot has been doubled
also removes it's one hand penalty, you can only fire it when it's wielded, anyways.
moe mad
:cl:
tweak: the laser cannon is now less deadly - its charge mode was removed and energy per shot increased(100 instead of 50).
/:cl:

Lascannon nerf

---

code/game/machinery/vending.dm
code/game/objects/items/stacks/nanopaste.dm
code/game/objects/items/weapons/tools/_tools.dm
code/modules/organs/wound.dm
code/modules/power/cable.dm
code/modules/research/designs.dm

Nanopaste being 20~ plastic for instant robotic treatment felt a little off, and I was suggested to have it require nanites.
Now, it requires nanites, 1 sheet of plasteel, and 10 sheets of steel to construct.
It is now considerably more valuable, and rarer.
Rather than healing every wound at once every click, when healing a prosthetic it now takes the medpatch approach of
- Cycling through every wound
- If it can be healed, it heals so much
- Tells you if there's still more to heal
The amount you heal via nanopaste/welding/cabling scales off of MECH
FBPs are proving to be a pain to balance, considering they feel no pain and can be healed instantly.
This is a 3:30 AM PR, so I'm going to sleep on this and maybe something better will come to mind.
:cl:
tweak: Nanopaste now requires plasteel, …

Prosthetic repair standardization

---

code/modules/projectiles/gun.dm
code/modules/projectiles/guns/projectile/shotgun.dm
code/modules/projectiles/guns/projectile/shotgun/sawnoff.dm

Now when somebody not wielding a shotgun (except sawn off) decides to fire it while not having godlike robustness will stumble most of the times. There is probability based on robustness - more robustness = less chance to stumble.
Ask genessee on discord.
:cl:
balance: You'll now stumble when firing shotguns (except sawn off) with one hand based on yours robustness.
/:cl:

Firing shotgun with one hand

---

code/modules/client/preference_setup/occupation/occupation.dm

The ideal character age for every job is now displayed in it's decription, so players know that they have to change the age of their neon-haired anime girl (male) to 70 years if they want to have a chance at playing as the captain. Truly, a breakthrough for the quality of our roleplay!
Ram Ranch really rocks!
:cl:
add: the ideal character age is now displayed in the occupation description.
/:cl:

Ideal character age in job decription

---

code/modules/hivemind/machines.dm
code/modules/hivemind/mobs.dm

EMP is even better against hivemind, increasing the malfunction chance increase and damage dealt to mobs/machines
Malfunction is also now capable of dealing more damage
Tormentor (head on a tendril) has now a longer cooldown, and a slightly stronger stun, while also the chance to resist the stun being larger
Bans a mob (marionette) from spawning from assemblers (as it was never meant to)
-Makes EMP actually strong and useful against hivemind
-Malfunction had a long cooldown, it now is capable of dealing more damage in order to balance the 1 minute cooldown
-Tormentor stuns have always been weird balance-wise, think it's better if the chance to resist/ignore the stun is higher than before, also longer cooldown
-Marionette was never intended to spawn from assemblers
:cl:
tweak: Tweaked …

Even more Hivemind balance changes and tweaks

---

cev_eris.dme
code/datums/wires/wires.dm
code/game/gamemodes/changeling/modularchangling.dm
code/game/objects/items/weapons/implant/implants/carrion/signal_spider.dm

I'll probably merge this with the  spark spider if showns PR ever gets merged
shown also helped me circumvent shitcoding through advanced shitcoding.
Carrions get a cheap spider that can be attached to wires like a signaler and pulsed via activation. can't be used for grenades and assemblies, though.
1000 IQ plans instead of hand grenade spiders
:cl:
add: signaler spider for the carrion, works like a signaling device
/:cl:

signaling spider for carrion

---

code/modules/projectiles/projectile/bullettypes.dm

incendiary shotgun slugs now deal 45 damage and have the same amount of AP as normal slugs, but they still don't knock you back. they also no longer cause agony.
Fire deals very low damage and can be easily extinguished. Incendiary slugs also require plasma and research to be fabricated.
:cl:
balance: buffed the damage of incendiary slugs
/:cl:

fire slug buff

---

code/controllers/configuration.dm
code/modules/admin/admin_verbs.dm
code/modules/client/client_defines.dm

:cl:
admin: Stock byond's optimized client-side profiler for devs, that not cause dream seeker and daemon lag as shit, required rights can be set through config. Current R_DEBUG | R_SERVER.
/:cl:

Enables stock profiler for devs

---

code/game/objects/items/weapons/storage/uplink_kits.dm

the AMR briefcase can no longer spawn in maint
:cl:
fix: AMR briefcase no longer spawns in maint
/:cl:

AMR briefcase fix

---

code/game/antagonist/station/changeling.dm
code/modules/organs/internal/carrion.dm

Carrion internal organs (maw, chem vessel, spinneret) now add 4 genome points while only lowering your hunger by one point. They also completely refill your chemicals. regenerating without a maw will now deduct 4 gene points so you can't infinitely regenerate and eat and regenerate your own maw (you need your chemvessel to regenerate, and the spinneret costs 7 points to evolve, so those can't be eaten for a profit)
This gives carrions an incentive for screwing each other over, leading to funfunfun paranoia. Also makes spamming infection spiders riskier, as mass-converting will certainly lead to you being backstabbed by others. You can't farm gene points by converting because new convertees will only develop their organs once they're certain you won't/can't harm them, so converting someone …

Carrion organ eating buff

---

code/modules/clothing/suits/armor.dm

This PR adds some slowdown to most fullbody vests with the exceptions of the ablative vest and the handmade vest- the ablative vest is already barely used, and the handmade vest is shit enough anyways.
Now full body vests shouldn't just be a straight upgrade that makes normal vests 100% obsolete. Now, you must decide between all body parts being covered with slowdown (fullbody), all body parts being covered without slowdown but with lower protection (coats) and no slowdown and good protection but limited coverage(regular vest)
:cl:
balance: fullbody vests now slow you down
/:cl:

slowdown for most full body vests

---

code/game/gamemodes/events/hivemind_invasion.dm
code/game/gamemodes/storyevent.dm

Makes Hivemind require 16 players/crewmembers to spawn
Makes the req_crew verb actually do shit, which affects blitz, serbs and malf AI event spawnining
Also adds a TODO comment in code, mostly because I have no clue how to deal with the other verbs and hope some poor bastard in the future tries fixing it.
Example of the code working ~~I think~~
For a long time the req_crew verb did nothing, this PR fixes that by checking if the req_crew number is lower than the amount of players.
Also makes Hivemind unable to spawn when there are less than 16 players, because of balance.
:cl:
balance: Hivemind now requires 16 players to spawn
fix: Blitz, Serbs and Malf AI now actually check for the amount of players to spawn
/:cl:

Hivemind Pop requirement and actually making said requirement work

---

code/game/jobs/job/medical.dm
code/game/jobs/job/science.dm
code/game/jobs/job/security.dm
code/modules/mob/language/neohongo.dm

Switches Neohongo over to the IH due to their affilitation with Frozen Star, also militarised the vocabulary to suit IH more. (Moebius no longer has Neohongo)
Neohongo suits IH better, because of their relationship with the Japanese company known as Frozen Star.
:cl:
tweak: Neohongo IH conversion.
/:cl:

Neohongo Ironhammer Conversion

---

code/modules/biomatter_manipulation/toxic_biomass.dm

Previously, if you had any amount of bio protection, no matter the amount, you were completely safe from Biomatter. Now, bio protection reduces the toxin damage percentage-based
Rosa, please mention this change boldly in your news post, we at least want to pretend we care about NTards who are going to die like flies after this change.
So scientists in bare jumpsuuits can no longer steamroll street shitting NT
:cl:
fix: biomatter now deals damage based on the amount of bio protection you have, instead of just not dealing damage if you had even a very tiny amount of bio resist.
/:cl:

Biomatter now properly checks bio armor

---

code/modules/hivemind/machines.dm

##About Pull Request
You can (rougly) tell how much a hivemind machine is damaged now when examining it.
That's it
Players being able to tell if they are actually dealing any damage to the machine is important, along with being able to know how much HP the machine still has.
Also helps in debugging.
:cl:
add: You can now examine Hivemind machines to rougly check their health
/:cl:

Hivemind Machine Damage Text

---

code/modules/hivemind/mobs.dm
code/modules/mob/living/simple_animal/hostile/megafauna/hivetechboss.dm

Fixes Bomber explosion being 5x5 instead of 3x3
Hiborg and Mechiver have now reduced HP
Mechiver has a small Resistance, reducing damage taken
Tyrant can no longer teleport
5x5 explosion was ridiclously broken
Hiborg was a bit too tanky in personal
Mechiver similary so, however I also gave it a small amount of resistance so it can shrug off very basic attacks
Tyrant teleporting around is absolutely awful, given the fact that it can teleport to ANY core in game, not to mention often failing at that and teleporting into maint and other unintended areas. Also reduced HP by a bit, as to help the crew a bit.
:cl:
tweak: Hiborg and Mechiver have reduced HP. Mechiver now has some flat damage resistance.
balance: Removed Hivemind Tyrant's ability to teleport around.
fix: Fixed Hivemind Bomber's …

Yet another awful hivemind mobs update, including Tyrant

---

code/ATMOSPHERICS/components/unary/vent_pump.dm
code/ATMOSPHERICS/components/unary/vent_scrubber.dm
code/__DEFINES/machinery.dm
code/game/machinery/alarm.dm
code/modules/power/apc.dm
maps/CEVEris/_CEV_Eris.dmm

This PR makes fires much easier to clean up, and also makes scrubbers and vents more efficient and powerful
I feel for a ship the size of Eris, standard ZAS configurations of some atmos machinery simply isnt enough to sustain a ship. If engineers are having to vent a room to space to clean it up faster than siphoning or scrubbers can, that is a major design issue.
:cl:
tweak: Max scrubber flow rate is now 400 Liters per second
tweak: vents and scrubbers now have a power rating of 12000 watts instead of 7500, this should make them able to move more moles of gas
tweak: scrubbers and vents now have more volume
tweak: APCs and air alarms (hopefully) no longer take fire damage and break, NT has now upgraded them
add; there is now a shield diffuser around the atmos waste vent, which will allow …

Makes atmos fires less painful for engineers to deal with

---

code/game/objects/items/stacks/tiles/tile_types.dm

Cyborg tile stack (the one owned by maintenance drones and engi borgs) can copy steel tiles by clicking on them.
It makes reconstruction way easier and prettier for cyborgs because right now you have to chose the type you want to build with a limited list without any previsualization capability. Now when a floor is damaged, you just crowbar a nearby intact tile, click on it to copy it then put down the tile on the damaged spot. And because it's the same type they will merge cleanly instead of an ugly spot because you could not find the exact right type.
:cl: Hyperio
add: Cyborg tile stack can copy steel tiles by clicking on them for easy reconstruction of damaged areas
/:cl:

QoL: Cyborg tile stack can copy steel tiles by clicking on them

---

code/modules/hivemind/mobs.dm

I finally figured out how to properly set the speed of Hivemind mobs, no more fucky balance
Stinger is fast now, to the point it could possibly catch up
Bomber is slow, you can easily outrun it or kite it
Lobber has "normal" movement speed
Similary with Mechiver, however the mechiver has now way better armour and a bigger HP pool as to compensate for it's slowness
Hiborg and Himan are slower than average, with the Himan being faster than Hiborg
Marionette movement speed is unchanged
Before this PR all the hivemind mobs had the same speed
This was obviously awful and not what i wanted, given the fact that a suicide bomb and a armoured walking tank had the same speed.
This PR effectively fixes that by making the mobs slower (or faster for the Stinger).
Also the Mechiver being so slow …

Fixes/tweaks Hivemind mobs speed

---

code/modules/overmap/overmap_shuttle.dm

Fix an oversight about travel distance for shuttles.
I did not see that travel time = base time * ( 1 + distance to sector).
So with a 200x200 overmap and a base travel time of 1 minute (Hulk), the final travel time could go up to 4.7 hours...
Traveling to another sector does not take hours anymore.
:cl: Hyperio
fix: Fix shuttle travel time when moving to another sector on overmap
/:cl:

[Hotfix] Reduce shuttle travel time on overmap

---

code/modules/overmap/overmap_shuttle.dm
code/modules/overmap/sectors.dm

Due to shuttles now being able to move far away from Eris, the code was not made to detect the docking ports if Eris was not on an overmap sector like asteroid or space ruins.
Shuttles can now go back to Eris after their planetary exploration.
:cl: Hyperio
fix: Fix shuttles not being able to move back to Eris
/:cl:

[Hotfix] Fix shuttles not being able to move back to Eris

---

code/game/atoms_movable.dm

Removes recursion in `set_glide_size` proc, lowering it's impact on performance substantially.
Profiler results (3 minutes each, 90 pk ammo boxes on a conveyor loop with 80 bullets each):
Before:
After:
Lag bad.
:cl:
code: `set_glide_size` had the recursion for all atom/movable in contents removed
/:cl:

Glide size recursion removal

---

code/modules/reagents/reagent_containers.dm

Fix for the centrifuge, to no longer allow for infinite reagent duplication.
Full credit goes to Hyperio. I've only done the manual labor.
Fixes a bug.
:cl:
fix: fixed separate_solution in reagent_containers.dm, to properly handle the amount of reagents transferred in the centrifuge. Amounts of reagents below 2u no longer result in 2u after separation.
/:cl:

Fix: Chem Duping Bug

---

code/modules/random_map/noise/ore.dm

Revert a change made during the Planetary port that caused shuttle landing area to have no mineral ressources in the ground.
Makes miners happy.
:cl: Hyperio
fix: Fix shuttle landing area not having any mineral ressource
/:cl:

Fix shuttle landing area not having any mineral ressources

---

code/game/gamemodes/scores.dm

modifies the IH base score and fixes this runtime:
No matter how poorly IH did in a round, his score was still the highest.
:cl:
tweak: IH now has less base score.
/:cl:

IH now has less base score.

---

code/modules/clothing/clothing.dm

This adds shivs to the spaghetti code list of knives that can be put in a boot.
Additionally, I noticed during testing that non-knifeable boots have `can_hold_knife` set as `null`, so I gave the variable a default value of 0.
You can now hide your prison shank in those stylish Oberth Republic jackboots. Instant jailbreak whenever you need it, wherever you need it. Anytime.
:cl:
add: Craftable shivs now count as boot knives, allowing you to put them in any boot that can hold a knife.
/:cl:

Adds shiv to list of boot knives

---

code/game/antagonist/alien/borer.dm
code/modules/mob/living/simple_animal/borer/borer.dm

Allows unoccupied borers to be taken over whenever. There appears to be an issue where maybe multiple borers being made at once only allows one or maybe none to be occupied, so you end up with dumb borers just sitting around until someone stomps them to death despite there being plenty of ghosts. Mostly just stolen old spider code.
Allows ghost to occupy unoccupied borers.
:cl:
add: Ghosts can now occupy borers whenever.
/:cl:

Ghosts can occupy borers whenever

---

code/modules/reagents/reagent_containers/food/snacks.dm

Previously monkey cubes created a human, then set that human's species to a monkey. I'm not sure how current organs work but  set_species seemed to carry over any organs from the previous species. Now it just spawns a monkey on the turf it's expanded on, I'm not sure if there was any reason why it did it the way it did, but I encountered no issues while testing.
https://imgur.com/69TgtvA
Fixes #5976 
This made xenobiology a tiny bit more difficult, as some monkey's would die before the slime could completely eat them. It's also just weird for monkey's to have 2 sets of organs.
:cl:
fix: Fixed monkey cubes
/:cl:

Fixes monkey cubes

---

maps/CEVEris/_CEV_Eris.dmm
maps/CEVEris/centcomm.dmm
maps/encounters/asteroid/asteroid.dmm
maps/submaps/planetary_ruins/hydrobase/hydrobase.dmm
maps/submaps/planetary_ruins/lodge/lodge.dmm
maps/submaps/planetary_ruins/oldpod/oldpod.dmm
maps/submaps/planetary_ruins/playablecolony/colony.dmm
maps/testmap/test_map.dmm

Deletes all occurrences of the tag variable from the map files, these aren't used in SS13 in general, and /tg/ code documentation reports that they cause issues. They are auto-generated when an object is created with Dream Maker, hence the massive amount of objects which use "tag".
fixes #5764 
Removes useless variables which could be causing unknown issues.
:cl:
refactor: Removed ~2000 lines regarding some map object variables, should have no in-game effect.
/:cl:

Deletes all occurrences of the tag variable

---

code/datums/uplink/stealth and camouflage items.dm

This PR removes one extra `f` from proffessional word that is used in uplink 
Makes us look like we know english
:cl:
spellcheck: "Syndicate "Proffesional Killer" scope" now contains one less 'f', resulting in  "Syndicate "Profesional Killer" scope"
/:cl:

Syndicate proffessional killer scope

---

code/game/objects/structures/girders.dm

This PR changes wall girders names from "grider" to "girder".
Makes us look look like we know english
:cl:
spellcheck: All wall griders were replaced with girders. Rejoice!
/:cl:

Wall griders

---

code/modules/mob/living/living_defense.dm

Fixes a typo in a word
Makes us look like we know english while we actually do not
:cl:
spellcheck: Instead of abosrbing damage, armor now absorbs it properly.
/:cl:

Fix a typo that occurs every time there's a firefight with IH or anyone who wears armor(means, very often)

---

maps/submaps/planetary_ruins/marooned/marooned.dm

Fix compilation issue.
For some reason effect/damagedfloor was declared twice and the compiler never complained since planetary exploration was ported. Except now it complains. Nothing to understand, really...
:cl: Hyperio
fix: Remove redeclaration of effect/damagedfloor
/:cl:

Hotfix: remove redeclaration of effect/damagedfloor

---

code/game/jobs/job/church.dm

I was asked to do this PR. Remove salary of all Neotheology jobs. They can earn money by placing obelisks for other departments, selling food, chems, biomatter, weapons, medkits and other stuff that they can print such as pouches.
* Incentive for NT people to perform church related activities and increase interactions with the rest of the crew.
* NT people only needs the faith, feeling of a well-done job and recognition of their believers as a salary, don't they? 🙏 
:cl: Hyperio
balance: Remove salary of NT jobs
/:cl:

Remove salary of NT jobs

---

code/modules/cargo/packs.dm

Adds Resource Integration Gear to Cargo Console, along with multiple crates: Generic EVA, Hazard and Industrial RIGs, crates with some modules (mostly generic ones, except for basic mounted egun, Internal Storage, and NVG, autodocs and chem injectors are still moebius exclusive).
Most common complaints I hear about RIGs and one I raised myself very often, is that there is not really any way to get most modules, however essential they are. It's all junk, uplink, and maybe robbing armory hoping they got something cool. And what better place to make soruce of them, than Guild?
:cl:
add: Resoruce Integration Gear Tab in Cargo Console
add: Some RIG crates to Cargo console
/:cl:

Adds RIG tab and bunch of related crates to Guild Console

---

code/modules/admin/bluespacetech.dm

The admin "test dummies", Bluespace Technicians, didn't have any specific stat modifiers set at spawn, which made doing any sort of stat check very slow, and annoying for doing actual testing. I set all of their stats to 99 when they spawn.
Additionally, they don't know any of the newer languages, so I added every missing language (including robot and drone, even if humans can't speak them) to the BSTs as well.
Finally, the BSTs' ID cards refer to "Central Command" and "classified information" in their descriptions, so I changed that to be more in line with the times.
Certain kinds of testing are now a lot faster, since BSTs no longer have to wait very long at all to do any stat-based actions.
:cl:
admin: Bluespace Technicians now spawn with 99 in each stat, know every language, and have …

Gives Bluespace Technicians 99s in every stat, and knowledge of all languages

---

code/modules/hivemind/core.dm

Removes the Hivemind from being able to corrupt the supermatter
Wacky things would happen with the SM, that and because it makes no sense for it to somehow upgrade a funky death crystal
:cl:
tweak: Hivemind can't upgrade the supermatter now
/:cl:

Removes Hivemind ability to upgrade the supermatter

---

code/ZAS/Airflow.dm
code/game/objects/structures/low_wall.dm
code/modules/clothing/shoes/magboots.dm
code/modules/tables/tables.dm

- Low walls and unflipped tables will no longer block `mob/living` that are `weakened`, allowing those mobs to pass through when atmos pushes them. This has the hilarious side effect of allowing you to defenestrate stunned people and/or throw them onto/over tables.
- No changes to shields, the modules will still work normally. Base shields won't prevent you from getting pulled out into space, humanoid blocking only will still pull you towards space but still block you at the shield, atmospheric containment will prevent the atmos from moving at all.
- Flipped tables will still block movement in their normal directions.
- The `Weaken(5)` from airflow stunning has been changed to `Weaken(3)`, so that you can't get spaced to a whole other sector on a laggy server with no ability to do …

Low walls & tables no longer block Weakened mob/living, and airflow stun length nerfed

---

code/modules/client/preference_setup/global/preferences.dm

changes a single line of code so that floating chat is enabled in preferences by default.
I'm not sure if many players actually know the server even has floating chat. I don't see any reason as to why it's disabled by default, but it's a great addition that makes it incredibly easy to see chat in tense situations. Due to preferences already being saved on most players, they will still have to enable it manually. As a result, this would only apply to new players.
:cl:
tweak: New players have floating chat enabled by default.
/:cl:

enable floating chat by default

---

code/game/gamemodes/scores.dm

A typofix in gamemode/scores/.
Well, it's a typofix, those are pretty good for the game.
:cl: Xoxeyos
spellcheck: Neotechnology is now Neotheology, in the scores screen.
/:cl:

Typo Fix - Neotechnology now Neotheology.

---

code/modules/paperwork/paper_premade.dm

Blacklists the Paper "Judgement" from spawning in maint.
It barely had any text (literally two sentences) and would generally be just a waste of a spot for other useful items (aka everything, even scrap metal has more use).
:cl:
del: Removed a premade paper titled "Judgement" from spawning in maint
/:cl:

Judgement is now illegal

---

code/modules/core_implant/cruciform/cruciform.dm

This adds an `examine()` to cruciforms that informs the user whether or not a cruciform has been activated (read: has a soul), and that also tells NT members and ghosts the soul's name, if present.
Clearly tells apart a cruciform that belongs to someone from one that's brand-new. You don't need someone to tell you in LOOC that they shouldn't sell the cruciform he/she found lying around maintenance anymore.
:cl:
add: Added an examine message that states whether or not a cruciform has been activated, and that additionally tells NT members and ghosts whose soul it is.
/:cl:

Examining cruciforms tells you if they've been activated or not

---

code/modules/projectiles/guns/projectile/pistol/avasarala.dm
code/modules/projectiles/guns/projectile/pistol/colt.dm
code/modules/projectiles/guns/projectile/pistol/handmade.dm
code/modules/projectiles/guns/projectile/pistol/lamia.dm
code/modules/projectiles/guns/projectile/pistol/mandella.dm
code/modules/projectiles/guns/projectile/pistol/paco.dm
code/modules/projectiles/guns/projectile/pistol/selfload.dm
code/modules/projectiles/guns/projectile/revolver/consul.dm
code/modules/projectiles/guns/projectile/revolver/deckard.dm
code/modules/projectiles/guns/projectile/revolver/handmade.dm
code/modules/projectiles/guns/projectile/revolver/havelock.dm
code/modules/projectiles/guns/projectile/revolver/mateba.dm
code/modules/projectiles/guns/projectile/revolver/revolver.dm
code/modules/projectiles/guns/projectile/revolver/sky_driver.dm

Cuts down a lot of recoil from most of the pistols to make them viable.
3 Shots and the rest can't be aimed , even with very high stats. A pistol shouldn't have a lot of recoil , especially one that is rare ,  obtainable through stashes or the traitor uplink  , and that already has a low mag capacity.
Pistols also in general use barely powerfull calibers most of the time and lack the ability for full auto.
:cl:
balance: Reduced recoil of the mandella from 19 to 2
balance: Reduced recoil of the avarsala from  33 to 5
balance: Reduced recoil of the lamia from 21 to 5
balance: Reduced recoil from the paco from 10 to 3
balance: Reduced recoil from clarrisa from 19 to 2
balance: Reduced recoil from the makarov from 21 to 3
balance: Reduced recoil fron the consul from 35 to 6
balance: Reduced …

Reduces the recoil of pistols/revolvers by a lot

---

code/game/jobs/department.dm
code/game/jobs/job/church.dm

Reverses what PR number 6039 did (#6039).... Kinda
this PR also removes the Neotheology source of funding, forcing them to use their department account
the starting money is also increased by 1000 (from 3500 to 4500) which should last for 5 paychecks
Will close this PR if the other one (https://github.com/discordia-space/CEV-Eris/pull/6050) is merged, and vice versa
This doesn't remove starting money from the Neotheology, while also forcing them to """"""""""interact"""""""""" with the rest of the crew as to maintain a steady balance
:cl:
balance: Neotheos now have a wage and starting money, however no external funding so they have to use their department account for wages, it should last enough for five paychecks though.
/:cl:

Neotheo wage alternative

---

code/datums/autolathe/biomatter.dm
code/datums/craft/crafting_items.dm
code/game/objects/items/weapons/design_disks/NeoTheology.dm
code/game/objects/items/weapons/storage/pouches.dm

1. Increases the material from gun and armour parts (gun part is 1.2 plasteel, armour part is 5 wood, steel, cardboard and plastic)
reduces gun part size to small
2. allows NT to print parts pouch
3. also makes the part pouch list look nicer
1. having the parts give only 1 sheet in materials made them highly useless to those who didn't want to craft anything with them, also having the gun parts not be the same size as a crowbar is nice
2. consistency, NT can already print almost every pouch
3. doesn't affect gameplay, just looks better and more consistent with other pouches
:cl:
add: Added parts pouch to a NT disk (the one with pouches and clothes)
tweak: tweaked materials from gun and armour parts, gun part is smaller
/:cl:

Gun and Armour parts

---

code/modules/reagents/reagents/other.dm
code/modules/research/xenoarchaeology/machinery/coolant.dm

This PR basically ports over current Baystation 12 coolant behaviour with a minor tweak.
Bruh you can chill entire deepmaint with a single coolant tank because it sets the atmosphere to zero no matter how much there air to cool.
Proofs of it working:
First section outside of FO office:
https://user-images.githubusercontent.com/57810301/115128474-a9808a00-9fe6-11eb-803c-16236e0e101b.mp4
Brig lobby:
https://user-images.githubusercontent.com/57810301/115128482-b8ffd300-9fe6-11eb-8c6b-935b093eaa8a.mp4
Head Staff meeting room:
https://user-images.githubusercontent.com/57810301/115128487-be5d1d80-9fe6-11eb-876b-3e6511278d1c.mp4
And, of course, deepmaint:
https://user-images.githubusercontent.com/57810301/115128457-92419c80-9fe6-11eb-8876-f02d2b92e991.mp4
Sorry for the delays in videos, I needed …

Fix the coolant tanks

---

code/datums/perks/fate.dm
code/datums/setup_option/backgrounds/fate.dm

Basic typo fix from psyionic to psionic for the oborin syndrome perk description.
Basic typo fix
:cl: Xoxeyos
spellcheck: Psyionic is now psionic
/:cl:

Psyionic to psionic

---

code/modules/projectiles/guns/energy/decloner.dm

This PR edits the price and material requirements to make a decloner
20 steel for:
1. tenfold increase in price
2. 150 irradiation projectiles 
is way too much
:cl:
balance: Due to recent [REDACTED] raid on Moebius science station the original blueprint for biological demolecularisor was lost. Replacements are already being researched, but the new resource cost will be higher.
/:cl:

Tweak decloner price

---

code/game/jobs/job/church.dm
maps/CEVEris/_CEV_Eris.dmm

Added 2 more acolyte slots as well as closets and their spawn essentials. All NTs speak latin now
I've always found it odd how every other faction has a backbone role except for NT. Mobi has scientists, technomancers have technomancers and IH has operatives but NT was always capped. This PR aims to make the acolyte the backbone of NT as i can understand that not everyone wants to be a janitor or a botanist just to play a dedicated NT role. Also all NTs know latin now just like all technos know russian.
:cl:
add: 2 more NT acolyte closets
add: 2 more toolboxes of each type
add: 2 more NT acolyte slots and spawn points
tweak: upped NT acolyte cap by 2
tweak: All NTs know latin now
/:cl:

More acolytes and all dedicated NTs speak latin now

---

code/game/machinery/vending.dm
code/modules/projectiles/guns/energy/egun.dm
code/modules/projectiles/guns/projectile/automatic/atreides.dm
code/modules/projectiles/guns/projectile/boltgun.dm
code/modules/projectiles/guns/projectile/pistol/giskard.dm
code/modules/projectiles/guns/projectile/pistol/olivaw.dm
code/modules/projectiles/guns/projectile/revolver/havelock.dm
code/modules/projectiles/guns/projectile/shotgun/gladstone.dm
code/modules/projectiles/guns/projectile/shotgun/pump.dm

I reduced almost all the prices in the gun vendors with items that relate to guns (guns, magazines and ammo) as almost all of these are early to mid tier items and have fallen into disuse. Many people regard these prices as not worth it as they often find better guns and ammo in maint a lot faster than they attain the credits to buy these.
In short this is a effort to make these weapons see a bit more use and be more affordable for the average eris role. Open to more suggestions on the prices as i more or less just willy nilly reduced them by 200-600 creds except for special cases.
:cl:
tweak: reduced gun vendor prices (and prices on guns themselves).
/:cl:

Tweaked gun vendor prices

---

code/modules/mob/living/carbon/resist.dm

As the title states it makes it so players with high enough robustness can tear handcuffs apart.
This is already technically possible, it's just nicer. Beforehand you would need a robustness value of 120 to instantly break cuffs instantly, so players can break handcuffs easier than they could before. If players have robustness higher than 120, it also no longer gives negative values.
:cl:
tweak: If you have robustness of 80 or more you can break cuffs in 5 seconds.
/:cl:

Players with godlike strength(robustness) can tear apart handcuffs

---

code/modules/core_implant/cruciform/rituals/base.dm

This PR removes the carrion part in the reveal adversaries litany and fixes a typo.
This was supposed to be removed when EOTP system was introduced with Miracle that would tell you the area Carrion is.
:cl:
del: Evil powers have affected NT religion! "Reveal Adversaries" is no longer able to detect Carrions. Rely on EOTP instead.
/:cl:

Remove the carrion part in reveal adversaries litany

---

code/modules/core_implant/cruciform/cruciform.dm
code/modules/core_implant/cruciform/machinery/eotp.dm
code/modules/core_implant/cruciform/rituals/priest.dm

1. the miracle that increases the regeneration of energy gives a little warning to the members of the church.
2. the perk Channeling is applied when calculating passive energy regeneration instead of running on an external proc. This should not make any changes to avoid strange situations when interacting with the rest of the nt update code.
improve the criciform and EOTP code.
:cl:
tweak: now the miracle of regeneration gives an alert to all the members of the church.
/:cl:

crucifrom energy fixes

---

code/game/objects/items/weapons/traps.dm
code/modules/mob/living/carbon/resist.dm

Being beartrapped and cuffed no longer means you are stuck forever until you kill yourself with failed breakout attempts (the attempts don't actually happen you just get snapped). You also use the trap to break out faster now, note you still need to break out of the trap after.
Prevents players from being cuffed and left for upwards of 20 minutes (time to dispose of yourself depends on armour).
:cl:
tweak: tweaked resist code so the visible message does not display unless you are actually attempting to break out
balance: you now use the trap to break out of your cuffs faster (basically the total time to completely break out evens out)
fix: fixed infinite handcuff in trap exploit
/:cl:

Fixes infinite handcuff exploit and minor resist improvements.

---

code/modules/clothing/spacesuits/rig/modules/storage.dm

This essentially brings the internal storage module for RIG's in line with satchels
Not a lot of people use rigs, even after Omni added a way to easily get modules, maybe this will make using rigs less cbt and more fun
:cl: 
balance: internal storage for RIGs is now satchel sized
/:cl:

Buffs internal storage module for RIG's

---

code/game/gamemodes/malfunction/newmalf_ability_trees/tree_manipulation.dm
code/modules/shieldgen/emergency_shield.dm

Fixes the malf AI emergency forcefield , it now spawns at the AI eye.  Quadruples its health so it holds somewhat well against current weapon damage values(Values weren't adjusted in 5 years) , The shields no longer dissipate (they cost 275 CPU , a hefty investment)
Lets the ability work , lets AI's do something more than hide and blow station , lets them create jail cells for their new slaves using power ,etc.
:cl:
balance: AI Emergency forcefield health quadruped (100 > 400)
balance: AI Emergency forcefield no longer dissipates 
fix: Fixed AI Emergency forcefield not being useable
/:cl:

Refactors and fixes malf AI emergency forcefield , buffs emergency forcefield

---

code/modules/trade/datums/trade_stations_presets/zarya.dm

Guild can buy a fuckton of disks in Zarya station because the spawner they use cost 30. This removes the disk. Go junk.
Most of the disks are junk but the fact that you can get a fuckton of disks some of them are basically appear once every five round combined with our broken export creates interesting amount of disks spam-bought by guild.
:cl:
del: Random disk in 'Zarya' station.
/:cl:

Remove the disk inflation

---

code/game/objects/items/weapons/improvised_components.dm
code/game/objects/items/weapons/material/misc.dm

Banishes the spear for all eternity, being a wonky bay leftover that used material hardness and before the bandaid fix could do a whopping 75 damage per hit
despite spears being, well funky spears, their damage output and usage of material hardness resulted in real wonky business
:cl:
del: Banishes spears to the eternal realm of the TeeGee github, where it will suffer for all eternity for using bay code
/:cl:

Spear Banishment

---

code/game/objects/structures/crates_lockers/closets.dm

Dump_contents happens whenever a closet is destroyed. Changes dump_contents to drop to turf.
Players were getting sent to nullspace before.
:cl:
fix: Fixes locker destruction.
/:cl:

Fixes closets

---

code/game/objects/items/devices/PDA/PDA.dm
code/game/objects/items/weapons/clown_items.dm
code/game/objects/items/weapons/implant/implants/carrion/smooth_spider.dm
code/game/objects/items/weapons/mine.dm
code/game/objects/items/weapons/traps.dm
code/game/turfs/simulated.dm

Avoid triggering soaps, excel mines, beartraps, banana peels, carrion smooth spiders, clown PDA and wet floors on ladder/stairs tiles.
To avoid ladder cheesing with slipping objects since you cannot interact with them if you're on another zlevel. You can basically get an easy killzone / interdiction tool if a ladder is the only way to get into an area. Just have to carry a soap with you and if someone follow you then you just can drop a soap on the ladder, nobody can move up/down anymore without getting slipped.
And some of the ship areas only have a single ladder leading to them (especially in maints), or two but super far away from each other, so you cannot avoid it.
Technically beartraps and mines cannot be armed on ladder tile but better be safe than sorry so I've included them in the …

Remove ladder cheese with slipping items, traps and mines

---

maps/CEVEris/_CEV_Eris.dmm

Remove biomatter pipes from NT area (those connecting bioreactor to solidifier and biogenerator) since they can cause crazy lag and no one uses them anyway.
Red lines to show where pipes where:
Reduce lag. Lag is **bad**.
:cl: Hyperio
del: Remove biomatter pipes from NT bioreactor room
/:cl:

Remove NT pipes from bioreactor room

---

code/modules/reagents/recipes.dm

Water/Pot reaction explosions now get divided by 45 instead of 10 , at 600 reaction amount (bluespace beakers) resulting in a explosion slightly weaker than a cracker.
Griefing shouldn't be this easy , being  able to force a round to end shouldn't be done with a few simple clicks, unlike water/pot , glycerol requires some effort. If people want to end the round they should work for it.  Oversized water/pot explosions also have never proven to be fun for anyone , they force the round to end everytime they're used.
:cl:
balance: Water/Pot bombs have been extremly toned down.
/:cl:

Tones down the explosive potential of water/pot bombs

---

maps/CEVEris/_CEV_Eris.dmm

Removed all the spare sols in the armoury with the new IH AK. 9 mags added for them in ammo crate.
These sols are never used aside for their plasteel, with these new AKs IH will have some variety to their arsenal.
:cl:
add: Added IH AK to IH armour along with magazines to their crate for it. 4 AKs and 9 mags.
del: Replaced old surplus sols in the armoury case. 4 sols removed.
/:cl:

Replaces spare sols in armoury (not the lockers) with the new IH AK.

---

code/modules/core_implant/cruciform/cruciform.dm
code/modules/core_implant/cruciform/machinery/eotp.dm
code/modules/core_implant/cruciform/machinery/obelisk.dm
code/modules/core_implant/cruciform/rituals/priest.dm

fixes an obviously not broken code.
The power regeneration proc in byond runs every second but byond defines the seconds as 600 instead of 60 so it runs ten times slower than it should.
:cl:
fix: cruciform energy
tweak: reduces the energy cost of the offerings to 10
tweak: doubles the energy regeneration coming from the obelisks.
tweak: the energy regeneration miracle further increases energy regeneration.
/:cl:

cruciform energy fixes V4

---

code/modules/projectiles/ammunition.dm

Now, if you have a spare mag on the floor, in your belt, in your bag or anywhere alse near you and your gun has no mag inside, you can click on the spare mag with your gun and after 0.5 second it will be reloaded and you will be ready for a shootout
It works with all the mag fed ballistic pistols, some SMGs (Molly, Atreides, but not Straylight)
People who likes dual wielding, "tactical reloads" and doesn't likes reloading like a normal person will be happy now
:cl: CeUvi, SPCR/MLGSTATICa
add: Added new tactical reload (empty gun -> click on mag -> loaded gun)
/:cl:

adds new tactical reload

---

code/modules/mob/living/carbon/carbon_defines.dm
code/modules/multiz/structures.dm
code/modules/projectiles/gun.dm
code/modules/projectiles/projectile.dm

Gives players the ability to shoot people on the other side of ladders as long as they are adjaecent to it, this it to counter ladder camping and give people a viable choice other than grenade spam
More robust combat for multi-z , more robust counters
:cl:
add: You can now shoot people adjacenet to ladders you look through from above/elow
/:cl:

Adds the ability to shoot people near ladders from below/above

---

code/modules/mob/living/carbon/human/human.dm
code/modules/mob/living/carbon/human/species/species_attack.dm
code/modules/mob/living/carbon/human/species/station/slime.dm
code/modules/organs/organ_description.dm
code/modules/reagents/reagents/toxins.dm

Slime people can now regenerate limbs at the cost of 50 nutrition
Slime people can now electrocute people at the cost of  40 nutrition by attacking them
Slime people now have 2x their health
Slime people now have 1.2x brute mod
Slime people now have 0.7x burn mod
Slime people now have more internal space in general
Slime people have their arms and legs more fragile , but the upper body , groin and head more resistant
Slime jelly now heals slimes 
Slime people are kinda meh and don't really have anything super different. Now people have a reason to lynch slime people as they are possibly very dangerous due to their very tough nature and ability to electrocute and regenerate limbs.
:cl:
balance : Slime people now have a 1.2x brute mod
balance : Slime people now have a 0.7x burn mod
balance …

Slime people changes

---

code/__DEFINES/gamemode.dm
code/datums/autolathe/autolathe_datums.dm
code/datums/autolathe/biomatter.dm
code/datums/autolathe/circuits.dm
code/datums/autolathe/devices.dm
code/datums/autolathe/guns.dm
code/game/machinery/autolathe/artist_bench.dm
code/game/machinery/autolathe/autolathe.dm
code/game/machinery/autolathe/mechfab.dm
code/game/machinery/autolathe/nanoforge.dm
code/game/machinery/bioprinter_nt.dm
code/game/machinery/excelsior/autolathe.dm
code/game/objects/items/weapons/circuitboards/machinery/excelsior.dm
code/game/objects/items/weapons/design_disks/NeoTheology.dm
code/modules/research/rdmachines.dm
code/modules/scrap/oldificator.dm

Pretty simple, all autolathes print items with very similar effects to oldified items found in maints, with some effects removed to make sense in game. Machines spared from this effect are the moebius protolathe, exofab and the circuit imprinter, as they can only print specific designs, the clown bench and the nanoforge. (The normal, excelsior and NT autolates all have this effect). The only machine that can print disk designs with no side effects is the newly renamed technomancer (auto-)nanoforge.
As one disk can print up to 4 guns and the main (almost only) source of disks is maints this should be a nerf to vagabonds. This is mostly targeted to vagabonds but the guild and the NT lathe are also affected by this, so this may be changed. Also lore compliance.
:cl:
balance: items printed in …

Autolathe nerf

---

code/modules/projectiles/guns/projectile/automatic/wintermute.dm

1.5 recoil and 1.15 damage mult. (25 * 1.15 brute with 25 pen)
This gun has fallen into disuse over the years and hopefully this will put it back into use, it is now a direct upgrade from the sol and provides good damage and AP along with full auto and not too bad recoil. Well suited for later game antags.
:cl:
tweak: tweaked wintermute recoil to 1.5 and damage multiplier to 1.15
/:cl:

Tiny wintermute buff.

---

code/game/objects/random/food.dm
code/modules/reagents/reagent_containers/food/snacks.dm
code/modules/reagents/reagents/medicine.dm
maps/CEVEris/_CEV_Eris.dmm

Adds a variety of chemicals (vomitol most common) to maint food and makes food spawns rarer.
Maintchem is now a bit more possible and maint food is overall more dangerous/rare.
:cl:
add: Maint food now contains a variety of chemicals.
tweak: Maint food is rarer. 
map: Replaced some normal food spawns with low_chance.
/:cl:

Maintchem and vomit! 

---

code/__DEFINES/components.dm
code/game/area/areas.dm
code/game/machinery/alarm.dm
code/game/objects/items/devices/radio/intercom.dm
code/modules/power/apc.dm

Removes process() from intercoms , now they work based on signals , add a signal for when the APC of an area is deleted, and for when a power change on an area is called, firealarms no longer do src.time which  would result in src.src.time on compile
adresses #4537 by a bit.
190 less objects to process overall , bad code removal , signals good.
:cl:
code: added signals for APC power change, and APC deletion for areas.
refactor: refactored intercom code to not process and instead use signals
/:cl:

Refactors intercom code to not process , adds signals for area power changes and area apc deletion , removes .src from fire alarm code

---

code/game/objects/items/weapons/storage/misc.dm
code/modules/client/preference_setup/loadout/lists/misc.dm

Adds a clown box to the loadout
it contains a bikehorn, banana peel, clown stamp, clown shoes, uniform and mask
all for the sweet low price of 3 points
only for vagabonds
So vagabonds can roleplay as a clown, cost of 3 because it's free clothing, bike horn, stamp and the ultimate CQC weapon, a banana peel
:cl:
add: Added new loadout item, costs 3 points and contains clown clothing along with a bikehorn, clown stamp and a banana peel. PDA and actual sense of humor not included!
/:cl:

Clown box added

---

code/modules/mob/living/carbon/human/human_movement.dm
code/modules/mob/living/carbon/shock.dm

Removes extra hallos slowdown as hallos is already accounted in the shock stage, and nerfs the slowdown scaling from 0-3 at 0-50 shock stage, to 0-3 at 0-100 hallos. Also fixes a calculation bug that would make shock stage not go up.
Slowdown is too strong, and bugs are bad.
:cl:
balance: slowdown from pain is lowered.
fix: shock stage should now increase properly.
/:cl:

Erismed 3 slowdown nerf and bugfix

---

maps/CEVEris/_CEV_Eris.dmm

Removed that odd O2 canister in the hallway, or rather fixed it instantly dropping from the floor above.
Also removed that weird wire connection in NT maint
added shit ton of railings to the catwalk above the engine and above atmos.
O2 canister - it was annoying having it there, at the same time i don't believe it was ever intended because it actually spawned the floor ABOVE where it usually was
Wire connection - literlaly hotwired 2 seperate grids, don't believe that is intended nor is it good for anyone trying to find out why the church is hotwired to the engine
Railings - imagine you're walking on the catwalk, and you lag and end up falling into roaches, or just generally falling down 1 z level, having to go up again and once again slowly carefully walk over the catwalk, hoping you …

Fixes map related thingies and adds railings to engineering

---

code/game/objects/items/weapons/design_disks/frozen_star.dm

Adds the .35 lethal speedloader to the FS .35 Civilian Pack
Consistency and shooty-shoot bang-bang
:cl:
add: Added .35 speedloader to FS .35 Civilian Pack
/:cl:

Adds lethal speedloader to civilian disk

---

code/game/machinery/computer/prisoner.dm

**Fixes chem and tracking implants not showing up on the prisoner management console** 
this PR fixes the tracking and chemical implants not showing up on the prisoner management console as it used to disappear as soon as you step 1 foot out the brig  
Bug fix? 
:cl:
fix: chem and tracking implants now show up if you leave the brig
/:cl:

Fixes chem and tracking implants not showing up on the prisoner management console 

---

code/modules/power/lighting.dm

Reduces the light coming from light bulbs
Pre Change
Change
Light tubes are inconsistent across maps and would need remapping to actually look good if i nerfed their range and/or power. As such im not touching them, atleast not now.
Makes maintenance tunnels (as those are usually the only places where light bulbs are used in majority) even darker, adding to a darker/dangerous feel/theme of said tunnels.
:cl:
tweak: reduced light bulb range and power
/:cl:

Light bulb nerf

---

code/modules/clothing/head/armor.dm
code/modules/clothing/suits/armor.dm

Changes stats of the technomancer helmet and armour (now called "Insulated technomancer helmet" and "Insulated technomancer armour" respectively) to
melee = 35,
bullet = 25,
energy = 40,
bomb = 20,
bio = 0,
rad = 30
which is basically both the items stats semi combined
Consistency
having the helmet have quite radically different stats to the armour is, personally, a dumb idea.
(if the stats are bad then i can edit the PR to only be a name change, since frankly i think thats more important)
also changed the names so its easier to find them and easiet to tell the two are from the same "set", also for consistency
:cl:
balance: rebalanced the technomancer helmet and insulated armour (now called insulated technomancer …

Technomancer armour changes

---

code/game/objects/items/weapons/grenades/flashbang.dm

Thermals users are now affected by flashbangs through walls.
Thermals have no counter and flashbangs need more use , this atleast gives IH the choice to trade confusion and deafness to flash the contractor using said thermals.
:cl:
balance: Flashbangs now affect thermal users through walls
/:cl:

Flashbangs now affect thermal users through walls.

---

maps/CEVEris/_CEV_Eris.dmm

title
I fucking hate railings on the trade beacons
:cl:
del: Vagabonds stole trade beacon railings
/:cl:

removes guild railings from trade beacons

---

code/game/objects/items/weapons/tools/mods/_upgrades.dm
code/modules/projectiles/guns/mods/mods.dm
code/modules/scrap/oldificator.dm

Faulty gun mods are no longer removable and added a var that can force gun mods to be irremovable. Rebalanced faulty mods so they can be both a asset and a detriment to a gun but overall the gun will still be usable.
Printing a gun currently has no drawbacks aside from being a noob trap and faulty gun mods are far too punishing.
:cl:
add: Added var that enables irremovable gun mods
tweak: faulty gun mod values, higher chance of faulty gun mod
balance: rebalanced faulty gun mods, no longer removable
/:cl:

Faulty guns and you!

---

code/modules/organs/external/_external.dm
code/modules/organs/organ.dm

External damage changed from  10 to 20 , 5 to 10 , 1 to 5
Internal damage changed from  9 to 32,  3 to  18 , 1 to 9
FBPs barely feel any pain , get armour by default , don't have to deal with blood. EMP's are often used against them but they yield no result , this should change it .
Organ health also got increased , so should the damage to keep up.
:cl:
balance: Rebalanced the emp damage taken by robotic organs and limbs, they now take on the average twice as much damage.
/:cl:

Increases the EMP damage deals to robotic internal and external organs
