code/modules/food/recipes_microwave.dm
=> recipes_microwave.dm,463

code/modules/organs/external/damage.dm
=> fix Runtime in damage.dm,79

code/modules/clothing/spacesuits/rig/rig.dm
=> fix runtime in rig.dm,643

code/game/objects/items/weapons/tanks/jetpack.dm
=> rig.dm,643

code/modules/mob/observer/ghost/ghost.dm
=> ghost.dm,170

code/game/machinery/doors/door.dm
=> door.dm,428

code/modules/sanity/breakdowns.dm
nerffs glassification
glass is annoying for a lot of players and punishing people with good sanity, this sould make it less. .. "bad"
tweak: glass breakdown now don't last 5mins anymore. now it lasts only 2. and happens 3times only in 20 secs intervals with 1 sec duration.
/:cl:
=> nerffs glass breakdown

code/modules/reagents/machinery/chem_dispenser.dm
You can now Alt-Click all Chem dispensers to detach the beaker.
:cl: Hopek
add: You can now Alt-Click the all Chem dispensers to detach the beaker.
/:cl:
=> Chem dispenser detach QoL

code/modules/reagents/machinery/grinder.dm
You can now Alt-click on grinders to detach their beakers.
:cl: Hopek
add: You can now Alt-click on grinders to detach their beakers.
/:cl:
=> Grinder detach QoL

code/modules/reagents/reagents/core.dm
**Discord order:** Slimes:
Buff fire extinguisher water damage. Right know it's actually faster to just melee them with the extinguisher.
Fire extinguisher is now a viable way to kill slimes.
:cl: Hyperio
tweak: Increase water damage done to slimes
/:cl:
=> Increase water damage done to slimes

code/modules/clothing/head/misc.dm
bandana time.
little changes
they no longer look ugly af
:cl:SrReptile
code: Blockhair added in the bandanas
/:cl:
=> bandanas now are properly shown

code/modules/organs/internal/lungs.dm
=> fix Runtime in lungs.dm,160

code/game/objects/items/devices/uplink.dm
=> fix Runtime in uplink.dm,155

code/modules/research/xenoarchaeology/artifact/artifact.dm
=> fix Runtime in artifact.dm,121

code/game/sound.dm
=> fix Runtime in sound.dm,435

code/modules/client/preferences_spawnpoints.dm
=> Fix Runtime in preferences_spawnpoints.dm,140

code/_onclick/item_attack.dm
=> Fix  Runtime in item_attack.dm,77

code/game/objects/items/weapons/tools/_tools.dm, code/game/objects/items/weapons/tools/mods/_upgrades.dm
was:
force = force * mults + mods
now:
force = force * (1 +  Σ(mults - 1)) + mods
one more nerf 
:cl:
balance: rebalanced formula for upgraded tool damage
/:cl:
=> modification for tools upgrade force formula

code/modules/projectiles/guns/energy/lasersmg.dm
Lasblender will now keep shooting things continuously for longer, with its lower charge cost.
I may of overdone the damage nerfs, making it nonviable for actual play, since it's overshadowed by the Atreides.
:cl:
balance: The Lasblender should perform better in-game now.
/:cl:
=> Lasblender readjustment

code/world.dm
Fixes the missing file for GC Qdel shutdown log
:cl:
server: Adds the log file in data/logs for Qdel
/:cl:
=> Quick addition for logging of GC

code/__HELPERS/logging.dm
=> Quick fix for QC logging

code/game/objects/items/weapons/storage/bags.dm
Fix an issue with the trashbag of holding appearing like a classic trashbag once you put something in it.
Sprite bug.
:cl: Hyperio
fix: Fix trashbag of holding sprite update
/:cl:
=> Fix icon update for trashbag of holding

code/game/objects/items/weapons/autolathe_disks.dm, code/game/objects/random/lathe_disks.dm
Fixes it
I'm fucking astounished by my stupidity
:cl:
fix: NT LP "Svalinn" autolathe disk has been fixed
/:cl:
=> Fix Svalinn autolathe disk

code/game/objects/items/weapons/tools/mods/mod_types.dm
I messed up with the copy paste so the booster toolmod had its own New() as well as the New() of the injector toolmod.
The injector had no New().
Fix bug.
:cl: Hyperio
fix: Fix booster and injector toolmods
/:cl:
=> Fix booster and injector toolmods

code/modules/multiz/ztravel/jetpack.dm
Fix animation bug
Less bugs is good, right?
:cl:
fix: fix z-move animation with jetpack
/:cl:
=> fix invisible with jetpack z moving

nano/templates/sanity.tmpl
I have problems with my internet and I can't upload the images, sorry.
the current ui is horrible.
:cl:
tweak: Make the Sanity ui less shitty
/:cl:
=> Make the Sanity ui less shitty

code/modules/core_implant/cruciform/machinery/cloning.dm
fix NT cloner unlimited biomatter bug
fixes a bug
:cl: Fernandos33
fix: NT cloner will not check if player is trying to add more sheets than it got
/:cl:
=> fix NT cloner unlimited biomatter bug

code/game/machinery/shower.dm
=> Shower runtime

code/modules/modular_computers/file_system/programs/engineering/shield_control.dm, code/modules/shield_generators/shield_generator.dm
=> Runtimes + log clarification if missing x y or z in shield control

code/modules/mob/living/carbon/human/human_defense.dm, code/modules/projectiles/projectile.dm, code/modules/projectiles/projectile/bullets.dm
:cl:
fix: bullets can leave shrapnel insidel the impacted organ
/:cl:
=> fix shrapnel logic

code/datums/datacore.dm, code/modules/mob/living/carbon/human/human_defense.dm
=> 2 runtimes. One in datacore.dm and one in human_defense.dm

code/modules/core_implant/cruciform/rituals/base.dm, code/modules/core_implant/cruciform/rituals/inquisitor.dm
This PR is a number of updates from around last year that never went through. The objectionable part of this PR (a reduction in the numbers needed to call a crusade) has been completely removed.
I do plan on furthering the litanies available to Neotheologists and perhaps giving more depth/diversity to the whole cruciform mechanic (without just buffing it), but I'd prefer to get this through first!
These additions were discussed and agreed upon a long time ago in discord and github, it seems that a number of my other suggestions have been added to the game in my absence. I feel that these are changes that people want and aren't objectionable. 
:cl:
add: The entreaty litany now calls out the area of the chanter.
tweak: The power cost of Bounty has been reduced to 1/5 of the previous, …
=> Neotheo QOL Tweaks

code/__DEFINES/holomap.dm, code/modules/multiz/map_data.dm
:cl:
refactor: improves the automatic centerling of the holomap and makes it more compatible with maps of different sizes.
/:cl:
=> holomap 1.5

code/modules/projectiles/guns/energy/plasma.dm
nerfs martyr fire rate
nerfs martyr fire rate
balance: nerfs martyr fire rate
/:cl:
=> martyr is a pistol not a LMG

code/__DEFINES/perks.dm, code/datums/perks/fate.dm, code/modules/mob/living/carbon/human/human_defines.dm
:cl:
fix: Fate perk: freelancer logic.
tweak: the oddity of the nobles now increases the sanity of whoever looks at it.
tweak: fate perk: alcoholic produces an increase in VIG and TGH when the user is drunk.
/:cl:
=> Tweak: Fates

code/modules/biomatter_manipulation/biogenerator.dm, code/modules/reagents/reagent_dispenser.dm, code/modules/research/xenoarchaeology/machinery/coolant.dm, maps/CEVEris/_CEV_Eris.dmm
recent conflicts erased an important part of the plumbing code. This brings back the things that were lost.
=> Plumbingfix

code/controllers/configuration.dm
Fixes a mistake in the config.
Mistakes are bad.
:cl:
config: fixed a small error related to sql in config
/:cl:
=> Small config fix

code/modules/admin/admin_verbs.dm, code/modules/admin/verbs/antiraid.dm, code/modules/client/client procs.dm
Ports the panic bunker whitelist from https://github.com/Skyrat-SS13/BoH-Bay/commit/9fe5b750d2f4d6fb6ba040ce36aa1e6fad3ab98c and makes the VPN whitelist button more clear.
More admin tools for population control, if they are ever needed.
:cl:
admin: added a panic bunker whitelist
/:cl:
=> Panic bunker whitelist

code/datums/craft/recipes/machinery.dm, code/game/atoms_movable.dm, code/game/objects/structures/window.dm, code/modules/biomatter_manipulation/biogenerator.dm, code/modules/biomatter_manipulation/bioreactor/biotank.dm, code/modules/biomatter_manipulation/solidifier.dm, code/modules/plumbing/ducts.dm, code/modules/reagents/reagent_dispenser.dm
:cl:
tweak: building dcuts is faster and cheaper.
tweak: the solidifier is compatible with the plumbing system.
tweak: the solidifier connector now points south.
/:cl:
=> solidifier update

code/game/objects/items/oddities.dm
:cl:
fix: runtime in technomancer oddities
/:cl:
=> fix runtime in oddities.dm, 29

code/game/objects/items/weapons/tools/_tools.dm
Was going through the coder shaming channel, and found this runtime.
Should prevent unwanted behaviour (Attacks being dropped, unique interactions being dropped, etc.)
Backend change, changelog shouldn't be required.
=> Fixes a runtime where a non-tool would be checked for tool qualities

code/modules/clothing/shoes/jobs.dm
reinfoced shoes
:cl:
fix: Moebius reinfoced shoes were replaced with Moebius reinforced shoes.
/:cl:
=> Fix an unacepptable, godawful, terrible fault in the code that is truly the worst defect in the Eris codebase

code/modules/shield_generators/floor_diffuser.dm, code/modules/shield_generators/shield.dm, code/modules/shield_generators/shield_generator.dm
No more shield flickering.
Increased cost on shield upkeep as every diffused tile is being correctly initialized with shields.
:cl:
tweak: Stationary shield diffusers are more responsive upon activation/deactivation. No more shield flickering.
/:cl:
=> Shield diffusers and shield recalculation

code/datums/loot_spawner.dm
:cl:
fix: fix the rarity value of all items
/:cl:
=> Spawn values fix 2

code/datums/datacore.dm
=> Fix runtime if no account number can be displayed in crew records detailed view

code/game/objects/items/weapons/tools/_tools.dm
Whoops, I accidentally runtimed the place. I did not expect L to be null. Which it would be if it is a tool, but doesn't share any of the required tool qualities
=> Get tooltype fix

code/__DEFINES/_extools_api.dm
this pr fixes the inability to use breakpoints to check code step by step
This makes my life significantly easier
:cl:
fix: improved development by allowing breakpoints to work
/:cl:
=> fixes debugger not showing line by line checking

code/modules/core_implant/cruciform/machinery/cloning.dm
Fixes the following:
**Exploit 1 (Massive):**
You can insert a negative number of biomass sheets in the biomass cloning container. For some dumb reason, it actually processes the negative number too which means if you put -99999 biomass inside you LITERALLY get a stack of 99999+ biomass sheets in your hand. Easiest massive exploit I've ever found.
**Exploit 2:**
When you insert more biomass sheets than what you currently have. The logic literally bypasses taking the sheets from your hand. So if you have 10 sheets in your hand and you put in 100, it will add the 10 sheets into the biomass container but won't take the 10 sheets from your hand so you can keep inserting it. 
**Bug:**
The cloning biocanister now doesn't give you a satisfying ping as intended when you do not insert any …
=> Fixes two massive NT exploits and removes shitcode. Biomatter container gives reality checks.

code/__DEFINES/plumbing.dm, code/datums/craft/recipes/machinery.dm, code/game/objects/items/weapons/autolathe_disks.dm, code/modules/plumbing/ducts.dm, code/modules/research/nodes/engineering.dm
adds an autolathe / protolathe design for fluid ducts, adds a new type of duct, and makes normal dcuts compatible with multilayer dcuts.
:cl:
add: fluid duct multilayered
add: fluid duct design
tweak: the fluid ducts now have can be of different layers.
/:cl:
=> plumbing update: multilayer

code/game/machinery/excelsior/ex_teleporter.dm, nano/templates/excelsior_teleporter.tmpl
Excelsior revs can call for reinforcements now!
Got no conscripts ready? Grab any excel and stuff him in. That's that simple. Check teleporter UI.
And no, ANY ghost can join in. Be a good communist, share your fun.
please, consider suggesting good messages, I'm not good at writing stuff
also, 15 minutes respawn reduction for rev is kinda wonky maybe
:cl:
add: Excelsior wants YOU to fight. Draft conscripts from outer space to aid your revolution. Send ~~asleep~~ any revolutioner to your Motherbase and replace them with fresh new blood with 20 minutes cooldown.
/:cl:
=> Excelsior draft

code/datums/craft/recipes/misc.dm
fixes smoking pipe craft
fixes smoking pipe craft
:cl:
fix: fixes smoking pipe craft
/:cl:
=> fixes smoking pipe craft

code/datums/craft/step.dm
Fixes being able to use anything to complete a material-requirement step
Fixes being able to use anything to complete an amount-requirement step.
No more breaking the laws of equivalent exchange.
=> [BOUNTY] Exploit: Fixes some crafting exploits

code/game/objects/items/weapons/trays.dm, code/game/objects/structures/bedsheet_bin.dm
:cl:
fix: trays un backpack
fix: bedsheets un backpack.
/:cl:
=> [BOUNTY] Bug: Some items can't be removed from bags

maps/CEVEris/_CEV_Eris.dmm
Fixes from bad placement because chairs are invisible on the byond map editor : https://cdn.discordapp.com/attachments/375588651599396866/761480643812261888/unknown.png
Instead, I replaced 2 tables with slot machines
=> Fixed Slot machines

maps/CEVEris/_CEV_Eris.dmm
This time, adds these stools chairs for slot machines.
=> Stool chairs added for slot machines

code/modules/clothing/glasses/misc.dm, code/modules/mob/living/carbon/human/human_helpers.dm
:cl:
fix: fix prescription glasses
/:cl:
=> [BOUNTY] BUG:  Prescription glasses don't work

code/modules/mob/living/carbon/human/inventory.dm
=> Quick fix for the return in suit_storage_equip

code/modules/goonchat/browserOutput.dm
Since the bug crashes the server, temp hotfix will do for now. Ported from https://github.com/BeeStation/BeeStation-Hornet/pull/2693
:cl:
fix: Better temp fix for crashing bug
/:cl:
=> Cookie fix

code/modules/reagents/reagents/core.dm, code/modules/reagents/reagents/dispenser.dm, code/modules/reagents/reagents/drugs.dm, code/modules/reagents/reagents/food-Drinks.dm, code/modules/reagents/reagents/medicine.dm, code/modules/reagents/reagents/nanites.dm, code/modules/reagents/reagents/other.dm, code/modules/reagents/reagents/stims.dm, code/modules/reagents/reagents/toxins.dm
fixes a lot of situations where reagents were executing human code on carbon mobs. and remove unnecessary variable declarations.
Less runtimes.
=> fix reagents logic

code/modules/shield_generators/shield_generator.dm
Quality of life code for Shield generator UI to prevent from losing track of this list as UI updates.
Helps to catch anyone who disabled the shield generator with a rogue computer or anything else like warnings.
:cl:
tweak: Shield Generator logging is sorted by new
/:cl:
=> The shield generator's logging is now sorted by new to old order.

code/datums/autolathe/clothing.dm, code/game/machinery/vending.dm, code/game/objects/items/weapons/autolathe_disks.dm, code/modules/clothing/head/armor.dm, code/modules/clothing/suits/armor.dm
functionally identical to: https://github.com/discordia-space/CEV-Eris/pull/5584 
except it's not awful to try to review
maintainers not being insane is generally a good thing
:cl:
add: Three new autolathe disks that can print armor can now be found in maintenance, one of which that can also be bought at an Asters Print-o-Mat. Two more disks that print IH faction armor can be found in the SecTech.
tweak: The SecTech now vends Ironhammer Miscellaneous Pack design disks.
/:cl:
=> armor disks but they're not hell to review

code/modules/projectiles/guns/launcher/projectile_grenade_launcher.dm
It worked before I added preloaded. I didn't test my code again after I added this - that's my bad, heehoo. This just makes it so the lake will spawn with a single frag shot, similar to how voidsuits spawn with a pair of magboots.
Things working is very good.
:cl:
fix: China Lake works for real this time. I promise.
/:cl:
=> China Lake hotfix

code/game/objects/items/weapons/tools/mods/_upgrades.dm, code/modules/projectiles/guns/mods/mods.dm
Fixes a bunch of bad description in weapon mod aspects
Fixes some typos in some weapon mods
Fixes being able to attach weapon mods to tools that shouldn't do anything.
No more "holy fuck, the forged barrel increases your firerate by 120%!"
:cl:
fix: misc weapon mod fixes
/:cl:
=> Weapon mod fixes

code/game/turfs/turf.dm
fix this:
:cl:
fix: missing footsteps sounds 
/:cl:
=> fix Runtime in turf.dm,273

code/modules/hivemind/machines.dm, code/modules/mob/living/carbon/breathe.dm
=> fix Runtime in machines.dm,485

code/game/atoms.dm, code/modules/mechs/mech_interaction.dm, code/modules/mechs/mech_life.dm, code/modules/mob/living/life.dm, code/modules/mob/mob_defines.dm, code/modules/mob/mob_helpers.dm
Mech vision now works correct
Fix mech vision
:cl:
fix: Mech vision works correct
/:cl:
close #5054
=> fix mech vision

code/modules/mob/living/silicon/robot/drone/drone_damage.dm
:cl:
fix: Fixes drones and blitzshells annihilating the master controller (and other drone health related issues)
/:cl:
=> Fixes drones causing infinite loops

code/datums/objective/individual_objective/common.dm, code/datums/objective/individual_objective/guild.dm, code/modules/mob/living/carbon/carbon.dm, code/modules/mob/living/carbon/human/life.dm, code/modules/mob/living/carbon/superior_animal/roach/types/bluespace.dm, code/modules/mob/living/carbon/superior_animal/roach/types/roachling.dm, code/modules/mob/living/carbon/superior_animal/roach/types/support.dm, code/modules/mob/living/carbon/viruses.dm, code/modules/mob/living/life.dm, code/modules/mob/living/silicon/pai/life.dm, code/modules/mob/living/silicon/pai/pai.dm, code/modules/mob/living/simple_animal/hostile/stranger.dm, code/modules/mob/living/simple_animal/simple_animal.dm, code/modules/sanity/breakdown.dm, code/modules/virus2/disease2.dm
Much code continues to run even when the player is dead, often with no reason to run, this pr prevents it.
fewer unnecessary processes.
:cl:
tweak: "personal objectives" stop updating when the player is dead.
tweak: bluespace roaches no longer teleport when their AI is idle.
tweak: You cannot get a virus while you are dead. 
tweak: All breakdowns end when you die.
/:cl:
=>  minor mob optimization.

code/game/machinery/adv_med.dm
Small changes to the body scanner to make it nicer.
:cl:
add: Alt clicking a body scanner will eject the occupant
add: Body scanners now put the name of the occupant on the output and name the printed paper after the occupant
spellcheck: Fixed a typo in the body scanner printout
/:cl:
=> Body Scanner QoL

code/modules/organs/internal/internal_organ_processes.dm
:cl:
fix: fixed a runtime in erismed
/:cl:
=> Erismed runtime fix

code/game/machinery/excelsior/ex_teleporter.dm
i changed the cost of excel uniforms from 100 to 50 in the excelsior teleporter
makes excelsior more likely to wear their own uniforms. (this is a learning PR. im learning to use github and figuring out how to code)
:cl:
tweak: tweaked excelsior jumpsuit cost from 100 to 50
/:cl:
=> Excelsior Jumpsuit cost reduction

code/game/objects/items/weapons/grenades/flashbang.dm
make flashbang great again
:cl:
tweak: Flashbang now confuses you.
/:cl:
=> Flashbang now makes you walk in a random direction

code/__DEFINES/weapons.dm, code/modules/projectiles/gun.dm, code/modules/projectiles/gun_firemode.dm
Fixing fire rates in #5644 
Fix
:cl:
fix: Guns fire rate are working as intended
/:cl:
=> guns damage multiplier changes

code/game/objects/items/weapons/implant/implants/carrion/control_spider.dm
So we know whodunwhat when the preacher suddenly whips out a shotgun and blows away the bartender, an agrolyte, and then themself.
Admin feedback good
:cl:
admin: Control spiders now tell you who is taking over who
/:cl:
=> Control spiders now warn admins when they've taken over somebody

nano/templates/centrifuge.tmpl
Centrifuge now doesn't require codediving to figure out what the buttons do.
Just adds some brief explanations as to what each mode does.
Having to codedive to cure a virus sucks.
:cl:
tweak: The virology centrifuge UI is a little more informative
/:cl:
=> Centrifuge made straightforward

tools/changelog/ss13_genchangelog.py
Stops annoying Github actions failure spamming
=> Update ss13_genchangelog.py to stop from having failure with yaml loader

code/controllers/subsystems/jobs.dm, code/modules/mob/living/carbon/human/human.dm, code/modules/organs/internal/internal_organ_processes.dm
:cl:
fix: borgs no longer spawn with a cruciform..
/:cl:
=> [BOUNTY] borgs no longer start with a cruciform.

code/game/objects/items/weapons/storage/fancy.dm, code/game/objects/items/weapons/storage/storage.dm
:cl:
tweak: now you can close the lid of the cigarette box.
/:cl:
=> [BOUNTY] Allows you to open and close the lid of the cigarette box.

html/changelogs/AutoChangeLog-pr-5436.yml
Exactly what it says, no description needed, maintenance PR
=> unfucks the changelog

html/changelogs/CeUvi-new-tech-sprotes.yml
=> Fixes this file

README.md
The link is dead and gone replaced by a website of strange stuff. Removing it now.
=> Removal of dead link in README.MD

maps/dungeons/deepmaint/deepmaint.dm
Although the documentation explains why we need three levels, the individual features of each level have not yet been implemented, resulting in three identical levels that consume a lot of resources.
our hamsters will have to work less.
:cl:
tweak: reduce deepmaint levels to 1
/:cl:
=> reduce deepmaint levels to 1

code/game/machinery/autolathe/autolathe.dm, code/game/machinery/excelsior/ex_teleporter.dm, code/game/objects/items/weapons/tools/_tools.dm, code/modules/reagents/machinery/centrifuge.dm, code/modules/reagents/machinery/electrolyzer.dm, code/modules/reagents/reagent_containers/hypospray.dm, code/modules/reagents/reagent_containers/syringes.dm
Someone forgot a comma. I've put it back
no more random pings from excel lathe in maints
:cl:
fix: fixed a missing comma in some files
/:cl:
=> playsound fixed

code/game/machinery/adv_med.dm
closes a font change on the adv_med machine. Oversight.
:cl:
/:cl:
=> Fixes a missing font closure

code/__DEFINES/sanity.dm, code/modules/mob/living/carbon/human/human.dm, code/modules/mob/living/carbon/human/inventory.dm
Original coder meant to divide by MIN_HUMAN_STYLE not MAX_HUMAN_STYLE which led to the negative number turning positive. I also fixed the typo in the define's name
:cl:
fix: Fixed negative style working like it was positive
/:cl:
=> Fixes negative style working like positive style

code/__HELPERS/artwork_names.dm
fixes a small error in the item descriptions made by the artist.hy you think these changes would benefit the game. If you can't justify it in words, it might not be worth adding. -->
:cl:
fix: descriptions of artwork.
/:cl:
=> fix descriptions of artwork.

code/modules/modular_computers/file_system/reports/report_field.dm
Fixes a glitch that gave players infinate money.
Infinate money is not good.
:cl:
fix: fixed an exploit that could give you infinate money
/:cl:
=> Infinate money fix

code/modules/sanity/sanity_mob.dm
Only the ethanol subtypes are supposed to increase sanity, not the ethanol itself.
:cl:
fix: ethanol (parent) no longer increases sanity.
/:cl:
=> ethanol (parent) no longer increases sanity.

code/modules/projectiles/ammunition/magazines.dm, code/modules/projectiles/guns/projectile/pistol/gyropistol.dm, strings/loot_data/all_spawn_data.txt, strings/loot_data/all_spawn_paths.txt, strings/loot_data/blacklist.txt, strings/loot_data/tags/ammmo_storage.txt, strings/loot_data/tags/ammo.txt, strings/loot_data/tags/clothing.txt, strings/loot_data/tags/gun.txt, strings/loot_data/tags/gun_projectile.txt, strings/loot_data/tags/guns.txt, strings/loot_data/tags/head.txt, strings/loot_data/tags/item.txt, strings/loot_data/tags/mask.txt, strings/loot_data/tags/obj.txt, strings/loot_data/tags/shotgun.txt, strings/loot_data/tags/under.txt
see changelog
The gyropistol is not supposed to be accessible to players.
:cl:
tweak: gyropistol no longer spawns in maint.
tweak: cal .70 has less spawn frequency.
/:cl:
=> gyropistol no longer spawns in maint.

code/game/objects/items/weapons/implant/implant.dm, code/modules/surgery/surgery_ui.dm
Fixes a bug where the UI would break if a person was cruciformed, fixed a bug here the same implant could be imlanted into the same person multiple times
(same ref)
Bugs are bad
:cl:
fix: fixed a surgery UI bug where the UI would break if a person was cruciformed
fix: fixed a bug where the same implant would show up twice in the UI
/:cl:
=> Erismed UI bugfixes

code/__DEFINES/mobs.dm, code/game/objects/items/weapons/maneki_neko.dm, code/game/objects/items/weapons/tools/mods/mod_types.dm, code/modules/mob/living/carbon/human/human.dm, code/modules/mob/living/life.dm, code/modules/mob/living/living_defense.dm, code/modules/mob/mob.dm, code/modules/reagents/enricher.dm, code/modules/reagents/reagent_containers/glass/bottle.dm, code/modules/reagents/reagents/other.dm
Are you tiered of Molitor-Riedel Enricher uselessness? Are you screaming in discord "Add defib god dammit"?
Then this update it's for you!
This update improving Molitor-Riedel Enricher, made him making no blood but "resuscitator"!
A new reagent incredibly rare cardiac stimulant, that reanimate recipient heart! (WARNING! Effect works only if recipient have heart, brain and died in range of 5 minutes.)
Making Molitor-Riedel Enricher useful, and approving request about adding defib.
:cl: DarkLevel - code, Matt - code(resuscitator base).
add: resuscitator reagent
balance: Molitor-Riedel Enricher now produce resuscitator.
fix: maneki neko now will work properly.
fix: sanctifier is no longer spawns in maintenances.
/:cl:
=> Molitor-Riedel Enricher improved

code/modules/reagents/enricher.dm
:cl: DarkLevel
fix: Fixing some enricher old text
/:cl:
=> Fixing some enricher old text

code/modules/clothing/masks/breath.dm
Adds an action button(the button in the top left corner of the screen) for toggling the breath mask. There was already a verb but most people are used to an action button.
Action buttons are cool
:cl:
add: Added an action button for toggling breath masks
/:cl:
=> Adds action button for toggling breath masks

code/modules/sanity/sanity_mob.dm
see changelog.
this fixes a bug.
:cl:
fix: The desires are displayed in the chat.
/:cl:
=> The desires are displayed in the chat.

code/modules/mob/living/carbon/superior_animal/ai.dm
A previous optimization attempt actually left us worse off in a few aspects.
Roaches being aggro'd on monkeys through walls sucks.
:cl:
fix: Roaches and spiders can no longer hunt you through walls.
/:cl:
=> Reverts the ability for roaches to see through walls

code/modules/projectiles/guns/projectile/automatic/maxim.dm, strings/loot_data/all_spawn_data.txt, strings/loot_data/blacklist.txt
excel machine gun keeps popping up on gun spawner, it's functionally the same as a PK more or less save for one bit, it can't be fired while **wielded.**
This fixes that, also makes it that you have to wield the damn thing to fire, maybe PK should need two hand to fire as well?
unbroke the broken machine gun
:cl:
fix: Fixes Excelsior Machine Gun
/:cl:
=> Excelsior Machine Gun

code/game/machinery/computer/guestpass.dm, code/game/objects/items/weapons/cards_ids.dm
Removes the Read ID Card verb for ID cards and instead gives you those informations when simply examining it
:cl:
tweak: Read ID Card verb was removed, its code got merged with examine
/:cl:
=> QoL change for IDs

code/game/machinery/doors/door.dm
idk
:cl:
fix: The door flickers if you do not have access but you click on it
/:cl:
=> the doors now flickers when you click on it

code/modules/organs/body_modifications.dm
All jobs can now pick most of the body prosthesis again.
Player feedback improved
I am being bullied
:cl:
fix: Body prosthesis is now not limited by faction again
/:cl:
=> Body Prosthesis fixes

code/game/objects/items/stacks/medical.dm, code/modules/core_implant/cruciform/machinery/eotp.dm, code/modules/reagents/reagent_containers/syringes.dm
Now The NeoTheologian Medkit will cost 80 BIOMATTER to make.
No more basic melee disk reward.
Now EotP will spawn each disk once before going back through the list.
:cl: DarkLevel
fix: EotP first day fix
/:cl:
=> EotP first day fix

code/datums/wires/jukebox.dm
Removes the ability to turn off the "parental guidance" on the jukebox
Having every round be filled with people shouting about cum and fucking trucks is proving detrimental to the quality of the server
:cl:
del: Removes the ability to hack the jukebox for meme songs
/:cl:
=> Removes jukebox hacking

code/game/antagonist/station/revolutionary/excel_faction.dm
Literally just teleports the excel stash to the first person to press the summon button. Anyone who tries to do it after will just be told that [X] teleported it to themself, so they know who to blame when it's stolen by ironhammer/moebius/guild.
No more hunting and counterhunting powergaming for stashes, no more excel suffering because their stash teleported into the AI core, or landed at the feet of a vagabond.
:cl:
tweak: The excelsior stash now has to be summoned, by a member of excelsior.
/:cl:
=> Literally just teleport the stash to the person

code/modules/clothing/head/armor.dm, code/modules/clothing/suits/armor.dm
:cl: DarkLevel
balance: Crusader armor now have bullet/energy protection 50 instead of 30
/:cl:
=> Crusader Armor Changes

code/modules/biomatter_manipulation/solidifier.dm
what the title says.
because reasons 
:cl:
fix: solidifier no longer crashes the server.
/:cl:
=> solidifier no longer crashes the server.

code/game/objects/items/weapons/space_harpoon.dm
Attempting to jump into a wall will now telefrag you.
I was informed that you can, indeed, just jump onto a wall then teleport to either of the rooms that wall is part of.
This should prevent some illicit access from being gained with it.
I elected to not have it telefrag others than the user, as you can just build a wall on the turf you're on and bring others in, telefragging them.
:cl:
balance: Using the Harpoon to teleport onto a wall now telefrags you.
/:cl:
=> Harpoon nerf beta

code/modules/surgery/surgery_ui.dm
Issue was it was looking for an owner that did not exist.
I can now chop into a mans severed leg and pull out his augs.
:cl:
fix: The surgery UI on amputated limbs now works again.
/:cl:
=> Fixes the surgery UI on amputated limbs not showing properly.

code/modules/mob/living/carbon/human/inventory.dm, code/modules/mob/mob_helpers.dm
the get_max_w_class proc was not working as it should.
:cl:
code: fix get_max_w_class proc
/:cl:
=> fix get_max_w_class proc

code/__DEFINES/perks.dm, code/game/antagonist/antagonist.dm, code/game/antagonist/outer/mercenary/mercenary.dm
Serbians now will have IH perk "Survivor".
:cl: DarkLevel
balance: Serbians now spawns with SURVIVOR perk
code: Add perks value to antags
/:cl:
=> Serbian Survivor

code/__DEFINES/weapons.dm, code/game/machinery/autolathe/artist_bench.dm, code/modules/mob/living/simple_animal/hostile/stranger.dm, code/modules/projectiles/gun.dm, code/modules/projectiles/gun_firemode.dm, code/modules/projectiles/guns/energy.dm, code/modules/projectiles/guns/energy/egun.dm, code/modules/projectiles/guns/energy/floragun.dm, code/modules/projectiles/guns/energy/nuclear.dm, code/modules/projectiles/guns/energy/plasma.dm, code/modules/projectiles/guns/energy/shrapnel.dm, code/modules/projectiles/guns/matter/launcher/nt_sprayer.dm, code/modules/projectiles/guns/projectile.dm, code/modules/projectiles/guns/projectile/automatic/maxim.dm, code/modules/projectiles/guns/projectile/automatic/z8.dm, code/modules/projectiles/guns/projectile/pistol/olivaw.dm, code/modules/projectiles/guns/projectile/shotgun/bull.dm, code/modules/projectiles/guns/projectile/shotgun/doublebarrel.dm, nano/templates/weapon_stats.tmpl
Makes the weapon info page a little more informative 
- Adds a description to most firemodes
- If a firemode doesn't change anything stat-wise, it won't show nulls
- If a firemode changes the projectile, it tells you the projectile's name
Planned:
- Show damage values of the projectile the weapon will fire.
- Show what a weapon's gunmods does for the weapon.
More informative.
:cl:
add: The weapon info page has been improved
/:cl:
=> Weapon stats page improvements

code/modules/clothing/suits/armor.dm, code/modules/clothing/suits/neotheology.dm
Fixes some oversights with NT armor (hair poking through acolyte hood and crusader armor not covering the legs and arms despite it doing so visually).
Fixes minor oversights.
:cl:
tweak: Made NT crusader armor cover legs and arms.
fix: Made hair not poke through acolyte hood. 
/:cl:
=> Minor NT armor tweaks

code/modules/core_implant/cruciform/machinery/eotp.dm
Me: NO! YOU CAN NOT PICK FROM THE EMPTY LIST!
EOTP: RUN TIME MACHINE GOES BRRRRRRR!
:cl: DarkLevel
fix: EOTP runtimefix
/:cl:
=> EOTP runtimefix

code/defines/procs/announce.dm, code/game/gamemodes/events/hivemind_invasion.dm, code/modules/hivemind/machines.dm, code/modules/hivemind/mobs.dm, code/modules/hivemind/objects.dm, code/modules/hivemind/self_defense.dm, code/modules/hivemind/wires.dm
Hivemind balance is once more thrown off the rails.
This PR includes name and description changes, primarly capitalizing names
Along with buffs and nerfs for the hivemind, such as:
Reducing maneater (now Mechiver) HP and (a bit) damage dealing via its special ability
Removed certain useless comments I made before
Nerfs tox damage of the goo projectile
Reduces cooldown of tormentor (head on a tendril) while also greatly increasing cooldown of shockwave ability for the core
Tweaking rarity_value of mobs
Wires now deal more damage to doors and have a higher chance of unlocking them
Increases time for hivemind to be announced
Fixed ressurected mobs description
This PR also prepares room for a new hivemob in the future, along with a projectile it will be firing
At the moment the code does …
=> Hivemind rebalance fuckery part 2 the reckoning.

code/modules/reagents/reagents/stims.dm
MBR was broken, now it is fixed
Sometimes you just want an edge on mechanical, so you need some spicy machine coffee
:cl:
fix: Machine binding ritual now actually gives some stats
/:cl:
=> Fixes machine binding ritual not working

code/game/machinery/jukebox.dm
the jukebox registers as badly initialized according to the atom subsystem. This fixes it.
=> fix jukebox initialization.

code/datums/setup_option/backgrounds/origin.dm
Adds a colony of australians who live in Mad Max-ville, sending out criminals to work as pathfinders in nullspace for vital supplies.
Changelog
🆑
add: Eureka, an australian death world, is now a background for char setup.
/🆑
=> Eureka, a colony of Australians!

code/game/objects/items/weapons/nt_melee.dm, code/game/objects/items/weapons/shields.dm, code/modules/mob/living/carbon/human/human_defense.dm, code/modules/mob/living/carbon/human/human_movement.dm, code/modules/mob/living/carbon/superior_animal/roach/attack.dm, code/modules/mob/living/living_defines.dm, code/modules/mob/mob.dm
(30 Melee protection was shifted to 20, so you cannot do a 100 melee armor)
:cl: DarkLevel
balance: Reworked NT and IH shields to provide armor increase and lesser knockdown immunity instead of block chance.
/:cl:
=> Shield Rebalance

code/game/objects/items/weapons/tools/mods/_upgrades.dm, code/modules/projectiles/guns/mods/mods.dm, code/modules/scrap/oldificator.dm
Adds a bunch of junk gunmods that may appear on older weapons, that will need correcting/removing
Adds a bit of correctable character to guns you find while junkdiving
:cl:
add: Old guns can now have faulty weapon mods on them, that require removal.
/:cl:
=> Old gun junk mods

maps/CEVEris/_CEV_Eris.dmm
Testing FastDMM2. Added cabinet to medbay exam room. Fixed scrubber and vent in VIP bar using the wrong pipes.
https://media.discordapp.net/attachments/790574950447972434/790577105183178772/unknown.png?width=306&height=473
please god let me make PRs without conflicts 
:cl:
add: Added cabinet to medbay examination room
fix: fixed scrubber and vent in VIP bar using the wrong pipes
/:cl:
=> Testing FastDMM2

code/modules/research/research.dm
Patches the R&D accumulating points from researching technology nodes instead of losing points from researching technology nodes bug.
Using advice from @Evankhell561 on the CEV Eris Discord.
There may still exist other bugs in the recent Research code changes but I ain't sure.
People now have to progress through the tech trees on the R&D console by continuing to deconstruct and perform other activities to accumulate points rather than being able to research all items with a minimum amount of points meaning that people have a reason to deconstruct items beyond the first couple points.
Removes the ability for people to research all tech with minimal points which can take out of a unique situation what we ain't seen before.
:cl:
fix: r&d console no longer gains points from researching tech …
=> Research Point Accumulation Bug Patch

code/game/gamemodes/scores.dm
this was designed to average 250 negative points. However, he is currently overweight in the NT score.
:cl:
tweak: Dirty areas have a lower penalty on the NT score.
/:cl:
=> Dirty areas have a lower penalty on the NT score.

code/modules/projectiles/guns/projectile/pistol/olivaw.dm
The Olivaw now costs money in the vendor again
*dab
:cl:
fix: The Olivaw is no longer costs 0 credits in the vendor
/:cl:
=> Oliwav costs money again

code/game/machinery/autolathe/autolathe.dm, code/game/machinery/autolathe/nanoforge.dm
:cl:
fix: Only technomancer or players with a high MEC stat can use the nanoforge.
/:cl:
=> You can only use the nanoforge if you meet its requirements.

code/datums/uplink/highly visible and dangerous weapons.dm, code/game/objects/items/weapons/storage/uplink_kits.dm
Title
I will leave you to prepare.
:cl:
tweak: the uplink AMR now comes in a briefcase.
/:cl:
=> The uplink AMR now comes in a briefcase

code/datums/perks/fate.dm
the perk is randomly selected.
It was a suggestion that I received.
:cl:
tweak: Nobles inheritance now has a perk.
/:cl:
=> Nobles inheritance now has a perk.

code/datums/contract.dm, code/game/objects/items/weapons/storage/boxes.dm, code/modules/cargo/packs.dm, code/modules/organs/external/_external.dm
fixes a bug with the ablative vest 
fixes a bug with performing surgery on separated limbs
In preparation for the day trash is nerfed
- The IH ballistic armor pack now contains actual IH ballistic armor and the gamer NVG helmets, too. They should not be trash exclusive
- The FS assault pack had one atreides (which you can already buy from the vendor) replaced with a bulldog. Price remains unchanged because you can't tell me I'm going to be able to sell these 3 guns for a profit at that price.
- The ablative armor crate now comes with ablative helmets instead of normal helmets.
- The kitchen crate now contains universal enzyme bottles.
- Lowered the price of the surplus crate since it only contains low quality guns.
- The experimental weapons pack has been renamed to incendiary weapons …
=> cargo crates update+bug fixes

code/datums/craft/item.dm, code/datums/craft/recipe.dm, code/datums/craft/recipes/clothing.dm, code/datums/craft/recipes/guns.dm, code/datums/craft/step.dm
these weapons were being created from armor parts rather than gun parts
the craft system was broken.
:cl:
fix: handmade revolver recipe
fix: handmade bolt gun recipe
fix: Scavenger armor recipe
fix: Makeshift armored void suit recipe
fix: craft system
/:cl:
=> fix some gun recipes.

code/modules/clothing/clothing.dm, code/modules/clothing/under/color.dm, code/modules/scrap/scrap.dm
fix this:
items without an appropriate item should not appear in maint
:cl:
fix: add a debug item called "under" to the blacklist
tweak: the default name for jumsuit is "jumsuit"
/:cl:
=> adds a debug item to the blacklist

code/datums/craft/step.dm
this pr makes the craft system work as it should.
:cl:
fix: Material requirements no longer disappear when crafting an item.
/:cl:
=> Another fix to the craft system

code/__DEFINES/projectile_defines.dm, code/__DEFINES/spawner/_spawner.dm, code/game/objects/items/weapons/stock_parts.dm, code/modules/projectiles/guns/projectile/automatic.dm
RANGE_BIOMES has no reason to exist.
STOCK_PARTS_BASE_RARITY_VALUE encourages writing code that Ree does not approve of.
.35 auto does not exist and causes confusion
=> .35 auto is a lie - removes some unused definitions.

code/modules/core_implant/cruciform/cruciform.dm
fis this:
:cl:
fix: Preacher no longer sends spam messages constantly.
/:cl:
=> Removes a debug tool that was spamming.

code/modules/core_implant/cruciform/cruciform.dm, code/modules/core_implant/cruciform/upgrades.dm
fix this:
:cl:
fix: score for converting players to the church.
/:cl:
=> fix score for converting players to the church.

code/game/objects/random/purerandom.dm, code/modules/scrap/scrap.dm, code/modules/stashes/stash_spawner.dm
1. the trash piles are less likely to spawn a rare item.
2. stash spawners were becoming too common, this pr changes that.
:cl:
tweak: the trash piles are less likely to spawn a rare item.
tweak: stash spawner is less frequent to find.
/:cl:
=> the trash piles are less likely to spawn a rare item.

code/game/objects/items/weapons/candle.dm
candles now restore sanity to those who see them
because the design document demands it.
because of the design document.
:cl:
tweak: candles now restore sanity to those who see them
/:cl:
=> candles now restore sanity to those who see them

code/game/objects/items/weapons/sword_of_truth.dm, code/modules/core_implant/cruciform/machinery/cloning.dm, code/modules/core_implant/cruciform/rituals/group.dm
the damage of the Sword of Truth increases when the crusade ritual is performed.
design document.
:cl:
tweak: the damage of the Sword of Truth increases when the crusade ritual is performed.
/:cl:
=> Sword of Truth now increases its power when the crusade is activated.

code/datums/craft/step.dm
As long as you had at least one unit of material in your hand, you could build anything in the craft system.
fix a bug
:cl:
fix: you can no longer craft items with less materials than required.
tweak: warning messages in the craft system now appear in red.
/:cl:
=> another fix to the craft system.

code/modules/core_implant/cruciform/machinery/eotp.dm, code/modules/core_implant/cruciform/rituals/group.dm
these rituals were totally useless, they never worked at all. (I know this from reports and because the code itself makes no sense).
With this pr, the rituals to increase stats now increase them permanently by 2. The condition for these rituals to work is that the EOTP has performed a miracle.
Design doc.
:cl:
tweak: Every time the EOTP performs a miracle, you can use the rituals to increase stats.
tweak: stat boosting rituals now permanently increase one stat by 3+2 for each participant.
/:cl:
=> Stats ritual rework

code/modules/core_implant/cruciform/cruciform.dm, code/modules/core_implant/cruciform/rituals/priest.dm
the score gained by converting new disciples previously increased when a cruciform is installed and that leads to having to apply a lot of checks to protect the code from many sploits and weird situations.
this pr makes that score increase when the epiphany ritual is performed properly, which has many more advantages, it is more atomic code and in general it is cleaner.
Avoid some sploits in the game.
:cl:
tweak: convert score now increases every time an epiphany ritual is performed.
/:cl:
=> convert score tweaks

code/modules/core_implant/cruciform/machinery/cloning.dm, code/modules/core_implant/cruciform/rituals/base.dm, code/modules/core_implant/cruciform/rituals/machinery.dm, code/modules/core_implant/cruciform/rituals/priest.dm
this pr is focused on making it possible for any disciple to resurrect other NT members.
because design doc
:cl:
tweak: reincarnation and Commitment can now be performed by any disciple of nt.
tweak: cloning now produces cloning damage depending on who has activated the cloning machine.
/:cl:
=> reincarnation and Commitment ritual now be performed by any disciple of nt.

code/modules/hivemind/machines.dm, code/modules/mob/living/carbon/hallucinations.dm
Removes bad words that may have a negative effect on our codebase.
Literally 1969
:cl:
del: Removed bad words
/:cl:
=> Removes bad words

code/__DEFINES/is_helpers.dm, code/game/machinery/kitchen/gibber.dm
Fixes old gibber issue.
:cl:
fix: gibber now spawns correct meat
code: added isroach check
/:cl:
=> Gibber, now with real roach meat

code/modules/reagents/reagent_containers/food/snacks.dm
Fixes being able to endlessly heat MRE.
:cl:
fix: Fixes being able to endlessly heat MRE
/:cl:
=> MRE endless heating fix

code/modules/modular_computers/file_system/programs/generic/email_client.dm
Adds more convenient way of checking messages for admins. 
:cl:
add: email now properly logged.
/:cl:
=> Proper email logging for admins

code/modules/core_implant/cruciform/rituals/priest.dm
from design doc:
> To Uphold the Holy Word
> Replaces the Toughness, Robustness, and Vigilance prayers. Can be cast by any Acolyte or Preacher, alone or in groups. This ritual temporarily increasesthose stats by 10(?) of anyone who hears it.
> Grace of Perseverance
> Replaces the Cognition, Mechanical, and Biology prayers. Can be cast by any Acolyte or Preacher. Can be cast alone, or in groups.  This ritual temporarily increases those stats by 10(?) of anyone who hears it.
:cl:
add: To Uphold the Holy Word and Grace of Perseverance rituals
del: priest rituals: increase of stats.
/:cl:
=> new rituals

code/datums/uplink/highly visible and dangerous weapons.dm, code/modules/hivemind/machines.dm, code/modules/hivemind/mobs.dm, code/modules/hivemind/objects.dm
For ~~april fools~~ very serious PR with serious results
also removes pickles from the uplink as asked by our God-Emperor
Pickles are funny
~~none of us are free of sin~~
:cl:
balance: Rebalanced the hivemind to be more enjoyable to fight against
/:cl:
=> Pickle mind

code/modules/economy/price_list.dm
Decreases the amount of money guild produces tenfold
:cl:
fix: Tobacco demand have been increasing too much lately, cigarette prices have lowered in accordance to demand.
/:cl:
=> Delete the monopoly

code/modules/reagents/reagent_containers/food/drinks.dm
Whenever you moved while gulping down the contents of a bottle, it would just make you down it all instantly. Now it will instead splash all of its content on you, as intended (probably).
Squash bugs, lift code, get buff
:cl:
fix: Moving while gulping something down will splash everything on you now
/:cl:
=> Fixes gulping down

code/modules/projectiles/projectile/beams.dm, code/modules/projectiles/projectile/bullettypes.dm
Since you can very easy cheese players with it. Not anymore.
it's realistic, but not balance wise
:cl:
balance: AMR is less OP now
/:cl:
=> removes stun from AMR

code/game/objects/items/oddities.dm
Replaced "maded" with "created" in oddity decription that were made by the cube
Makes us look like we know english
:cl:
spellcheck: Oddities description that are made by Techno-Tribalist Enforcer are now "created" rather than "maded"
/:cl:
=> All oddities made by Techno-Tribalism Enforcer will be created rather than maded

code/game/objects/items/devices/hacktool.dm
Fixes a typo
Makes us look like we know english
:cl:
spellcheck: Hach mode on hacktool was replaced with hack mode.
/:cl:
=> Replace hach with hack mode on hacktool

code/modules/clothing/suits/armor.dm
This fixes a typo and makes description looks better.
Makes us looks like we actually know english.
:cl:
spellcheck: God now protects those who defend his faith rather than those who believe while wearing crusader armor.
/:cl:
=> Fix a typo that occurs every time when someone looks at the crusader armor

code/modules/virus2/effect.dm
when editing something through github with access rights github automatically chooses to commit directly to master rather than make a separate pull request
so I didn't untick that option
=> unfuck the commit to master

code/game/objects/items/weapons/design_disks/autolathe_disks.dm
This is just me wanting to have more variety in the one-off Excel disks than the Drozd
I noticed how only the Drozd was able to be found in disks, and thought that it was odd to only have one Excelsior gun printable by non-infiltrators. As such, I decided to make the disks myself. 
:cl:
add: Added 4 new Excelsior disks, in the style of the Drozd disk that was already found.
/:cl:
=> More Excelsior Disks

code/game/machinery/vending.dm
Fixes cigs prices in vending machines without me doing unspoken things
Cigs have prices, both who lacked it, also fixes some issue that i had first time.
:cl:
fix: Cigs have prices
/:cl:
=> Fix Cigs part 2

maps/CEVEris/_CEV_Eris.dmm
Fixes formatting issue from removing all the tags from the map, should resolve readability issues on future PRs.
Should improve readability on map PRs that are currently being PR'd.
:cl:
code: Mapfile format readability quick-fix.
/:cl:
=> [HOTFIX] Quick Map Formatting issue

code/game/objects/structures/crates_lockers/closets/syndicate.dm, code/modules/clothing/head/mindreader.dm, code/modules/clothing/under/mercenary.dm, code/modules/projectiles/guns/projectile/other/RPG.dm, code/modules/shield_generators/handheld_diffuser.dm
:cl:
add: RPG, traitor uplink, mindreader and several other debug items were removed from maints.
/:cl:
=> adds some new items to the maint blacklist.

code/game/objects/items/devices/techno_tribalism.dm
this fixes 2 typos that have been grinding my gears for ages
typo fix good
:cl: Joooks
spellcheck: fixed 2 typos in techno cube
/:cl:
=> Fixes a few typos in the techno cube

code/modules/virus2/effect.dm
Deletes monkism syndrome since we cannot turn people into monkeys and vice versa.
Reject monkey
:cl:
del: Every CEV Eris crewman, including vagabonds, have been vaccinated against monkism syndrome. Reject monkey, return to modernity.
/:cl:
=> Remove Monkism symptom, for real this time

code/modules/core_implant/cruciform/rituals/base.dm
see changelog.
NT update
:cl:
tweak: the Cruciform sense litany now scans everyone around the one performing the ritual.
/:cl:
=> Cruciform sense buff

code/game/objects/items/weapons/autopsy.dm, code/modules/core_implant/cruciform/rituals/priest.dm
it seems that the code was checking if the corpse was from Moebius instead of checking if the user was from that department.
:cl:
fix: autopsy score
/:cl:
=> autopsy score fixes

code/modules/core_implant/cruciform/rituals/priest.dm
:cl:
fix: the message that appears when performing an offering ritual is now in English.
tweak: offering rituals now let you know what to offer.
/:cl:
=> offerings fixes

code/modules/core_implant/cruciform/machinery/obelisk.dm, code/modules/core_implant/cruciform/rituals/group.dm, code/modules/core_implant/cruciform/rituals/priest.dm
see changelog.
NT update
:cl:
tweak: now when performing the sanctify ritual, all obelisks, temporarily, function as if they have an NT member in their vicinity.
/:cl:
=> Sanctify ritual buff

code/game/objects/items/weapons/material/material_weapons.dm
25 damage, 15 thrown max
No fun allowed
:cl:
del: fun
tweak: max damage for spear
/:cl:
=> caps the makeshift spear damage

code/modules/overmap/ships/computers/helm.dm
Encodes input on helm computer.  Tested.
Players can do mean things if they have malicious intents, and a stored xss vuln is present.
:cl:
fix: Encodes helm computer.
/:cl:
=> encodes helm computer

code/datums/craft/crafting_items.dm, code/modules/core_implant/cruciform/rituals/priest.dm
when creating a weapon using the gun assembly it returns all guns parts used.
the weapons you can see are no longer organized in function of higher spawn frequency to lower spawn frequency.
:cl:
fix: gun assembly no longer returns to the user the gun parts used to create a gun.
tweak: gun that can be created using a gun assembly are no longer displayed according to their spawn frequency.
/:cl:
=> gun assembly fixes

code/modules/core_implant/cruciform/machinery/obelisk.dm, code/modules/core_implant/cruciform/rituals/priest.dm
Much of the obelisk code does not work and has never worked and this eliminates it.
With the latest changes of the nt update to the energy regeneration of the cruciform, the regeneration provided by the obelisks is excessive, this decreases it.
:cl:
tweak: obelisks provide less energy regeneration to nearby disciples. 
/:cl:
=> cruciform energy tweaks v2 + obelisk shitcode fixes.

code/modules/core_implant/cruciform/rituals/group.dm, code/modules/core_implant/cruciform/rituals/priest.dm
the vigilance ritual had not been added for many years for some strange reason.
nt update
:cl:
add: group ritual: VIG.
/:cl:
=> VIG ritual

code/game/machinery/mindswapper.dm
Most mobs can be mind-swapped. Synthetics are blocked, and there is a blacklist for any mobs that cause issues(It's empty). Since eris code is bad a lot of mobs don't work well when directly controlled, but they do work, the player just might shoot gas at random or walk towards a dead body.
You can be a cow.
:cl:
tweak: Most mobs can be mind-swapped into, with a few exceptions.
/:cl:
=> Most mobs can be mind-swapped

code/modules/clothing/clothing.dm
Lets you store tools on the suit slot.
Being able to store your tools on your suit slot is just a nice feature. If someone wants to store a hammer on their armor slot instead of a gun, more power to them.
:cl:
tweak: Tools can now be stored in the suit slot.
/:cl:
=> Lets you put tools in the suit slot.

code/modules/core_implant/cruciform/cruciform.dm
see changelog.
fixes a bug.
:cl:
fix: the energy regeneration of the cruciform no longer increases excessively due to a high COG value.
/:cl:
=> cruciform energy fixes v3

code/modules/reagents/reagents/medicine.dm
Buffs Ossisine , a chemical hard to make to fix bones. , now it deals 15 agony per affect_blood, not even tramadol can keep someone up.
Preety much all off quality assurance said it was crap and shouldn't be because its a high-tier chem that is actually hard to make (requires plasma and blattedin)
:cl:
balance: Ossisine now deals pain instead of paralyzing and has 100% chance to fix a bone break.
/:cl:
=> Ossisine no longer paralyzes,  ossisine now has a 100% chance to fix bones.

code/__DEFINES/spawner/_spawner.dm, code/game/objects/random/purerandom.dm
this spawner can generate almost any item, usually it should be limited to cheap items but some changes in the repository have made its previous value too high.
:cl:
tweak: Reduces the maximum "lowkeyrandom" spawner  price 
/:cl:
=> Reduces the maximum "lowkeyrandom" spawner price

code/modules/projectiles/guns/projectile/shotgun/bull.dm
Removed wield requirement from pumping the shotgun.
Its really tedious to fully reload these since you need to pump in order to do it, i can't exactly remember why we added this but its contributed nothing but tedium. 
:cl:
del: Removed wield requirement to pump shotgun. 
/:cl:
=> You can now pump a shotgun unwielded

code/modules/projectiles/gun.dm, code/modules/projectiles/guns/projectile/automatic.dm, code/modules/projectiles/guns/projectile/automatic/ak47.dm, code/modules/projectiles/guns/projectile/automatic/dallas.dm, code/modules/projectiles/guns/projectile/automatic/lmg.dm, code/modules/projectiles/guns/projectile/automatic/slaught_o_matic.dm, code/modules/projectiles/guns/projectile/automatic/sol.dm, code/modules/projectiles/guns/projectile/boltgun.dm, code/modules/projectiles/guns/projectile/revolver/sky_driver.dm, code/modules/projectiles/projectile/bullettypes.dm, code/modules/tips_and_tricks/gameplay.dm
Adds the ability to break apart guns for their parts using a wrench
Cause a staff dev asked for it , also adds another way to destroy "oddity" guns like the skydriver and complete the objective
:cl:
add: Added the ability to break apart guns for their parts and salvage.
/:cl:
=> Lets people break apart guns for gun parts

code/modules/projectiles/guns/projectile/automatic/lmg.dm
Title.
Looks cool.
:cl:
fix: fixed takeshi onsuit sprite.
/:cl:
=> fixes takeshi onsuit sprite

code/modules/reagents/reagents/dispenser.dm
Sugar now gives less nutrition and has some side effects, most notable being heart damage.
Apparently people have been injecting raw sugar into their veins so forego food.
:cl:
tweak: Decreased nutrition from sugar and added OD effects, most notably minor heart damage.
/:cl:
=> Injecting sugar in bad.

code/modules/clothing/gloves/miscellaneous.dm, code/modules/clothing/under/jobs/civilian.dm
title
consistency is nice
:cl:
fix: fixed cap gloves and jumpsuit description to match their sprites
/:cl:
=> Fixes cap clothing description

code/modules/projectiles/guns/projectile/sniper.dm
title.
big pp gun.
:cl:
fix: vanishing AMR sprite no longer vanishes.
/:cl:
=> fixes disappearing AMR sprite issue.

code/controllers/subsystems/tickets/tickets.dm
Put back the autoresponse option in the ticket interface.
You can tell people to man up with a few clicks (and other useful answers).
:cl: Hyperio
admin: Re enable autoresponse in ticket system
/:cl:
=> Re-enable autoresponse in ticket system

code/game/objects/items/weapons/tools/hammer.dm
Adds prying quality to IH Breaching Hammer
With prying quality you can:
1. Pry stuff
2. (Also, the main reason) Install toolmods on the hammer (damage of the hammer = damage that the wall would get after a succesfull hit)
:cl: CeUvi
tweak: Adds prying quality to IH Breaching Hammer
/:cl:
=> Prying quality for IH Hammer

code/__DEFINES/components.dm, code/_onclick/hud/screen_objects/base_screen_objects.dm, code/game/atoms_movable.dm, code/game/machinery/telecomms/broadcaster.dm, code/game/objects/items.dm, code/game/objects/items/_inventory.dm, code/game/objects/items/devices/radio/radio.dm, code/game/objects/items/weapons/storage/storage.dm, code/modules/lighting/lighting_atom.dm, code/modules/mob/inventory.dm
Adds signals for Item picking , Dropping , picking items from storage , taking items from storage , checking storage, hearing radio messages or sending radio messages , changing walk intent or action intent and a signal for before a move is executed
Easier for contributors to hook onto various  aspects without having to force a call or employ shitcode
:cl:
code: Signals added for various common actions so that contribution is easier.
/:cl:
=> Adds various signals for common actions

code/game/machinery/vending.dm, maps/CEVEris/_CEV_Eris.dmm
Relocates gun vendor to a more suitable location
before:
after:
:cl:
tweak: Some crafty vagabond stole the Billomat. It's somewhere in second section now.
/:cl:
=> Relocate billomat

code/modules/research/xenoarchaeology/machinery/coolant.dm
Fixes a runtime.
When I tested there wasn't a runtime that currently appears on a coolant tank
Less runtimes less lag
:cl:
fix: Coolant tank runtime
/:cl:
=> Fix coolant tank runtime

code/game/objects/effects/portals.dm
using the JTB should have some cost and in fact this was designed to increase entropy.
:cl:
tweak: Junk Tractor Beam now increases bluespace entropy. 
/:cl:
=> Junk Tractor Beam now increases bluespace entropy. 

code/modules/mob/living/carbon/superior_animal/giant_spider/types/hunter.dm, code/modules/mob/living/carbon/superior_animal/giant_spider/types/nurse.dm
Replaces instances of insect in giant spider description into arachnid
Spiders are arachnids not insects
maybe
i dont know actually
:cl:
fix: Another kneejerk PR, spider's are now arachnids
/:cl:
=> Arachnophobia

code/game/machinery/autolathe/autolathe.dm, code/game/machinery/autolathe/nanoforge.dm
the nanoforge code was causing some unexpected behavior, it was supposed to consume license points from the disks, however it was not working that way.
:cl:
fix: nanoforge now consumes disk license points.
/:cl:
=> Nanoforge Refactor

code/modules/core_implant/cruciform/rituals/base.dm
:cl:
tweak: the Cruciform sense no longer includes the ritual performer.
/:cl:
=> the Cruciform sense no longer includes the ritual performer.

code/modules/projectiles/guns/projectile/battle_rifle/kovacs.dm
Some slight tweaks to damage, penetration, fire delay and recoil
Gun is a tad too strong, its still pretty strong after this but respectable.
:cl:
tweak: longer fire delay, more recoil, less damage and penetration. 
/:cl:
=> Kovacs tweaks 2.0

code/modules/mob/living/carbon/human/human_damage.dm
Fixes limb HP PR
I broke shit, this fixes it.
:cl:
balance: Makes it so limbs and groin don't count towards death. They still inflict pain though.
/:cl:
=> Limb PR fix

code/datums/craft/crafting_items.dm, code/game/machinery/autolathe/artist_bench.dm, code/game/objects/items/oddities.dm
See title, this is according to the documentation but it was not implemented due to lack of sprites.
There are still no sprites for this but I would like to finish my part of the work.
Makes the artist bench more in line with the documentation.
:cl:
add: the artist bench can now produce parts of guns and armor.
/:cl:
=> the artist bench can now produce parts of guns and armor.

code/game/turfs/simulated/floor_icon.dm
Fixes floors runtiming when placed
Because its a fix and stops filling up code-shaming
:cl:
fix: Floors runtiming
/:cl:
=> Flooring runtime fix

maps/CEVEris/_CEV_Eris.dmm
fixes pods not launching.
less bugs, people can do evac properly and escape from the 17 hiveminds that Rosa-storyteller spawned.
:cl: Herbaon
fixes: pods can launch again.
/:cl:
=> making evac pods great again

code/datums/uplink/ammunition.dm, code/datums/uplink/announcements.dm, code/datums/uplink/badassery.dm, code/datums/uplink/devices and tools.dm, code/datums/uplink/grenades.dm, code/datums/uplink/hardsuit_modules.dm, code/datums/uplink/highly visible and dangerous weapons.dm, code/datums/uplink/implants.dm, code/datums/uplink/medical.dm, code/datums/uplink/stealth and camouflage items.dm, code/datums/uplink/stealthy and inconspicuous weapons.dm, code/game/antagonist/outer/blitzshell/blitzshell.dm, code/game/objects/items/devices/uplink_random_lists.dm, code/game/objects/items/gene_vial.dm, code/game/objects/items/weapons/storage/boxes.dm, code/game/objects/items/weapons/storage/firstaid.dm, code/game/objects/items/weapons/storage/uplink_kits.dm, code/modules/clothing/spacesuits/rig/modules/combat.dm, code/modules/clothing/suits/armor.dm, code/modules/mob/living/simple_animal/hostile/syndicate.dm, code/modules/projectiles/ammunition/magazines.dm, code/modules/projectiles/guns/energy/laser.dm, code/modules/reagents/reagent_containers/food/snacks.dm, code/modules/reagents/reagent_containers/pill.dm
I followed the orders of the holy google doc in some stuff, others when im not lazy as fuck
Google doc
:cl:
add: PK and dallas ammo to uplink, nanopaste, ammo strips for mosin/novak, HV and normal, at the prize of 2 and 1 Tcs respectively
del: deleted clerical kit,
tweak: HV SMG prize changed to 4, .35 Pistol ammo prize changed to 1, HV 35 pistol ammo changed to 2, magnum SL changed to 3, HV magnum SL changed to 4,reduced in 1 the prize in both .25 ammo mags, HV and normal. .25 mandella ammo changed prize to 2. .35 ammo packet prize goes to 4. Shipside announcement prize changed to 1, fake crew announcement changed to 6, fake rad storm announcement changed to 4,fake serb announcement changed to 3.Hacked AI module prize reduced to 7,mind fryer to 2.Combat medkit changes to 6 Tcs, but the …
=> Rebalance Part 1, the doc

code/modules/projectiles/guns/projectile/pistol/lamia.dm
Pistol shoot
My hand doesn't breaks anymore when I try to fire it 
:cl:
balance: Lamia recoil have been lowered from 5 to 2.
/:cl:
=> Lower Lamia recoil

code/game/objects/items/weapons/design_disks/autolathe_disks.dm
Kovacs lathe disk no longer DDOS the lathe. Also upped rarity
I accidentally made a virus. Also too common
:cl:
tweak: Also upped rarity
/:cl:
=> Kovacs virus

code/modules/mob/living/silicon/robot/robot.dm
Prevents special characters in robot names.
Russians made chinese robots.
:cl:
fix: lack of sanitation in robo names 
/:cl:
=> No more chinese robots.

code/datums/outfits/jobs/command.dm, code/modules/clothing/head/jobs.dm
Adds Sunglasses with SecHUD to Captain & FO at Roundstart/latejoin spawns. Also makes captain spawn with....captain gloves, while FO spawns now with their respective caphat and changes the name to properly fit him.
I believe these are good QoL changes.
:cl: HerBaon
add: FO & Captain spawn with Sunglasses that have a integrated SecHUD.
add: FO spawn with their respective hat and the name now references him.
add: Captain spawn with their respective gloves.
/:cl:
=> adds things to FO/Cap roundstart.

code/modules/mob/living/carbon/superior_animal/roach/blattedin.dm
did you know there was code that gave roaches a 70% chance to revive with blattedin...
but it didn't work because the code to run it would only run when the bug was alive, meaning that there was no way to revive with it
this fixes that.
idea: giving roaches a way to revive a few seconds after getting beat to shit if they have blattedin in their corpse (callback?)
bugs about bugs should be fixed
:cl:
fix: Roaches now actually have their 70% chance to revive if they have blattedin injected into their corpses.
/:cl:
=> blattedin reviving roaches now actually works

code/game/objects/items/weapons/storage/backpack.dm, code/modules/clothing/masks/miscellaneous.dm, code/modules/clothing/under/miscellaneous.dm
Adds adminbus payday items with SCAF stats and cleans up the lootbag code a bit. Made at the request of the best storyteller.
It's not.
:cl:
add: Added adminbus payday items with SCAF stats.
/:cl:
=> Adminspawn payday items and lootbag code cleanup

code/modules/projectiles/guns/mods/research_mods.dm
reduces extra damage from the gauss barrel, increases it's speed boost, slightly buffs AP mod.
A modification with a primary focus on being a guaranteed wall penetration is already quite powerful on its own, I don't see why it also adds a ton of brute damage. I'm open to changing or being less heavy handed with this PR but I think this is probably for the best.
:cl
balance: lowers damage boost on gauss barrel to 5, makes the bullets fly slightly faster, slightly buffs its AP to multiplier 1.3.
/:cl:
=> Gauss nerf

code/modules/core_implant/cruciform/rituals/construction.dm, code/modules/core_implant/cruciform/rituals/priest.dm
:cl:
fix: acolytes can build through rituals.
fix: acolytes may perform the epiphany ritual.
/:cl:
=> acolytes can build through rituals.

code/game/machinery/newscaster.dm
=> nanotransen => nanotrasen

code/controllers/evacuation/evacuation_pods.dm
Blocks maint drones from calling evac
Ghosts need to cope.
:cl:
fix: drones being able to call evac.
/:cl:
=> Blocks maintenance drones from calling evac

code/modules/core_implant/cruciform/rituals/agrolyte.dm, code/modules/core_implant/cruciform/rituals/base.dm, code/modules/core_implant/cruciform/rituals/custodian.dm
just like changelog says
balacing out NT
:cl:
balance: accelerated growth power 50 > 10
balance: mercy power 50 > 5
balance: Absolution of wounds power 50 > 10
balance: Relief  power 50 > 20
balance: Entreaty power 50 > 0 AND added cooldown of 1min
balance: Cruciform sense added cooldown of 1 minute
balance: Revelation power 50 > 10
balance: Words of purging power 50 > 5
/:cl:
=> litany balance 

maps/submaps/deepmaint_rooms/normal/hive_nest.dmm
Replaces creature with stinger inside the hivemind nest
"creature" hivemind mob is basically not an actual mob that's meant to spawn
:cl:
fix: Shadow Banishes a creature in the hivemind nest into eternal pit of torment known as discord admin channel. (fixes a hive mob not spawning properly in the hivemind deepmaint room)
/:cl:
=> El Creatura

code/modules/projectiles/gun.dm
you used to be unable to attach bayonets to guns due to a bug
who am I even kidding
:cl:
fix: you can now attach bayonets to guns again
/:cl:
=> Fixes no guns having a bayonet slot

code/datums/craft/recipes/weapon.dm, code/modules/projectiles/guns/launcher/crossbow.dm
remove old left overs
:cl:
refactor: Crossbow and RXD are fully done by eris crafting system "no bay leftover"
/:cl:
=> Crossbow and RXD now are integrated in the crafting system completly

code/modules/mob/living/carbon/superior_animal/attack.dm, code/modules/mob/living/carbon/superior_animal/superior_animal.dm
title
superior animals will allow you to get shot in maint
:cl:
code: steals ranged attacks from simple_mob
/:cl:
=> Gives ranged attack procs for superior_animal

code/modules/projectiles/guns/projectile/revolver/revolver.dm
Fixes an incorrectly named variable.
Fixes are always good.
:cl:
fix: The Miller's AP now correctly reflects its role as the gun for killing poor people.
/:cl:
=> Corrects the Miller's AP multiplier

code/modules/mob/living/carbon/human/life.dm, code/modules/organs/internal/carrion.dm
30. Fixes carrion paralysis bug that triggered 10 minutes after the reg.stasis.
Solves/fixes #6301 
_thanks to NicoDB for the image._
:cl: Herbaon
fix: fixed carrion being permanently paralyzed 10 minutes after using reg.stasis
/:cl:
=> Fixes Carrion Stasis Paralysis

code/modules/core_implant/cruciform/rituals/priest.dm
Fixes my retard moment. I should have pushed this one not the other. This has been fixed already on the branch that is being tested on the server but the master still has this problem and people that updates their master are going to have a error for my mistake. 
-10 points for me 
I'm retard and this fixes my error. 
:cl: Herbaon
fix: fixed Preacher making all stats oddities with cube and artist oddities 
/:cl:
=> Fixes my retard moment on priest.dm

code/modules/client/preference_setup/global/06_media.dm
Basic typo fix within the global settings menu.
Typo fix
:cl: Xoxeyos
spellcheck: Typo fix, 'comptuer' to 'computer'.
/:cl:
=> Typo fix, 'comptuer' to 'computer'.

maps/CEVEris/_CEV_Eris.dmm
Rework of the Guild Lobby following the Section III community event.
Rework of Section III based on players feedback. Church and bar will follow.
Floor decals in the waiting queue do not appear for now due to an issue that affect all floor decals at round start. It looks like that but with some shelves and tables instead of being full racks in order to add some diversity.
:cl: Hyperio
add: Rework Guild Lobby in Section III
/:cl:
=> Guild Lobby Map Rework

code/modules/mob/living/carbon/human/human_movement.dm
Fixes the movement runtimes using this`?` one`?` simple`?` trick`?`
:cl:
fix: fixed movement runtimes.
/:cl:
=> Movement fix

code/controllers/subsystems/machines.dm
Exactly what the title says.
It should lag even less and prevent a lot of chugging in general. Plus gets rid of processing runtime.
:cl:
fix: Fixes a runtime in processing
/:cl:
=> Fixes processing runtime

code/modules/reagents/reagents/toxins.dm
fixes zombie powder paralysis
one less bug
:cl: Herbaon
fix: fixed zombiepowder permanent paralysis
/:cl:
=> zombie powder paralysis fix

maps/CEVEris/_CEV_Eris.dmm
Add the new style vendor to the map in the area in front of the FO office.
Doing it because the author has some map merging issues :D
New vendor.
:cl: Hyperio
add: Add style vendor to Eris map
/:cl:
=> Add style vendor to Eris map

code/datums/setup_option/backgrounds/origin.dm
Adds a new IH only background that focuses on non-combat stats. Everything done and credited to @Benblu.
Spent 5 minutes on this section and couldn't come up with anything.
:cl:
add: added new IH background
/:cl:
=> Ironhammer (M.)A.I.D.S background

code/controllers/subsystems/trade.dm
:cl:
fix: Now markup of prices in trade stations is real.
/:cl:
=> Fix of markups

code/modules/trade/datums/trade_stations_presets/asterstradecapital.dm, code/modules/trade/datums/trade_stations_presets/nt_cruisers.dm, code/modules/trade/datums/trade_stations_presets/serbianship.dm, code/modules/trade/datums/trade_stations_presets/tb_cheapammofactorys.dm
YOOOOO NO PLACEHOLDER DESCRIPTIONS POG.
also changed code-wise the order of some items because it wasn't the only one following the original order. 
this counts as a bugfix, right? right¿
:cl: Herbaon
fix: fixes placeholder text in stations.
/:cl:
=> descriptions

cev_eris.dme, code/game/area/asteroid_areas.dm, code/game/objects/effects/spawners/ghostroles.dm, code/game/objects/effects/spawners/ghostspawner.dm, maps/encounters/prisonhulk/prisonhulk.dm, maps/encounters/prisonhulk/prisonhulk.dmm
Adds in ghost roles, stolen from TG. these are intended to be stories that run roughly parallel to the main Eris crew, with groups like scavengers, prisoners, and other people working to explore parts of the universe beyond the main ship. Currently adds in the prison hulk
TODO: add in ghost role menu
:cl:
add: Added ghost roles
add: Added prison hulk, in which prisoners must escape their prison ship's wreck
/:cl:
=> Adding in Ghost roles

code/game/machinery/vending.dm, code/game/objects/items/weapons/cigs_lighters.dm
title
more literal chainsmoking, more variety in smokes
:cl:
add: Added more cigarettes to cigarette vendor
add: gave lit cigarettes/cigars cauterizing quality
/:cl:
=> Adds other smokes to cig vendor, adds cauterization to lit smoke

code/game/objects/items/weapons/shields.dm
closes #6389
:cl:
fix: Fix for handheld shields
/:cl:
=> shields fix

code/game/gamemodes/endgame/supermatter_cascade/universe.dm
This PR makes the announcement for the SM cascade much more curt, and makes it more lore friendly.
We aren't a station, there is no escape shuttle, and everyone in the galaxy will know who to be pissed at, for their lost benefits.
:cl: Xoxeyos
tweak: SM Cascade event is now more lore friendly.
/:cl:
=> Updated SM Cascade event to be more lore friendly.

code/datums/perks/job.dm, code/modules/reagents/metabolism.dm, code/modules/reagents/reagents/medicine.dm
Neural system accumulation threshold would scale with COG stat, adding 1 point to NSA limit for each 3 points of COG.
Most useless stat finally good for something.
:cl:
add: COG affecting nsa_threshold
/:cl:
=> Stats affecting NSA

code/game/objects/items/weapons/grenades/flashbang.dm
Remember when flashbangs did not disappear after the bang? No longer.
Fixes cool.
:cl:
fix: fixed flashbang not being deleted after detonation
/:cl:
=> Flashbang fix

code/datums/ai_law_sets.dm, code/modules/mob/hear_say.dm, code/modules/mob/living/say.dm
It seems to work properly now. Tried as sorts of stuff and it's all ok.
Changed drone laws too, it's "You may not interact with a human being or, through your action, allow a human being to come to harm." now.
Fixes cool.
:cl:
fix: codespeak fixes
tweak: drone interacting laws
/:cl:
=> Codespeak hotfix

code/datums/ai_law_sets.dm, code/modules/mob/hear_say.dm, code/modules/mob/living/say.dm
Yet another one, hopefully the last one.
Fixes cool. 
:cl:
fix: fixed radio working as an universal translator
/:cl:
=> Fix of a fix

code/game/gamemodes/events/blob.dm
Deleted that verb. It has no reason to exist at all. Nanako, why?
Fixes cool.
:cl:
fix: annoying blob "expand" verb
/:cl:
=> Blob verb fix

code/modules/projectiles/guns/energy.dm
You have to remove power cell before dismantling though.
Fixes cool.
:cl:
fix: egun dismantling
/:cl:
=> Unbreakable eguns fix

code/game/gamemodes/events/rogue_drones.dm, code/game/objects/items/toys.dm, code/modules/economy/TradeDestinations.dm
Replaced NDV Icarus with IHS Atomos.
Bay lore should go.
:cl:
fix: mentions of NDV Icarus
/:cl:
=> NDV Icarus fix

code/game/objects/structures/kitchen_spike.dm
Fixes cool.
:cl:
fix: items from butchered mobs no longer getting lost in bluespace
/:cl:
=> Spikes deleting mob's content fix

code/game/objects/items/weapons/melee/energy.dm
Fixes cool.
:cl:
fix: invisible energy swords
/:cl:
=> Invisible energy swords fix

code/modules/mob/living/simple_animal/hostile/bear.dm
Fixes cool.
:cl:
fix: now bears rest in peace after death
/:cl:
=> Undead space bears fix

maps/CEVEris/_CEV_Eris.dmm
* Fix missing APC in deck 3 maintenance
* Fix missing hull in church maintenance
* Fix missing power cable in club worker barracks
* Add toilets at lower club level
* Move 1 hull tile at zlevel 1 so that people can move around in space
F.I.X
:cl: Hyperio
add: Add toilets at lower club level
fix: Fix a few issues of church map rework
/:cl:
=> [MAP] Church rework hotfix

code/_onclick/hud/radial.dm, code/modules/integrated_electronics/subtypes/input.dm, code/modules/integrated_electronics/subtypes/manipulation.dm, code/modules/integrated_electronics/subtypes/output.dm
Added supprot for my hacks in radial menu.
Bluspace rift circuit is now working.
Good is good, that's rule.
:cl:
fix: possible radial error fixed.
fix: bluespace rift circuit is now works.
/:cl:
=> HICU: bluespace fix and radial fix

maps/CEVEris/_CEV_Eris.dmm
Add missing plating in lower bar.
Space is harmful.
:cl: Hyperio
fix: Fix missing plating in lower bar
/:cl:
=> [MAP] Add missing plating in lower bar

code/game/objects/items.dm
Provides a default hitsound for items, fixing the issue of some items not having a sound on hit.
Items having no sound on hit is bad.
:cl:
fix: fixed object items having no sound on hit
/:cl:
=> Fixes object items having no sound on hit

code/datums/datum_click_handlers.dm, code/modules/projectiles/guns/energy/temperature.dm
Fixes temp gun not working , makes automatic guns not sleep, makes temperature gun not give gun parts
changed from timers to spawn in the loop because timers are not necesarry and it might actually kill the timer subsystem
Almost exactly the same as https://github.com/discordia-space/CEV-Eris/pull/6485 , only difference being using spawn() instead of addtimer.
Less lag , more fun.
:cl:
fix: Temp gun not applying temperature onto its projectiles
fix: Temp gun giving gun parts
code: Gun handlers using sleep
/:cl:
=> (Possible) Fix to gun lag , fixes temperature gun , now without skin.dmf

maps/CEVEris/_CEV_Eris.dmm
Fix a small issue with the shield.
:cl: Hyperio
fix: Fixed issue with shield in research area
/:cl:
=> [MAP] Fix shield bug in research area

maps/CEVEris/_CEV_Eris.dmm
Add a sink in the hydroponics room and IH barracks.
Apparently it's useful and IH like washing their bloody boots.
:cl: Hyperio
add: Added a sink in hydroponics and IH barrack
/:cl:
=> Add sink in hydroponics and IH

code/datums/loot_spawner.dm
fix runtime error with loot spawn
https://en.wikipedia.org/wiki/Logarithm
Spawn more items
:cl:
fix: loot spawn error
/:cl:
=> fix loot spawner

maps/CEVEris/_CEV_Eris.dmm
Replace civilian console in cargo to trade console
:cl:
fix: fix unavailable trade program in cargo
/:cl:
=> fix trade console

code/modules/organs/internal/carrion.dm
Prevents a carrion runtime.
Runtimes bad.
:cl:
fix: prevents a carrion runtime
:cl:
=> Prevents a carrion runtime

code/game/objects/items/weapons/storage/firstaid.dm, code/modules/reagents/reagent_containers/pill.dm, code/modules/reagents/reagents/medicine.dm
Replaces tramadol in traitor's surgery kit with oxycodone cuz tramadol gives up very fast and pain starts distracting the human from cutting himself to pieces, passing out and etc.
adds oxycodone pill bottle and a pill itself
Since pain rework or tweaks tramadol is no longer very good for self surgery
:cl:
tweak: tramadol from traitor's surgery kit got replaced with oxycodone
/:cl:
=> Traitor first aid (Tramadol to Oxycodone)

code/modules/projectiles/projectile/special.dm
Makes it so rockets cant penetrate walls.
No more wallpen RPG memes.
:cl:
tweak: tweaked rockets so they cant penetrate walls anymore
/:cl:
=> Rockets cannot penetrate walls

code/modules/mob/observer/freelook/ai/eye.dm, code/modules/mob/observer/freelook/eye.dm
Fixes the bug about AI visibility not properly updating when moving up or down a z-level
Less gamin
:cl:
fix: Fixed AI Eye not properly updating when moving up or down a z-level
/:cl:
=> Fixes AI being able to see unintended places by moving up or down a z-level

code/game/machinery/doors/airlock_control.dm, code/game/machinery/doors/door.dm
I fucked up
People want to eva
:cl:
fix: Fixed door cycling not working properly
/:cl:
=> Fixes door commands and airlock cyclers

code/modules/surgery/surgery.dm, code/modules/surgery/surgery_ui.dm, nano/templates/surgery_organ.tmpl
Added "remove shrapnel" button to surgery UI, it's not visible when there is no shrapnel to remove.
Requires hemostat / wirecutters and skill check that is somewhat harder than diagnostic check.
Healing people packed with shrapnel is too much pain.
:cl:
add: shrapnel removal button in surgery UI
/:cl:
=> Remove shrapnel button

code/__DEFINES/items.dm, code/game/objects/items/weapons/tools/mods/_upgrades.dm, code/game/objects/objs.dm, code/game/turfs/simulated/walls.dm, code/modules/projectiles/gun.dm, code/modules/projectiles/guns/mods/mods.dm, code/modules/projectiles/projectile.dm
Adds a new Oberth brand gunmod
God forgive me for what I've done... I was merely following orders...
:cl:
add: Added a new Oberth brand gunmod. Accessible through RNG and adminbus
code: Added some bullet/gun variables
/:cl:
=> Oberth™ brand weapon mod

code/modules/mob/living/carbon/human/human_movement.dm
they speed you up nooo
fck
:cl:
fix : fixed painkillers grantiing you speed
/:cl:
=> Hotfix for painkillers

code/game/objects/items/weapons/material/kitchen.dm
You can spoon someone to instantly force feed them without any actual checks , this changes that
I was walking in a hallway , and then a chemist passes by me , turns around  then goes away , suddenly i fall asleep and im being organ harvested. I was wearing heavy armor so i  was wondering how such thing is possible . I have found that spoons are simply overpowered.
:cl:
fix: Spoons not checking wheter a person can be fed and wheter the timer to do so has been run
/:cl:
=> Nerfs spoons

code/modules/mob/living/simple_animal/friendly/cat.dm
Bones is now the MBO's friend
Its not
:cl:
fix: Bones can now befriend the MBO
/:cl:
=> Bones can now befriend the MBO

code/modules/mob/living/silicon/robot/robot.dm
Before this pr, you couldn't damage a borg with tools/items with certain qualities when on harm intent, Now it's fixed
NO MORE OPENING THE BORG COVER WITH A FIREAXE ON HARM MODE
:cl:
fix: fixed not being able to attack borgs with certain tools on harm intent
/:cl:
=> Fixes not being able to harm borgs with certain tools

code/modules/mob/living/silicon/robot/robot.dm
This change is good and all but it somehow screwed up the linters.
=> Revert "Fixes not being able to harm borgs with certain tools"

code/game/objects/effects/portals.dm, code/modules/admin/admin_verbs.dm
Asked by Gray, allow the creation of portals between two locations knowning their (x, y, z) coordinates.
New admeme tool.
:cl: Hyperio
add: Added Create Portals verb in Fun tab
/:cl:
=> Add Create Portals verb in Fun tab

code/modules/projectiles/gun.dm
Wield factor 0 moment ? 
Its not , people are already trying to remove it and make vigilance useless all around , but i might as well future proof my code for the mistake of the short-minded
:cl:
fix: Wield factor runtiming when set at 0.
/:cl:
=> Fixes a future wield timer runtime

code/game/machinery/surveillance_pod.dm
Fixes cool.
:cl:
fix: surveillance pods seeing too much
/:cl:
=> Hotfix surveillance pods being able to see too much

code/modules/mob/living/silicon/robot/robot.dm
I hate robot.dm I HATE robot.dm
Fixes not being able to harm borgs with certain tools
:cl:
fix: Fixed not being able to harm borgs with certain tools
/:cl:
=> Beat borgs with tools, #6727 done properly

code/game/objects/items/weapons/mine.dm, code/game/objects/items/weapons/traps.dm
What it says on the tin. When someone placing a mine or a trap - info about user, location and type of trap is recorded.
Literally 1984.
Admeme asked for this.
:cl:
admin: record trap and mine placement
/:cl:
=> Log mine and trap placement

code/modules/projectiles/guns/energy/plasma.dm
redoes #6702 without the merge conflict, with NT dominion
gives a reason to use plasma
:cl:
add: Added burst fire mode to Dominion and Cassad plasma rifles
/:cl:
=> Makes Plasma rifles fire in bursts

code/modules/mob/living/carbon/superior_animal/defense.dm
upgrade superior animal AI
Mobs will look for new nearby targets when receiving damage
:cl:
tweak: superior animal ai
/:cl:
=> update animal ai

code/_onclick/hud/hud.dm, code/controllers/subsystems/ticker.dm
Fixes the dither not being click-through
Makes the helmet not pain
:cl:
fix: fixes heavy operator helmet
/:cl:
=> Heavy op helmet hotfix

code/datums/mind.dm
Stops runtime spam caused by #6744. Also fixes a typo introduced by the same PR.
=> Fixes roundstart runtime spam

code/modules/surgery/organic.dm
I must atone for my sins by fixing my own bugs
Fixes a number fuckup, making shrapnel removal no longer gib you
:cl
fix: fixes shrapnel removal values
/:cl:
=> Shrapnel Removal Hotfix

code/modules/projectiles/guns/energy/stun.dm
Changes the Moebius' knock-off of the stunrevolver
It's just interesting flavour
:cl:
tweak: Moebius Laboratories have come up with a totally original name for their stunrevolver design
/:cl:
=> Gives the Moebius stunrevolver a unique name

code/datums/uplink/highly visible and dangerous weapons.dm
Adds bullet blender to uplink
If have any questions read uplink update document in mines. If there are still questions left - go to fortune master, aka rope bunny.
:cl:
tweak: Bullet blender is added to uplink for 5 tc
/:cl:
=> Bullet blender to uplink

code/modules/reagents/reagent_containers/food/drinks/drinkingglass.dm
Fixes cool.
:cl:
fix: runtime related to drinking glasses
/:cl:
=> Fix runtime in drinkingglass.dm

code/modules/sanity/sanity_mob.dm
no idea what is in the uhhh what is in the title, I may be sleep depriveed
club buff*
* - actually easier insight stacking
:cl:
balance: you don't get desires to smoke/use drugs if you are addicted to them
/:cl:
=> Don't get desires to smoke/use drugs if you are addicted to them

code/modules/projectiles/projectile.dm
Temporary solution, prevents shields on the back from proccing to bonk SPCR.
Stops SPCR from abusing a very niché exploit.
:cl:
fix: temporarily removed shields on the back from proccing
/:cl:
=> Removes shield on the back from being procced

code/modules/reagents/reagents.dm
Allows Chems to once again work as intended.
:cl:
fix: Chems with a constant metabolism, like stims, now drain from the blood of humans.
/:cl:
=> Fixing chems your welcome

code/modules/projectiles/guns/energy/plasma.dm
Fixes cassad burst
fixes good
:cl:
fix: fixed cassad doing armor-piercing bursts
/:cl:
=> makes cassad not burst on every shot after switching

code/datums/ai_law_sets.dm
badmin happy
:cl:
tweak: AI law 4 expanded to include personnel authorized to tamper with its equipment(FO. TE. MEO. Cap)
/:cl:
=> AI Law 4 expansion

code/modules/reagents/recipes.dm, tools/hooks/install.bat
We have solidification for one thing that is commonly a liquid. Just made ones for the other common ones.
Botany is now useful an make decent money. The uranium is not overpowered because at almost maxed out potency 4 plants will make 1 sheet worth every couple of minutes.
:cl:
add: gold and uranium can now be solidified
/:cl:
=> solidification

code/modules/mob/mob.dm, code/modules/projectiles/gun.dm, interface/skin.dmf
yea
now it's foolproof
:cl:
tweak: Tell player if they face dir, change face dir hotkey from ALT+DIR to ALT+CTRL+DIR
/:cl:
=> Tell player if they face dir, change face dir hotkey from ALT+DIR to ALT+CTRL+DIR

code/modules/reagents/recipes.dm, tools/hooks/install.bat
Reverts discordia-space/CEV-Eris#6812
I did not see it also deleted install.bat, my bad. Apparently this file is a duplicate and has no purpose.
Let's have this PR just change the solification to avoid mixing things and maybe we'll have another PR that remove the file.
=> Revert "solidification"

code/game/machinery/vending.dm, maps/CEVEris/_CEV_Eris.dmm
Expanded forensic lab and hospital a little, ~gave it a medicine vendor.~
Lethal injection closet moved to execution room. See screenshots for more details.
<details>
<summary>
Before
</summary>
</details>
<details>
<summary>
After
</summary>
</details>
<details>
<summary>
Vendor
</summary>
Regular:
Hacked:
</details>
UPD: Vendor have been removed.
More use for money for IH and actual source of chems when Moebius Medical not running chemistry (90% of the time), even if at robbing price.
:cl:
add: expanded hospital a little
/:cl:
=> Brig map changes

code/modules/mob/living/carbon/human/species/species_attack.dm, code/modules/mob/living/carbon/human/unarmed_attack.dm, code/modules/mob/mob_grab.dm, code/modules/mob/mob_grab_specials.dm
THESE WILL GIVE STYLE AFTER STYLE DODGE REWORK
suplex: neck grab, harm intent, aim chest. After 2 seconds, slam the opponent and yourself on the floor(duration for yourself - 1 second softstun, enemy - 3 second hardstun), dealing (ROB/2)+15 dmg to opponent. If you think this is OP, remember that you can stunlock the opponent and cut their throat on the same grab level.
dropkick: aggro grab, harm intent, aim groin. Dropkick the opponent, sending them flying away(3 tiles), while also softstunning them for 3 seconds and yourself for 1 second. Damage - (ROB/3), which is puny, which is intended.
grammar: check files. In short, the eye attacking and neck grabbing texts are better now.
THESE WILL GIVE STYLE AFTER STYLE DODGE REWORK
Dropkick that baby in self-defence!
Even more unarmed combat and …
=> Suplex, dropkick, some grammar stuff with grabs

code/modules/reagents/recipes.dm
Fixes a typo in the recipe for mold-based spaceacillin
Allows the recipe to work as intended
:cl:
fix: changed "spaceacilin" to "spaceacillin"
/:cl:
=> Typo fix for ghetto spaceacillin

code/ATMOSPHERICS/components/unary/vent_scrubber.dm, code/ZAS/Atom.dm, code/ZAS/Zone.dm, code/__DEFINES/components.dm, code/controllers/subsystems/machines.dm, code/game/machinery/doors/firedoor.dm
Attempt 2 at cutting 1200~ ish machinery from processing
I tried to brick it locally and it did not work. Should be test merged just to make sure.
Less lag
:cl:
code: Optimized firedoors to no longer process
balance: Firedoors no longer give as much data about the other sides
code : Optimized scrubbers to not process
/:cl:
=> Firedoors and Scrubbers no longer process, attempt 2

code/game/machinery/doors/airlock.dm, code/game/objects/structures/crates_lockers/closets.dm, code/modules/mob/living/silicon/ai/ai.dm, code/modules/reagents/reagent_dispenser.dm
Fixes Engi Multitool interactions with
AI
Unscrewed Doors
Closets
Welding fuel tanks (intent based now)
Finnaly..i  can unbolt my beloved AI.
:cl:
fix: Broken engineering multitool interactions.
/:cl:
=> Fixes 4 Engineering Multitool interactions

code/modules/mob/living/silicon/ai/ai.dm
~Fixes it so that any tool with the wrench quality may be used instead of *specifically* a wrench.~
SPCR's fix is better than mine, he can have the glory of that.
Grants the AI the ability to speak the common languages of the crew, so that it may respond in the appropiate languages. Little mechanical change, besides the potential for secrecy, as the AI already understands all languages inherently. It also can't speak anything it logically is incapable of (Jive, borer, etc.).
Language thing is just because I want to.
:cl:
add: The AI can now speak the languages of the crew (except the ones that it would not logically be able to).
/:cl:
=> AI Language speaking

code/datums/setup_option/backgrounds/origin.dm
Makes origin descriptions that gave you languages say so on the tin.
More clarity to the player, also fixes #6864 
:cl:
spellcheck: origin descriptions that give you a language say so now so you don't need to guess
/:cl:
=> Clearer origin descriptions

code/game/objects/items/weapons/shields.dm
Fixes on-mob sprite of energy shield
:cl:
fix: energy shield's icon
/:cl:
=> Eshield icon fix

code/modules/reagents/reagent_containers/food/drinks.dm
The container needs to not be empty
Closes #5679
:cl:
fix: Fixed infinite gulp down
/:cl:
=> Add empty check for gulp down

code/datums/perks/fate.dm, code/modules/core_implant/cruciform/cruciform.dm, code/modules/economy/price_list.dm, code/modules/modular_computers/file_system/catalog.dm, code/modules/reagents/bonsai.dm, code/modules/reagents/reagent_containers/food/drinks/bottle.dm, code/modules/reagents/reagents/dispenser.dm, code/modules/reagents/reagents/drugs.dm, code/modules/reagents/reagents/food-Drinks.dm, code/modules/reagents/reagents/medicine.dm, code/modules/reagents/reagents/other.dm, code/modules/reagents/reagents/stims.dm, code/modules/reagents/reagents/toxins.dm, code/modules/sanity/sanity_mob.dm, nano/templates/catalog_entry_drink.tmpl
Fixes withdrawals, all alcohols were refactored under the "alcohol" name, which are metabolized into Ethanol in the stomach.
Lots of various fixes and tweaks.
10/10 realistic drunkness, alcohols finally stack (they didn't), you can get drunk more effectively.
Withdrawals are fixed, which was a bug up until now.
:cl:
refactor: alcohol was refactored, now involves putting ethanol in the bloodstream
tweak: cahors is halal
fix: a large number of typos were fixed
fix: lots of withdrawals fixed, including nicotine
tweak: various withdrawal and Toxin tweaks
/:cl:
=> Ethanol refactor, withdrawal fix

code/game/objects/structures/catwalk.dm
Fixes runtimes which keeps failing CI compiling.
CI stops throwing unrelated errors.
Sidenote: Generally it's best to not merge something if a CI check is failing, unless the PR being merged is to fix CI or Very Urgently Needed.
=> Fixes constant source of runtimes

code/datums/objective/individual_objective/common.dm
Back transfer to bank trasfer.
Grammer good
:cl:
spellcheck: back transfer is now bank transfer as it should have been
/:cl:
=> Fixes spelling mistake

code/modules/maps/tg/reader.dm
Adds extra debugging info for the reader.dm runtimes.
=> Gets extra info on the reader runtimes

code/modules/reagents/reagents/food-Drinks.dm
Makes Milkshakes a subtype of Milk
Something that is literally cold milk inexplicably no longer behaving like milk irks me
:cl:
tweak: Milkshakes are now a subype of milk
/:cl:
=> Makes milkshakes a subtype of milk

maps/CEVEris/_CEV_Eris.dmm
- Adds cargo tiles under doors in church, science
- Placed a hull instead a space turf above a ladder in medbay's maintenance. Yes, it used to be exposed
- Made the bridge above RND have white tiles
:cl:
fix: Fixed a few mapping errors
/:cl:
=> Mapping fixes

code/__DEFINES/economy.dm, code/controllers/subsystems/economy.dm, code/game/jobs/department.dm, code/game/machinery/cryopod.dm, code/modules/economy/Accounts.dm, code/modules/economy/economy_misc.dm, code/modules/modular_computers/file_system/programs/generic/taxes.dm
Moebius gonna be paid again.
Fixes cool.
:cl:
fix: moebius not getting free money out of nowhere
/:cl:
=> Fix external department funding

tools/hooks/install.bat
It's an exact duplicate, but windows/git Does Not Like It, as windows is insensitive to file name capitalization.
=> Removes file that causes Weird Things to happen with Git

code/modules/projectiles/projectile.dm
What it says on the tin. Works with lasers too.
https://user-images.githubusercontent.com/65828539/147842012-269641b4-8361-4295-bba9-628015b5d9fd.mp4
Dancing on stairs is effective but borderline exploit strategy, that adds nothing but annoyance to the game.
:cl:
balance: projectiles pass trough stairs
/:cl:
=> Projectiles passing trough stairs

code/modules/mining/machine_stacking.dm
Fixes this:
Caused by simultaneous merge of #6911 and #6932. I wonder how that even compiled on server side.
Fixes cool.
:cl:
fix: compiling error
/:cl:
=> FLICK to flick

code/_onclick/drag_drop.dm, code/game/objects/structures/low_wall.dm, code/modules/tables/interactions.dm
Prevents ghosts from moving items on tables, racks and low walls.
Fixes cool.
:cl:
fix: ghosts moving items on tables, racks and low walls
/:cl:
=> Fix poltergeists

code/modules/clothing/suits/bio.dm
Fixes cool.
:cl:
fix: biosuit hiding shoes
/:cl:
=> Fix biosuit hiding shoes

SpacemanDMM.toml, cev_eris.dme, code/__HELPERS/debugger.dm, code/game/world.dm, tools/hooks/install.bat
Adds the functionality to [debug code with Visual Studio Code](https://code.visualstudio.com/docs/editor/debugging).
Can help track down issues.
:cl:
code: Can now debug using VSC.
/:cl:
=> VSC Debugging

code/modules/mob/living/carbon/superior_animal/superior_animal.dm
Fixes runtime
Bugfix good
:cl:
fix: roach armor runtimes fixed
/:cl:
=> Fixed roach armor

code/modules/mob/mob_grab_specials.dm
changes the formula from ROB/2 + 15 to ROB + 15, effectively doubling the damage. Still balanced and fair. I swear
I recieved some feedback about it being REALLY weak, so here
yes it's just a balance change, cry about it
:cl:
balance: made suplex stronger
/:cl:
=> Suplex buff

code/game/objects/structures/cyberplants.dm
*refuses to elaborate further
It's https://github.com/discordia-space/CEV-Eris/pull/6984
I did not test this.
I took pity on valo wrangling with the .dme
:cl:
tweak: holographic plants now shine a bit brighter.
/:cl:
=> Re brightens Cyberplants

code/modules/mob/living/living.dm
Makes the weakened condition work as intended in limiting player movement.
:cl:
fix: prevents players with the weakened status from being able to speed up movement by diving repeatedly instead of crawling.
/:cl:
=> Prevent wave dashing cripples

maps/CEVEris/_CEV_Eris.dmm
2 rooms changed for hopefully makings bombings from those harder, and no more effortless jumping in MBO office.
Delegate approved.
:cl:
tweak: tweaked 2 rooms in maint, one has more catwalks while other is now floored.
/:cl:
=> Minor maint map changes

code/datums/wires/explosive.dm
C4 wires will no longer runtime when interacted with
fixes good
:cl:
fix: fixes a runtime when interacting with C4 wires
/:cl:
=> C4 runtime fix

code/modules/mob/hear_say.dm
I did the woopsie.
Whoopsies bad.
:cl:
fix: hear_say.dm runtime
/:cl:
=> hear_say.dm hotfix

code/modules/clothing/spacesuits/rig/rig_wiring.dm
This pr fix RIG hacking and add named wires for him. btw, thanks Alliostra and KIROV for pushing and helping with the code. (The whole code was essentially written by them : p, I just made this PR).
fixes good, more fixes for god of fixers.
:cl:
fix: Add name for wires in rig code, to avilable hack em.
/:cl:
=> RIG wires fix

code/datums/objective/individual_objective/common.dm
lowered the time required to keep eye contact with someone for the "obsessive observation" objective from 5 to 3 minutes, this objective is very hard to complete without just talking to the guy you're supposed to look at, which kind of defeats the purpose. 3 Minutes is till plenty of time to creepily weasel around someone.
also lowers the amount of time needed to complete the objective where someone is supposed not to have their sanity lowered below 50 from 15 minutes to 5 minutes you know why.
I've made a few content updates now, I've earned myself a balance PR (luv me balance update)
:cl:
balance: lowered the time required to do something for some personal objectives
/:cl:
=> Personal objectives balance

code/datums/wires/wires.dm
Wire panels without descriptions for wires in them will no longer runtime when interacted with.
fixes good
:cl:
fix: Wire panels without descriptions for wires in them will no longer runtime when interacted with.
/:cl:
=> Wire panel runtime fix

code/modules/projectiles/guns/projectile/automatic/lmg.dm, code/modules/projectiles/guns/projectile/automatic/maxim.dm
lmg from 20 to 4(bruh!)
maxim from 25 to 5 (oof!)
two people were very upset
:cl:
tweak: brace penalty reduction for lmgs
/:cl:
=> brace penalty reduction for lmgs

code/modules/mob/living/carbon/human/human_attackhand.dm, code/modules/mob/mob_grab_specials.dm
joint time doesnt scale off ROB anymore(yes, a ROB debuff!!!!!!!), dislocating and jointlock show progress bar because they are long
also fix
and blance
QoL love
fix good
yet another balance change nobody asked for
:cl:
fix: jointlock
tweak: progress bars for joint and dislocating
balance: less pain damage on joint
/:cl:
=> Fix jointlock proc, better timers on joint and dislocating, joint deals less pain damage

code/game/objects/items/weapons/storage/boxes.dm
Fixes bug
Bugfix good
:cl:
fix: sting grenades spawning in armory
/:cl:
=> Fixed sting grenade box populator and name

code/game/turfs/simulated/walls.dm
Fix ricochet text.
:cl: Hyperio
fix: Fixed ricochet text
/:cl:
=> Fix ricochet text

code/game/machinery/deployable.dm, code/game/objects/structures/low_wall.dm, code/modules/tables/interactions.dm
Depending on aiming, a bug allows people behind cover to be hit without the cover properly activating. This fixes it.
Bugfix good.
:cl:
fix: cover triggers properly
/:cl:
=> Makes cover work at a distance

code/modules/mob/living/recoil.dm, code/modules/projectiles/gun.dm, code/modules/projectiles/guns/projectile/automatic/lmg.dm, code/modules/projectiles/guns/projectile/automatic/maxim.dm
Changes a few lines of Kegdo's bracing code and balances LMGs using the new system. A balance PR, in effect.
LMGs now have significantly more punch, especially against armoured targets. They are easier to manage, but still much harder than pre-bracing.
LMGs now benefit a lot more from bracing, and bracing now provides the buffs written in the documentation.
In line with Tactical Combat design documentation.
:cl:
Balance: Bracing values tweaked, LMGs improved significantly.
/:cl:
=> LMG and HMG fix

code/game/machinery/deployable.dm, code/game/objects/structures/girders.dm, code/game/objects/structures/grille.dm, code/game/objects/structures/railing.dm
Allows bracing on - barricades, girders, deployable barrier and grills.
More bracing interaction for people to use their guns on,
:cl:
add: Allows bracing on -  barricades, girders, deployable barrier and grills.
/:cl:
=> Adds more brace interactions

code/game/machinery/deployable.dm, code/game/objects/structures/low_wall.dm, code/modules/tables/interactions.dm
Remerge #7045 , all credits to Humonitarian
Cover fix
:cl:
fix: Covers now trigger properly
/:cl:
=> Makes cover work at a distance (bis)

code/game/machinery/deployable.dm, code/game/objects/structures/low_wall.dm, code/modules/tables/interactions.dm
Fixes emitter hitting low wall
I wonder
:cl:
fix: emitter no longer hits low walls
/:cl:
=> Fixes emitter hitting low wall

code/modules/mob/living/simple_animal/friendly/iriska.dm
It seems Iriska breaks when she eats food that wasn't dirtied by the hands of a living being. This PR addresses this problem.
Fixes runtimes regarding our favourite cat.
:cl:
fix: Iriska and Dusty date less often
/:cl:
=> Fixes Iriska runtimes

code/modules/clothing/spacesuits/rig/rig.dm
Makes the RIG UI more responsive in general by calling an update everytime a button is pressed
At higher player loads , the MC progressively gets more loaded , and the MC update tick gets called less, resulting in very unresponsive rig UI's.
nanoui autoupdate is a curse upon this codebase and a pinnacle of  coder lazyness
:cl:
code: RIG UI's now update at clicks.
/:cl:
=> Makes rigs update instantly when pressing buttons

code/modules/hydroponics/trays/tray.dm
fix a bug
a runtime on every process() for a tray is not good
:cl:
fix: dielthymine did not process properly in trays.
/:cl:
=> fix diethylamine not processing properly

code/modules/core_implant/cruciform/machinery/eotp.dm
used the wrong var, not sure when this got swappped
it works
:cl:
fix: eotp quick fix
/:cl:
=> fix eotp not working

maps/CEVEris/_CEV_Eris.dmm
Fix this vent which was connected to the scrubber system instead of the supply system.
:cl: Hyperio
fix: Fixed broken vent in kitchen quarters
/:cl:
=> Fix broken vent in kitchen quarters

code/modules/reagents/recipes.dm
What it says on the tin
By jove let the fucking CLI work
:cl:
fix: Fixes CLI Error
/:cl:
=> Quick CLI fix

code/datums/movement/mob.dm, code/modules/mob/living/carbon/human/human_defines.dm, code/modules/mob/living/carbon/human/human_movement.dm, code/modules/mob/living/living.dm, code/modules/mob/mob_movement.dm
Reverts discordia-space/CEV-Eris#7108
=> Revert "Diving & Sliding: Implements Momentum, removes nutrition demand"

code/modules/projectiles/guns/projectile/automatic/ak47.dm, code/modules/projectiles/guns/projectile/automatic/luty.dm, code/modules/projectiles/guns/projectile/battle_rifle/boltgun.dm, code/modules/projectiles/guns/projectile/shotgun/handmade.dm
All names from the Foundation series by Isaac Asimov.
New names cool,
:cl:
tweak: Many HomeMadeTM guns renamed
/:cl:
=> Makeshift gun renames

code/game/machinery/computer/ai_core.dm, code/modules/mob/living/silicon/ai/ai.dm
Makes the AI self destruct roundstart. Intended to be merged at a specific date.
Makes the game more compliant with the lore.
:cl:
add: AI self destructs roundstart
/:cl:
=> Makes the AI self destruct roundstart

code/modules/projectiles/guns/projectile/shotgun/handmade.dm
Increases the damage of the slide barrel shotgun
Much needed buff on a suprisingly expensive, yet worthless weapon
:cl:
balance: makeshift slide barrel shotgun buffed
/:cl:
=> Buffs slide barrel shotgun

code/game/objects/structures/crates_lockers/closets/secure/security.dm
No free second gun for FO
If he wants a second gun he has to fucking pay for it like everyone else
:cl:
del: Removed avasarala + a mag from FO's locker.
/:cl:
=> Remove Avasarala + 1 mag from FO's locker

code/datums/outfits/equipment/backpacks.dm
Added a leather satchel to the bag selection menu.
A leather satchel looks quite interesting. New satchel.
edit: Add a leather satchel to the bag selection menu.
/:cl:
=> Leather satchel

code/modules/mechs/mech_icon.dm
Sometimes randomly generated mekas runtime on `update_icon()`. Shouldn't happen anymore.
Fixes cool.
:cl:
fix: runtime in mech_icon.dm
/:cl:
=> Fix runtime in mech_icon.dm

code/modules/mob/living/simple_animal/friendly/cat.dm, code/modules/mob/living/simple_animal/friendly/corgi.dm, code/modules/mob/living/simple_animal/parrot.dm
Pets heal sanity , Ian provides -2 , Normal cats , parrots and corgis -1, and Runtime -2
Makes pets more usefull.
:cl:
add: Pets now heal sanity .
/:cl:
=> Makes pets overpowered ( Pets now heal sanity)

code/modules/mob/living/living.dm, code/modules/mob/living/living_defines.dm, code/modules/projectiles/gun.dm
Players can no longer dive/slide in space or when grabbed by someone.
Fixes cool.
:cl:
fix: diving in space
fix: diving when grabbed
/:cl:
=> Fix space and grab diving

code/game/objects/items/devices/radio/radio.dm
Fixes cool.
:cl:
fix: runtime in radio.dm
/:cl:
=> Fix runtime in radio.dm

code/modules/recycling/disposal.dm
Fixed runtime introduced in #6985.
Fixes cool.
:cl:
fix: chat-related runtime
/:cl:
=> Fix runtime in chat.dm (actually disposal.dm)

code/__DEFINES/cyborg_traits.dm
Fixes cyborg trait bit-numbers
Some traits were applied randomly due to correlating numbers
:cl:
code: Fixed some cyborg traits being randomly added.
/:cl:
=> AI Nerf(Fixes cyborg traits)

code/game/machinery/crafting_station.dm
at Holvr's request. Helps clarify when you have goofed up when crafting gun parts.
Helps clarify why you aren't getting gun parts.
:cl:
add: Added notice for gun part crafting failure
/:cl:
=> Adds notice when you fail to craft gun parts

code/modules/mechs/mech_damage.dm
Fixes roaches targetting bodyparts mechs don't have.
fix
:cl:
fix: Fix roaches not targetting mechs properly
/:cl:
=> Fix mech runtime

code/game/verbs/ooc.dm
Press in case fancy chat didn't load.
Ported from downstream who ported it from TG.
QoL stuff.
:cl:
add: button for reloading fancy chat
/:cl:
=> Port "Fix chat" button

code/modules/mob/living/carbon/human/human.dm
Seeing mutant forcing people to speak, even when dead, was hilarious.
But that's not intended behavior.
Fixes cool.
:cl:
fix: missing check in some mutation-based abilities
/:cl:
=> Hotfix some mutations not checking user's status

code/game/objects/effects/roaches.dm
Reverts #7162.
Easter is over, time to move on.
:cl:
del: easter eggs
/:cl:
=> Revert "Add Easter eggs"

code/modules/trade/datums/trade_stations_presets/1-common/caduceus.dm, code/modules/trade/datums/trade_stations_presets/1-common/nt_cruisers.dm
Typos: "blusepace tomato seeds" in NTV "Faith" and "ossissine bottle (60u)" in MAV "Caduceus".
Because it's more convenient.
:cl:
/:cl:
=> Fixed a few typos

code/modules/reagents/reagent_containers/glass/bottle.dm, code/modules/trade/datums/trade_stations_presets/1-common/boozefood.dm, code/modules/trade/datums/trade_stations_presets/1-common/caduceus.dm, code/modules/trade/datums/trade_stations_presets/1-common/nt_cruisers.dm, code/modules/trade/datums/trade_stations_presets/1-common/smoke.dm, code/modules/trade/datums/trade_stations_presets/1-common/suit_up.dm, code/modules/trade/datums/trade_stations_presets/1-common/zarya.dm, code/modules/trade/datums/trade_stations_presets/2-uncommon/advmoe.dm
The chem price drop among other things reduced the price of alot of items in the beacon to below standard prices. Other issues like animals being 1/50 of the price they were pre beacon I just upped a couple of the prices. Also artist statues sell at a medium price from my experience in making/selling them. 600 was unacceptable.
no more 5 credit cigars, it brings things to an acceptable price instead of a few basically free items that you can make profits on
:cl:
tweak: beacon prices have been changed
/:cl:
=> Trade station price update

code/modules/mob/mob.dm
For some reason mobs are being passed to hard del() 100% of the time.
Fixes cool, lags uncool.
:cl:
fix: possibly fixed mobs being deleted improperly 
/:cl:
=> Tweak mob deletion

code/game/machinery/autolathe/autolathe.dm, code/game/machinery/recycle_vendor.dm
Addresses found bugs and balance complaints.
:cl:
balance: recycling vendor payouts halved
fix: several recycling vendor bugs
/:cl:
=> Hotfix some recycling bugs and cut payouts in half

code/modules/projectiles/ammunition/ammo_kits.dm
Fixes .50 scrap slugs in ammo kits giving pistol ammo
Small bug thats not all that intented and allows the slugs to be gotton
:cl:
fix: Fixes .50 scrap slugs in ammo kits giving pistol ammo
/:cl:
=> Ammo kit pistol fix

code/datums/autolathe/autolathe_datums.dm, code/game/machinery/smelter.dm, code/game/objects/items/stacks/stack.dm, code/modules/materials/material_sheets.dm
More changes to get_matter(), autolathes and recycler, to make sure that all materials are being accepted and counted properly, this time for real and with no exceptions.*
<sub>*Hopefully</sub>
Fixes cool.
:cl:
/:cl:
=> Tweak get matter() again

code/modules/mob/living/carbon/human/species/species.dm
Fixes an issue with damage and drug overlays not going away when they should.
Fixes cool.
:cl:
fix: damage and drug overlays not going away
/:cl:
=> Fix permanent overlays

code/modules/mob/living/carbon/superior_animal/roach/blattedin.dm
Makes roach rejuvenation work as intended (1 time maximum), currently roaches could be revived with blattedin indefinitely.
Fixes cool.
:cl:
fix: roaches revival limit not working
/:cl:
=> Fix roach rejuvenation

code/modules/mob/living/carbon/superior_animal/roach/roach.dm
Prevents dead fuhrer roaches from calling reinforcements.
Fixes cool.
:cl:
fix: dead fuhrer roaches screaming
/:cl:
=> Fix dead roaches screaming

maps/CEVEris/_CEV_Eris.dmm
Remap warehouse and nanoforge room.
Because 300 meters to the warehouse is not very cool. And Fortune asked me.
:cl:
tweak: Moved most of the loot from the warehouse to the room with nanoforge. I have slightly reduced the loot in the old warehouse. Slightly expanded the nanoforge room.
/:cl:
=> little tm remap

code/__DEFINES/trade.dm, code/modules/trade/datums/_trade_station.dm, code/modules/trade/datums/trade_stations_presets/1-common/caduceus.dm
Changes export prices and sets the import to prevent abuse
Knowing you lose almost half the money on export is depressing. I would rather lower all the prices than know I lose 40% on export. This also is for the recycling vendor because it gives at cost so guild ill be at a loss until this is merged. Fixes the export scanner being wrong by proxy
:cl:
tweak: import and export prices
/:cl:
=> Export and Import multiplier tweak

code/game/machinery/autolathe/autolathe.dm, code/game/machinery/autolathe/nanoforge.dm
Removed the oddity requirement for printing things.
Fortune asked me.
:cl:
tweak: remove oddity requirement for nanoforge.
/:cl:
=> remove oddity requirement for nanoforge.

code/__DEFINES/weapons.dm
Reduces recoil as per #7251, to make guns feel better with new aiming
#7251 
:cl:
balance: reduced recoil globally
/:cl:
=> Reduced recoil for #7251

code/modules/admin/admin.dm, code/modules/mob/observer/ghost/ghost.dm
Added verb in "Server" category for changing respawn timer.
Admins asked for this.
:cl:
admin: verb for tweaking respawn timer
/:cl:
=> Add verb for setting respawn timer

cev_eris.dme, code/game/gamemodes/events/hivemind_controller.dm, code/game/objects/structures/burrows.dm, code/modules/admin/admin_verbs.dm, code/modules/hivemind/core.dm, code/modules/hivemind/machines.dm, code/modules/hivemind/mobs.dm, code/modules/hivemind/self_defense.dm, code/modules/hivemind/wires.dm, code/modules/mob/living/simple_animal/hostile/megafauna/hivetechboss.dm
Admins asked for this.
:cl:
admin: tools for extra fancy adminbus
/:cl:
=> Add hivemind control panel

code/modules/mob/living/bot/cleanbot.dm, maps/CEVEris/_CEV_Eris.dmm
Added cleaning bots that look like roomba for Moebius and Ironhammer.
Ugh... new content, I guess?
:cl:
add: couple of roombas
/:cl:
=> Add roombas

code/game/machinery/kitchen/gibber.dm
Changed some gibber code.
Fixed infinite meat exploit.
All organic organs are consumed, while implants and augmentations rejected.
<details>
<summary>
Screenshots
</summary>
</details>
Fixes cool.
:cl:
fix: infinite meat from gibber
/:cl:
=> Fix infinite meat exploit

code/game/objects/structures/girders.dm
Significantly reduces girder health.
Gray's request
:cl:
balance: reduced girder health
/:cl:
=> Girder nerf (salt PR)

maps/CEVEris/_CEV_Eris.dmm
Remove excess showcase
mapfixes good.
:cl:
del: excess showcase
/:cl:
=> Remove excess showcase

code/modules/mob/living/carbon/superior_animal/giant_spider/giant_spider.dm, code/modules/mob/living/carbon/superior_animal/giant_spider/types/hunter.dm, code/modules/mob/living/carbon/superior_animal/giant_spider/types/nurse.dm, code/modules/mob/living/carbon/superior_animal/roach/types/fuhrer.dm, code/modules/mob/living/carbon/superior_animal/roach/types/hunter.dm, code/modules/mob/living/carbon/superior_animal/roach/types/kaiser.dm, code/modules/mob/living/carbon/superior_animal/roach/types/roachling.dm, code/modules/mob/living/carbon/superior_animal/roach/types/tank.dm, code/modules/mob/living/simple_animal/hostile/doomba.dm
What it says on the tin, good luck outrunning roaches now.
Jager (green hunter roach) is two times as fast, rest is noticeably faster, but nothing crazy.
Currently it's very easy to outmaneuver hostile mobs, that significantly reduces the challenge they meant to pose, if not outright removes it for experienced players.
:cl:
balance: increased roach and spider movement speed
/:cl:
=> Increase roach and spider movement speed

code/_global_vars/misc.dm, code/modules/admin/admin_verbs.dm
A tool for admins to ~shitspawn~ prepare for events more easily, allows to define a storage item and a list of items that would be spawned inside of it.
E.g. ammo pouch full of specific ammo, backpack with set of clothes, etc.
<details>
<summary>
Screenshots
</summary>
</details>
Admin requested this to be added.
:cl:
admin: added "manage custom kits" verb and associated functionality
/:cl:
=> Add custom kits

code/game/gamemodes/events/money_lotto.dm
Fixes cool.
:cl:
fix: runtime in money_lotto.dm
/:cl:
=> Fix runtime in money_lotto.dm

code/modules/organs/organ.dm
Fixed infection code not accounting for chest / upper body not having a parent organ.
Fixes cool.
:cl:
fix: runtime in organ.dm
/:cl:
=> Fix runtime in organ.dm

code/datums/perks/fate.dm, code/datums/perks/job.dm, code/datums/perks/oddity.dm, code/datums/perks/perk.dm
Fixes cool.
:cl:
fix: runtime in fate.dm
/:cl:
=> Fix runtime in fate.dm

code/ZAS/Fire.dm
Fixes cool.
:cl:
fix: runtime in Fire.dm
/:cl:
=> Fix runtime in Fire.dm

code/modules/clothing/spacesuits/rig/modules/computer.dm
Fixes cool.
:cl:
fix: runtime in computer.dm
/:cl:
=> Fix runtime in computer.dm

code/modules/organs/internal/_internal.dm
Fixes cool.
:cl:
fix: runtime in _internal.dm
/:cl:
=> Fix runtime in _internal.dm

code/game/turfs/simulated/floor_damage.dm, code/modules/mob/inventory.dm
Fixes cool.
:cl:
fix: runtime in floor_damage.dm
/:cl:
=> Fix runtime in floor_damage.dm

code/modules/mechs/mech_movement.dm
Fixes cool.
:cl:
fix: runtime in mech_movement.dm
/:cl:
=> Fix runtime in mech_movement.dm

code/modules/projectiles/guns/projectile/pistol/mk58.dm
i cant spell
minor spelling mistake
:cl:
fix: fixed MK58 Army's Description
/:cl:
=> Hotfix: MK58 Description

code/game/objects/items/weapons/tanks/onestar_regenerator.dm, code/game/objects/items/weapons/tools/mods/mod_types.dm, code/modules/clothing/glasses/thermal.dm
clown world
blacklists all the onestar toolmods and stuff i un blacklisted in #7310 because spawners don't work right
:cl:
fix: onestar stuff spawning in maint (and at all)
/:cl:
=> Hotfix: Onestar stuff in maint

code/modules/admin/admin.dm, code/modules/text_to_speech/tts_main.dm
Records response from tts service so we have a clue why tts stop working sometimes.
Tts cool.
:cl:
add: tts error logs
/:cl:
=> Add some error logs for tts

code/modules/admin/admin.dm, code/modules/text_to_speech/tts_main.dm
Nothing to see here, citizen.
TTS cool.
:cl:
add: debug TTS verb
/:cl:
=> One more tts verb

code/modules/text_to_speech/tts_html.dm, code/modules/text_to_speech/tts_main.dm
A typo ruined everything, sorry.
Fixes cool.
:cl:
fix: issue with api calls missing a header
/:cl:
=> Fix another TTS issue

code/game/machinery/telecomms/broadcaster.dm, code/game/sound.dm, code/modules/admin/admin.dm, code/modules/client/preference_setup/global/preferences.dm, code/modules/hivemind/mobs.dm, code/modules/mob/living/bot/bot.dm, code/modules/text_to_speech/tts_main.dm
https://user-images.githubusercontent.com/65828539/182669941-05e1ceac-5c1c-41c7-a3c4-adc7fabe5dce.mp4
:cl:
code: changed some tts-related code
/:cl:
=> Another batch of TTS improvements for test server

code/modules/text_to_speech/tts_main.dm
Nothing to see here, just a mismatched argument.
Fixes good.
:cl:
fix: wrong argument for tts proc
/:cl:
=> Itsy-bitsy tts fix

cev_eris.dme, code/game/machinery/telecomms/broadcaster.dm, code/game/sound.dm, code/modules/client/preference_setup/global/preferences.dm, code/modules/clothing/masks/voice.dm, code/modules/clothing/spacesuits/rig/modules/utility.dm, code/modules/mob/living/carbon/human/say.dm, code/modules/mob/living/carbon/human/whisper.dm, code/modules/mob/living/say.dm, code/modules/text_to_speech/tts_main.dm
What it says on the tin. Also voice changer now works.
Why wouldn't it be?
:cl:
code: voice changer compatibility with tts
/:cl:
=> Address tts feedback from test server

code/game/machinery/vending.dm
Drinks Showcase showcases drinks now
Theomat no longer eats cash
Custom vendors no longer automatically guild-affiliated
MiniPharma finally shut up
Bugfix good
:cl:
fix: various vending machine issues
/:cl:
=> Vendors fixes

code/game/objects/heatwave.dm
Heatwave now triggers properly, code quality improved.
Random zone calculation replaced with the built-in method.
Code quality, bugfix.
:cl:
fix: fixed heatwave light damage range trigger
code: Improved heatwave code
/:cl:
=> Improves heatwave code

code/modules/projectiles/guns/energy/crossbow.dm, code/modules/projectiles/guns/energy/laser.dm, code/modules/projectiles/guns/energy/plasma.dm, code/modules/projectiles/guns/energy/xray.dm, code/modules/projectiles/guns/projectile/automatic/slaught_o_matic.dm, code/modules/projectiles/guns/projectile/pistol/gyropistol.dm
fixes some guns have the wrong or no serial numbers
bugfix good?
:cl:
fix: some guns having wrong or no serial numbers
:cl:
=> Serial Number Fixes

maps/CEVEris/_CEV_Eris.dmm
some minor mapping edits, a small shop area for technomancers in their lobby, a remapping of disposals and some holoposters and decorations in and around maint. plus fixing that one tile in NT maint everyone hates
nicer mapping good
:cl:
add: more holoposters and decorations around maint
add: Shop area in technomancer lobby
tweak: Remapped Disposals
/:cl:
=> Technomancer Shop, Disposal Remap and Maintenance Cyberpunkification 

code/datums/wires/jukebox.dm, code/datums/wires/mulebot.dm, code/game/machinery/floodlight.dm, code/game/machinery/floor_light.dm, code/game/objects/items/weapons/storage/bsdm.dm, code/modules/clothing/spacesuits/rig/rig.dm, code/modules/clothing/spacesuits/rig/rig_wiring.dm, code/modules/dungeons/teleporter.dm, code/modules/hivemind/machines.dm, code/modules/mob/living/carbon/slime/examine.dm, code/modules/mob/living/carbon/superior_animal/roach/types/bluespace.dm, code/modules/mob/living/silicon/robot/drone/_drone.dm, code/modules/modular_computers/computers/modular_computer/core.dm, code/modules/modular_computers/computers/modular_computer/hardware.dm, code/modules/modular_computers/computers/modular_computer/power.dm, code/modules/organs/surgery_helpers.dm, code/modules/power/apc.dm, code/modules/research/xenoarchaeology/artifact/artifact_replicator.dm, code/modules/research/xenoarchaeology/artifact/effect.dm, code/modules/research/xenoarchaeology/artifact/effects/unknown_effect_badfeeling.dm
Fixes all text instances of `flick_lights` (even in code comments), also fixes floor lights
Fixes always good
:cl:
fix: Floor lights now have sprites again
spellcheck: BSDM, RIGs and other stuff no longer `flick_lights` and flickers properly
/:cl:
=> Fix flick_lights

code/game/machinery/camera/camera.dm, code/game/objects/items/weapons/storage/storage.dm, code/modules/mob/living/carbon/human/human.dm, code/modules/mob/living/carbon/superior_animal/superior_animal.dm
Fixes multitool interactions with camera.
Fixes roach flipping.
Fixes some items having wrong planes set at times.
Fixes lookup not working at times.
It isn't
:cl:
fix: Roaches can no longer be flipped
fix: Multitool interactions with camera
fix: Some items showign up through z-levels at time
fix: Lookup not working at times
/:cl:
=> Misc fixes.

maps/CEVEris/_CEV_Eris.dmm
Does what #7366 does, but this time it's really gonna be fixed (maybe) (i dont kow how github works nor vsc). also beer keg in upper club
Hyperio edit: See #7366 for pictures
It's not gonna be good for long
:cl:
add: Added beer keg back to club
add: added more scrubbers and vents to club
add: added more shield diffuers to junk beacon
add: added shield diffusers to incinerator room
fix: fixed conference buttons with wrong id
fix: fixed SM eject button not working
fix: fixed bad and incomplete piping in club
fix: fixed that one normal window in courtroom
fix: fixed double wall and missing hull plating
fix: more I forgot
/:cl:
=> third times the charm

maps/CEVEris/_CEV_Eris.dmm
#7367 undid #7340 due to bad commit history, and #7340 could not be reapplied directly because of conflicts. 
I rebased and fixed the conflicts by hands. Both PRs modified the plumbing in bar, maybe another tiny PR will be needed if scrubbers/vents in bar are broken after this.
Fixes #7372
:cl: Hyperio
fix: Fix #7340 and #7367 conflicts
/:cl:
=> Fix #7340 and #7367 conflicts

code/modules/ghosttrap/trap.dm, code/modules/mob/living/living.dm
(It just lets people posses whatever they want)
Its bad , its horrible , its terrible even.
:cl:
code: Fixed a exploit regarding possesions.
/:cl:
=> Fixes a so called game-breaking exploit

code/modules/economy/Accounts.dm, code/modules/economy/Accounts_DB.dm, code/modules/economy/cash_register.dm, code/modules/modular_computers/file_system/programs/generic/taxes.dm
Fixes even more code  security related stuff 
Its terrible
:cl:
code: Fixed security exploits.
/:cl:
=> MoreSecurityStuff

code/modules/surgery/autodoc.dm
Fixes shrapnel removal for autodoc
I hate autodocs
:cl:
fix: Fixed autodoc shrapnel removal not working properly.
/:cl:
=> Autodoc fix numero 4

code/modules/nano/nanoui.dm
A very likely fir for NanoUI going white
(I believe it is caused by sending updates to the client without making sure the
html is loaded , since if it happens on local , the alert can be closed and the window will reboot
but on servers , the error is only shown to the host)
Terrible
:cl:
fix: Probably fixed white screens.
/:cl:
=> Probably fixes NanoUI having permanently white UI's

code/_onclick/click.dm, code/modules/integrated_electronics/subtypes/input.dm, code/modules/mining/satchel_ore_boxdm.dm, code/modules/mob/living/bot/farmbot.dm, code/modules/multiz/structures.dm, code/modules/projectiles/guns/projectile/automatic/ak47.dm, code/modules/reagents/reagent_containers/food/snacks.dm
Fixes IH AK Folding verb
Fixes AltClicking turfs for AI and Players alike
Fixes farmbot runtiming.
Fixes being able to throw implanted items up ladders
Fixes being able to stick implanted items into pizzas.
Its fixes.
:cl:
fix: Fixes the IH AK Folding verb.
fix: Fixed AltClicking turfs,  now it will always set your statpanel to Turf tab.
fix: Fixed farmbot pathing runtimes
fix: Fixed being able to throw implanted/attached/undroppable items up ladders
fix: Fixed being able to stick implanted/attached/undroppable items in pizzas.
/:cl:
=> Fixes yet another bundle of problems

code/modules/asset_cache/asset_list_items.dm, code/modules/nano/nanoui.dm
Title
being able to view this again would be good
:cl:
fix: nanoui map view
/:cl:
=> Fix nanoui map view

code/modules/core_implant/cruciform/machinery/armaments.dm
:cl:
fix: Fixed armament disks runtiming
/:cl:
=> Fixes armaments

code/controllers/communications.dm, code/modules/integrated_electronics/subtypes/input.dm
I hate circuits
Fucking circuits breakng everything they interface with
:cl:
fix: fixes a circuit related bug
/:cl:
=> Fix atmo runtimes

code/controllers/subsystems/inactivity.dm, code/modules/client/client procs.dm
Should fix the Inactivity system kicking people randomly if no config value is set.
Duuh
:cl:
fix: Fixed inactivity kicking everyone.
/:cl:
=> Adjust is_afk so i doesn't kick if there is no kick_time value

code/game/machinery/machinery.dm
Le epic fuck up
Lets pump plasma round-start!
:cl:
fix: Fixed all binary pumps being turned on at round-start.
/:cl:
=> Fixes every pump starting online

code/modules/asset_cache/asset_list_items.dm, code/modules/nano/nanoui.dm
Reverts discordia-space/CEV-Eris#7399
Along with #7093, it breaks private messages
=> Revert "Fix nanoui map view"

code/modules/recycling/disposal.dm
so apparently this can also be an outlet, causing the runtime
runtimes bad
:cl:
fix: Fixed disposal runtime
/:cl:
=> fixfix disposals again

code/modules/asset_cache/asset_list_items.dm, code/modules/nano/nanoui.dm
Reverts discordia-space/CEV-Eris#7420 after issue with #7093 has been resolved
=> Revert "Revert "Fix nanoui map view""

code/modules/mob/living/simple_animal/friendly/mouse.dm
title. should fix the race condition of the mouse falling
less runtime + using Initialize == better
:cl:
code: mouse now inits using Initialize instead of New
/:cl:
=> Move mouse init to Initialize

code/game/machinery/atmo_control.dm
attempts to fix radio runtime by placing creation BEFORE ssmachine ticks it
less runtime == good
:cl:
fix: attempt fix radio runtime
/:cl:
=> test fix for radio runtime

code/modules/dungeons/procedural/jp_dungeon_gen.dm, code/modules/random_map/random_map.dm
title
having the random being changed while generator uses it is bad
:cl:
code: only the mc can control rng
/:cl:
=> no setting randseed outside mc

code/game/machinery/atmoalter/scrubber.dm, code/game/machinery/spaceheater.dm, code/game/objects/items/weapons/tools/multitool.dm, code/game/turfs/simulated/wall_types.dm, code/game/turfs/simulated/walls.dm, code/modules/clothing/spacesuits/rig/rig.dm, code/modules/mob/living/carbon/slime/items.dm
Just adds more descriptions for slime cores , rigs , multitool and atmos equipment.
More information for beginners
:cl:
add: Added more item descriptions
/:cl:
=> Adds more Examine Tab descriptions

code/datums/datum_click_handlers.dm
I forgot to also make this cap
Bugfix
:cl:
fix: Fixed fire-rate limits being bypassable by spam clicking(again)
/:cl:
=> Fixes fire_delay hard-cap being bypassable by spam clicking

code/__DEFINES/components.dm, code/_onclick/click.dm, code/datums/components/ai_like_control.dm, code/datums/components/clothing_sanity_protection.dm
A lone port of the AI-like-control component and its needed framework
Do not merge if  #7439  was merged , since it already includes this.
Also fixes a component removal to work properly.
Admin fuckery i guess.
:cl:
code: Added the AI-like-control component , can only be applied on humans , provides AI-like shortcuts to humans.
/:cl:
=> Adds AI-LIKE-CONTROL component(Cause gray wanted it)

code/modules/mob/living/carbon/superior_animal/roach/types/nanites.dm, code/modules/mob/living/carbon/superior_animal/roach/types/roachling.dm, code/modules/mob/living/carbon/superior_animal/roach/types/tank.dm, code/modules/mob/living/carbon/superior_animal/roach/types/toxic.dm
Changes some roach sizes
Some roaches will be harder to hit, others easier
:cl:
tweak: roach sizes changed
/:cl:
=> Tweaks roach sizes

code/modules/mob/living/carbon/superior_animal/giant_spider/giant_spider.dm, code/modules/mob/living/carbon/superior_animal/giant_spider/types/hunter.dm, code/modules/mob/living/carbon/superior_animal/giant_spider/types/nurse.dm, code/modules/mob/living/carbon/superior_animal/roach/types/fuhrer.dm, code/modules/mob/living/carbon/superior_animal/roach/types/hunter.dm, code/modules/mob/living/carbon/superior_animal/roach/types/kaiser.dm, code/modules/mob/living/carbon/superior_animal/roach/types/roachling.dm, code/modules/mob/living/carbon/superior_animal/roach/types/tank.dm, code/modules/mob/living/simple_animal/hostile/doomba.dm
Tunes down discordia-space/CEV-Eris#7281
No more lightspeed hunter roach
:cl:
balance: most roaches and spiders slowed down to be closer to old speed
/:cl:
=> Tune down "Increase roach and spider movement speed"

code/modules/mob/living/silicon/robot/gripper.dm
Lets robots remove tape from cameras using their magnetic gripper
Also gives it  descriptions for antags and normal
Firefox approved
:cl:
balance:Robots can now remove tape from cameras using their magnetic gripper
/:cl:
=> Robots can now remove tape from cameras using their gripper

code/modules/core_implant/cruciform/cruciform.dm
It's a hotfix.
It's a hotfix.
:cl:
fix: Fixed modded organs exploding in curciform holder's hands
fix: Fixed a bug with mod removal when the modded organ explodes
/:cl:
=> Hotfix for exploding organs plus fix for mod removal

code/modules/unit_tests/map_tests.dm, maps/CEVEris/_CEV_Eris.dmm, maps/CEVEris/_Eris_areas.dm
* Add vent/scrubber to Genetics
* Remove duplicate APC in maint
* Engineering post is now exempt from atmos
* Remove duplicate engineering break room area
:cl: Hyperio
fix: Fixed map issues for the CI
/:cl:
=> Fix map issues for the CI

code/game/objects/items/devices/von-krabin.dm
I forgot a debug message
No admin spam
:cl:
code: Removed a debug message from the von-krabin.
/:cl:
=> Removes debug message from von-krabin

code/modules/aberrants/organs/machinery/regurgitator.dm
:cl:
fix: Fixed items getting stuck in the regurgitator
fix: Fixed situation where regurgitator biotic substrate count would go negative
fix: Fixed potential issue with swapping parts on the regurgitator
/:cl:
=> Regurgitator fix

code/modules/projectiles/guns/projectile/revolver/artwork_revolver.dm
Fixes a runtime in artwork revolvers. They should spawn correctly when made from the artist bench now.
Bug fix
:cl:
fix: Fixed artwork revolver Initialize() runtime
/:cl:
=> Makes artwork revolvers spawn correctly

code/game/gamemodes/events/carp_migration.dm
Fixes a possible hardel for carps, though there is probably another deep rooted issue for simple mob deletion.
Hard dels are bad
:cl:
fix: fixed possible carp hard dels
/:cl:
=> Small carp hardel fix

code/modules/projectiles/guns/projectile/automatic/molly.dm, code/modules/projectiles/guns/projectile/automatic/motherfucker.dm, code/modules/projectiles/guns/projectile/automatic/slaught_o_matic.dm, code/modules/projectiles/guns/projectile/battle_rifle/boltgun.dm, code/modules/projectiles/guns/projectile/battle_rifle/levergun.dm, code/modules/projectiles/guns/projectile/pistol/handmade.dm, code/modules/projectiles/guns/projectile/pistol/mandella.dm, code/modules/projectiles/guns/projectile/revolver/artwork_revolver.dm, code/modules/projectiles/guns/projectile/revolver/havelock.dm, code/modules/projectiles/projectile/bullettypes.dm
Fixes a bunch of wrong gun stats (blame humon not me), tweaks some values anyway since oversight or over/undertuned (blame me), correctly adds the .25 speed boost humon forgot about, changes the molly desc for the new firemoded that humon will give it (i am too retarded to do it)
Something something contribution guidelines and commenter of PRs, but generally fix is good.
:cl:
tweak: tweaked a few guns to be better balanced
fix: fixed wrong gun stats
/:cl:
=> Yikes, more fixes and tweaks

code/modules/dungeons/junk_tractor_beam.dm
Disable the release feature of the JTB for now to see if the server runs better without people deleting the first one and generating a second one.
Also remove some useless `src.` and use `SPAN_DANGER` macro in console messages.
:cl: Hyperio
del: Disable release of junk field
/:cl:
=> Disable release of junk field + Cleanup code

cev_eris.dme, code/__DEFINES/MC.dm, code/__DEFINES/perf_test.dm, code/__DEFINES/qdel.dm, code/__DEFINES/subsystems-priority.dm, code/__DEFINES/subsystems.dm, code/__HELPERS/_logging.dm, code/controllers/master.dm, code/controllers/subsystem.dm, code/controllers/subsystems/garbage.dm, code/controllers/subsystems/machines.dm, code/controllers/subsystems/processing/objs.dm, code/controllers/subsystems/processing/processing.dm, code/datums/craft/menu.dm, code/datums/craft/step.dm, code/datums/datum.dm, code/game/machinery/machinery.dm, code/game/objects/items.dm, code/game/objects/objs.dm, code/game/world.dm, code/modules/asset_cache/asset_list_items.dm
title. updates the mc and garbage
performance good
seeing icons also good
:cl:
fix: icon regression
code: updated MC, GC, and subsystem
/:cl:
=> fix missing icons + yearly gcmc update

code/modules/projectiles/gun.dm, code/modules/projectiles/projectile.dm, code/modules/projectiles/projectile/bullets.dm
Nerfs buckshot combined with mods like gauss coil
Balance
:cl:
balance: bonus damage from gun mods now applies only once to buckshot
/:cl:
=> Damage bonus now divided by pelletcount

cev_eris.dme, code/__DEFINES/MC.dm, code/__DEFINES/perf_test.dm, code/__DEFINES/qdel.dm, code/__DEFINES/subsystems-priority.dm, code/__DEFINES/subsystems.dm, code/__HELPERS/_logging.dm, code/controllers/master.dm, code/controllers/subsystem.dm, code/controllers/subsystems/garbage.dm, code/controllers/subsystems/machines.dm, code/controllers/subsystems/processing/objs.dm, code/controllers/subsystems/processing/processing.dm, code/datums/craft/menu.dm, code/datums/craft/step.dm, code/datums/datum.dm, code/game/machinery/machinery.dm, code/game/objects/items.dm, code/game/objects/objs.dm, code/game/world.dm, code/modules/asset_cache/asset_list_items.dm
Reverts discordia-space/CEV-Eris#7472
Heavy lags on server. Testing if thing get better without it. Sad that no one went on the test server when we put this one up at the start of the week
=> Revert "fix missing icons + yearly gcmc update"

maps/CEVEris/_CEV_Eris.dmm
Replace this turf by a proper carpet.
:cl: Hyperio
fix: Fix turf in bar meeting room
/:cl:
=> Fix derpy turf in bar meeting room

code/modules/core_implant/cruciform/rituals/crusader.dm
Fixes litany grammer.
Less people cry in #junkyard.
:cl:
spellcheck: fixed a few typos regarding litanies,
/:cl:
=> Fix crusader grammer

code/modules/surgery/organic_damage.dm
NO FUN ALLOWED
quick 1984 fix
:cl:
fix: using spent advanced kits to heal wounds in surgery
/:cl:
=> fix using spent advanced kits to heal wounds in surgery

code/modules/acting/acting_items.dm, code/modules/clothing/chameleon.dm, code/modules/tips_and_tricks/gameplay.dm
The chameleon backpack has been replaced by a chameleon satchel.
Nobody uses backpacks.
:cl:
tweak: the chameleon backpack has been replaced by a chameleon satchel.
/:cl:
=> readds the chameleon satchel, attempt 2

code/modules/mob/living/carbon/carbon_defense.dm, code/modules/mob/living/carbon/human/human.dm, code/modules/mob/mob_grab.dm, code/modules/mob/mob_grab_specials.dm
Removed vore grab special.................................... sad..................
Added fireman throw grab special instead. Procs the same as that vile vore special, click on self with the grab. You throw your victim behind yourself, dealing holodamage, and even more holodamage if they land on a window/table/into a wall
swing grab special - grab intent neck level, swing the victim around yourself in a circle and throw them VERY far away; can't proc if there are structures/walls in range of 1 tile around you, mobs in that range get weakened. Needs the victim to be on the ground to work.
Throatslit grab special nerfed; it deals regular knife damage to victim, but with wounding multiplier of 2, so basically double the damage if unarmored, grab is not killed afterwards. Oxyloss damage is …
=> More melee additions

code/datums/browser.dm, code/modules/modular_computers/terminal/terminal.dm, code/modules/modular_computers/terminal/terminal_commands.dm, code/modules/nano/nanoui.dm
Fixes terminals not working
Added a function to update the data of an actively opened /datum/browser input
bug fex good
:cl:
fix: Fixed terminals
/:cl:
=> Fix terminals not updating , add function to update data of opened browser windows.

code/game/objects/items/weapons/circuitboards/machinery/chemistry.dm
Chem industrial board now correctly named.
Reere english bad.
:cl:
spellcheck: industrial chemical dispenser circuit board now correctly named
:cl:
=> Fixes grammer

code/game/objects/items/toys.dm
Changes lizard plushie description so it doesn't mention baylore.
Say no to baylore.
:cl:
spellcheck: lizard plushie description now doesn't reference baylore
:cl:
=> Removes baylore

code/datums/objective/individual_objective/common.dm
slowerd -> lowered
Grammer good.
:cl:
spellcheck: Corrected protector personal objective spelling
:cl:
=> Corrects personal objective grammer

code/game/objects/items/weapons/storage/fancy.dm
Makes c into a C.
Mistake bad.
:cl:
:cl:
=> Fixes DromedaryCo capitalization

code/modules/clothing/under/miscellaneous.dm
Dresses in loudout no longer debug sprite.
Debug bad.
:cl:
fix: dresses show properly in loadout now
/:cl:
=> Dresses in loudout no longer debug sprite

code/modules/clothing/glasses/hud.dm
Ironhammer tactical hud and medical hud didn't protect from flashes, so I removed that from their description.
It fixes the false description.
:cl:
spellcheck: fixed the description of ironhammer tactical hud and medical hud
/:cl:
=> Ironhammer medical hud and tactical hud flash fix

code/modules/economy/cash_register.dm, code/modules/integrated_electronics/subtypes/time.dm, code/modules/mob/mob.dm, nano/templates/pda.tmpl
IT'S A SHIP GOD DAMNIT!
:cl: Hyperio
tweak: Station time replaced by ship time
/:cl:
=> It's a ship!

code/controllers/subsystems/misc.dm
Comment a possible source of lag till things get better as a whole.
:cl: Hyperio
del: Removed exoplanet generation
/:cl:
=> Remove exoplanet generation

code/game/objects/items/weapons/tools/_tools.dm, code/modules/mob/living/carbon/superior_animal/roach/types/benzin.dm
Removes benzin roaches
Might fix lag
:cl:
del: No more benzin
/:cl:
=> Comments out benzin

code/modules/mob/living/simple_animal/hostile/stranger.dm, code/modules/projectiles/guns/energy/laser.dm, code/modules/projectiles/guns/energy/plasma.dm, code/modules/projectiles/guns/energy/rapidcrossbow.dm
Adjust penetration value of rapid crossbow and sawn off cog, adjusts firerate of plasma weapons to better measure up to new ballistic firerates.
Balance.
:cl:
balance: sawn off Cog and rapid crossbow penetration stat fixed
balance: plasma firerates increased, plasma firemode related firerate bugs fixed
/:cl:
=> Energy adjustments

code/modules/mob/living/carbon/carbon_defense.dm, code/modules/mob/mob_grab_specials.dm
refactors fireman throw, since a part of its code didn't work at all(i hate byond)
fixes swing grab special
changes throatslitting's timer a bit, should make stacking slower
fix
:cl:
tweak: throatslit timer
fix: swing grab special
fix: fireman grab special
/:cl:
=> Fix melee grab specials

maps/CEVEris/_CEV_Eris.dmm
This PR restores some of the areas from Medbay before the remap while keeping the new additions. old surgery maint is back plus the lounge has been somewhat shrunk. 
the locker room has been moved up a floor to behind chemistry. 
Chemistry had its desk moved down abit and was slightly shrunk
there is now a very tiny maint passage into silk road where the two old chem windows were. and there is now doors into maint in that area between MBO and Chem. chemists locker was moved up to chem storage
i also fixed that one tile in disposals 
also fixed some roofing in IH maint so it wont be vented when shields go down due to lack of roof
This PR also adds more posters and holoposters around the inhabited areas of the ship while removing two holoplants that looked bad in maint (sorry about that)
I …
=> Medbay Remap Remap and Map Fixes and Tweaks

maps/CEVEris/_CEV_Eris.dmm
i hate wiring i hate wiring i hate wiring. bioengineering should get power now. i forgot to connect a wire.
wiring functioning is generally good
:cl:
fix: Genetics and Organs not being connected to the power grid
/:cl:
=> Hotfix: Medbay Power

maps/CEVEris/_CEV_Eris.dmm
Remove unconnected duplicate APC that made the CI fail.
:cl: Hyperio
del: Removed duplicate APC
/:cl:
=> [MAP] Remove duplicate APC

maps/CEVEris/_CEV_Eris.dmm
Fuck i forgor to remove the button
fixes the video game we all play
:cl:
fix: removed a button in medbay maint and moved the obelisk like i said i did
/:cl:
=> Map Hotfix Number Two

code/modules/asset_cache/asset_list_items.dm
Fix those runtimes
```
[15:25:15] Runtime in asset_list_items.dm,410: bad icon
proc name: register (/datum/asset/simple/design_icons/register)
src: /datum/asset/simple/design_ico... (/datum/asset/simple/design_icons)
call stack:
/datum/asset/simple/design_ico... (/datum/asset/simple/design_icons): register()
/datum/asset/simple/design_ico... (/datum/asset/simple/design_icons): New()
get asset datum(/datum/asset/simple/design_ico... (/datum/asset/simple/design_icons))
Assets (/datum/controller/subsystem/assets): Initialize(null)
Master (/datum/controller/master): Initialize(10, 0, null)
[15:25:15] Runtime in asset_list_items.dm,451: bad icon
proc name: register (/datum/asset/simple/craft/register)
src: /datum/asset/simple/craft (/datum/asset/simple/craft)
call stack: …
```
=> Fix wrong icon_file check

code/game/machinery/doors/holy_door.dm
I was annoyed that I had to wear the necklace, the cross isn't even visually shown to be that big anyways so I doubt the comment's claims to its size.
Less inventory management, yes, I know, but I don't care who comments. I'm not wearing it.
:cl:
tweak: Tau Cross Necklace is now a small item.
/:cl:
=> Tau Necklace is now small item class

code/modules/projectiles/guns/projectile/shotgun/bojevic.dm
Bojevic required a self-loading mechanism, but dropped a shotgun mechanism.
Fix
:cl:
fix: Fixed Bojevic disassembly
/:cl:
=> Fixes Bojevic disassembly

code/modules/mob/living/carbon/superior_animal/ai.dm, code/modules/mob/living/carbon/superior_animal/golem/golem.dm
Pleasant bugfix
Squash
:cl:
fix: roaches no longer "list/" windows when bumping into them
/:cl:
=> Fixes "list/" attacks

code/modules/onestar/generator.dm, code/modules/onestar/os_turret.dm, nano/templates/os_generator.tmpl
Apologies to the guy who died while Valo was testing.
Fix
:cl:
fix: Fixed OS laser turret using the wrong laser type
fix: Fixed backwards distance prioritization
fix: Fixed bad checks in OS machinery
add: Added missing UI template
/:cl:
=> Fixes OS machinery

code/modules/mob/living/carbon/human/say.dm
Fixes sanity grammer.
Reenglish bad.
:cl:
spellcheck: fixed a typo regarding sanity
/:cl:
=> Fixes more grammer

code/__DEFINES/is_helpers.dm, code/__DEFINES/misc.dm, code/modules/clothing/spacesuits/void/station.dm, code/modules/mob/living/living_defense.dm, code/modules/projectiles/projectile.dm, code/modules/projectiles/projectile/beams.dm, code/modules/projectiles/projectile/bullets.dm, code/modules/projectiles/projectile/plasma.dm
Shields and walls can now be penetrated, and will decrease the damage of projectiles.
Mobs now properly dodge when shot at based on size.
Also cleans up some code and fixes how agony is calculated.
Bugfix.
:cl:
fix: fixed penetrating objects
fix: small creatures can dodge
fix: various agony- and damage calculations
/:cl:
=> Penetration improvements and bugfixes [ready]

maps/CEVEris/_CEV_Eris.dmm
Fix a missing disposal pipe in medical that caused all garbage from organ research and genetics to be thrown in the medical backroom.
:cl: Hyperioo
fix: Fix missing disposal pipe in medical
/:cl:
=> Fix missing disposal pipe in medical

maps/CEVEris/_CEV_Eris.dmm
Adding two objects to the map
All gardeners and farmbots will have enough water
:cl:
tweak: Add sink to Garden and Xenoflora Lab
/:cl:
=> Add sink to Garden and Xenoflora Lab

code/modules/genetics/moecubes.dm
Minor runtime fixed
Squash
:cl:
fix: fixes a minor runtime related to cruciforms and moeballs
/:cl:
=> Fixes a codebit

code/game/objects/heatwave.dm, code/modules/mechs/mech_damage.dm, code/modules/mob/living/carbon/carbon_defense.dm, code/modules/mob/living/carbon/superior_animal/defense.dm, code/modules/mob/living/living_defense.dm, code/modules/mob/living/simple_animal/hostile/bear.dm, code/modules/mob/living/simple_animal/parrot.dm, code/modules/mob/mob_grab_specials.dm
My investigation resulted in a bear. Also a parrot, heatwave and British accent.
Fixes cool.
:cl:
fix: some division by zero
/:cl:
=> Fix division by zero

code/datums/datum_click_handlers.dm
Sanity checks for shooting loop.
Fixes cool.
:cl:
fix: rare click handler runtime
/:cl:
=> Fix click handler runtime

code/modules/projectiles/projectile.dm
Avoid division by 0 when there is just no damage to block.
```
[20:50:02] Runtime in projectile.dm,638: Division by zero 
```
:cl: Hyperio
add: Add check for division by 0 in block_damage
/:cl:
=> Add check for division by 0 in block_damage

code/modules/mob/living/carbon/resist.dm
(conditionsapply * (5 + max((stats?.getStat(STAT_ROB)) - G.assailant.stats?.getStat(STAT_ROB), 1) ** 0.8))) // ~4% minimal chance
removes illegal pow runtime
:cl: Kegdo
fix: change neckgrab resist formula to kill runtime
/:cl:
=> Change neckgrab resist formula

code/modules/projectiles/guns/mods/mods.dm
Removes duplicate DNA Lock gun mod
Why is this here?
:cl:
code: Removed duplicate gun DNA Lock gun mod from the code.
/:cl:
=> Removes duplicate gun mod

code/game/objects/items/oddities.dm
Quick fix.
Oddity now works.
:cl:
fix: Bearmath now works normally, hopefully.
/:cl:
=> Fixes bearmath

code/datums/craft/gun_parts.dm
What it says on the tin
Should prevent the debug gun from spawning
:cl:
fix: junk frames no longer turn into debug guns
/:cl:
=> Fixes grip not updating result on junk frames

code/modules/clothing/head/misc.dm
i changed one line
:cl: Kegdo
fix: Cowboy hats don't cover eyes(for style)
/:cl:
=> Cowboy hats don't cover eyes(for style)

code/game/antagonist/station/revolutionary/excel_faction.dm
Adds a confirmation panel when you press "Summon stash" button
I've tried also adding a notification that someone summoned it but I couldn't fucking figure it out, I'll appreciate help with that
People won't accidentally summon stash anymore.
:cl: Firefox13, SirRichardFrancis
add: Added confirmation panel when summoning excelsior stash
add: Added notification to all excelsior members when stash is summoned
/:cl:
=> Seize means of fatfingering

code/modules/reagents/reagent_containers/food/snacks.dm
Added code comments to the file for whenever I come back to it I don't need to go code diving for what variables do. Eating cooked junk food will specify that it will not help you "rest" instead of "grow". Changed an oversight where "shokoloud" was named "shokolad".
Kitchen-made chocolate bars are now considered a cooked junk food.
Code comments are pretty nice, and some, including myself, can be confused with the statement "helping you grow" since "grow" isn't used as a term anywhere in the sanity system.
:cl:
balance: Kitchen-made chocolate bars are now considered a cooked junk food.
spellcheck: Eating cooked junk food will specify that it will not help you "rest" instead of "grow".
spellcheck: Oversight where "shokoloud" was named "shokolad".
/:cl:
=> Some snack formatting

code/game/objects/items/devices/von-krabin.dm
It was hard deleting cause it still kept refs
its good cause no more op nt
:cl:
fix: FIxed an edge case in von-krabin deletion
/:cl:
=> Fixes von-krabin not deletin again

code/game/antagonist/station/revolutionary/excel_faction.dm
Reverts discordia-space/CEV-Eris#7696
For some reason it works fine on local but not on live server.
=> Revert "Seize means of fatfingering"

code/modules/client/client_procs.dm
so yeah this version has (popular?) cheats and it's not the latest one so it's better to be on the safe side
???
:cl:
config: 1583 BYOND build blocked from connecting due to security issues
/:cl:
=> Block 1583 BYOND build from connecting

code/modules/organs/internal/_internal.dm, code/modules/organs/organ.dm
Minor optimizations to organ code.
Performance.
:cl:
code: get_process_efficiency(), organ process is only searched once
code: handle_blood(), OP_VESSEL is searched after we know the organ has a blood requirement
code: Dead organs are removed from processing list
code: Organ stasis is only checked if there is no owner
code: Organ bleeding no longer checks if there is blood because remove_reagents() already does so
/:cl:
=> Organ optimizations

code/modules/core_implant/cruciform/rituals/machinery.dm
makes acolyte clone people without genetic damage
I have **NO** fucking idea why it's `is_inquisidor` blame russian coders
I find it really fucked up.
:cl:
balance: Acolytes now can clone people without genetic damage
/:cl:
=> Allow acolytes to clone without genetic damage

code/game/objects/items/weapons/storage/firstaid.dm
Let's the freezer hold organ mods
QoL
:cl:
tweak: Handheld freezer can hold organ mods
/:cl:
=> Freezer can hold organ mods

code/modules/mob/living/living_defense.dm
Certain PR with over 2k lines changes broke it. Shocking, I know.
Fixes cool.
:cl:
/:cl:
=> Fix crossbow bolts not embedding

code/modules/sanity/sanity_mob.dm
Dirty fix for the infinite loop in artist insight logic. It's possible leveling may have some issues due to the fix, but I was able to level up as artist and normal crew in test. I'll revisit this over the weekend.
Fix
:cl:
fix: Fixed for the infinite loop in artist insight logic
/:cl:
=> Fixes infinite loop

code/__DEFINES/perks.dm, code/datums/outfits/jobs/science.dm, code/datums/perks/job.dm, code/game/jobs/job/science.dm, code/game/objects/structures/crates_lockers/closets/secure/scientist.dm, code/modules/reagents/reagent_containers/glass/beaker.dm, maps/CEVEris/_CEV_Eris.dmm
Psychiatrist's Office is guaranteed to always spawn a bottle of whiskey for making Mindwipe, and they also now start with a vial of Psilocybin on their person. Psychiatrist may now access Xenoflora and Medical Equipment, both things they need in order to produce sanity-gain chems. They begin with ten more Vigilance so they aren't busy breaking down too much in order to help anyone.
They can at least pursue a bit more options from just their office.
:cl:
tweak: Map changes to Psychiatrist's Office, guaranteed to always spawn a bottle of whiskey for making Mindwipe.
balance: Psychiatrist may now access Xenoflora and Medical Equipment, they start with a vial of Psilocybin on their person, and they begin with ten more Vigilance.
/:cl:
=> Psychiatrist Stop-Gap Changes

code/datums/objective/individual_objective/individual_objective.dm, code/modules/sanity/sanity_mob.dm
fulfilling personal objectives doesn't give you 300 stat points anymore(1984)
fix
:cl:
fix: ridicilous stat points after fulfilling personal objective
/:cl:
=> [SPEEDMERGE THIS] quick sanity fix

code/ATMOSPHERICS/components/valve.dm, code/ATMOSPHERICS/mainspipe.dm, code/ATMOSPHERICS/pipes.dm, code/__HELPERS/_logging.dm, code/controllers/subsystems/mapping.dm, code/modules/dungeons/procedural/deepmaint.dm, code/modules/dungeons/procedural/jp_dungeon_gen.dm, code/modules/flufftext/TextFilters.dm, code/modules/mob/mob_helpers.dm, code/modules/power/singularity/singularity.dm
Changes this:
To this:
It's somewhat annoying to see unrelated warning popup all the time.
:cl:
code: Fixed 14 compiler warnings.
/:cl:
=> Warnings-be-gone

code/game/machinery/excelsior/ex_teleporter.dm
Why wouldn't it be?
:cl:
tweak: Notification about stuffing someone in excel teleporter is now bold and red.
code: Excelsior teleporter became compliant with contribution guidelines.
/:cl:
=> Misc excel teleport changes

code/modules/mob/living/carbon/superior_animal/roach/roach.dm, code/modules/mob/living/carbon/superior_animal/roach/types/support.dm
More qdel stuff related to roaches. Along with the other fixes, this should greatly reduce the amount of mob har dels.
Performance
:cl:
fix: Added roach Destroy() logic
/:cl:
=> Roach qdel fixes

code/modules/mob/living/carbon/superior_animal/superior_animal.dm
Yet another attempt at fixing the GC. Should help reduce hard dels.
Performance
:cl:
fix: Superior animal targeting cleanup in Destroy()
/:cl:
=> Superior animal qdel fix

code/modules/projectiles/ammunition.dm
Ammo magazine fix by Trilbyspaceclone.
Performance
:cl:
fix: Ammo magazines clear contents in Destroy()
/:cl:
=> Ammo magazine qdel fix

code/modules/mob/living/carbon/human/human.dm, code/modules/sanity/sanity_mob.dm
Cleans up sanity in human Destroy().
Performance
:cl:
fix: Cleans up sanity in human Destroy()
/:cl:
=> Human qdel fix

code/game/world.dm, maps/CEVEris/_CEV_Eris.dmm
Green check marks cool, red crosses uncool. 
:cl:
fix: Incorrect area placement in the third section.
code: fixed error that pops up in testing mode.
/:cl:
=> Fix map-related CI fail

code/controllers/configuration.dm, code/controllers/subsystems/chat.dm, code/modules/admin/admin.dm, code/modules/text_to_speech/tts_main.dm
Apparently bearer tokens are short-lived, so we'll request new one each round from login-password hash.
I can't tell how long hash will last though.
Do not merge until changes to config have been made.
Less round without TTS. Gray wouldn't have to change config often.
:cl:
code: Removed TTS maintenance busywork.
/:cl:
=> Make TTS receive auth keys automatically

code/controllers/configuration.dm, code/controllers/subsystems/chat.dm, code/modules/admin/admin.dm, code/modules/text_to_speech/tts_main.dm
Reverts discordia-space/CEV-Eris#7749
I did not read.
=> Revert "Make TTS receive auth keys automatically"

code/controllers/configuration.dm, code/controllers/subsystems/chat.dm, code/modules/admin/admin.dm, code/modules/text_to_speech/tts_main.dm
Reverts discordia-space/CEV-Eris#7763
=> Revert "Revert "Make TTS receive auth keys automatically""

code/modules/mob/living/carbon/superior_animal/stalker/stalker.dm, code/modules/mob/living/simple_animal/hostile/doomba.dm, code/modules/mob/living/simple_animal/hostile/onestar_drone.dm
Fixes OS mobs not dropping stock parts
Bugfix
:cl:
fix: Fixed OS mobs not dropping stock parts
/:cl:
=> OS mob component drop fix

code/game/objects/structures/burrows.dm
More cleanup for burrows to reduce the number of hard deletes.
Performance
:cl:
fix: Burrows remove themselves from global lists on Destroy() to reduce hard dels
/:cl:
=> Burrow GC fix

code/modules/clothing/head/armor.dm
Crusader helmet no longer shows your identity, and hides it properly.
Bug bad,  junkyard in shambles.
:cl:
fix: fixed crusader helmet actively revealing your Identity instead of hiding it
/:cl:
=> Crusader helmet no longer shows your identity

code/modules/clothing/head/armor.dm
Tanker helmets no longer hide beards.
Looked wack previously.
:cl:
fix: tanker helmets no longer hide beards
/:cl:
=> Tanker beard fix

code/game/objects/items/devices/organ_module/passive/muscle.dm
Corrects mechanical muscle description.
A relic from the past, they don't work like they used to.
:cl:
spellcheck: corrected mechanical muscle description
/:cl:
=> Mechanical muscle description correction

code/game/objects/items.dm
Removes a reference to item blood overlays from a global list, items_blood_overlay_by_type, on /obj/item/Destroy().
Performance
:cl:
fix: Removes a reference to blood overlays from a global list on /obj/item/Destroy()
/:cl:
=> Image GC fix

code/modules/mob/mob_grab_specials.dm
changes the density checking proc in swing grab special code so it accounts for tables and other dense objects
actually checking for free space now
:cl: Kegdo
fix: swing jank
/:cl:
=> fix swing jank

code/modules/projectiles/guns/projectile/revolver/handmade.dm
Changes handmade revolver ammo from 5 to 6.
Realistically it's a pretty weak gun, and this makes it so it can be reloaded with a speedloader properly
:cl:
balance: handmade revolver holds 6 bullets now
/:cl:
=> Changes handmade revolver ammo from 5 to 6

code/_onclick/click.dm
Fixes an error in click logic
Bug fix
:cl:
fix: Fixed click logic to include afterattack()
/:cl:
=> Fixes click logic to include afterattack()

code/modules/power/lighting.dm
Removes around 600+ objects from machinery processing
Less CPU spent on useless stuff that is already handle by APCs
:cl:
code: Lights no longer double their power draw.
/:cl:
=> Lights no longer process

code/modules/reagents/reagents/toxins.dm
The genetic reagent shows up on scanners now
Helps bioengineer tell when the next dose can be given
:cl:
tweak: Genetic reagent shows up on medical scanners
/:cl:
=> Genetic reagent is scannable now

code/game/objects/items/weapons/grenades/spawnergrenade.dm
Viscerators will no longer attack whoever primed the viscerator grenade.
Being surrounded by a swarm of drone friends is more cyberpunk then a bay leftover
:cl:
balance: viscerators will no longer attack whoever primed the viscerator grenade
/:cl:
=> Viscerators are now friendly to the deployer

code/game/objects/items/weapons/storage/backpack.dm
Makes leather satchels stylish, but have less storage space (28->20)
Sacrificing storage space for style is cool
:cl:
balance: leather satchel has less storage space, but is stylish
/:cl:
=> Leather satchels are stylish

code/controllers/subsystems/trade.dm, code/game/objects/structures/crates_lockers/closets/secure/personal/subtypes.dm, code/modules/modular_computers/file_system/programs/generic/trade.dm, code/modules/trade/machinery/trade_beacon.dm
Trade beacons use a secure crate that is ID locked when orders are purchased. Fixed an issue where the first click would not register when adding items to the shopping list.
Bug fix and a tweak
:cl:
tweak: Trade beacons use a secure crate that is ID locked when orders are purchased
fix: Fixed initial delay when adding items to the shopping list
code: Better list handling
/:cl:
=> Trade fixes

code/_onclick/click.dm, code/modules/mob/living/carbon/human/inventory.dm, code/modules/tips_and_tricks/gameplay.dm
lol got you
If we're not wearing any hat/glasses/gloves we look stylish, if we're not wearing shoes we don't look stylish, if we put away our storage slot we look stylish too
So you don't have to put something on to look stylish
:cl:
balance: If you're not wearing any glasses/hat/backpack/gloves you're stylish
balance: If you're not wearing shoes you're not stylish
/:cl:
=> Buff nude people

code/modules/projectiles/projectile.dm
This may or may not fix the bug, but it should be done regardless.
Bug fix
:cl:
fix: Adds cleanup in /obj/item/projectile Destroy()
/:cl:
=> Hotfix for projectiles deleting mobs

maps/CEVEris/_CEV_Eris.dmm
Adds a missing pipe to the Junk Beacon disposals, ensures things actually get delievered
Makes life slightly easier
:cl:
fix: Fixed a single pipe
/:cl:
=> Fixes single disposals pipe

code/modules/mob/mob_grab_specials.dm
Trying to put a person into a jointlock will now give a warning message.
No more accidental jointlocks.
:cl:
tweak: added jointlock warning
/:cl:
=> Jointlock warning

code/game/machinery/doors/airlock.dm
Annoying stuff.
:cl:
del: hallucination door shocking
/:cl:
=> Remove hallucination door shocking

code/game/machinery/doors/airlock.dm, code/modules/surgery/surgery.dm
:cl:
tweak: removed restriction on healing right/left arms while holding stuff
/:cl:
=> Remove item holding restrictions for surgery

code/modules/mob/hear_say.dm
Fixes codespeak over radio
Bugfix
:cl:
fix: codespeak now works properly over radio
:/cl:
=> Fixes bad radio

code/game/machinery/vending.dm
Lowers them so you don't have to pay a lot of money for things that mechanically behave the same. Please merge it with the ot only with #7859 
Easier style selection
:cl:
tweak: All uniform prices in style vendor are now 100 credits
/:cl:
=> Lower style vendor prices for uniforms

code/datums/craft/recipes/misc.dm
Adds a rolling pin recipe
So you can craft one in case you lose it
https://user-images.githubusercontent.com/57810301/204800808-1e06bc81-272a-4bc9-81a1-686f8fef9cb0.mp4
(this video took many times longer than coding the actual recipe but I'm proud of it)
:cl:
add: Rolling pin crafting recipe in "Misc" section
/:cl:
=> Craftable rolling pin

code/modules/mob/living/carbon/human/human.dm
Reverts discordia-space/CEV-Eris#7798
=> Revert "fix vomiting not stunning"

code/__DEFINES/weapons.dm, code/datums/datum_click_handlers.dm, code/modules/mechs/equipment/combat.dm, code/modules/mob/living/simple_animal/hostile/stranger.dm, code/modules/projectiles/guns/projectile/automatic/maxim.dm
Reverts discordia-space/CEV-Eris#7841
it broke fire rates and made full auto fire extremely slow. test your PRs i beg you
=> Revert "Fixes FA, burst delays"

code/__DEFINES/weapons.dm, code/game/objects/items/weapons/tools/mods/_upgrades.dm, code/modules/projectiles/guns/energy/lasersmg.dm, code/modules/projectiles/guns/projectile/automatic.dm, code/modules/projectiles/guns/projectile/automatic/ak47.dm, code/modules/projectiles/guns/projectile/automatic/atreides.dm, code/modules/projectiles/guns/projectile/automatic/c20r.dm, code/modules/projectiles/guns/projectile/automatic/dallas.dm, code/modules/projectiles/guns/projectile/automatic/drozd.dm, code/modules/projectiles/guns/projectile/automatic/lmg.dm, code/modules/projectiles/guns/projectile/automatic/luty.dm, code/modules/projectiles/guns/projectile/automatic/maxim.dm, code/modules/projectiles/guns/projectile/automatic/molly.dm, code/modules/projectiles/guns/projectile/automatic/slaught_o_matic.dm, code/modules/projectiles/guns/projectile/automatic/sol.dm, code/modules/projectiles/guns/projectile/automatic/straylight.dm, code/modules/projectiles/guns/projectile/automatic/sts35.dm, code/modules/projectiles/guns/projectile/automatic/type17.dm, code/modules/projectiles/guns/projectile/automatic/type47.dm, code/modules/projectiles/guns/projectile/automatic/vintorez.dm, code/modules/projectiles/guns/projectile/automatic/wintermute.dm, code/modules/projectiles/guns/projectile/automatic/z8.dm, code/modules/projectiles/guns/projectile/automatic/zoric.dm, code/modules/projectiles/guns/projectile/pistol/selfload.dm, code/modules/projectiles/guns/projectile/pistol/type62.dm, code/modules/projectiles/guns/projectile/pistol/type90.dm, code/modules/projectiles/guns/projectile/shotgun/bojevic.dm, code/modules/projectiles/guns/projectile/shotgun/type21.dm
Reverts discordia-space/CEV-Eris#7878
As god intended
=> Revert "Renames the fullauto modes"

maps/CEVEris/_CEV_Eris.dmm
Changes button's ID to a proper one
Fixes a bug
I tested it by editing the said variable on live server and ran a local one with changes - it works.
:cl:
soundadd: added a new sound thingy
sounddel: removed an old sound thingy
imageadd: added some icons and images
imagedel: deleted some icons and images
code: changed some code
refactor: refactored some code
config: changed some config setting
admin: messed with admin stuff
server: something server ops should know
/:cl:
=> Fix FO shutters

code/modules/mob/mob_grab.dm
Title
Bug fix
- Tabled a human before making changes, runtime.
- Tabled a human after change, no runtime.
:cl:
fix: Fixed a tabling runtime
/:cl:
=> Fixes grab tabling runtime

code/modules/projectiles/projectile.dm
Title
Bug fix
- Will be done live
:cl:
fix: Fixed Bump() runtime where a qdeleted objected was bumped
/:cl:
=> Fixes projectile Bump() runtime

code/modules/mob/mob_grab.dm
Title
Bug fix
- Upgraded a grab on a human with negative ROB.
:cl:
fix: Fixed a runtime caused by taking the negative root of a value
/:cl:
=> Fixes grab warmup calc runtime

code/modules/projectiles/guns/projectile/battle_rifle/boltgun.dm
Like a bunch of other guns, Kadmin has faster bullets.
It both makes sense, and it also helps the gun perform better as a sniper role, since it trades the higher damage of the other bolt guns.
My laptop lags enough I could not discern a difference, but this also happens with any other gun that is not hitscan when I local test. Bullet speed is fine on live server.
:cl:
tweak: Kadmin has slightly faster bullets
/:cl:
=> Kadmin now has faster bullets

code/game/gamemodes/events/space_weather.dm
Fixes cool.
Launched local server, spawned an event and waited for a bit.
:cl:
fix: Weather-related CI fail
/:cl:
=> Fix runtime in space_weather.dm

code/game/gamemodes/events/space_weather.dm
Kegdo wanted a certain phrase to be less common than others. My suggestion made it the most common phrase.
Fix.
- Ran the event several times.
:cl:
fix: Low frequency messages are actually low frequency
/:cl:
=> Fixes Graveyard event

code/datums/loot_spawner.dm, code/game/machinery/vending.dm, code/game/objects/items/contraband.dm, code/game/objects/items/weapons/storage/boxes.dm, code/game/objects/items/weapons/storage/firstaid.dm, code/game/objects/items/weapons/storage/misc.dm, code/game/objects/items/weapons/storage/storage.dm, code/game/objects/items/weapons/storage/uplink_kits.dm, code/game/objects/structures/crates_lockers/closets/secure/chaplain.dm, code/modules/detectivework/tools/storage.dm, code/modules/modular_computers/computers/subtypes/preset_pda.dm, code/modules/reagents/prefilled.dm, code/modules/reagents/reagent_containers/blood_pack.dm, maps/CEVEris/_CEV_Eris.dmm, maps/submaps/planetary_ruins/hydrobase/hydrobase.dmm
Saw that Njoy packets spawn empty, looked at box code and it disgusted me. Made some optimizations.
Boxes, medkits and pill bottles were affected, with no gameplay effects, other than fixes mentioned in changelog.
Codebase becomes a tiny bit less shitcoded.
Spawned as a mouse and ripped a box apart.
Checked that Njoy packs spawn full.
Spawned most of box types (some similar types are skipped) and found no abnormalities.
Disassembled a cardboard box.
:cl:
fix: Fixed nameless and empty Njoy bottles appearing.
fix: Fixed Njoy packets spawning empty
spellcheck: Changed few box names to lowercase
refactor: Partial storage code optimization
/:cl:
=> Fix njoy packets

code/modules/projectiles/guns/projectile/pistol/selfload.dm
Fixes cool.
:cl:
fix: Makarov's serial number mentioning incorrect manufacturer.
/:cl:
=> Fix Makarov serial number

code/modules/core_implant/cruciform/rituals/base.dm, code/modules/reagents/reagents/medicine.dm
The NT painkiller litany now a version of paracetamol to you that is
- un-scannable 
- has no nsa
- is hard to overdose on
The NT litany was too weak to be of any use before. Compared to FBP's who can fix away their pain with it, there weren't many advantages to being a NT outside the church.
While this is just a small change, hopefully it will not only make up for being locked out of augument and mutations, it will make the pain killer litany a tactical option to use.
- Launched the test server
- Spawned in as a NT vagabond
- Teleported to the round end area
- Attacked myself with a crowbar till my leg broke
- Did the litany
- Opened up the variables tab
- Checked to see the reagent was in my bloodstream
- Checked to see the reagent was being processed properly
:cl:
balance: NT pain …
=> NT Painkiller Litany Buff

code/game/gamemodes/roleset/simple.dm
Redoes #7810.
No more grief machine.
It works.
:cl:
del: malf AI has been removed from the storyteller
/:cl:
=> Removes malf AI from the storyteller

code/__DEFINES/mob_stats.dm, code/datums/mob_stats.dm
Easier to handle balancing , standardizes the definition of high stats across the codebase 
https://youtu.be/D675HU21oK8
:cl:
balance: All stats are now capped at a maximum of 150.
/:cl:
=> Caps all stats to a max of 150

code/modules/projectiles/projectile.dm
Kills RNGesus, Removes the accuracy debuff you get at close range for some reason.  why was this even added?
(curse you github for not letting me embed images) https://cdn.discordapp.com/attachments/534648497861951488/1057496131455680573/TacticalCombat.png
having a random miss chance at close range generally was counterintuitive and is annoying to deal with. without it combat should feel less loose and random and more tight and skillbased
i compiled then dumped 9 mags into a test dummy
:cl:
del: Removed accuracy debuff at close range
/:cl:
=> Remove RNG hit chance at close range

tgui/packages/tgui/interfaces/Processor.js
Changes requested in #7943 since MLGTASTICa's head repo was deleted.
Requested change
:cl:
tweak: Added MLGTASTICa's edits to Processor.js
/:cl:
=> MLGTASTICa's Processor.js changes

code/__DEFINES/items.dm, code/__DEFINES/weapons.dm, code/datums/datum_click_handlers.dm, code/modules/projectiles/gun.dm
Reverts discordia-space/CEV-Eris#7931
Fire rate decrease was way too low
=> Revert "Full auto cleanup and burst fire fix"

code/modules/mob/living/living_defense.dm, code/modules/projectiles/projectile.dm
Apparently I knew my code wrong, asked SPCR about it and he corrected my error. I looked through most of my previous PRs to find any cases where I made this mistake, and found a couple.
This PR fixes them.
Less bugs, guns will behave as intended, armor will become overpowered (probably)
Compiled and ran, test server encouraged, but not essential.
Extended value testing will take place once I'm free. If a test server goes up in the meantime, add this to it.
:cl:
fix: fixed calculation errors in penetration and armor
/:cl:
=> Calculation error fixes

code/game/objects/structures/window.dm
Fixing typos and the value of the thoughness divisor. Couldn't apply suggestion directly on the PR before merging because the fork has been deleted.
Refer to #7845
:cl: Hyperioo
fix: Fix window grab interaction rework
/:cl:
=> Fix window grab interaction rework

code/modules/projectiles/projectile.dm, code/modules/projectiles/projectile/beams.dm, code/modules/projectiles/projectile/bullets.dm, code/modules/projectiles/projectile/plasma.dm
Damage reduction part of penetration was off. This PR fixes it.
Wallbanging significantly harder.
Tested, numbers on localtest matched up with expected results and calculations.
:cl:
fix: walls and shields block bullets significantly more effectively
/:cl:
=> Fixes penetration calculations

code/game/objects/structures/crates_lockers/closets/secure/cargo.dm, code/modules/clothing/suits/jobs.dm
bruh
puts the old guild tech jacket in the guild tech lockers. 
people yelled at me on discord to do this.
i compiled, went into the game and opened the locker. and put the jacket on. no problems
:cl:
add: Old Guild Tech jacket
/:cl:
=> readds old guild tech jacket

code/modules/reagents/reagents/dispenser.dm
Ethanol calculated the painkiller effect wrong
Bugfix to intended value
Tested, shown new correct value 
:cl:
fix: fixed ethanol painkilling power
/:cl:
=> Fixes painkiller calculation

code/__DEFINES/items_clothing.dm, code/game/objects/items.dm, code/modules/clothing/accessories/accessory.dm, code/modules/clothing/clothing.dm, code/modules/clothing/glasses/welding.dm, code/modules/clothing/head/armor.dm, code/modules/clothing/head/misc_special.dm, code/modules/clothing/spacesuits/bomb.dm, code/modules/clothing/spacesuits/captain.dm, code/modules/clothing/spacesuits/rig/rig.dm, code/modules/clothing/spacesuits/rig/suits/combat.dm, code/modules/clothing/spacesuits/rig/suits/light.dm, code/modules/clothing/spacesuits/rig/suits/merc.dm, code/modules/clothing/spacesuits/rig/suits/station.dm, code/modules/clothing/spacesuits/spacesuits.dm, code/modules/clothing/spacesuits/syndi.dm, code/modules/clothing/spacesuits/void/excelsior.dm, code/modules/clothing/spacesuits/void/merc.dm, code/modules/clothing/spacesuits/void/offship.dm, code/modules/clothing/spacesuits/void/station.dm, code/modules/clothing/spacesuits/void/void.dm, code/modules/clothing/suits/armor.dm, code/modules/mob/living/carbon/human/human_recoil.dm, code/modules/mob/living/living_recoil.dm
Same as #7983.
Same as #7983.
Same as #7983.
:cl:
del: Removed stiffness and obscuration
/:cl:
=> Stiffness and obscuration removal try 2

code/modules/clothing/head/misc.dm
I missed this one when I was renaming other ones. Thanks to Daget for pointing this out
Fixes inconsistency
Name appeared fine on testing
:cl:
spellcheck: Renamed NT beret to Securitech that I missed the other week
/:cl:
=> Fix NT beret name

code/datums/autolathe/basic_stuff.dm, code/game/objects/items/devices/lighting/glowstick.dm, code/modules/clothing/gloves/miscellaneous.dm, code/modules/clothing/masks/breath.dm, code/modules/clothing/masks/gasmask.dm, code/modules/core_implant/cruciform/cruciform.dm, code/modules/reagents/reagent_containers/food/drinks/jar.dm
Dusters, jar and cruciform had their matter not match materials used to make them. This fixes it.
adds matter to breath and gas masks, glowsticks.
"Glass ashtray" design printed "steel ashtray". Renamed design to "Ashtray"
Fixes oversight
Recycled each item
:cl:
fix: fixed wrong materials when recycling: dusters, cruciform, jar
add: added matter to breath mask, gas mask, glowstick
fix: renamed "glass ashtray" design to "ashtray"
/:cl:
=> recycling matter oversight

code/_onclick/hud/parallax.dm
Parallax wasn't randomized at the start of the round like it used to be. Now, it is.
Fix
:cl:
fix: Randomizes parallax again
/:cl:
=> Randomizes parallax again

code/modules/client/client_procs.dm
Increases UPLOAD_LIMIT to 10MB. Current code just doesn't work and this is old version of it (and it works)
@LetterN I think this was your code, there is probably a better solution than just axing this
Allows admins to play music and upload high quality anime pics
I cannot really test it on local, but it compiled
:cl:
admin: increased upload limit to 10MB
/:cl:
=> Increases upload limit to 10 MB

code/game/objects/items/weapons/RSF.dm
Fixes invisible Service Fabricator being set to the wrong .dmi
Resolves an issue for many players trying to help club.
:cl:
fix: Cyborg Service Fabricators use the correct icon file.
/:cl:
=> Fixes invisible Service Fabricator

code/datums/autolathe/basic_stuff.dm, code/game/objects/items/weapons/design_disks/asters.dm, code/game/objects/structures/mirror.dm
Handheld mirror can be printed in autolathe. Recipe is in Asters Miscellaneous Pack disk
One less irreplaceable thing
printed, deconstructed
:cl:
add: autolathe recipe for handheld mirror
tweak: handheld mirror has materials
/:cl:
=> Printable handheld mirror

code/controllers/subsystems/voting/poll.dm, code/modules/sprite_accessories/_accessory_hair.dm
Github doesn't like some words. Substitutes one word for another.
N/A
I read the text.
:cl:
code: Made some text compliant with Github's TOS
/:cl:
=> Github TOS compliance

maps/CEVEris/_CEV_Eris.dmm
all my things in one place
https://github.com/discordia-space/CEV-Eris/pull/8022
https://github.com/discordia-space/CEV-Eris/pull/8026
https://github.com/discordia-space/CEV-Eris/pull/8028
https://github.com/discordia-space/CEV-Eris/pull/8038
stated in PRs
stated in PRs. yes I repeated tests
:cl:
add: Added obelisk to hydroponics and biogenerator
tweak: replaced regular hydroponics door with NTdoor
tweak: moved Krabin id lock button next to showcase
fix: added missing ceiling to funeral ejector
tweak: disposal bin in guild lobby now properly sends trash to sorter
fix: added missing disposal pipe in maintenance above gym
/:cl:
=> minor map tweaks and fixes

maps/CEVEris/_CEV_Eris.dmm
Remove a window in maintenance above library (and the stuff under it, i.e a disposal chute, a scrubber pipe and a supply pipe) to make #8017 and #8039 agree with each other.
Also remove a scrubber pipe that was forgotten.
:cl: Hyperio
fix: Remove window in maints above library
/:cl:
=> Remove window in maints above library

code/__DEFINES/dcs/signals.dm, code/game/atoms.dm, code/game/machinery/camera/motion.dm, code/modules/mob/living/carbon/superior_animal/ai.dm, code/modules/mob/living/carbon/superior_animal/roach/ai.dm, code/modules/mob/living/carbon/superior_animal/roach/life.dm, code/modules/mob/living/carbon/superior_animal/roach/roach.dm, code/modules/mob/living/carbon/superior_animal/superior_animal.dm
- Added targeting signals to some mobs and cameras to clear references on Destroy()
Performance
Large reduction in delete time. Used to be 100-1000 ms each round per mob type.
:cl:
fix: Added targeting signals to some mobs to clear references on Destroy()
fix: Added targeting signals to cameras to clear references on Destroy()
code: Cleaned up some camera code
/:cl:
=> Adds signals to clear misc target refs

code/modules/core_implant/cruciform/rituals/construction.dm
Allows NeoTheology to construct altars
Was a missing thing for NT
[Attachment]
:cl:
tweak: NeoTheology Altars can be constructed now
/:cl:
=> Altar construction

code/__DEFINES/items.dm, code/game/objects/items/devices/lighting/toggleable/flashlight.dm, code/game/objects/items/weapons/tools/mods/_upgrades.dm, code/modules/projectiles/gun.dm
Players can now attach flashlights to guns. Discussion requested for what weapons should allow this, in case if not all.
TactiCool
I ran around the Eris with a Kadmin that had a flashlight on it
:cl:
add: Ironhammer flashlights can be installed on guns
/:cl:
=> Functional flashlight attachments

code/modules/hydroponics/trays/tray.dm
Added liquid Biomatter to reagent lists for plant trays at half efficacy to most, if not all, other reagents in the individual lists.
Facilitates future "tainting" of plants via biomatter in a way that agrolytes would actually try to, and giving motivation to do so.
No cool video today. Hard to showcase what's mostly background change.
:cl:
add: Added biomatter reagent to plant tray reagent lists
/:cl:
=> Expanded application of Biomatter in relation to plants

code/datums/ai_law_sets.dm, code/game/objects/items/weapons/AI_modules.dm
While going through the AI laws in this codebase I noticed that there isn't too many printable "fun" lawsets so this PR adds 4 new original lawsets that should create some interesting RP scenarios.
:cl: Hopek
add: Added 4 "fun" non malicious lawsets to print. Partybot, Chefbot, TravelGuide and Friendbot
/:cl:
=> Adds 4 brand new "fun" AI lawsets

code/modules/mob/living/silicon/robot/gripper.dm
Adds the ability for the Service Gripper (unique to Service model cyborgs) to pick up and handle cash.
Previously it was a pain for a Service cyborg to accept payments from customers, could only drag the pile away, or drag the ETPOS to the counter. At least with this, the cyborg can actually handle the money. Next step: Silicon bank accounts. Stay tuned.
[dreamseeker_9FLY2hBAfy.webm](https://user-images.githubusercontent.com/11076040/231897447-a701b765-d63b-408c-938f-50393cc412db.webm)
:cl:
tweak: Added service gripper functionality to include credit handling
/:cl:
=> Silicon Economy Update Part 1 (The Implants) [Get it, because silicon] {pls laugh}

code/modules/hydroponics/seed_datums.dm, code/modules/hydroponics/seed_packets.dm, code/modules/trade/datums/trade_stations_presets/1-common/nt_cruisers.dm
Reintroduces Real Egg Plant, which I found referenced as a mutation of eggplants but the rest was empty. Filled it in, gave it yolk as an additional reagent, and added it's seed packet data and put it into the Curious Seeds of the NT Vendor. Also introduced animal protein as a reagent to blood tomatoes.
A fun thing to do with botany is mix reagents within them, see how far you can push the envelope. I found that one can mix chocolate bars in a plant, so I figured why not meatballs and dough? This essentially lets a skilled person with the right equipment splice up some plants to "automate" the more mundane mixing of basic cooking ingredients.
Plus it's funny as shit when a new player witnesses a plant straight up fart out chocolate bars. This'll be even funnier.
Meatball plant.
:cl:
add: …
=> Factorio, but with plants (Alchemy Reigns)

code/datums/craft/gun_parts.dm
Minor issue fixed
Bugfix
I didn't.
:cl:
fix: fixed .40 barrel not working on modular guns
/:cl:
=> Modular magnum barrel fixed

code/modules/research/designs/weapon.dm, code/modules/research/nodes/combat.dm, code/modules/research/nodes/robotics.dm
Adds a Anne pistol ammo recipe to the self-defense research
Ammoless self-defense
:cl:
add: Added a .35 pistol ammo recipe to the moebius self-defense research.
/:cl:
=> Morbius buffs (Adds Anne pistol ammo recipe)

code/modules/core_implant/cruciform/rituals/base.dm
(The ride never ends)
Added new litany. When used, it removes all embedded objects.(Works exactly like rejection mutation)
Gives cruciform an ability to counter carrion spiders, without making it passive buff. Gives cruciform ability to remove foreign objects **because that makes sense** without killing shrapneled disciples in the fight.
shot, spidered, threw knifes at disciple
used litany as disciple
all things fell off
:cl:
add: Added new litany: Rejection
/:cl:
=> Yet another new litany: Rejection

code/datums/autolathe/biomatter.dm
Deleted repeated section of code \datums\autolathe\biomatter.dm
No playerfacing changes
Printed and recycled each cell
:cl:
code: Deleted repeated ntcells designs from code
/:cl:
=> Removed duplicated NT cells design

code/modules/core_implant/cruciform/rituals/agrolyte.dm, code/modules/core_implant/cruciform/rituals/base.dm, code/modules/core_implant/cruciform/rituals/custodian.dm, code/modules/core_implant/cruciform/rituals/inquisitor.dm, code/modules/core_implant/cruciform/rituals/machinery.dm, code/modules/core_implant/cruciform/rituals/priest.dm
Standardized litany phrases, every one now has dot at the end
Updated some notifications to use span macros.
Standardization
Said each litany
:cl:
tweak: all litany phrases now end with a dot. (update your macros)
/:cl:
=> Litany dots

maps/CEVEris/_Eris_areas.dm
this pr makes it so that technomancer and moebius ambience now play properly like how maintenance ambience does
having functional features is good
i walked around in R&D and in Techno and the ambience played
:cl:
fix: fixed Technomancer and Moebius ambience not playing or looping
/:cl:
=> Fixes Technomancer and Moebius R&D Ambience

code/controllers/subsystems/jamming.dm
Fixes stored/held handheld jammers no working
Actually usable now
Tested on local
:cl:
fix: Fixed AI Jammers not working while held(Due to checking the distance to the wrong object)
/:cl:
=> Fixes a AI jammer bug

code/game/objects/items/wielding.dm, code/modules/mob/inventory.dm, code/modules/mob/living/carbon/carbon.dm
Wielding something will drop item in the offhand
Switching hands while wielding something will unwield it
Trying to wield empty hand will wield offhand item
Added function to drop offhand item
QoL. Makes the combat inventory management more fluid.
https://user-images.githubusercontent.com/62264115/234029810-50e9a907-bd71-4631-9c0f-8ac41f83dc36.mp4
Picked and wielded various things via various methods (video)
:cl:
tweak: wielding now is more fluid
code: Added function to drop offhand item
/:cl:
=> Wielding QoL

code/modules/mob/living/carbon/human/species/station/skeleton.dm
Gibber no longer gets frozen by putting in skeletons, there's better solutions to this, but this was most immediate.
Club no longer gets their gibber removed from the round.
None.
:cl:
fix: Gibbers no longer stall and become stuck processing forever when a skeleton is inserted.
/:cl:
=> Gibber no longer gets frozen by skeletons.

maps/CEVEris/_CEV_Eris.dmm
To be merged after https://github.com/discordia-space/CEV-Eris/pull/7913 because of unholy map conflicts. I went for the solution of a second PR just for shipside.
Won't compile without 7913
=> Shipside pulsar map

cev_eris.dme, code/game/objects/effects/map_effects/simple_portals.dm, code/modules/pulsar_engine/pulsar_consoles.dm, maps/CEVEris/_CEV_Eris.dmm, maps/pulsar/pulsar.dmm, nano/templates/pulsar_power_bridge.tmpl
Forgor this push 💀 💀 💀 
NEEDS AN EXTRA PR TO FIX ERIS MAP SIDE!!!
Normal portals instead of the fog...
:cl:
tweak: tweaked pulsar portals
/:cl:
=> Pulsar - The Lost Push

maps/CEVEris/_CEV_Eris.dmm, maps/pulsar/pulsar.dmm
Gives engine room a better and compact look overall (no one-tile long halls), adds some danger to pulsar (traps and roaches)
Less mapping eyesore.
Teleportation works (it yeets you if you use bag of holding, intended)
Shutters work
Areas are OK, roofs are there, nothing gets vented
Airlock works
:cl:
tweak: Edited engine room to make it prettier and more compact
add: Added trap and roach/spider spawners to pulsar
/:cl:
=> Followup pulsar map edits

code/modules/reagents/reagents/medicine.dm
Fixes Peridaxon treating all wounds immediately (prob might be a little too low, but eh) and healing bones. It also doesn't heal brain now (use alkysine for this)
It's a fix.
https://cdn.discordapp.com/attachments/265411250341543936/1109153257177239623/2023-05-19_19-11-37.mp4
Video that shows me breaking my ribcage and injecting peridaxon. I shoot myself several times afterwards to show that ribcage isn't healing but organs are.
:cl:
fix: Peridaxon doesn't heal brain or bones anymore. It's also slower at it.
fix: Peridaxon doesn't damage bones on OD too (brain is also spared).
/:cl:
=> peridaxon works slower and doesn't mend bones

code/controllers/subsystems/jobs.dm
Fix
Fix
Don't appear anymore if I deadmin
:cl:
fix: Removed un/whitelist player button from non-admins 
/:cl:
=> Remove whitelist/unwhitelist buttons from players view

code/modules/mob/living/carbon/human/human.dm, code/modules/mob/living/living.dm
Fixes everyone having the same DNA
The deep-lore must be hidden
Ran locally
:cl:
fix: Fixed everyone having the same DNA.
/:cl:
=> Kills the clone army( Fixes same-DNA bug)

code/controllers/subsystems/inactivity.dm
The failsafe PR failed us. It added a new runtime!!!
Fixes the issue caused by improper checks i added.
It doesn't reset it to 0 anymore constantly.
Tested locally.
:cl:
fix: Fixed playtime tracking resetting itself for any round-start joiner.
/:cl:
=> Hotfix for playtime tracking

code/controllers/subsystems/ticker.dm
Playtimes were not being saved because the ckeys were given as datums and not strings
i blame the total lack of type casting
Its a fix
Locally tested
:cl:
fix : Fixed playtimes not saving.
/:cl:
=> Fix playtimes not actually saving

code/game/machinery/telecomms/presets.dm, code/game/machinery/telecomms/telecomunications.dm, maps/pulsar/pulsar.dmm
The Pulsar Sat is fun and all, but a critical component it is missing is the ability to actually communicate to the Eris. This thing isn't Deep Maint. This is a step towards making it a hodge-podge lookin' structure with makeshift telecom, atmospherics, and jury rigged power.
I did attempt to fix the airlock that wasn't working, but after finding out that even the piping connecting the air tank to the vent don't even initialize correctly (they start disconnected), and two days of pulling my hair out on what should've been a simple map fix, I gave up. I did correct the vent's master_tag, and made sure frequencies/id/tags all lined up.
I did attempt to remap everything. If you want to see the last few marbles I have slowly drip out my ear, just tune into the coding-tent channel on the …
=> Pulsar Relay

code/__DEFINES/chemistry.dm, code/modules/organs/blood.dm, code/modules/reagents/reagents.dm
Reverts discordia-space/CEV-Eris#8142
Bleeding out is instant, other issues.
I slashed a person with a katana and they died instantly. lol.
=> Revert "Metabolism changes"

code/game/machinery/telecomms/presets.dm, code/game/machinery/telecomms/telecomunications.dm
Thought I had it, now I do. Pulsar Relay actually links, and possibly future Telecomms attempts will be easier in the future with new maps. I believe I made it so that, during autolinking, confirmation of the link makes not just the searching machine, but the machine it matches to, link.
Feel free to put it into the test server in case I'm not trusted, I'd understand.
Fixed my mistake, and hopefully prevented future mistakes.
:cl:
fix: Fixed Pulsar Relay not being appropriately linked to the HUB on the Eris.
/:cl:
=> Actual Pulsar Relay Fix

code/ATMOSPHERICS/components/unary/unary_base.dm, code/ATMOSPHERICS/pipes.dm, code/modules/multiz/pipes.dm, code/modules/projectiles/projectile.dm
Pipes and projectiles no longer hard delete.
We save 16.2 seconds every round for the Garbage Collector.
Launched game, restarted server, checked logs. Pipes were deleted successfully.
:cl:
code: some harddeletes resolved
/:cl:
=> Pipe and projectile GC fixes

code/controllers/subsystems/explosions.dm
Fixes the runtime from missing explosion epicenters (due to the SS deleting them before the game can finish throwing all objs)
Tested locally
:cl:
fix: Fixed null epicenter runtime
/:cl:
=> Fixes missing epicenter runtime

code/game/objects/effects/spawners/corpsespawner.dm, maps/CEVEris/_CEV_Eris.dmm
doktors funny event map thats like 50% complete
doktor asked
oops
:cl:
soundadd: added a new sound thingy
sounddel: removed an old sound thingy
imageadd: added some icons and images
imagedel: deleted some icons and images
code: changed some code
refactor: refactored some code
config: changed some config setting
admin: messed with admin stuff
server: something server ops should know
/:cl:
=> Funny Event Map

code/game/objects/effects/spawners/corpsespawner.dm, maps/CEVEris/_CEV_Eris.dmm
Reverts discordia-space/CEV-Eris#8248
=> Revert "Funny Event Map"

code/game/objects/items/machinery_crates.dm, code/modules/trade/datums/trade_stations_presets/1-common/asterstradecapital.dm
Removes beer and chem dispensers IKEA packs from Solnishko
Go outside and ~~touch some grass~~ buy them if you want unlimited booze and drugs.
:cl:
balance: Removed beer and chem dispensers from FTS Solnishko
spellcheck: Changes autholate to autolathe in code
/:cl:
=> Remove beer and chem dispenser from IKEA asters, fix misc typos

code/modules/projectiles/ammunition/bullets.dm
Added missing materials to stinger, NT frag, heatwave shells.
I just eyeballed values, as I had nothing to compare to, so they may be bad, give better.
Fix
Recycled each shell, printed printable.
:cl:
fix: missing materials for some grenade launcher's shells
/:cl:
=> Grenade launcher shells' materials

code/datums/craft/gun_parts.dm, code/modules/organs/external/damage.dm, code/modules/organs/internal/_internal.dm
Fixes damage issue on modular guns and wound calculation on humanmobs.
Fix fix people are dying oh no oh no
My ears are ringing because I left my headphones at maximum volume when the lobby loaded.
Humanmobs took damage roughly how it was predicted.
:cl:
fix: toxins no longer twice as lethal as intended
fix: modular guns no longer have extreme damage multipliers
/:cl:
=> Combat hotfixes

code/game/gamemodes/storyteller_print.dm
Makes admins forcing events logged
Important things being logged is good. In case someone silly and goofy decides to troll players we will know
can't do it localside
:cl:
admin: Admin-forced events, no matter successful or not, are now logged.
/:cl:
=> Make forcing events logged

code/__HELPERS/game.dm, code/modules/mob/living/say.dm
fixes people not hearing things or chat by partially reverting #8213 
fix
can't, but it compiles
:cl:
fix: fixed people not hearing local things
/:cl:
=> probably fix hearsay

code/__HELPERS/game.dm, code/modules/mob/living/say.dm
Reverts discordia-space/CEV-Eris#8277
didn't work, everyone can hear everything now
=> Revert "probably fix hearsay"

code/__HELPERS/game.dm, code/game/objects/objs.dm, code/modules/mob/living/say.dm, code/modules/mob/mob.dm
tries to fix the hearsay bug again
fix good
it compiled
:cl:
fix: fixed chat bug (again)
/:cl:
=> MEASURE ONCE CUT THRICE

code/__HELPERS/game.dm, code/game/objects/objs.dm, code/modules/mob/living/say.dm, code/modules/mob/mob.dm
Reverts discordia-space/CEV-Eris#8279
=> Revert "MEASURE ONCE CUT THRICE"

code/__HELPERS/game.dm, code/game/objects/objs.dm, code/modules/mob/living/say.dm, code/modules/mob/mob.dm
aaaaaaaaaa
my sanity is melting
it compiled
:cl:
fix: chat broke fixed again
/:cl:
=> you know already

code/datums/contract.dm, code/datums/topic/admin.dm, code/datums/uplink/devices and tools.dm, code/game/gamemodes/storyteller_print.dm, code/game/machinery/vending.dm, code/game/objects/items/devices/taperecorder.dm, code/game/objects/items/spraypaint.dm, code/game/objects/items/toys.dm, code/game/objects/items/weapons/implant/implant.dm, code/game/objects/items/weapons/storage/deferred.dm, code/game/objects/structures/cryopod.dm, code/game/turfs/simulated/walls.dm, code/modules/clothing/suits/jobs.dm, code/modules/clothing/suits/miscellaneous.dm, code/modules/organs/internal/internal_organ_processes.dm, code/modules/projectiles/guns/energy.dm, code/modules/pulsar_engine/pulsar_events.dm, code/modules/pulsar_engine/pulsar_map.dm, code/modules/reagents/reagent_containers/food/drinks.dm, code/modules/tables/tables.dm, code/modules/ventcrawl/ventcrawl_multiz.dm, nano/templates/pulsar_power_bridge.tmpl
Fixes a bunch of extra punctuation (`"!."`) and uppercases where they aren't supposed to be. Also removes swimsuit parent spawn.
~~Compiled~~ I launched the server and spawned those items, they appeared fine.
:cl:
fix: Spriteless swimsuit parent item shouldn't appear anymore
spellcheck: Fixed multiple uppercases where there should be lowercases across some items and prompts
spellcheck: Fixed extra punctuation (?.) in some decriptions
/:cl:
=> Fix miscellaneous typos

code/modules/dungeons/procedural/deepmaint.dm
Added comments to explain how makeNiche works.
I was sent an image of findNicheTurfs as an example of spaghetti code and wound up spending a lot of time figuring out what it did. I added documentation so that anyone else wondering what purpose the function serves can do so more easily.
Will allow changes made to niche generation to be done much easier, or will at least help those making them start work quicker.
Tests were not necessary, as no actual game code was changed.
:cl:
add: Added comments to deepmaint/proc/makeNiche, findNicheTurfs, and checkForWalls.
/:cl:
=> Updated makeNiche with comments

code/modules/mining/drilling/cave_generator.dm, code/modules/mining/drilling/cave_mineral.dm, code/modules/mining/drilling/deep_drill.dm, code/modules/mining/drilling/scanner.dm, code/modules/mob/living/carbon/superior_animal/golem/types/plasma.dm, maps/pulsar/pulsar.dmm
* Added "(1-6)" to the seimic activity display to indicate the possible range.
* The remaining cooldown time is now displayed when trying to regenerate a cavern.
* Tweaked the cavern cleaning mechanism so that people can pull stuff in and out. A few items are blacklisted and will just pop out of the cave instead of being deleted.
* Cavern collapse has now a countdown instead of being instantaneous, with a warning displayed to all people inside the cavern so that they have time to leave it.
* Fixed cavern wall layering so that ladder appears properly instead of being hidden under adjacent walls.
Improve the mining rework experience with new features and fixes.
Tested on live test server.
Went to asteroid, spawned a deep drill, wrenched it and clicked on it. Cave hole appeared once …
=> Mining rework (continued)

code/modules/mining/drilling/cave_generator.dm
Fix impossibility to access cavern due to a bad link with the cavern hole. Also improved condition to be able to access cavern even during collapse if back and forth are needed to retrieve stuff and such.
Launch server, triggered the cave generation and waiting till completion, clicked on hole and was able to access the cave. Was also able to access during collapse.
:cl: Hyperio
fix: Fix access to caverns
/:cl:
=> [Hotfix] Fix access to caverns

code/game/jobs/job/church.dm, maps/CEVEris/_CEV_Eris.dmm
Increasing custodian slots 2->4.
Decreasing acolyte slots 4->2 to increase their importance through scarcity.
Also fixed missing downward pipes behind guild shop while I'm at it.
Map changes:
Makes acolytes more important (hopefully). Will make ship a bit cleaner (hopefully).
Also fix.
Respawned many times to fill both slots. Checked closets' contents, crawled through both pipes.
:cl:
balance: Increased Custodian slots 2->4; Decreased Acolyte slots 4->2.
fix: fixed missing downward pipes near guild
/:cl:
=> Less acolytes, more custodians, tiny map fix

code/game/objects/structures/roachsign.dm
Makes the roachsign emit a little blue light.
Make it looks cooler, more flavor for the roachdiner that will use it (cave update)
all good, as the pic show
:cl: Twomoon
tweak: tweaked the roachsign code
/:cl:
=> roachsign now emits a bit of light

code/modules/reagents/reagent_containers/food/drinks.dm, code/modules/reagents/reagents/food-Drinks.dm, code/modules/reagents/reagents/other.dm
Makes energy drinks contain adrenaline (weak stimulant) instead of nuka cola (now not as powergamey as shit)
Lowers nuka cola speedboost significantly, lowers its NSA to 30 to compensate, increases the irradiation effect and increases heartbeat rate, removes the drowsiness removing because you already have sleepy lowering what the fuck is this powergaming piece of drink
Also makes adrenaline increase heart rate too because it's literally adrenaline
It's too strong
I compiled it and ~~it worked~~ launched the server. NSA was 30, not 50, other effects included
:cl:
balance: nuka cola now has lower speedboost, lower NSA, doesn't instantly wake you up, irradiates you more and increases heartbeat
tweak: adrenaline increases heartbeat (does this even do anything? a mystery)
tweak: energy drinks …
=> Nerf nuka-cola, energy drinks, adrenaline

code/modules/sanity/sanity_lists.dm
Adds a few new lines to breakdown list. Some are references, some are sourced locally.
More variety good.
Saw no problems launching local server
:cl:
add: new insanity lines
/:cl:
=> Adds new lines to breakdown speech list

maps/CEVEris/_CEV_Eris.dmm
Cleaned and fixed disposal mail delivery. Did slight repiping in the church and engineering. Added Club, Tool storage and Dormitories as mail destination. Each department has 2 destinations: Head office and general area. Exception is medbay - they have third one, Chemistry. And IH, they have only one mailbox which is security lobby, since almost whole 1st section is separated from the rest of the disposal system.
Fix
Disposaled myself to every possible destination as a droid.
:cl:
add: Added Club, Tool storage and Dormitories to the list of possible mail recipients. Added trash bin to the Preacher Office.
fix: fixed disposal mail delivery
/:cl:
=> Disposal mail delivery

maps/CEVEris/_CEV_Eris.dmm
Before: 
After: 
fix
Looked at where it was
:cl:
del: Removed airlock floating in space
/:cl:
=> A door? In space? Never happened!

code/modules/mining/drilling/deep_drill.dm
Prevent unwrenching the drill during collapse so that's it's not possible to pull the drill inside the cave hole and have it deleted at collapse.
* Generated a cave
* Triggered collapse
* Tried to unwrench and got the notice message
:cl: Hyperio
fix: Prevent deep drill unwrenching during collapse
/:cl:
=> Prevent deep drill unwrenching during collapse

code/game/jobs/department.dm
lowers the captains bank account from 2 million to 300k to make the captain be more mindful about spending large amounts of money or just donating it and breaking the game economy, also fixes a minor misnomer
this makes the captain no longer able to break the game economy at will by giving hundreds of thousands of credits away without consequence
:cl:
tweak: changed name of Moebius on paychecks from Corp to Labs
balance: Captain now only has 300k in thier department account
/:cl:
=> Decreases Captain Bank account to 300k, fixes moebius name in paycheck

code/_onclick/item_attack.dm
I forgot swing params arent always a list as they should be
Fix
Tested on local , every swing worked fine
:cl:
fix : Fixed swing attacks from non-mech sources.
/:cl:
=> Silly hotfix

code/modules/mechs/equipment/combat.dm
I intended it to be blunt since its mech sized.. not blade
i love autocorrect
Actually more damage than a normal claymore
Ran on local
:cl:
balance: Readjusted the mech blade structure damage from blade to blunt.
/:cl:
=> Increases mech blade structure damage (oops)

code/game/objects/structures.dm
I somehow managed to test this properly on local and then have it not work in every othe case.
Fix
Ran a local server and actually climbed in different situations instead of just one.
:cl:
fix: Fixed mech climbing.
/:cl:
=> Fixes mech climbing

code/game/machinery/excelsior/ex_teleporter.dm, code/game/objects/items/weapons/circuitboards/machinery/excelsior.dm, code/modules/reagents/reagents/food-Drinks.dm
Tones down the component requirements and  divides the price by 3
I estimated wrongly how much time it takes for excels to get 10k power and the 5k needed for components
Tested on local , far cheaper now.
:cl:
tweak: Tweaked excelsior redirector price from 10000 to 3000 and reduces the required components drastically.
/:cl:
=> Tones down excel redirector requirements

code/modules/reagents/reagents/food-Drinks.dm
Alcohols no longer have any painkilling effects whilst in blood , now instead they metabolize into ethanol better.
You could inject 3 different alcohols and get more painkilling than oxycodone.
Tested on local
:cl:
balance: Alcohol in blood no longer has painkilling effects , it instead metabolizing into ethanol.
/:cl:
=> Removes painkilling effects from alcohol in blood and makes it metabolize into ethanol

code/game/objects/structures/railing.dm
Fixes climbing over a railing as a mech moving you out of the mech and  multiplying messages.
Bug fix.
Ran a local server and climbed over a railing ,was no longer telled out of the mech.
:cl:
fix: Fixed mech railing interaction where the pilot would get moved out.
/:cl:
=> Fixes railing and mech interaction

code/modules/mechs/components/frame.dm, code/modules/multiz/structures.dm
I failed at basic computo-logic
I also forgot to include a edge case for ladders
at last . arms without prying and ladders without removing you from the mech
Ran on local , all arm types now worked for installation
:cl:
fix: Fixed the arm instalation of some mech arms asking you to remove something.
fix: Fixed using mech toolkit on the ladders causing you to get put outside of the mech.
/:cl:
=> Fixes 2 funnny mech oopsies again

code/modules/mechs/components/_components.dm
Fixes mech limbs not updating properly on each attack
Fixes mech crowbaring (again!!!)
Fixes
Went ahead , got a mech , actually put in parts,  tried to crowbar with arms and this time WITH normal tools too.
Tested gibbing with a dallas , now gibs properly
:cl:
fixed: Mech part gibbing mechanics not always triggering
fixed: Removing mech parts from a frame.
/:cl:
=> Fix for 2 other mech oopsies (again)

code/modules/mechs/components/frame.dm
:cl:
soundadd: added a new sound thingy
sounddel: removed an old sound thingy
imageadd: added some icons and images
imagedel: deleted some icons and images
code: changed some code
refactor: refactored some code
config: changed some config setting
admin: messed with admin stuff
server: something server ops should know
/:cl:
=> 2 fixes for 2 other mech oopsies

code/__DEFINES/dcs/signals.dm, code/datums/outfits/jobs/science.dm, code/game/objects/items/weapons/storage/belt.dm, code/modules/mob/living/carbon/human/human.dm, code/modules/organs/external/dismemberment.dm, code/modules/organs/internal/_internal.dm, code/modules/organs/internal/carrion.dm, code/modules/organs/internal/internal_wounds/_internal_wound.dm, code/modules/organs/internal/internal_wounds/eyes.dm, code/modules/organs/internal/internal_wounds/organic.dm, code/modules/reagents/reagents/other.dm, code/modules/surgery/organic.dm, code/modules/surgery/robotic.dm
**Can you hear the visible_message?**
**Can you see the OP_EYES?**
**Can you fix the ORGAN_BROKEN?**
**CAN YOU FEEL MY random_organ_by_process(OP_HEART)?**
Fixed typo in comment
Removed excess whitespace in techno belt line
Fixed people walking without vital organs like they are still inside
Now you actually need to attach organs in order for them to work and by default they are unattached Resuscitator now actually tells you what's wrong during resurection
Also robotist got a new fancy belt instead of toolbox!
Resuscitator now checks if the body is too damaged, as it was intended to do
Removes a critical bug that made you semi-invincible with need to only keep the brain inside your body, I guess this is gud
Gives robotist vital tools in fixing FBP's roundstart and takes rudimentry blue …
=> ErisMed fixes Season 1 Episode 2

code/__DEFINES/dcs/signals.dm, code/datums/outfits/jobs/science.dm, code/game/objects/items/weapons/storage/belt.dm, code/modules/mob/living/carbon/human/human.dm, code/modules/organs/external/dismemberment.dm, code/modules/organs/internal/_internal.dm, code/modules/organs/internal/carrion.dm, code/modules/organs/internal/internal_wounds/_internal_wound.dm, code/modules/organs/internal/internal_wounds/eyes.dm, code/modules/organs/internal/internal_wounds/organic.dm, code/modules/reagents/reagents/other.dm, code/modules/surgery/organic.dm, code/modules/surgery/robotic.dm
Reverts discordia-space/CEV-Eris#8413
=> Revert "ErisMed fixes Season 1 Episode 2"

code/__DEFINES/dcs/signals.dm, code/datums/outfits/jobs/science.dm, code/game/objects/items/weapons/storage/belt.dm, code/modules/organs/internal/internal_wounds/_internal_wound.dm, code/modules/organs/internal/internal_wounds/eyes.dm
Reupload.
Loading safe and tested fixes with separate PR to ensure that nothing needs reverting
Fixes runtimes and critical bugs
Also. New belt
Already was tested on real Eris launch and proved to cause no issues
:cl:
add: Added multitool and pliers to robotist's toolbelt. Essential tools in fixing FBP's organs
del: Removes old and rusty toolbox from robotist on roundstart
fix: Fixed stakable items consumed whole while repairing organs
runtime: Removes runtime on attmpting healing certain eye organ wound and makes it actually cureable
spellcheck: fixed a typo in signals.dm comment
/:cl:
=> !isBrokenPR()

code/modules/power/supermatter/supermatter.dm
Changes SM price from 10000 to 20000
They were able to buy a SM shard for 12000 and then sell it for 20000 at a offer station.
Ran up a local server , bought a crystal, price was now 24000 credits.
:cl:
balance: Increased SM price from 10000 to 20000. This will show in trading stations as from 12000 to 24000
/:cl:
=> Kills GUILD's LATEST monetary scheme

maps/CEVEris/_CEV_Eris.dmm
tiny map change to add a few graffitis in maint
Adds more flavor and style to maint, made sure i dont place too much of them, and only in maint and even very isolated part of maints to not overdo it.
made sure to get them only visible from a specific side of the wall using pixel shifting to keep it consistent and not weird
see pics:
:cl:
add: Added some graffis in maint as decoration
/:cl:
=> Maint decorated: graffitis

code/game/objects/items/weapons/melee/energy.dm
I do not know if  Desktop screwed itself but hopefully not.
This PR updates Energy swords examine descriptions gives them the old energy blade sound and not the gen hit whack that everything gets the Rig Energy blade   and the Eswords values have all been adjusted 
The Energy swords felt very weak compared to any normal   brute dealing weapon and its partly to do to how burns just work by adjusting the values a bit was able to get a lot more damaging wounds to appear with Eweapons 
I do plan at some point to move these over to the new  item/tool system. that almost every other weapon in game use's but thats for another time.  
Spawned energy swords
tested each sword against humans both with armor and without
swords were able to damage targets correctly  
sounds played correctly. …
=> updated Eswords

cev_eris.dme, code/modules/organs/internal/_internal.dm, code/modules/organs/surgery_helpers.dm, code/modules/surgery/assisted.dm, code/modules/surgery/organic.dm
- Adds surgery steps for assisted organs.
- Fixes issue where replacing bones destroyed the limb.
Bug fixes are good. The assisted surgery steps aren't an ideal solution, but reworking surgery doesn't sound fun when the current system is functional.
:cl:
add: Added assisted organ surgery steps
fix: Fixed bone replacement surgery
/:cl:
=> Surgery fixes

code/modules/cooking_with_jane/cooking_appliances/grill.dm, code/modules/cooking_with_jane/cooking_items/cooking_containers.dm, code/modules/cooking_with_jane/food_overrides.dm
Cooking and food related examines weren't updated alongside every other examine when the new stat panel was merged. This fixes that.
Bugfixes good.
:cl:
fix: fixed examines causing runtimes
/:cl:
=> Examines hotfix

code/modules/mob/living/living_defense.dm, code/modules/projectiles/projectile.dm
This PR removes random miss chance.
Death is our destination.
shot several monkeys using practice bullets and threw items at them a bunch with zero occurrences of a random miss or runtime.
balance: Random Miss Chance is gone.
/:cl:
=> removes random miss chance

code/modules/mechs/equipment/utility.dm, code/modules/mechs/mech_interaction.dm, code/modules/mining/mine_turfs.dm
Summary of changes:
- Time to drill scales with hardness of drill head material: steel 1.7, plasteel 1.1, diamond 0.5 seconds
- Added mining by bumping into rocks (or fixed, but I suspect it never worked)
- If you drill an object or a wall, the drill automatically continues drilling until it is destroyed (super funny, try it out)
- General fixes and improvements to this ancient code
Funny drill go brrr and better code.
Drill works as normal. Can mine, dig up sand, drill my through the entire ship, and the timers work accordingly.
:cl:
balance: Mech drill speed scales off material hardness; minor speed adjustments.
fix: Mech drills were not able to mine by bumping into walls.
code: Mech drill code is more organized.
refactor: General mech drill improvements.
/:cl:
=> Mech drill rework

code/modules/reagents/reagent_containers/food/snacks.dm
Fixes good.
:cl:
fix: Fixes a couple of roundstart runtime errors.
/:cl:
=> Fix runtime in snacks.dm

tools/changelog/generate_cl.py
changelogs were broken!
this might even fix changelogs!
this **might** even fix changelogs!
fix: this might even fix changelogs!
/:cl:
this might even fix changelogs!
=> this might even fix changelogs!

code/modules/core_implant/cruciform/machinery/eotp.dm
Adds miracle counter to EOTP description
No more gueswork!
:cl:
tweak: EOTP displays miracle points
/:cl:
=> EOTP displays miracle points.dm

code/game/machinery/autolathe/autolathe.dm, code/game/machinery/excelsior/autolathe.dm, code/modules/core_implant/cruciform/machinery/obelisk.dm
Updates the descriptions for the obelisk and autolathes to give more detail. 
Not much description was given the obelisks which explained WHAT they did. I feel more information on what they do and their benefit would help compel NT to make more, creating a potential avenue for conflict. I also updated the autolathe description to give more flavor than the old description 
Entered game, spawned items, checked items, all of them had updated descriptions. 
:cl:
tweak: Tweaked the descriptions of the autolathe, the excelsior autoforge, and the NT obelisk to give more description for what they do.
=> Description Updates

code/modules/text_to_speech/tts_main.dm
Our TTS provider NovelAI implemented persistent API tokens somewhat recently.
It would be very convenient for us to use these.
TTS surely will stop breaking every other month...
Ran local server, successfully generated a few phrases.
Hijacked some variables on live server to replicate effect of this PR, 700 successful generations and counting at the moment of opening the PR.
:cl:
config: Config for TTS now expects a persistent API token.
/:cl:
=> TTS shenanigans

code/game/jobs/job/church.dm, code/game/jobs/job/civilian.dm, code/game/jobs/job/engineering.dm, code/game/jobs/job/guild.dm, code/game/jobs/job/medical.dm, code/game/jobs/job/science.dm, code/game/jobs/job/security.dm, code/game/jobs/job/silicon.dm
uhh smolleris jobs
I dunno ask Holvr
:cl:
tweak: smol eris crew manifest
/:cl:
=> change jobs

code/__HELPERS/game.dm, code/game/objects/items/devices/radio/radio.dm, code/game/objects/objs.dm, code/modules/mob/living/say.dm
This should fix the most severe issues
IF there are STILL issues with chunk hearing send me a private DM on discord.
Its a fix and it brings back the performance gains.
Ran 2 clients on local , tested if they hear eachother in lockers , trashbins, MMI, normally , Radio.
:cl:
fix: Fixed MMI's and Radios not working
/:cl:
=> Brings back chunk hearing. Fixes MMIs/Radios not picking up and hearing messages

code/modules/organs/external/damage.dm, code/modules/organs/internal/_internal.dm, code/modules/organs/internal/internal_wounds/organic.dm
This PR fixes wound calculations and tumor child structure being out of date.
Runtimes bad, Bugs bad
shot disciples with .20 Kadmin and found good results, with and without armor.
shot disciple with Miller and found good results without armor, and appropriately weak results with armor.
shot disciple with decloner until tumor successfully appeared
fix: increased danger of radiation and war
/:cl:
=> Small erismed fix

code/controllers/subsystems/mapping/mapping_mapload_procs.dm, code/modules/holomap/generate_holomap.dm
Replaces procs from #8591 that are not supported by BYOND 514.
Fixes good.
Rolled back to 514, hosted a local server, checked that affected code still functions the same.
:cl:
fix: Fixed compilation errors on BYOND 514
/:cl:
=> 8591 hotfix

code/__DEFINES/misc.dm, code/controllers/subsystems/mapping/mapping.dm, code/modules/client/preferences.dm, code/modules/client/preferences_savefile.dm
Last launch it was discovered that character preferences can't be updated, this PR fixes the issue.
Fixes good.
Launched local server, tried saving, editing, and loading a character.
:cl:
fix: Fixed inability to save characters
/:cl:
=> Preference saving hotfix

code/modules/mining/machine_processing.dm, code/modules/mining/machine_unloading.dm, code/modules/recycling/conveyor2.dm
This PR makes map-loaded Conveyors function.
Conveyors are important!
Loaded map with conveyors, ran switch, jumped onto conveyor, conveyor moved character.
fix: fixed conveyors
/:cl:
=> Conveyor Fix
