- code/modules/mob/inventory.dm
/mob/proc/unequip is apparently unsafe and its called to unequip WITHOUT an item.
Runtimes lag 
:cl:
fix: fixed the clothing drop signal being called on nulls.
/:cl:
> Fixes a horrible runtime from signals

- code/_onclick/hud/screen_objects/base_screen_objects.dm
- code/game/objects/items.dm
- code/game/objects/items/weapons/shields.dm
Cleaner handling of the shield raising/lowering with signals instead of a Process()
Name changed to `tactical shield` with description `A personal shield made of pre-preg aramid fibres designed to stop or deflect bullets and other projectiles fired at its wielder.`
Avoid adding `Process` to item.
:cl: Hyperio
refactor: Shield handling with signals
/:cl:
> Shield handling with signals

- code/modules/mob/living/carbon/human/human_movement.dm
Removes slowdown from damage. It is now based only on limb efficiency and pain.
This is a relatively small change, but it could potentially have a big impact on the overall game. First shot advantaged will be leve important, enabling more interesting fire fighters and more options to retreat, rather than just trying to outdps each other with automatics and praying for the best. This also feels more consistent, since you would expect pain and limb efficiency to dictate speed, not some random, arbitrary damage number to stack with these things and slow you down massively.
:cl:
balance: Removes slowdown from damage. It is now based only on limb efficiency and pain.
/:cl:
> removes health_deficiency

- code/game/objects/items/devices/propaganda_chip.dm
- code/game/objects/items/devices/spy_sensor.dm
Title, before it was TECH_MAGNETS which doesn't exist and would break shit/not allow the propaganda chip to be deconstructed for research
Unintentional (probably) mistake has been fixed
:cl:
fix: The Electro-magnetic-feuro-nanite field of the propaganda chip and spy sensor has been realligned and repaired using neural-hyper-reflected-laser-connections, as such you can now properly deconstruct them for research using the destructive analyzer's solaris-mind-based-nano-manipulation.
/:cl:
> Fixes propaganda chip and spy sesnsor origin tech

- code/modules/core_implant/cruciform/rituals/priest.dm
According to the documentation, this is the side effect of performing this ritual, when it appeared I forgot to add it at the time. The stats that are subtracted from the preacher will be half of what the oddity gains.
makes the divine blessing ritual work as designed.
:cl:
tweak: The Divine Blessing ritual now reduces the stats of the performer.
/:cl:
> The Divine Blessing ritual now reduces the stats of the performer.

- code/modules/mob/living/carbon/shock.dm
Applying shock stage from initial damage jumps to 60% of the damage, instead of 40%.
I noticed in some situations people would die before getting knocked out, and hallos weapons had problems catching up with the shock stage. 
:cl:
balance: speed of which shock stage goes to regular damage increased
/:cl:
> Erismed 3 faster knockout

- maps/CEVEris/_CEV_Eris.dmm
Fixes RnD Desk Shutters values to be actually closed since they had the closed sprite, but open values.
Was annoying. Less bugs.
:cl: Herbaon
fix: RnD Shutters at roundstart are properly closed now.
/:cl:
> RnD Shutters aren't bugged roundstart

- code/datums/uplink/stealthy and inconspicuous weapons.dm
- code/game/objects/items/devices/uplink_random_lists.dm
Removes parapen from the uplink and from the ship.
The parapen is an oldified, SS13 generic tator tool. It has a broken stun that makes any combat impossible. If we are focusing on a better and funnier PVP we need to cast this to the shadow realm of oldified baycode. Also, the stun is bugged and infinite, so, more reasons to cast this into the shadow realm. I just had this idea while petting my cat, if want this dumb pen to stay, go ahead,i prefer it leaves but eh,not like i care much.
:cl:
del: Removed Parapen from this ship
/:cl:
> Fuck parapen

- code/modules/mob/living/carbon/human/human_damage.dm
- code/modules/organs/organ_description.dm
Makes it so limbs and groin don't contribute to death. They only deal pain and the associated advantages of disabling limbs now.
Further augments erismed 3 by giving a safer location to shoot someone, even if you're using lethal ammunition. The end result may make humans a tad tankier in terms of surviving death, but paincrit should be about the same. Shooting people in the head and chest is still lethal of course.
:cl:
balance: Humans don't have shared HP between all limbs and groin, making them safer to shoot for non-lethal takedowns. Aim for the chest or head to kill.
/:cl:
> Organic buff: Makes limb HP separate from death.

- code/modules/clothing/glasses/night.dm
They are treated as abstract item and shouldn't be spawned anywhere else other than when using the tactical ballistic helmet
less bugs
:cl:
fix: Fixed ballistic night vision goggles appearing outside of tactical ballistic helmet
/:cl:
> Blacklist ballistic NVGs from spawning

- code/game/jobs/job/church.dm
Title, increased each NT job cognition by 10
Primarly because of this
along with the fact that new rome gives a -10 to cog
however according to Evan:
Tl;DR - this should increase Cruciform regeneration by more than 10% for NT jobs (preacher being 25% instead)
Taking the New Rome origin will put them back at their original cog stat so i believe this also synergises nicely.
I believe this change is more of a quality of life improvment than some kind of NT buff, since the cog increase is for jobs rather than anyone with a cruciform, meaning new converts or non NT-job cruci-bearers won't get the regen boost
:cl:
tweak: The Neotheology Church on the CEV Eris has gotten a proper education now! Atleast for New Rome standards. Their cognitive capabilities have been increased by 10, whatever that …
> Increases NT job cognition

- code/modules/organs/external/_external.dm
- code/modules/organs/organ.dm
Decreases EMP damage to cybernetics from the new values, and increases from the old values. These are
External 10/5/2
Internal 12/6/3
This translates to 70/35/24 damage to a full FBP externally per EMP. Please don't make me calculate internal damage, just know that for medium and heavy it's going to be in the hundreds if you count every organ that needs to be repaired.
The previous EMP PR was done very poorly, and tried to justify it with erismed 3. It was also a poor band-aid fix to nerf FBPs, when the solution is to fix the issues that were plaguing humans. These EMPs will do reasonable damage internal and external damage, reducing their efficiency and making them easier to kill or disable, while still taking into account that the majority of EMP sources are nigh impossible to dodge. …
> Properly tweaks EMP

- code/game/objects/items/stacks/medical.dm
Fixes a bug where advanced trauma kits and bandages could be spamed and used multiple times on a bandaged wound.
Bugs are bad.
:cl:
fix: advanced trauma kits and bandages can't be stacked anymore, don't try or you are gonna waste kits.
/:cl:
> Advanced trauma kit fix

- code/modules/projectiles/guns/projectile/pistol/olivaw.dm
- code/modules/projectiles/guns/projectile/revolver/havelock.dm
Title, from 6 to 3.5 for Olivaw, from 8 to 3 for havelock
As requested by frost
I believe Havelock's and Olivaw's recoil was too damn high, and as such i reduced it
that's kinda it
:cl:
balance: Olivaw recoil reduced to 3.5 and havelock to 3
/:cl:
> Gun recoil changes

- code/modules/mob/living/carbon/carbon.dm
Try 2:
Being able to throw an item a floor above themselves is something a player would expect to be able to do. This is a pretty small change, and it's a tiny bit more polished than my previous pull. There is one math thing in it, which just multiplies an item's weight class by 5, then subtracts the result by the players robustness * 0.1, for a large object and pretty high strength this is a few seconds off
Like stated above, players expect certain cause & effect reactions. If they attempt to toss an item a floor above, they expect it to work. If they try to shoot a floor above, they expect it to work(Although this isn't the case yet for guns). 
:cl:
add: You can now toss items a floor above yourself! Heavier objects take longer to throw, slightly altered by your strength.
/:cl:
> Multiz throwing

- code/modules/projectiles/ammunition.dm
- code/modules/projectiles/guns/projectile.dm
This finally fixed all the ammo icon issues by giving the ammo clones all the defs they need, including caseless defs.
Fixed a big sprite issues and the caseless issue.
:cl: Shazbot194
fix: fixed big ammo sprite issue
fix: Caseless ammo is now always caseless
/:cl:
> Finally fully fixed big ammo sprites

- code/game/machinery/kitchen/microwave.dm
The burn barrel now stays lit unless you toggle it off.
Take a rest.
:cl:
add: Toggle to light barrel
tweak: barrel stays lit
/:cl:
> Barrel stays lit

- code/game/objects/effects/roaches.dm
- code/modules/food/recipes_microwave.dm
- code/modules/mob/living/carbon/superior_animal/roach/life.dm
- code/modules/reagents/reagent_containers/food/snacks.dm
Makes the roach egg a item/weapon now, allowing it to be implanted, picked up and shoved in a microwave
also makes a new snack, a boiled roach egg
also makes the egg and the snack both tiny items, the latter for consistency, the former so you can implant more eggs in people
There was already code for the roach egg to be implanted into people which i believe is really fucking cool, as such this PR makes it possible by making the roach egg a item/weapon
the roach egg can now also be prepared into a highly nutritious and high in protein snack, for that maintenance food experience
:cl:
add: Added new snack, a boiled roach egg, 5 parts water, 1 roach egg. Shove it all into a microwave/fire barrel at max heat
tweak: roach egg is now a tiny sized item that can be picked up
/:cl:
> Roach egg shit

- maps/submaps/deepmaint_rooms/normal/hive_nest.dmm
- maps/submaps/deepmaint_rooms/normal/normal_rooms.dm
Another kneejerk PR
adds a normal sized deepmaint room with some loot and one of each hivemind mob (except bomber), along with a abnormal PDA and 2 hivemind beakers (so a total of 60 units of each nanite)
It's not
I believe this could spice up deepmaint a bit more, by having a new room with "new" enemies in it, while not having broken easy to gain loot within nor being bloat
:cl:
add: When the hive is destroyed all the machinery is destroyed aswell, what about the little guys? A group of hive mobs have been left behind deep within the ship.
/:cl:
> Deepmaint hiveroom aka hive nest

- code/game/machinery/vending.dm
- code/game/objects/items/weapons/storage/deferred.dm
title, replaces the tuxedo, gloves, masks etc. with 4 crates (each having a different mask) that have the mask, tuxedo, gloves, the speshul dufflebag, basic armour, reinforced shoes and a tactical belt
It's not
Requested by Not rosalimo from eris and because of my own spite for players
makes it so the players have to spend a fair amount of money to get the (un)funny reference masks
:cl:
add:  Replaced clothing in bill's vendor with 4 crates filled with clown accesories
/:cl:
> replaces tuxedo, payday 2 masks etc. with 4 "crates" (in the maint vendor of course)

- code/modules/core_implant/cruciform/cruciform.dm
- code/modules/core_implant/cruciform/rituals/priest.dm
this makes several changes so that NT has more control over which miracles happen and how frequent they are, to avoid their abuse, the preachers regenerate a little less energy. 
It gives NT a little more control over its mechanics.
:cl:
tweak: offering rituals now increase the energy of the EOTP
tweak: increases the energy cost of offering rituals
tweak: reduces the energy regeneration of the preachers.
tweak: the divine blessing ritual now costs energy.
/:cl:
> offering rituals now increase the energy of the EOTP

- code/game/jobs/job/medical.dm
- code/game/jobs/job/science.dm
Gives all moebius roles maintenance access.
Everyone else on the ship has maintenance access, and recent PRs have added it to most of the ones that didn't. I feel its about time moebius received this treatment as well. Given they can already get it quite easily, I don't feel this is a problem and see no reason to withhold it from them.
:cl:
add: Added maintenance access to all moebius roles.
/:cl:
> Gives moebius maint access

- code/modules/overmap/ships/computers/helm.dm
This code checks for whether linked is null, and if so calls the error proc with relevant info and returns from the helm's Initialize proc.
The Initialize proc before this change would call linked.check_link(), which as linked would be null, runtimed.
runtime bad, this one interrupts launching a local when runtime breakpoints are enabled.
fix: fixes helm runtime on starting server with overmap disabled.
/:cl:
> fixes helm null.check_link runtime on starting server with overmap disabled

- code/game/objects/structures/wire_splicing.dm
Presently, adding wires to a wire splicing past the 10th will set used_now to true, then give an error message and return, leaving used_now set to true for eternity, causing it to be forever uninteractable.
Now, we don't set used_now until after we've checked we're actually able to add cables.
Unremovable wire splicings seem like a pretty nasty bug that could potentially be abused.
:cl:
fix: Wire splicings no longer get stuck in a state of being used if you attempt to add wires past the max.
/:cl:
> Splicings no longer get stuck in a state of being used

- code/modules/mob/living/carbon/shock.dm
- code/modules/organs/pain.dm
Lowered the knockout time from 2-3 minutes to a flat 1.5 minutes. Makes self surgery possible with either tramadol + paracetamol or oxycodone + inaprov.
Should have just made knockout play admin "man up, deal with it, move on", but this is an alternative solution.
:cl:
balance: pain knockout duration lowered to 1.5 minutes
balance: self surgery now possible by stacking 2 painkillers
/:cl:
> Erismed 3 Knockout time nerf and self surgery buff

- code/modules/projectiles/guns/projectile/boltgun.dm
changes recoil around for the bolt-action guns:
excel mosin recoil_buildup from **40!!** -> 1.6
novakovic recoil buildup from 0.4 -> 1.7
handmade joonk boltaction from **40!!** -> 1.9
two bolt-actions with silly recoil buildups is a silly concept.
recoil is a scuffed system but these numbers really don't matter unless you reduce the fire delay on these bitches with the dangerzone/forged barrel
:cl:
balance: bolt-actions' recoil has been made a little more in-line with other .30 firing rifles
/:cl:
> changes bolt-action recoil to be more in-line with other .30 rifles

- code/datums/setup_option/backgrounds/origin.dm
Adds a new origin restricted to technomancers, giving some nice combat stats, and the IH survivor perk. All code made by Beblu, PR-ed it at his request.
New origin inspired by lore. Another illusion of technomancer content.
:cl:
add: New combat focused origin for technomancers
/:cl:
> New technomancer origin by Benblu

- code/datums/perks/job.dm
- code/modules/core_implant/cruciform/cruciform.dm
- code/modules/core_implant/cruciform/machinery/obelisk.dm
Instead of having True Faith added on cruciform installation and entering an obelisk's range and removed on cruciform uninstallation and exiting an obelisk's range, this PR makes True Faith added on cruciform installation and removed on cruciform uninstallation, and activated on entering an obelisk's range and deactivated on exiting an obelisk's range.
Having a sanity bonus that you can permanently keep as long as you never enter an obelisk's range rewards you for playing NT badly; before this PR it would also appear as though you lost the perk permanently on leaving an obelisk's range. These are not good things.
:cl:Chickenish
fix: True Faith gave the benefit by itself and was added and removed by obelisks; now obelisks activate and deactivate it similarly to Exotic Inspiration.
/:cl:
> makes True Faith activate like Exotic Inspiration

- code/game/gamemodes/malfunction/newmalf_ability_trees/tree_interdiction.dm
Stop malf AI from being able to recall bluespace jumps.
Bluespace jumps are the equivalent of crew shift to end the round, it's different from ship evacuation with shuttles and AI should not be able to recall them.
:cl: Hyperio
tweak: Malf AI cannot recall bluespace jumps anymore
/:cl:
> Malf AI should not be able to recall bluespace jumps

- code/game/objects/items/devices/PDA/PDA.dm
- code/game/objects/items/weapons/clown_items.dm
- code/game/objects/items/weapons/implant/implants/carrion/smooth_spider.dm
I forgot which kind of programming language byond was (i.e not smart).
Basically the stuff after the `||` was not properly taken into account for some reason.
Fixes #6300
Fix ladder slipping cheese as intended.
:cl: Hyperio
fix: Fix slipping on ladders with slipping items
/:cl:
> Fix slipping on ladders

- code/modules/projectiles/ammunition/boxes.dm
Modifies .60 ammo to something a bit more sane. Scrap .60 ammo is slightly more rare than .35 ammo, leaving it findable but not something you'll trip over constantly. 
I'm not sure why .35 ammo has its HV and Practice variants blacklisted from trash spawning whilst every other ammo type's is allowed - if it was intentional then I'd like to know why for future documentation. I've not touched any of the other ammo rarity due to a lack of feedback, if there's any you feel are too common, or not common enough, please let me know and I'll check with others how they feel before making adjustments.
AMR ammo really should not be the most common ammo type to spawn.
:cl:
balance: .60 ammo is now more scarce. .35 HV and Practice removed from trash spawn blacklisting, the scrap variant is now much …
> Modifies .60 rarity to something more sane, unblacklists .35 ammo types

- code/modules/projectiles/guns/projectile/automatic/motherfucker.dm
the ultimate "fuck you" shotgun should not deal the same damage as the boltgun in melee, especially since it can get a bayonet attached to deal even more damage, while the boltgun can not.
death in t+5-0.05 seconds
:cl:
balance: The melee damage of the motherfucker has been nerfed by 5 damage points.
/:cl:
> Motherfucker melee damage nerf

- code/modules/multiz/pipes.dm
- maps/CEVEris/_CEV_Eris.dmm
Fix layer and level of zpipe so that they are properly displayed on standard tiles. No need to let plating tiles anymore.
Plating bad.
:cl: Hyperio
fix: Fix zpipes display on standard tiles
add: Add normal tiles to atmos room to cover unecessary plating
/:cl:
> Fix zpipes display on standard tiles

- code/modules/mob/living/simple_animal/friendly/cat.dm
I forgot to block people from carrying Dusty, which caused a "Fix me" glitched sprite.
Pet the cat, don't carry it.
:cl: Hyperio
tweak: Dusty cannot be carried anymore
/:cl:
> Dusty cannot be carried anymore

- maps/CEVEris/_CEV_Eris.dmm
This PR moves Pressurized Air tank assigned to eva access point a bit further to allow pasage to Engineering from there upon deconstruction of one wall (since I was told taht these tanks can't be really destroyed by player in any conventional way).
This will be used ~~mostly by me and me alone~~ by many many people, I promise. 
~~It's not~~ It furthers our society in many ways.
:cl:
tweak: Edited bit of maint next to EVA access point above S3 hallway
/:cl:
> Slight map edit of airlock above S3 hallway

- maps/CEVEris/_CEV_Eris.dmm
Medbrig now gets its own sleeper (I tried to restrict access to it so that only medspec can apply chems, it didn't really work though for whatever reason), proper surgery&oxyloss kit, organ freezer and a minor refurbishment. 
Removed area of space in bar's walls too, minor oversight would cause shield to pop in there.
There is, in my opinion, no point in keeping medspec neutered as he is now (since he has to spend considerable time and resources to get nearly close to actual medbay's capabilities). While Medbrig shouldn't get everything medbay does, many people feel like sleeper is bare minimum to actually do any medicine there semi-reliablly. Either that, or give up on medspec entirely.
:cl:
tweak: tweaked birgmed's equipment
fix: fixed a shield tiel appearing in bar
/:cl:
> Medical Specialist appreciation day

- code/__DEFINES/is_helpers.dm
- code/modules/core_implant/cruciform/cruciform.dm
- code/modules/core_implant/cruciform/rituals/base.dm
something something, makes lesser form not being able to be cruciformed and if they somehow manage to get it and activate it on, it should gibs then.
I have to say that I initially added mutated people to the gibbing one aswell, but noticed that if you get a breakdown it could fuck you aswell plus heterocromia is a thing. So no.
So the check is on nonhuman species & some funny carbons.
This count as my fix n19
It was funny for players, it wasn't funny for jannie.
And this count as a bugfix.
:cl: HerBaon
balance: Only glorious humans can be part of NT. Everyone else gets gibbed or isn't worthy anymore.
/:cl:
> Lesser Forms can't be cruciformed anymore.

- code/datums/sound_player.dm
- code/game/machinery/adv_med.dm
- code/game/objects/effects/decals/contraband.dm
- code/game/verbs/who.dm
- code/modules/mob/living/say.dm
This PR clarifies some code that was making warnings, applying parenthesis to sound_player.dm, contraband.dm, who.dm, and say.dm along with one change from a binary and to a logic and in adv_med.dm, although for some reason both works.
The warnings were getting annoying.
code: fixed the code causing ambiguous code warnings
/:cl:
> clarifies code in four files and fixes one

- code/modules/clothing/suits/jobs.dm
Gives the detective's coat leg protection and 30% against melee, bullet, and laser instead of 20%.
It isn't, this is the epitome of powercreep, sue me and ban me from contributing. 
Real reason is that the detective felt like he should have slightly better protection against body shots and the fact that coats are meant to be stylish. He can still be headshot with ease if he sticks with his basic drip though.
:cl:
balance: Made the detective's coat more protective, and made it offer leg protection.
/:cl:
> Detective buff.

- code/game/machinery/bioprinter_nt.dm
Buffs printing speed of the NT lathe to being equivalent to a tier 2 lathe and the storage of a t3 lathe (360) because they were cucked since the ability to upgrade the lathe was removed with the new building system. 
This takes in account that the lathe can't be upgraded anymore so it's permanently stuck on a very bad level. It still has the efficiency of a normal lathe. 
An actual NT Buff that matters. 
:cl: Herbaon
balance: NT Bioprinter was balanced to have better storage and printing speed. 
/:cl:
> nt bioprinter buff

- code/game/objects/items/weapons/storage/secure.dm
- code/modules/core_implant/cruciform/rituals/priest.dm
- code/modules/materials/material_sheets.dm
- code/modules/projectiles/guns/launcher/syringe_gun.dm
- code/modules/projectiles/guns/mods/research_mods.dm
- code/modules/projectiles/guns/projectile/dartgun.dm
4 small bugfixes. Evan helped me with several doubts / errors regarding the first mentioned bug, by the way.
26. Artist and Kube Oddities turning all-stats oddities by Preacher Blessing Litany.
27. Secure Briefcase being able to be opened by altclick.
28. Borosilicate/Plasma glass being called Platinum glass and incorrect Moebius isotope diffuser description.
29. Dartgun and syringe guns gunpart exploit
less 🐛
:cl: Herbaon
fix: Artist and Kube Oddities turning all-stats oddities by Preacher Blessing Litany.
fix: Secure Briefcase being able to be opened by altclick.
fix: Borosilicate/Plasma glass being called Platinum glass and incorrect Moebius isotope diffuser description.
fix: dartgun and syringe guns gunpart exploit
/:cl:
> Bugfixes 3 small edition

- code/game/objects/items/weapons/grenades/grenade.dm
Removes 1 second timer setting for grenades.
Cook your nades or get a grenade launcher if you want them to explode this fast, or even better, grab two of them and run at the fool.
:cl:
del: Removed one second detonation option from grenades.
/:cl:
> Removes 1 second timer option from grenades.

- code/modules/mob/living/carbon/shock.dm
Increases the amount of pain needed to get negative effects from pain that are not paincrit.
Using old pain effect numbers doesn't make much senses now that pain can scale properly from 0 - 200 and effects went from 10 - 80.
:cl:
balance: negative effects of pain such as chat messages and stuttering take more pain to activate.
/:cl:
> Pain effect threshold increase

- code/modules/mob/living/silicon/ai/malf.dm
Massively increases the malf AI's idle CPU gain from 0.01 to 0.2 and a hacked APC to contribute 0.08 CPU gain per tick, increasing each by a factor of 20.
Predominantly a stop-gap measure to increase the threat the antag represents until a full refactor/replacement is implemented. Taking into account the the sheer number of points it takes to develop T3 abilities, most rounds will end by the time you get them and often require the rest of the playerbase playing dumb to give you the chance. In addition, the CPU upgrade is a complete no-brainer as it is the only hardware chocie that will actually give you the chance to play around with malf abilities - it's still the strongest choice but now it's not the *obvious* choice.
Values open to adjustment.
:cl:
balance: Malfunctioning AIs have …
> Massively increases malf CPU gain

- code/modules/reagents/reagents/drugs.dm
- code/modules/reagents/reagents/medicine.dm
Removes the `* effect_multiplier` from some painkillers that use it, making it consistent with all the other painkillers.
This would cause painkillers that are used in different ways to have different strength (inaprov pills would be stronger than inaprov injections), making it hard for players to do self surgery.
:cl:
balance: All painkillers have consistent strength anyway they consumed/injected.
/:cl:
> Painkiller effect standardization

- code/game/objects/structures/window.dm
- code/modules/reagents/holder.dm
This PR re-adds silicate reinforcing windows, which had the damage reduction removed apparently accidentally three years ago.
https://github.com/discordia-space/CEV-Eris/commit/55d92b204e7595e6b2d1758b2f1775dd5bac7982
This PR also adds touch to the trans_to, which has comments saying it has touch.
Both features appeared to exist prior, but didn't.
fix: reinforcing windows with silicate actually works now, and beaker splashes now apply touch effects.
/:cl:
> re-adds silicate reinforcement

- maps/CEVEris/_CEV_Eris.dmm
Power cables next to Guild's lobby APC were glitched and did not transmit power. I just rearranged the cables in another way and it works now, don't ask me why.
New layout in green, with old layout in blue.
Fix power issue
:cl: Hyperio
fix: Fix glitched power cables in guild lobby
/:cl:
> Fix power issue with guild lobby APC

- code/modules/mob/mob_grab.dm
- code/modules/mob/mob_grab_specials.dm
This PR changes the headbut proc's name to headbutt and makes it check for the victim wearing armor rather than the grab having an armor datum.
typo bad, bug bad.
> fixes headbut typo and makes armor check work

- cev_eris.dme
- code/controllers/subsystems/processing/fluids.dm
Removes a redundant subsystem I missed when removing plumbing
It doesn't even do anything, why is it here?
:cl:
del: Redundant fluid subsystem
/:cl:
> Removes fluid subsystem

- cev_eris.dme
- code/datums/objective/steal.dm
- code/game/machinery/portable_turret.dm
- code/game/machinery/recharger.dm
- code/game/objects/items/weapons/storage/pouches.dm
- code/modules/projectiles/guns/energy/laser.dm
- code/modules/projectiles/guns/energy/mindflayer.dm
- code/modules/projectiles/guns/energy/nuclear.dm
- code/modules/projectiles/projectile/beams.dm
- code/modules/projectiles/projectile/special.dm
- code/modules/research/designs/weapon.dm
- code/modules/research/nodes/combat.dm
Reworks the mindflayer, it now works similarly to the psionic laser cannon, though it is a bit weaker. It cannot however be used to complete the mindbreak contract. It can still be found in maintenance, and can now be printed by moebius after obtaining laser research.
AEG is now a one handed, 20 shot pistol with a 2 round burst. It's high ammo capacity is somewhat countered by the fact that it cannot be reloaded.
The captain's laser now has 10 AP and 36 damage per shot.
We don't have many psionic weapons, so I thought it'd be cool to add one. Given the mindflayer currently is just a regular laser that applies the confusion status affect, I thought it'd be a good idea to rework it.
Captain's laser quite frankly currently feels like a sidegrade to the spider rose, since it cannot be …
> Reworks the mindflayer, AEG, and Captain's laser.

- code/modules/reagents/recipes.dm
Fixed the issue of mead and ethanol having the same recipe.
Oversights are bad.
:cl:
tweak: mead now uses honey instead of sugar
/:cl:
> Ethanol and mead no longer share same recipe

- cev_eris.dme
Map is temporarily removed for improvements
There's a dozen sleepers and only four spacesuits to get to the teleporter. So we either get four more raiders to handle every round or a bunch of people locked in a room with nothing to do
:cl:
del: Removed prison hulk
/:cl:
> Removes Prison Hulk

- code/datums/perks/oddity.dm
- code/game/objects/items/oddities.dm
makes it so hiveborn perk doesnt show up on normal odditties
speshul snowflake perk only for hive oddity
proof that i somehow didnt fuck shit up and it still shows up on the normal one
:cl:
fix: fixed hiveborn perk showing up on non-hivecore oddities
/:cl:
> no more hiveborn oddities

- code/game/objects/items/devices/von-krabin.dm
makes the stat increase of the von krabin thing be 15 instead of 5
~~its not~~
von krabin felt underwhelming ever since it was introduced, hopefully this makes it see a bit more use in science instead of collecting dust
:cl:
tweak: tweaked Von-Krabin Stimulator stat increase to 15 (from 5)
/:cl:
> Da crab increase

- code/game/objects/items/weapons/design_disks/NeoTheology.dm
Removes "NeoTheology - Blank" from EOTP rotation. Parent of NT discs was made into medkit disk, and blank ~~now /nt_blank~~ is gone forever.
This PR is tested out, NT disks work as intended, with no design lists or resource cost altered.
https://github.com/discordia-space/CEV-Eris/issues/6281
Fixes cool.
:cl:
fix: empty disk no longer appearing in EOTP
/:cl:
> Blank no more

- code/modules/mob/living/simple_animal/friendly/iriska.dm
So I woke up just now, checked discord and see that Iriska curse not working. Apparently, when removing mob reference lists from Iriska code right before merge - I forgot to adjust destroy_lifes() proc to new lists, but now it's fixed.
Fixes cool.
:cl:
fix: Iriska curse
/:cl:
> Itsy bitsy fix

- code/_onclick/hud/screen_objects/base_screen_objects.dm
this PR fixes a division by zero runtime that happened when max sanity was zero, sanity hud now always shows the breakdown overlay when max sanity is zero.
Runtime Bad.
fix: fixed division by zero runtime in sanity HUD
/:cl:
> fixes a division by zero runtime in sanity HUD

- code/modules/reagents/enricher.dm
makes the enricher reject virus food
also fixes a word(?) mistake
roundstart (there is a dispenser in virology) easy rescuitator might not be the best of ideas frankly
also english is better than engrish
:cl:
tweak: enricher rejects virus food
/:cl:
> Virus Food Nerf: Remastered

- code/game/machinery/excelsior/ex_teleporter.dm
- code/modules/hydroponics/spreading/spreading.dm
- code/modules/overmap/ships/ship.dm
This PR removes three division by zero runtimes,one in ex_teleporter.dm RefreshParts(), one in spreading.dm refresh_icon(), and one in ship.dm get_brake_path()
runtime bad
fix: fixed three division by zero runtimes from excel tele, piloting the ship, and spreading plants
/:cl:
> removes three division by zero runtimes

- code/modules/projectiles/projectile.dm
Bullets can now miss depending on the body part they hit:
Head - 45%
Upper body  - 10%
Everything else - 20%
Modified by VIG (30 VIG, 30% less chance to miss)
With new aiming players would be very accurate and focus the head, leading to most gun fights ending before paincrit with a missing head, increasing the overall lethality of combat. Now the only way to get that kind of precision is at point blank range with 100 VIG.
Test with 15 VIG at point blank range:
:cl:
balance: projectiles have a chance to miss depending on the limb they are going for.
/:cl:
> Re-adds ranged miss chance

- code/game/objects/items/weapons/teleportation.dm
This PR removes the outdated check in hand tele that would cause it to fail to function if the zlevel was exactly two, and leaves the no location/zlevel greater than equal to 7 part of the check intact.
zlevel 2 now resolves to part of the ship and shouldn't disable it.
del: fix: hand teles no longer malfunction on zlevel 2
/:cl:
> removes outdated zlevel==2 check in hand tele

- code/modules/multiz/turf.dm
This PR makes it so that when something falls on someone, the falling thing's damage is applied through armor, instead of directly as was previously done.
armor should armor
fix: armor now works against things falling on you
/:cl:
> makes armor work against things falling on you

- code/game/objects/items/weapons/tools/_tools.dm
- nano/templates/tool_stats.tmpl
This PR makes the tooltip of tools include the Armor Penetration value, currently stated as a flat number.
Players should know the AP of the the melee weapons they're using.
add: tool tooltips now include the armor penetration value.
/:cl:
> adds AP to tool tooltip

- maps/CEVEris/_CEV_Eris.dmm
Changed ID's on buttons in engine room. Now "vent" button opens/closes ventilation blast door, while "eject" button triggers mass drivers.
Fixes cool.
:cl:
fix: vent button in supermatter room
/:cl:
> [MAP] Engine vent button fix

- code/modules/mob/living/silicon/robot/gripper.dm
- code/modules/reagents/machinery/grinder.dm
Added /meat to chemistry gripper list and allowed synthetics to interact with the grinder.
Fixes cool.
:cl:
fix: chemistry gripper not accepting meat
/:cl:
> Meat grinding for synths fix

- code/modules/dungeons/junk_tractor_beam.dm
If people were teleported outside the JTB border because of a teleportation incident, they were unable to get out of there without admin intervention. Now they can just walk toward the edge and they will be teleported back inside.
:cl: Hyperio
fix: Fix being unable to get back in JTB area
/:cl:
> [JTB] Fix people being unable to get back in

- maps/submaps/junk_field/j25_25/ironhammer/ironhammer1.dmm
- maps/submaps/junk_field/j25_25/ironhammer/ironhammer2.dmm
- maps/submaps/junk_field/j25_25/ironhammer/ironhammer3.dmm
- maps/submaps/junk_field/j25_25/serbian/serbian1.dmm
- maps/submaps/junk_field/j25_25/serbian/serbian2.dmm
- maps/submaps/junk_field/j25_25/serbian/serbian3.dmm
Reduce the quality of loot in some JTB 25 x 25 chunks to avoid people rushing there for gamer loot (good guns, pouches, gear)
Less gamer loot.
:cl: Hyperio
balance: Reduce quality of loot in JTB chunks
/:cl:
> [JTB] Rebalance loot

- code/modules/projectiles/ammunition/boxes.dm
title
Ammo in the box takes up almost two times as much space, than same ammo without the box.
Not to mention that shotgun need ammo to be handfed inside, and interacting with that ammo box is more pain than with regular box.
In other words, this box is very very bad as it is now, and you should take ammo out and trash the box to save space.
:cl:
tweak: tweaked shotgun box size
/:cl:
> changes shotgun shell box size

- code/datums/autolathe/guns.dm
- code/game/objects/items/weapons/design_disks/NeoTheology.dm
- code/game/objects/items/weapons/design_disks/autolathe_disks.dm
- code/modules/projectiles/guns/projectile/sniper.dm
Design disc states one name, but printed gun spawns with different one. Not anymore.
Fixes cool.
:cl:
fix: NT-branded AMR having wrong name
/:cl:
> NT-branded AMR fix

- code/game/objects/items/weapons/RCD.dm
Not even that good at coding so whatever
Fixed a little bug that allowed RCD to build low walls and airlocks inside other walls by clicking on them, and that doesnt spend any matter.
Also trying to make RCD's matter consumption a little more fair to the hand version since it's extremely unfun and feels unfair to use even in extreme situations. Tested how it affects borgs and rigs, the only problem might be the borgs since they can afford their cell charge to lose some energy and it might not even be that expensive for them but they are controlled by laws anyway, **so what could go wrong?**
In it's current state all RCDs that humans use are left to dust on the shelf and it feels very punishing to use it since building cost is very high and making new cartriges feels like getting scammed …
> RCD's bug fix and some balancing

- code/game/machinery/jukebox.dm
- code/game/objects/items/boombox.dm
- code/game/objects/items/musictapes.dm
- code/modules/media/media_tracks.dm
- code/modules/mob/living/carbon/superior_animal/roach/roach.dm
Adds playlist autogeneration for music tapes, a lot of them added to our internal config file. GLOBalizes juke lists for easier tracking. Roaches have a chance to spit up a tape on death.
Uplifting musique. Lore justifications on as to why roaches have the tapes in the first place - you know how nintendo coated cartridges for Switch with a really bitter tasting liquid that was intended to make toddles reluctant to swallow them? And then everyone FUCKING EVERYONE started licking those stupid cartridges and posting it online? Yeah, they are coated in the same stuff, but roaches like it for some fucking reason.
:cl:
add: Many more tapes and a way to get them from roaches.
/:cl:
> Adds a lot of music tapes

- code/modules/mob/living/carbon/superior_animal/defense.dm
- code/modules/mob/living/simple_animal/simple_animal.dm
- code/modules/organs/organ.dm
This PR makes it so that all uses of the death proc don't call it if they're already dead.
Infinite Tapes Bad.
fix: roaches no longer die over and over again while dead.
/:cl:
> fixes things calling death proc while dead

- code/_compile_options.dm
Because you should able to compile things and just know that better to compile with another version.
:cl:
code: Compiling not failing if you have to old version of byond, now it will just warn you about this.
/:cl:
> Do not fail compile just because of version of byond

- code/modules/organs/internal/eyes.dm
Removes the check for inorganic eyes for changing the colour matrix
The Oborin syndrome provides a ton of buffs in exchange for colorblindness, thus this exploit allows the player to bypass this drawback as easily as choosing a different option in character selection, which is bad. Moreover, lore-wise, Oborin is a "psionic" condition, so it doesn't make much sense that changing out the eyes would just remedy it.
:cl:
balance: prevents inorganic eyes from removing the colorblindness effect of Oborin
/:cl:
> Makes Oborin colorblindness no longer bypassable through the usage of prosthetic eyes

- code/game/gamemodes/storyteller_meta.dm
Fixes the storyteller , and finnaly gets rid of skin.dmf fuckery
Its not , self antag eris ancapistan is better.
Exactly the same code as https://github.com/discordia-space/CEV-Eris/pull/6487
:cl:
fix: The storyteller refusing to storytell
/:cl:
> Fixes the storyteller (now without skin.dmf)

- code/modules/clothing/accessories/holster.dm
- code/modules/mob/living/carbon/human/inventory.dm
Fixes Holstered weapons with the automatic firemode breaking when unholstered
Also likely fixes a lot of bugs caused by put in active hand lacking the swapped_to proccall
Credit to Bruh Momentium / Roma for giving me a very reliable test case to replicate the issue with
Full auto blasting
:cl:
fix: Fixed holstered weapons with the auto-firemode breaking upon being unholstered
/:cl:
> Fixes holstered weapons having their click-handlers deleted when pulled out

- code/game/area/areas.dm
This PR fixes the issue where a mob would be standing on an open space if gravity is re-enabled. Instead, he would fall through as normal.
This issue doesn't make much sense in the game world and ruins immersion. My fix serves to remedy that.
:cl:
fix: enables falling through an open space after a change in gravity
/:cl:
> Enables a mob falling through an open space when gravity changes

- code/game/objects/random/packs.dm
- code/game/objects/structures/crates_lockers/closets/maint_loot.dm
This PR replaces the two gun loot spawners in roachless forgotten closets with three copies of a new spawner, gun_adjacent_loot.
The gun_adjacent_loot spawner has mostly gun parts, with a chance for a knife, ammo, a gun upgrade, or a holster.
Gun Parts are supposed to be used to make guns, but when the main source of them is destroying guns, it's hard to justify doing so. This PR makes gun parts more available.
balance: roachless forgotten closets now contain gun parts instead of guns.
/:cl:
> replaces guns in roachless forgotten closets with gun parts

- cev_eris.dme
- code/datums/components/clothing_sanity_protection.dm
- code/game/objects/items.dm
- code/game/objects/items/_inventory.dm
- code/modules/clothing/masks/balaclava.dm
- code/modules/clothing/masks/gasmask.dm
- code/modules/clothing/masks/miscellaneous.dm
- code/modules/tips_and_tricks/gameplay.dm
Makes balaclavas provide 60% more protection from environmental sanity damage.
Adds a component for this behaviour that can be added to any item
(Important note , this uses a multiplier , not added on directly , if you have a perk that sets your environment coeff to 0 , it won't help you at all)
Also im a dumbass and i fixed the clothing dropped signals,  because i forgot a case in which the item gets moved to another slot.
Players should be incentivized to wear something other than ciggaretes , vape masks , or drink chemicals every 10 minutes in order to preserve their sanity.
Also its badass to be more mentally tough if you wear a balaclava.
:cl:
add: Added the sanity_damage_reduction component for clothing
add: Made balaclavas and any subtype of gasmasks reduce sanity damage fron …
> Adds the sanity damage reduction component for clothing , adds it to balaclavas

- code/ZAS/Turf.dm
- code/modules/overmap/exoplanets/exoplanet.dm
- code/modules/overmap/exoplanets/planet_types/chlorine.dm
- code/modules/xgm/xgm_gas_mixture.dm
- maps/submaps/planetary_ruins/datacapsule/datacapsule.dm
- nano/templates/pda.tmpl
Remove phoron reference, fix unprocessing atmos icons
Allows you to see orange and sleeping gas
:cl:
del: Rename phoron reference
fix: Allows you to see orange and sleeping gas
/:cl:
> fix atmos icons & rename phoron

- code/game/objects/effects/spawners/gibspawner.dm
Reduces the gibs per roach from 5 to 3
Less stacking decals and less processing for sanity datums , also , 5 is overkill for slaughtering 1 roach.
:cl:
tweak: Gibbing roaches now makes 3 splatters instead of 5.
/:cl:
> Reduces gibs per roach from 5 to 3

- code/datums/components/clothing_sanity_protection.dm
- code/modules/clothing/accessories/holster.dm
Fixes clothing_sanity runtiming on destroying , fixes holsters deleting weapons
Fix
:cl:
fix: Clothing sanity component from  improperly destroying
fix: Holsters deleting guns when pulled out into a occupied hand
/:cl:
> Hotfix for clothing_sanity and holsters

- code/datums/datum_click_handlers.dm
- code/modules/projectiles/gun.dm
Fixes the exploit allowing people to fire faster by just smashing click.
Also fixes gun firing datum not updating its firerate when the gun gets upgraded
1 Exploit less, and powergamers can and will cope.
:cl:
fix : Fixed auto guns firing faster by just click smashing.
fix: Fixed guns receiving a super slow firerate on their enabled firemode  when upgraded
/:cl:
> Fixes exploit allowing people to spam-click to fire auto-guns faster

- code/modules/trade/datums/trade_stations_presets/zarya.dm
Adds CO2 canister to guild trading beacon.
All 3 basic gasses should be replenishable in case they run out.
:cl:
add: Adds CO2 canister to guild's trading beacon.
:cl:
> Adds CO2 canister to guild trading beacon

- code/game/machinery/doors/airlock.dm
- code/game/machinery/doors/airlock_control.dm
- code/game/machinery/doors/door.dm
Removes all doors from processing , cutting down around 1500~ machinery from 10000 machinery processing roundstart
Very likely will break in edge cases i can't test or even think of
Holy fuck why do we still process every fucking door this is 2021
:cl:
fix: Fixed doors processing
/:cl:
> (Needs testing) Makes all doors not process

- code/__HELPERS/global_lists.dm
- code/datums/objective/individual_objective/command.dm
- code/global.dm
- code/modules/long_range_scanner/long_range_scanner.dm
- code/modules/overmap/events/movable.dm
- code/modules/overmap/sectors.dm
- code/modules/overmap/ships/ship.dm
- code/modules/shield_generators/shield_generator.dm
- maps/CEVEris/overmap-eris.dm
del_event function was searching `in world` instead of using the global list that contains all existing ships.
Minor tweak of how Eris is stored in that list because that `ships[eris]` with eris a global class variable made little sense to me.
Optimization
:cl: Hyperio
refactor: Refactor del_event function and global list for ships
/:cl:
> Avoid search in world for del_event

- code/modules/projectiles/gun.dm
Makes pistols no longer runtime on init
Is it ?
:cl:
fix: Pistols runtiming on refresh_upgrades() due to having no firemodes.
/:cl:
> Fixes a roundstart runtime

- code/modules/projectiles/guns/projectile/pistol/olivaw.dm
Olivaw had to high recoil for whats it worth in battle.
Players complained about its recoil problem and it was generally underwhelming.
:cl:
balance: Olivaw recoil have been lowered from 3.5 to 2.
:cl:
> Lower olivaw recoil

- code/game/objects/effects/spawners/ghostspawner.dm
Fixes cancel button not working on becoming prisoner pop up.
Bugs bad.
:cl:
fix: Canceling Scrapyard pop up in case you clicked on its pod works now
:cl:
> Scrapyard pop up fix

- code/datums/uplink/uplink_sources.dm
Changes the uplink unit(station bounced uplink thingy) starting TC from +80% to +20%.
Documentation(https://docs.google.com/document/d/1FeYkH2MXWMUCK45zPyepfPL6ub8RNr_DYqQ7fb1qlCs/edit) was changed so this is being changed to what its meant to be.
:cl:
tweak: tweaked the amount of TC the particular uplink unit option gives to additional 20 instead of 80%
:cl:
> Makes uplink unit have starting TC inline with current design documentation

- code/game/machinery/doors/airlock.dm
- code/game/machinery/doors/door.dm
makes doors keep trying to close
It is not
:cl:
fix: The technomancer exultant has given a very angry complaint to Hansa after their last shipment of airlock circuits were malfunctioning , the issue has been remedied and all doors now close as expected.
/:cl:
> Fixes doors not always closing

- code/game/machinery/biogenerator.dm
- code/game/objects/effects/roaches.dm
- code/modules/reagents/reagent_containers/food/snacks.dm
- code/modules/reagents/reagent_containers/food/snacks/meat.dm
Roach eggs contain eggyolk and blattedin.
Removed the code for making cutlets, replaced with the pizza code instead, allowing chems from cutlets to be transferred into foods you cook from them. Now the only way to make blattedin-free food from roaches is to make meatballs.
Biogenerator can now print boxes of eggs.
Removes some exploits, gives more power to vagabonds doing ghetto cooking.
:cl:
fix: Replaced broken cutlet cutting code with sliceable code
tweak: Biogenerator can print egg boxes
tweak: Roach eggs contain 9 units of eggyolk and 3 units of blattedin
/:cl:
> Some love for the Kitchen

- code/modules/mob/living/carbon/human/human.dm
Explosions no longer forcefully paralyse people , we got the pain to handle it now
We got pain to handle this now , no need to force paralyse people anymore
:cl:
balance: Explosions no longer forcefully paralyze
/:cl:
> Explosions no longer force paralyse people

- code/game/objects/items/devices/radio/radio.dm
- code/modules/mob/living/carbon/human/human.dm
Fixes people being able to stack a oddity on the random wave
Less bugs
:cl:
fix: Fixed random wave radio letting you stack the same oddity
/:cl:
> Fixes random wave radio oddity stacking

- code/game/objects/items/devices/techno_tribalism.dm
Gives cube a cooldown thats more in line with its power.
People were complaining about only being able to use the cube a few times per round, less then they had hoped to.
:cl:
tweak: cube cooldown is now 20 instead of 30 minutes
:cl:
> Reduces Techno-Tribalism Enforcer(cube) cooldown to something more manageable

- code/datums/craft/recipes/guns.dm
In title
Why does each and every ammo kit need its own wirecutter? What happens to it once you use it up? Why is this a thing?
:cl:
tweak: tweaked a ammo crafting kit's recipe
:cl:
> Ammo crafting kit no longer consumes wirecutters

- code/game/objects/items/weapons/sword_of_truth.dm
- code/modules/mob/living/living_defense.dm
Sanctifier tool mod now burns carrions, as intended.
Sanctifier tool mod added to Sword of Truth.
Intended effect failed to hit the mark, best help it reach it's target.
If even the lowliest NT weapon comes with a sanctifier pre-installed, why not the Sword of Truth?
:cl:
tweak: Sanctifier added to Sword of Truth
fix: Sanctifier works against Carrions
/:cl:
> Sanctifier fix

- code/modules/materials/material_sheets.dm
Increases the maximum amount a biomatter stack can hold from 60 to 120
In a revolutionary breakthrough, through the divine guidance of the Angels, a research team employed at His Divine Grace's Applied Thaumaturgy Laboratory has successfully synthesized a novel form of biomatter showing 200% stability compared to the standard. The potential applications of this novel material will surely be wide-reaching.
Biomatter is the only stackable material that maxes at a value other than 120, with no clear reason for this. 
:cl:
tweak: Biomatter max_amount changed from 60 to 120
/:cl:
> Biomatter sheets now stack at 120

- code/datums/craft/recipes/tools.dm
Tweaks recipe for arguably one of the most useful toolmods out there to still be mildly time consuming to craft but without requiring welder pack, which iirc can't be even printed or anything, and hardly ahs place in game regardless.
Crafting good, crafting using rare nd useless legacy items bad, simple as!
:cl:
tweak:Expanded fuel tank recipe
/:cl:
> Makes Expanded fuel tank mod actually attainable to common folk

- code/modules/mob/living/carbon/human/human.dm
Medspec is the only IH with no job prefix, for no particular reason.
:cl:
add: "specialist" prefix for medspec
/:cl:
> Prefix for medspec

- code/__DEFINES/misc.dm
- code/__DEFINES/mob_stats.dm
- code/__HELPERS/mobs.dm
- code/datums/mob_stats.dm
- code/datums/perks/job.dm
- code/datums/perks/perk.dm
- code/game/atoms.dm
- code/game/jobs/job/medical.dm
- code/game/turfs/flooring/flooring.dm
- code/modules/clothing/glasses/science.dm
- code/modules/mob/living/carbon/human/human.dm
- code/modules/mob/living/carbon/human/human_helpers.dm
- code/modules/mob/living/living.dm
Trip chance is now at base 50%
Cognition reduces chance to trip
Tripping is no longer prevented by slip-preventing items such as magboots
You now need scanning googles , 35 cognition or 50 biological to recognise reagents in drinks
Adds functionality for abilities that are shared between more perks with bitflags
Forces everyone on plating to play on even ground , makes cognition count more 
Lets people actually poison drinks , which can deal to interesting plots
:cl:
balance: Seeing reagents inside beakers now requires scanning goggles , 35 cognition or 50 biology
balance: Tripping can no longer be prevented by anything slip-preventing
balance: Trip chance is now 50% , and gets lowered by cognition stat
code: Added bitflag handling for perks that share a common ability
balance: Buffed …
> Cognition now influences chance to trip,Cognition/Biological is required to see reagents inside a container, Chemist buff

- cev_eris.dme
- code/datums/autolathe/autolathe_datums.dm
- code/game/machinery/autolathe/autolathe.dm
- code/game/machinery/autolathe/nanoforge.dm
- code/game/objects/items/weapons/tools/mods/mod_types.dm
- code/modules/projectiles/guns/mods/mods.dm
- code/modules/scrap/extra_quality.dm
The auto-nanoforge now adds a positive gunmod / toolmod or increases the capacity of batteries printed
matter nanoforge is now 40% more efficient on materials
matter nanoforge now prints at double speed
matter nanoforge now stores twice as many materials
matter nanoforge can no longer be upgraded
It sucks , now it should be preety good to be forced to not get a oddity perk
:cl:
balance : Weapons / Tools printed using the nano autoforge now receive a buff attachmnt
balance: Automatter nanoforge is now 40% more efficient on materials and prints twice as fast, and stores twice as much.
balance : Automatter nanoforge can no longer be upgraded.
/:cl:
> Buffs technomancer auto-nanoforge , adds positive gunmods / toolmods.

- code/modules/mob/living/carbon/human/human_movement.dm
- code/modules/mob/living/carbon/shock.dm
Reduces pain gained from limb damage by 10%
Reduces pain from oxyloss by 40%
Pain slowdown is now based on (halloss * 1.33 ) / 25 , instead of shock_stage / 100 
People get far too much slowdown from a few shots.
:cl:
balance: Reduced overall agony from limb damage by 10%
balance : Reduced overall agony from oxyloss by 40%
balance : Pain induced slowdown is now linear and based on dynamic pain instead of shock stage
/:cl:
> Reduces overall pain by 10% , reduces oxyloss pain by 40%, pain slowdown is now linear instead of stage-based.

- code/game/jobs/job/silicon.dm
- code/modules/mob/living/silicon/ai/ai.dm
- code/modules/mob/living/silicon/robot/drone/_drone.dm
- code/modules/mob/living/silicon/robot/drone/drone_manufacturer.dm
- code/modules/mob/new_player/new_player.dm
Malf AI roll by storyteller was broken when an AI used its remote controlled drone or when it was joining after roundstart due to some issues with the subsystem that handle player minds.
:cl: Hyperio
fix: Fix Malf AI Roll when using AI drone or joining after roundstart
/:cl:
> Fix Malf AI Roll when using AI drone or joining after roundstart

- code/__HELPERS/unsorted.dm
- code/modules/projectiles/projectile/bullets.dm
- code/modules/projectiles/projectile/bullettypes.dm
Buckshot knockback is now more sane , and is limited to 5 turfs at most with a improved algorithm which is far more accurate in determing where to throw the target
No more buckshot yeeeeeet half of the ship 
:cl:
fix: Crazy buckshot knockback
balance : Maximum distance a buckshot can fling you now is 5 tiles.
/:cl:
>  makes buckshot knockback less crazy.

- code/game/machinery/doors/firedoor.dm
What it says on the tin. ~It's still logged, but no admin messages pop up.~
Admeme asked for this.
:cl:
admin: admins no longer messaged about firedoors being opened
/:cl:
> Remove admin warnings from opening firedoors

- code/game/objects/items/weapons/grenades/emgrenade.dm
Fixes low yield EMP grenades having the same effects as normal ones
Le buy 30 low yield emp grenades , le not spend TC for proper ones.
:cl:
fix: Fixed Low Yield Emp Grenades having the same effects as a normal one.
/:cl:
> Fixes low yield EMP grenades being as effective as normal ones

- code/modules/organs/internal/internal_organ_processes.dm
- code/modules/reagents/reagents.dm
Ingested metabolization now works based off  ( stomach_eff + liver_eff + heart_eff ) / 300
Bloodstream metabolization now works based off (liver_Eff + heart_eff * 2) / 300
I put 3 hearts in me why don't i process shit faster >:(((
:cl:
add: Ingested reagents metabolization now scales off your stomach , liver and heart efficiency combined.
add: Bloodstream reagents metabolizatio now scales off your liver_eff  and heart efficiency
/:cl:
> Erismed 3.1 , adds scaling metabolization based off liver , stomach and heart efficiency

- code/game/machinery/portable_turret.dm
- code/modules/hivemind/machines.dm
- code/modules/mob/living/simple_animal/simple_animal.dm
Remember when you shot a turret or hivemind's mob or machine with ion beam and zero fuck was given? Well, no more.
Don't have to target walls anymore.
Fixes cool.
:cl:
fix: EMP projectile not creating EMP when hit a turret, hivemind structure or simple_mob
/:cl:
> Fix EMP projectile not working sometimes

- code/datums/craft/step.dm
Crafting Embedded SMG with a Slaught-o-Matic no longer break player's hands. Hopefully.
Fixes cool.
:cl:
fix: phantom gun after crafting embedded SMG
/:cl:
> Fix phantom gun after crafting

- code/__HELPERS/unsorted.dm
- code/game/objects/explosion.dm
- code/modules/projectiles/projectile/bullettypes.dm
Fixes breacher ammo being broken and lagging the server to a halt
Fixes a oopsie in get_target_complex that would cause it bogus results
Makes breacher ammo send shrapnel only on the other side of where it penetrates ( behaviour similar to a tank getting penetrated by a anti-tank shell and shrapnel being thrown on the inside)
Breacher rounds are kinda cool , wallbanging people with deadly shrapnel couldn't ever be more balanced!
:cl:
fix:Breacher rounds now work properly and don't lag the server to death
fix:Coding fuckup in get_turf_away_from_target_complex
/:cl:
> Fixes breacher ammo , makes it be angled the other way from where it was fired , fixes a oopsie in get_target_away_complex

- code/datums/outfits/jobs/security.dm
- code/game/objects/structures/crates_lockers/closets/secure/security.dm
- code/modules/clothing/glasses/hud.dm
Replace Medical specialist standard medical belt by an emergency response team belt so that they can store more rescue stuff on them (such as crowbar).
Create a medical HUD with flash protection. Replace the sec HUD in Medspec lockers by one of those.
Makes Medical Specialists' life easier.
:cl: Hyperio
add: Added new IH medical HUD
balance: Medspec now spawns with an ERT medical belt
/:cl:
> IH medical HUD + EMT belt for medspec

- code/ATMOSPHERICS/components/binary_devices/pump.dm
- code/modules/power/smes.dm
Gas pumps can now be toggled on and off by alt clicking
Gas pump pressure can be maxed by ctrl clicking
SMES input can be maxed/ zeroed by alt clicking
SMES output can be maxed / zeroed by crtl clicking
SM Setup speedrun
:cl:
add: You can now toggle pumps on and off by alt clicking , and their pressure to max by ctrl clicking
add:You can now max SMES input / output or zero it by alt / ctrl clicking
/:cl:
> Misc technomancer QoL

- cev_eris.dme
- code/__DEFINES/misc.dm
- code/datums/datum_hud.dm
- code/game/machinery/surveillance_pod.dm
- code/modules/clothing/head/armor.dm
- code/modules/clothing/masks/miscellaneous.dm
- code/modules/clothing/under/miscellaneous.dm
- code/modules/mob/living/silicon/ai/ai_HUDs.dm
- code/modules/multiz/movement.dm
- maps/CEVEris/_CEV_Eris.dmm
- maps/submaps/deepmaint_rooms/core/ai_core.dmm
Added a surveillance pod, stationary version of old "camera MIU" mask used by Bay12's ninja antagonist.
Mask have been spawning in trash until now.
Pods have same functionality as "camera MIU", minus constant runtimes and plus UI buttons.
To use it, player should have empty suit slot, internals, special jumpsuit and headgear.
Compatible headgear:
Type-34C (cyberpunkish helmet from loadout)
Type-34 (same helmet with armor stats slightly lower than on operator's helmet. Two of those found in the armory.)
Compatible jumpsuits:
Augmented jumpsuit (from loadout)
Cybersuit ("new" jumpsuit with sprite of black HoS uniform. Two of those found in the armory.)
<details>
<summary>
Screenshots
</summary>
</details>
Cool feature.
:cl:
add: armored version of type-34 helmet
add: surveillance pods, …
> Surveillance pods

- code/modules/projectiles/ammunition/boxes.dm
Corrects .20 ammo packet description.
Misinformation bad.
:cl:
spellcheck: fixed .20 ammo packet description
:cl:
> Fixes .20 ammo packet description

- code/modules/projectiles/guns/projectile/battle_rifle/boltgun.dm
Previous bolt action PR did not take muscle memory into account. The new method was reverted.
Recoil was significantly increased on the bolt actions, but fire delay was reduced. Still fires slower than a semi-auto, of course.
Muscle memory
:cl:
tweak: reverted bolt action change
balance: bolt action recoil increased
/:cl:
> Bolt action revert

- code/game/machinery/excelsior/ex_turret.dm
Makes excelsior turret shoot in bursts of 8 bullets, wildly inaccurate at that.
Still an easy kill, if not rushing in melee, but that's something at least.
Demonstration:
https://www.youtube.com/watch?v=cv0WPZXzpgE
UPD: Turret direction no longer lags behind and updates before each shoot instead of before each burst.
<details>
<summary>
Suggestions
</summary>
</details>
Considering how expensive that turret is to make (requires Maxim LMG), performance of it is laughable.
:cl:
balance: excelsior turret shoot in bursts of 8
/:cl:
> Buff excel turret

- code/modules/admin/secrets/admin_secrets/move_shuttle.dm
Asked by Gray. Fix the Move shuttle verb in Secret panel, you can now force move shuttle from one landmark to another as long as the destination landmark is compatible, like you cannot move Hulk to a pod landmark.
Debugging of stuck shuttles should now be possible.
:cl: Hyperio
fix: Fixed Move Shuttle verb in Secret panel
/:cl:
> Fix Move Shuttle verb in Secret panel

- code/modules/mob/observer/ghost/ghost.dm
adds the follow verb in context menu(right mouse button menu thingy(only for ghosts))
comfy QoL
:cl:
add: now possible to use Follow verb via context menu
/:cl:
> Add Follow verb in context menu

- code/modules/projectiles/ammunition/boxes.dm
made .35 ammo packet contain 70 bullets instead of 30, so now you can fill two smg mags (previously you couldn't fill any).
every other ammo packet follow the same logic, i.e. .30 packet has 60 ammo (two AK mags), and so.
:cl:
tweak: .35 ammo packets now contain 70 bullets
/:cl:
> more ammo in .35 packet

- code/modules/surgery/organic.dm
Fixes standing shrapnel removal surgery, preventing it from gibbing your head if you succeed at low Bio
Help succeeding at the surgery gibbed my head
:cl:
fix: Shrapnel removal damage no longer scales with bio
balance: Shrapnel removal surgery now guaranteed to remove the shrapnel even when failed, but will deal increased damage
/:cl:
> Fixes shrapnel removal

- code/modules/reagents/machinery/centrifuge.dm
- code/modules/reagents/machinery/electrolyzer.dm
- code/modules/reagents/machinery/grinder.dm
Add ghetto chem tools to the junktool spawning pool
now you can actually find ghetto tools in ghetto rooms
:cl:
tweak: you can find ghetto chem tools in maintenance now
/:cl:
> Ghetto chem tools spawn in maint

- code/modules/projectiles/guns/projectile/pistol/colt.dm
- code/modules/projectiles/guns/projectile/pistol/giskard.dm
- code/modules/projectiles/guns/projectile/pistol/handmade.dm
- code/modules/projectiles/guns/projectile/pistol/mandella.dm
- code/modules/projectiles/guns/projectile/pistol/mk58.dm
- code/modules/projectiles/guns/projectile/pistol/olivaw.dm
- code/modules/projectiles/guns/projectile/pistol/paco.dm
- code/modules/projectiles/guns/projectile/pistol/selfload.dm
Most pistols are reduced to 5 vigilance and 0.1 second
Should only have a delay if you're negative on vigilance
:cl:
balance: Most pistols now have their wield delay lowered and wield factor halved.
/:cl:
> Lowers pistol wield delay and wield factor in general

- code/modules/organs/external/_external.dm
- code/modules/surgery/organic_damage.dm
Adds two buttons to the surgery menu: Treat damage to tissue and salve burns. Requires the respected advanced kits, takes a long time, has an increased chance to fail. Heals 25 damage.
The year is 2577, we can convince our immunity system to not reject chunks of steel glued to our flesh, while also being able to fix(heal) the prosthetics on the go, but can't heal the flesh itself? dislike and unsub
/////
no more waiting for tricord to make the bone mendable. I decided to make this instead of just removing the damage threshold.
:cl:
add: It's now possible to heal limbs directly via surgery.
/:cl:
> Heal limbs directly

- code/game/machinery/doors/door.dm
Doors that have their panel open can now be opened 
People abuse this to instantly lock doors in a chase instantly, very dumb gameplay overall
:cl:
balance: Doors with their maintenance panel can now be opened.
/:cl:
> Doors with their panel screwed open can be opened

- code/datums/mind.dm
- code/modules/client/preference_setup/global/preferences.dm
- code/modules/mob/living/silicon/robot/login.dm
- code/modules/mob/login.dm
What it says on the tin. If new preference is set to "Yes", on login or mob change (spawning, ghosting, detaching as a spider core, being borged, etc.) player will have hotkey mode enabled, instead of if being reset.
QoL feature.
Prevents situations where player can't move precisely at a time they have to. Like when spider core / borer detaching.
:cl:
add: preference for keeping hotkeys always on
/:cl:
> Add preference for keeping hotkeys always on

- code/game/objects/items/weapons/power_cells.dm
- code/modules/mechs/_mech_defines.dm
- code/modules/mechs/equipment/combat.dm
- code/modules/mechs/interface/screen_objects.dm
- code/modules/mechs/mech_movement.dm
This fixes exosuits being able to mostly ignore movement disruptions from EMP damage by disabling a mech's strafe if its emp_damage reaches a threshold. 
A few people complained exosuits were able to 'soak up EMPs before running off to repair', this should fix that. It'll still be able to waddle back, but should be far easier to finish off now.
Also, changes the mech's laser gun to fire in 2-round bursts now, this was an intended feature that didn't work, rebalances a few mech parts costs, and makes the mech PK a tad more accurate.
:cl:
balance: fixes mechs running at full speed when EMP'd, changes costs of a few mech guns, reduces the the internal mag for exosuit energy guns
fix: fixes mech's move disruption being functionally useless, makes the immolator fire in bursts
/:cl:
> Fixes exosuits ignoring move disruptions via strafe

- code/game/machinery/crafting_station.dm
Fixes "crafting ctation", now it's properly named to "crafting station".
Typo fix, immersion intact
:cl: Xoxeyos
spellcheck: Fixes "crafting ctation", now it's properly named to "crafting station".
/:cl:
> Fixes a typo in crafting_station.dm

- code/datums/uplink/ammunition.dm
- code/game/objects/items/weapons/storage/uplink_kits.dm
.35 and .40 speedloaders very horribly overpriced compared to other .35 and .40 ammo, this fixes that problem.
Traitors are encouraged not to just buy .35 and .40 ammo from mags and put it in speedloaders and instantly reloading revolvers with that tactic.
:cl:
tweak: both .35 and .40 speedloaders lethal and HV variant now come in a box of 2
tweak: .40 SMG HV cost increased from 4 to 5, .40 HV ammo packet cost increased from 5 to 6
/:cl:
> Speedloaders in uplinks come in a box of 2 also price changes

- code/modules/projectiles/projectile/bullettypes.dm
Now lethal and HV bullet __projectiles__ are named after its caliber.
Made mostly for #6793, can also be a QoL of sorts? For compendium stories?
These two prs aren't really related so I decided to break them into two.
QoL of sorts? For compendium stories?
:cl:
tweak: now lethal and HV bullet projectiles are named after it's caliber.
/:cl:
> Caliber names for bullet projectiles

- code/datums/outfits/jobs/security.dm
- code/game/objects/structures/crates_lockers/closets/secure/security.dm
The flash resistant medical HUD was a new addition to the medspec locker. Problem is that IH operatives keep breaking into the locker to steal them. Now medspecs spawn directly with these on their eyes.
:cl: Hyperio
del: Removed flash resistant medhud from medspec locker
tweak: Medspecs now directly spawn with their flash resistant medhud
/:cl:
> Make medspecs spawn with their flash resistant medhud

- code/modules/mob/living/living_defense.dm
spcr made a salt pr and then closed it without fleshing it out, I decided that the idea is good so I stole his code and tweaked it.
splints fall off after getting more than 20 damage. For scale, wielded untoolmodded crowbar deals 19.5, unwielded untoolmodded butcher cleaver deals 20.
"No longer you can combat pre-splint to avoid a major part of the medical system and balance"
:cl:
balance: splints break and fall off after being hit, 20+ damage to break them.
/:cl:
> Breakable splints

- code/game/objects/items/weapons/cigs_lighters.dm
Changes the charge use from .5 to .2. Turns the basic battery use from 10 units to 25 units per charge. 200 unit batteries will use the whole amount of reagents inside now instead of requiring 500 units of charge to use the whole mask.
Does the same as #6667 but without build bat fuckery.
Masks cant be used for smoking desires due to code issues I cant fixed. Time to make them a slow chem delivery systems, theyre good with space drugs and you need to know how to modify them but theyre good for pain chem delivery that lets you cut it off hen you want to instead of measuring pill size or liquid amounts. Balanced by the fact you cant use internals with it.
:cl:
tweak: changed the amount of power to use the vapour mask fully from 500 units to 200 units.
/:cl:
> Vapor but no build.bat

- code/modules/organs/blood.dm
- code/modules/organs/external/_external.dm
- code/modules/organs/external/damage.dm
- code/modules/organs/internal/_internal.dm
- code/modules/organs/internal/internal_organ_processes.dm
General tweaking with the organ efficiency system. Mirror of a near-identical PR I did on Sojourn
Makes Reinforced Bones work like it should
Improves code efficiency in calculating organ efficiency
Increases readability
:cl:
spellcheck: Fixes some variable typos for get_process_efficiency
tweak: Changes the heart's blood volume equation to an identical one that is easier to look at.
tweak: Changes the get_tally() function to include nerve and muscle efficiency. Only thing changed between this equation and the old equation is a .25 modifier on muscle efficiency. So minor it won't be noticed. (it still doesn't do much)
fix: Changed the take_damage function to account for bone efficiency when deciding whether or not to fracture a bone, like it does when an organ takes internal damage. This …
> Very slight Organ Efficiency changes and bugfixes

- code/game/machinery/crafting_station.dm
Fix a crafting exploit for the crafting station where you could spam recipes.
Exploit bad.
:cl: Hyperio
fix: Fix crafting station exploit
/:cl:
> Add working status check for crafting station

- code/game/objects/items/weapons/tools/_tools.dm
- code/game/objects/items/weapons/tools/weldingtools.dm
- Tools can now have different hitsounds when turned on
- Welding tools get a burn sound
Fixes "Oversight:Welding tool has the standard bashing sound when you use it to melee"
:cl:
tweak: welding tool hitsound
/:cl:
> Welding tools make burn hitsounds

- maps/submaps/deepmaint_rooms/normal/hive_nest.dmm
Typo fix for Test Subject Beta-149.
It's a typo fix. Subject, not subjet.
:cl: Xoxeyos
spellcheck: Typo fix for Test Subject Beta-149's name.
/:cl:
> Typo fix for unique hivemind mob.

- code/modules/organs/internal/internal_organ_processes.dm
F'er ye to undesstan', matey, parahlyze makes ya drop to them ground, not bein' able to see nor talk nor piss, while them weaken makes ye just fall to them ground, effectively makin' this pr a huge QoL for them blood loss enjoyars. Prollems?
a HUGE quality of life change. you still fall and drop shit, it's just that you can now hear and talk while down.
:cl:
tweak: blood loss now weakens instead of paralyses(hardstun)
/:cl:
> Replace blood loss paralyse with weaken

- code/datums/wires/airlock.dm
- code/datums/wires/alarm.dm
- code/datums/wires/apc.dm
- code/datums/wires/autolathe.dm
- code/datums/wires/camera.dm
- code/datums/wires/jukebox.dm
- code/datums/wires/mulebot.dm
- code/datums/wires/nuclearbomb.dm
- code/datums/wires/particle_accelerator.dm
- code/datums/wires/radio.dm
- code/datums/wires/robot.dm
- code/datums/wires/shield_generator.dm
- code/datums/wires/smartfridge.dm
- code/datums/wires/smes.dm
- code/datums/wires/suit_storage_unit.dm
- code/datums/wires/vending.dm
- code/datums/wires/wire_description.dm
- code/datums/wires/wires.dm
- code/modules/clothing/spacesuits/rig/rig_wiring.dm
All machinery(code/datums/wires/) has randomised wiring.
You can examine wires.
If your MEC is >= 40, you can figure out what the wire does.
Now MEC is actually useful besides gun crafting. ~~Come on, lynch me, I dare you.~~
This was in FortuneMaster's design doc. Also known as "Rope Bunny Boy" on discord.
:cl:
tweak: all wires in machinery are randomised now.
add: you can now examine(MEC >= 40) wires to figure out what each does.
/:cl:
> Randomise wiring, add examine wire, examining wires scales off MEC

- code/modules/projectiles/guns/projectile/revolver/mateba.dm
Mateba damage modifier updated from 1.35x to 1.75x
OP revolver should be OP, I refuse to accept that a Consul is equally as good as a Mateba.
:cl:
balance: Mateba damage modifier changed from 1.35x to 1.75x. Good luck ever finding it though.
/:cl:
> Makes the Mateba OP as it was always meant to be

- code/game/objects/items/weapons/implant/implant.dm
- code/game/objects/items/weapons/implant/implants/carrion/infection_spider.dm
fokken no idea who made this oversight, but JNFECTION carrion spiders could work in prosthetic limbs, effectively making it possible to infect and convert a FBP
yes, carrion in a steel body, bad fucking idea
carrion nerf
muh realism
:cl:
fix: infection spiders don't work in prosthetic limbs
/:cl:
> INFECTION carrion spiders don't work in prosthetic limbs

- code/__DEFINES/items_clothing.dm
- code/game/objects/effects/effect_system.dm
- code/modules/mob/living/carbon/human/life.dm
Legacy code made it so glasses can block smoke(???), so it was removed
For smoke proc not to work it needs not only the airtight tag(e.g. voidsuits have airtight), but the block smoke tag, which only the gasmasks have. Shouldn't inhale smoke if internals are on.
Everyone wants the smoke to be fixed, so here it is. I am not 100% this will fix the issue, because the smoke is handled horrendously spaghetti, and nanako also "fixed" it years ago. Still, it at least SHOULD work.
:cl:
fix: smoke should be inhaled properly now. Maybe.
/:cl:
> Fix smoke not being inhaled

- code/game/objects/effects/effect_system.dm
- code/modules/reagents/holder.dm
/datum/reagents/Destroy() does everything /datum/reagents/delete() does and more, and delete() is called only from /obj/effect/Destroy() which ITSELF is redundant with its parent /atom/movable/Destroy()
optimisation.
:cl:
del: removed abundant cleanup of atom/var/reagents.
/:cl:
> remove useless cleanup of /atom/var/reagents

- code/modules/clothing/head/armor.dm
Knocks paramedic helmet face shield vision tint down from `TINT_MODERATE` (default value, same as Altyn) to `TINT_LOW` (same as IH "heavy operator" helmet).
It has less armor than the IH "heavy operator" helmet, even with its faceplate down - and is harder to obtain than Altyn.
Dunno. I was asked to make this PR, and so I did.
:cl:
balance: Reduces face shield vision obstruction for paramedic helmet
/:cl:
> Reduces face shield vision obstruction for paramedic helmet

- code/game/objects/items/devices/suit_cooling.dm
- code/game/objects/items/stacks/knife.dm
- code/game/objects/items/weapons/storage/toolbox.dm
- code/game/objects/items/weapons/storage/wallets.dm
- code/modules/projectiles/guns/energy/laser.dm
Added material cost to items that obviously miss it (including newly added throwing knives), added ability to put appropriate oddities into wallet, increased melee damage for Cog (it's basically a laser equivalent to Novakovic, except it has nothing interesting or funky about it). I think it is fair considering Cog is an old and bulky police weapon, and those guys sure love bashing people skulls. 
Makes joonking and getting rid of items slightly less annoying and disappointing, adds some interesting property to old good Cog, makes so you can now put money into your wallet, wow. 
:cl:
tweak: Added material cost to toolboxes, throwing knives, suit cooling unit, increased OS LG "Cog" melee damage, added ability to put appropriate oddities into wallet.
/:cl:
> Super minor QoL tweaks

- code/modules/mob/living/carbon/human/human_attackhand.dm
Allows Punching to work properly for people with Special(tm) organs implanted, and removes a previously unknown, super niche exploit for everyone else.
Up until now, the organ efficiency in the active arm of THE PERSON BEING PUNCHED determined how much damage they took from punching. This meant many stupid things could happen, such as: If someone removed the blood vessels, nerves, and muscles in their right arm, they would be almost immune to being punched by other players, so long as they had their right hand selected.
This was intensely stupid, so I fixed it to use the limb efficiency of the person doing the punching instead.
Textbook example of why using bad variable names results in bad readability, which results in bad code. H.
:cl:
fix: Fix punching that was computed with the …
> Fixing punching with one line of code.

- code/game/objects/random/food.dm
- code/modules/reagents/reagents/toxins.dm
- code/modules/reagents/recipes.dm
- code/modules/scrap/oldificator.dm
yum!
Replaces vomitol in (most of) oldified food with mold, which damages sanity(2 per tick, spider venom deals 3, for scale) and gives a very little toxin damage(equal to pararein)
The taste is horrendous.
So, basically, homemade pararein. More potent(and common) version of vomitol, that can be extracted and added to normal drinks and foods to trol people
Vomitol, which is actually medicine, shouldn't be in old foods. So it's just a chem that you make now.
P. S. I decided to not add any warnings to the user about the mold processing and dealing sanity damage, but I can add them if needed.
:cl:
add: mold toxin. Mold deals sanity damage and a little bit of toxin damage.
tweak: vomitol in trash foods is replaced with mold.
/:cl:
> Replace vomitol with mold in trash foods

- code/game/machinery/kitchen/microwave.dm
- code/modules/reagents/reagents/dispenser.dm
- code/modules/reagents/reagents/drugs.dm
- code/modules/reagents/reagents/food-Drinks.dm
- code/modules/sanity/sanity_mob.dm
Alchohols give scaling sanity gain based on their strength
serotrotium insight gain = 3, previously - 1.5
Ciggaretes shall no longer be the king, long live throwing my wealth at alchohol at club.
:cl:
balance: Alcholic reagents give in general much more sanity based off their strength
balance: serotrotium insight gain increased to 3
/:cl:
> Buff ethanol and serotrotium

- code/game/objects/items/weapons/autopsy.dm
~~how the FUCK can a device in 5577 BUG OUT depending on HOW YOU HOLD IT???!!!~~ <-- I am still salty about this
formula itself: (BIO_STAT) * 4, always success at BIO 25+
you will be seeing those OPs who died to "tomato soup" and "oxygen tank" while being full of high-velocity pistol bullets far less often
:cl:
tweak: autopsy scanning error formula changed to BIO_STAT * 4
/:cl:
> Autopsy scanner error formula change

- code/modules/reagents/reagents/medicine.dm
Oxycodyne once again has the same metabolic rate as the rest of the painkillers and has 10 more pain relief, putting it on the same level as ParaTram (but still takes 20 more NSA). It was either this or make every other painkiller metabolise at the same speed as oxycodone and I took the path of least resistance.
Inconsistency isn't fun design and the painkiller that takes more effort to make shouldn't be objectively worse than its precursors. At least now it's on par with its contemporary, Tramadol, in terms of how much pain relief is provided per NSA.
:cl:
balance: Oxycodyne once again has the same metabolic rate as the rest of the painkillers and has 10 more pain relief, putting it on the same level as ParaTram (but still takes 20 more NSA).
/:cl:
> Tweaks Oxycodone

- code/_onclick/click.dm
- code/_onclick/hud/screen_objects/base_screen_objects.dm
after testing, I figured out that CC actually HAVE a (shitty) use, so to NOT make me experience PTSD I just turn them invisible to human eye
literally one line change btw
honestly we could just remove CC one day
:cl:
code: Click catchers are invisible now. One is right behind your back.
/:cl:
> Make click catchers invisible

- code/modules/mob/living/carbon/carbon.dm
- code/modules/mob/living/carbon/human/human_attackhand.dm
- code/modules/mob/living/carbon/human/human_defense.dm
- code/modules/mob/mob_helpers.dm
- code/modules/projectiles/projectile/bullets.dm
removes the old ass bay12 leftover get_zone_with_missing_chance proc, that overwrote some given vars and did useless checking + was calculating missing buckled mobs incorrectly. It was also removed to implement stat-based dodging.
dodging melee formula: __((base_miss_chance[hit_zone] * (5 /(1 + 100 / dodge) + 10))__ //soft cap
dodging  the thrown items formula: __(base_miss_chance[zone] * (10 / (1 + 100 / dodge ) + 10)) /10__ //soft cap
more ROB scaling, better dodge, fixes cool, bay leftover bad
:cl:
balance: dodging melee attacks and thrown items scales off ROB
del: bay leftover get_zone proc
fix: missing buckled mobs with thrown items
fix: division by zero in throwing knives code
/:cl:
> REMOVE melee and throw dodging, fix missing buckled mobs, fix division by zero in throwing knives

- code/datums/craft/recipes/guns.dm
- code/datums/craft/recipes/misc.dm
Moves the gun assembly from misc to guns.
Think its better to have a gun related crafting assembly to be in the guns category, rather than at the bottom of misc
:cl:
tweak: Moved gun assembly craft recipe to the "guns" category from "misc"
/:cl:
> Gun assembly moved to guns crafting category

- code/modules/mob/living/carbon/human/human_attackhand.dm
- code/modules/mob/living/recoil.dm
I am going to be hated for this probs, maybe needs tweaking
disarming adds recoil that scales off of ROB
your own ROB negates some of recoil damage
you need 60+ recoil to disarm
80 if item is wielded!
the CRAZY formulas, made ~~up~~ by Humon
rob_attacker = (50 / (1 + 150 / (min(1, __attacker robustness__))) + 40) - soft capped amount of recoil that attacker deals
rob_target = max(0, min(400, __target robustness__)) - hard capped amount of recoil the target negates upon disarming. 400 - no recoil
recoil_damage = (rob_attacker * (1 - (rob_target / 400))) - recoil itself
:cl: Kegdo and Humonitarian
add: disarm deals recoil, scales off of ROB from both the attacker and target, wielding matters
/:cl:
> Remove RNG from disarming

- code/modules/materials/materials.dm
Materials will now use the solid wall base as default, this doesn't affect materials which have their own icon_base set. This can lead to weird behavior but we're beyond that now.
Iron walls adjacent to some steel ones:
Old iron wall adjacent to the newer ones:
Less 2D, more Faux-3D.
:cl:
tweak: Some materials will form regular-looking walls now.
/:cl:
> Material Wall Icons

- code/game/machinery/doors/airlock.dm
Uncomments airlock headbutting
Hurr duurrr i hav brain damage , people should suffer for having brain damage
:cl:
balance: People with brain damage have a high change to headbutt airlocks.
/:cl:
> Brings back airlock headbutting

- code/game/objects/items/weapons/tools/mods/mod_types.dm
makes an overwriting definition of hydraulic circuits actually refer to the plasma coating
i miss hydraulics bro
:cl:
fix: Hydraulic circuits have returned to increasing tool speed, and not coating tools in plasma.
/:cl:
> makes hydraulic circuits hydraulic again

- code/game/machinery/crafting_station.dm
replaces a code snippet referring to the autolathe to make it refer to the crafting station. also adds the proc for crafting stations to eject materials. doesn't make it accessible other than deconstruction though
i feel like deconstructing a crafting station for the mats inside it is a good idea
:cl:
fix: Crafting stations should now, theoretically, drop their loaded materials when deconstructed.
/:cl:
> crafting stations should drop their materials on deconstruction

- code/game/objects/structures/catwalk.dm
Catwalks now only show caution strips when bordering plating/underplating (implied elevation difference)
:cl:
tweak: Catwalk smoothing
/:cl:
> Catwalk smoothing

- code/modules/clothing/accessories/holster.dm
Backport thing from: https://github.com/Occulus-Server/Occulus-Eris/pull/777
I've deleted two firearms so far using a holster, no more.
:cl: Jamini
fix: Holsters no longer devour guns
/:cl:
> Jamini's Holster fix

- code/game/objects/items/weapons/mine.dm
https://user-images.githubusercontent.com/65828539/146677479-154e9967-a0fd-49c3-9281-301e3567bd0a.mp4
Fixes cool.
:cl:
fix: pre-spawned mines missing blink animation
/:cl:
> Fix pre-spawned mines missing blink animation

- code/_onclick/hud/action.dm
- code/modules/clothing/suits/armor.dm
Replaced constant 0.3 speed boost of paramedic's armor with 0.5, that can be active for ~15~ 30 seconds and have a cooldown of 5 minutes.
Added materials of medium atomcell to armor cost.
If paramedic helmet is equipped, there will be notifications on activation, deactivation and cooldown end.
People are salty over constant speed boost, probably that will work out better.
:cl:
tweak: paramedic armor's constant 0.3 speed boost replaced with 0.5, that can be active for 30 seconds and have a cooldown of 5 minutes
/:cl:
> Paramedic armor slowdown rework

- code/__HELPERS/global_lists.dm
- code/datums/repositories/crew/binary.dm
- code/datums/repositories/crew/crew.dm
- code/datums/repositories/crew/vital.dm
- code/modules/clothing/head/armor.dm
- code/modules/modular_computers/file_system/programs/medical/suit_sensors.dm
- nano/templates/crew_monitor.tmpl
Fixed an issue with synthetic heart triggering suit sensors.
Added mute/unmute button to paramedic tablet's interface, allowing to disable paramedic helmet's notifications for specific people.
Fixes cool.
QoL features cool too.
:cl:
add: mute/unmute button to paramedic tablet's interface
fix: synthetic heart no longer trigger suit sensors
/:cl:
> Paramedic helmet fix and "mute" feature

- code/modules/core_implant/cruciform/rituals/priest.dm
It's finally time, as NT development moves on more and more litanies have been added into the Preacher list. This PR makes the split between shared litanies and Preacher exclusive litanies.
Two short lists are far easier to navigate than one bloated list.
:cl:
add: Litanies shared between the Acolytes and the Preacher have been separated into their own list.
/:cl:
> Splits shared and Preacher exclusive NT litanies into separate lists

- code/datums/craft/recipes/weapon.dm
- code/game/objects/items/weapons/tools/knives.dm
Reduces drill requirement to 5, so you can use a shiv
Also makes the shiv actually show up, 2 fucking lines come on people and no one noticed a invisible shiv
More pipebombs, Go full Ted Kaczynski
:cl:
tweak: drill quality requirement for pipebomb, reduced to 5, you can now use a shiv/knife/etc.
/:cl:
> Pipebomb change, shiv DLC

- code/modules/mob/living/silicon/silicon.dm
Your mining robot pressed "rest" verb and turned immobile and deaf? No more!
Fixes cool.
:cl:
fix: robots being able to rest
/:cl:
> Fix resting robots

- code/modules/scrap/oldificator.dm
Rejuvenator will empty harddrives from all files, including the designs within design disks. It will also reduce license to 0, if any.
Prevents rejuv from fixing up designs disks with little effort, but still allows the rejuvenation of printed items.
:cl:
add: rejuv clears disks
/:cl:
> Harddrives interact with rejuvenator

- code/game/machinery/crafting_station.dm
Adds RPG shell costs to examine on crafting bench.
Clarity.
:cl:
spellcheck: RPG shell cost now shown on examining crafting station
/:cl:
> Forgotten cost blurb added

- cev_eris.dme
- code/game/objects/effects/overlays.dm
- code/game/objects/empulse.dm
- code/game/objects/heatwave.dm
- code/modules/projectiles/effects.dm
- code/modules/projectiles/guns/energy/plasma.dm
- code/modules/projectiles/projectile/plasma.dm
- code/modules/shieldgen/emergency_shield.dm
Reworks plasma projectiles, adds new effects.
Dominion:
- Light projectiles, offers good firerate and has a burst-fire mode
- Alternate fire: powerful anti-armor projectile with high energy cost and firedelay
Cassad:
- Standard semi-auto with good firerate and relatively low energy cost
- Alternate fire: high-cost and high-delay shot that causes AoE damage, and a small EMP effect, allowing more tactical utility
Purger:
- Fully automatic, will rapidly release medium-powered shots at an increased energy cost
- Alternate fire: high-cost and high-delay shot that causes heavy AoE damage, and a larger EMP effect, making it ideal for destroying heretical equipment and machinery
Brigador:
- Light projectiles, with mediocre firerate
- Alternate fire 1: powerful anti-armor projectiles with massive …
> Plasma firemode rework

- code/game/machinery/nuclear_bomb.dm
When the ship's nuke is armed (read: any nuke with `eris_ship_bomb = TRUE`), the alert level will be set to Delta.
If the nuke is disarmed/safed, the alert will drop to what it was before the nuke was armed.
Fixes https://github.com/discordia-space/CEV-Eris/issues/1858
Big ol' alarm for when the nuke is angry.
:cl:
add: The ship's nuke now sets the alert level to Delta when armed, and back to the original level when disarmed.
/:cl:
> Ship's nuke sets the alert to delta when armed

- code/datums/wires/airlock.dm
- code/datums/wires/alarm.dm
- code/datums/wires/apc.dm
- code/datums/wires/autolathe.dm
- code/datums/wires/camera.dm
- code/datums/wires/jukebox.dm
- code/datums/wires/lrange_scanner.dm
- code/datums/wires/nuclearbomb.dm
- code/datums/wires/particle_accelerator.dm
- code/datums/wires/radio.dm
- code/datums/wires/robot.dm
- code/datums/wires/shield_generator.dm
- code/datums/wires/smartfridge.dm
- code/datums/wires/smes.dm
- code/datums/wires/suit_storage_unit.dm
- code/datums/wires/taperecorder.dm
- code/datums/wires/vending.dm
- code/datums/wires/wires.dm
- code/game/machinery/bots/mulebot.dm
Reworked version of #6820.
Removes silly examine button and authomatically shows wire function if player stats are high enough.
Default:
MEC stat over 40 or technomancer perk:
Pressing examine a dozen times for every door sucks a lot, so here is QoL improvement.
:cl:
refactor: wires UI looks less shitty
/:cl:
> Wires UI done right

- code/modules/mob/living/carbon/human/human_defense.dm
Pretty radical change, makes armor stack multiplicatively (eg. 60% bulletproof with 10% rockerboy jumpsuit becomes 64% bullet protection). There are other safety features in mind, such as any armor against melee, bullet and energy is averaged with 75 once above 75. (eg. 80 armor becomes (75+80)/2)
_**Do not merge**_
Until properly tested.
Armor will make a lot more sense now, limbs will be able to take armor from organs and from being robotic, generally just a lot more pleasant to make features for.
:cl:
balance: armor stacks
/:cl:
> Armor stacking with fall-off and fractional multiplication

- code/game/machinery/vending.dm
Apparently last PR fixed only part of the issue, my bad.
Fixes cool.
:cl:
fix: ammo names in vendor, this time for real
/:cl:
> Fix ammo names in vendors (again)

- code/modules/reagents/recipes.dm
Fixes `## ERROR: recipe /datum/chemical_reaction/platinumsolidification created incorectly,[required_reagents] reagent with id "platinum" does not exist.` introduced in #6893, by removing the recipe.
Better than adding more reagents that will be used maybe in one of hundreds rounds, if at all.
Errors bad, all my hommies hate errors.
:cl:
del: platinum solidification recipe
/:cl:
> Remove "platinumsolidification" recipe

- code/modules/mob/living/living_defense.dm
- code/modules/projectiles/projectile/energy.dm
Gun code was not meant to handle the agony damage of crossbow bolts, that is fixed. Apparently these two guns are overpowered, downing an antagman (full mercenary armor, that gives 50 energy protection against the 0 penetration of the crossbows) in 5 shots, so their firepower was nerfed. They have no recoil, afterall.
Themis and Nemesis fix good.
:cl:
fix: Themis and Nemesis now do agony damage as intended
balance: Themis and Nemesis nerfed
/:cl:
> Themis and Nemesis fix

- code/datums/perks/oddity.dm
- code/modules/mob/living/living.dm
- code/modules/mob/living/living_defines.dm
- code/modules/mob/living/silicon/pai/pai.dm
- code/modules/mob/living/simple_animal/simple_animal.dm
- code/modules/tables/interactions.dm
- interface/skin.dmf
Tactical Combat design doc PR stage 1
Rest hotkey - C
Can't stack resting action anymore
You can dive and dodge now, based on rest(more info in the video in discord, too big to post here)
Removed bay leftover SHEET ROLLING PROC
Parkour perk reduces the time it takes to stand up
Diving is a 1-tile JUMP(you can bridge gaps!) which lets you pass over tables, so you can vault over a table and cover. Press C(rest) while moving. You may continue to hold down C after a dive to preserve your momentum and slide. This will allow you to close a few extra tiles at an increased speed until you run out of momentum, and dodge unaimed projectiles. Being faster increases the maximum range of sliding.
For the time being tables and short walls exist as hard to pass obstacles, players having to spend …
> Mobility Stage 1: Diving, Sliding

- code/modules/maps/tg/reader.dm
So, according to SpaceManiac over at coderbus, the issue happened if for whatever reason the next map going through reader.dm started loading as the previous was being CHECK_TICK'd.
Assuming this works, this should stop CI from failing due to reader.dm runtimes.
(Side note, if this is merged before other PRs that have failing checks, those PR branches will need to have the updated master branch merged into them.)
> Attempt to fix reader.dm CI fails

- code/game/objects/items/weapons/nt_melee.dm
You can no longer store the NT spear in the NT buckler.
The NT spear does not fit into backpacks, but the NT buckler does. Thus, you shouldn't be able to put the NT spear into the buckler and store the buckler inside of a backpack. Also change for the sake of change (I was asked to do this)
:cl:
tweak: you cannot store the NT spear inside the NT buckler anymore (not balance, I swear!)
/:cl:
> Shield of holding no more

- code/__HELPERS/bluespace_entropy.dm
- code/controllers/subsystems/voting/poll_types.dm
- code/game/gamemodes/storyteller.dm
- code/game/gamemodes/storyteller_print.dm
- interface/skin.dmf
Adds the chaos level vote into the game. It can be called after an hour and a half from roundstart and after that every 30 minutes. Each vote increases storyteller point generation (first vote OG value * 2, second vote OG value * 3 and so on), bluespace entropy generation and lowers cooldowns on bluespace entropy events.
Player vote need 75% positive votes to pass as it increases point generation for the rest of the round.
Bandaid fix until storyteller rework (never)
Speeds up rounds after the 90 minute mark, and only if the players want so. Many a time have I found myself at this time of the game after a major threat has been defeated (excels, hive, serbs), with the choice to wait another hour so something interesting would happen or jump now and wait again, but in the next round. Now …
> Chaos Level

- code/game/objects/items/weapons/implant/implants/carrion/carrion_spiders.dm
- code/game/objects/items/weapons/implant/implants/carrion/observer_spider.dm
- code/modules/organs/internal/carrion.dm
- code/modules/reagents/reagent_dispenser.dm
- nano/templates/carrion_spiders.tmpl
You can now assign carrion spiders to one or multiple groups, and activate all the spiders in a group at the same time.
The observer spider will also no longer be triggered when activating all spiders, since you don't really want that to happen if you hit "activate all".
Also fixes a bug with fuel tanks, you can now make them leak fuel and secure them to the floor again.
Hyperioo, Handyman and Shown were a great help as per usual.
makes it easier to pull off 9000 IQ schemes
:cl:
add: Carrion spiders can now be assigned to groups to make them activateable at the same time.
tweak: the observer spider will no longer be triggered when activating all carrion spiders
fix: you can now secure water and fuel tanks to the ground and make fuel tanks leak fuel again
/:cl:
> Carrion spider menu QOL

- code/modules/mob/living/living_defense.dm
Reduces armor hallos coefficient from 0.4 to 0.1, makes armor more effective.
Requested by TheShown.
:cl:
tweak: armor hallos coefficient changed from 0.4 to 0.1, armor more effective now
/:cl:
> Reducing armor hallos coefficient

- code/modules/reagents/reagent_containers/food/drinks/bottle.dm
Bottles properly break when thrown with harm intent again.
https://github.com/discordia-space/CEV-Eris/pull/5211 
broke bottles breaking when thrown (I now realize how stupid this sounds, but I'm not going to change it), because bottles check if the thrower is in harm intent when the bottle smashes, but that PR made the thrower var on the item get set to null before the throw_impact. This is a workaround.
I also removed the random chance from bottles breaking when thrown, they now always break regardless of range traveled when thrown by someone with harm intent. Fire is weak enough already, no need to add a random chance for a molotov not to break on impact.
No good revolution without molotovs.
:cl:
balance: bottles now always break when thrown with harm intent active
fix: bottles can now …
> Molotov fix

- code/modules/admin/verbs/getlogs.dm
Currently, if the server's time hits the next day, the server log for that round will no longer be accessible from in-game.
This makes it so that the "Get Server Log" verb uses the `diary` var, which is set to the server file for the round on world start, and doesn't change.
:cl:
admin: Get-Server-Log will no longer stop working if the server hits midnight during a round.
/:cl:
> Fixes "Get-Server-Log" not working if server hits midnight during a round

- code/game/objects/items/weapons/tools/mods/mod_types.dm
the gyroscopic stabilizer can now be used as a toolmod and gunmod again.
fixes good.
:cl:
fix: the gyroscopic stabilizer can now be used as a toolmod and gunmod again.
/:cl:
> gyroscopic stabilizer bug fix

- code/modules/projectiles/guns/projectile/sniper.dm
- code/modules/projectiles/projectile/beams.dm
- code/modules/projectiles/projectile/bullettypes.dm
- code/modules/projectiles/projectile/plasma.dm
- code/modules/projectiles/projectile/special.dm
Reduces most bullet damages by 20%, with some mercy shown towards .35. Also increases style damage on lasers and the RPG.
Let me first start off by blaming all of this on humon, they came to my house and threatened to release my ERP logs if I didn't comply.
Jokes aside, I've been asked to do this in the past by several people. Bullet damage is believed to be a little too high, and while bullets are still going to be substantially powerful, this should lower TTK a bit, making fire hit advantage a bit less deadly and making lighter armors less dangerous. This also applies to plasma projectiles but not lasers, as in general most people consider them to be underperforming and they have less damage and no AP on average.
As for the style damage thing, I think lasers were forgotten since I'm the …
> Bullet Nerf and laser/RPG buff

- code/game/machinery/doors/firedoor.dm
As per title.
Stops CI from erroring on every PR. Again.
(Please, _please_, check that PRs aren't failing CI checks* before merging. They're there to help catch runtimes and other broken stuff.)
((*Not really applicable when it's an issue out of the scope of their PR, ie: the `reader.dm` runtime))
> Fixes firedoors runtiming, if update_icon was called before init

- code/modules/organs/internal/carrion.dm
- nano/templates/carrion_spiders.tmpl
The carrion spider group buttons will now be red when the spider is not in a group and blue when it is in a group.
words are hard, so this is what it looks like now.
also replaces a few else ifs with something better.
and makes the spider window a bit wider by default to accommodate all the buttons properly.
easier to distinguish which spiders are in which group.
:cl:
add: adds colors to carrion group activation buttons.
/:cl:
> carrion spider group coloring

- code/modules/projectiles/gun.dm
Adds in a check to make sure you cant swap fire modes well shooting.
Prevents a bug were you can swap fire modes mid-burst shot to full auto or semi auto, forcing the burst shot to complete itself at the same time
Tested to work without any issues to note.
:cl:
fix: Fixes swapping fire modes well shooting.
/:cl:
> Fixes a omni fire bug.

- code/modules/mob/living/carbon/carbon.dm
the calculation formula somehow managed to fuck up, so the damage numbers were always extremely low(I'm talking about 4 damage at 500 rob and 2 damage at 0)
bug fix
:cl:
fix: throwing knife damage
/:cl:
> throwing knife damage fix

- code/datums/perks/fate.dm
- code/modules/reagents/metabolism.dm
- code/modules/reagents/reagents.dm
alcoholic fate perk gets permanent addiction, alcoholic gets bonus of 15 stats, and yes this is a fair and balanced tradeoff
drug addict now gets a bottle of 12 pills full of 15 units of a random stim they are addicted to; before, they got FUCKING __60__(!!!) units of a drug in one pill, AND TWO BOTTLES of said pills(~25). also permanent addiction yea
withdrawal deals gradually more sanity damage when you get the... announcement? english hard
anyways: 
stage1 - 0 (sanity dmg)
stage2 - 0
stage3 - 5
stage4 - 10
end - +10 sanity restoration
trillionardos of people complained that withdrawal does nothing(except for stat debuffs for certain chems)
now, in REAL WORLD(sic!) withdrawals are pain!! time to add realism
also fates focused on addiction are actually addicted and good now, with an …
> Withdrawal deals sanity damage, tweak perks focused on addiction

- code/game/objects/structures/crates_lockers/closets/secure/chaplain.dm
All 10 Cruciforms Removed From Preacher's Locker. 
Before the addition of the Cruciform Forge, 10 roundstart Cruciforms was welcome. At of the addition of the Cruciform forge, the existence of 10 roundstart cruciforms became excessive. As of the Chapel Remapping, with four additional Cruciforms added to spawn adjacent to the Altar, their existence became redundant. With the addition of a cruciform sink of the NTV Faith's export of cruciforms, NT players are provided with an effort free means to acquire large capital, with minimal fear of using their entire supply of roundstart cruciforms (an average of 2 required every twenty minutes, if deals with the guild are done perfectly). Dropping NT's supply of roundstard cruciforms would allow the Cruciform Forge to take up a more active roll, …
> Removes Cruciforms From Preacher's Locker

- code/game/machinery/kitchen/microwave.dm
- code/modules/hydroponics/trays/tray.dm
In the displayed messages, securing and unsecuring where inverted.
:cl: Hyperio
fix: Fixed microwave and fire barrel secure unsecure verbs
fix: Fixed hydroponics tray secure unsecure verbs
/:cl:
> Fix microwav, fire barrel, hydroponics tray secure unsecure verbs

- maps/submaps/planetary_ruins/crashed_pod/crashed_pod.dmm
- maps/submaps/planetary_ruins/ec_old_crash/ec_old_crash.dmm
- maps/submaps/planetary_ruins/marooned/marooned.dmm
- maps/submaps/planetary_ruins/oldpod/oldpod.dmm
Remove cables and pipes from planetary ruins to reduce server load.
Also replace boombas by other roombas to avoid undesired roundstart explosions (boombas rush the corpses that have no factions).
:cl: Hyperio
tweak: Remove cables and pipes from planetary ruins to reduce server load.
tweak: Replace boombas by other roombas to avoid undesired roundstart explosions
/:cl:
> Remove cables and pipes from planetary ruins to reduce server load.

- code/modules/mob/new_player/new_player.dm
Warn player if they are trying to spawn without brain or eyes.
Avoid ahelps of players dying right when they spawn because they let brain to "Removed" in their player setup.
:cl: Hyperio
add: Added warning when trying to spawn without brain or eyes
/:cl:
> Warn player if they are trying to spawn without brain or eyes

- code/modules/mining/drilling/deep_drill.dm
- code/modules/mining/drilling/golem_wave.dm
- code/modules/mob/living/carbon/superior_animal/golem/golem.dm
Another balance pass:
* Double time interval between burrows for all waves
* Double time interval between golem spawn for all waves
* Double drill health
* Increased mineral multiplier
* Golems no longer try to destry golem burrows in their way
* Drill has three health stage. If its healths falls under 66%, you can only repair it up to 66%. If it falls under 33%, you can only repair it up to 33%.
Note: Destroying golem burrows by hitting them with weapons is a good way to avoid a snowball of the number of golems. Updated deep mining guide to include tips.
:cl: Hyperio
balance: Double time interval between burrows for all waves
balance: Double time interval between golem spawn for all waves
balance: Double drill health
balance: Increased mineral multiplier
fix: Golems no longer try to …
> Mining Overhaul Part 2.2

- code/game/objects/items.dm
- code/modules/mob/living/carbon/human/human.dm
- code/modules/mob/living/carbon/human/life.dm
- code/modules/projectiles/gun.dm
previously, when using a scope or binocular to zoom out, your expanded view would immediately switch back to the default amount of tiles, this fixes that. Hyperio helped, as per usual.
Fixes good, scopes good (actually bad)
:cl:
fix: fixed a bug with zooming out
/:cl:
> fixes scopes

- code/game/gamemodes/changeling/modularchangling.dm
- code/game/objects/items/weapons/implant/implants/carrion/blight_spider.dm
- code/game/objects/items/weapons/implant/implants/carrion/identity_spider.dm
- code/game/objects/items/weapons/implant/implants/carrion/talking_spider.dm
Don't worry, this is the last balance PR in a while, content PR coming soon.
Lowers the gene point cost of the talking, identity and holographic spiders from 3 to 1, and also lowered the chem point cost of the talking and identity spider- All of these spiders aren't too powerful, but actually using them can make for fun rounds, so they should be cheaper to acquire and produce.
Reduces the gene point cost of the blight spider from 7 to 5, doubles the amount of amatoxin it injects from 5 to 10 and makes it inject 5 units of pararein as well. Previously, the toxins from a single blight spider would just get outhealed by passive toxin regeneration, and even if multiple were stacked, the toxins buildup was still extremely slow and could be easily healed.
Now, a single spider is at least able …
> carrion spider balance

- code/global.dm
- code/modules/economy/economy_misc.dm
its always annoyed me how in a few small places the date was set to be several hundred years after the game is set because bay leftover lore. so i changed it to the correct date (at least according to the wiki). the current date is now 2341 (Current date +319 in code) halfway through Eris's journey. bank account creation date is 2339, when the wiki says the Eris departed
correct information in game as to when eris takes place, """lore""" in game good, bay leftovers bad
:cl:
fix: fixed bank account creation date to be lore accurate
config: changed game year to be lore accurate
:cl:
> Fixes in-game Date

- code/game/objects/items/weapons/implant/implants/carrion/carrion_spiders.dm
- code/modules/organs/internal/carrion.dm
- code/modules/projectiles/guns/projectile/automatic/vintorez.dm
- nano/templates/carrion_spiders.tmpl
Makes carrion spider groups handled by bitflags.
Adds an extra group for carrion spiders (now 4 groups), 3 groups weren't enough.
Newly spawned spiders will now get assigned to all groups that another spider of the same type is in (if there is a spark spider that's in group 1 and 3, a newly spawned spark spider will also be assigned to group 1 and 3 automatically). Auto-assigning can an be turned on and off.
Makes the carrion spider activation window even wider!
Hyperio helped with the code for group auto-assigning.
more QOL
:cl:
tweak: Some QOL changes to the carrion spider activation menu.
/:cl:
> Spider menu QOL and new features

- code/modules/clothing/head/armor.dm
- code/modules/clothing/spacesuits/rig/suits/combat.dm
- code/modules/clothing/spacesuits/rig/suits/merc.dm
- code/modules/clothing/spacesuits/rig/suits/station.dm
- code/modules/clothing/spacesuits/void/anomaly_suit.dm
- code/modules/clothing/spacesuits/void/excelsior.dm
- code/modules/clothing/spacesuits/void/merc.dm
- code/modules/clothing/spacesuits/void/station.dm
- code/modules/clothing/suits/armor.dm
- code/modules/clothing/suits/jobs.dm
- code/modules/clothing/suits/labcoat.dm
- code/modules/clothing/suits/neotheology.dm
- code/modules/projectiles/projectile/beams.dm
Rebalances armor, primarily buffing low to mid tier armors, and buffs laser beam AP.
Hopefully makes armor a little more meaningful. I've personally found that anything less that 40% did very little to help me survive. I believe this will make armor tiers that aren't BP more effective. I also standardized the stats a bit because I suspect I have OCD and the numbers were triggering me, so helmets will line up with their vests.
In case anyone is worried, bulletproof armor did not get any stronger against ballistics, 60% is still the highest you'll see on ship. I strengthed some of the lesser specialist armors without making them completely useless against their weakness (looking at you flak armor), so with energy weapons hopefully becoming more prominent, we shouldn't see too many issues in …
> Armor buff

- code/game/machinery/deployable.dm
- code/game/objects/structures/low_wall.dm
- code/modules/tables/interactions.dm
Reverts discordia-space/CEV-Eris#7045
it broke the SM, causing the emitter to destroy the low wall infront of crystal and delam every single round. will conduct futher testing.
> Revert "Makes cover work at a distance"

- code/datums/outfits/antagonist/mercenary.dm
- code/game/objects/items/devices/radio/encryptionkey.dm
- code/game/objects/items/devices/radio/headset.dm
- code/game/objects/items/devices/radio/radio.dm
Serbs now have access without needing to spend tc their own coms, but it only has common and Mercenary.
Screen shot of testing - 
Rozalimo requested this to help let the serb team communicate better with one a other and this gives more uses for emaging the wave radio. This also still gives use for buying the Synda headset as it still decrypts all coms  
:cl:
add: Mercenaries now have a radio with their own privet channel rather then needing to buy it form their uplinks - But its more limited then the version they do buy
/:cl:
> Mercs own headset

- code/modules/mining/mine_turfs.dm
- code/modules/overmap/exoplanets/turfs.dm
Make asteroid and exoplanet turfs indestructible by overwritting their take_damage proc so that it does nothing. That way those turfs won't expose metal plating after being hit by weapon or by explosion. Problem was that a whole planet could be vented by a hole (destroying the plating exposes space).
:cl: Hyperio
tweak: Asteroid and exoplanet turfs are now indestructible
/:cl:
> Make asteroid and exoplanet turfs indestructible

- code/modules/dungeons/junk_tractor_beam.dm
- nano/templates/jtb_console.tmpl
Fix issue with JTB portals when releasing too soon. You could release the junk field while it was being created, which glitched the generation and made a portal on the ship that led you to nullspace. There is now a new "STABILIZING" state during JTB creation and you can only release when it is finished, in STABILIZED state.
:cl: Hyperio
fix: Fix issue with JTB portals when releasing too soon
/:cl:
> Fix issue with JTB portals when releasing too soon

- code/__DEFINES/weapons.dm
- code/modules/projectiles/gun.dm
- code/modules/projectiles/guns/projectile/automatic/sol.dm
Adds a new fire mode to the Sol: Rapid 3-round bursts. Within the bursts, the rounds are fired more quickly, but the delay between the bursts is much larger than that of the regular 3-round burst mode, resulting in an overall worse RoF.
Also removes some redundant code related to zooming with guns.
WIGFTG
You can use this mode when you can't get LoS on a target for longer amounts of times, for example when you or your target are hiding behind cover and only peek around a corner for short amounts of time.
Gives IH ops a reason to choose the sol over the wintermute 
:cl:
add: Adds rapid 3-round-bursts to the Sol
/:cl:
> Rapid burst mode for the Sol

- code/game/gamemodes/events/blob.dm
- code/game/machinery/doors/door.dm
- code/game/machinery/doppler_array.dm
- code/game/machinery/portable_turret.dm
- code/game/machinery/vending.dm
- code/game/objects/explosion.dm
- code/game/objects/items/weapons/grenades/explosive.dm
- code/game/objects/structures/girders.dm
- code/game/objects/structures/grille.dm
- code/game/objects/structures/window.dm
- code/game/turfs/simulated/floor_acts.dm
- code/game/turfs/simulated/walls.dm
- code/modules/hivemind/machines.dm
- code/modules/hydroponics/spreading/spreading_response.dm
- code/modules/mob/living/carbon/human/human.dm
- code/modules/mob/living/carbon/superior_animal/defense.dm
- code/modules/mob/living/silicon/silicon.dm
- code/modules/mob/living/simple_animal/hostile/megafauna/megafauna.dm
- code/modules/mob/living/simple_animal/simple_animal.dm
- code/modules/power/antimatter/containment_jar.dm
- code/modules/power/antimatter/control.dm
- code/modules/power/antimatter/shielding.dm
- code/modules/power/cell.dm
- code/modules/power/supermatter/supermatter.dm
- code/modules/projectiles/projectile/projectilegrenades.dm
- code/modules/projectiles/projectile/special.dm
- code/modules/recycling/disposal.dm
- code/modules/research/xenoarchaeology/artifact/artifact_unknown.dm
- code/modules/research/xenoarchaeology/machinery/coolant.dm
- code/modules/shieldgen/sheldwallgen.dm
Adds another layer of severity.
Reduces the damage of Severity 2 and 3 in accordance with the bullet damage nerf.
All explosions with the new severity not defined will reduce the severity 3 range by 1, and add severity 4 with the range of severity 3, but increased by two.
(Eg. if the severity 3 impact range is 4, then it is reduced to 3, and the severity 4 impact range is set to 5)
Severity 4 deals little to no damage to most structures, but can still cause significant damage to mobs, or unarmoured humans.
Even light armor gives a significant advantage, heavy armor will outright halve damage taken from severity 4, encouraging heavy armor to counter light explosives.
Salt PR (it isn't)
Balance good
:cl:
add: Severity 4 explosions implemented
balance: blast and explosive grenades now less …
> Severity 4

- code/__DEFINES/weapons.dm
- code/modules/projectiles/gun.dm
- code/modules/projectiles/guns/projectile/automatic/maxim.dm
The damage reduction for a gun being in fullauto/burst mode was applied twice, leading to double the reduction of the listed damage. The damage reduction of firemode has been doubled, so in practice nothing about the damage has changed, this is fix is just there for clarity.
more clarity
:cl:
fix: fixed the fullauto/burst damage reduction being applied twice. doubled fullauto and burst damage reduction.
/:cl:
> Fixes fullauto damage reduction being applied twice

- code/game/objects/items/weapons/nt_melee.dm
reduced the damage the NT spear does when thrown from 75 to 45. the 75 value is a remnant of when all throwforces were multiplied by 0.6 for the purpose of applying damage. This changes it back to it's old damage.
also increases the style damage of the spear to 50 (requested by humon)
fix but also balance
:cl:
balance: The NT spear now deals the intended 45 damage when thrown instead of 75 damage, and deals 50 style damage instead of 20.
/:cl:
> NT pilum throwing damage reduction

- code/modules/client/preference_setup/global/preferences.dm
The "Keep hotkeys on mob change" preference will now be toggled on by default. This way, switching mobs (such as detaching as carrion) will no longer turn your hotkey mode off by default.
I didn't know this existed and neither did you
:cl:
tweak: the "Keep hotkeys on mob change" preference will now be toggled on by default
/:cl:
> default hotkey retaining on mob change

- code/game/objects/items/weapons/storage/uplink_kits.dm
- code/modules/clothing/chameleon.dm
- nano/templates/chameleon.tmpl
~~I'm deeply sorry~~
Wearing the chameleon jumpsuit will now allow you to quickly switch between one of 4 loadouts, which you can customize yourself (the default loadouts are a vagabond, an IH op, a scientist and a NT acolyte)
Also adds a chameleon satchel, so you are no longer bound to using a backpack if you want to go full chameleon clothes.
Chameleon clothes will now properly respect what the item they are mimicking is supposed to block from view. (Previously, having a chameleon mask with the appearance of a cigarette would not display glasses)
Chameleon clothes no longer contain biomatter, but plastic instead, so moebius can now actually print the chameleon kit.
Hex helped with the nanoUI stuff. Others who I forgot about probably helped, too.
this is the result of a copy-paste coder …
> Chameleon clothing update

- code/datums/uplink/stealth and camouflage items.dm
- code/game/objects/items/weapons/storage/uplink_kits.dm
- code/modules/clothing/masks/voice.dm
- code/modules/clothing/spawn_data/spawn_data.dm
- code/modules/mob/hear_say.dm
The voice changer mask now works exactly like a chameleon mask, meaning that you can change it's appearance at will.
Also moves the "toggle voice" and "change voice" verbs to the Chameleon items tab.
harder to spot someone obviously mimicking someone's voice
:cl:
tweak: The voice changer mask can now change appearances like a chameleon mask. 
tweak: The "change voice" and "toggle voice" verbs of the voice changer have been moved to the chameleon item tab
/:cl:
> Gives the voice changer mask chameleon capabilities

- code/game/objects/items/devices/lighting/toggleable/flashlight.dm
Makes the seclite use half the amount of power per tick as it did before.
(the removed light_spot radius of the seclite doesn't matter, since it doesn't matter from the base flashlight one)
Gives operatives a reason not to ditch their seclite for a heavy duty flashlight.
:cl:
tweak: the seclite now uses half as much power per tick as it did before.
/:cl:
> Better efficiency for the seclite

- code/modules/core_implant/cruciform/rituals/construction.dm
Changes one line so the ritual to construct the platform parts for the bioreactor gives the correct result, instead of another tank platform. Closes #7077 
Actually being able to build the machines you're supposed to be able to is good.
:cl:
fix: Attempting to construct a bioreactor platform now gives the correct result, instead of a tank platform.
/:cl:
> Fixes construction ritual result

- code/modules/mob/living/carbon/carbon.dm
- code/modules/mob/living/carbon/human/life.dm
- code/modules/mob/mob.dm
- code/modules/multiz/turf.dm
- code/modules/reagents/reagents/food-Drinks.dm
- code/modules/shuttles/shuttle.dm
- oldcode/shuttles_old/old_shuttle.dm
Sources of getting weakened include falling down a zlevel, being electrocuted, tripping on underplating and many more. All of these now make you drop the items you are holding in your hands again, with the exceptions of being weakened by shuttle acceleration and by radiation effects. Resting and diving will NOT make you drop items in your hands.
Jumping on top of someone from above will now also weaken the person who is being jumped on regardless of whether or not they are wearing a helmet.
If I manage to push someone over a railing, I want him to drop whatever the fuck he is holding. This primal need of man is adressed by this PR.
:cl:
tweak: weaken() makes you drop items again
/:cl:
> Makes weaken() drop items carried in hands again.

- code/game/objects/items/oddities.dm
The "Old newspaper" oddity can now be used to zoom out a couple tiles, similar to a binocular or scope, because there's comically obvious holes for spying through inside.
Oddities make even less sense now.
:cl:
add: The "Old newspaper" oddity can now be used to zoom out a couple tiles.
/:cl:
> Makes an oddity more odd

- code/game/objects/effects/chem/chemsmoke.dm
- code/modules/mob/living/carbon/breathe.dm
This PR changes the way chemsmoke is handled. Previously, reagents would only get transferred to a mob if they touched one of the visible gas clouds created by a chem reaction. And This didn't work like 90% of the time. Now, if you are inside the area of the smoke reaction when it occurs and you're not wearing a gas mask/or active internals, 5 units of whatever was in the smoke will be transferred to your bloodstream, and 5 units will be ingested (These amounts are the same as the ones you could take in from one visible smoke cloud). 
Theoretically this means that you could take in twice the amount of chems from a single smoke reaction since you can still breathe in the smoke clouds, but that only happens extremely rarely, so I hope that's fine.
Also fixes a bug where the actually visible …
> Chemsmoke fix (not really)

- code/datums/uplink/devices and tools.dm
- code/game/objects/items/weapons/storage/uplink_kits.dm
- code/modules/clothing/spacesuits/syndi.dm
Simply adds the basic syndicate space suit to the traitor uplink. Sprites aren't mine, credit to whoever the original artist is.
It's a less armoured but more maneuverable and aesthetically pleasing alternative to the more commonly seen  Merc Voidsuit. It's also not used anywhere else, so why not?
:cl:
tweak: Adds the syndicate space suit to the uplink for the price of 3 TC.
/:cl:
> Adds the Syndie Space Suit to the uplink

- cev_eris.dme
- code/modules/core_implant/cruciform/machinery/armaments.dm
- code/modules/core_implant/cruciform/machinery/eotp.dm
- code/modules/core_implant/cruciform/rituals/priest.dm
- nano/templates/eopt.tmpl
refactors the code so the priest can pick any disk when an armenent miracle has occured and makes it so only 1 oddity miracle may occure
EDIT: smh got bamboozeld and rewrote the whole thing.
Priests gain a new litany that can be used near the EOPT to summon armenents. This new system simply spawns a type path so its relativly flexible exacly what you spawn, from items to mobs. and with the on_purchase proc you could implement some other effects(epic buffs or smth)
lazy nano UI included
being able to pick the disk makes it much more interesting, also getting 7 "rare badges" is dumb
:cl:
add: priests may use new litany to summon items from the EOTP
tweak: Only 1 High Inquisitor's Seal may be recieved from the EOTP
/:cl:
> rework how EOTP armaments work+ only 1 High Inquisitor's Seal spawn

- maps/CEVEris/_CEV_Eris.dmm
^screw this thing
It isn't
:cl:
fix: The Maintenance Control Hatch button in perma now opens that shutter instead of the (nonexistant) one at the firing range
/:cl:
> Fixes the Shutter near perma

- code/datums/uplink/hardsuit_modules.dm
- code/modules/clothing/spacesuits/rig/modules/utility.dm
- code/modules/clothing/spacesuits/rig/suits/combat.dm
- code/modules/clothing/spacesuits/rig/suits/light.dm
- code/modules/clothing/spacesuits/rig/suits/merc.dm
- code/modules/clothing/spacesuits/rig/suits/station.dm
- code/modules/research/designs/rigmodules.dm
- code/modules/trade/datums/trade_stations_presets/1-common/suit_up.dm
- code/modules/trade/datums/trade_stations_presets/2-uncommon/rigprovider.dm
Fully reworks the rig chemical injectors , most notable changes
1)You can now insert/remove beakers
2)You can adjust the injection amount (and saboutage if you set it to 0)
3)Combat injectors now have hyperzine , nutriment , tricordazine and tramadol
4)Medical injectors now have dylovene , bicardine , kelotane , spaceacilin and inaprovaline
5)Modular injectors no longer start full , only their subtypes (RND printing injectors won't start full now)
6)Normal injector can fit 5 beakers , subtypes can fit 6
7)Uplink modular injector price changed from 6 to 3 tc(no longer starts full)
They suck in general , and were hard to refill , and use in general , now this  makes them more flexible for players and to their needs , especially paramedics which can finnaly fill theirs with upgraded chems. …
> RIG Chem Dispenser rework.

- code/modules/mob/living/life.dm
- code/modules/mob/living/simple_animal/spider_core.dm
Fixes some unintended behavior in the living Life() proc where player-controlled nonhuman mobs would sleep, preventing environmental effects among others from being applied. So, carrion spider cores will no longer be able to survive indefinitely in space. Also, the spider core would die in roughly 60 seconds in a vacuum if it was at 100%., which is about the time it takes to create a new body. The timer was changed to 66 seconds.
Removes abusable behavior.
:cl:
tweak: added mind check to living Life() sleep check logic
balance: slightly extends the generate_body() timer to 66 seconds from 60
/:cl:
> Carrion bug fix

- code/modules/reagents/recipes.dm
You were right I was wrong. The Iron recipe wiped out the extra uranium, by putting it inside you. You couldnt help but get irradiated while doing that recipe. Even when wearing a hazard void I was still getting radiation. No idea how or what was happening but it was painful.
No need for constant rad chems to do this, and its less tedious as well
:cl:
fix: made a better uranium solidification recipe
/:cl:
> Uranium Solidification Changes

- code/modules/core_implant/cruciform/machinery/eotp.dm
- code/modules/core_implant/cruciform/rituals/priest.dm
The EOTP's observation limit was raised by 125% (from 800 to 1800)
As a result, maximum power gain rate has been doubled.
To offset this, now it requires 20% more power to release a miracle:
This means a maximum of 66% increase to miracles.
This however also means a slower roundstart power gain rate.
The logic for calculating observation was changed, up until now a bug prevented observation to ever reach maximum, as periodically it would lose 20 observation from updating.
Observation can now increase without limit, but its effects are capped at the maximum instead, allowing lategame church to secure observation gain more reliably.
The armament litany can now be casted by acolytes.
EOTP logic improvement, buffs miracle rate, increases incentive to build obelisks and cruciform the crew. …
> EOTP adjustment

- code/modules/mob/living/simple_animal/borer/borer_powers.dm
Presently, attempting to infest a host with biograde vision active will cause it to deactivate, and then return, blocking infestation when it shouldn't - it even happens after the message for wiggling into the host's ear, which can cause a lot of confusion for both borers who don't know why they're not in the host, and humans who think they're infested when they're not.
Closes #7115 
The proc shouldn't stop midway through after removing biograde vision's effects.
:cl:
fix: having biograde vision active as a borer no longer prevents infesting a host.
/:cl:
> Removes bad return in borer_powers.dm

- code/controllers/subsystems/trade.dm
Changes the export scanner shown price from a fraction of the value to the actual value
People dont know it only shows 60% of the value. It doesnt say suggested price it just says export price. This makes it the actual export price.
:cl:
tweak: Fixes export scanners shown value
/:cl:
> Export scanner

- code/game/objects/items/weapons/tools/hammer.dm
The damage and armour piercing values of six hammers have been modified, said hammers are listed below
- Makeshift Mace
- Mace
- Home Wrecker
- Powered Hammer
- Charge Hammer
- One Star Powered Hammer
In all cases except for the Home Wrecker this was a buff, the Home Wreckers AP was nerfed slightly to bring it in line with the others.
I've attempted to divide their damage into tiers depending on their quality and size.
I've additionally attached a [worksheet](https://docs.google.com/spreadsheets/d/1YE5jRkzpAWpIUOUxmQ_8p7RxcJvaszR7gK6RsMOsQPM/edit?usp=sharing) which shows the maximum damage that can be achieved with each choice, raw and modded.
This is an attempt to make hammer/blunt type weapons more pleasing to use for players, as well as presenting them as an alternative armour piercing …
> QoL Changes so hammers are viable alt melee

- code/modules/reagents/machinery/chem_dispenser.dm
Adds tiers to the chem dispenser , making upgrading it now worth it
tier 2 parts  - inaprov , dylo kelo
3 - tricord , spaceaccilin , dermaline
4 - blattedin , polystem
5 - carpotoxin , bicaridine
6  - meralyne , nanites
All machinery should in generally have upgrades + gives a good reason for moebius to do expeditions , for those sweet T5 one-star parts
:cl:
balance: Upgrading the chem dispenser now provides it with more reagent options.
/:cl:
> Adds upgrade tiers to chem dispensers

- code/game/objects/structures/catwalk.dm
Catwalks will no longer freak out when located on exoplanet/asteroid tiles.
Fixes cool.
:cl:
fix: runtime in catwalk.dm
/:cl:
> Fix runtime in catwalk.dm

- code/modules/mob/mob_helpers.dm
Relatively rare (540 cases in over two years) runtime, that occurs when a mouse crosses a trap before game is fully initialized.
Fixes cool.
:cl:
fix: runtime in mob_helpers.dm
/:cl:
> Fix runtime in mob_helpers.dm

- code/modules/mob/observer/ghost/ghost.dm
New "Follow player" verb that is similar to "Follow mob", but only shows mobs that have a `ckey` assigned to them, so user don't have to scroll trough a ton of roaches, monkeys and other mobs to find a fellow human.
Removed "Follow" verb from ghost menu, now it's only visible on right click, as it should.
When called from ghost menu, it showed a list of every mob and object in view, which is pretty useless and only used by mistake.
QoL is good.
:cl:
add: "follow player" verb to ghost panel
tweak: "follow" verb no longer visible in ghost panel
/:cl:
> Add "Follow player" verb

- code/modules/economy/cash.dm
Cash bundle that vagabonds receive on spawn always have appearance of a single banknote, regardless of how much money bundle actually contains. Not anymore.
Also changes bundle name and description if it contains only coins or a single coin.
Fixes cool.
:cl:
fix: icon of cash bundle that vagabonds spawn with
/:cl:
> Fix vagabond's cash bundle

- code/game/objects/items.dm
- code/game/objects/items/weapons/storage/uplink_kits.dm
- code/modules/clothing/chameleon.dm
- nano/templates/chameleon.tmpl
https://github.com/discordia-space/CEV-Eris/pull/7072
but doesn't cause warnings anymore (the horror!)
now ~~marginally~~ much less convoluted as well, thanks to Kirov.
Also cleans up some chameleon clothing items in general and removed some things you can't disguise chameleon items as.
ask nestor
:cl:
add: added the ability to quickly switch between different loadouts for chameleon clothes if the chameleon jumpsuit is worn.
add: Added the chameleon satchel
fix: chameleon items will no longer block other clothing sprites from appearing when they weren't supposed to
tweak: chameleon clothes are now made of plastic instead of bioatter
tweak: removed some things you can't disguise chameleon items as.
/:cl:
> Chameleon clothing update, this time without warnings

- code/modules/multiz/movement.dm
Players may no longer FALL ontop of non-climbable structures (Windows , Walls) , they will still however fall on climbalbe sturctures ( Low-walls , tables)
No more wall clipping
:cl:
balance: Mobs can no longer fall into walls or any fully dense structres.
/:cl:
> Ruins z-levels(You can no longer fall on non-climbable structures)

- code/game/machinery/vending.dm
- code/modules/economy/economy_misc.dm
- maps/CEVEris/_CEV_Eris.dmm
Converts some of the on-ship vending machines into custom ones 
- medbay's supply vendor (products remain free and requiring access)
- the MiniMed in medbay lobby
- the NeoTheology Theo-Mat
Also replaces the drink showcase minifridge with a vending machine of identical appearance.
The medbay vendors can only be supplied with medical equipment and chem containers, while the drink showcase continues to only hold items it used to be able to, meaning glasses, drinks and condiments.
The NT vending machine is not locked and can hold any item. It is now only able to serve disciplines however.
The medbay vending machines will experience a large QoL improvement, allowing the inner one to retain use through restocks as the round goes on, and the lobby one to distribute chems to the crew, while …
> Vending machine tweaks

- code/modules/cargo/packs.dm
- code/modules/clothing/spacesuits/rig/rig.dm
- code/modules/clothing/spacesuits/rig/suits/combat.dm
- code/modules/clothing/spacesuits/rig/suits/light.dm
- code/modules/clothing/spacesuits/rig/suits/merc.dm
- code/modules/clothing/spacesuits/rig/suits/station.dm
- code/modules/mechs/equipment/utility.dm
- code/modules/research/designs/mechs2/exosuits_components.dm
- code/modules/research/nodes/robotics.dm
- Adds storage bags to each type of RIG in the game by default
- Increases medical/EVA/SCI RIG melee/ballistic armour by 10 because 10% proj resist on a light RIG seemed a bit low (light, unarmored 'punk' themed jackets are 20% resist.
- Buffs the mech flashlight, adds printable mech drill pieces to the exofab and makes the orderable cargo Ripley more viable by adding required parts.
- (QoL) adds a diagnosis unit to the mechfab exosuit tab
RIGs don't seem worth it currently if they don't come with a storage module, nobody wants to haul a bag in one hand everywhere they go or spend 30 minutes begging cargo/IH for a storage bag. Paramedic/Expedition/Light or even techno RIGs are very rarely seen anyway. Buffs a few under armored RIGs (light-EVA, medical and Science) to be more useful.
Mech …
> Adds a storage bag to every RIG, minor RIG buffs, minor exosuit buffs

- code/game/objects/effects/roaches.dm
Roach eggs are now Easter eggs.
Approximately a hundred of roach eggs will spawn in maints, each containing 15 units of some chemical.
Possible chemicals: bicaridine, hyperzine, dermaline, dexalin plus, tramadol, oxycodone, alkysine, peridaxon.
Hatch time now x10, to prevent maints being flooded with roaches before eggs could be collected.
Easter themed stuff for Easter.
:cl:
add: limited edition colored Easter (roach) eggs with gamer chemicals
/:cl:
> Add Easter eggs

- code/modules/hydroponics/grown.dm
Adds a check for existing invisible soil when planting a seed with TRAIT_SPREAD > 0.
Removes exploitable behavior from the game.
:cl:
fix: added check for existing invisible soil when planting a seed with TRAIT_SPREAD > 0
/:cl:
> Plant stacking fix

- code/game/machinery/doors/firedoor.dm
Removes the alert to confirm opening a firedoor
We are not bay , a HRP server that alerts people that they die when they wanna go in disposals bin. It also fucked me over in combat.
:cl:
del: Removed firework pop-up open alert.
/:cl:
> Removes firedoor open alarm

- code/modules/clothing/head/armor.dm
- code/modules/clothing/suits/armor.dm
Technomancer armor no longer wrecks style, however its armour rating has been changed to 30 melle , 30 bullet , 10 energy  , 50 bomb , 80 rad. (from  35 melle , 30 bullet , 40 energy , 20 bomb , 30 rad)
Imagine being forced to wear vagabond attire , while IH inspector gets max style with armor ontop.
:cl:
balance: Techomancer armour ratings tweaked to be more usefull to their job ,  technomaner armor style loss removed.
/:cl:
> Style buffs (Fixes technomancer attire being horrid)

- code/modules/surgery/autodoc.dm
Autodoc no longer tries to fulfill non-existing surgeries if the picked option is used.
Bug fix, excel buff,  IH buff , moebius buff , everyone buff.
Someone said that the more damaged you are , the faster the autodoc works , wrong , its the opposite.
:cl:
fix: Fixed autodoc trying to complete unselected surgery steps
/:cl:
> Autodoc no longer pranks you(Fixes autodoc)

- code/game/machinery/deployable.dm
- code/game/objects/structures/low_wall.dm
- code/modules/tables/interactions.dm
Cover no longer applies if the target is not near any cover
>Prepare to do epic valkyrie shot  1-2 tiles behind a low-wall using the scope
>The low wall blocks the shot, even if its aimed at chest  and if the target is not near any cover, because the target zone gets changed
:cl:
balance: Cover now only works if the target is adjacent to it
/:cl:
> Cover no longer works if the target is not near it

- code/modules/mechs/premade/combat.dm
- code/modules/mechs/premade/heavy.dm
Increases turn rate and the move delay on the heavy legs and combat legs of mechs
Someone (cough cough the guy doing Mech PR's lately) has been overbuffing mechs, my changes were within the idea of them standing at a reasonable balance level , at which they currently are not.  Mechs are way too fast and way too powerfull as is , especially with the now HUMUNGOUS module health they get since the (cough cough , mech pr guy) bufffed them.
:cl:
balance: Heavy mech legs are now slower and turn twice as slow.
balance : Combat mech legs are now slower and turn slower
/:cl:
> Mech nerfs ( Mechs heavy legs and combat legs are now slower)

- code/modules/mechs/mech_damage.dm
Fixes a few major issues with  mech damage dealing
1)Fixes the mech damage being distributed , by random picking
2)Fixes mechs not taking damage at all sometimes
3)Fixes aiming for the mouth /  groin attacking the body instead of head , and legs respectively.
4)Fixes attack zones not being translated for mechs
The mech nerf we all wanted
:cl:
fix: Bullets now hit mechs where you aimed them
fix: Mechs no longer magically soak up bullets
/:cl:
> Absolutely ruins mechs (Fixes mech targetting , and mech damage dealing)

- code/game/objects/items/weapons/grenades/frag.dm
- code/game/objects/items/weapons/grenades/grenade.dm
Frag nades now create a 2-tile radius explosion around then
Frag nades also completly obliterate anyone thats sitting above them now.
Frag nades thrown from above now will bounce to the side of someone's head.
People can stand ontop and suffer nothing. 
:cl:
balance : Frag nades now create a very weak explosion around themselves when detonating
balance : frag nades now will obliterate anyone standing ontop
balance: Grenades that are thrown above people will bounce to the side.
/:cl:
> Buffs fragmentation nades(Fragmentation nades now create a weak explosion around them, and bounce off when thrown from above)

- code/modules/mob/mob.dm
Returns Weaken() to not being a hardstun , we have Paralyse() for that you fucking cunts that don't adhere to STANDARDS
PR'ed this a long time ago and was accepted , and then reverted in le funny RTM combat update.
TRIPPING ON PLATING WAS NEVER INTENDED TO LOCK YOU IN PLACE FOR A WHOPPING 6 SECONDS, Or geting crushed by a door.. or anything that weakened. 
:cl:
balance: You can once again , move while Weakened()
/:cl:
> Once again , removes hardstun from Weaken()

- code/datums/craft/gun_parts.dm
- code/modules/scrap/scrap.dm
Gun frames that spawn in trash piles or maintenance will come with part(s) preinstalled. One part is guaranteed and the second has a 50% of spawning. Additionally, using a screwdriver on the frame will let you take out any parts currently installed.
Reduces randomness in gun part hunting.
:cl:
tweak: gun parts can be removed from frames with a screwdriver
balance: maint/trash gun frames spawn with 1-2 parts installed
/:cl:
> Gun frames in trash/maintenance spawn with 1-2 parts installed

- code/__HELPERS/turfs.dm
Makes burrowns no longer spawn on tiles with cables or pipes
Shouldn't have vital pipes or cables ruined round-start cause funny burrow RNG
:cl:
balance: Burrows can no longer spawn ontop of cables / pipes
/:cl:
> Burrows no longer spawn on tiles with cables or pipes

- code/game/machinery/deployable.dm
Deployable barriers stopped being an obstacle with implementation of diving/sliding PR, which is clearly unintended change.
UPD: Players with "Parkour" perk still able to jump over barricades, because why not.
Fixes cool.
:cl:
fix: no longer can jump over security barrier
/:cl:
> Fix jumping over deployable barriers

- code/modules/mob/living/carbon/human/inventory.dm
Previously `bag_equip()` proc (Shift+B hotkey) did not take into account the storage type, letting people to use backpacks and duffel bags while those are equipped, which is not an intended behavior.
Also it works with RIGs now.
Fixes cool.
:cl:
fix: Shift+B hotkey interactions with various storage types
/:cl:
> Fix bag_equip() hotkey

- code/modules/mob/living/living.dm
Rewrote get_contents() so it takes into account items in suit pockets and rig storage.
Fixes cool.
:cl:
fix: oddities and steal targets not being accounted for if placed in RIG or suit pockets
/:cl:
> Fix get_contents() ignoring some storages

- code/datums/perks/oddity.dm
What it says on the tin, robots and FBPs no longer get toxins from stinky vagabonds.
Also makes gasmasks actually work against that perk.
Fixes cool.
:cl:
fix: toxic revenger affecting robots and fbp
/:cl:
> Fix toxic revenger affecting robots and fbp

- code/game/objects/items/weapons/cigs_lighters.dm
If player's cigarette goes out near an ashtray - they will use it, instead of dropping cigarette on the floor.
Muh roleplay.
:cl:
add: ashtrays being used automatically
/:cl:
> Add automatic use of ashtrays

- code/game/machinery/camera/camera.dm
Taping up cameras now uses your duct tape
Should have a cost.
:cl:
balance: Duct taping a camera now costs 10.5 units of duct tape.
/:cl:
> Taping cameras now uses up tape

- code/modules/mob/living/living.dm
This reverts commit 1e8e63e46911b64f17e46dcaf8b8eece79aaa3ea.
Pretty big bug around wiping players inventories and this is the suspected cause.
> Revert "Fix get_contents() ignoring some storages (#7208)"

- code/modules/clothing/glasses/hud.dm
Simply blacklists the spawn of the broken broke huds form spawning
Firstly there is absolutely no reason for this to be spawning, secondly it will screw up loot and make all these items more common, thirdly, this is possibly a direct violation to contributing guidelines, I should try reading them.
https://wiki.cev-eris.com/Content_GuidelinesEn
:cl:
fix: Broken, broken huds no longer spawn.
/:cl:
> Blacklists broken huds form spawning

- code/modules/clothing/spacesuits/rig/modules/utility.dm
Dobles the beakers inside the combat rig to be completable with a normal medical injector
Makes medical rig injector able to inject people
Fixes a small indexing issue with pre-filled rig injectors and dispensers 
Adds different names for the rig dispensers and injector so in its list you can more at a glance tell what one your using and injecting
Combat injectors for rigs in its current state is a weaker medical, so its always a no brainer to get a medical one at this time then use a combat one, thats a bit silly it should have ups and downs to the medical one imo
Fixes are good so the medical rig injecter injects
:cl:
balance: combat dispenser now holds 12 beakers rather then 6!  - For Rigs
fix: Fixes medical injectors not injecting - For rigs
fix: Fixes all dispensers and chem …
> Corrects some rig dispender things

- code/__DEFINES/mobs.dm
- code/modules/mob/mob_grab.dm
This PR makes neck grabs take no time to upgrade to and aggressive grabs take time to upgrade to again.
Aggressive grabs are the first stage of grab with combat use.
Balance change here due to popular command by grab in combat players.
balance: Aggressive Grab is now instant and Neck Grab now has a timer again.
/:cl:
> now aggressive grabs take no time again and neck grabs take time

- code/modules/mining/drilling/deep_drill.dm
* Mining drill will now mine ores randomly instead of digging out vast amounts of hematite and almost nothing of the other minerals
* Mining drill will now display its content upon examine, just like the ore box.
* Mining drill cannot be deconstructed anymore to prevent health abuse
:cl: Hyperio
tweak: Mining drill will now mine ores randomly instead of digging out vast amounts of hematite and almost nothing of the other minerals
add: Mining drill will now display its content upon examine, just like the ore box
tweak: Mining drill cannot be deconstructed anymore to prevent health abuse
/:cl:
> Mining Overhaul Part 2.4

- code/modules/biomatter_manipulation/bioreactor/biotank.dm
Removes the bottle neck on biomatter production. This will make the bottleneck the amount of solidifiers you have. Goes with the price nerf.
Currently Biomatter has alot of exploits. Those are closed by the price nerf. This removed the CBT of waiting for 80 tics for the tank to fill up and lets you move on with the next part of your job.
:cl:
tweak: makes the biotank spit out biomatter faster
/:cl:
> Biotank bottleneck removal

- code/modules/materials/material_sheets.dm
Halves the price of biomatter letting the minigame be faster and removing trade exploits. ouches no longer cost 400 credits to make and biomatter production is faster while still requiring setup time to reach full production capacity
Currently Biomatter has alot of exploits. Those are closed by the price nerf. This removed the CBT of waiting for 80 tics for the tank to fill up and lets you move on with the next part of your job.
:cl:
tweak: halved biomatter price
/:cl:
> Biomatter price update

- code/__DEFINES/_planes+layers.dm
- code/modules/mob/living/carbon/superior_animal/defense.dm
- code/modules/mob/living/carbon/superior_animal/roach/roach.dm
Makes dead roaches always display under stunned roaches, with conscious roaches always being on top.
Pretty sure dead roaches not meant to be on top, that's just inconvenient.
:cl:
fix: live roaches sometimes displaying below dead roaches
/:cl:
> Fix roach layers

- code/game/machinery/recycle_vendor.dm
Makes the recycle vendor when giving you payments log what was scrapped for guild to see what items are being recycled when not around, or the IH when investigating and need to see if someone sold their weapon in that.
Removes an exploit allowing of destruction of nested items in bags or boxes via selling them full in the recycle vendor
Investigation RP shouldnt lead to a cold trail do to someone selling their bag inside a fancy vender
Exploits are bad and we shouldnt allow such easy destruction of tons of items all in 3 clicks
:cl:
balance: recycle vendor now logs what is buy'ed
fix: Fixed mass selling stored items recycle vendor, note this didnt give you wealth for items inside nested items
/:cl:
> Adds sanity and logging to the recycle vendor

- code/modules/mob/observer/ghost/ghost.dm
New verb in "ghost" tab, that makes player's ghost (in)visible when activated.
Quite convenient for making screenshots, and if you don't want your ghost to cover sprite of whoever you're following.
:cl:
add: toggle self vision verb
/:cl:
> Add "Toggle Self Vision" verb

- code/modules/projectiles/guns/energy/laser.dm
- code/modules/projectiles/guns/projectile/automatic/c20r.dm
- code/modules/projectiles/guns/projectile/battle_rifle/type47.dm
- code/modules/projectiles/guns/projectile/pistol/selfload.dm
- code/modules/research/xenoarchaeology/finds/finds_eguns.dm
Fixed:
1)Cog missing One Star serials
2)Moebius C-20 ripoff having Syndicate serials, instead of Moebius Laboratories
3)Moebius Clarissa ripoff having Syndicate serials, instead of Moebius Laboratories
4)Type XLVII having Oberth Republic serials instead of One Star
5)Alien artifact guns having various serials
Fixes cool.
:cl:
fix: fixed bunch of incorrect serial numbers
/:cl:
> Fix some incorrect serial numbers

- code/game/objects/items/weapons/mop.dm
Apparently mop had a "sweep" option, which wouldn't clean tiles with wires or pipes, due to changes in #7199.
Credit goes to @Trilbyspaceclone.
Fixes cool.
:cl:
fix: mop sweep
/:cl:
> Fix mop sweeping

- code/game/objects/items/devices/radio/encryptionkey.dm
Captain and FO have access to all frequencies, but most have to be enabled manually, which is quite annoying.
This PR makes all channels enabled by default.
QoL change.
:cl:
tweak: captain and fo start with all channel in their headsets enabled by default
/:cl:
> Tweak captain and FO headsets

- code/game/objects/objs.dm
- code/modules/projectiles/guns/energy.dm
Clicking with a cell on egun, that already have a cell inside, now replaces the cell.
Clicking Z with egun in hand will eject the cell, if it's not internal and have no charge for more shots.
QoL functionality.
:cl:
add: more egun and energy cell interactions
/:cl:
> Add more egun and energy cell interactions

- code/game/objects/items/bodybag.dm
- code/game/objects/structures/crates_lockers/closets.dm
Removed examine() line that body bags inherited from closets(body bags are actually closets, yeah), and that makes little sense for a body bag.
Before:
After:
Fixes cool.
:cl:
fix: weirdness in body bag examine()
/:cl:
> Tweak body bag's examine()

- code/modules/mob/observer/ghost/ghost.dm
When player uses "Ghost" verb, they lack buttons like on the screenshot:
Also, using "Re-enter Corpse" would always remove those buttons, even if player can't return to body.
Fixes cool.
:cl:
fix: ghosted players missing UI buttons
fix: re-enter corpse verb breaking UI
/:cl:
> Fix "ghost" verbs breaking UI sometimes

- code/game/objects/structures/cyberplants.dm
What it says on the tin. Colors automatically toned down to prevent cringe.
Mildly useful functionality.
:cl:
add: flourescent color customization
/:cl:
> Add cyberplant colors customization 

- code/modules/mob/living/carbon/superior_animal/superior_animal.dm
Currently bullets flying past hostile mobs won't connect, unless mob have been clicked at, which is pretty dumb and unfun.
Projectile is not guaranteed to hit, bullet's just won't ignore mobs completely.
https://user-images.githubusercontent.com/65828539/173418691-93ac4157-4130-402e-93a8-3c2583968786.mp4
https://user-images.githubusercontent.com/65828539/173419495-0ffbef55-e0ae-4d97-b103-613f98c065c5.mp4
Fixes cool.
:cl:
fix: hostile mobs ignoring non-targeted projectiles
/:cl:
> Fix hostile mobs ignoring non-targeted projectiles

- code/__DEFINES/mobs.dm
- code/game/machinery/cryopod.dm
- code/game/machinery/excelsior/ex_teleporter.dm
- code/game/objects/structures/crates_lockers/closets/coffin.dm
- code/game/objects/structures/morgue.dm
- code/modules/biomatter_manipulation/bioreactor/platform.dm
- code/modules/mob/living/silicon/ai/latejoin.dm
- code/modules/mob/observer/ghost/ghost.dm
Drone respawn timer - 5 minutes.
Human respawn timer reduction:
Went in cryo healthy - 25 minutes.
Went in cryo wounded - 20 minutes.
Put in the morgue - 15 minutes.
Dissolved in bioreactor - 15 minutes.
Stolen by commies - 15 minutes.
Spaced in a coffin - 25 minutes.
Keeping players out of the game benefits literally nobody, currently players are unlikely to stick around and wait for long respawn timer.
:cl:
tweak: increased respawn timer reduction from most sources
/:cl:
> Buff respawn timer reduction

- code/__DEFINES/mobs.dm
Increased time when player character could be revived from 5 to 15 minutes.
Being brought back from the dead feels good, staying permanently dead is not so much.
Shocking, but nerfing resuscitator didn't force people to "just play NT lol".
:cl:
tweak: resuscitator could be used 15 minutes after person's death
/:cl:
> Increase resuscitator timer

- code/game/objects/items/oddities.dm
Adds an oddity that:
1. Requires adept stats of Cognition to realize its effect.
2. Is a moderate gamble between risk and reward.
3. Is a paper scrap with an equation that when solved properly may equate to a bear. (And rarely a bounty of other oddities)
4. Has no perk attached.
A functional oddity, with a small gambling and danger factors.
:cl:
add: A new oddity!
/:cl:
> Adds another functional oddity

- code/datums/craft/recipes/guns.dm
- code/datums/craft/recipes/weapon.dm
- code/modules/projectiles/ammunition/bullets.dm
- code/modules/projectiles/guns/energy/poweredcrossbow.dm
- code/modules/projectiles/projectile/bullettypes.dm
This PR updates the merged Powered Crossbow with some QoL feedback suggestions, buffs, and observations made after using the crossbow last launch.
Bolt projectile sprite was changed to something more fitting:
Community feedback after testing is good indicator of what players want.
:cl:
tweak: Recipe for crossbow bolts moved to guns section, right under powered crossbow.
tweak: Crossbow recipe edited slightly to include glass, representing a poor scope.
tweak: Crossbow has a minor zoom factor now, 3 spaces when used.
tweak: Bolts now embed on hit and can be extracted from kills in bolt form to be used again. Prior to this they turned into metal rods on hits.
tweak: Embedded bolts are sharp, dealing pain, brute and toxin like normal shrapnel if you run without removing them. They can be …
> Powered Crossbow Update - After Feedback and Live Tests

- maps/CEVEris/_CEV_Eris.dmm
Added ~20 (I lost count) space heaters to atmospherics, substations and throughout the maintenance tunnels, per jannie-with-long-nickname reqiest.
Benzin roach fires is a lot of trouble, and high temperature kills fast, meanwhile ship only have three (3) space heaters and coolant is nerfed to hell.
:cl:
add: more space heaters to maintenance, substations and atmos
/:cl:
> Add more space heaters

- maps/CEVEris/_CEV_Eris.dmm
- maps/CEVEris/_Eris_areas.dm
Honestly I made like half a dozen club remaps or something. This one makes it truly not shit, and it involved about ten hours or work with real time community feedback (read: people yelling at me to do this and that).
Topside club got a significant facelift, with bar counter closer to the hallway like other ss13 servers, which allows people to quickly see if club is staffed and they can quickly grab a drink or a snack without walking for ages. The shitcloset with the lathe and hydro trays got split up, with the hydro portion upstairs right above kitchen (no more walking between z levels to grow plants or unwrench the trays), and it features an agro closet with the necessary tools and a seed converter without enduring wirecutter CBT with club low starting BIO. Manager room is prettier, …
> Club Remap, and Theater Light

- code/modules/mechs/equipment/utility.dm
Mekas could pick up ores from the floor only via the drill module, meaning that mechas can't pick up ores if it's mined via a plasma cutter or dropped by golems.
This PR adds interaction of mech clamp with the turf.
I've been asked to make this, so probably someone actually uses mechs for mining.
:cl:
add: mechs picking up ore from the floor with mounted clamp
/:cl:
> Add mechs picking up ore from the floor

- code/__DEFINES/research.dm
- code/modules/integrated_electronics/core/debugger.dm
Decreases the amount of plastic, glass and steel needed for making(and deconstucting) a debugger in integrated electronics
Sane values in case somewhere to find or want to make these should be gained
:cl:
fix: Debugging tool for integrated electronics now has saner values of materials
fix: Printing integrated electronics no longer doups materals
/:cl:
> Debugger saner values

- code/modules/clothing/spacesuits/void/excelsior.dm
- code/modules/clothing/spacesuits/void/station.dm
some small buffs to the Combat Oriented Void suits to make them more viable compared to BP and Style Dodge
Some of the combat void suits (NT and Excel) felt underpowered compared to their competition with style dodge and full armor vests. so I gave them some small buffs to hopefully increase use of void suits and make them somewhat viable in combat once again.
suggested by BeadsJR
the excel and NT void were previously the exact same armor as the lowest tier of armor vest. so nobody would ever wear them. they should now be slightly better than that
:cl:
balance: small buffs to Excelsior and Neotheo Voidsuit to compete with basic armor vests
/:cl:
> Excelsior and Neotheo Voidsuit Buffs

- code/datums/outfits/jobs/guild.dm
- code/modules/client/preference_setup/loadout/lists/eyegear.dm
- code/modules/clothing/glasses/misc.dm
Gave the heads the opportunity to take in loadout glasses, with flash protection. Guild Merchant now has normal protective glasses in preloadout. I changed the name of ordinary glasses so that there would be no misunderstandings.
Fixes good. Protection from flashes for command stuff is also not bad.
:cl:
add: The ability to take glasses that protect from flash for heads of departments/
fix: Sunglasses desc.
/:cl:
> flash-protected sunglasses for head stuff and fix desc.

- code/__DEFINES/weapons.dm
- code/datums/datum_click_handlers.dm
- code/modules/projectiles/gun.dm
- code/modules/projectiles/guns/projectile/automatic.dm
- code/modules/projectiles/guns/projectile/automatic/ak47.dm
- code/modules/projectiles/guns/projectile/automatic/atreides.dm
- code/modules/projectiles/guns/projectile/automatic/c20r.dm
- code/modules/projectiles/guns/projectile/automatic/dallas.dm
- code/modules/projectiles/guns/projectile/automatic/drozd.dm
- code/modules/projectiles/guns/projectile/automatic/luty.dm
- code/modules/projectiles/guns/projectile/automatic/molly.dm
- code/modules/projectiles/guns/projectile/automatic/sol.dm
- code/modules/projectiles/guns/projectile/automatic/straylight.dm
- code/modules/projectiles/guns/projectile/automatic/sts35.dm
- code/modules/projectiles/guns/projectile/automatic/type17.dm
- code/modules/projectiles/guns/projectile/automatic/vintorez.dm
- code/modules/projectiles/guns/projectile/automatic/wintermute.dm
- code/modules/projectiles/guns/projectile/automatic/z8.dm
- code/modules/projectiles/guns/projectile/automatic/zoric.dm
- code/modules/projectiles/guns/projectile/battle_rifle/type47.dm
- code/modules/projectiles/guns/projectile/pistol/selfload.dm
- code/modules/projectiles/guns/projectile/pistol/type62.dm
- code/modules/projectiles/guns/projectile/pistol/type90.dm
- code/modules/projectiles/guns/projectile/shotgun/bojevic.dm
- code/modules/projectiles/guns/projectile/shotgun/bull.dm
Burst fire can no longer be stacked
Full auto's fire delay is now based on the shown value , and not on the guns burst_delay
Guns  are no longer hard-locked to the 4 second delay between attacks.The fire_delay is now properly applied
Bull no longer has 0 fire_delay (since you can insta-fire all shots with the new fix)
SEMI_AUTO_NODELAY changed to SEMI_AUTO_300 since it now has the same firerate as a 300 shot auto would.
Related video : https://cdn.discordapp.com/attachments/299262993617780737/1004766001642086540/2022-08-04_18-00-08.mp4
Any gun that would get lower than 4 MS fire delay would have its effects not applied , this made most pistols underwhelming even with upgrades meant to make them better.
Makes Semi-Auto properly apply its delay if its firerate is under 4 MS.
:cl:
fix: Burst …
> Yet another Major Gun Rebalance ( Fixes several issues with gun code,  full auto is now based off fire_delay)

- code/game/sound.dm
- code/modules/mob/living/say.dm
Fixes too many mobs being able to generate tts and ghosts not hearing tts.
Fixes cool.
:cl:
fix: ghost not hearing tts
fix: mice and other mobs having actual voice
/:cl:
> TTS hotfix

- code/modules/projectiles/guns/energy/plasma.dm
- code/modules/projectiles/guns/energy/stun.dm
- code/modules/projectiles/guns/projectile/automatic/c20r.dm
Brings the C20 into line with the standardised naming convention. Also clears up a misunderstanding about the C20r being a Moebius product.
I have a crippling phobia of inconsistencies and it is ruining my life.
:cl:
tweak: The C20 is now in line with the standardised naming convention. Moebius gun products are now abbrviated to "ML"
/:cl:
> Brings the C20 into line with naming convention. Abbreviates Moebius guns

- code/modules/mob/living/carbon/human/say.dm
Uncomments part of code, enables people to gag other people via covering mouth and some chems again, adds a little feedback to it.
https://user-images.githubusercontent.com/57810301/183472476-35b4f9cd-d0d8-49b9-8a08-c5313772a3cd.mp4
(I don't know why this fancy video isn't displaying properly but it shows that this fix is working)
(being silent after leaving grab is part of `silent` code, I dunno)
Fixes good
:cl:
fix: You can once more cover people mouths to make them shut up.
/:cl:
> Fixes covering mouth

- code/game/objects/items/weapons/storage/pouches.dm
This PR allows small and medium cells to fit in ammo pouches.
Energy guns are not favored at the moment and while you can carry engineering pouches for cells, they limit the ability to carry a mixed loadout while keeping the majority of your ammo in one place. This hopes to fix that.
:cl:
balance: Small and Medium cells now fit in ammo pouches.
/:cl:
> Adds the ability to put small and medium cells in ammo pouches.

- maps/CEVEris/_CEV_Eris.dmm
Put back fumo added by #7351 that was removed by #7367 because of git dark magic
:cl: Hyperio
fix: Fix fumo removal due to another map PR
/:cl:
> Put fumo plushy back on the dorms table

- code/game/objects/items.dm
- code/modules/reagents/reagents/dispenser.dm
Acid now takes into account all the worn clothing's armour value instead of just checking if the head , glasses or mask is unacidable and stopping all damage. Acid now takes into account bio armour , along with the unacidable var.
Less insta-kill potential
https://cdn.discordapp.com/attachments/299262993617780737/1007051785317396600/2022-08-11_01-03-13.mp4
:cl:
balance: Acid now takes into account all worn clothing
balance: Acid now melts clothing before dealing damage.
/:cl:
> Reworks how acid takes armor into account , acid damage now gets reduced by bio armour

- code/game/objects/items/weapons/storage/pouches.dm
- code/modules/projectiles/ammunition/magazines.dm
Title
Normal sized items should not fit in a pouch.
:cl:
balance: Ammo pouches can no longer hold ammo boxes and drum magazines.
/:cl:
> Fixes the ammo pouch being able to hold drum mags

- code/game/objects/effects/chem/chemsmoke.dm
Due to balance concerns, in https://github.com/discordia-space/CEV-Eris/pull/7087 I made chemsmoke lose some of its reagents when it transferred them to a mob, in order to prevent duping. This caused the visible smoke to lose its reagents and color due to the reagents being transferred to mobs beforehand. This is why blattedin farms no longer work properly.
By not removing reagents from the smoke when it is transferred to a mob, this problem is solved. And no, this is not a balance problem, SPCR . That's because it's handled the same way with reagents being transferred to containers or splashed. In fact, the blattedin farms are technically dupes as well.
Blattedin farms work again, and smoke now has the correct color again. People complained about blattedin farms not working anymore
:cl: …
> Fixes smoke related problems (blattedin farm fix)

- code/modules/surgery/robotic_damage.dm
- code/modules/surgery/surgery.dm
If you are on harm intent , you will not attempt to weld the target FBP and you won't stop other surgeries from being checked.
This doesn't apply to the owner ,the owner will always try to weld themselves.
This also fixes old surgery not being considered if there was a existing surgery step, even if the existing one was not possible.
Exploiters been having fun with it for too long.
:cl:
fix: FIxed hardsuits not being removeable from FBP's backs.
/:cl:
> Fixes FPB hardsuit gaming(Also revives old surgery by accident)

- code/modules/reagents/machinery/chem_dispenser.dm
What it says on the tin. Lemon juice is available in the dispensers.
Both dispensers had orange juice, lime juice and lemon lime juice, but not lemon, which you also cannot buy with guild so its growing only. It is only used for a couple of drinks that would otherwise be annoying to make. Lemon cake needs lemon juice, yes, but it also needs a whole lemon, so if you want that you still have to grow it.
:cl:
add: Added lemon Juice to soda and booze dispensers
/:cl:
> Adds Lemon Juice to Soda and Booze Dispensers

- code/modules/mob/living/carbon/human/life.dm
Currently, being in a vacuum with no suit doesn't cause the player to take any damage.
Fixes unintended change.
:cl:
fix: re-enables low pressure damage
/:cl:
> Re-enables low pressure damage

- code/modules/core_implant/cruciform/machinery/armaments.dm
Any disk brought through the EOTP is uncapped
NT Disks that come from EOTP shouldn't be capped for the simple fact that getting the required power level takes a huge amount of time.
I also see no balance reason to have them limited , material scarcity is already enough.
It also lets them sell as much medicine or pouches as they want , finnaly , player interaction.
:cl:
balance: NT-disks brought through the EOTP have unlimited license points
/:cl:
> All NT disks brought through the EOTP are uncapped

- code/datums/craft/crafting_items.dm
- code/datums/craft/recipes/guns.dm
1. changed gun assembly required gun parts 10 -> 5
2. changed makeshift AK and laser gun parts required 4 -> 3, makeshift smg 3 -> 2
3. changed recycle cost of gun parts 1.2 -> 5
First, the gun part recyle part. Before, with Omni's initial implementation of the crafting station, gun part crafting was rng. with 5 plasteel, you could make 0-2+ gun parts, so to avoid plasteel multiplication the recycle cost was lowered to 1.2. Kirov fixed and changed it, so the cost is back up to 5 since 5 plasteel will only make 1 single gun part, and this way you can actually recycle makeshift guns found or crafted into other guns or plasteel not at a great loss.
Then, the gun assembly changes. As I said, Kirov made it so you can only craft 1 gun part per 5 plasteel instead of RNG. shame that with this …
> Tweaks Gun Part Cost and Amounts

- code/controllers/subsystems/inactivity.dm
- code/modules/client/client procs.dm
The asset update removed the duration check from the is_afk very , causing it to kick everyone since we had no config for kick_time
I made a shitty fix because i was super tired(and had no idea inactivity was used for something else)
This properly fixes the problem
:cl:
fix: Fixed inactivity properly
/:cl:
> Fixes inactivity proper

- code/modules/recycling/disposal.dm
Fixes trunks accessing bins that is never linked
fixes the issue at https://github.com/discordia-space/CEV-Eris/pull/7406
> stops disposal from accessing null

- code/modules/projectiles/guns/energy/rapidcrossbow.dm
Minor Balance change to RXB 
- Damage lowered from 55 > 44
- Penetration lowered from 30 > 20
- Chargecost increased from 50 >100
Community feedback was valid for balance.
Acts more like a six shooter now with a basic cell.
:cl:
balance: RXB damage now 44 instead of 55
balance: RXB ap now 27 instead of 30
balance: RXB charge cost now 100 instead of 50
/:cl:
> BalanceHotfix for Rapid Crossbow (RXB)

- code/game/objects/items/weapons/design_disks/NeoTheology.dm
- code/modules/core_implant/cruciform/machinery/armaments.dm
Bruh
Reverts #7409 #7397 as all it did was just make NT disks unusable. and makes the core disks themselves infinite like that PR intended to do. 
NT can actually use thier disks now
:cl:
fix: NT can use thier disks now
/:cl:
> Proper Armament Hotfix

- code/__DEFINES/components.dm
- code/game/objects/items/oddities.dm
- code/modules/mob/living/simple_animal/hostile/stranger.dm
- code/modules/sanity/sanity_mob.dm
Gives the stranger's plasma gun the properties of an oddity, along with randomizing the single stat on the gun on oddity use+fixes the issues with the broken necklace's description, which led to two different descriptions being documented on it, along with adding this feature to the stranger's plasma gun.
The randomization required the creation of a define, if this is too much, i can replace the single stat randomization for 3 stats that are affected by entropy the same way as currently.
Honestly, it makes the stranger more interesting in terms of loot.
:cl:
add: Stranger's gun has oddity properties and randomizes said properties.
fix: broken necklace's description.
/:cl:
> Stranger gun update+Necklace fix

- code/datums/datum_hud.dm
- code/game/gamemodes/endgame/supermatter_cascade/universe.dm
- code/game/machinery/flasher.dm
- code/game/objects/items/devices/flash.dm
- code/game/objects/items/devices/lighting/toggleable/flashlight.dm
- code/game/objects/items/weapons/grenades/flashbang.dm
- code/game/objects/items/weapons/grenades/spawnergrenade.dm
- code/modules/dungeons/teleporter.dm
- code/modules/mining/mine_turfs.dm
- code/modules/mob/living/carbon/carbon.dm
- code/modules/mob/living/carbon/human/human.dm
- code/modules/mob/living/carbon/superior_animal/defense.dm
- code/modules/mob/living/living.dm
- code/modules/mob/living/silicon/silicon.dm
- code/modules/mob/living/simple_animal/simple_animal.dm
- code/modules/projectiles/projectile/energy.dm
- code/modules/projectiles/projectile/special.dm
- code/modules/reagents/recipes.dm
Generalized flashing a mob into a single proc. (No more hudtech find everywhere)
Almost all flashes now deal eye damage
Fixed robots not being properly flashed(their overlay did not exist)
Fixed flashlights not letting you flash other people than yourself
Added special description for the flashlight
Flashbangs now bypass all protections on thermal users
Fixed chemical flashbangs bypassing all protection
Code quality + More Generalized Behaviour + Easier to code + Bugs are bad
:cl:
balance: Most flashes now deal eye damage
balance: Fixed flashlights no letting you flash / check other people
add: Added special descriptin for flashlights
balance: Flashbangs now bypass all protection on thermal users.
fix: Fixed robots not getting a flash overlay
fix: Fixed chemical flashbangs not checking …
> The flashy update!

- code/modules/surgery/hardsuit.dm
- code/modules/surgery/robotic_damage.dm
- code/modules/surgery/surgery.dm
This PR reverts SPCR's PR below
https://github.com/discordia-space/CEV-Eris/pull/7389
As the PR above broke healing for FBPs as long as they wore rigs, making them attempt to cut through the rig when using a welder.
He was made aware of this after the merge, but declined to fix the new bug that came from it.
So this PR ports changes made in the PR below by https://github.com/ThePainkiller
https://github.com/sojourn-13/sojourn-station/pull/1579
Which change the quality needed to remove hardsuits from FBPs forcibly to drilling. This bypasses the bug that SPCR's PR fixed.
Note that you will need a tool with only drilling, which limits this to the surgical drill. Trying to use a combi driver or electric screwdriver will open the FBPs torso instead.
I'm fine with this since surgical drills are …
> Rig Removal Now Drilling Instead Of Welding (Reverts #7389)

- code/modules/multiz/structures.dm
Reduces the climb delay multiplier from 6 to 3
No reason to have it 6 times higher. The sound que is more than enough anyway.
:cl:
balance: Robots now climb ladders 50% faster than before.
/:cl:
> Robots now climb ladders 50% faster

- code/modules/core_implant/cruciform/cruciform.dm
- code/modules/core_implant/cruciform/rituals/construction.dm
Replaces the base toolbox type it requires with the blue one
Also adds description info to the cruciforms.
It should be fucking craftable
:cl:
fix:Fixed NT being unable to build Bioprinters.
/:cl:
> Fixes NT bioprinter not being buildable

- code/modules/integrated_electronics/subtypes/input.dm
Switch frequency of integrated circuits to 1457 (the frequency used by other small devices of that kind like remote signaling devices or computer network cards).
Fix their Destroy function to be in line with other devices that listen to a radio frequency.
Stop the thousands of runtimes in atmos machines
:cl: Hyperio
tweak: Switch frequency of integrated circuits to 1457
tweak: Modify the Destroy function of integrated circuits
/:cl:
> Fix frequency runtimes in atmos machineries

- code/game/objects/items.dm
- code/modules/mob/mob_grab.dm
Grab speed now takes into account the affected's robustness, increasing its speed.
Flip_in_hand no longer forcibly rests people.
Instant-grabs are bad for the game , and flip-in-hand was just obscure abuse.
:cl:
balance: Grab speed also takes the affected's robustnesss into account now
balance: flip-in-hand no longer forces people to rest
/:cl:
> Grab speed now also depends on the target's robustness. Flip_in_hand no longer forces humans to lie down.

- code/game/objects/items/devices/techno_tribalism.dm
- code/modules/organs/internal/eyes.dm
Eyes now need 70 eye damage to go broken , instead of 30.
Technomancer radio no longer brodcasts all conversations near it
Flashes too op , radio is not a CIA machine
:cl:
fix: Fixed techno-radio broadcasting
balance: Made eyes take double the damage to be broken,
/:cl:
> Fixes technomancer radio broadcasting , makes eyes less susceptible to eye damage

- code/game/machinery/bioprinter.dm
- code/game/objects/items/devices/radio/radio.dm
Fixes the guild radio and robotic organs
Fix good
:cl:
fix: Fixed shortwave radio not spawning bluespace items
fix: Fixed organ naming having a + in the middle.
/:cl:
> Fixes organ naming , bluespace short-wave radio

- code/game/gamemodes/events/ion_storm.dm
- code/modules/admin/verbs/randomverbs.dm
- code/modules/scrap/oldificator.dm
Ion storm ticks were eating up a lot of server resources because they were searching the entire world for /obj/machinery/bot objects to emag. Mulebots are our only objects of that type and are rarely used at that. This PR removes that behavior.
Optimization.
:cl:
fix: Removed worldwide check for deprecated object type
/:cl:
> Removes pointless ion storm code

- code/modules/mob/living/carbon/human/human.dm
oops
Bugfix
:cl:
fix: Fixed the eye damage from flashes always being doubled/
/:cl:
> Eye damage from any source is no longer doubled

- code/game/objects/items/devices/radio/radio.dm
Fixes radio spawning atom movables instead of items
is it
:cl:
fix: Fixed guild radio bluespace item spawning.
/:cl:
> Fixes guild radio bluespace

- code/game/objects/items.dm
- code/modules/mob/living/carbon/human/examine.dm
- code/modules/mob/living/carbon/human/human.dm
- code/modules/mob/living/carbon/human/human_attackhand.dm
- code/modules/mob/living/carbon/human/human_defense.dm
- code/modules/mob/living/carbon/human/human_organs.dm
- code/modules/mob/mob_grab.dm
- code/modules/mob/mob_grab_specials.dm
- code/modules/multiz/turf.dm
- code/modules/organs/external/_external.dm
- code/modules/organs/external/stump.dm
- code/modules/organs/external/subtypes/robotic.dm
- code/modules/organs/external/subtypes/unbreakable.dm
- code/modules/organs/organ_description.dm
Adds a comical amount of new grab specials, as well as a way to counter grabs the COOL WAY:tm:
Irish whip: Changes flipping humans (spin-held-item with grabs) to irish whip instead of forceresting them; irish whip gives 40 external recoil and sends the victim __walking__ behind the attacker for 3 tiles; unique interactions(damage) for walls, windows, tables and railings in the way: walls deal low damage, windows deal medium damage, railings and tables flip over.
Gut punch: Punch the victim in lower body(harm intent, any grab level) to deal damage depending on their TGH and force-vomit them. Force-vomiting cannot be spammed due to hardcoded CD(35 seconds), but the special can be used indefinitely. Has a wounding multiplier of 2.
Jointlocks give better(I quote, "more gory") feedback.
Suplex …
> Melee grab specials: first aid, damage, flipping changes, COUNTERS

- code/modules/projectiles/projectile.dm
When a bullet reaches someone behind cover, the bullet will always miss unless they are the intended target (were directly clicked on, or an NPC is targeting them).
Tested on test server.
Removes an exploit, makes cover more effective, especially against sprayfire. Does not prevent long-range snipers from shooting over cover, and if they aimed correctly, will still enable them to hit someone directly behind cover.
:cl:
add: Cover properly triggers when overshooting
/:cl:
> Fixes cover functionality when overshooting [RTM]

- code/modules/projectiles/projectile/bullets.dm
- code/modules/projectiles/projectile/bullettypes.dm
- code/modules/projectiles/projectile/fragment.dm
Gives fragments a 0.5 wound modifier, but buffs base damage
As stinger rounds now use combined damage types, halloss was significantly cut on them
No more insta-KO from stinger rounds
:cl:
balance: fragment damage adjusted for new armor system
fix: fragment damage type fixed
/:cl:
> Fixes fragment damage values

- code/modules/projectiles/guns/energy/poweredcrossbow.dm
- code/modules/projectiles/guns/energy/rapidcrossbow.dm
- code/modules/projectiles/guns/energy/shrapnel.dm
- code/modules/projectiles/guns/mods/research_mods.dm
Fixes an oversight.
The RCD Crossbow, Rapid Crossbow and Shellshock have now been blacklisted from using the following gun mods.
- Excruciator Lens (More damage less charge)
- Battery Shunt (More damage less charge)
- Telsa overdrive (Less damage more fire rate and battery)
The Shellshock should now be able to use the following gun mods
- Moebius "Atomik" isotope diffuser
- Moebius "Mastermind" psionic catalyst
- Moebius "Black Mamba" toxin coater
- Moebius "Caster" magnetic overheat barrel
- Moebius "Penetrator" magnetic accelerator barrel
- Syndicate "Gauss Coil" barrel
- Makeshift bullet time generator
The main reason for this is the mentioned weapons being hybrid weapons rather than energy weapons.
The RCD Xbow and Shellshock are mat fab, and the Rapid Crossbow just uses a cell for …
> Crossbows and Shellshock lose energy weapon privileges, Shellshock gets barrel mods

- code/controllers/subsystems/migration.dm
- code/game/objects/items/devices/radio/radio.dm
Fixes guild radio spawning bluespace items without being upgraded
fixes burrows taking out pipes roundstart (with shitcode)
Fixes
:cl:
fix: Fixed guild radio spawning bluespace items with no upgrade
fix: Fixed burrows taking out pipes round-start
/:cl:
> Fixes guild radio and burrows taking out pipes roundstart

- code/datums/craft/gun_parts.dm
Debug guns were spawning because of problems with how grips were inserted in the trash. To fix the problem, I have removed the chance to add grips to frames in the trash
Useless debug gun bad
:cl:
del: removed grips spawning in frames
fix: fixed debug gun spawning when assembling frames
/:cl:
> Fixes debug gun appearing when using weapon frame

- code/modules/aberrants/organs/_defines.dm
- code/modules/aberrants/organs/holders.dm
- code/modules/aberrants/organs/internal/teratoma.dm
- code/modules/aberrants/organs/machinery/disgorger.dm
- code/modules/aberrants/organs/machinery/organ_fabricator.dm
- code/modules/aberrants/organs/mods/component/_component.dm
- code/modules/aberrants/organs/mods/component/special.dm
- code/modules/aberrants/organs/reagents/hormones.dm
Not sure where the organ fab runtime was coming from, but I added a check to prevent it.
A comment about 2u reagent outputs: Using the reagent outputs with an input that constantly triggered caused a lot of ODs in early tests. For example, brute damage input with a space drug output was a good way to remove yourself from the round if you weren't healing.
Fixes and balancing
:cl:
fix: Teratoma stat recommendation fixed
fix: Added check to prevent an organ fab runtime
fix: Disgorger description fix
fix: Fixes disgorger losing acceptable reagents
fix: Removed organ fab and disgorger circuits from junk spawns
tweak: Allows ghosts to see organoid info, fixes a runtime
balance: Added lipzoine, lime juice, orange juice, tomato juice, tea, and iced tea to teratoma (edible) pool
balance: Standard …
> Aberrant organ fixes and balancing

- code/game/objects/items/weapons/implant/implants/carrion/explosive_spider.dm
- code/game/objects/items/weapons/implant/implants/carrion/flashbang_spider.dm
- code/game/objects/items/weapons/implant/implants/carrion/toxic_spider.dm
- html/changelogs/AutoChangeLog-pr-7375.yml
swaps lines, fixes things
had a friend find and help with this one but they don't want to be mentioned
turns this
(notice 'crawls out of' and no target)
into this
https://user-images.githubusercontent.com/57810301/189864937-2599daf6-8d5c-48f3-abb4-398fb52397e2.mp4
(can't make preview show but it works trust me)
:cl:
fix: fixed explosive/flashbang/toxic spiders saying "crawls out of and flashes brightly!", now they actually crawl out of someone
/:cl:
> fix carrion spiders not displaying wearer properly

- code/modules/mob/living/simple_animal/hostile/stranger.dm
Fix this runtime in chaos proc, called during initialization. I guess Stranger ends up in null space sometimes? So area is null.
```
[21:37:03] Runtime in stranger.dm,185: Cannot read null.bluespace_entropy
proc name: chaos (/obj/item/gun/energy/plasma/stranger/proc/chaos)
src: the unknown plasma gun (/obj/item/gun/energy/plasma/stranger)
src.loc: null
call stack:
the unknown plasma gun (/obj/item/gun/energy/plasma/stranger): chaos()
the unknown plasma gun (/obj/item/gun/energy/plasma/stranger): New()
Random wave radio (/obj/item/device/radio/random_radio): Process(10, 0, Objs (/datum/controller/subsystem/processing/obj))
Objs (/datum/controller/subsystem/processing/obj): fire(0)
Objs (/datum/controller/subsystem/processing/obj): ignite(0)
Master (/datum/controller/master): RunQueue() …
```
> Add a check for area existence in Stranger code

- code/modules/organs/external/_external.dm
- code/modules/organs/external/damage.dm
- code/modules/organs/organ_description.dm
increases DROPLIMB_THRESHOLD_EDGE from 0.75 to 1.15
increases max_health from 75 to 90
lowers the droplimb proc's chance to dismember with a blunt weapon from brute/2 to brute/3
less funny funky rng instakills, call it a salt pr, but if I could I'd delete that proc's random chance to dismember completely and nothing of value would be lost
:cl:
balance: made combat less lethal (salt pr)
/:cl:
> Make combat less lethal

- code/modules/surgery/organic.dm
on success, the organ takes 0.1 of the tool's force instead of 0.3
on failure, the organ takes 0.3 of the tool's force instead of 1
both damage flags now lack EDGE, which means they cannot send limbs flying off
no more shall we experience this
glory to my salt prs
:cl:
balance: nerfed shrapnel removal damage, again
/:cl:
> Nerf shrapnel removal damage, again

- code/modules/clothing/spacesuits/rig/suits/station.dm
This gives the Technomancer Rig the same slowdown as the Technomancer Exhault Rig.
I feel like there's enough of a distinction between the TE and Techno rigs module and armor wise, that boosting the speed of the latter won't blur the lines between them.
Also it's weird that while all Clan are expected to be able to respond to trouble effectively, the majority of the clan is stuck lagging behind when it comes to simple movement.
:cl:
tweak: Techno Rig has the Light_Slowdown Flag now, same as the TE Rig
/:cl:
> Technomancer Rig Speed Buff

- code/modules/core_implant/cruciform/rituals/base.dm
- code/modules/core_implant/cruciform/rituals/priest.dm
All of the NT occupations are able to clone, but none of them except the preacher were able to do the deprivation lithany (ejecting the cruciform). This PR adds it to all occupations.
Quality of life for all Neotheology, so they don't have to perform surgery every time.
:cl:
balance: adds deprivation lithany to all NT occupations
/:cl:
> Adding deprivation lithany to all NT roles

- code/datums/craft/crafting_items.dm
- code/game/machinery/crafting_station.dm
Armor parts now recycle for 10 steel and 10 plastic
Armor parts are now made for 10 steel and 10 plastic
The cost of printing them was changed awhile ago, Maik asked me to update the recycle gain to match
:cl:
tweak: Armor parts now recycle for 10 steel and 10 plastic, same as the cost to print them.
/:cl:
> Armor Part Matter Tweak

- maps/CEVEris/_CEV_Eris.dmm
Removes 2 levers and 4 conveyors in guild considering shuttle is gone now.
Before:
After:
Map looks cleaner now that shuttle is gone.
:cl:
tweak: no more conveyors and levers in lower guild
/:cl:
> Conveyor and lever removal

- code/ATMOSPHERICS/components/unary/vent_scrubber.dm
- code/ZAS/Zone.dm
- code/__DEFINES/components.dm
- code/game/machinery/doors/firedoor.dm
Removes all atmos signals from vent , scrubbers and firedoors
Firedoors now get triggered by firealarms
Vents and Scrubbers go back to constant-processing
It works with the new MC system changes , also firedoors are even less intensive , but vents and scrubbers are back to.. processing for now
:cl:
code: Made firedoors even less of a performance hit, and no longer update their icons.
code: Brought back processing for vents and scrubbers
/:cl:
> Firedoors are no longer instant , vents and scrubbers no longer use atmos signals and go back to processing.

- code/modules/clothing/suits/armor.dm
Ablative armor can now reflect lasers again
Nobody in their right mind would ever consider wearing ablative armor anyways, and the laser reflection was the only thing that made it cool enough to warrant pretending that wearing it is a good idea.
:cl:
tweak: ablative armor can now reflect lasers again
/:cl:
> ablative armor can now reflect again

- code/modules/organs/organ.dm
Organ species var was not being set correctly. Transplant data was fine.
One known effect of this fix is that human organs will be exportable for the price tag value. Livers and kidneys still have to be done via offers. Printed organs do not have a set species and cannot be exported for value.
Fixes a bug.
:cl:
fix: Fixed an issue with organ species not being set
/:cl:
> Fixes issue with organ species not being set

- code/game/machinery/vending.dm
Added check for id_scan flip before cruciform checks to the NeoTheology vendor.
The Guild has orders that require church items that are locked within the church, or behind the Theomat that checks for only the faithful. An aspiring techie can now try to hack the NT Vendor for the items stealthily.
This will also lead into future changes that I intend where ritual books need more availability to people outside the church.
:cl:
tweak: Added id_scan check to the NeoTheology vendor before it checks for cruciform.
/:cl:
> Help Those That Help Themselves

- cev_eris.dme
- code/modules/aberrants/_modification.dm
- code/modules/aberrants/organs/_defines.dm
- code/modules/aberrants/organs/holders.dm
- code/modules/aberrants/organs/internal/dependent.dm
- code/modules/aberrants/organs/internal/simple.dm
- code/modules/aberrants/organs/internal/teratoma.dm
- code/modules/aberrants/organs/machinery/disgorger.dm
- code/modules/aberrants/organs/machinery/organ_fabricator.dm
- code/modules/aberrants/organs/mods/0_mods.dm
- code/modules/aberrants/organs/mods/4_special.dm
- code/modules/aberrants/organs/mods/5_upgrades.dm
- code/modules/aberrants/organs/mods/component/_component.dm
- code/modules/aberrants/organs/mods/component/special.dm
- code/modules/aberrants/organs/mods/component/upgrades.dm
- code/modules/organs/internal/_internal.dm
Changes:
- Organ mod install difficulty reduced. 35 BIO (base bio-engineer level) has 100% success rate to attach.
- Stat-boosts from intracrinal organoids and membranes increased to 5 and 10, respectively.
- Disgorger buffed. Stomach, liver, and kidney efficiency affects conversion ratios for reagents, muscle efficiency increases consumption speed more than prior, and accepts any nutriment (includes child types like animal protein, corn oil). Fixed bug with handling child reagent types. Items will have their reagents checked before their biomatter content is checked.
- Pygmy and regular parenchymal membranes only come with a single organ tissue, but their base efficiency modifier is increased to 20 and 40, respectively. The organ type can be adjusted using a laser cutting tool on the …
> Aberrant Organs - balance PR

- code/modules/mob/living/carbon/human/human.dm
- code/modules/mob/living/living.dm
flashes don't weaken humans
flashes don't deal eye damage
muh salt pr
flash is no longer an autowin button
flashbangs still are though, because that stumble is really strong and is not related to flashes themselves
flash already fucks you over by dealing eye damage not to the mob, but to you, the player, as well as obstructing your entire screen for a very long time.
if someone is standing and shooting, and then suddenly gets flashed, they shouldn't go and say "aw jeez, my eyes hurtie so I have to lay down for a while and rest", no, they keep shooting, but since they can't see where they click, they miss.
personally I wanted the flash to also give a temporary vision obstruction like welding helmets/goggles do, but HUDOverlay code countered my grab, irish-whipped me on a table, gut-punched …
> Nerf flashes, again

- code/datums/setup_option/backgrounds/origin.dm
New stat spread:
ROB = 5
TGH = 5
BIO = 5
MEC = -10
VIG = -10
COG = 10
1. There is no background that gives high COG gain besides End Point, which mirrors Crozet and is supposed to be a location with all work stats.
2. Stat spread now corresponds to things NeoTheology members use. COG +10 for Cruciform recharge speed. 
-10 MEC because literally nobody there uses MEC. They don't even know how their miracle technology works. VIG -10 because they're melee fanatics.
BIO +5 because they have interest in both medicine and botany, but not all of them. ROB/TGH unchanged.
:cl: 
tweak: New Rome background updated, now increases COG and decreases MEC. 
/:cl:
> New Rome now buffs the stats that NeoTheology members use.

- code/modules/core_implant/cruciform/machinery/cloning.dm
- code/modules/core_implant/cruciform/modules.dm
Neotheology Cloning pumps out a generic potato man instead of your character's original appearance, which sort of sucked.
So I fixed that and now basically all of your character's apperance is copied over, code-wise technically so should the TTS seed (how your character sounds) as well, but I cant test it in local server so it has to be tested live.
Thanks to @Pink-Chink for helping with the skin tone part of the appearance code
A bug is fixed and people can keep their appearances as NT followers, not really life important, but it is a QoL imo
:cl:
fix: fixed the NT not being able to copy all of appearance bug
code: Did some new code on the cloning machine and cruciform module to allow for this
/:cl:
> Fixed the NT Cloning bug

- code/game/objects/items/oddities.dm
Prepares this document for another PR I'm planning to make later down the line.
General order should be Singular Combat Stat > Singular Work Stat > Dual Combat Stat > Dual Mixed >, and so on.
Also fixes description on the observer book.
I tried to mess with this file earlier, but since everything was out of order and ended up constantly jumping towards different points.
I also believe the reorganized state of this file reveals some things about our current oddity design and layout.
:cl: 
tweak: The oddities.dm file has been reordered.
spellcheck: Observer book description changed.
fix: Bear math oddity is now a subtype of /obj/item/oddity/common/, which allows it to spawn in maintenance.
/ :cl:
> Reorders all common oddities in oddities.dm to make more sense

- code/modules/reagents/reagent_containers/food/snacks.dm
- maps/CEVEris/_CEV_Eris.dmm
Changes all roundstart monkeys to monkey cubes.
Punpun is in his own special cube which specifically spawns him.
Also puts one more artist landmark on map so that instead of when having two artists ready roundstart one spawns in office and one in in cryo now both spawn in the office.
Also deletes a floating camera in medbay isolation.
Dev del approval.
:cl:
tweak: roundstart monkeys changed to monkey cubes, artists now spawn in office always instead of only when there is one artist and floating camera in medbay isolation deleted
/:cl:
> Various map fixes

- code/game/objects/items/devices/organ_module/active/armblades.dm
- code/game/objects/items/devices/organ_module/simple.dm
- code/modules/mob/living/carbon/human/human_defense.dm
- code/modules/mob/living/carbon/human/human_organs.dm
increases armblade's force from dangerous(20) to brutal(33) to be on par with other swords.
finally prevents embedded tools and weapons(like surgery omnitool or armblade) to be dropped by pain and malfunctioning(etc.)
also very slightly refactored nanako/bay code(i genuinely have no idea whose it is), thanks to @SirRichardFrancis on that part
~~it's probably not~~
now a tool you have to research and have a surgery for is on par with something you can find in maint(it was worse than a junkblade)
FINALLY FIXING THIS DAMN BUG
:cl:
balance: armblade damage increased
fix: no more embed tools being dropped
/:cl:
> Bladeruiner - slightly buff armblade's damage, prevent embed tools from being dropped

- code/modules/organs/external/subtypes/robotic_types.dm
Makes prosthetics examine text work properly, instead of showing stuff two times.
No more this:
Bug bad.
:cl:
fix: prosthetics examine text now works properly for all prosthetics
/:cl:
> Makes prosthetics examine text work properly

- code/datums/craft/recipes/weapon.dm
- code/game/objects/items/stacks/knife.dm
amount = 3
also changes  crafting recipe name from "knife" to "knives" to reflect on the change
deconstructing knives now gives 1 plasteel instead of 2
no need to waste 6 plasteel sheets for three knives anymore, now you get 3 for 3(the item is very tiny anyway)
:cl:
tweak: throwing knives now spawn in full stack
balance: deconstructing throwing knives now gives 1 plasteel instead of 2
/:cl:
> Throwing knives now spawn in full stack

- code/modules/projectiles/guns/projectile/automatic/ak47.dm
Makes Vipr actually gildable with golden paint.
Bug bad.
:cl:
fix: you can now use golden paint on Vipr properly
/:cl:
> Makes Vipr actually gildable with golden paint

- code/modules/reagents/reagent_containers/food/drinks/bottle.dm
force from 5 to 7
throwforce from 1(__!!!__) to 7
tweaked intent check on throwing bottles
first off, now molotovs ACTUALLY WORK
second, hitting someone with a bottle is far stronger than a *fucking punch* now
third, throwing a bottle at someone is now ~~an alternative to throwing knives~~ *actually useful*
:cl:
add: increase force and throwforce of intact bottles
tweak: bottles guaranteed to break on impact when not in help mode
/:cl:
> Increase force and throwforce of intact bottles, bottles guaranteed to break on impact

- code/game/objects/items.dm
removed the twirling proc that happened when both the attacker and the victim have help intents
i have been told that people sometimes they keep twirling people around instead of irish whipping them. Haram!
Besides, this is obscure and bloat. ~~and this is also not written on wiki because I was unaware of this~~
:cl:
del: twirling instead of irish whipping on help intent
/:cl:
> Remove twirling humans on help intent

- code/datums/craft/recipes/guns.dm
- code/datums/craft/recipes/weapon.dm
- code/modules/projectiles/guns/energy/lasersmg.dm
Lasblender has slightly better damage, pen and no initial offset now.
Description changed to remove the accuracy malus mention.
Furher dies in 4 bursts.
The gun was overnerfed the first time and now it's a waste of materials, it's still pretty bad now but not as bad.
Does 10.5 damage with 1 pen, so 84 if you get pegged with every shot from a full burst.
:cl:
add: Added Lasblender crafting recipe to the guns section
del: Removed Lasblender crafting recipe from the weapons section
tweak: Lasblenders description has been updated
balance: Lasblender does has a 0.35 damage mod and a 1 pen mod now, up from 0.28 and default
balance: Lasblenders initial offset is gone
/:cl:
> Lasblender buff

- code/modules/clothing/masks/gasmask.dm
Makes artist glasses visible roundstart so you don't have to put them off and on just for them to work.
Bug bad.
:cl:
fix: artist glasses now properly show roundstart
/:cl:
> Makes artist glasses visible roundstart

- code/__DEFINES/weapons.dm
The Sol's high-delay rapid 3-round burst is now actually rapid.
Gun work. This is my second time writing this and I can't be assed to write a whole bible
:cl:
tweak: Reduced the burst delay on the high-delay rapid three round burst from 2 to 0.5
/:cl:
> Fixed Sol Burst

- code/modules/modular_computers/file_system/reports/crew_record.dm
Removes home system and faction fields from the crew records program as they were always showing up empty and Nanako ain't returning.
Empty fields bad.
:cl:
del: Removed two fields from the crew records console which were empty anyways
/:cl:
> Removes home system and faction fields from the crew records program as they were always showing up empty

- code/modules/clothing/head/armor.dm
Humon can't code and always fucks something up so as his guardian angel I have fixed his mistake.
No more riot helmet blocking **40** damage.
Invincible spaceman bad.
:cl:
fix: riot helmet now has normal armor values
/:cl:
> Makes riot helmet not be the best armor in the game

- code/modules/clothing/spacesuits/rig/rig.dm
- code/modules/clothing/spacesuits/rig/suits/combat.dm
- code/modules/clothing/spacesuits/rig/suits/light.dm
- code/modules/clothing/spacesuits/rig/suits/merc.dm
- code/modules/clothing/spacesuits/rig/suits/station.dm
Buffs all RIG armor across the board, rescue suit RIG has less slowdown
Further buffs might be necessary, but due to how overly effective we have made AP, it walks a fine line between being worthless against a Tosshin and being indestructible against an atreides.
Rework made RIGs not as effective as they should be, this alleviates it
:cl:
balance: RIG armor values increased
balance: Rescue Suit RIG slowdown decreased
/:cl:
> RIG armor buff

- code/datums/outfits/jobs/engineering.dm
- code/game/objects/items/weapons/storage/belt.dm
- code/game/objects/structures/crates_lockers/closets/secure/engineering.dm
Much like the doctors and paramedics spawn with trauma kits and gloves, because they are required to perform their job efficiently. I believe technomancers should spawn in with tools of the trade
This PR
- Replaces the technomancer thick gloves with insulated gloves 
- Replaces the standard toolbelt with one full of advanced tools (electric screwdriver, big wrench, advanced welding tool, pneumatic crowbar, armature wirecutter, a power shovel and cable coils)
- Adds a technomancer tool pouch to each of the technomancer lockers (there are 4)
As someone who plays Technomancer constantly, these are items which I end up getting round after round just to be able to do my job properly, and it's honestly a slog to do.
Adding this to the profession and profession lockers from the get go seems like …
> Technomancer QoL Update

- code/modules/projectiles/gun.dm
- nano/templates/weapon_stats.tmpl
Adds a new autocalc value to the gun UI. In addition to damage against 0 and 10 armour, damage against 15 armour will also be displayed.
More info, yay. Making the actual effectiveness of weapons clear from even the most surface-level look should help massively with perception of my beloved armour rework. That being said, I won't deny that this could be seen as taking it too far. Fortunately for me, this was piss easy to code and I can just toss this shit out there! Merge it if you want.
:cl:
add: Added damage against 15 armour to the gun UI.
/:cl:
> Adds 15 armour to UI calculations

- code/modules/projectiles/projectile/bullettypes.dm
Fixes a error that was discussed weeks ago and then nobody got up to fix.
Scrap ammo is supposed to be worse than normal ammo, but easier to produce. No idea what happened here.
:cl:
balance: Fixed two cases where scrap ammo was superior to normal ammo.
/:cl:
> Certain scrap ammo is no longer superior to normal ammo

- code/game/objects/items/weapons/storage/holster.dm
gunsheath no more(this must be a feature)
@SirRichardFrancis localtest lied to us apparently
~~it's not~~ fix
:cl:
fix: no more gun overlay on sheaths
/:cl:
> Fix double overlays on sheaths

- maps/submaps/dungeon_rooms/rooms/armory.dmm
Move the position of a stalker in the "armory" dungeon room. It was causing runtime at roundstart due to airflow trying to move the mob too soon, before its movement variables were all properly initialized
:cl: Hyperio
tweak: Switch stalker position in armory dungeon room
/:cl:
> Switch stalker position in armory dungeon room

- code/game/objects/items/oddities.dm
- Many oddities now have different stat layouts... (Single-statters now exist for every stat, photo oddities were reworked to have VIG-focused layout, dual stats now cover every ROB-TGH-VIG combo, and so on)
- Oddities now roll from 2 to Max, instead of 1 to max.
This is a watered down version of what I wanted to do but oh well.
Maint oddities are now more useful in general. People can actually focus down a specific stat layout instead of being given maybe "ROB/TGH/VIG all in combat" or "BIO/COG/MEC all in work".
:cl:
balance: Oddities in maint have slightly more diverse stat layouts. You may just find one that better fitting for your intended job or build.
balance: Maint oddities will no longer roll 1s on their RNG stat rolls.
/:cl:
> Adjustments to maint generated oddities

- code/modules/client/preference_setup/loadout/lists/headwear.dm
- code/modules/client/preference_setup/loadout/lists/uniforms.dm
OP beret, OP cap and formal sec outfit are now available to JOBS_SECURITY(every IH OP job)
more drip for other ironhammer gamers (for farya)
:cl: Kegdo
tweak: IH OP related stuff in loadout available to other IH jobs
/:cl:
> IH OP related stuff in loadout available to other IH jobs

- nano/templates/sanity.tmpl
The values in the sanity UI (sanity, insight, style, rest progress, holiness) are now visible.
Vague bar bad, accurate number good
:cl:
add: Sanity UI now shows exact values
/:cl:
> Numbered Sanity UI

- code/modules/mob/living/carbon/human/human_attackhand.dm
From 3 + ROB/10 to (0 + ) ROB/4, but the damage is hardcapped at 15.
The punch damage increase from ROB stat was ridicilously low. At 200(!!!) ROB, your damage was 5+3+20 = 28 damage, with no armor penetration whatsoever. This PR makes the ROB hustle much easier, but prevents people from achieving instakill levels of punching(1000+ ROB - instakill)
The formula, ROB/4, stops increasing after 60 robustness is reached, which is an increase to 15 damage.
With PLATINUM knuckle dusters and 60 rob, the MAXIMUM damage a punch can deal is 5 + 15 + 15 = 35. Again, no armor penetration. Fair and balanced!
:cl: Kegdo
balance: ROB stat damage increase capped, formula changed
/:cl:
> Punch damage: ROB stat damage increase capped, formula changed

- code/datums/autolathe/biomatter.dm
- code/game/objects/items/weapons/design_disks/NeoTheology.dm
- code/game/objects/items/weapons/nt_melee.dm
- code/modules/core_implant/cruciform/machinery/eotp.dm
Increases the amount of armament points rewarded by the EOTP (100->125), as well as the starting maximum (100->150)
Readds license points to most disks
EOTP design disks were troublesome as they required lots of points and were then limited by license. This did not solve the issue with lategame options simply not being worth the points before the three hour mark, such as the lightfall or the holy grenade.
The solution isn't to remove the license, but to provide more energy to the EOTP, helping NT reach their high tier disks faster.
:cl:
balance: NT disks have license points
balance: EOTP generates more armaments and starts at a higher tech
/:cl:
> Armament and EOTP Tweaks

- code/modules/projectiles/guns/matter/launcher/nt_sprayer.dm
When you set the `projectile_type` of a gun to something that is not a projectile, shit happens (runtimes).
Used for the cleaning guns of NT and Excelsior.
Recoil of 2 is equivalent to light plasma bolt.
```
[21:30:25] Runtime in gun.dm,535: undefined variable /obj/item/arrow/neotheo/cleansing/var/recoil 
proc name: kickback (/obj/item/gun/proc/kickback)
```
:cl: Hyperio
add: Set default recoil for /obj/item/arrow
/:cl:
> Set default recoil for /obj/item/arrow

- code/datums/craft/recipes/clothing.dm
- code/modules/clothing/gloves/miscellaneous.dm
golden dusters are made out of plasteel now, not platinum
all dusters are spawn blacklisted
weighted gloves now actually need knuckle gloves and not dusters...
fix oversights
:cl: Kegdo
fix: golden dusters are made out of plasteel now, not platinum
fix: all dusters are spawn blacklisted
fix: weighted gloves now actually need knuckle gloves and not dusters
/:cl:
> fix knuckle dusters oversights

- code/datums/autolathe/ammo.dm
- code/datums/autolathe/guns.dm
- code/game/objects/items/weapons/design_disks/frozen_star.dm
It's .25 now, not .30
Also fixes its autolathe name
I got eally pissed off when I got takeshi disk and realized this
how it is now:
:cl:
fix: Takeshi disk is now properly named
fix: Takeshi disk now comes with .25 LMG box (its new caliber) instead of .30 LMG box
/:cl:
> Fix takeshi disk having wrong ammo

- code/modules/asset_cache/transports/asset_transport.dm
Comments out two cache errors
They bog down our logs a lot. By a **TON**
:cl:
del: commented out two asset cache messages for the time being because they bog down logs
/:cl:
> Silence two caching logs

- code/modules/clothing/chameleon.dm
- code/modules/scrap/oldificator.dm
You can now manually change the appearance of the voice changer mask, which was bugged previously . this fix is not very elegant, but it will do for now.
Also replaces some shitcode that turned oldified huds into the broken hud subtype with the sprite of the original hud.
:cl:
fix: you can now manually change the appearance of the voice changer again.
fix: broken huds are now actually what they appear to be (no actual changes in-game)
/:cl:
> voice changer bandaid fix and hud shitcode removal

- code/__DEFINES/components.dm
- code/modules/dungeons/crawler/dungeon_gen.dm
- code/modules/dungeons/teleporter.dm
The OS dungeon is now generated only when the teleporter in space ruins is triggered to avoid unecessary server load with all the OS mobs and stuff.
:cl: Hyperio
server: OS dungeon generated only when teleporter is triggered
/:cl:
> OS dungeon generated only when teleporter is triggered

- code/game/objects/items/devices/von-krabin.dm
You may no longer keep the effects of the von-krabin if you deconstruct it
Unintended
:cl:
fix: Fixed von krabin buffs being kept on deconstruction.
/:cl:
> Fixes von krabin deconstruction

- code/datums/craft/recipes/furniture.dm
- code/datums/craft/recipes/machinery.dm
- code/game/objects/structures/railing.dm
- code/game/turfs/flooring/flooring.dm
- code/game/turfs/simulated/floor_attackby.dm
- code/game/turfs/space/space.dm
- code/modules/aberrants/organs/mods/component/output.dm
- code/modules/multiz/turf.dm
- code/modules/overmap/exoplanets/turfs.dm
Railings cost  4 → 2 sheets of metal
Catwalk cost 3 → 2 steel rods, speed adjusted from *six* seconds to 2 at 0 MEC and instant at 40 MEC
Underplating→Plating cost 2 → 1 sheet of metal, speed adjusted from 0.5 seconds to 3 at 0 MEC and instant at 40 MEC
Lattice→Underplating cost 4 → 1 sheet of metal, speed adjusted from 8 seconds to 4 at 0 MEC and instant at 40 MEC
Standartized (kinda?) construction on exoplanets/open space/space tiles
Most stuff that goes onto walls (air/fire alarms, light fixtures) craft time lowered from 9 to 6 seconds default (it is affected by MEC and other things too)
There are unrelated changes in this PR (indentation fixes) because compiler wouldn't shut up about them otherwise
it's no longer CBT
:cl:
balance: Railings cost 4 -> 2 sheets of metal
balance: Catwalk …
> Tweak construction prices and times.

- code/modules/reagents/reagents/toxins.dm
This PR sets `addiction_chance` to 0 for Pararein and Aranecolmin. It also fixed a lowercase.
These toxins already destroy your sanity and getting *addicted* to spider bites is something really stupid.
:cl:
balance: You cannot get addicted to spider toxins (Pararein and Aranecolmin) anymore.
/:cl:
> Remove spiders toxin addiction chance

- code/modules/projectiles/guns/mods/mods.dm
Buffs Oberth Bullet Blender by reducing its recoil increase and penetration decrease. 
Although this is the most balls to the wall insane gun modification, people are scared of using it since it'll nuke their gun damage. 
:cl:
balance: Oberth's bullet blender barrels have been buffed, and no longer nuke your armor penetration and recoil.
/:cl:
> Buffs OR Bullet Blender

- code/modules/projectiles/ammunition/ammo_kits.dm
Makes the pug drum craftable. costs like the .30 drum
pain in the ass to use the pug, you can craft high capacity mags for other guns anyway.
:cl:
add: .50 drum craftable in the crafting station
/:cl:
> Boejevic magazine craftable

- code/modules/reagents/reagents.dm
Adds a minimum amount (0.05 units) for metabolizing reagents. While it is slow, this should prevent chems from getting stuck in the body and keeping NSA high.
Bug fix
:cl:
fix: Added minimum amount removed for reagent metabolism
/:cl:
> Fix for reagents stuck in body

- code/modules/hivemind/mobs.dm
Hivemind mobs won't use their special abilities after dying. Should take care of a related timer bug, too.
Bug fix
:cl:
fix: Fixed hivemind mobs processing after death
/:cl:
> Fixes hivemind mobs processing after death

- code/modules/core_implant/cruciform/machinery/obelisk.dm
- maps/CEVEris/_CEV_Eris.dmm
NT obelisks use LoS. Returns chapel obelisk to original spot.
Makes sense
:cl:
tweak: NT obelisks use line of sight for checking affected mobs
tweak: Moved chapel obelisk back to original spot
/:cl:
> NT obelisk uses LoS

- code/game/objects/items/weapons/nt_melee.dm
- code/game/objects/items/weapons/shields.dm
- code/modules/projectiles/projectile/bullets.dm
Previous PRs made shields able to be penetrated but leaned too hard on it, making it difficult to block even shrapnel properly and having it embed in the body.
This buffs the integrity of shields to near wall levels/above wall levels, and makes it so even when bullets penetrate their damage is reduced enough that it's worth using a shield.
Buckler Tac 125 > 195
Ballistic 135 > 205
Bulldozer 160 > 230
Hardsuit 180 > 250
Buckler Wooden 100 > 170
Tray 85 > 155
Energy 130 > 200 
NT 130 > 200
Divisor code is Humons, I just got annoyed enough to bug him on how to edit it.
You're able to tank smaller calibers as intended but still not immortal to larger ones meant to penetrate
:cl:
balance: All shields have gotten an integrity buff of 70 points
code: Armor divisor code now has a minor rng …
> Armor Divisor Code Change, Shield Integrity Buff

- code/modules/core_implant/cruciform/upgrades.dm
Buffs Faith's Shield to 20% brute and burn protection.
The Cruciform IS competing with Moebius mutations and artificial organs, or robotic limbs. And that free bicardine mutation is really, really strong. 
I think free Bicardine+Tricord is still better than Faith's Shield actually, but this covers fully burn damage and the aforementioned combo only less-than-half-covers it, so lets call it even.
I could be wrong but it was really hard to feel the difference in-game, even at +100 TGH (And thus 200 HP instead of 100~)
:cl:
balance: NT Faith's Shield damage reduction just got stronger.
/:cl:
> Buffs NT Faith Shield cruciform upgrade

- code/modules/projectiles/ammunition.dm
- code/modules/projectiles/guns/projectile.dm
This won't fix every hard del, but it did reduce the number of failures in the GC during local testing.
Performance
:cl:
fix: Added some qdels in guns, ammo magazines, and ammo casings
/:cl:
> Projectile qdel fix

- code/modules/mob/living/carbon/carbon.dm
- code/modules/reagents/holder.dm
- code/modules/reagents/metabolism.dm
Cleans up some qdel stuff for reagent holders, metabolism, and metabolism effects in carbon mobs. This should reduce the amount of hard dels for roaches and other mobs.
Performance
:cl:
fix: Added Destroy() logic to metabolism and metabolism effects
fix: Cleaned up logic for qdels in reagent holders
fix: Cleaned up logic for metabolism qdels in carbon mobs
/:cl:
> Metabolism qdel fix

- code/modules/mob/living/living.dm
Living mobs will remove themselves from the mob_living_by_zlevel list in SSmob when Destroy() is called. Doesn't seem to stop the carp hard dels, but mice and hivemind mobs stopped showing up in the GC failures after this.
Performance
:cl:
fix: Living mobs remove themselves from mob_living_by_zlevel in SSmob
/:cl:
> Mob living qdel fix

- code/modules/mob/living/carbon/carbon.dm
Cleans up the "vessel" reagent holder in Destroy()
Performance
:cl:
fix: Cleans up the "vessel" reagent holder in Destroy()
/:cl:
> Carbon mob qdel fix

- code/_onclick/hud/parallax.dm
- code/modules/mob/mob.dm
- code/modules/multiz/shadow.dm
Cleans up the parallax and HUD in mob Destroy().
Performance
:cl:
fix: Cleans up the parallax in mob Destroy()
/:cl:
> Mob qdel fix

- code/game/objects/items/weapons/design_disks/NeoTheology.dm
Adds Cleansing Presence and Martyr's Gift to existing NT disks.
Those cruciform upgrades are basically gone, unless NT manages to find a incredibly rare generic cruciform upgrade disk in maintenance.
:cl:
tweak: Martyr's Gift is now available on NT's Grenade disk, and Cleansing Presence is now available on Products and Utilities.
/:cl:
> Makes two NT Cruciform Upgrades obtainable again.

- code/modules/projectiles/projectile/bullettypes.dm
Increases .20 damage from 32 to 34.
The previous nerf to .20s went a bit too far, reducing damage from 36 to 32, causing a lot of .20 guns to become less than viable and a bit anemic. My goal with this minor adjustment is to hopefully approach if not reach that sweet spot between intended balance and viability.
:cl:
Increased .20 damage from 32 to 34.
/:cl:
> Small .20 Tweak to Small Tweak to .20 Damage

- code/game/objects/items.dm
- code/game/objects/items/devices/scanners/price.dm
Price scanners and Guild Merchant perk show the actual export value as well as any special offers from discovered stations.
QoL
:cl:
tweak: Price scanners and Market Professional perk show correct export value and special offer information
/:cl:
> Price info update

- code/__DEFINES/trade.dm
- code/controllers/subsystems/trade.dm
- code/modules/trade/datums/_trade_station.dm
- nano/templates/trade_offers.tmpl
- Exports are soft capped at 200 items per use. It'll suck when you have loaded ammo mags in the pile, but it's for the sake of server performance.
- Objects containing humans and monkeys will not export.
- Special offer tab on the ordering app shows offer credit value.
- Trade station offer update time range reduced to 6 to 8 minutes.
- Removed special offer limits. This shouldn't affect anything in-game.
Performance, bug fixes, and QoL
:cl:
fix: Humans and monkeys inside objects will prevent the object from being exported
code: Added export item soft cap of 200
tweak: Ordering app shows special offer value
tweak: Trade station offer update time reduced to 6 to 8 minutes
code: Removed special offer price limits
/:cl:
> Trade tweaks

- maps/encounters/blacksite/blacksite.dm
Should fix blacksite map templates being generated on top of themselves.
Bug fix
:cl:
fix: Blacksites only load once
/:cl:
> Blacksites only load once

- code/modules/mob/living/carbon/superior_animal/stalker/stalker.dm
- code/modules/mob/living/living_defines.dm
- code/modules/mob/living/simple_animal/hostile/doomba.dm
- code/modules/mob/living/simple_animal/hostile/onestar_drone.dm
One Star roombas and drones have a 1/5 chance to drop a random One Star component. Dead One Star Stalkers can be pried apart to reveal 2-4 One Star Components, along with cable coil and random quantities of steel and plasteel.
Valo is doing One Star ruins/blacksites, and asked for it. Outside of the One Star Trash Beacon, you need some hell of good luck to get OS components other than capacitors.
:cl:
tweak: One Star Roombas and Drones drop One Star Components.
tweak: One Star Stalkers can be broken down with the prying quality, yields: 2-4 One Star Components, Steel, Plasteel, Wires
/:cl:
> OS robots drop OS components

- code/datums/mob_stats.dm
- code/modules/mob/living/living.dm
Stat holder datums clean up perks, which may be a cause of human hard dels. /mob/living objects clean up their static overlay, which may be the cause of image hard dels (unsure).
Performance
:cl:
fix: Stat holders clean up perks on Destroy()
fix: /mob/living objects clean up their static overlays on Destroy()
/:cl:
> /mob/living GC fix

- code/modules/mob/living/living_defense.dm
Raised pain resistance given by armour from 60% to 75%. (No more near paincrits from a single .40 rubber against bulletproof armour.)
Currently, the balance between Style and Armour is in a poor state leaning towards Style, this change should hopefully lessen the power difference as it will be harder to paincrit people wearing high amounts of armour.
(Free to discuss in comments if 80% is too high or too low, I personally feel like 85% is too high and 75% is too low. However regardless, I think this is a necessary change to make armour a more solid choice when considering your defensive options.)
:cl:
Changed pain block from 60% to 75%
/:cl:
> Armour Protec (Armour reduces pain more.)

- code/game/machinery/kitchen/microwave.dm
Microwaves accepts more items for cleaning. That being soap bars, and the rag.
Too often a Club Worker will hit the microwave with a bar of soap only to be frustrated, they will then print a spray bottle, go through the effort of acquiring space cleaner to fill it, and also face that it _also_ doesn't work. There's still many issues and bugged behavior with this object, but this is at least one step.
:cl:
tweak: You may now clean microwaves if they get dirty with soap bars or a dry/damp rag.
/:cl:
> Let me clean it!

- code/game/objects/items/weapons/design_disks/autolathe_disks.dm
Adds vipr to golden disk it already has a golden sprite, license  cost of 6 used like of similar guns on that disk.
Fixing a mistake I made with an earlier PR
:cl:
fix: vipr is not on gold paint disk
/:cl:
> Adds vipr to golden disk

- code/modules/client/preference_setup/loadout/lists/suits.dm
- code/modules/clothing/suits/jobs.dm
Fixes text mistakes in loadout regard apron, it now correctly states it's yellow.
Colorblind people can play the game again, eris is saved.
:cl:
spellcheck: apron description in loadout is now appropriate  
/:cl:
> Loadout apron fix

- code/modules/reagents/reagent_containers/hypospray.dm
Autoinjectors sold in hidden Caduceus inventory are no longer empty.
There's a point to buying Caduceus autoinjectors.
:cl:
fix: added reagent values to bloodclot, bloodrestore, painkiller, speedboost and oxygenation autoinjectors
/:cl:
> Added reagents to Caduceus autoinjectors

- code/modules/client/preference_setup/loadout/lists/uniforms.dm
Added Blue and Purple options back to medical scrubs in the loadout.
Blue and Purple options are now available in the loadout.
:cl:
fix: fixed being unable to pick blue and purple options to medical scrubs in the loadout
/:cl:
> Options to medical scrubs

- code/game/objects/items/weapons/storage/boxes.dm
- code/modules/reagents/reagent_containers/food/snacks.dm
- code/modules/trade/datums/trade_stations_presets/2-uncommon/McRonalds.dm
Makes some changes to the McRonalds trade station, to the benefit of kitchen workers primarily.
Thou shalt not ignore the kitchen... as much.
:cl:
tweak: Changed the Happy Meal to include some different items, and a soda.
balance: You may no longer buy whole cakes from the McRonalds trade beacon, they instead come in smaller slices.
balance: A few cooked items such as jelly burgers and sandwiches now count as cooked for gathering insight.
/:cl:
> Happy Meal Change

- code/modules/mob/living/carbon/human/human.dm
- code/modules/organs/blood.dm
Adds some qdel checks in human code since mannequins will qdel after being created, which causes problems with two instances of spawn() in human New().
Bug fix and should be one fewer item ruining CI checks.
:cl:
fix: Added qdel check in set_species()
fix: Added qdel check in fixblood()
/:cl:
> Mannequin runtime fix

- code/game/objects/items/devices/radio/intercom.dm
Another CI failure cause and generally annoying runtime. Intercoms were creating a timer with a negative ID.
Bug fix
:cl:
fix: Added a flag to intercom timer
/:cl:
> Timer roundstart runtime fix

- code/modules/trade/datums/trade_stations_presets/1-common/hellcat.dm
- code/modules/trade/datums/trade_stations_presets/2-uncommon/tb_cheapammofactorys.dm
- code/modules/trade/datums/trade_stations_presets/3-rare/fs_experimental_factory.dm
Since trade station special offers stop the requested items from exporting, these modded guns were preventing any guns from exporting.
Smoother trade gameplay
:cl:
fix: Removes modded gun offers from trade stations
/:cl:
> Removes modded gun offers

- code/modules/mob/living/carbon/superior_animal/stalker/stalker.dm
One star stalkers no longer make roach gibs upon death, they make black robotic gibs instead.
:cl:
fix: one star stalkers are no longer roaches
/:cl:
> One star stalkers no longer make roach gibs

- code/game/objects/structures/low_wall.dm
- code/modules/tables/tables.dm
Fixes onestar table and low wall names.
onestar table and low wall no longer just called onestar
:cl:
spellcheck: onestar table and low wall names work properly now
/:cl:
> Fixes onestar table and low wall names

- code/modules/research/designs/prosthesis_implants.dm
- code/modules/research/nodes/biotech.dm
Added regular and advanced head and torso prosthesis to known designs. Changed prosthesis to moebius type instead of unbranded for aesthetics.
You can now make any body part as a prosthesis. It also makes sense that moebius makes their own branded prosthesis.
:cl:
add: added torso and head to basic biotech
add: added reinforced torso to augmentations biotech
change: changed basic prosthesis type to moebius instead of unbranded
/:cl:
> Added head and torso prosthesis to tech and fabricator

- code/_onclick/click.dm
- code/_onclick/item_attack.dm
title, fixes the issue of swinging when you click on your equipped bag when you are wielding the item on harm intent.
also fixes a possible issue of clicking on an atom on yourself requiring double tact
fixes
:cl: Kegdo
fix: fix melee attacks proccing when you click on atoms on yourself
/:cl:
> fix melee attacks proccing when you click on atoms on yourself

- code/modules/mob/living/carbon/human/human.dm
- code/modules/mob/living/carbon/human/human_organs.dm
- code/modules/organs/external/_external.dm
title
also made it not drop items so that it wouldn't be instant disarm, being unable to use your hand is already tuff
fix
:cl: Kegdo
fix: nerve strike not working
balance: nerve strike doesn't make you drop items
/:cl:
> fix nerve strike not working(how)

- code/modules/mob/living/carbon/human/human.dm
Bay12 code is a piece of putrid garbage.
code starts actually working from simply increasing a number by **1**.
:cl: Kegdo
fix: vomit stun not working
/:cl:
> fix vomiting not stunning

- code/game/gamemodes/malfunction/newmalf_ability_trees/tree_networking.dm
- code/game/gamemodes/roleset/simple.dm
Makes the Malf AI's System Override reasonably achievable. It should no longer be expected to take ~2 hours to self-destruct the ship.
Cost for system override reduced to help mid-round Malf AIs.
Adjusted when command announcements trigger for both lore, and the fact there's no real metagame rules.
The AI blowing up the ship finally has the needed closure of the round. The AI spends the time murdering people, only for it to sputter out into a "glorious death" scenario. Even on low-pop of ~5 players as Malf AI, in a 4 hour round, I was still unable to successfully perform override. That was years ago, and was when I realized this role was dead end garbage with little ground to explore as it currently stood. This isn't exploring anything, it's just one step to getting to the best part of a …
> System override timer reduction

- code/datums/autolathe/guns.dm
- code/datums/uplink/highly visible and dangerous weapons.dm
- code/modules/projectiles/guns/energy/shrapnel.dm
- code/modules/projectiles/guns/projectile/automatic/sts35.dm
- code/modules/projectiles/guns/projectile/dartgun.dm
Renames the gun boxes in uplink to clarify them, renames Oberth guns to follow convention.
No more misunderstanding good
:cl:
tweak: name of uplink gun boxes clarified
spellcheck: Oberth gun names adjusted to follow convention
/:cl:
> Uplink renames

- code/modules/mob/living/bot/cleanbot.dm
it's a 10% chance now
Massive QoL, huge even, one could even say hugongous
:cl: Kegdo
tweak: Cleanbots don't always say stuff when cleaning (10% chance)
/:cl:
> Cleanbots don't always say stuff when cleaning

- code/game/objects/items.dm
- code/game/objects/items/stacks/knife.dm
- code/game/objects/items/weapons/material/thrown.dm
- code/game/objects/items/weapons/nt_melee.dm
- code/game/objects/items/weapons/sword_of_truth.dm
- code/game/objects/items/weapons/tools/knives.dm
- code/game/objects/items/weapons/tools/pickaxe.dm
- code/game/objects/items/weapons/tools/saws.dm
- code/game/objects/items/weapons/tools/simple_weapons.dm
- code/modules/mob/living/carbon/carbon_defense.dm
Items have an embed multiplier that makes it more/less likely than normal for that item to embed. Unfortunately, the way this was calculated caused to the problem that if a weapon used to have a negative base chance to embed (without the embed multiplier calculated in), then even having an insanely high embed multiplier would never cause the weapon to embed. This is now fixed, and for the majority of weapons, everything stays the same. Only weapons that had a non-standard embed mult now behave differently. 
Those weapons that are designed to embed such as throwing knives, the ritual dagger or the displacement dagger are now much more likely to embed. 
Weapons that had a higher embed multiplier before (saws including chainsaws, pickaxes including drills and jackhammers , the meat hook and …
> Rewrites embed code to make more sense

- code/modules/clothing/accessories/accessory.dm
Fixes armor plates possibly speeding you up and lowering your stiffnes, now instead of setting your slowdown/stiffness to set value (if you put it on a suit) they just add to it. 
Also tweaks some values:
added slowdown to basic armor plate, removed stiffnes from it, lowered slowdown on ballistic armor plate. I believe `LIGHT_STIFFNESS` is only used for full vests or something similar and those aren't even close to it. We'll keep it on more bulky ones, though
bugfix good, rebalance even better
:cl:
fix: armor plates (which is an accessory) now properly slows you down and increases your stiffness
balance: basic armor plate now gives 0.1 slowdown (very little)
balance: basic armor plate now doesn't gives any stiffness (gun accuracy penalty)
balance: ballistic armor plate now gives light …
> Tweak armor plates

- code/modules/organs/internal/bones.dm
Makes bone breaking have a sound. Crunch. 
More visceral combat and easier to tell when your own/the enemies bones break. 
:cl:
add: Bone Break sound. 
/:cl:
> Adds the Jointlock Sound to bone breaking 

- code/_onclick/item_attack.dm
- code/modules/mob/living/carbon/human/human.dm
- code/modules/mob/living/carbon/human/human_attackhand.dm
- code/modules/mob/living/carbon/human/human_defense.dm
- code/modules/mob/living/carbon/human/human_defines.dm
Removes help intent halving the damage you deal, because that's just another noob trap. Instead, pulling punches will now also halve the melee damage you deal with weapons.
cringe removal.
:cl:
balance: attacking with help intent no longer halves your melee damage, but pulling attacks will.
/:cl:
> Makes melee less cringe

- code/modules/mob/living/silicon/robot/robot_modules.dm
Cyborg modules use actual languages, instead of Bay remnants which no longer exist.
There's a discussion to be had whether or not Cyborgs should be able to understand Jive or not.
Another piece of support for a dead-end mob type.
:cl:
tweak: Cyborgs can actually understand most station languages now.
/:cl:
> Adjusts Cyborg Module Languages

- code/game/machinery/vending.dm
- code/modules/reagents/reagents/food-Drinks.dm
Dr. Gibbs is a base ingredient, not an end goal. A Club Worker shouldn't need to rely on rare RNG to create the drinks they want. This ignores the aspect of bartending which is just as important as taste tagging, and that's creating a diversity of interesting sprites to interact with.
Club Workers can still make mixed drinks without first relying on RNG.
:cl:
balance: Controversy has erupt regarding Dr. Gibbs' 42 berries and spices, just not the same claim uninformed consumers.
/:cl:
> Dr. Gibbs no longer has a mass plethora of tastes.

- code/modules/aberrants/organs/machinery/organ_fabricator.dm
- code/modules/aberrants/organs/mods/component/output.dm
Fixes an issue with using mismatched input and output organoids.
Allows organ fabricator to accept non-biomatter sheets.
Organ fabricator has a message for attempting to rip the wrong disk type.
Bug fixes
:cl:
fix: Fixed an issue with using mismatched inputs and outputs
tweak: Organ fabricator accepts non-biomatter sheets
tweak: Organ fabricator has a message for attempting to rip the wrong disk type
/:cl:
> Aberrant organ fixes

- code/game/objects/items/devices/radio/radio.dm
- code/modules/mob/language/jive.dm
- code/modules/mob/living/say.dm
Removes NONVERBAL flag from it. As much as I can say, those two flag (NONVERBAL and SIGNLANG) shouldn't be used together and Jive is more of subtle motions rather than moaning slightly and pointing fingers (which is kind of non-verbal)
Fixes people talking on Jive through radio
:cl:
tweak: Removed NONVERBAL flag from Jive, in return it's much more like a sign language and people can't talk on it through comms
/:cl:
> Fix Jive comms

- code/__DEFINES/weapons.dm
- code/game/objects/structures/window.dm
Weak windows now have FLIMSY resistance
Any window that is not reinforced can no longer be dislocated if the hit does not damage it
Bug fix + slightly tougher windows so they can't be broken with a lighter
:cl:
balance: windows now have a resistance of 2 
fix: windows being dislocated by non-damaging hits
/:cl:
> Weak windows now have FLIMSY resistance , and can no longer be dislocated by non-damaging hits

- code/game/objects/items/weapons/tools/simple_weapons.dm
- code/game/objects/structures/fireaxe_cabinet.dm
The Fire axe has received a small damage and penetration buff (from 33 damage wielded to 34 damage wielded and from 1.6 AP to 1.8 AP), since it was pretty shit for a weapon that doesn't fit into a bag.
The fire axe cabinet can now also be unlocked by an ID with head or medical access without smashing the glass.
No longer neglected
:cl:
add: the fire axe cabinet can now be opened by an ID with head or medical access.
balance: slightly buffed fire axe damage
/:cl:
> Some fireaxe love

- code/modules/mob/living/simple_animal/borer/borer_powers.dm
So apparently, the borer's "Read Mind" ability was checking if the host did NOT have stats, rather than checking if they did.
That's obviously dumb and unintended, so I fixed it.
I fully tested this. Worked as intended, stats were copied, messages regarding copied stats and increased brain/sanity damage work fine, no runtimes or anything nasty.
In all honesty it's probably not, I fully expect this to have balance issues, but it's a bug so I fixed it.
:cl:
fix: Borers can now actually copy stats as intended.
/:cl:
> Makes borers actually able to copy stats

- code/modules/mob/living/carbon/superior_animal/superior_animal.dm
Apparently, proc calling is very expensive in byond. Superior animal's handle_cheap_regular_status_updates() was one of the more costly procs used by superior mobs. Based on a local test, replacing the getter procs for damage with the damage vars cut the proc's CPU time cost in half. I doubt we'll see a noticeable improvement in performance, but every little bit counts.
Performance
:cl:
code: Replaced damage getter procs with damage vars in superior animal status updates
/:cl:
> Replaces getter procs with vars in superior animal status updates

- code/modules/onestar/os_turret.dm
Adds firing sounds, damage feedback via sparks, and extended the EMP state duration.
Bug fixes and better feedback
:cl:
add: Added firing sounds to OS turrets
tweak: Added 50% for the turret to spark when taking damage
balance: Extended duration of EMP'd state from 4 seconds to 8 seconds
/:cl:
> OS Turret tweaks

- code/datums/outfits/equipment/backpacks.dm
Adds grey satchel, backpack and sport backpack and other colors to loadout. Currently game overrides backpack/satchel/sports backpack with your departmental variant, this allows people to get default grey satchel and other colors if they so wish.
Should this mess with the preferences? I dunno, unlikely. Leather satchel has an uppercase letter (unforgivable) in its name but I'm not touching it in case it fucks up anyone's preferences.
It's good for the looks if you choose unique clothing from loadout. Or if you're the only scientist, commit a crime in a generic voidsuit and get called out because of your research backpack.
:cl:
add: Color satchels, backpacks and sport backpacks added into possible starting backpack selection
/:cl:
> Add grey satchel, backpack and sport backpack and other colors to loadout

- code/game/turfs/simulated/walls.dm
- code/modules/projectiles/projectile.dm
This fixes low-damage bullets deleting walls and mobs wearing RIGs. Also, fixes a runtime when a bullet ricochets off of a wall that it destroyed (not related to wall-deleting bug).
Bug fix
:cl:
tweak: Fixed a runtime when a wall is destroyed while a bullet is ricocheting
fix: Fixed issue with low damage bullets qdeling walls and mobs wearing RIGs
/:cl:
> Another projectile qdel fix (this one is for real)

- code/__DEFINES/items.dm
- code/__DEFINES/weapons.dm
- code/datums/datum_click_handlers.dm
- code/modules/mechs/equipment/combat.dm
- code/modules/mob/living/simple_animal/hostile/stranger.dm
- code/modules/projectiles/guns/projectile/automatic/maxim.dm
Fullauto now uses a two-layer while() system with sleep() instead of spawn()
Currently any RPM above 600 causes some bullets to be fired in pairs.
A line of code was left in we can swap to that raises the number of checks to match up with FPS rather than tickrate, which means you need an RPM of 2400 to cause bullets to pair up, but as there is no mechanical difference, I didn't see a need to.
"rapid" firerates have been changed to match the current code-locked minimum. (no ingame effect)
Firerate almost fixed (#7878 contains remaining fixes). Also optimization.
:cl:
tweak: firerates lower than the old minimum set to minimum to avoid balance inconsistencies in future PRs (who set those so low?)
refactor: optimized fullauto code
fix: stranger gun fire delay fixed (values were swapped in …
> Fixes FA, burst delays

- code/modules/mob/living/carbon/human/species/station/station.dm
Adds remains_type to human species
So you don't leave xeno remains when you touch supermatter
:cl:
fix: Dusted humans will now leave human remains, not xeno ones
/:cl:
> Dusting people no longer leave xeno remains

- code/__DEFINES/weapons.dm
- code/game/objects/items/weapons/tools/mods/_upgrades.dm
- code/modules/projectiles/guns/energy/lasersmg.dm
- code/modules/projectiles/guns/projectile/automatic.dm
- code/modules/projectiles/guns/projectile/automatic/ak47.dm
- code/modules/projectiles/guns/projectile/automatic/atreides.dm
- code/modules/projectiles/guns/projectile/automatic/c20r.dm
- code/modules/projectiles/guns/projectile/automatic/dallas.dm
- code/modules/projectiles/guns/projectile/automatic/drozd.dm
- code/modules/projectiles/guns/projectile/automatic/lmg.dm
- code/modules/projectiles/guns/projectile/automatic/luty.dm
- code/modules/projectiles/guns/projectile/automatic/maxim.dm
- code/modules/projectiles/guns/projectile/automatic/molly.dm
- code/modules/projectiles/guns/projectile/automatic/slaught_o_matic.dm
- code/modules/projectiles/guns/projectile/automatic/sol.dm
- code/modules/projectiles/guns/projectile/automatic/straylight.dm
- code/modules/projectiles/guns/projectile/automatic/sts35.dm
- code/modules/projectiles/guns/projectile/automatic/type17.dm
- code/modules/projectiles/guns/projectile/automatic/type47.dm
- code/modules/projectiles/guns/projectile/automatic/vintorez.dm
- code/modules/projectiles/guns/projectile/automatic/wintermute.dm
- code/modules/projectiles/guns/projectile/automatic/z8.dm
- code/modules/projectiles/guns/projectile/automatic/zoric.dm
- code/modules/projectiles/guns/projectile/pistol/selfload.dm
- code/modules/projectiles/guns/projectile/pistol/type62.dm
- code/modules/projectiles/guns/projectile/pistol/type90.dm
- code/modules/projectiles/guns/projectile/shotgun/bojevic.dm
- code/modules/projectiles/guns/projectile/shotgun/type21.dm
- html/changelogs/archive/2022-08.yml
Halves the displayed RPM of all gun firemodes to make them show actually realistic values.
Only present balance change is the removal of minimum firerate.
To be merged only after #7841 
Visual QOL, fixes fullauto issues.
Game compiled and ran locally, firearms functioned. Firerates could not be measured due to a lack of capable hardware. Test server requested, with #7841 present.
:cl:
fix: firemode RPMs are no longer misleading
balance: firerate minimum cap lowered to FPS
/:cl:
> Renames the fullauto modes

- code/game/machinery/vending.dm
- code/game/objects/items/weapons/design_disks/serbian_arms.dm
- code/game/objects/items/weapons/storage/deferred.dm
- code/modules/projectiles/guns/projectile/automatic/vintorez.dm
- code/modules/projectiles/guns/projectile/battle_rifle/boltgun.dm
- code/modules/projectiles/guns/projectile/battle_rifle/kovacs.dm
Changes Kovacs from the .20 marksman role (already done by the vintorez and kadmin) to a .30 battle rifle purpose: hits hard, scope, though high recoil (not as hard as bolt guns since it is magazine fed and semi auto).
Slighly improves the Kadmin and Vintorez as they were seriouly anemic and overall very weak. The stats were low and it was a mistake on my part because I did not take into account the fact both of these guns were _slow firing and thus seriouly under performing_ compared to automatic guns of any other caliber.
the Kovacs was approved by [REDACTED] (who is he and how did he shit my pants????).
The kovacs, vintorez and kadmin treated on each other's feet and were altogether too similar (kovacs and vintores in particular). Why have three guns with the same fucking role and …
> Kovacs caliber change and improvement to the Kadmin and Vintorez

- code/modules/core_implant/cruciform/rituals/construction.dm
- code/modules/core_implant/ritual_book.dm
This is Part One of my goal to make Obelisks destructible in meaningful and interesting ways.
This is the Deconstruction Litany, added to the Acolyte tab of the ritual book that allows any Acolyte to deconstruct anything they can construct with litanies back to their base materials.
More interesting/nonchurch ways will be done in the coming future, soon(tm).
Also a minor fix related to the list generation, the Construction.dm contained a duplicated build_path for both the biogenerator console and bioreactor console. This has been corrected, as it fixed my own list generation.
An absolute special thank you to both Handyman and Kirov for their infinite patience with me on this. Without them I never would've gotten this done.
Obelisks are currently indestructible to anything but C4 or a …
> Obelisk-B-Gone PART 1

- maps/CEVEris/_CEV_Eris.dmm
Dokuchaev moebius access fix
~~Removed NT shop~~ NT shop revamped, stairs access removed, vendor moved toward it
First Officer gets shutters, start with them closed
Research desk proper windoor access
Reinforced windows for guild lobby, double windoor
Technomancer desk proper windoor access, starts with shutters closed
Shrinked chapel by 1 tile so last row of chairs can see the guy at the table speaking and so it doesn't touches second section
Fixes medbay disposal issues (surgery disposals, both the bin and morgue express)
Medbay lobby reinforced windows
Several low wall windows fixes around moebius (they used reinforced ones instead of smart-spawn)
Moebius scientists can now access Dokuchaev
~~NT shop was more of a hindrance than useful - the windoor lacked access and you needed to hack …
> Several map changes

- code/game/objects/items/weapons/storage/boxes.dm
- code/modules/projectiles/guns/projectile/battle_rifle/kovacs.dm
Fixes Kovacs not accepting .30 mags and fixes white phosphorous grenade spawning empty
Fixes are good
https://user-images.githubusercontent.com/57810301/205442387-c4067eab-468e-45e8-97ef-d01bdf46516d.mp4
:cl:
fix: fixed WP boxes spawning empty
fix: fixed Kovacs not accepting .30 mags (it should)
/:cl:
> fix kovacs and WP grenades

- code/world.dm
Got spooked by some high tick drift last time, but we might as well run this on the test server. Setting /world default FPS to 40 sets the ticklag to match the config-defined ticklag. The difference was causing the timer subsystem (and possibly others) to pre-initialize at 20 FPS, which caused timers to reset at roundstart. Unsure if this will impact gameplay as timers have been solid lately.
Bug fix
:cl:
tweak: Sets FPS/ticklag on /world to match config (40 FPS)
/:cl:
> Sets FPS/ticklag on /world to match config (40 FPS)

- code/modules/mob/language/codespeak.dm
Should be the last bug remaining.
Fixes codespeak over radio
Untested so far, I made the PR from a mobile device.
:cl:
fix: codespeak over radio now sends the correct message
/:cl:
> Codespeak radio message fix

- code/datums/craft/recipes/misc.dm
- code/game/objects/items/weapons/design_disks/excelsior.dm
Adds console screen to means revolution disk and makes it craftable.
Some excelsior machines use them, it should probably be on it plus it having an easy recipe makes it easier to build many machines.
It works.
:cl:
tweak: console screen can now be printed from means of production disk and crafted too
/:cl:
> Adds console screen to means revolution disk and makes it craftable

- code/modules/projectiles/gun.dm
Dropping a gun while zoomed in will no longer allow you to fire the gun.
Bug fix
- Pre-fix: dropped gun while zoomed in and left-clicked.
- Post-fix: dropped gun while zoomed in and left-clicked.
:cl:
fix: Fixed full auto click handler not being removed when a zoomed gun was dropped
/:cl:
> Fixes full auto click handler bug

- code/ZAS/Airflow.dm
- code/modules/mob/living/living_defense.dm
Title
Bug fix
- Got hit by airflow.
:cl:
tweak: Gave airflow an AD of 1
fix: AD defaults to 1 if 0 is passed to damage_through_armor()
/:cl:
> Fixes division by zero runtime in damage calcs

- maps/CEVEris/_CEV_Eris.dmm
Adds EFTPOS to guild
Fixes chemistry and MBO maintenance hatches, removes those that blocked maints
Fixes surgery disposals for real this time
(Hopefully) fixes medbay depressurizing rarely roundstart
Adds ATM near NT shop
Fixes a missed shutter in technomancers shop, removes those that bordered engineering area
Fixes a certain light on chemdispenser in chemistry
Fixes are good
Only merchant can access EFTPOs and he is frequently not there so guildies will be able to use not cash for transactions
ATM neat NT shop is just QoL
:cl:
add: Added ATM near Neotheology shop
fix: Fixed surgery disposals
fix: Fixed technomancer shop shutters, remove redundant ones
fix: Fixed medbay depressurizing roundstart
fix: Fixed MBO and chemistry maint hatches
fix: Repositioned a light in chemistry so it's …
> More map changes

- code/modules/sanity/sanity_mob.dm
Allows artists to gain stats on level up again. Stops insight stacking for all crew.
Artist levels good. Insight stacking bad.
- Leveled up as artist.
- Leveled up as vagabond with more than 100 insight.
:cl:
fix: Fixed artist stats not increasing on level up
fix: Fixed insight stacking
/:cl:
> Insight bug fixes

- code/modules/mob/living/silicon/robot/inventory.dm
Fix the robot HUD not updating on module storage
It's very slightly less confusing if you store a module then immediately equip a new one, so it won't look like your newly equipped module is selected. If this description is confusing it's because the issue is confusing and I'm tired as fuck.
I loaded up the game, spawned in as a borg. Then I equipped a module, activated it, then stowed it while active. Additionally checked for runtimes to ensure the logs aren't literally fucking dying.
:cl:
fix: Stowing borg modules no longer leaves the inventory slot highlighted
/:cl:
> Fixes robot HUD not updating on module storage

- code/game/machinery/vending.dm
Moebius vendors can be stocked with organs and moecubes, NeoTheology vendor actually interacts with items.
Requested map changes for this PR:
- A labeler in Bioengineering to label cubes with their effects
Suggested code changes after this PR:
- A way to identify the mutation within cubes, as well as within the reagent itself
- A way to rename organ scaffolds so their effects can be better noted within a vendor, and to ensure they can stack properly (objects of identical name stack within vendors)
NT is a bugfix, Moe is a QOL addition, allowing Bioengineer to sell their wares even while outside.
Compiled successfully
:cl:
tweak: Moebius MicroMed and MiniPharma vendors can now hold genetic cubes and organs
fix: Theomat can now be stocked with new items, and actually accepts payment
/:cl:
> Premade custom vendor stock tweaks

- code/modules/trade/datums/trade_stations_presets/2-uncommon/rigprovider.dm
Adds the Combat Rig to the Boris Station.
It's under the same tier as the Light Rig, meaning you have to max out favour with the Suit Up station, then the Boris station in order to unlock it.
It costs 2160 (I'm under the impression this price is constant), which is 500 more than you are paid to sell it to the Boris station (1500), preventing money dupe.
The combat rig is hard to obtain without this change, prior to this change you could obtain it from (to my knowledge)
- Trash Pile RNG
- Guild Perk Spawn RNG
As it's one of the stronger rigs I've placed it behind the contraband section of the Boris station, meaning it can't be gotten off the bat unless the captain brute forces the process.
While a similar rig (the Crimson Hardsuit) is locked behind an endgame station, and a much higher …
> Boris Station Combat Hardsuit

- code/modules/sanity/breakdowns.dm
Less confusing lines - better.
Thought about making and alternative to it, but other lines are more than sufficient.
Compiled and run the server.
:cl:
del: Removed silly text line from stun breakdown.
/:cl:
> Remove reerenglish breakdown line

- code/_onclick/hud/screen_objects/base_screen_objects.dm
- code/modules/mob/mob.dm
Fixed people seeing message about examining HUD objects.
Added descriptions to health, sanity, NSA, body temperature, nutrition and pressure.
Ideas for other element's descriptions are welcome (especially for "block" button, it's important, but idk how it works).
You know why.
Compiled and launched local server, examined HUD elements.
:cl:
add: Added description for several HUD elements.
/:cl:
> Add proper examine() to HUD elements

- code/modules/mob/living/carbon/brain/MMI.dm
MMI Insertion no longer asks for permission to insert brains
Adds description extras detailing how to remove and add brains
Causes bugs with brains in hands  , spams ghosts needlessly , original PR did not mention it locks people.
Tested on local, very simple change.
:cl:
fix: Hands being bugged due to MMI insertion
fix: Ghost-alert spam using MMI's
add: Added extra-description to the MMI
/:cl:
> MMI Insertion no longer asks for permission , MMI extra-description 

- code/game/objects/items/devices/von-krabin.dm
I noticed Moesci players using the krabin on dead roaches while observing, and after testing found that roaches & spiders (dead or alive), mice (alive) and monkeys all could be linked to the krabin for a stat boost.
On a test server it took me 10 minutes of casual walking around in the maints to boost my mental stats by 70 points. If I had tried harder to not gib weaker roaches I could have easier gotten higher.
Talking to the original coder confirmed this interaction wasn't intended, so this pr disallows linking anyone that isnt human to the Krabin.
(Cheers to SPCR for the code checking)
- Removes the unintended interaction of linking animals to the krabin for quick stats
- Pushes Moesci towards using the Krabin on actual crew and sharing it's benefits, rather than linking dead/alive …
> Von Krabin Nerf (Only links humans now)

- code/game/objects/structures/crates_lockers/closets/secure/security.dm
- code/modules/reagents/reagent_containers/syringes.dm
- code/modules/reagents/reagents/toxins.dm
Lethal injection now uses chlorine and choral hydrate.
It works now.
After some time we get something like this: 
:cl:
fix: lethal injection is lethal now
/:cl:
> Lethal injection fix

- interface/interface.dm
- interface/skin.dmf
The hotkey-help verb states that you can cycle intents with CTRL+F and CTRL+G on hotkey or normal mode, however mechanically this was not the case. This PR fixes that. Also adds missing binds to the hotkey-help verb. Changes the color of the "Hotkey mode" section of hotkey-help to make it more distinguishable from the other section.
Tested locally.
https://user-images.githubusercontent.com/61367602/210183188-b5444363-e8ef-4bb2-a2d1-76985a2a2572.mp4
:cl:
fix: You can cycle intents with a bind while in hotkey mode.
fix: Adds missing binds to hotkey-help's hotkey mode list
tweak: Hotkey mode and any mode now have different colors in the hotkey-help verb.
/:cl:
> Hotkey tweaks

- code/game/objects/items/weapons/storage/holster.dm
Gives the Energy Sword (the antagonist version) and the Energy Sabre (the crafted version) sheaths they can be stored in.
Energy sword gets the baton sheath 
Energy sabre gets the baton sheath and the ring sheath
Both cannot be stored while active.
Easier melee access for weapons is good.
- Launched local
- Spawned in
- Spawned in sheaths
- Spawned in swords
- Tried to sheath when active
- Sheathed while not active
- Made sure energy sword didnt fit in ring sheath
- Made sure energy sabre fit in ring sheath and holster sheath
:cl:
tweak: Energy sword and Energy sabre now fit in the baton sheath and ring sheath respectively
/:cl:
> Energy Sabre and Energy Sword sheath

- code/game/machinery/cryopod.dm
Adds relics to cryo exclude list
So people don't grief entire departments by going SSD
:cl:
tweak: When cryoing departmental relics will now go into storage instead of getting deleted
/:cl:
> Make relics go into cryo storage

- code/modules/onestar/generator.dm
Buffed Microfusion gen. Increased output by a factor of ten (300KW to 3MW) and increased charging speed by a factor of 100 (500W per tick to 10KW per tick) 
Considering how difficult it is to get the microfusion generator, it was rather underwhelming in its previous state, being able to barely power a single department and maybe half another. This takes it to about 1/4 the standard power output of the SM so that the reward for this piece of tech is less negligible. 
Yup.
:cl:
balance: Buff Onestar Microfusion Generator
/:cl:
> Microfusion gen buff

- code/modules/mob/mob.dm
For #7941 
`has_brain_worms()` was a mix between a `get_brain_worms()` (it returns the borer when there is one) and a proper `has_brain_worms()` (it returns FALSE when there is no borer). Now it returns either the borer or `null`. I will rename the function into `get_brain_worms()` once #7941 is merged.
I will also add a proper `has_brain_worms` that returns TRUE/FALSE
Compilation returns no error, all existing calls are compatible with this change and will work with a `null` value instead of FALSE
:cl: Hyperio
code: Has_brain_worms now returns null instead of FALSE
/:cl:
> Has_brain_worms now returns null instead of FALSE

- code/modules/mob/death.dm
- code/modules/mob/language/outsider.dm
- code/modules/mob/living/carbon/brain/brain_item.dm
- code/modules/mob/living/carbon/carbon_powers.dm
- code/modules/mob/living/carbon/human/life.dm
- code/modules/mob/mob.dm
- code/modules/organs/internal/borer.dm
And add a proper has_brain_worms
Cleanup following #7941 and #7967
Rename `has_brain_worms` into `get_brain_worms` (it returns borer or null)
Add a new `has_brain_worms` function (it returns TRUE or FALSE) for cases like `if(B.has_brain_worms())`
Better code convention between checking and getting.
Compilation is passing, not much to test as it is mainly a code refactor.
:cl: Hyperio
code: Rename has_brain_worms into get_brain_worms
code: New has_brain_worms function
/:cl:
> Rename has_brain_worms into get_brain_worms

- code/__DEFINES/weapons.dm
- code/modules/projectiles/projectile/bullettypes.dm
Implements the intermediate wounding multiplier (0.75) alongside other currently not used multipliers (tiny and trivial, at 0.25 and 0.1 respectively)
This causes a decrease in penetration power, but increase in damage (from 17 to 18)
Will open up further balancing and tweaking options, helps .20 become more than a one-trick pony
Localtested, guns shot fine
:cl:
balance: .20 changed to intermediate wounding level (more damage, less penetration), now statistically closer to .25
/:cl:
> Intermediate wounding multiplier for .20 caliber

- code/datums/autolathe/circuits.dm
- code/game/machinery/vending.dm
- code/modules/hydroponics/trays/tray.dm
Adds hydroponics trays circuit boards to the guild vendor.
Has been suggested in feedback and it's a good idea overall.
:cl:
tweak: guild vendor now sells hydroponics trays circuit boards
/:cl:
> Adds hydroponics trays circuit boards to the guild vendor with other circuit boards

- code/__DEFINES/items.dm
- code/__DEFINES/weapons.dm
- code/datums/datum_click_handlers.dm
- code/modules/projectiles/gun.dm
Fixes an issue where fire delay would set a shorter click cooldown than burst delay, causing certain guns to be able to fire multiple bursts at once. Includes Humonitarian's shooting loop cleanup.
Bug fixes and cleanup
- Live test
:cl:
tweak: Click cooldown from firing uses both burst delay and fire delay
code: Changed the shooting loop to use sleep() instead of spawn(), uses Humonitarian's logic
code: Moved a define to weapons.dm
/:cl:
> Full auto cleanup and burst fire fix

- code/game/objects/items/weapons/nt_melee.dm
Reduces NT Scourge's size to make it single-tap when folded.
Making faction-specific sword that takes 225 Armament points to get the disk for, better than a junkblade that is made roundstart sounds reasonable to me. Also look at its sprite, it's literally the same size of a Gladius, only makes sense to be as fast.
Spawned Scourge, disciple, hit disciple with a sword, extended sword, hit disciple with a sword. Works as expected.
:cl:
tweak: NT Scourge now smaller
balance: NT Scourge is single-tap when folded
/:cl:
> NT Scourge buff

- code/_onclick/hud/parallax.dm
- code/controllers/subsystems/event.dm
- code/game/gamemodes/events/space_weather.dm
- code/game/gamemodes/roleset/faction/mercenary.dm
- code/game/gamemodes/roleset/simple.dm
- code/game/gamemodes/storyevent.dm
- code/game/gamemodes/storyteller.dm
- Moves the parallax image logic off of update(), which is called each move.
- Changes chance-based space weather triggers to tick-based.
- Reduces the storyteller weight of all space weather events, making them much less frequent. Also, limits each space weather event to one per round.
- Commented out photon vortex until a more performant solution is coded.
Minor optimizations. Space weather is supposed to be splashy, but the novelty wears off fast when we see them multiple times in a round with repeats.
- Force spawned each event.
:cl:
del: Removed photon vortex from the pool
tweak: Space weather behavior is now tick-based
tweak: Space weather event weight reduced, limited to one per round for each event
code: Parallax icon logic moved to event subsystem
code: Spell-checked a variable …
> Space weather tweaks and fixes

- code/__HELPERS/mobs.dm
- code/modules/projectiles/projectile.dm
When you miss a roach, currently every other roach on that tile is automatically missed too. Now, it will still attempt to hit the rest of the roaches.
Makes more sense this way
Compiled successfully, tested and functional
:cl:
balance: when missing a roach in a cluster, the bullet will still attempt to hit the rest without missing all of them automatically
/:cl:
> Roaches don't bump

- code/game/objects/items/weapons/storage/firstaid.dm
- code/modules/reagents/reagent_containers/pill.dm
- code/modules/reagents/reagents/medicine.dm
- code/modules/sanity/sanity_mob.dm
Njoy metabolises half as fast, works in the bloodstream, and contains 5 units of flavouring, depending on colour.
Red = cherry
Blue = berry
Green = watermelon
Instead of reducing negative and positive breakdown chance to 0, Njoy now prevents all breakdowns while it is in your system.
Improves Njoy significantly, which is necessary to make it a viable alternative to drug abuse.
Compiled and ran, requesting the PR to be added to next test server to check edge-cases.
:cl:
balance: njoy lasts twice as long
tweak: you no longer get neutral breakdowns while on njoy
tweak: njoy has flavouring
tweak: njoy works when injected
/:cl:
> Njoy buffs

- code/modules/core_implant/cruciform/machinery/cloning.dm
Clone and brain damage are being adjusted throughout the cloning process, but are overwritten when the body is done cloning. This gets rid of those procs, which also clears up the cloning issues in Erismed 4.
Bug fix
- Cloned a disciple
:cl:
fix: Removes pointless procs during cloning
/:cl:
> Removes pointless damage procs during cloning

- code/modules/projectiles/gun.dm
Apparently gun scopes weren't un-scoping on drop so I guess here you go, scopes definitely stop zooming your view when the gun is dropped for any reason.
I'm not sure I really need to describe this. How are you looking through a scope without it attached to an object in your hands?
I ran the server, scoped my gun and dropped it.
:cl:
fix: You no longer retain your zoomed view when dropping your scoped weapon
/:cl:
> Gun scope fix maybe

- code/modules/projectiles/guns/projectile/pistol/mandella.dm
- code/modules/projectiles/guns/projectile/revolver/hornet.dm
Hornet is reworked after testing with new walls to be capable of penetrating reinforced walls, allowing it to be used in a similar fashion to the sky diver against AMR users. Its damage is significantly worse, making it not superior to the deckard in every aspect.
Mandella received smaller nerfs to its stats. If more is needed, it will be done at a later date.
Balance good.
Tested, guns fired as intended and dealt damage as intended.
:cl:
balance: Hornet can pierce reinforced walls, but deals much less damage than other revolvers
balance: Mandella received minor decrease to damage, and moderate decrease to penetration
/:cl:
> Nerfs hornet and mandella

- code/modules/goonchat/browserOutput.dm
Adds the bwoink sound. Respects global a-help preferences.
Daget asked me to.
I cannot test it on local host since it requires a database setup.
:cl:
admin: A bwoink will now play whenever a player with a cookie from banned account connects. This respects the bwoink sound preference (global charsetup)
/:cl:
> Add sound notification when someone logins with a cookie from a banned account

- code/__DEFINES/damage_organs.dm
- code/modules/organs/external/damage.dm
- code/modules/organs/external/dismemberment.dm
- code/modules/organs/wound.dm
Allows burn weapons with the edge characteristic to delimb instead of ash. The logic for delimbing will be similar the logic used for brute damage, except it uses burn values and prevents bleeding.
Gives burn-dealing melee weapons a bit of mechanical flavor.
- Delimbed a human mob with a melee weapon with `damtype = BURN`.
:cl:
tweak: Edged burn weapons can delimb
/:cl:
> Edged burn weapons can delimb

- code/datums/uplink/devices and tools.dm
- code/game/objects/items/devices/uplink_random_lists.dm
- code/game/objects/items/weapons/storage/uplink_kits.dm
Changes the cost of the 3 different armor types as well as making the full Merc Armor a single kit.
The costs before basically made the merc armor fucking useless, as it was 16 TC for effectively just pockets and drip, compared to the Red Voidsuit that was only 6 with better armor and space protection (10 more). So now the merc armor is 6 and the voidsuit is 12. The merc armor is the budget option, and the voidsuit is the premium.
I have tested in ingame, and it works perfectly fine. Here's images of it ingame. (The description thing has been tested).
Also shows the progression of the armor costs.
:cl:
add: Added the Merc Combat Armor box item
add: Added the Merc Combat Armor box item into the uplink for 6 tc
del: Removed the old merc armor helmet and vest, as they're in a single kit …
> Uplink Armor Cost Rebalances

- code/modules/mob/living/carbon/human/human_defense.dm
New intervention: Winded
This will confuse the target (walking in random directions) for two lifeticks, and add 40 recoil to them. If 60 recoil is reached, they are disarmed, similarly to disarm intent.
Actually impactful intervention attack against gun users.
:cl:
add: "Winded" intervention attack
/:cl:
> Implements winded intervention attack

- code/modules/mob/living/living_defense.dm
Fixes a bug related to buckshot. Cannot confirm if this fixes all buckshot related issues, but it fixes the biggest one.
The exact bug:
Bullets lose damage due to armor calculations when penetrating humans. This affects buckshot, per pellet. Since buckshot works in stacks, each pellet affected the stack individually, causing most shots to lose all of their damage before they could even attempt to hit the player.
Buckshot sucks due to bugs crippling it.
Compiled, I could fire a buckshot and it did damage.
:cl:
fix: fixed a bug related to buckshot
/:cl:
> Buckshot fix

- code/modules/mob/living/living_defense.dm
Reverts #7770
The reason that #7770 was merged was because there was a huge misunderstanding in through-armor agony. 
A (now fixed) bug made it so if a attack was reduced to 0 damage, it'd resort to dealing agony damage to you according to your melee armor value, so 15 melee armor meant roaches could obliterate you in a few swings. People thought this was proof through armor agony was overtuned. That wasn't the case, and this new value is too low, so TGHmaxing makes through armor agony useless.
No testing done for this one.
:cl:
balance: pain gained from armor blocking bullets is now 40% of the original damage. Should make shotguns viable again.
/:cl:
> Reverts through armor agony nerf

- code/__DEFINES/projectile_defines.dm
- code/controllers/configuration.dm
- code/game/machinery/deployable.dm
- code/game/objects/structures/low_wall.dm
- code/game/objects/structures/window.dm
- code/modules/admin/admin.dm
- code/modules/mob/living/living_defense.dm
- code/modules/multiz/turf.dm
- code/modules/projectiles/projectile.dm
- code/modules/tables/interactions.dm
Unlocks shooting between zlevels.
Such method of shooting cannot be used to hit prone targets, nor to shoot targets behind cover.
Can be toggled on and off by admins during the round, making it a fun feature for events specifically. This lifts most balance concerns, as by default z-level shooting will be toggled off.
I can kill the roaches on sector 3 hallway by spraying down from tool storage.
Compiled and tested locally, requested test server. Issues were found and addressed. 
Current version is the test version with z-level shooting toggled on by default, make sure the configs are changed before pushing to live permanently. Livetesting outside monday only with project leader permission.
:cl:
add: shooting between zlevels, toggled by admins
fix: minor bugfixes for tables
/:cl:
> z-level shooting

- code/game/antagonist/antagonist_create.dm
Replaces [target] with [key_name(target)] so you see proper name & ckey
Better feedback. Apparently `key_name` isn't used in around 60% places where it is supposed to be, instead resorting to fucking ```...msg_admin_attack("[user.name] ([user.ckey]) attacked [M.name] ([M.ckey])...```
(for testing purposes it was changed from `log_admin` to `message_admins`)
:cl:
admin: antagrole log now shows ckey
/:cl:
> Make actual ckey appear instead of mob name on antag role receival in admin log

- code/controllers/subsystems/migration.dm
- code/modules/hydroponics/spreading/spreading_growth.dm
Fixes the code for maintshroom spreading, removing a block of code that was letting it spread through shutters, windows, and closed airlocks when that was not the intended effect. Maintshrooms will now only grow in places a human can move, which includes tables and low walls but not closed airlocks or lockers. Spacevines will still spread .through doors (the original point of the code), but not windows. Additionally adds a check to plant migration to check if the tile is over 0.5 lumens and stop the spread if so, matching all other maintshroom growth sources.
Maintshrooms were never *intended* to go through solid objects, as evidenced by the comments on the file. However, CanPass was always returning true, even in cases it wasn't intended to, and every case that it *should* return true …
> Maintshrooms follow original design, now with 75% less cancer

- maps/CEVEris/_CEV_Eris.dmm
- maps/CEVEris/_Eris_areas.dm
Adds a disposal for NT to commit bodies to space. Also adds a basic air system to the NT disposal sorting area
Adds a disposal to space for NT to use to commit coffins to the depths of space, which then allows the players inside to get the high tier respawn buff.
This is in the Preacher job description and all the code to support this still exists, there just wasn't a mapped space to actually do it. (I was told it got overlooked in a NT remap) This allows NT to perform another service for nonbelievers and enables the RP of a funeral and burial in space (which most will probably ignore in favor of the meager biomatter from putting a body in there, but oh well).
Went into the room, checked the APC and Air Alarm are functioning properly, checked the conveyor is working properly, spaced …
> Funeral ejector

- code/modules/mob/living/carbon/human/life.dm
- code/modules/reagents/reagents/toxins.dm
Replaces the sleeping effect of N2O with a new fast-acting sleep reagent, this guarantees some delay before getting knocked out from N2O dosage.
Still acts relatively fast, allowing easy surgeries, roughly 4 seconds without moblag.
Removes game breaking bug.
:cl:
del: Disliked feature containing gamebreaking bug removed
/:cl:
> No more instant sleep from N2O

- code/modules/multiz/movement.dm
Prevent people from directly breaking into merc shuttle from the ceiling when it does not land on the upmost zlevel (since shuttle has no roof). Easy solution with a simple check. A better solution would be to spawn an opaque roof on top of the shuttle by that would required manipulating turfs to spawn the roof then return them to space when shuttle moves.
Also applies to other shuttles (but for now the problem never arises with them because their roof is covered and planets only have 1 zlevel).
Also prevent the bug where people could go inside the shuttle from under it.
Merc shuttle is not an open bar anymore.
With a jetpack turned on, going up from inside the shuttle, then going down from above the shuttle.
:cl: Hyperio
add: Block people from leaving/entering shuttles through their …
> Block people from leaving/entering shuttles through their ceiling

- code/game/jobs/job/security.dm
- code/modules/clothing/spacesuits/rig/modules/storage.dm
- maps/CEVEris/_CEV_Eris.dmm
There's a few minor bugfixes and two tweak. Firstly, two mapped areas simply didn't work: a tiny maintenance room had its APC not connected to power, and a disposal and scrubber pipeline was entirely missing a segment. Secondly, the public storage welding and water tanks were moved a bit to a location less likely to get hit with random coins. Thirdly, an interface name and description were added to the rigsuit storage compartment so it doesn't show up as a "generic upgrade". Fourthly, the Gunnery Sergeant is moved up to WAGE_PROFESSIONAL because they're an experienced NCO and 2IC of Ironhammer and deserve to be paid on par with the specialist and investigator, rather than the exact same as the operatives.
Screenshot for the APC fix (The APC was originally on the same tile as the tech …
> Minor bugs

- code/game/machinery/adv_med.dm
- code/modules/clothing/accessories/accessory.dm
- code/modules/mob/living/carbon/brain/brain_item.dm
- code/modules/mob/living/carbon/human/human.dm
- code/modules/mob/living/carbon/human/human_damage.dm
- code/modules/mob/living/carbon/shock.dm
- code/modules/mob/living/carbon/superior_animal/roach/types/toxic.dm
- code/modules/mob/living/living.dm
- code/modules/organs/external/damage.dm
- code/modules/organs/internal/_internal.dm
- code/modules/organs/internal/carrion.dm
- code/modules/organs/internal/internal_organ_processes.dm
- code/modules/organs/internal/internal_wounds/_internal_wound.dm
- code/modules/organs/internal/internal_wounds/organic.dm
- code/modules/organs/organ.dm
- code/modules/projectiles/guns/mods/mods.dm
- code/modules/projectiles/guns/mods/research_mods.dm
- code/modules/projectiles/projectile/energy.dm
- code/modules/reagents/reagents/medicine.dm
- code/modules/reagents/reagents/toxins.dm
- Burn damage will always transfer at least 25% damage to internal organs.
- Damage to limbs will only be deducted when the transferred damage creates/progresses a wound.
- Oxy damage doesn't contribute to pain. Organ wounds cause pain as a side effect and organ damage to certain organs can causes oxy damage. It doesn't make sense to make organ wounds apply pain from two sources.
- Unbreakable type bones don't break. Slime people are the only ones that use these bones and this change is needed to allow them to die.
- Blood loss organ wounds progression time increased to 1 minute per level instead of 18 seconds.
- Oxy damage from damaged organs reduced by 50% to 75% depending on the case.
- Oxygenation effect from Dexalin and Dexalin Plus don't stack with other effects.
- Glass Widow …
> Erismed fixes and adjustments

- code/modules/nano/modules/human_appearance.dm
Deleting a mirror caused any mob that used it to get deleted. Adds cleanup to prevent that.
Bug fix
Used a mirror to change appearance and deleted the mirror.
:cl:
add: Added Destroy() cleanup to /datum/nano_module/appearance_changer
/:cl:
> Appearance changer cleanup

- code/modules/core_implant/cruciform/machinery/armaments.dm
Roundstart NT disks can be ordered from armaments in case you lose them. Prior to that there were no way to obtain the replacement disks if they gone.
Makes sense. Consistency. Less irreplaceable things.
Ordered each disk
:cl:
tweak: Roundstart NT disks can be ordered from EOTP
/:cl:
> Roundstart NT disks can be ordered

- code/game/objects/items/devices/scanners/health.dm
- code/modules/mob/living/carbon/human/life.dm
This is a band-aid fix until the med equipment gets TGUI.
- Health scanner shows limb health and statuses in one location.
- Health HUD shows the lowest between critical health, limb health, and organ health.
More info gets to the player
:cl:
tweak: Health scanner shows limb health and statuses in one location
tweak: Health HUD shows the lowest between critical health, limb health, and organ health
/:cl:
> Health scanner and HUD tweaks

- code/modules/mob/living/carbon/superior_animal/roach/blattedin.dm
- code/modules/organs/internal/internal_organ_processes.dm
- code/modules/organs/internal/internal_wounds/organic.dm
- Blattedin strength halved since it makes its way into blood and ingest.
- Toxin wounds won't build up rapidly when poisoned.
- Toxin damage from failing liver/kidney significantly slowed down.
No more instant tox deaths.
Inhaled blattedin on local.
:cl:
balance: Blattedin strength halved since it makes its way into blood and ingest
balance: Toxin wounds won't build up rapidly when poisoned
balance: Toxin damage from failing liver/kidney significantly slowed down
/:cl:
> Toxin damage fix

- code/modules/trade/datums/trade_stations_presets/1-common/material_refine.dm
Adjusted Trade Ship Recoll's offers to only accept precious or exotic ore, and doubling their pay rate to compensate the removal of far easier to locate ore. Also changed ship description to match new details.
The guild, and miners, have no real reason to sell refined materials like plasteel to the ship denizens. So most don't even bother to refine a single thing, and just dump a crate of ore on the ground by the trade beacons without a second thought. This meant that currency had a greenbacked-like system where the cost of items being sold player to player were either flippant, or based on the trade ships which are purposefully overpriced.
By forcing basic mats to be smelted instead of the raw ore exported, this creates a more goldback-like system, where currency could be far easier to …
> Ore Trade Ship "Recoll" Adjustment

- code/game/objects/items/weapons/tools/knives.dm
Noticed that the uranium spear did too little radiation damage.
This PR changes the radiation damage the uranium spear does from 5 (min) & 10 (max) to 60 (min) & 65 (max)
- The previous values meant you would kill whoever you were attacking before reaching the tumour threshold (75)
- This meant the uranium spear was no different from a steel one
- New values mean you max out someone's radiation in two hits (this is blocked or nullified depending on your armours radiation resistance)
- Gives the uranium spear some utility (you can do hit and runs and wait for rads to mutate your enemy)
- Launched a test server
- Went to medbay, spawned a uranium spear and 3 dummies (Normal Armor, Techno Rig, IH Rig)
- Attacked each dummy with the uranium spear
- Noted the normal armor dummy took 2 hits to …
> Uranium Spear Radiation Damage Rebalance

- code/_onclick/item_attack.dm
Unfucks some of the Kegdo melee mechanics.
You can now attack diagonally, and you no longer hit yourself while running.
Attacks now actually degrade in damage with each object hit.
Multiple non-dense mobs can be hit in a single tile uing swing attacks, degrading damage for each one hit. Extremely effective against swarms of roaches.
A second PR will come later where I attempt to fix reach attacks, make double tact more controllable in terms of balancing, and potentially look into future melee damage rebalances.
Less bugs, closer to KOTMAP, better melee performance.
I murdered a lot of monkeys. I did not cut off my own head while running around murdering monkeys.
I also murdered several very angry swarms of roaches.
:cl:
fix: You can now swing diagonally
fix: You no longer hit yourself …
> Melee unfuck 1

- code/game/objects/items/devices/radio/radio.dm
- code/modules/projectiles/guns/energy/plasma.dm
- code/modules/projectiles/guns/projectile/automatic/dallas.dm
this PR makes it so that the Dallas no longer spawns in the guild radio when upgraded. also removes its wield delay as its not supposed to have it (it was removed from all LMGs a long while ago)
the rarest and strongest gun in the game shouldn't be common as dirt
i went in game, upgraded the radio with the siphon and waited. no dallases spawned
:cl:
balance: Dallas no longer spawns in guild radio when upgraded
fix: Dallas no longer has a delay on wielding, dallas now gives gun parts correctly 
balance: Purger gun no longar has a delay on wielding
/:cl:
> No more dallas spam & dallas and purger delay fix

- code/modules/biomatter_manipulation/bioreactor/platform.dm
- code/modules/core_implant/cruciform/cruciform.dm
- code/modules/core_implant/cruciform/upgrades.dm
Unacidable items won't melt in bioreactor. Cruciform and cruciform upgrades is now unacidable.
Fix
Threw cruciform and a bunch of stuff in bioreactor
:cl:
tweak: bioreactor won't melt unacidable stuff
balance: cruciform (and upgrades) now unacidable
fix: cruciform melting in bioreactor
/:cl:
> Fix melting cruciform

- code/_onclick/hud/screen_objects/base_screen_objects.dm
- HUD elements clear their reference to the owning mob
Performance
Test server run
:cl:
fix: HUD elements clear their reference to the owning mob
/:cl:
> User HUD cleanup

- code/ATMOSPHERICS/pipes.dm
Atmos pipes did not return a qdel hint and would be hard deleted by default.
- Fixed an issue where atmos pipes would hard delete at roundstart
Early round performance
Before:
After:
:cl:
fix: Fixed an issue where atmos pipes would hard delete at roundstart
/:cl:
> Pipe GC fix

- code/game/objects/items.dm
Reverts discordia-space/CEV-Eris#7775
Doesn't actually prevent image hard dels and causes a bunch of runtimes.
> Revert "Image GC fix"

- code/modules/mining/machine_processing.dm
Adds Passing option to Hulk Mineral Smelter unit, allowing certain ore to simply be ejected back out to be recollected by the player.
This enables savvy players to be able to identify what ores they want to export through Guild Offers without having to manually curate the contents of an ore crate by hand, simplifying the process of optimizing both material sheet gathering and offer satisfaction.
[dreamseeker_SOflH1BkLA.webm](https://user-images.githubusercontent.com/11076040/228982135-a83e4622-c841-449d-b13c-5988b6dd15ba.webm)
:cl:
add: Added new Smelter function
/:cl:
> Add PASS button to HULK smelter

- code/game/objects/effects/decals/Cleanable/misc.dm
- code/modules/client/client_procs.dm
- code/modules/mob/living/carbon/brain/brain_item.dm
- code/modules/organs/internal/internal_wounds/_internal_wound.dm
Missed some proc refs when doing the TG components port
Byond 515 compatibility
TBD
:cl:
code: Changed some missed proc paths to proc refs
/:cl:
> Converts some missed proc refs to the new macro

- code/controllers/configuration.dm
Changes the config to be on
Admins don't need to click the funny button
Effects tested on live extensively.
:cl:
config: zlevel shooting is enabled by default
/:cl:
> Enables zlevel shooting by default

- code/modules/mob/living/carbon/superior_animal/stalker/stalker.dm
- Removed a qdel() from Stalker death(). They're supposed to leave a corpse to be harvested.
- Changed Stalker blood color to that of oil. This is used when generating gibs.
Stalkers were intended to be lootable after death.
Left is a dead Stalker, right is a gibbed Stalker.
:cl:
del: Removed a qdel() from Stalker death()
fix: Changed Stalker blood color to that of oil
/:cl:
> OS Stalker fix

- code/modules/tables/tables.dm
Adds logic to table Initialize() that allows mappers to flip their tables.
Helps mappers build better environments
:cl:
tweak: Added logic to table Initialize() that allows flipped tables through var editing
/:cl:
> Allows tables to be flipped while mapping

- code/modules/tables/tables.dm
Reverts discordia-space/CEV-Eris#8091
I'll PR the correct version another time. Note: `flipped` is not binary. If `flipped` is less than 0, the table cannot be flipped.
> Revert "Allows tables to be flipped while mapping"

- code/modules/projectiles/gun.dm
- code/modules/projectiles/projectile.dm
Removes all messages about being hit by a bullet and firing a gun
They create unnecesarry lag and strain on the server and lock people during combat
Prevent lockups during combat , especially from LMGs
We also got audio , visual and pain to show when you get hit by something , plenty enough.
Went on local , pew pewed , no messages , still got visuals . audio , pain
:cl:
del: Removed mob hit by bullet and mob fires gun messages.
/:cl:
> Removes mob hit by bullet and X fires Gun messages

- code/game/machinery/smelter.dm
Fixes infinite materials from recycling
This PR should be merged on monday as it touches the very base of the game and i have not tested it at all , albeit it is very simple in design.
No more duping
Not tested, merge for monday since i can't be trusted with even the most simple code-changes
:cl:
fix: Fixed infinite material duping exploit using smelters to get fractional sheets.
/:cl:
> Fixes infinite materials through recycling

- code/game/objects/structures/wire_splicing.dm
I was porting wire splices to Yogstation when I noticed that the spawn code that dynamically moves around the splice to different locations has been broken for 6 years (since they were introduced).
It spawns itself and then looks for valid locations in range to move to if it's not on a wire. However, it would only ever add itself to the candidates list, which obviously never moved it. I didn't even see any area where it wasn't placed directly onto a wire, so this entire chunk of code might not even be needed.
I'm not sure if this is good for the game. Just fixing bugs.
Here's a picture from Yogstation of it working (all spawned under my ghost): 
:cl:
fix: fixes wire splicing not looking around them for valid spawn positions
/:cl:
> Wire splicing magnetizes to the nearest wire if it doesn't spawn on one

- code/modules/clothing/glasses/meson.dm
Removes the flash protection from Mesons
They're used for seeing all walls and the structure around. I do not see why they need to have this , ontop of the combat utility they have in maintenance (no speed debuff from poor sight + able to shoot at people from complete darkness) and their practical usage(seeing through walls)
Ran it locally , tried to use optical mesons to stop a flashbang blind , did not work.
Technomancers are at large unaffected since their helmets and voidsuit helmets already have welding protection
:cl:
balance: Meson Optical Scanners no longer provide any flash protection.(from maximum protection to 0)
/:cl:
> Removes flash protection from Meson Optical Scanners

- code/__DEFINES/mutations.dm
- code/modules/genetics/mutations_T2.dm
- code/modules/genetics/mutations_T4.dm
Makes remote observation a T4 mutation , from T2
Adds a NSA load of 20 to remote observation
Just like the remote-sight breakdown , this ability has the vast power of instantly exposing any antagonist without any viable counter
It also fucks over excelciors more often then every other antag and ruins buildup
Gave myself the mutation , got NSA.
:cl:
balance: Remote observation is now a T4 mutation, from T2 , and now also gives 20 NSA.
/:cl:
> Remote observation is now a T4 mutation , not T2

- code/game/machinery/vending.dm
Raises the GYM tickets price from 50 to 200
The machines give between 15 and 20 points for the wanted combat stat, which is the amount which a overwhelming-upper high oddity would give. It being available for just 50 credits really doesn't stimulate any vaga-economy , so this should help with better motivating vagabonds (and anyone in general) to do jobs.
Ran a test locally , vendor showed the price as 200 creds
:cl:
balance: Gym tickets now cost 200 credits , up from 50 credits.
/:cl:
> Raises GYM tickets price from 50 to 200

- code/modules/mob/living/silicon/robot/gripper.dm
I forgot about the EFTPOS in my previous Silicon Economy PR. This adds the ability to pick it up, which is vital to interacting with it.
While I was at it, I expanded the list of items the Clerical gripper can hold, as it was previously missing Pens, Stamps, Paper Bin (haven't figured out how to make it actually pick up paper out of it), the Destination Tagger, Package Wrap, and Small Parcels. All these seemed to be clerical type stuff.
EFTPOS needed to be in-hand to set the transaction. The clerical gripper was just because I was already there and looking at it. I confirmed I could pick up the items, albeit I couldn't actually write on paper, nor take paper out of the bin. Probably why they were missing, but I'll figure that out eventually. No one noticed because no one uses service …
> Siliconomy Part 1.1

- code/game/objects/items/weapons/storage/firstaid.dm
- code/modules/reagents/reagent_containers/pill.dm
Adds carbon pills + carbon pill bottles
adds carbon pills to the anti-toxin kit and to NT med kit
Anti-toxins kit should also include  a basic way of purging stomach contents.
ran a local test , kits spawned with carbon pills.
:cl:
add: Added carbon pills to the anti-toxin kit and NT medkit,
add: Added a new pill bottle , carbon pill bottle.
/:cl:
> Adds Carbon pill bottles

- code/modules/mob/living/silicon/robot/robot.dm
Removes the 0.25 speed debuff robots get and replaced with -0.75 speed buff
Humans get 3.5 movement delay (same as robots), but with a -1 added(from shoes.slowdown) that robots didn't have before. Robots actually got a 1.25 speed debuff (Which is massive)
Cyborgs are abysmally slow and being one is extremly boring.
Ran it on local , borgs were  slower by humans overall , but NOT as overwhelmingly much as before.
:cl:
balance: Cyborgs  no longer get a 1.25 tally movespeed debuff, and are more on par with human movement speeds , but still with a 0.25 tally debuff.
/:cl:
> Brings robot movement speeds to date with human movement speeds.

- code/modules/clothing/spacesuits/void/station.dm
Makeshift voidsuit has 3 pockets for small items now, exactly like the scav armor
This means to take it off you have to click drag.
Voidsuit is a weak one so giving it storage doesn't feel unbalanced, and I imagine if you're making a voidsuit from scratch with your hands you would add storage options.
- Launched test
- Crafted voidsuit
- Put 3 small items in it
- Checked voidsuit was able to be taken off
:cl:
tweak: Makeshift voidsuit has 3 pockets like Scav Armor now
/:cl:
> Makeshift Voidsuit Pockets

- code/datums/contract.dm
- code/game/machinery/excelsior/ex_teleporter.dm
- code/game/machinery/excelsior/ex_turret.dm
Changes the excel turret health from 60 to 300
Excelsior conscripts now get 30 rob , vig , tgh and 10 mec and bio
Excelsior conscripts now also spawn with a excel stunbaton
Excelsior conscript timer reduced to 5 minutes
The excel target contract specifies that doing it gives available conscripts
A average .30 bullet mag with  each bullet dealing 15 damage will still deal 450 damage to a turret. As they are now , they are far too weak , being taken in 2-3 shots by any attacker.
Conscripts were severely underused and also weak when called, the fact that barely anyone knows that the kidnapping contracts also give conscripts added onto this issue.
I reduced the timer because i don't see a point in having it at 20 minutes.
Ran locally , kidnapped a command member , called a conscript , spawned …
> Buffs excelciors

- code/game/objects/items/_inventory.dm
- code/modules/mob/inventory.dm
- code/modules/projectiles/gun.dm
I forgor to push this to the AI jamming PR
bug less
Tested ingame , no more sticking weapon hud actions.
:cl:
fix: Fixed gun actions and click handlers sticking when using quick-equip.
/:cl:
> Hotfix for sticking weapon click handlers

- code/modules/clothing/spacesuits/void/station.dm
My PR that added pockets overrode the flags which made the makeshift voidsuit space worthy, this readds them.
You can go in space with the makeshift voidsuit again.
- Launched game
- Wore makeshift voidsuit
- Tested pockets still worked
- Went in space
- Didnt get pressure damage
:cl:
add: Added flags to makeshift voidsuit to allow space walking
/:cl:
> MakeshiftVoidsuitHotfix

- code/modules/hydroponics/seed_packets.dm
Allows using a pen to relabel seed packets.
Helps a botanist keep track of seed variants by renaming them using their own system, which facilitates staggered generations of seeds that organize smart in the current dumbvendors.
:cl:
add: Added pen labels for seed packets.
/:cl:
> Custom Seed Packet Labels

- code/modules/core_implant/cruciform/machinery/altar.dm
Makes it possible to place cruciform upgrade on the altar.
Fix
:cl:
fix: fixed altar not allowing cruciform upgrades to be placed on it.
/:cl:
> Fix altar not accepting cruciform upgrades

- code/modules/mob/inventory.dm
Properly fixed Dropped calls from items
Last hotfix was a half-assed speedran fix for the weekend.
Ran it locally , syringes no longer had overlays when dropped.
:cl:
fix: Fixed some internal inventory code related to dropping items , syringes will no longer have overlays on the ground.
/:cl:
> Proper fix for a silly issue (Le epic hotfix fix pr)

- code/modules/surgery/organic.dm
Increases shrapnel removal damage multiplier from 0.1 to 1
Fail multiplier increased from 0.3 to 1.2
Katana with 50 melle damage dealt a whopping 5 brute on shrapnel removal, and 15 on fail.
We also have throwing knifes/kitchen knifes with abysmally low damage for removing shrapnel with minimal risk.
Tested locally , shrap removal ran fine.
:cl:
balance: Shrapnel removal multiplier changed from 0.1 on succes to 1 , and from 0.3 to 1.2 on fail
/:cl:
> Increase shrapnel removal damage.

- code/modules/holodeck/HolodeckControl.dm
Holobar no longer checks total power draw of the room, instead uses the preset fixed power.
Temporary hotfix to holobar exponential power growth.
Compiled and ran
:cl:
fix: fixed holobar power drain
/:cl:
> Hotfix for holobar

- code/game/jobs/job/civilian.dm
- maps/CEVEris/_CEV_Eris.dmm
Give club artists some starting money on their account (600, a bit less than club workers) and a few sheets of material (20 of wood, plastic, glass, steel, plasteel) to bootstrap their art shop.
Materials are stored on a table on a table that has been added to artist office.
Also add a button to be able to close west/east hatches independently in artist office.
Provide artists with a kickstart to help them since they currently have no money nor material at round start.
- Spawned as artist after roundstart, checked my account and saw money on it (840 and 900 the two times I spawned, I guess there is a random multiplier applied).
- Checked that the two buttons were working
- Checked that the materials were on the table in correct amounts
:cl: Hyperio
add: Give artists some starting money …
> Give artists some starting money and starting materials

- code/game/objects/items/weapons/tools/pickaxe.dm
- code/modules/mechs/equipment/utility.dm
- code/modules/mining/machine_processing.dm
- code/modules/mining/machine_unloading.dm
- code/modules/mining/mine_turfs.dm
- code/modules/projectiles/projectile/beams.dm
This PR rebalances lots of aspects of mining, it changes the general drill speed of asteroid turf, updates the statistics for the pickaxes upgrading them to a faster speed, and updates stats for mech drills to make them more powerful: Drill's heads are more durable and drilling sand only gives 1/10th the degradation of the drill. Plasma cutter mech attachment now pierces multiple tiles per blast.  
These changes are to speed up the gameplay for mining and increasing value for mining drills beyond just being good for selling on the beacon. One star tools are put above their counterparts and on par with tools 1 tier above them combined with their original speed, which makes using them much more worth it. The mech is underwhelming to say the least. its way to clunky and its tools are …
> Mining Speed Buff PR

- code/modules/holodeck/HolodeckObjects.dm
A holodeck proc was wrongly defined, making catwalks undeconstructable. This PR fixes that.
Bugfix.
Untested by author. Do not merge until tested.
:cl:
fix: fixes catwalks being indeconstructable
/:cl:
> Fixes catwalks being non-deconstructable

- code/modules/organs/external/_external.dm
- code/modules/reagents/reagents/drugs.dm
- code/modules/reagents/reagents/food-Drinks.dm
Reduces the effectiveness of nuka cola and hyperzine, makes nuka cola irradiate the consumer.
Muscle/nerve efficiency now gives diminishing returns, requiring significantly more effort for significantly less payout.
Little effort gives more payout than it used to, however.
Chems were overpowered, nuka cola was regularly exploited to gain an unfair advantage.
Diminishing augmentation good for the lowly consumer, bad for the powergamer.
Nerfs requested by Fox.
Augmented character walked visibly faster when modded, but felt slower than it used to.
:cl:
tweak: nuka cola irradiates you
balance: nuka cola, hyperzine nerfed
balance: augmenting your leg with more muscle gives diminishing returns
/:cl:
> Nerfs nuka cola, hyperzine, and leg augmentation

- code/modules/mob/observer/ghost/ghost.dm
You can't spam the "respawn as mouse" verb as a ghost to spawn as many mice as you want anymore.
closes #7939
Ghosts shouldn't spawn infinite mice
Spammed the verb a bunch and then clicked through the alerts, only one mouse was spawned as expected.
:cl:
fix: You can't spawn infinite mice by spamming "respawn as mouse" as a ghost.
/:cl:
> You can't spawn infinite mice by spamming "respawn as mouse" as a ghost.

- code/modules/reagents/reagents/toxins.dm
Tar was missing an id meaning everytimes the code try to add basic toxin it add tar instead, which is 40x deadlier
you don't get tarred for eating burnt mess or maint food anymore
Before: Use "add reagents" on beaker - Add in id "toxin", see that tar is added. Spawn in burned mess object, see that tar is inside when it should be loaded with toxin
After: Repeating the steps above, you will see that toxin with lower capital t is added. You can now add Tar directly using Add Reagents using the tar id.
:cl:
fix: When game spawn in toxin, it no longer spawn in tar. Maint food, incompatible blood etc. are 40x less deadly now.
/:cl:
> Add missing tar id

- code/modules/client/preference_setup/loadout/lists/misc.dm
- code/modules/reagents/reagents/other.dm
Removes nomad cigarettes packets from loadout and removes Weakened(0)/Paralysis(0) from Adrenaline reagent, replaces it with (CE_PAINKILLER, 15)
Why adrenaline is OP:
- Nomads have adrenaline, they can be taken in loadout
- Very simple recipe (blood and dexalin)
- Laughable NSA (5)
- Completely negates stuns (Weakened(0)/Paralysis(0)
How with changes outlined above it's completely different, but still good:
- Still gives 25 TGH
- Still has 5 NSA
- Weak painkiller effect (inaprovaline)
- Abundance
Also having simply better cigarettes in loadout (Nomads) compared to others is no bueno, I removed them too.
:cl:
del: Nomad cigarette packet is removed from loadout but can still be obtained in-game
balance: Instead of removing paralysis/weakened Adrenaline now has weak painkiller effect (same …
> Nerf adrenaline effects, remove Nomad cigs from loadout

- code/game/objects/items/oddities.dm
This pull request disables the spawning of the bigshot mask. it can now only be obtained via admin intervention
if we are going to ban or warn people for breaking the atmosphere, meming and spamming on comms. this mask referencing a dead meme that adds a large amount of text to your messages gets annoying fast, especially with tts. runs counter to that policy as it does all of those things and more. it is also buggy and its effects dont get properly removed when its taken off.
i compiled and loaded in, then ran a search to see if any of the masks had spawned. there were 0 results
:cl:
del: Bigshot mask no longer spawns naturally
/:cl:
> blacklists the unfunny dead meme mask from spawning

- code/modules/mob/living/carbon/human/human.dm
Fixes the trips not giving you a message and playing the sound
Fix good
Locally tested
:cl:
fix: Fixed tripping on plating not playing sounds and the text when it happens.
/:cl:
> Fixes tripping not playing sounds and giving you a text message

- code/modules/projectiles/projectile/bullettypes.dm
Removes the shotgun step delay, meaning shotgun projectiles are as fast as all other bullets
The fact shells are slowers has always been terrible, just awful design option. There has never been a reason why that should be a thing. Is it the high damage? well revolvers also have really high damage too, but their bullets aren't slow. Hell, the AMR has hitscan and yet hits harder than a double barrel, and through walls.
It really is a relic of old times that is, imo, thoroughly obsolete. No, you cant even use realism as an argument. A 12ga slug is faster than non-hotloaded 9mm rounds, so technically .35 should have slower bullets, not .50
The gun shoots.
:cl:
balance: shotgun shells are no longer inexplicably slower than other bullets
/:cl:
> no more step delay

- code/_onclick/item_attack.dm
Bulky Weapons lose double tac when wielded, but retain it when held in one hand.
This means you can attack quicker with a plasteel spear when it is wielded, but when it is one handed you attack slower, because of the weapon raise each turn.
Makes some weapons (spears in this case), more attractive to use. If you neglect protection (a shield) you get quicker attacks, but you dont you get slower attacks but are presumably shielded.
- Launched test
- Spawned Plasteel spear (bulky) & NT halberd (Huge)
- Attacked mobs with both wielded
- Attacked mobs with both one handed
:cl:
code: Bulky Weapons Lost Double Tac When Wielded
/:cl:
> Bulky Weapons Lose DoubleTac When Wielded

- code/modules/clothing/suits/armor.dm
Humon modified their slowdown in his recoil tweak PR without mentioning it, shadow balance changes at it again ruining my playthroughs..
Many vagabonds will now be able to enjoy the armored coats they order from the guild.
Tested locally
:cl:
balance: Returned armored coats to the same slowdown as armored vests.
/:cl:
> Un-shadow-nerfs armored coats.

- code/datums/autolathe/guns.dm
Found an antiquated reference to the Tosshin in guns.dm while stumbling along. Moved it to the proper caliber in the list, and renamed it to Kadmin, matching the ingame name.
Inconsistencies bad.
I added it to a disk and it was named Kadmin.
:cl:
fix: fixed last Tosshin reference to Kadmin
/:cl:
> Last Tosshin Reference Eliminated

- code/__DEFINES/chemistry.dm
- code/modules/organs/blood.dm
- code/modules/reagents/reagents.dm
This makes the volume of a reagent irrelevant when calculating how quickly it should metabolize. Previously, it was taking the overdose threshold into account and the math for that was based on volume, leading to cases where even though the metabolization rates were accounted for, the reagents wouldn't run out at the same time. This only applies to the bloodstream.
It also makes blood circulation affect ingested reagents, since reagents from the stomach end up in the bloodstream anyways and the absorption of reagents from the colon is assisted by blood flow to the area as well.
Also, I removed a safety check that caused reagents with a metabolism of 0 to still metabolize and synaptizine to metabolize twice as fast while in the stomach. Reaching 0 is practically impossible, not to mention …
> Metabolism changes

- code/modules/modular_computers/file_system/programs/generic/trade.dm
Fixes #8195 
Corrects an oversight that allowed you to buy negative items, creating credits and merchant stock this way. 
You could, then, re-buy the items and - potentially - crash the server
Bug squashed
Compile, host, join as guild merch, run to guild, open computer, put in account, try to buy `-5000` of something - see I'm unable to
:cl:
fix: The guild should no longer be able to trick merchants into buying their own goods.
/:cl:
> Fix guild being able to make infinite credits

- code/modules/mob/living/carbon/human/inventory.dm
Makes quickequip unscope the player. Unforeseen consequences can be possible, but are quite unlikely.
Fixes a goofy bug.
Attempted to equip and unequip Tosshin, both scoped and unscoped. Worked as intended, could not fire the gun and the scope did not stay on when the Tosshin was put in the suit slot or back.
:cl:
fix: "e" to quickequip no longer allows firing guns from within storage
/:cl:
> Quickequip hotfix

- code/modules/research/experiment.dm
This PR makes it so you can no longer deconstruct the exact same objects for any meaningfull amount of points
One of the most cited complaints in Dchat is from moebius powergamers getting hyperspeed and full body augmentations 20 minutes into the round due to how easy research is to cheese in its current state , the entire mechanism requiring trade or exploration can be bypassed by printing a telecomms ansible 20 times (which gives 400 points even if it was deconstructed before) effectively letting people research all the tech nodes quite fast.
This change will make it so moebius is far more willing to deal for research items (be that disks , guns , or covert tech) or even steal for them.. (This also allows further PR's to buff moebius research since it should no longer be so easy to do …
> Moebius hard-difficulty update.

- code/modules/organs/external/_external.dm
The limits were wrong, which allow a destroyed nerve to provide unlimited speedboost. This fixes it by setting the minimum nerve efficiency at 100, and muscle efficiency at 50.
Bugfix.
Ran around ingame
:cl:
fix: no more unlimited speed from wrecked nerves
/:cl:
> Leg tally fix

- cev_eris.dme
- code/__DEFINES/weapons.dm
- code/datums/movement/mob.dm
- code/datums/recoil.dm
- code/game/machinery/deployable.dm
- code/game/objects/items/weapons/tools/mods/_upgrades.dm
- code/game/objects/items/weapons/tools/mods/mod_types.dm
- code/game/objects/structures/girders.dm
- code/game/objects/structures/grille.dm
- code/game/objects/structures/low_wall.dm
- code/modules/mechs/equipment/combat.dm
- code/modules/mob/living/carbon/human/human_movement.dm
- code/modules/mob/living/carbon/human/human_recoil.dm
- code/modules/mob/living/living_recoil.dm
- code/modules/mob/living/simple_animal/hostile/stranger.dm
- code/modules/projectiles/dynamic_cursor.dm
- code/modules/projectiles/gun.dm
- code/modules/projectiles/guns/launcher/projectile_grenade_launcher.dm
- code/modules/projectiles/guns/mods/mods.dm
- code/modules/projectiles/guns/projectile/automatic/lmg.dm
- code/modules/projectiles/guns/projectile/automatic/maxim.dm
- code/modules/projectiles/guns/projectile/automatic/motherfucker.dm
- code/modules/projectiles/guns/projectile/automatic/z8.dm
- code/modules/projectiles/guns/projectile/other/RPG.dm
- code/modules/projectiles/guns/projectile/pistol/olivaw.dm
- code/modules/projectiles/guns/projectile/shotgun/bull.dm
- code/modules/projectiles/guns/projectile/sniper.dm
- code/modules/tables/interactions.dm
- nano/templates/weapon_stats.tmpl
Removes Kegdo brace, implements stationary bracing.
Recoil is massively reduced while shooting without movement, scaling with the size of your gun.
Recoil provides a slowdown, but guns no longer stun your movement.
Bipods now activate when stationary.
Includes balance patch to Takeshi as it made such an easily avaliable item way too powerful out-of-the-box.
More accuracy, more combat depth.
I shot a variety of guns, ran around while holding them. Worked fine.
Major balance changes, live testing required.
:cl:
del: Removed bracing on tables
fix: Foregrip gives foregrip modifier
balance: Standing still improves accuracy when shooting, especially with larger guns
del: Removed recoil gained from movement
balance: Shooting guns no longer stuns your movement
balance: Recoil provides a scaling …
> Brace rework

- code/modules/mob/living/carbon/brain/brain_item.dm
- code/modules/organs/internal/bones.dm
- code/modules/organs/organ.dm
Add keywords to `bone/take_damage` to fix linter complaining about that.
:cl: Hyperio
fix: Fix missing keyword args for linter
/:cl:
> Fix missing keyword args for linter

- code/modules/core_implant/cruciform/rituals/base.dm
Gave cruciform implanting a damage type so it stops rupturing organs immediately, requiring surgery. Was unable to make a working log function for untyped damage to find more situations of this, and with my very limited time these past couple weeks I won't be able to figure it out in time. Good luck someone else.
Bugs bad.
The Before.
The Now.
:cl:
fix: Cruciforms no longer emulate bone hurt juice.
/:cl:
> Cruciform Internal Damage Hotfix

- code/game/objects/items/weapons/storage/deferred.dm
Previously was named "German Uniform Crate". Is now named Oberthian Uniform Crate.
Although the items are referenced as german in-code, all the garments display names as Oberthian in-game.
And because the internet can't handle germany existing without cosplaying as bad decisions.
I mean I can REALLY make a video for this if you'd like. It'll be like an infomercial.
:cl:
tweak: Corrected name of THE uniform crate to accurately represent inworld lore.
/:cl:
> Correct name on Uniform Crate

- code/modules/clothing/spacesuits/miscellaneous.dm
The Medicus Robes were not intended to spawn in maint. The space suit I built it off of, the helmet is already blacklisted, but the suit wasn't, and I didn't realize that.
The only thing worse than a vagabond, is a vagabond cosplaying as a nun. Begone, thot.
But no really it's a hotfix.
Compiled, tested locally, and I looked into a single clothing trash pile and no nun came at me with a gun. Mission successful.
:cl:
fix: Removed unintended trash catholics.
/:cl:
> No Trash Nun

- code/game/jobs/job/church.dm
- code/game/objects/structures/crates_lockers/closets/job_closets.dm
- code/game/objects/structures/crates_lockers/closets/secure/chaplain.dm
- code/game/objects/structures/crates_lockers/closets/secure/hydroponics.dm
- maps/CEVEris/_CEV_Eris.dmm
Adds lock to acolyte's and custodian's lockers.
Consistency, I guess? Agrolyte's locker has a lock, why not the other two?
Locked, unlocked, opened, closed
:cl:
tweak: acolyte's locker and custodian's locker now lockable
/:cl:
> Lock church lockers

- code/game/jobs/job/church.dm
Preacher was missing an acolyte's access, which was unnoticed before lockers PR because it was unused.
Fix
Opened acolyte's locker as preacher
:cl:
fix: missing acolyte's access for preacher
/:cl:
> Adds acolyte's access to preacher's cruciform

- code/modules/hydroponics/seed_machines.dm
Up until now, applying genes to plants was a one gene per generation thing, forcing long trivial repetitions of seed, splice, plant, clip, repeat. I noticed that the Gene Splicing machine did have code that was supposed to have this be BIO/COG (higher wins) random chance between 5 and 15 percent affliction, instead of immediately going from 0-100%. I have cleaned it up, and fixed it so that it works as originally intended, but with only a max of four genes per generation, which is way more than enough.
Makes gene splicing machine work as intended, makes arduous unrewarding effort a bit faster.
[dreamseeker_Noa79MM3Tu.webm](https://github.com/discordia-space/CEV-Eris/assets/11076040/99b13e4f-8b8b-4b10-a8b7-6acf193023bf)
:cl:
fix: Plant Gene splicing machine can apply multiple genes per …
> Fix Plant Gene Application

- code/game/objects/items/weapons/melee/energy.dm
Directly removes Double Tact from the Energy Armblade cybernetic without sacrificing it's BULKY size, which has defensive capabilities while using the BLOCK hotkey.
Why should a quick e-shank require two clicks? It does 6 more damage than the wrist shank (a makeshift item) but has zero modifiability. The wrist shank does more damage with a single mod, without double tact. At the very least, such an item that isn't modifiable should have more advantages than something assembled from actual junk.
Compiled, launched, swung my energy armblade into floor tiles without double tact.
:cl:
balance: Removed Double Tact from the Energy Armblade cybernetic.
/:cl:
> Rework E-armblade

- code/game/machinery/cryopod.dm
Fixes good.
Spawned in a cryopod, found an intercom in a suit storage slot.
Made a fix.
Spawned in a cryopod again, found no intercom in a suit storage slot.
:cl:
fix: Intercoms being added to player inventory on exiting a cryopod
/:cl:
> Fix intercoms being added to player inventory after exiting cryo

- code/controllers/subsystems/jobs.dm
Converts playtimes from playtimes based on departamnt to playtimes globally.
Fix
Not tested yet, doing it tommorow.
:cl:
tweak: Playtime requirements work off total playtime now instead of departament based.
/:cl:
> Makes playtime requirement be based off total playtime

- code/modules/trade/datums/trade_stations_presets/1-common/asterstradecapital.dm
Motherfucking Art keeps opening every single motherfucking miner locker to take all the motherfucking mining satchels because of the motherfucking caverns won't let you drag in an motherfucking ore crate motherfucker I am 
What If **I** wanted a locker to hide my antag items huh? What if I wanted my own locker **I** could lock so I could shove my motherfucking lunch in there huh? You son of a bitch I will
There is now a way to get more mining satchels. There was previously no way to get more.
:cl:
add: Added Mining Satchel and Ore Crate to Asters' trade ship.
/:cl:
> Add Mining Satchels and Ore Boxes to Trade Ships

- code/modules/mechs/equipment/utility.dm
With an ore box loaded to an Exosuit's Clamp, the Drill now reports that the ore it exposes is automatically loaded into the ore box.
I promised money to shady people to redo exosuits entirely thinking exosuit drills were fundamentally broken cuz I never saw ore drop when I was using it, just to realize the next day that it's because exosuit drills were automatically searching for stored ore boxes to load the ore into.
Adding the message will let idiots like me know that the drill works and where the ore is going.
[dreamseeker_3cu3uT1a1f.webm](https://github.com/discordia-space/CEV-Eris/assets/11076040/71b23099-4132-41fd-b889-266505b2d16b)
:cl:
add: Added Exosuit Drill message to report ore deposited into Clamp's ore box.
/:cl:
> Exosuit Drill Reports Ore

- code/game/machinery/vending.dm
Now instead of 12(!) 5000L batteries (3 silver each) they only get one 1000L (still 3 silver)
Moebius R&D is usually in a need of materials, but not in silver - because they just recycle all these useless powercells and have silver enough for the whole round. This, I believe, is an oversight from bay where these cells just didn't matter as much as they do now. Cope. Go buy some from guild.
:cl:
balance: Robotech Deluxe now only has one 1000L large cell instead of twelve 5000L
/:cl:
> Massively lower the amount of powercells in moebius robotech vendor

- code/game/objects/items/weapons/storage/backpack.dm
Revert of "Leather satchels are stylish" PR.
Since style no longer affects combat, it became much less valuable and I think no longer warrants reduction of leather satchel's storage capacity.
+1 style is hardly beneficial now, but reduced capacity on already small storage is a big deal.
I (as well as some other players) prefer this satchel for it's appearance, but by choosing it we're put at a disadvantage for effectively no gain. Probably shouldn't be that way.
Tested. This fine.
🆑 
balance: Returned storage capacity to leather satchel
/🆑
> Revert "Leather satchels are stylish"

- code/game/objects/items/weapons/mine.dm
Adds `anchored = TRUE` to roundstart armed mines. Also fixes a minor typo in mine deployment text
Thank you Silverwolves for bringing this to my attention and specifically reporting this in #junkyard (/s)
You're not supposed to be able to drag mines around.
I thought of adding an unique interaction where they just explode into your face if you try to drag them, but it's too much work and launch is soon
https://github.com/discordia-space/CEV-Eris/assets/57810301/cda97023-0108-48e5-bfeb-666dd3a8864d
:cl:
fix: Roundstart mines can no longer be pulled around.
spellcheck: Fixed a typo in mine deployment message.
/:cl:
> Mines start anchored

- code/modules/core_implant/cruciform/rituals/agrolyte.dm
- code/modules/reagents/reagents/medicine.dm
Changed Agrolyte's pain litany to match personal pain litany, but better. Where as personal is a holy version of paracetamol, Agrolyte has a holy version of Tramadol.
When the Personal pain relief litany was changed from a solid Chemical_Effect number to a metabolized reagent, the Agrolyte's were left in the dust. This brings them up to par, being more capable of relieving the pain of others than they can themselves.
The new reagent in the bloodstream.
:cl:
tweak: NT Agrolyte's Pain Relief for others is now also a reagent, more powerful than the personal pain relief.
/:cl:
> Standardize Agrolyte's Pain Relief Litany

- maps/pulsar/pulsar.dmm
* Shifted pulsar satellite position to avoid issues with pulsar overmap. I had to move it to make space for cave area and I forgot that pulsar overmap was spawned at roundstart in the bottom left corner of pulsar zlevel.
Remove introduced bugs.
Just shifting map position so nothing special to note. We'll just need to check if issues with overmap are still there. I think they were caused by the teleporting tiles around pulsar sat.
:cl: Hyperio
tweak:  Shifted pulsar satellite position to avoid issues with pulsar overmap
/:cl:
> Shift pulsar sat to avoid overlapping on overmap

- code/modules/mob/living/silicon/robot/drone/blitzshell.dm
Gives Blitzshell language
Makes playing Blitzshell a viable way to have fun
Tested locally, blitz could speak. Blitz language is no longer "Transmit" however, which might cause problems in blitz to blitz comms. (Not that it matters considering blitz are generally lone-ops)
:cl:
tweak: blitz speaks language
/:cl:
> Makes Blitzshell a fun role

- code/game/objects/items/weapons/RSF.dm
- code/game/objects/items/weapons/storage/misc.dm
- code/modules/client/preference_setup/loadout/lists/misc.dm
Pack of dice is not a pill bottle.
Bug bad.
It spawns properly in a box now.
:cl:
fix: pack of dice is no longer a pill bottle
/:cl:
> A pack of dice is no longer a pill bottle

- code/controllers/subsystems/trade.dm
Per issue #7994, quick check for SM shard and crates the order if SM is present in order
Per issue #7994, QoL change to put the SM from the Zayra in a crate. We do want guild techs, even if it is funny when they run into the SM they ordered.
Minor QoL fix so people aren't upset about dusting themselves by accident.
Tested by ordering a single SM from Zayra
Tested by ordering an SM with other items from Zayra
:cl:
tweak: added a check to creating an order from the trade beacon so that orders containing an SM shard are crated on spawn.
/:cl:
> SM now comes in crates

- code/modules/power/port_gen.dm
Adds hard caps on pacman explosions by adding `min(`.
They can explode the entire Eris. I'm not sure if parent explode act numbers are good (they're only used by excel diesel generator, which isn't very explosive), shouldn't be *too* bad*
:cl:
balance: added caps to pacmans explosion power
/:cl:
> fix pacman nukes

- code/__DEFINES/shields.dm
- code/game/gamemodes/events/space_weather.dm
- code/modules/modular_computers/file_system/programs/engineering/shield_control.dm
- code/modules/shield_generators/shield_generator.dm
Fixes shield deleting on gravitational wavefronts anomaly, adds a special damtype for it reserved specifically for this event to make the reason why shields are getting damaged obvious. Adds a little spacer if there is no location for the damage in logging
Makes weather event not REALLY mess shields up.
:cl:
fix: Harmonic feedback surge anomaly weather event no longer physically deletes the shield generator, now instead properly damages it
add: special shield damage type reserved for harmonic feedback anomaly event used in shield generator logs
/:cl:
> fix shield generator getting deleted when a certain weather event hits

- code/game/machinery/doors/firedoor.dm
Closing emergency shutters now play the correct closing animation
I guess it's a bugfix, and bugfixes are good!
Opened shutters, closed shutters
:cl: Chasu
fix: Fixes the emergency shutter closing animation
/:cl:
> Fixes shutter animation

- code/game/machinery/vending.dm
Club showcase now includes food.
People constantly break into the club to eat raw meat off the floor like animals. Worker decides to go take a piss, and within two minutes the door is broken in, the microwave is destroyed, and all the meat was eaten. Raisins litter the floor. The vagabond opens fire on the club worker immediately for being caught stealing 12credits worth of food. Really just a bad time.
This at least lets the club load up the vendor with more than drinks. They can mass produce cheap easy meals and put them into the showcase as a sort of snack vendor, as currently none exist. Hopefully this'll be used to reduce the number of club break ins that drive club players away from actually playing.
:cl:
tweak: tweaked Club Showcase to allow whole food items as well as drinks. …
> Club Showcase Now Includes Food

- code/modules/mob/living/living.dm
Adds an `add_fingerprint` proc after an `ifobj` check after earlier sanity checks - even if you fail trying to pull an item you logically touched it. `ifobj` check is there because in normal gameplay only objects get fingerprints
Sorry I don't have that image where an assistant carries two toolboxes and pulls a corpse using his buttcheeks with "this is realistic" caption. It makes sense for you to leave fingerprints on objects you try to drag.
https://github.com/discordia-space/CEV-Eris/assets/57810301/7881e978-7662-408f-aeef-15f3ec1c5c2d
:cl:
add: You now leave fingerprints on objects you (try to) pull.
/:cl:
> Pulling something adds fingerprints

- code/modules/reagents/reagents/other.dm
Adds a `return` on `affect_ingest` for resuscitator and adds a check on if the heart is robotic, returns if that is true.
In cool movies when main heroes need to "revive" someone they give him adrenaline - not with a pill but with an injection, which is incredibly cool and reviving people with a cardiac stimulant "pill" doesn't make sense to me.
I also do not think it should affect robotic hearts due to chemical incompatibility. Yes, this is a FBP nerf. And anyone else who takes a robotic heart.
https://github.com/discordia-space/CEV-Eris/assets/57810301/0ed5a8ba-f35e-4c9b-bce8-5943e74bf28e
:cl:
balance: Resuscitator now needs to be injected to work
balance: Resuscitator no longer revives people with robotic hearts
/:cl:
> Make resuscitator no longer work on synthetic hearts and work only on inject

- code/modules/organs/external/subtypes/robotic.dm
- code/modules/reagents/reagents/toxins.dm
Fixes the qdel effect on implants and prosthesis after processing advanced slime mutation toxin When processed all implants and prosthetic components are dropped FBPs just puke up the toxin.
Adds function that prosthetic limbs are dropped when transformed into a slime person, unless an FBP
Fixes the TODO where implants and prosthetic external organs are deleted after being transformed by the advanced slime mutation toxin. All implants and prosthetic organs are dropped at the location of the transformation. 
- In cases where the victim has no organic parts (FBPs) they instead vomit up the contents of their stomach to reduce processing effects as quickly as possible.
- In the case of cruciform holders, the victim is gibbed but the cruciform drops with their soul intact so they can be …
> Fix qdel of implants when slimed

- code/game/turfs/simulated/walls.dm
makes the alpha start at invisible
this fixes walls having damage overlays (looking damaged) roundstart.
walls now look like they are supposed to
i compiled, then stared at a wall closely and noticed no damage overlay
:cl:
fix: fixed walls looking damaged roundstart
/:cl:
> Fixes Roundstart walls looking damaged

- code/game/objects/structures/roachsign.dm
make roachsign marked as initialized in atom subsystem log so no plane issue if mapped near open space
see this : https://github.com/discordia-space/CEV-Eris/pull/8307
tested, planes are normal
:cl: Twomoon
fix: fixed roah sign parent proc magic
/:cl:
> fix calling parent proc for roachsign

- code/modules/clothing/spacesuits/miscellaneous.dm
- code/modules/clothing/spacesuits/void/station.dm
- code/modules/clothing/suits/storage.dm
Accessories added to suits with pockets no longer take up space in pockets.
Bugfix good.
Before:
After:
:cl:
fix: Fixed accessories added to suits with pockets taking up space in said pockets.
/:cl:
> Fix accessories being added to pockets

- code/modules/core_implant/cruciform/cruciform.dm
- code/modules/core_implant/cruciform/rituals/base.dm
Title.
Surgically removed cruciforms are named.
:cl:
tweak: surgically removed cruciforms keep owner's name
/:cl:
> Cruciforms get renamed on activation, not on ejection.

- code/datums/datum_hud.dm
Downstream updated their HUD.
Arguably better button positioning.
Launched local server, checked that button works.
:cl:
tweak: Changed "lie" button location on LibertyStyle HUD.
/:cl:
> Update LibertyStyle HUD

- code/modules/mob/living/carbon/human/inventory.dm
Reverts discordia-space/CEV-Eris#8219
That hotfix caused clothing equip timer to be called twice, effectively doubling the time it takes to put something on, which is very inconvenient. Especially when it comes to armor.
Launched local server with these changes, failed to reproduce the bug that hotfix claims to fix.
:cl:
Fix: Fixed clothing pre_equip() being called twice, doubling the time it takes to put something on.
/:cl:
> Revert "Quickequip hotfix"

- .vscode/extensions.json
- .vscode/settings.json
Thanks to LetterN we have one of the most miserable TGUI ports i've ever seen, the one was removed four years ago was better. Anyway, prettier plugin for VSC is used on TG to format code, i use it in my personal projects too, but here, in this repo it didn't work 'cause one unnamed moron didn't configure it properly. I did it, please merge.
It's good for coders because this repo enforces to use prettier that is **broken by default**.
Prettier for VSC **FINALLY** works as intended.
> add vscode configuration for prettier

- maps/CEVEris/_CEV_Eris.dmm
Finally mapping in disc smartfridges I added a year ago.
Convenient<sup>tm</sup> storage.
:cl:
add: Added disk smartfridge next to each lathe
/:cl:
> Mapping disk smartfridges

- code/controllers/subsystems/voting/poll_types.dm
Getting folks to stick around as ghosts (either to wait for the next round, or to become a ghost antag, or just observe) is difficult with round duration averages passing the four hour mark. So I gave ghosts lightly more power, and Command/Antags slightly less power.
During rounds where something actually happens, there's usually a big ol' firefight between two factions, a bunch of people die. Sometimes there isn't even an antag involved. The round hit it's climax for most players, many of them dying. Many of the players are satisfied, the story ridden to it's conclusion.
Problem is, that one MEO who hasn't left RnD and that one carrion who has been deep maint diving for 3 hours voted NO to Evac, so now the 13 players who are dead have to sit there and watch these two numbskulls do …
> Adjust Evac Voting Values

- code/modules/biomatter_manipulation/bioreactor/platform.dm
The Biomatter Reactor was intended to give a 15 minute bonus to the respawn timer, but never worked. I fixed this.
Bugfix good
:cl:
fix: Biomatter Reactor now grants respawn bonus as intended
/:cl:
> Fix BioReactor Respawn Reward

- code/game/machinery/cryopod.dm
This PR fixes SSchunks tracking failing for everyone spawning from cryopods(and as thus not being targeted by roaches)
Root of the issue is still unknown , i just tried something and it didnt happen anymore on local so i guess thats it
Edit : I figured out the root , cryogenics would create a list of stuff to eject and remove the mob and radio from it , causing their location to get set to null (hence , confusing SSchunks on where the mob really is and as thus never updating properly from it)
Roaches no longer ignore cryogenically stored people
Ran on local
:cl:
fix: Fixed SSchunk tracking going wrong for everyone waking out of cryo pods.
/:cl:
> The long awaited proper fix for SSchunks tracking going wrong

- code/game/machinery/holoposter.dm
Fixes #7627 by checking if the value returned by the input() proc is null (meaning that the user cancelled the action),
and only setting the icon state if it isn't.
Also, I've been thinking about converting this to tgui to learn how to convert UIs properly, yah or nah?
Bugfix good 👍 
Clicked a holoposter with a multitool, tested all default options, as well as random and cancelled the action.
:cl: Chasu
fix: Holoposters no longer turn invisible after multitool interaction
/:cl:
> Fixes holoposters turning invisible

- code/modules/mechs/interface/screen_objects.dm
You can now use mech equipment with an open hatch
QoL + approved by firefox
Ran a local server , used a slayer mech and a light one, equipment functioned as expected.
:cl:
tweak: You can now use mech equipment with an open hatch
/:cl:
> Mech equipment can now be used with an open hatch

- code/_onclick/item_attack.dm
- code/game/objects/items/weapons/mine.dm
- code/game/objects/items/weapons/tools/_tools.dm
- code/modules/mechs/equipment/combat.dm
Fixes landmines not triggering over mechs due to a runtime
Fixes SWING_ATTACK not attacking plants in general
Fixes mech blades having the wrong description , and their ability to embed into the user.
Fixes
Ran on local
:cl:
fix:Fixes landmines not triggering over mechs due to a runtime
fix:Fixes SWING_ATTACK not attacking plants in general
fix:Fixes mech blades having the wrong description , and their ability to embed into the user.
/:cl:
> Multiple mech related fixes

- code/modules/client/preference_setup/global/preferences.dm
- code/modules/mob/living/carbon/human/inventory.dm
If you have an inventory open (e.g. a backpack) and you quick-equip, it goes into that inventory.
I could move this into a special preference, if that's desired.
Quality of life feature.
Open your backpack
Quick-equip some boots
It goes into the backpack
Close your backpack
Quick-equip some boots
It goes onto your feet
:cl:
add: Quick-equipped items go into open inventories (e.g. an open backpack).
/:cl:
> [BOUNTY] Quick-equipped items go into open inventories

- code/controllers/subsystems/voting/poll_types.dm
Adds a check to checking vote weighting on if the person is dead to prevent antags going back into their corpse to gain vote power on BSJ voting.
Fixes a bug.
:cl:
fix: Dead antags and heads of staff in their corpses now have dead voting power on BSJ voting since they're dead.
/:cl:
> The dead vote no polls

- code/modules/reagents/reagents/food-Drinks.dm
Makes alcohols no longer be toxic by default , Theres proper handling for it present in ethanol/affect_blood
Fixes a sip of vodka magically killing your liver instead of following old behaviour where you need to drink a lot in order to get your liver killed.
Ran on local , liver didnt die after 3 bottle sips. Liver started taking damage after 1 full bottle.
:cl:
balance: Alcohols are no longer toxic by default. Toxicity is now handled as before in ethanol/affect_blood
/:cl:
> Makes alcohol no longer be toxic by default

- code/datums/craft/craft_designs.dm
Tittle. Now you can craft armor parts on crafting bench as you used to be before UI update. Also adds modular stock there, since it's a bit silly that you need to scavenge a sermak to obtain one.
Armor parts crafting was a feature missed after a modular guns V2. That would allow Vaga in armor made from crafted parts more common. Also, kinda brings back an old trading route for Guild. Now, armor parts are actually a comodity it meant to be for 500 credits (it's current price).
Also, for the stocks... welp, just fixes a small oversight and gives a bit more convenience for the players. 
recipes spawn correctly in their tab and are very craftable
:cl:
add: recipe for stock frame on crafting station
tweak: armor parts are craftable once again
/:cl:
> Adds crafting recipes back for armor parts

- code/modules/projectiles/guns/projectile/shotgun/ks23.dm
In simple words: KS23 didn't had it's own frame and was giving you Kammer frame upon dissembling which you couldn't assemble in KS23 in the last place.
Die, roachlings, die!
I spawned KS23, brake it down, got the correct frame, then reassembled it and got the right shotgun
:cl: Evie7056
fix: fixed KS23 crafting and uncrafting
/:cl:
> Fixes KS23 crafting

- code/modules/clothing/spacesuits/rig/rig_attackby.dm
- code/modules/clothing/spacesuits/rig/rig_modules.dm
- code/modules/clothing/spacesuits/void/void.dm
- code/modules/mob/living/carbon/brain/brain_item.dm
- code/modules/mob/living/carbon/carbon_powers.dm
- code/modules/mob/living/simple_animal/borer/borer.dm
- code/modules/mob/living/simple_animal/borer/borer_captive.dm
- code/modules/mob/living/simple_animal/borer/borer_powers.dm
- code/modules/organs/external/dismemberment.dm
- code/modules/organs/internal/carrion.dm
- code/modules/surgery/organic.dm
- code/modules/surgery/robotic.dm
- code/modules/tips_and_tricks/roles.dm
Borer bug fixes. Such as: 
Borer's abilities will not think it's inside the host when surgically removed.
Borer invisibility now correctly processes chemicals.
If host's head is gibbed (not cut off), borer will not die and will drop out.
Borer cannot pull big things, such as humans and closets anymore
You cannot bump-walk into borer anymore, he is smol!!!
Borer rebalance:
Borer's invisibility cost has been slightly increased.
Borer cooldowns for both paralyze and invisibility increased to 60 seconds.
Borer paralyze will now put borer out of invisibility.
Borer cannot occupy humans that SSD'd.
Borer doesn't get exp from reproducing in mobs that are not humans, though still can do that
Borer now takes 30 seconds to take control of the human instead of 10.
Other fixes:
All "detaTch" in code …
> Borer fixes + rebalance

- code/game/objects/items/devices/scanners/scanners.dm
Added a check for virtual scanners to ignore cells. Universal sollution!
Agrolytes won't loose their faith battery, hail the Lord Protector!
Run the server with upstream code and my agrolyte compitely burned out after 20 glanses
Run the server with changed code and I can stare at grass for hours!
Also checked other scanners (from med and two plant scans) - all works and requires charge
:cl:
fix: fixed agrolyte perk requiring cell charge
/:cl:
> Not-so-hot fix for agrolyte perk

- code/modules/mob/living/simple_animal/borer/borer_powers.dm
Added check for being a monkey. That's about it
Expands worm roleplay variety? IDK, we just forgot to add this check and now it's working as it was intended
- Confirming bug
Spawned a monkey and tried infesting it - fail. Issue confirmed
- Resolving issues
Dug into infest code and added check for monkey next to check for human
- Checking if issue is solved
Spawned monkey, stunned it, crawled inside
Double check. Spawned monkey and crawled inside without stun in case it was depended on stunning target
Success in both cases. Issue resolved!
:cl:
fix: Fixed borer not being able to infest monkeys
/:cl:
> Borer infest fix

- code/modules/projectiles/projectile.dm
- code/modules/projectiles/projectile/projectilegrenades.dm
grenade shells now universally qdel self on activation
this PR solves frag grenade shells overloading the server upon bump on wall.
the server being overloaded is bad.
fired all grenade shell types at walls, including frags, with expected results for each.
fix: fixed grenade shell wall bump bug
/:cl:
> frag grenade shell wall bug resolution

- code/game/turfs/simulated.dm
- code/game/turfs/simulated/wall_attacks.dm
- code/game/turfs/simulated/wall_types.dm
- code/game/turfs/simulated/walls.dm
- code/modules/materials/materials.dm
- code/modules/reagents/reagents/other.dm
This PR makes specific walls more resistant to thermite, disassembly, or being beaten apart. This PR also nerfs the overtuned weld time of unreinforced walls and adds presets that would allow someone to easily map in the now rebalanced walls.
This PR introduces more variety in wall types defenses against specific attacks, allowing for mapping in different walls for various levels of security. the Origin Reason for this PR was that Steel Reinforced Steel Walls were completely unused.
thermited steel and plasteel reinforced along with unreinforced variants of plasteel and steel walls, determining that all walls except for plasteel or plasteel reinforced variants were destroyed with one application; all variants other than steel reinforced left no girder behind.
welded steel, plasteel, …
> Wall becomes stronger

- code/modules/mob/living/simple_animal/friendly/farm_animals.dm
- code/modules/reagents/reagent_containers/food/snacks.dm
This PR makes the first few eggs start fertile, and after that eggs are less likely to be fertile depending on the number of chickens. This PR also adds a new "candling" mechanic which allows for progress monitoring of eggs.
Farming Chickens is currently rather difficult, as only one in ten eggs can hatch, and it is invisible which are which; this PR solves those issues both by making eggs start more likely to hatch, and by making it possible to tell if eggs have begun to grow.
spawned a chicken, fed it wheat, let the eggs hatch, used an unlit flare to fail to check the levels and used a lit flare on them to check the levels. After allowing flames to check the levels, used an unlit zippo to fail to check the levels and a lit zippo to check the levels.
add: you can now use …
> Egg Rebalance

- code/game/objects/items/weapons/storage/deferred.dm
On the Serb Shuttle, there's a "Communications Kit" box, that has 6 radios, and 6 tracking beacons. Beacons that let anyone instantly teleport onto the Serb shuttle as soon as Serbs spawn. This is ridiculous, and they are not used as Serbs don't have access to teleportation gear.
One Sci-bro cucking skilled Serbs by just teleporting to their shuttle and completely disabling it in 2 minutes without leaving a trace is demoralizing. Why bother doing objectives if you're just going to get shafted anyways?
Yepp it's a box with six radios in it now.
:cl:
del: Removed tracking beacons from Communications Deferred box
/:cl:
> Remove Tracking Beacons from Comms deferred crate

- code/__HELPERS/artwork_names.dm
- code/game/objects/structures/artwork_statue.dm
This is the most complete part of that silly artist pr I abandoned a while ago, polished up a bit
- Artist statues now use the sanity damage var instead of the (seemingly non-functional) component
- The sanity effects of artist statues now vary more, with a chance to harm sanity instead of healing it, a small chance to be nothing (shitty art) and a very tiny chance to be quite strong
- There is now a tell in the description of artist statues that lets you know whether they affect sanity positively or negatively
Fixes the (currently broken(?)) statue sanity effects, making artist statues a practical good beyond just immediately dumping them into the cargo bay.
The negative statues also open up a lot of opportunities for tomfoolery around putting sanity rending artwork outside people's …
> Artist statue sanity effects

- maps/CEVEris/_CEV_Eris.dmm
Maps in the new NeoTheology stamp, as well as the musician plush to the actor's room.
#8406 
Ran the game, stamped a piece of paper and played rock music with Bocchi.
:cl:
add: NT stamp now spawns in Preacher office
add: musician plush now appears in actor's room
/:cl:
> Mapping in a few unique items

- code/modules/sanity_grain/sanity_grain.dm
Ingesting Njoy now removed grain from your screen
Aside from helping Njoy actually remove the negative effects of low sanity, it also acts as a good visual indicator:
When the grain appears, you know you need to take another pill.
Run, went insane, popped a pill, all good.
:cl:
tweak: Njoy removes grain effect from low sanity
/:cl:
> Njoy makes you immune to grain

- code/modules/materials/material_sheets.dm
plasteel reduced likelyhood in building pool
glass removed from resource pool
This PR makes steel and glass more likely from those sheet spawns on tables while reducing the plasteel chance from said tables.
it also removes glass from the "resource" pool to avoid flooding it.
steel and glass should spawn in sheets more than plasteel does, and this PR ensures that.
spawned a bunch of building material spawners and found an acceptable ratio
balance: table sheets now give steel and glass more commonly, and plasteel less.
/:cl:
> table sheet rebalance

- code/_onclick/item_attack.dm
- code/game/objects/items.dm
- code/game/objects/items/weapons/tools/karl.dm
* Fixes the exploit of recharging the K.A.R.L instantly by spamming the recharge action to launch several of them in parallel. 
* Fixes the missing heightened damage of axe mode when the energy edge is turned on
* Lowers the damage of K.A.R.L in gun mode (should not hit as hard as unpowered axe mode)
* Fixes the attack behaviour of K.A.R.L in gun mode (no more swinging or double tapping, basically it now behaves as a normal gun)
* Add a new `no_swing` variable to items, analog to `no_double_tact` but for swinging instead of double tapping.
Remove recharge exploit and fix the K.A.R.L behaviour in gun/axe mode.
* Spawned a K.A.R.L
* Checked the `force` variable depending on axe/gun mode and turned-on/off.
* Checked the recharge mode by spamming Unique-action in gun mode
* Checked the attack …
> Fixing K.A.R.L mining tool

- code/modules/mob/living/carbon/human/human.dm
- code/modules/organs/external/dismemberment.dm
- code/modules/organs/internal/_internal.dm
- code/modules/organs/internal/internal_wounds/organic.dm
- code/modules/reagents/reagents/other.dm
- code/modules/surgery/organic.dm
- code/modules/surgery/robotic.dm
Basically it's other half of the https://github.com/discordia-space/CEV-Eris/pull/8413 but this time fixed and working
This PR adds more info when trying to resurect human and makes interactions with organs more logical, while fixing an array of critical bugs
Ran a test server, made a lot of immoral stuff to FBPs, monkeys and humans
Not a single connected runtime.
:cl:
tweak: Tweaked organs to be unattached by default
fix: Fixed organs counted inside person after removal in some scenarios
fix: Fixed resuscitator ignoring all damage on body upon resurrection
add: Added descriptions for resuscitator fails
/:cl:
> ErisMed fixes Season 1 Episode 2 [Resuscitated]

- code/modules/hydroponics/seed.dm
Seems like the abusers found out Botany is incredibly strong if you have patience to spend an hour or two brute forcing mutation paths or get incredibly lucky. So instead of letting someone else gut my beloved Botany of anything interesting or fun, I am nerfing the exploitative feature directly: Explosive Fruit Radius Size.
Potency affects many parts of a plant, from reagent volume to power generation. Explosive Fruit, a 1% chance mutation, is one of those affected parts. Players can, through brute force, get this trait under an hour. Then, using easy chemistry access, boost potency to 100. Then, using the guild, access to the Arbor and it's 'hidden' inventory can unlock a 300 potency disk.
Previous, 300 potency = 21x21 grid explosion / 100 potency = 7x7 grid explosion.
Now: 300 potency = …
> Reduce Potency Explosive Effectiveness (Botany)

- code/modules/multiz/structures.dm
stairs now have a massive amount of health. they shouldn't be getting blown up by a hand grenade anymore
this pull request increases the health of stairs by a large amount, making them functionally immortal. due to an oversight in recursive explosions, stairs were given the default healthbar of 100, making it so any explosion could entirely destroy a staircase and make an area inaccessible. as i do not know how to make staircases immortal, i just gave them a massive amount of health to make them effectively immortal
fixes oversight, staircases being destroyed by a single frag and being unreparable is not good
compiled, threw a dozen or so frag grenades at a staircase and it did not get destroyed. also tested with HE and Admin bomb
:cl:
balance: massively increased health of staircases so …
> Massively increases health of stairs

- code/datums/autolathe/biomatter.dm
- code/datums/autolathe/containers.dm
- code/game/objects/items/weapons/design_disks/NeoTheology.dm
- code/game/objects/items/weapons/storage/holster.dm
Lathe datums sometimes end up with lazy, copy/pasted names. Or they simply aren't descriptive enough, especially when they share an icon with another item that functions differently.
So I tried to clear up confusion that I personally had, renaming the Scabbard to Uniform Scabbard, signifying it as an accessory and thus different from the Sheath, which it shares an icon with. I also added it to the NT Pouches disk, as the Sheath was there as well as concealed holster and knife throwing rig.
I also renamed the "Parts Hardcase"s, as there were two of them on the Technomancer Advanced Tools disk with slightly different icons. One holds tools/materials, the other small parts. Hopefully this is more clear.
Identification of items at a glance is good.
:cl:
fix: fixed the names of the scabbard …
> Rename Scabbard, Hardcases

- code/modules/projectiles/ammunition.dm
This PR fixes improper magazine loading and improper sprite initialization order
bugs bad
fired Z8 with mag that was tampered with in way that reproduced bug before fix and successfully fired it
fired bullets and determined the spent and fired states were unique from each other
> fixes two errors in ammo code

- code/game/objects/items/weapons/storage/hardcases.dm
QoL: When you open the container by alt clicking, you also look inside of the crate (this is for people that are used to alt clicking containers but also good QoL for anyone in general).
Bugfix: You have to be right next to the crates to open them vs being able to do it from wherever.
You also can't be incapacitated.
Uhm, bugs bad?
"Yes"
:cl: Hopek
add: You now look inside hcases when you open them.
fix: You can't open hcases from an infinite range anymore.
fix: You can no longer open hcases when incapacitated.
/:cl:
> hcases QoL and bugfix

- code/modules/cooking_with_jane/cooking_items/cooking_containers.dm
- code/modules/cooking_with_jane/recipes/_read_me.dm
- code/modules/cooking_with_jane/recipes/recipe.dm
- code/modules/cooking_with_jane/step_defines.dm
- code/modules/cooking_with_jane/step_types/add_produce.dm
- code/modules/cooking_with_jane/step_types/use_tool.dm
- code/modules/hydroponics/seed_datums.dm
- code/modules/hydroponics/seed_packets.dm
- code/modules/reagents/bonsai.dm
Removed relic spatula scooping from containers.
Adjusted cwj recipes readme to reflect usage of kitchen_tags.
Honored kitchen_tags for mushroom, which is used by children as well, changing recipes and "mushrooms" tags to "mushroom".
Inherited quality modifier changes so player action is more impactful.
Added purposeful misuse of tools, so player action is more impactful.
Confusion removal good. Player feeling able to measure their personal impact onto something, also good.
Tested locally, was able to use reishi, libertyduff, chantrelle, and other mushroom children in place of "mushroom".
Tested tool behavior as well.
:cl:
add: Misusing tools on recipes negatively impact food quality
tweak: Changed "Mushrooms" to "Mushroom" so the cooking tracker stops saying "add a mushrooms"
balance: …
> Cooking Adjustments 2

- code/modules/mechs/mech.dm
- code/modules/mechs/mech_interaction.dm
- code/modules/mechs/mech_life.dm
Adds a parameter to eject() on living/exosuit that is set to TRUE when the mech is destroyed. Any pilots ejected when TRUE are moderately injured and briefly knocked down.
You can't just walk away from a mech wreckage unscathed.
Called death() on a mech and can confirm you come out injured and knocked down.
:cl:
balance: Pilots crawl out of mech wreckages with injuries.
/:cl:
> Pilots of mechs that break apart are injured

- code/game/objects/items/weapons/stunbaton.dm
- code/modules/clothing/spacesuits/rig/rig.dm
- code/modules/power/apc.dm
Typo fix from saboutage to sabotage
Typo fix
It's descriptive text without special effects. None needed.
:cl: Xoxeyos
spellcheck: Sabotage yourself, NOW! Saboutage is now sabotage.
/:cl:
> Sabotage yourself now

- code/controllers/subsystems/statpanel.dm
- code/game/antagonist/antagonist_factions.dm
- code/game/antagonist/station/revolutionary/excel_faction.dm
- code/game/verbs/ooc.dm
Returned the "Fix Chat" verb that was accidentally removed (probably assumed it to be redundant because of another "Fix Chat" verb that we have, but which is unticked in .dme, can't really tell by now).
Changed the way (mostly broken) icons of on-turf items are referenced, to be in line with RIG module icons, since these apparently worked well on live server.
Fixes good.
Checked that "Fix Chat" verb appears in OOC tab, activates and works as intended (reverted to old chat and back to goon chat).
Issues with on-turf Icons is something that only appeared on live server, I am literally unable to reproduce it on local server, both before and after the changes it worked well for me.
:cl:
fix: Returned "Fix Chat" verb to it's proper place in OOC tab
/:cl:
> Stat panel fixes

- code/game/gamemodes/storyteller.dm
This PR increases the Chaos Level once per hour.
Destination? Death.
tested the chaos level increase timing- it does not increase the level roundstart, but does increase it an appropriate cycle.
:cl:
balance: Bluespace Chaos now infuses the ship over time.
/:cl:
> chaos level now automatically increases hourly

- code/game/gamemodes/storyteller.dm
Reverts discordia-space/CEV-Eris#8488
This PR won't fix the issue of greenshifts on Eris and it will help guarantee a boring TDM-fest later on in the round. (aka 4 people roll traitor and decide to buy all the default gear they can through the uplink instead of actually prepping)
Greenshifts are a player issue created by lack of gimmicks , some gameplay aspects contribute to this , most notably the lack of content relating to non-combat , research and exploration.
> Revert "chaos level now automatically increases hourly"

- code/modules/mob/living/carbon/human/examine.dm
- code/modules/mob/mob_grab_specials.dm
You can see in the description of the lowborn perk that it implies the people who have it are downtrodden, poor, and seen as filth. This is not really common because they get lost in the crowds, this lets them have an extra description line if their face is uncovered. 
Likewise with nobles.
Having only a third of your sanity remaining is visible to others if your face is exposed, dilated pupils, shifty eyes, weird cast to face.
Having less than five percent of your sanity left is very easily noticeable, as well, in the same conditions.
In any case, wearing a mask makes all of these not noticeable.
Tested.
:cl: Buttcrack Berry Picker
add: Added visible poorness, nobility, low sanity.
/:cl:
> Adds being visibly insane, lowborn or noble.

- code/ZAS/Turf.dm
- code/controllers/subsystems/air.dm
- code/game/objects/items/weapons/grenades/grenade.dm
- code/modules/admin/admin_verbs.dm
Added a way for admins to unfuck the atmos.
Sometimes it's nice to have an option like that.
Also Jeff requested it.
Flooded hallways with plasma.
Watched it all burn for a moment.
Pressed "Fix air" button.
Observed plasma fires disappear and air alarms clearing.
:cl:
admin: Added "Fix air" button to "Admin" tab
/:cl:
> Add "Fix air" proc

- code/modules/mechs/equipment/utility.dm
Properly null-checks a object before doing other checks.
Its good for the devs!
Ran a local server a few times , was unable to get the forklift ejecting null runtime
:cl:
fix: Fixed a runtime relating to forklift bars
/:cl:
> Fixes a silly forklift runtime

- code/game/atoms_movable.dm
- code/modules/unit_tests/step_override.dm
This PR fixes some cases in which SSchunks mobs were duplicated
BUG fix.
Ran a local server , tested falling down , examinations/speaking was no longer doubled.
:cl:
fix: Fixed movement_signals being duplicated when a atom that falls/moves is re-located by other atoms.
/:cl:
> Fixes SSchunks duplication cases (Stairs , Fallingoff)

- code/modules/core_implant/cruciform/rituals/group.dm
Two group litanies (ROB and VIG) had the same name, which lead to ROB litany not being displayed in the book.
This renames VIG litany to Chant of Observance
Fix
:cl:
fix: group litany for robustness now properly shows up in the book
/:cl:
> Canto of courage fix

- code/modules/core_implant/cruciform/rituals/group.dm
Group statboosting litanies now send to each participant a message that their stats were increased.
Clueless believers will no longer think that praying to God is useless.
Performed every group statboosting litany.
:cl:
tweak: group litanies show message when stats are increased
/:cl:
> Group litanies feedback

- code/game/machinery/excelsior/redirector.dm
Blocks spamming the action from causing multiple reboot requests (fucking spammers , when do we get proper do_Afters????)
fIX
Ran a local server and tried to spam the actions again, the attempts after the first one were always blocked.
:cl:
fix: Fixed rebooting the excelsior redirector multiple-times.
/:cl:
> Fixes excelsior rebooter duplication

- code/modules/mob/living/carbon/human/life.dm
- code/modules/organs/internal/_internal.dm
- code/modules/organs/internal/internal_organ_processes.dm
If a human drops below 40% blood, they take oxygen damage over time at a rate high enough to outpace natural recovery.
This leads to unconsciousness followed by death. 
Increases lethality of bleeding wounds. This allows bullets to kill, while still allowing medical attention to delay the target's demise.
Increased damage due to bloodloss was tested and timed on multiple dummies. A set amount of blood was drained, with me continuously looking at the amount of oxygen damage through VV, and time to die compared to without the increased damage measured using a stopwatch.  
Blood loss wounds was tested by draining 420 units of blood from a human alongside giving the human a dose of dexalin. The dexalin would prevent death from suffocation, allowing enough time for the wounds to appear on a …
> Blood loss fix

- code/game/machinery/excelsior/redirector.dm
I forgot that deltimer() is not done by reference ((
Bug fix
Local tested.
:cl:
fix: Fixed excelsior redirector not getting rid of reboot timers properly.
/:cl:
> Fixes excel redirector again

- code/game/objects/structures/low_wall.dm
- code/game/turfs/simulated/wall_attacks.dm
- code/game/turfs/simulated/wall_icon.dm
- code/game/turfs/simulated/walls.dm
- code/modules/mob/mob_grab.dm
I've been told a couple of days ago that full-tile windows can't be knocked at, can't tell lasers and bullets apart, and that low walls are not grab-fu certified.
Also I've apparently forgot to write low wall description, oopsie.
Additionally, wall icon updates are somewhat more customizable now, with appearance cache supporting use of multiple .dmi files for walls (where icon names match these from other used .dmi), as well as custom alpha value for windows based off the wall type.
Fixes cool.
Customization changes made on request from a downstream.
Knocked on a window with harm and help intents.
Touched a low wall with no window.
Touched a regular wall.
Shot a window with a laser gun, observed laser pass right through.
Shot a window with ballistic gun, observed bullet impact the window. …
> Fix window interactions

- code/_onclick/hud/HUD_element/HUD_element.dm
- code/_onclick/hud/HUD_element/external_procs.dm
- code/datums/mutable_appearance.dm
- code/modules/mob/inventory/slots.dm
Fixes hopefully the last bug caused by hosting Eris on 515 version of BYOND.
It's about clothing sprites not being updated properly.
Also there were changes to `mutable_appearance` in BYOND about two weeks ago, some of the related code didn't compile and is now being removed.
Fixes good.
Launched local before the fix, observed the bug.
Applied code changes.
Launched local and observed no bug.
Messed with reagent containers a bit, made sure their overlays aren't looking funny (since "icons and reagent overlays tweaks" was the stated reason for adding the now removed code).
:cl: SirRichardFrancis, MLGTASTICa
fix: Fixed clothing-related case of 515 incompatibility.
/:cl:
> Better 515 compatibility

- code/game/machinery/vending.dm
When a human without a cruciform tries to buy something from Theo-Mat they are met with an unclear message which says "Unauthorized Access", it hints that the issue is their ID card.
Unclear messaging keeps players thinking that it's a bug.
Yes
:cl:
spellcheck: Theo-Mat now has a bit more clear messaging.
/:cl:
> Small Theo-Mat text change.

- code/modules/clothing/gloves/miscellaneous.dm
- code/modules/clothing/head/armor.dm
- code/modules/clothing/shoes/jobs.dm
- code/modules/clothing/suits/armor.dm
Blacklists Excelsior Excelsior's heavy armor's pieces from spawning per request and as labeled as an oversight.
It stops Excelsior's heavy armor's pieces from spawning at all and being too easy to obtain except for Excelsior infiltrations.
Queries of the described items.
:cl:
fix: Excelsior's heavy armor's pieces are blacklisted.
/:cl:
> Blacklists Excelsior's heavy armor's pieces from spawning

- code/controllers/subsystems/staverbs.dm
- code/game/objects/items/weapons/material/shards.dm
- code/game/turfs/simulated/floor.dm
Fix for ripped off with ROB tiles disappearing. Now they drop metal shards co-responding to what materials they made of.
Also metal shards now can be merged with hammering and plastic shards can he glued/taped together
Materials now won't just vanish in the air and torn tiles can be recycled with hammers or more efficiently with autolathe
Torn off few tiles near cryo as a BST and few plastic tiles in kitchen, then as a technomancer:
- Tried welding together metal shards. Got fail message suggesting using a different tool. Expected result achieved
- Tried hammering metal shards together. Two of 3 shards merged into two steel sheets taking some material from the last shard. Expected result achieved
- Tried welding together plastic shards. Got fail message suggesting using a different tool. …
> Floor-ripping fix

- code/game/objects/items/_inventory.dm
- code/game/objects/items/devices/lighting/toggleable/flashlight.dm
- code/modules/mob/living/life.dm
- code/modules/mob/living/living_defense.dm
- code/modules/mob/living/silicon/robot/life.dm
- code/modules/mob/login.dm
Makes sure action buttons are added and removed only when it is actually necessary, not every single `Life()` tick.
Better performance.
Equipped, dropped, and activated items with action buttons (voidsuit and a flashlight) to see if they work correctly.
Hosted via Dream Daemon, reconnected after equipping voidsuit and a flashlight, observed action buttons being visible on login.
:cl:
code: Optimized action buttons
/:cl:
> Optimize action buttons

- code/modules/reagents/reagents/medicine.dm
Some overdose procs were missing `ishuman()` checks, which would runtime when the reagent was present in non-humans.
Bug fix
Injected each affected reagent into a roach.
:cl:
fix: Added missing ishuman() checks to overdose procs
/:cl:
> Fixes overdose runtime

- code/_onclick/hud/screen_objects/base_screen_objects.dm
This PR unifies sanity button interaction between Liberty and Eris HUDs, but mainly fixes first one not opening new stats menu.
Working and unified UI iterations are always good, duh.
Launched game and clicked on sanity hud button, all good.
:cl:
add: unified sanity button interaction between Liberty and Eris HUDs, both list desires now.
fix: fixed Liberty HUD sanity button not opening sanity UI.
/:cl:
> Fix Liberty HUD not working & unify functions

- code/game/machinery/door_control.dm
- code/game/machinery/doors/blast_door.dm
Fiexs the issue that tends to occur during eris rounds a lot since we have a lot of rounds during that timestamp
They work.... at last... even at 1:00 EEST
I didnt have the time to test it nor the resources to emulate time ,but its preety obvious what was happening with how this was not a reproducible bug most of the time.
:cl:
fix: Fixed Blast Doors refusing to work past 24:00 GMT
/:cl:
> Fixes shutter buttons breaking for rounds that play near 24:00 GMT and reach 00:00

- code/datums/autolathe/tools.dm
- code/game/objects/items/weapons/design_disks/technomancers.dm
- code/game/objects/items/weapons/tools/tape.dm
Add superglue to 'Technomancers IJIRO-451 Advanced Tools' disk.
Change superglue's materials from 30 biomatter to 20 plastic, the same as fiber tape, making it printable by all fabricators.
Change superglue's adhesive stat from 40 to 50. This makes superglue contribute 3 mechanical stat instead of 2 to the techno-tribalism enforcer, allowing technomancers to create 15-mechanical oddities at roundstart.
I specifically chose superglue and not fiber tape because fiber tape's current stats would let technomancers create 30-mechanical oddities which I think is too drastic of a buff.
Mechanical is an important stat to technomancers, yet it's the only one they have no reliable access to. This PR would finally let them create oddities with mechanical stats without relying on finding some of the …
> Superglue is printable with an advanced tools disk + superglue buffs

- code/modules/clothing/head/armor.dm
The insulated technomancer helmet spawns with one of two icons currently. This PR lets the icon be swapped to the other and vice versa with a wrench.
I don't like the goggles appearance. Let people choose how they want to look, instead of relying on RNG.
Used a wrench on the helmet. Works.
:cl:
tweak: insulated technomancer helmet's appearance can be changed with a wrench.
/:cl:
> Insulated technomancer helmet's icon can be swapped with a wrench

- code/_onclick/hud/screen_objects/base_screen_objects.dm
- code/game/objects/items/weapons/storage/storage.dm
Adds the NO_CLIENT_COLOR appearance flag to most HUD elements, so that client color (oborin syndrome, mostly) doesn't affect their color. Held and stored items are still affected, but the HUD surrounding them is not.
Colorblindness and otherwise modified vision should affect things you see, not make it hard to tell if you're in pain, if you're hungry, how much insight you have, what hand you're using... etc. These are visual representations of a character's non-vision and non-hearing senses, not something that modified vision should affect.
:cl:
tweak: Things that affect your screen color no longer affect your HUD
balance: Oborin syndrome no longer affects your HUD
/:cl:
> Client color no longer affects the HUD

- code/modules/projectiles/ammunition.dm
- code/modules/projectiles/guns/projectile.dm
This PR makes ammo clusters regain the functionality of reloading bolt-actions lost in PR #8386 as a result of accidentally disabling occult code that lead to its proper function.
Bug Bad
reloaded a Kadmin with a clump of ammo and fired successfully until empty, twice.
fix: loading guns by hand from ammo groups now works again.
/:cl:
> Finally fixes bolt-actions

- code/modules/mob/living/carbon/human/human_species.dm
Mannequins are full fledged mobs that processed damage, life ticks, and sanity. They suffered breakdowns. They were impacting server performance. Basically anytime a player opened their character sheet, it would make a mannequin. Sometimes, multiple mannequins depending on how many character sheets they opened. This reduces their impact to a fraction of a fraction of their previous impact.
Optimization good.
[Testing video](https://puu.sh/Kq2I3/ca50a69844.webm), as it was too long.
:cl:
fix: Mannequins no longer process Life() or sanity, nor appear on Baptismal record
/:cl:
> Mannequins no longer process or appear on baptismal record

- code/game/objects/items/stacks/rods.dm
- code/game/objects/items/stacks/stack.dm
- code/modules/materials/material_sheets.dm
- code/modules/projectiles/ammunition.dm
A collection of adjustments to stacks and ammo boxes to make it harder to deal hundreds of damage by dropping rods and emptying ammo boxes onto people's heads:
- Dumping ammo from a box stacks it instead of splitting it into hundreds of separate items
- Ammo piles do not deal damage when falling on people unless there are at least 10 casings in the pile.
- Stacks of rods or material sheets will merge with other stacks on their tile when created and when crossing them.
- Damage from stacks falling on someone scales with the amount in the stack
Of note:
- Osmium deals more damage than other materials when falling on people.
What this PR does NOT do is fix the root problems with erismed that make this change necessary. Erismed runs into serious issues when dealing with lots of small chip …
> Make it harder to decapitate people with rods and ammo boxes

- code/__DEFINES/chemistry.dm
- code/__DEFINES/maths.dm
- code/modules/organs/internal/_internal.dm
- code/modules/organs/internal/internal_wounds/_internal_wound.dm
- code/modules/organs/internal/internal_wounds/organic.dm
- code/modules/reagents/reagents/medicine.dm
- code/modules/reagents/reagents/toxins.dm
This PR finalizes #8548 by making `ROUND_PROB` function properly and adds a type of wound that Amatoxins can use.
The wound, classified as "genetic damage", is cured by genetic heals, and is of Aggravated class, without passive progression.
Amatoxins apply this wound to the kidneys/liver once every five minutes, leading to a slow death that begins with a silent progression, and continues to progress in a painful manner once ten minutes pass, until the liver and kidneys are dead, and its pitifully low standard toxin strength finishes the job.
The necessary strength to start dealing damage has been reduced due to the re-introduced ability of ROUND_PROB.
Additionally, rectified inconsistent organ pain messages.
Eating bad mushrooms should eventually lead to your demise. Damage should Damage. …
> Poison/Wound Update/Fix

- code/game/objects/structures/cyberplants.dm
This lets you Alt click a cyberplant to change the plant, instead of it changing every time you choose a new color
QoL, and what if you wanted a certain design? It would be better to just alt click instead of clicking then click ok on the color picker.
https://github.com/user-attachments/assets/1219c0dc-f204-4084-ac92-5ec1c6fa1bc4
:cl:
add: You can now change the plant on a cyberplant by alt clicking it
fix: Changing a cyber plant's color no longer changes the design with it
/:cl:
> Better cyber plant functionality

- code/modules/mob/living/living.dm
This PR makes rejuvenation clear the Hallucinatory damage type.
Rejuv should fully heal a mob. Hal-Loss kills basic mobs.
Gave two Panzers separate factions and let them duke it out, constantly reviving them, with no build-up of halloss damage.
fix: Reviving superior mobs should now function properly.
/:cl:
> rejuvenate now clears hallucinatory damage

- code/modules/projectiles/projectile/bullets.dm
- code/modules/projectiles/projectile/bullettypes.dm
- code/modules/projectiles/projectile/fragment.dm
This PR replaces pellet count decreasing with distance with a cloud of pellets diverging as they move
Shotguns should live!
Fired shotgun at window and buckled to chair Disciple from a distance, fired shotgun at distant tile, point-blanked Disciple with shotgun, found concerning issues with stinger grenade but as normal frag grenades worked fine, concluded it probably isn't pellets doing it. Additionally shot fuhrer to death with an appropriate number of buckshot shells fired.
balance: fix: Shotgun spreadshot now actually spreads rather than weakening.
/:cl:
> pellets now spread via trajectory

- code/modules/core_implant/cruciform/rituals/group.dm
Sanctify was crashing people, and turned the books into cognito hazards. For some reason, moving it above Crusade in the same file fixes this. I also clarified that Sanctify doesn't need an acolyte or preacher, and Crusade needs at least six participants while I was dubbing around.
Bugfixes good. Clarity consistency also good.
[EzLODLwXpI.webm](https://github.com/user-attachments/assets/a7d656a9-5df2-4ab5-949f-c46d1bb55088)
:cl:
tweak: clarified Sanctify group litany not needing an acolyte or preacher
tweak: clarified Crusade group litany needing six participants
fix: fixed Sanctify group litany from crashing
/:cl:
> Fix Sanctify group litany, clarify descriptions

- code/game/machinery/doors/door.dm
- code/game/objects/items/stacks/stack.dm
- fixes stack duplication when splitting into an empty hand (newly split stack was immediately merging with the old one causing them to add their amounts)
- fixes stacks with 0 sheets forming when merging with another stack
- properly updates icons for freshly split stacks
Fixes good.
splitted and merged stacks with an empty hand and the split verb to make sure that the amount of sheets doesn't increase
:cl:
fix: Stacks can no longer be duped by splitting with an empty hand, no more 0 sheet stacks, icons update properly
> Stack fixes

- code/modules/mechs/equipment/medical.dm
- code/modules/organs/internal/_internal.dm
This PR ensures that upon a limbgib or other removal, the produced organs do not runtime on process. Additionally, Mech Sleepers no longer runtime when destroyed with no occupant.
Runtimes Bad.
Dismembered monkey before and after fix, runtimed before but not after.
fix: Removed Organs should now process properly
/:cl:
> Limbgibs no longer runtime and neither does Mech Sleeper

- code/modules/mob/living/carbon/superior_animal/roach/ai.dm
This PR disables roach screams from the dead.
Were they really dead before? Could you be SURE?
punched Kampfer to death, punched it some more, it didn't scream when punched after death.
del: Roach Ghosts no longer scream at you for smacking their dead bodies.
/:cl:
> dead roaches can no longer scream in rage

- code/modules/organs/internal/internal_organ_processes.dm
- code/modules/organs/internal/internal_wounds/_internal_wound.dm
- code/modules/organs/internal/internal_wounds/organic.dm
- code/modules/organs/internal/liver.dm
This PR adds a Liver-specific chain of Tox wounds, that being the Hepatitis->Fibrosis->Cirrhosis chain. Hepatitis cures quickly when removed from the source of the inflammation, Fibrosis cures slowly, and Cirrhosis does not cure at all without an auto-doc. Additionally, Brute wounds cure slowly when the Liver is not under threat by toxicity.
Fibrosis and Brute regeneration are accelerated by Anti-Tox.
Providing a self-regenerating minor buffer for liver damage is beneficial to the place of toxins in the game.
Confirmed effect with Chlorine, low doses of Blattedin, and a bottle of vodka on separate disciples- effects were acceptable.
add: Liver now self-regenerates while under toxic capacity, at a rate boosted by anti-tox.
/:cl:
> Adds Hepatitis and Liver Regeneration

- code/__DEFINES/jobs.dm
- code/game/jobs/jobs.dm
- code/modules/client/preference_setup/occupation/occupation.dm
runtime fixed in ckey playtime checking
This PR ensures that allowing guests allows them to select a job, and updates the guest job-ban list for eris.
The current situation incentivizes permitting the activity of guests, and currently the config doesn't really work.
Locked myself out of BYOND, edited job code until it worked.
fix: config: guest mode no longer breaks job selection.
/:cl:
> Guest Config now functional

- code/modules/mob/living/simple_animal/friendly/mouse.dm
This PR allows mice to survive the 30 minute mark.
Mouse can live, as a treat!
Before the PR, testing shows that once you leave a mouse alone to think about life for a brief time after it's been thirty minutes, it will shrivel up into a skeleton. After the PR, testing shows both mice tested with, brown and gray, survived.
Killed Tom, Confirmed Tom became remains thirty minutes later.
add: Mice can now live.
/:cl:
> mouse lifetime limit fixed

- code/modules/mining/drilling/deep_drill.dm
- code/modules/mining/machine_processing.dm
- code/modules/random_map/automata/caves.dm
This PR makes the deep drill wait until mapload to locate the cave generator obj. Additionally, multiple ore processors can function in the same game, and the cave generator can generate oredata without needing the assistance of an ore processor.
Mining is a good feature and should work.
Before fix:
Failed to wrench deep drill, runtime appeared.
Visited asteroid, walls appeared, floors appeared, ore did not.
After fix:
Used deep drill, entered cave successfully, fought golems successfully.
Visited asteroid, walls appeared, floor appeared, some walls were made with ore.
> Mining generation fixes

- code/modules/mob/living/carbon/superior_animal/roach/roach.dm
- code/modules/mob/living/carbon/superior_animal/roach/roachmind.dm
- code/modules/mob/living/carbon/superior_animal/roach/types/kaiser.dm
This PR provides a variety of roachmind fixes, which may or may not prevent a runtime. Additionally, Kaisers now manage their overmind when they die.
Improvements Good
Triggered Kaiser event twenty times and Infestation event 40 times, no roachmind-related runtimes found.
Killed Kaiser without fuhrer in Overseer swarm- Overseer was destroyed; with fuhrer, fuhrer gained leadership instead.
> Unknown Roachmind Fixes

- code/game/objects/items/weapons/candle.dm
- code/modules/mob/inventory.dm
- code/modules/reagents/reagents/toxins.dm
This PR ensures that calling dropped() without a mob parameter does not happen, and therefore the runtime created on doing so does not appear.
Runtimes Bad
Held candle before and after fix- fix removed runtime. injected Disciple with advanced mutation toxin before and after fix- fix fixed dropped() call runtime, but did not affect unrelated UnregisterSignal null target runtime.
fix: Holding a candle as it runs out of wax now functions properly.
/:cl:
> Dropped parameter fixed

- code/modules/sanity/breakdowns.dm
This PR makes the Hysteric and Self-Harm breakdowns nullcheck after their inbuilt delay. This is necessary because on the event the human they are attached to is destroyed, their references become invalid, while their spawn() calls will still continue.
Runtimes are BAD
Before fix:
Spawned Disciple, force-gave Hysteric breakdown, deleted Disciple, waited, runtime.
After fix:
Spawned Disciple, force-gave Hysteric breakdown, deleted disciple... waited... runtime did not appear!
fix: self-harm and hysteric breakdowns no longer cause a runtime when they begin shortly before the associated human is obliterated.
/:cl:
> hysteric and selfharm breakdowns now nullcheck after delay

- code/modules/mob/mob_grab_specials.dm
- code/modules/organs/wound.dm
This PR swaps the effect of bleeding limb help-grab from lowering the wound stage and bleed timer to clamping the wounds and stopping the bleeding via Clamp effect. Additionally, the re-open wounds proc now undoes clamped status. This replaces buggy code that resulted in runtimes via direct wound stage meddling with code that does not runtime.
Clamped wounds shouldn't be immune to bleeding, and Wound Stage should not be directly manipulated.
Shot disciple with slaughtomatic after punching them, before fix pressuring their wounds runtimed, after fix it did not.
balance: Clamped wounds do not stay clamped when re-opened.
balance: Pressuring wounds now clamps the wound until re-opened.
/:cl:
> Bleeding Limb Help-Grab rework and Wound-Clamping nerf

- code/__DEFINES/misc.dm
- code/game/objects/items/weapons/storage/wallets.dm
- code/modules/mining/abandonedcrates.dm
- code/modules/mining/coins.dm
- code/modules/mining/money_bag.dm
This PR modernizes Coins, making them more usable in the current economy of Eris.
This is done by giving them two vars- Price Tag and Matter, and by replacing the useless Iron Coin with an identically appearing Plasteel Coin. Additionally, Money Bags were made more functional, although they were not made obtainable.
The Material Barter Economy would benefit from being able to use the type of coin found in Wallets to craft items. Coins should have value.
Spawned Plasteel Coin, Moneybag, and Vault Variant Moneybag, added and removed coins from Moneybag with resulting coins dropped on turf.
add: Added Plasteel Coin
del: Removed Iron Coin
fix: Coins now moderately valuable for use and trade.
spellcheck: Platinum coin no longer spelled as Platunum coin.
code: Moneybag no longer …
> Coins Modernized

- code/game/objects/items/weapons/implant/implants/carrion/identity_spider.dm
- code/modules/mob/holder.dm
- code/modules/mob/living/simple_animal/spider_core.dm
- code/modules/organs/internal/carrion.dm
- code/modules/organs/internal/internal_organ_processes.dm
This PR updates the Carrion maw in a few ways.
-  The maw now applies chemgain as a multiplier to gained carrion chems and not just nutriment.
-  The code intended for cleanable puddles now define their behavior instead of overriding solid biomass puddle effect.
-  Eating a carrion core now transfers all of the core's disguises.
- Having maxed carrion hunger now increases human hunger, or if there is nutriment in the stomach, absorbs an equivalent amount.
- Carrion maw can now eat from holders.
Additionally:
- Spider core simple mob now drops the carrion core organ in a dead state when killed instead of gibbing, and can be picked up.
- Carrion organs are now worth more bio-tech than normal.
- A spawn call has been replaced with a timer.
Carrion can be better, and now it is.
Confirmed …
> carrion maw updated

- code/modules/mob/living/carbon/taste.dm
- code/modules/reagents/reagent_containers/food/snacks.dm
This PR ensures that even if nutriment doesn't have a taste, drinking it still works. This is necessary because nutriment can be created without a taste as a decay product of roach chems.
Additionally, this PR adds nutriment data to the flat dough item, rectifying its lacking taste.
Nutriment is made to be eaten.
Heated Diplopterum to its decay threshold, separated nutriment, drank it after fix, intended result occurred.
Cooked Spider Meat Pie, ate from Spider Meat Pie, runtime did not occur.
fix: nutriment made via roach chem decay is now fully drinkable.
fix: Flat Dough and derivatives are now more edible.
/:cl:
> tasteless nutriment no longer runtimes

- code/modules/mob/living/carbon/human/human_defense.dm
This PR fixes a type mismatch I made when setting the material of shrapnel from bullets.
Materials should not be strings.
Shot Disciple with SAW for a bit, then rejuvenated Disciple, releasing the shrapnel. Material of shrapnel was a datum.
> type mismatch fixed
